### PR TITLE
Fix unique constraint on compressed tables

### LINKED ISSUE #5553: [Bug]: Unique constraints are not always respected on compressed tables
### What type of bug is this?

Incorrect result

### What subsystems and features are affected?

Compression

### What happened?

Successfull insert into compressed chunk which violates unique constraint

Unique constraint violation is detected during decompression.

https://github.com/kgyrtkirk/reprox/blob/compressed-unique-err/unique_err.pgsql

### TimescaleDB version affected

current main

### PostgreSQL version used

15.2

### What operating system did you use?

docker

### What installation method did you use?

Docker

### What platform did you run on?

Not applicable

### Relevant log output and stack trace

_No response_

### How can we reproduce the bug?

```bash
https://github.com/kgyrtkirk/reprox/blob/compressed-unique-err/unique_err.pgsql
```

### PR DESCRIPTION
**Pull request by kgyrtkirk**
Inserting multiple rows into a compressed chunk could have bypassed
constraint check in case the table had segment_by columns.

Fixes #5553

### CODE REVIEW

File: test/pg_regress.sh [hunk 1]
```diff
@@ -30,6 +30,9 @@ SKIPS=${SKIPS:-}
 PSQL=${PSQL:-psql}
 PSQL="${PSQL} -X" # Prevent any .psqlrc files from being executed during the tests
 
+export PSQL
```
Comment (svenklemm) [inline test/pg_regress.sh:33]: seems like this is an unrelated change not belonging to this PR

File: tsl/test/expected/compression_errors.out [hunk 2]
```diff
@@ -3,6 +3,7 @@
 -- LICENSE-TIMESCALE for a copy of the license.
 \set ON_ERROR_STOP 0
 \set VERBOSITY default
+\set ECHO none
```
Comment (svenklemm) [inline tsl/test/expected/compression_errors.out:6]: Why are you setting this?

File: test/pg_regress.sh (hunk 1 above)
Comment (kgyrtkirk) [reply test/pg_regress.sh:33]: these changes enable me to debug tests - removed it

File: tsl/test/expected/compression_errors.out (hunk 2 above)
Comment (kgyrtkirk) [reply tsl/test/expected/compression_errors.out:6]: without this all the satements loaded from `test_utils.sql` would be listed in the `out` file.

see the first few line of changes in `tsl/test/sql/compression_errors.sql` - it turns back echo after the file is loaded.

File: test/pg_regress.sh (hunk 1 above)
Comment (svenklemm) [reply test/pg_regress.sh]: You can put it in separate PR or at least separate commit.

File: tsl/test/expected/compression_errors.out (hunk 2 above)
Comment (svenklemm) [reply tsl/test/expected/compression_errors.out:6]: should this be part test_utils.sql then?

File: src/nodes/chunk_dispatch/chunk_dispatch.c [hunk 3]
```diff
@@ -148,8 +147,17 @@ ts_chunk_dispatch_get_chunk_insert_state(ChunkDispatch *dispatch, Point *point,
...
+	else if (cis->rel->rd_id == dispatch->prev_cis_oid && cis == dispatch->prev_cis)
+	{
+		/* got the same item from cache as before */
+		cis_changed = false;
+	}
 
-		if (found && ts_chunk_is_compressed(chunk) && !ts_chunk_is_distributed(chunk))
+	if (found)
+	{
+		Chunk *chunk = ts_chunk_get_by_id(cis->chunk_id, true);
```
Comment (akuzm) [inline src/nodes/chunk_dispatch/chunk_dispatch.c:159]: This lookup is expensive to do per-row. Would be good to somehow merge with the above lookups, or cache it in the chunk insert state, or maybe check `cis->chunk_compressed` and `cis->chunk_data_nodes` first.

**Review by akuzm — APPROVED** [review]

File: src/nodes/chunk_dispatch/chunk_dispatch.c (hunk 3 above)
Comment (mkindahl) [inline src/nodes/chunk_dispatch/chunk_dispatch.c:159]: Could you add a comment explaining why you need to re-fetch the chunk using the chunk_id from the insert state. It is not very clear why this is necessary.

**Review by mkindahl — COMMENTED** [review]
Would be good if you can split up the commit comment into a description of what the problem is and what you do to solve it. It's a little hard to read and understand as a reviewer.

You also need to add a changelog entry.

File: test/pg_regress.sh (hunk 1 above)
Comment (kgyrtkirk) [reply test/pg_regress.sh]: I will - and there I'll explain how this could be usefull

File: tsl/test/expected/compression_errors.out (hunk 2 above)
Comment (kgyrtkirk) [reply tsl/test/expected/compression_errors.out:6]: Great idea! as this change will affect other tests as well - I'll open a separate PR for that!

File: src/nodes/chunk_dispatch/chunk_dispatch.c (hunk 3 above)
Comment (kgyrtkirk) [reply src/nodes/chunk_dispatch/chunk_dispatch.c:159]: For every new chunk the `cis` code above reads the chunk twice...the api contract of the `decompress_batches_for_insert` is to give a `Chunk` to it.

I think instead of storing random attributes of the `Chunk` struct - it would be better to store a more lightweight version of it - even more because down below where only pretty small part of the `Chunk` struct is actually being used - meanwhile where scankey is being constructed the relid for the hypertable was not available easily

I've changed to use `cis->...` for now and load the `Chunk` right before calling `decompress_batches_for_insert`

Comment (kgyrtkirk) [reply src/nodes/chunk_dispatch/chunk_dispatch.c:159]: the `decompress_batches_for_insert` needs it - so from now on every row inserted will need to have a `Chunk` struct.

the instructions above `ts_set_compression_status` is essentially bypasses the cache; and loads a new instance see [here](https://github.com/timescale/timescaledb/commit/84b6783a199c37bff6b36a3c0940915e5ca569ce#diff-7a9e9490252947c6a5c13cab7ce5ce5a2b6b67a5820c499b74b93f29a55977caR147) - so I'm not sure if we could trust the cache behind `ts_hypertable_find_chunk_for_point` ; or that will just cause trouble? (fyi: @antekresic)

for now I've decided to:
* lazy-init the `chunk` field
* load it with `ts_chunk_get_by_id` for now - in case its not already available

Comment (mkindahl) [reply src/nodes/chunk_dispatch/chunk_dispatch.c:159]: Please add a comment describing the situation. It will help your future self understanding the rationale behind it.

**Review by mkindahl — APPROVED** [review]
