### PR TITLE
Don't dump unnecessary extension tables

### LINKED ISSUE #5449: [Bug]: pg_dump fails due to permission issue in 2.10.0
### What type of bug is this?

Unexpected error

### What subsystems and features are affected?

Backup

### What happened?

PR #5218 restricts the permissions to the `_timescaledb_internal.job_errors` table so that the users can only view the job
errors log through the view `timescaledb_information.job_errors`. The `_timescaledb_internal.job_errors` is also configured to be included in a pg_dump. But due to the above said permissions updates, pg_dump is unable to lock the table during backup. It fails with the following error :

```
pg_dump: error: query failed: ERROR:  permission denied for table job_errors
pg_dump: detail: Query was: LOCK TABLE _timescaledb_internal.job_errors IN ACCESS SHARE MODE
```

If the `timescaledb_information.job_errors` is to be restricted for the users, it should be configured to be excluded from pg_dump as well.

### TimescaleDB version affected

2.10.0

### PostgreSQL version used

14.5

### What operating system did you use?

Ubuntu 22.04

### What installation method did you use?

Source

### What platform did you run on?

On prem/Self-hosted

### Relevant log output and stack trace

```bash
$ pg_dump -U testuser -v testdb
pg_dump: last built-in OID is 16383
pg_dump: reading extensions
pg_dump: identifying extension members
pg_dump: reading schemas
pg_dump: reading user-defined tables
pg_dump: error: query failed: ERROR:  permission denied for table job_errors
pg_dump: detail: Query was: LOCK TABLE _timescaledb_internal.job_errors IN ACCESS SHARE MODE
```

### How can we reproduce the bug?
Setup the user and database
```sql
-- Create a database and a new user
CREATE DATABASE testdb;
CREATE USER testuser;
GRANT ALL ON DATABASE testdb TO testuser;
\c testdb
GRANT ALL ON SCHEMA public TO testuser;
-- Connect to testdb as testuser
\c testdb testuser
-- Create the timescale extension and table
CREATE EXTENSION timescaledb;
CREATE TABLE t1 (a int);
```
Try taking a backup of testdb as testuser and observe the failure
```bash
pg_dump -U testuser -v testdb
```

### PR DESCRIPTION
**Pull request by nikkhils**
Logging and caching related tables from the timescaledb extension should not be dumped using pg_dump. Our scripts specify a few such unwanted tables. Apart from being unnecessary, the "job_errors" had some restricted permissions causing additional problems in pg_dump.

We now don't include such tables for dumping.

Fixes #5449

Disable-check: force-changelog-file

### CODE REVIEW

File: sql/pre_install/cache.sql [hunk 1]
```diff
@@ -18,10 +18,5 @@ CREATE TABLE _timescaledb_cache.cache_inval_bgw_job();
 -- etc.
 CREATE TABLE _timescaledb_cache.cache_inval_extension();
 
--- not actually strictly needed but good for sanity as all tables should be dumped.
-SELECT pg_catalog.pg_extension_config_dump('_timescaledb_cache.cache_inval_hypertable', '');
-SELECT pg_catalog.pg_extension_config_dump('_timescaledb_cache.cache_inval_extension', '');
-SELECT pg_catalog.pg_extension_config_dump('_timescaledb_cache.cache_inval_bgw_job', '');
-
```
Comment (mkindahl) [inline sql/pre_install/cache.sql:25]: What about updates? Don't you need to deal with this in `latest-dev.sql` as well?

**Comment by svenklemm** [comment]
Need to make equivalent changes in latest-dev/reverse-dev

File: sql/pre_install/cache.sql (hunk 1 above)
Comment (nikkhils) [reply sql/pre_install/cache.sql:25]: done

**Review by mkindahl — COMMENTED** [review]
Do you have some sort of check of the status of these tables in the post action of the upgrade/downgrade tests? If a mistake is made, we should capture it.

**Comment by nikkhils** [comment]
> Do you have some sort of check of the status of these tables in the post action of the upgrade/downgrade tests? If a mistake is made, we should capture it.

@mkindahl indeed. These diffs get captured via upgrade/downgrade scripts and also via pg_dump.sql test.

**Comment by mkindahl** [comment]
> > Do you have some sort of check of the status of these tables in the post action of the upgrade/downgrade tests? If a mistake is made, we should capture it.
> 
> @mkindahl indeed. These diffs get captured via upgrade/downgrade scripts and also via pg_dump.sql test.

Right, I found a dump of `extconfig` in `post.catalog.sql`. You might want to consider adding  `extcondition` to this place since this could break if you forget to update this field in a future pull request where you also update `extconfig`.

**Comment by nikkhils** [comment]
> Do you have some sort of check of the status of these tables in the post action of the upgrade/downgrade tests? If a mistake is made, we should capture it.

@mkindahl done.

**Review by mkindahl — APPROVED** [review]

File: sql/updates/latest-dev.sql [hunk 2]
```diff
@@ -397,3 +397,33 @@ CREATE FUNCTION _timescaledb_functions.constraint_clone(constraint_oid OID,targe
...
+            WHERE extname = 'timescaledb';
+        -- This should not happen if this block is called once, but better be safe
+        IF position IS NULL THEN
+            CONTINUE;
+        END IF;
+        -- We cannot use array_remove here since it will remove multiple matching entries
+        -- unnecessarily. So, we concatenate sub arrays excluding the index entry
+        UPDATE pg_extension SET
+            extconfig = extconfig[:position - 1] || extconfig[position + 1:],
+            extcondition = extcondition[:position - 1] || extcondition[position + 1:]
```
Comment (fabriziomello) [inline sql/updates/latest-dev.sql:426]:
```suggestion
        UPDATE pg_catalog.pg_extension SET
            extconfig = array_remove(extconfig, extconfig[position]),
            extcondition = array_remove(extcondition, extcondition[position])
```

File: sql/updates/latest-dev.sql [hunk 3]
```diff
@@ -397,3 +397,33 @@ CREATE FUNCTION _timescaledb_functions.constraint_clone(constraint_oid OID,targe
...
+            WHERE extname = 'timescaledb';
+   END LOOP;
+END $block$ ;
```
Comment (fabriziomello) [inline sql/updates/latest-dev.sql:429]: Why don't use `ALTER EXTENSION timescaledb DROP TABLE ...` for the given objects?

Comment (nikkhils) [reply sql/updates/latest-dev.sql:429]: @fabriziomello while it does remove entries for extconfig and extcondition, it also completely disassociates the table from the extension. So, it's not useful at all 👎 

```
postgres=# create extension timescaledb;
CREATE EXTENSION
postgres=# ALTER EXTENSION timescaledb DROP TABLE  _timescaledb_config.bgw_job;
ALTER EXTENSION
postgres=# drop extension timescaledb ;
ERROR:  cannot drop extension timescaledb because other objects depend on it
DETAIL:  table _timescaledb_config.bgw_job depends on schema _timescaledb_config
HINT:  Use DROP ... CASCADE to drop the dependent objects too.
```

Comment (fabriziomello) [reply sql/updates/latest-dev.sql:429]: Good point, but in any case you can do an `ALTER EXTENSION timescaledb DROP` followed by an `ALTER EXTENSION timescaledb ADD` to disassociate and associate again the object without the dump configuration.

**Review by fabriziomello — APPROVED** [review]
