### PR TITLE
Include parallel leader in plan execution

### LINKED ISSUE #1793: Concurrent query with date casted variable lead to "never executed plan"
**Relevant system information:**
 - Linux kairos-2018-1 4.15.0-91-generic #92-Ubuntu SMP Fri Feb 28 11:09:48 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
 - postgres (PostgreSQL) 10.12 (Ubuntu 10.12-2.pgdg18.04+1)
 - TimescaleDB 1.6.1
 - apt install

**Describe the bug**

Context: I've got two hypertables with time key 'timestam_client'.

When I launch this query: 

```
explain analyse 
select count(*) from my_table_1 where 
timestamp_client::date = '2020-03-28';
```
NB: I know we should not write a query like that ! but our intern did :-)

and at the same time the same query again

```
explain analyse 
select count(*) from my_table_1 where 
timestamp_client::date = '2020-03-28';
```
I get two different query plan:

1st query plan 
```
Finalize Aggregate  (cost=15155700.30..15155700.31 rows=1 width=8) (actual time=103558.548..103558.548 rows=1 loops=1)
  ->  Gather  (cost=15155699.88..15155700.29 rows=4 width=8) (actual time=3.225..103912.718 rows=4 loops=1)
        Workers Planned: 4
        Workers Launched: 3
        ->  Partial Aggregate  (cost=15154699.88..15154699.89 rows=1 width=8) (actual time=77654.440..77654.440 rows=1 loops=4)
              ->  Parallel Custom Scan (ChunkAppend) on client_raw_history  (cost=0.00..15153677.06 rows=409126 width=0) (actual time=77411.785..77653.039 rows=15488 loops=4)
                    Chunks excluded during startup: 0
                    ->  Parallel Seq Scan on _hyper_1_3_chunk  (cost=0.00..55098.77 rows=1647 width=0) (actual time=997.308..997.308 rows=0 loops=1)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                          Rows Removed by Filter: 1317860
                    ->  Parallel Seq Scan on _hyper_1_4_chunk  (cost=0.00..51376.47 rows=1524 width=0) (actual time=838.904..838.904 rows=0 loops=1)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                          Rows Removed by Filter: 1219619
                    ->  Parallel Seq Scan on _hyper_1_6_chunk  (cost=0.00..47451.48 rows=1408 width=0) (actual time=781.400..781.400 rows=0 loops=1)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                          Rows Removed by Filter: 1126067
                    ->  Parallel Seq Scan on _hyper_1_7_chunk  (cost=0.00..40194.21 rows=1190 width=0) (actual time=670.969..670.970 rows=0 loops=1)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                          Rows Removed by Filter: 951788
                    ->  Parallel Seq Scan on _hyper_1_12_chunk  (cost=0.00..56033.36 rows=1670 width=0) (actual time=1093.827..1093.827 rows=0 loops=1)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                          Rows Removed by Filter: 1335639
                    ->  Parallel Seq Scan on _hyper_1_13_chunk  (cost=0.00..32.35 rows=1 width=0) (actual time=2.516..2.516 rows=0 loops=1)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                          Rows Removed by Filter: 380
                    ->  Parallel Seq Scan on _hyper_1_14_chunk  (cost=0.00..2999.75 rows=198 width=0) (actual time=59.353..59.353 rows=0 loops=1)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                          Rows Removed by Filter: 67199
                    ->  Parallel Seq Scan on _hyper_1_20_chunk  (cost=0.00..47392.70 rows=1402 width=0) (actual time=787.845..787.845 rows=0 loops=1)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                          Rows Removed by Filter: 1121547
                    ->  Parallel Seq Scan on _hyper_1_23_chunk  (cost=0.00..49105.51 rows=1448 width=0) (actual time=806.651..806.651 rows=0 loops=1)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                          Rows Removed by Filter: 1158823
                    ->  Parallel Seq Scan on _hyper_1_72_chunk  (cost=0.00..55515.07 rows=1649 width=0) (actual time=1014.871..1014.871 rows=0 loops=1)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                          Rows Removed by Filter: 1318950
                    ->  Parallel Seq Scan on _hyper_1_75_chunk  (cost=0.00..8.28 rows=1 width=0) (actual time=107.018..107.018 rows=0 loops=1)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                          Rows Removed by Filter: 145
                    ->  Parallel Seq Scan on _hyper_1_81_chunk  (cost=0.00..55388.69 rows=1645 width=0) (actual time=1045.282..1045.282 rows=0 loops=1)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                          Rows Removed by Filter: 1315951
                    ->  Parallel Seq Scan on _hyper_1_130_chunk  (cost=0.00..5156.26 rows=238 width=0) (actual time=104.293..104.293 rows=0 loops=1)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                          Rows Removed by Filter: 114342
                    ->  Parallel Seq Scan on _hyper_1_131_chunk  (cost=0.00..6365.62 rows=290 width=0) (actual time=138.174..138.174 rows=0 loops=1)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                          Rows Removed by Filter: 139152
                    ->  Parallel Seq Scan on _hyper_1_132_chunk  (cost=0.00..11339.67 rows=414 width=0) (actual time=181.633..181.633 rows=0 loops=1)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                          Rows Removed by Filter: 256851
                    ->  Parallel Seq Scan on _hyper_1_133_chunk  (cost=0.00..24910.55 rows=904 width=0) (actual time=417.627..417.627 rows=0 loops=1)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                          Rows Removed by Filter: 560621
                    ->  Parallel Seq Scan on _hyper_1_134_chunk  (cost=0.00..24842.35 rows=901 width=0) (actual time=410.848..410.848 rows=0 loops=1)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                          Rows Removed by Filter: 558716
                    ->  Parallel Seq Scan on _hyper_1_135_chunk  (cost=0.00..26909.77 rows=974 width=0) (actual time=437.482..437.482 rows=0 loops=1)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                          Rows Removed by Filter: 603637
                    ->  Parallel Seq Scan on _hyper_1_136_chunk  (cost=0.00..26202.18 rows=969 width=0) (actual time=424.040..424.040 rows=0 loops=1)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                          Rows Removed by Filter: 601063
                    ->  Parallel Seq Scan on _hyper_1_137_chunk  (cost=0.00..26566.90 rows=985 width=0) (actual time=418.969..418.969 rows=0 loops=1)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                          Rows Removed by Filter: 610935
                    ->  Parallel Seq Scan on _hyper_1_138_chunk  (cost=0.00..25453.30 rows=944 width=0) (actual time=407.829..407.829 rows=0 loops=1)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                          Rows Removed by Filter: 585190
                    ->  Parallel Seq Scan on _hyper_1_139_chunk  (cost=0.00..26401.10 rows=978 width=0) (actual time=633.023..633.023 rows=0 loops=1)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                          Rows Removed by Filter: 606241
                    ->  Parallel Seq Scan on _hyper_1_140_chunk  (cost=0.00..27814.83 rows=1034 width=0) (actual time=434.215..434.215 rows=0 loops=1)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                          Rows Removed by Filter: 641306
                    ->  Parallel Seq Scan on _hyper_1_141_chunk  (cost=0.00..30348.78 rows=1141 width=0) (actual time=534.378..534.378 rows=0 loops=1)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                          Rows Removed by Filter: 707650
                    ->  Parallel Seq Scan on _hyper_1_142_chunk  (cost=0.00..30373.80 rows=904 width=0) (actual time=779.162..779.163 rows=0 loops=1)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                          Rows Removed by Filter: 723182
                    ->  Parallel Seq Scan on _hyper_1_143_chunk  (cost=0.00..30370.18 rows=1133 width=0) (actual time=478.499..478.499 rows=0 loops=1)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                          Rows Removed by Filter: 702330
                    ->  Parallel Seq Scan on _hyper_1_144_chunk  (cost=0.00..29358.71 rows=1096 width=0) (actual time=464.121..464.121 rows=0 loops=1)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                          Rows Removed by Filter: 679530
                    ->  Parallel Seq Scan on _hyper_1_145_chunk  (cost=0.00..23556.53 rows=875 width=0) (actual time=368.444..368.444 rows=0 loops=1)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                          Rows Removed by Filter: 542846
                    ->  Parallel Seq Scan on _hyper_1_146_chunk  (cost=0.00..11437.18 rows=427 width=0) (actual time=178.949..178.949 rows=0 loops=1)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                          Rows Removed by Filter: 264998
                    ->  Parallel Seq Scan on _hyper_1_147_chunk  (cost=0.00..8056.25 rows=378 width=0) (actual time=126.035..126.035 rows=0 loops=1)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                          Rows Removed by Filter: 181640
                    ->  Parallel Seq Scan on _hyper_1_148_chunk  (cost=0.00..25075.18 rows=910 width=0) (actual time=404.686..404.686 rows=0 loops=1)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                          Rows Removed by Filter: 564516
                    ->  Parallel Seq Scan on _hyper_1_149_chunk  (cost=0.00..27575.25 rows=1001 width=0) (actual time=673.000..673.000 rows=0 loops=1)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                          Rows Removed by Filter: 620488
                    ->  Parallel Seq Scan on _hyper_1_150_chunk  (cost=0.00..34037.90 rows=990 width=0) (actual time=551.642..551.642 rows=0 loops=1)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                          Rows Removed by Filter: 792248
                    ->  Parallel Seq Scan on _hyper_1_151_chunk  (cost=0.00..48677.39 rows=1422 width=0) (actual time=1617.212..1617.212 rows=0 loops=1)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                          Rows Removed by Filter: 1137177
                    ->  Parallel Seq Scan on _hyper_1_152_chunk  (cost=0.00..54976.80 rows=1619 width=0) (actual time=902.981..902.981 rows=0 loops=1)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                          Rows Removed by Filter: 1295476
                    ->  Parallel Seq Scan on _hyper_1_153_chunk  (cost=0.00..64012.31 rows=1886 width=0) (actual time=1043.627..1043.627 rows=0 loops=1)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                          Rows Removed by Filter: 1509190
                    ->  Parallel Seq Scan on _hyper_1_154_chunk  (cost=0.00..66025.86 rows=1948 width=0) (actual time=1067.318..1067.318 rows=0 loops=1)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                          Rows Removed by Filter: 1558653
                    ->  Parallel Seq Scan on _hyper_1_155_chunk  (cost=0.00..74477.34 rows=2188 width=0) (actual time=1639.253..1639.253 rows=0 loops=1)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                          Rows Removed by Filter: 1750250
                    ->  Parallel Seq Scan on _hyper_1_156_chunk  (cost=0.00..101021.52 rows=2940 width=0) (actual time=1837.628..1837.628 rows=0 loops=1)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                          Rows Removed by Filter: 2352185
                    ->  Parallel Seq Scan on _hyper_1_157_chunk  (cost=0.00..443034.54 rows=5705 width=0) (actual time=7987.354..7987.354 rows=0 loops=1)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                          Rows Removed by Filter: 2580587
                    ->  Parallel Seq Scan on _hyper_1_158_chunk  (cost=0.00..438025.09 rows=5904 width=0) (actual time=7788.798..7788.798 rows=0 loops=1)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                          Rows Removed by Filter: 2708814
                    ->  Parallel Seq Scan on _hyper_1_159_chunk  (cost=0.00..482907.84 rows=7236 width=0) (actual time=8644.826..8644.826 rows=0 loops=1)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                          Rows Removed by Filter: 3375662
                    ->  Parallel Seq Scan on _hyper_1_160_chunk  (cost=0.00..445100.37 rows=5674 width=0) (actual time=8293.797..8293.797 rows=0 loops=1)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                          Rows Removed by Filter: 2569686
                    ->  Parallel Seq Scan on _hyper_1_161_chunk  (cost=0.00..441578.39 rows=5314 width=0) (actual time=7765.992..7765.993 rows=0 loops=1)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                          Rows Removed by Filter: 2388709
                    ->  Parallel Seq Scan on _hyper_1_162_chunk  (cost=0.00..423424.26 rows=5031 width=0) (actual time=7324.283..7324.283 rows=0 loops=1)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                          Rows Removed by Filter: 2259103
                    ->  Parallel Seq Scan on _hyper_1_163_chunk  (cost=0.00..399283.11 rows=4596 width=0) (actual time=7248.530..7248.530 rows=0 loops=1)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                          Rows Removed by Filter: 2039983
                    ->  Parallel Seq Scan on _hyper_1_164_chunk  (cost=0.00..104521.00 rows=3094 width=0) (actual time=1794.451..1794.451 rows=0 loops=1)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                          Rows Removed by Filter: 2475252
                    ->  Parallel Seq Scan on _hyper_1_165_chunk  (cost=0.00..120348.16 rows=3560 width=0) (actual time=2357.366..2357.366 rows=0 loops=1)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                          Rows Removed by Filter: 2848046
                    ->  Parallel Seq Scan on _hyper_1_166_chunk  (cost=0.00..126958.25 rows=3755 width=0) (actual time=2071.524..2071.524 rows=0 loops=1)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                          Rows Removed by Filter: 3004123
                    ->  Parallel Seq Scan on _hyper_1_167_chunk  (cost=0.00..145543.77 rows=4305 width=0) (actual time=2459.045..2459.045 rows=0 loops=1)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                          Rows Removed by Filter: 3444228
                    ->  Parallel Seq Scan on _hyper_1_168_chunk  (cost=0.00..136344.66 rows=4030 width=0) (actual time=2231.105..2231.105 rows=0 loops=1)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                          Rows Removed by Filter: 3223943
                    ->  Parallel Seq Scan on _hyper_1_169_chunk  (cost=0.00..115869.22 rows=3420 width=0) (actual time=1865.234..1865.234 rows=0 loops=1)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                          Rows Removed by Filter: 2735571
                    ->  Parallel Seq Scan on _hyper_1_170_chunk  (cost=0.00..109473.61 rows=3231 width=0) (actual time=2025.227..2025.227 rows=0 loops=1)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                          Rows Removed by Filter: 2584995
                    ->  Parallel Seq Scan on _hyper_1_171_chunk  (cost=0.00..122040.90 rows=3599 width=0) (actual time=2026.604..2026.604 rows=0 loops=1)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                          Rows Removed by Filter: 2879467
                    ->  Parallel Seq Scan on _hyper_1_172_chunk  (cost=0.00..109662.40 rows=3296 width=0) (actual time=1817.514..1817.514 rows=0 loops=1)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                          Rows Removed by Filter: 2636405
                    ->  Parallel Seq Scan on _hyper_1_173_chunk  (cost=0.00..91046.60 rows=2764 width=0) (actual time=1484.856..1484.856 rows=0 loops=1)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                          Rows Removed by Filter: 2210882
                    ->  Parallel Seq Scan on _hyper_1_174_chunk  (cost=0.00..118110.42 rows=3504 width=0) (actual time=2104.902..2104.902 rows=0 loops=1)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                          Rows Removed by Filter: 2803638
                    ->  Parallel Seq Scan on _hyper_1_175_chunk  (cost=0.00..120060.49 rows=3542 width=0) (actual time=2357.759..2357.759 rows=0 loops=1)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                          Rows Removed by Filter: 2833219
                    ->  Parallel Seq Scan on _hyper_1_176_chunk  (cost=0.00..114699.34 rows=3380 width=0) (actual time=2167.220..2167.220 rows=0 loops=1)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                          Rows Removed by Filter: 2703861
                    ->  Parallel Seq Scan on _hyper_1_177_chunk  (cost=0.00..120024.82 rows=3536 width=0) (actual time=2828.887..2828.887 rows=0 loops=1)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                          Rows Removed by Filter: 2828531
                    ->  Parallel Seq Scan on _hyper_1_178_chunk  (cost=0.00..116121.96 rows=3417 width=0) (actual time=2003.762..2003.762 rows=0 loops=1)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                          Rows Removed by Filter: 2733357
                    ->  Parallel Seq Scan on _hyper_1_179_chunk  (cost=0.00..118347.55 rows=3476 width=0) (actual time=2210.074..2210.074 rows=0 loops=1)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                          Rows Removed by Filter: 2780728
                    ->  Parallel Seq Scan on _hyper_1_180_chunk  (cost=0.00..118732.62 rows=3480 width=0) (actual time=2073.155..2073.155 rows=0 loops=1)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                          Rows Removed by Filter: 2784196
                    ->  Parallel Seq Scan on _hyper_1_181_chunk  (cost=0.00..113507.20 rows=3334 width=0) (actual time=1839.445..1839.445 rows=0 loops=1)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                          Rows Removed by Filter: 2666741
                    ->  Parallel Seq Scan on _hyper_1_182_chunk  (cost=0.00..112220.97 rows=3293 width=0) (actual time=2240.523..2240.523 rows=0 loops=1)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                          Rows Removed by Filter: 2634716
                    ->  Parallel Seq Scan on _hyper_1_183_chunk  (cost=0.00..108818.77 rows=3204 width=0) (actual time=1918.302..1918.302 rows=0 loops=1)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                          Rows Removed by Filter: 2563149
                    ->  Parallel Seq Scan on _hyper_1_184_chunk  (cost=0.00..93209.08 rows=2753 width=0) (actual time=2025.456..2025.456 rows=0 loops=1)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                          Rows Removed by Filter: 2202443
                    ->  Parallel Seq Scan on _hyper_1_185_chunk  (cost=0.00..94941.75 rows=2798 width=0) (actual time=1615.573..1615.573 rows=0 loops=1)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                          Rows Removed by Filter: 2238393
                    ->  Parallel Seq Scan on _hyper_1_186_chunk  (cost=0.00..82409.78 rows=2433 width=0) (actual time=1462.451..1462.451 rows=0 loops=1)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                          Rows Removed by Filter: 1946611
                    ->  Parallel Seq Scan on _hyper_1_187_chunk  (cost=0.00..76015.58 rows=2249 width=0) (actual time=1371.793..1371.793 rows=0 loops=1)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                          Rows Removed by Filter: 1799119
                    ->  Parallel Seq Scan on _hyper_1_188_chunk  (cost=0.00..47009.29 rows=1385 width=0) (actual time=1178.988..1178.988 rows=0 loops=1)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                          Rows Removed by Filter: 1107859
                    ->  Parallel Seq Scan on _hyper_1_222_chunk  (cost=0.00..64269.71 rows=1908 width=0) (actual time=1152.749..1152.749 rows=0 loops=1)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                          Rows Removed by Filter: 1526615
                    ->  Parallel Seq Scan on _hyper_1_248_chunk  (cost=0.00..1.08 rows=1 width=0) (actual time=0.131..0.131 rows=0 loops=1)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                          Rows Removed by Filter: 9
                    ->  Parallel Seq Scan on _hyper_1_249_chunk  (cost=0.00..1.19 rows=1 width=0) (actual time=0.124..0.124 rows=0 loops=1)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                          Rows Removed by Filter: 22
                    ->  Parallel Seq Scan on _hyper_1_250_chunk  (cost=0.00..1.01 rows=1 width=0) (actual time=0.128..0.128 rows=0 loops=1)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                          Rows Removed by Filter: 1
                    ->  Parallel Seq Scan on _hyper_1_251_chunk  (cost=0.00..1.10 rows=1 width=0) (actual time=0.160..0.160 rows=0 loops=1)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                          Rows Removed by Filter: 11
                    ->  Parallel Seq Scan on _hyper_1_252_chunk  (cost=0.00..68.31 rows=4 width=0) (actual time=1.839..1.839 rows=0 loops=1)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                          Rows Removed by Filter: 1349
                    ->  Parallel Seq Scan on _hyper_1_253_chunk  (cost=0.00..345.25 rows=20 width=0) (actual time=8.155..8.155 rows=0 loops=1)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                          Rows Removed by Filter: 6846
                    ->  Parallel Seq Scan on _hyper_1_254_chunk  (cost=0.00..508.25 rows=29 width=0) (actual time=11.663..11.663 rows=0 loops=1)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                          Rows Removed by Filter: 10059
                    ->  Parallel Seq Scan on _hyper_1_255_chunk  (cost=0.00..605.63 rows=35 width=0) (actual time=10.969..10.969 rows=0 loops=1)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                          Rows Removed by Filter: 11989
                    ->  Parallel Seq Scan on _hyper_1_256_chunk  (cost=0.00..615.36 rows=36 width=0) (actual time=15.011..15.011 rows=0 loops=1)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                          Rows Removed by Filter: 12177
                    ->  Parallel Seq Scan on _hyper_1_257_chunk  (cost=0.00..698.22 rows=41 width=0) (actual time=12.416..12.416 rows=0 loops=1)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                          Rows Removed by Filter: 13804
                    ->  Parallel Seq Scan on _hyper_1_258_chunk  (cost=0.00..653.73 rows=38 width=0) (actual time=11.603..11.603 rows=0 loops=1)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                          Rows Removed by Filter: 12934
                    ->  Parallel Seq Scan on _hyper_1_259_chunk  (cost=0.00..743.76 rows=44 width=0) (actual time=12.396..12.396 rows=0 loops=1)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                          Rows Removed by Filter: 14724
                    ->  Parallel Seq Scan on _hyper_1_260_chunk  (cost=0.00..813.71 rows=47 width=0) (actual time=13.654..13.654 rows=0 loops=1)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                          Rows Removed by Filter: 16102
                    ->  Parallel Seq Scan on _hyper_1_261_chunk  (cost=0.00..820.18 rows=48 width=0) (actual time=13.325..13.325 rows=0 loops=1)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                          Rows Removed by Filter: 16239
                    ->  Parallel Seq Scan on _hyper_1_262_chunk  (cost=0.00..854.40 rows=50 width=0) (actual time=26.774..26.774 rows=0 loops=1)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                          Rows Removed by Filter: 16956
                    ->  Parallel Seq Scan on _hyper_1_263_chunk  (cost=0.00..1113.90 rows=66 width=0) (actual time=17.827..17.827 rows=0 loops=1)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                          Rows Removed by Filter: 22676
                    ->  Parallel Seq Scan on _hyper_1_264_chunk  (cost=0.00..1650.87 rows=104 width=0) (actual time=27.244..27.244 rows=0 loops=1)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                          Rows Removed by Filter: 35262
...
Planning time: 11.216 ms
Execution time: 103914.206 ms
```

2nd query plan 

```
Finalize Aggregate  (cost=15155700.30..15155700.31 rows=1 width=8) (actual time=3.588..3.588 rows=1 loops=1)
  ->  Gather  (cost=15155699.88..15155700.29 rows=4 width=8) (actual time=3.585..3.819 rows=1 loops=1)
        Workers Planned: 4
        Workers Launched: 0
        ->  Partial Aggregate  (cost=15154699.88..15154699.89 rows=1 width=8) (actual time=0.002..0.002 rows=1 loops=1)
              ->  Parallel Custom Scan (ChunkAppend) on client_raw_history  (cost=0.00..15153677.06 rows=409126 width=0) (actual time=0.001..0.001 rows=0 loops=1)
                    Chunks excluded during startup: 0
                    ->  Parallel Seq Scan on _hyper_1_3_chunk  (cost=0.00..55098.77 rows=1647 width=0) (never executed)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                    ->  Parallel Seq Scan on _hyper_1_4_chunk  (cost=0.00..51376.47 rows=1524 width=0) (never executed)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                    ->  Parallel Seq Scan on _hyper_1_6_chunk  (cost=0.00..47451.48 rows=1408 width=0) (never executed)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                    ->  Parallel Seq Scan on _hyper_1_7_chunk  (cost=0.00..40194.21 rows=1190 width=0) (never executed)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                    ->  Parallel Seq Scan on _hyper_1_12_chunk  (cost=0.00..56033.36 rows=1670 width=0) (never executed)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                    ->  Parallel Seq Scan on _hyper_1_13_chunk  (cost=0.00..32.35 rows=1 width=0) (never executed)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                    ->  Parallel Seq Scan on _hyper_1_14_chunk  (cost=0.00..2999.75 rows=198 width=0) (never executed)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                    ->  Parallel Seq Scan on _hyper_1_20_chunk  (cost=0.00..47392.70 rows=1402 width=0) (never executed)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                    ->  Parallel Seq Scan on _hyper_1_23_chunk  (cost=0.00..49105.51 rows=1448 width=0) (never executed)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                    ->  Parallel Seq Scan on _hyper_1_72_chunk  (cost=0.00..55515.07 rows=1649 width=0) (never executed)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                    ->  Parallel Seq Scan on _hyper_1_75_chunk  (cost=0.00..8.28 rows=1 width=0) (never executed)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                    ->  Parallel Seq Scan on _hyper_1_81_chunk  (cost=0.00..55388.69 rows=1645 width=0) (never executed)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                    ->  Parallel Seq Scan on _hyper_1_130_chunk  (cost=0.00..5156.26 rows=238 width=0) (never executed)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                    ->  Parallel Seq Scan on _hyper_1_131_chunk  (cost=0.00..6365.62 rows=290 width=0) (never executed)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                    ->  Parallel Seq Scan on _hyper_1_132_chunk  (cost=0.00..11339.67 rows=414 width=0) (never executed)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                    ->  Parallel Seq Scan on _hyper_1_133_chunk  (cost=0.00..24910.55 rows=904 width=0) (never executed)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                    ->  Parallel Seq Scan on _hyper_1_134_chunk  (cost=0.00..24842.35 rows=901 width=0) (never executed)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                    ->  Parallel Seq Scan on _hyper_1_135_chunk  (cost=0.00..26909.77 rows=974 width=0) (never executed)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                    ->  Parallel Seq Scan on _hyper_1_136_chunk  (cost=0.00..26202.18 rows=969 width=0) (never executed)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                    ->  Parallel Seq Scan on _hyper_1_137_chunk  (cost=0.00..26566.90 rows=985 width=0) (never executed)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                    ->  Parallel Seq Scan on _hyper_1_138_chunk  (cost=0.00..25453.30 rows=944 width=0) (never executed)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                    ->  Parallel Seq Scan on _hyper_1_139_chunk  (cost=0.00..26401.10 rows=978 width=0) (never executed)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                    ->  Parallel Seq Scan on _hyper_1_140_chunk  (cost=0.00..27814.83 rows=1034 width=0) (never executed)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                    ->  Parallel Seq Scan on _hyper_1_141_chunk  (cost=0.00..30348.78 rows=1141 width=0) (never executed)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                    ->  Parallel Seq Scan on _hyper_1_142_chunk  (cost=0.00..30373.80 rows=904 width=0) (never executed)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                    ->  Parallel Seq Scan on _hyper_1_143_chunk  (cost=0.00..30370.18 rows=1133 width=0) (never executed)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                    ->  Parallel Seq Scan on _hyper_1_144_chunk  (cost=0.00..29358.71 rows=1096 width=0) (never executed)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                    ->  Parallel Seq Scan on _hyper_1_145_chunk  (cost=0.00..23556.53 rows=875 width=0) (never executed)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                    ->  Parallel Seq Scan on _hyper_1_146_chunk  (cost=0.00..11437.18 rows=427 width=0) (never executed)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                    ->  Parallel Seq Scan on _hyper_1_147_chunk  (cost=0.00..8056.25 rows=378 width=0) (never executed)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                    ->  Parallel Seq Scan on _hyper_1_148_chunk  (cost=0.00..25075.18 rows=910 width=0) (never executed)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                    ->  Parallel Seq Scan on _hyper_1_149_chunk  (cost=0.00..27575.25 rows=1001 width=0) (never executed)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                    ->  Parallel Seq Scan on _hyper_1_150_chunk  (cost=0.00..34037.90 rows=990 width=0) (never executed)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                    ->  Parallel Seq Scan on _hyper_1_151_chunk  (cost=0.00..48677.39 rows=1422 width=0) (never executed)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                    ->  Parallel Seq Scan on _hyper_1_152_chunk  (cost=0.00..54976.80 rows=1619 width=0) (never executed)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                    ->  Parallel Seq Scan on _hyper_1_153_chunk  (cost=0.00..64012.31 rows=1886 width=0) (never executed)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                    ->  Parallel Seq Scan on _hyper_1_154_chunk  (cost=0.00..66025.86 rows=1948 width=0) (never executed)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                    ->  Parallel Seq Scan on _hyper_1_155_chunk  (cost=0.00..74477.34 rows=2188 width=0) (never executed)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                    ->  Parallel Seq Scan on _hyper_1_156_chunk  (cost=0.00..101021.52 rows=2940 width=0) (never executed)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                    ->  Parallel Seq Scan on _hyper_1_157_chunk  (cost=0.00..443034.54 rows=5705 width=0) (never executed)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                    ->  Parallel Seq Scan on _hyper_1_158_chunk  (cost=0.00..438025.09 rows=5904 width=0) (never executed)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                    ->  Parallel Seq Scan on _hyper_1_159_chunk  (cost=0.00..482907.84 rows=7236 width=0) (never executed)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                    ->  Parallel Seq Scan on _hyper_1_160_chunk  (cost=0.00..445100.37 rows=5674 width=0) (never executed)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                    ->  Parallel Seq Scan on _hyper_1_161_chunk  (cost=0.00..441578.39 rows=5314 width=0) (never executed)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                    ->  Parallel Seq Scan on _hyper_1_162_chunk  (cost=0.00..423424.26 rows=5031 width=0) (never executed)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                    ->  Parallel Seq Scan on _hyper_1_163_chunk  (cost=0.00..399283.11 rows=4596 width=0) (never executed)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                    ->  Parallel Seq Scan on _hyper_1_164_chunk  (cost=0.00..104521.00 rows=3094 width=0) (never executed)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                    ->  Parallel Seq Scan on _hyper_1_165_chunk  (cost=0.00..120348.16 rows=3560 width=0) (never executed)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                    ->  Parallel Seq Scan on _hyper_1_166_chunk  (cost=0.00..126958.25 rows=3755 width=0) (never executed)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                    ->  Parallel Seq Scan on _hyper_1_167_chunk  (cost=0.00..145543.77 rows=4305 width=0) (never executed)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                    ->  Parallel Seq Scan on _hyper_1_168_chunk  (cost=0.00..136344.66 rows=4030 width=0) (never executed)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                    ->  Parallel Seq Scan on _hyper_1_169_chunk  (cost=0.00..115869.22 rows=3420 width=0) (never executed)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                    ->  Parallel Seq Scan on _hyper_1_170_chunk  (cost=0.00..109473.61 rows=3231 width=0) (never executed)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                    ->  Parallel Seq Scan on _hyper_1_171_chunk  (cost=0.00..122040.90 rows=3599 width=0) (never executed)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                    ->  Parallel Seq Scan on _hyper_1_172_chunk  (cost=0.00..109662.40 rows=3296 width=0) (never executed)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                    ->  Parallel Seq Scan on _hyper_1_173_chunk  (cost=0.00..91046.60 rows=2764 width=0) (never executed)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                    ->  Parallel Seq Scan on _hyper_1_174_chunk  (cost=0.00..118110.42 rows=3504 width=0) (never executed)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                    ->  Parallel Seq Scan on _hyper_1_175_chunk  (cost=0.00..120060.49 rows=3542 width=0) (never executed)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                    ->  Parallel Seq Scan on _hyper_1_176_chunk  (cost=0.00..114699.34 rows=3380 width=0) (never executed)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                    ->  Parallel Seq Scan on _hyper_1_177_chunk  (cost=0.00..120024.82 rows=3536 width=0) (never executed)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                    ->  Parallel Seq Scan on _hyper_1_178_chunk  (cost=0.00..116121.96 rows=3417 width=0) (never executed)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                    ->  Parallel Seq Scan on _hyper_1_179_chunk  (cost=0.00..118347.55 rows=3476 width=0) (never executed)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                    ->  Parallel Seq Scan on _hyper_1_180_chunk  (cost=0.00..118732.62 rows=3480 width=0) (never executed)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                    ->  Parallel Seq Scan on _hyper_1_181_chunk  (cost=0.00..113507.20 rows=3334 width=0) (never executed)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                    ->  Parallel Seq Scan on _hyper_1_182_chunk  (cost=0.00..112220.97 rows=3293 width=0) (never executed)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                    ->  Parallel Seq Scan on _hyper_1_183_chunk  (cost=0.00..108818.77 rows=3204 width=0) (never executed)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                    ->  Parallel Seq Scan on _hyper_1_184_chunk  (cost=0.00..93209.08 rows=2753 width=0) (never executed)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                    ->  Parallel Seq Scan on _hyper_1_185_chunk  (cost=0.00..94941.75 rows=2798 width=0) (never executed)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                    ->  Parallel Seq Scan on _hyper_1_186_chunk  (cost=0.00..82409.78 rows=2433 width=0) (never executed)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                    ->  Parallel Seq Scan on _hyper_1_187_chunk  (cost=0.00..76015.58 rows=2249 width=0) (never executed)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                    ->  Parallel Seq Scan on _hyper_1_188_chunk  (cost=0.00..47009.29 rows=1385 width=0) (never executed)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                    ->  Parallel Seq Scan on _hyper_1_222_chunk  (cost=0.00..64269.71 rows=1908 width=0) (never executed)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                    ->  Parallel Seq Scan on _hyper_1_248_chunk  (cost=0.00..1.08 rows=1 width=0) (never executed)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                    ->  Parallel Seq Scan on _hyper_1_249_chunk  (cost=0.00..1.19 rows=1 width=0) (never executed)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                    ->  Parallel Seq Scan on _hyper_1_250_chunk  (cost=0.00..1.01 rows=1 width=0) (never executed)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                    ->  Parallel Seq Scan on _hyper_1_251_chunk  (cost=0.00..1.10 rows=1 width=0) (never executed)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                    ->  Parallel Seq Scan on _hyper_1_252_chunk  (cost=0.00..68.31 rows=4 width=0) (never executed)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                    ->  Parallel Seq Scan on _hyper_1_253_chunk  (cost=0.00..345.25 rows=20 width=0) (never executed)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                    ->  Parallel Seq Scan on _hyper_1_254_chunk  (cost=0.00..508.25 rows=29 width=0) (never executed)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                    ->  Parallel Seq Scan on _hyper_1_255_chunk  (cost=0.00..605.63 rows=35 width=0) (never executed)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                    ->  Parallel Seq Scan on _hyper_1_256_chunk  (cost=0.00..615.36 rows=36 width=0) (never executed)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                    ->  Parallel Seq Scan on _hyper_1_257_chunk  (cost=0.00..698.22 rows=41 width=0) (never executed)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                    ->  Parallel Seq Scan on _hyper_1_258_chunk  (cost=0.00..653.73 rows=38 width=0) (never executed)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                    ->  Parallel Seq Scan on _hyper_1_259_chunk  (cost=0.00..743.76 rows=44 width=0) (never executed)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                    ->  Parallel Seq Scan on _hyper_1_260_chunk  (cost=0.00..813.71 rows=47 width=0) (never executed)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                    ->  Parallel Seq Scan on _hyper_1_261_chunk  (cost=0.00..820.18 rows=48 width=0) (never executed)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                    ->  Parallel Seq Scan on _hyper_1_262_chunk  (cost=0.00..854.40 rows=50 width=0) (never executed)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                    ->  Parallel Seq Scan on _hyper_1_263_chunk  (cost=0.00..1113.90 rows=66 width=0) (never executed)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                    ->  Parallel Seq Scan on _hyper_1_264_chunk  (cost=0.00..1650.87 rows=104 width=0) (never executed)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                    ->  Parallel Seq Scan on _hyper_1_265_chunk  (cost=0.00..2062.86 rows=132 width=0) (never executed)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                    ->  Parallel Seq Scan on _hyper_1_266_chunk  (cost=0.00..3079.15 rows=194 width=0) (never executed)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                    ->  Parallel Seq Scan on _hyper_1_267_chunk  (cost=0.00..3175.40 rows=194 width=0) (never executed)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                    ->  Parallel Seq Scan on _hyper_1_268_chunk  (cost=0.00..1291.64 rows=81 width=0) (never executed)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                    ->  Parallel Seq Scan on _hyper_1_269_chunk  (cost=0.00..2252.85 rows=144 width=0) (never executed)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                    ->  Parallel Seq Scan on _hyper_1_270_chunk  (cost=0.00..1257.26 rows=77 width=0) (never executed)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                    ->  Parallel Seq Scan on _hyper_1_271_chunk  (cost=0.00..1404.68 rows=84 width=0) (never executed)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                    ->  Parallel Seq Scan on _hyper_1_272_chunk  (cost=0.00..1583.23 rows=98 width=0) (never executed)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                    ->  Parallel Seq Scan on _hyper_1_273_chunk  (cost=0.00..1979.48 rows=125 width=0) (never executed)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                    ->  Parallel Seq Scan on _hyper_1_274_chunk  (cost=0.00..1976.29 rows=125 width=0) (never executed)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                    ->  Parallel Seq Scan on _hyper_1_275_chunk  (cost=0.00..2197.04 rows=139 width=0) (never executed)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                    ->  Parallel Seq Scan on _hyper_1_276_chunk  (cost=0.00..2340.07 rows=148 width=0) (never executed)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                    ->  Parallel Seq Scan on _hyper_1_277_chunk  (cost=0.00..2401.34 rows=153 width=0) (never executed)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                    ->  Parallel Seq Scan on _hyper_1_278_chunk  (cost=0.00..2240.79 rows=142 width=0) (never executed)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                    ->  Parallel Seq Scan on _hyper_1_279_chunk  (cost=0.00..2710.33 rows=174 width=0) (never executed)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                    ->  Parallel Seq Scan on _hyper_1_280_chunk  (cost=0.00..2181.46 rows=139 width=0) (never executed)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                    ->  Parallel Seq Scan on _hyper_1_281_chunk  (cost=0.00..3060.92 rows=195 width=0) (never executed)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                    ->  Parallel Seq Scan on _hyper_1_282_chunk  (cost=0.00..1927.09 rows=122 width=0) (never executed)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                    ->  Parallel Seq Scan on _hyper_1_283_chunk  (cost=0.00..1565.19 rows=99 width=0) (never executed)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                    ->  Parallel Seq Scan on _hyper_1_284_chunk  (cost=0.00..2358.89 rows=151 width=0) (never executed)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                    ->  Parallel Seq Scan on _hyper_1_285_chunk  (cost=0.00..3719.96 rows=182 width=0) (never executed)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                    ->  Parallel Seq Scan on _hyper_1_286_chunk  (cost=0.00..4209.58 rows=205 width=0) (never executed)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                    ->  Parallel Seq Scan on _hyper_1_287_chunk  (cost=0.00..3675.07 rows=241 width=0) (never executed)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                    ->  Parallel Seq Scan on _hyper_1_288_chunk  (cost=0.00..3183.25 rows=210 width=0) (never executed)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                    ->  Parallel Seq Scan on _hyper_1_289_chunk  (cost=0.00..3239.74 rows=214 width=0) (never executed)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                    ->  Parallel Seq Scan on _hyper_1_290_chunk  (cost=0.00..3323.94 rows=219 width=0) (never executed)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                    ->  Parallel Seq Scan on _hyper_1_291_chunk  (cost=0.00..2709.04 rows=177 width=0) (never executed)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                    ->  Parallel Seq Scan on _hyper_1_292_chunk  (cost=0.00..3078.79 rows=201 width=0) (never executed)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                    ->  Parallel Seq Scan on _hyper_1_293_chunk  (cost=0.00..3930.97 rows=191 width=0) (never executed)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                    ->  Parallel Seq Scan on _hyper_1_294_chunk  (cost=0.00..4090.40 rows=195 width=0) (never executed)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                    ->  Parallel Seq Scan on _hyper_1_295_chunk  (cost=0.00..4528.26 rows=215 width=0) (never executed)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                    ->  Parallel Seq Scan on _hyper_1_296_chunk  (cost=0.00..4721.56 rows=222 width=0) (never executed)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                    ->  Parallel Seq Scan on _hyper_1_297_chunk  (cost=0.00..7862.38 rows=366 width=0) (never executed)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                    ->  Parallel Seq Scan on _hyper_1_298_chunk  (cost=0.00..11190.80 rows=415 width=0) (never executed)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                    ->  Parallel Seq Scan on _hyper_1_299_chunk  (cost=0.00..10601.48 rows=393 width=0) (never executed)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                    ->  Parallel Seq Scan on _hyper_1_300_chunk  (cost=0.00..8346.04 rows=389 width=0) (never executed)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                    ->  Parallel Seq Scan on _hyper_1_301_chunk  (cost=0.00..5842.42 rows=274 width=0) (never executed)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                    ->  Parallel Seq Scan on _hyper_1_302_chunk  (cost=0.00..4400.62 rows=208 width=0) (never executed)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                    ->  Parallel Seq Scan on _hyper_1_303_chunk  (cost=0.00..5187.12 rows=241 width=0) (never executed)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                    ->  Parallel Seq Scan on _hyper_1_304_chunk  (cost=0.00..95026.53 rows=2807 width=0) (never executed)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                    ->  Parallel Seq Scan on _hyper_1_579_chunk  (cost=0.00..65751.35 rows=1936 width=0) (never executed)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                    ->  Parallel Seq Scan on _hyper_1_591_chunk  (cost=0.00..63790.32 rows=1872 width=0) (never executed)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                    ->  Parallel Seq Scan on _hyper_1_607_chunk  (cost=0.00..65896.57 rows=1950 width=0) (never executed)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                    ->  Parallel Seq Scan on _hyper_1_614_chunk  (cost=0.00..72601.70 rows=2158 width=0) (never executed)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                    ->  Parallel Seq Scan on _hyper_1_621_chunk  (cost=0.00..78860.05 rows=2352 width=0) (never executed)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                    ->  Parallel Seq Scan on _hyper_1_629_chunk  (cost=0.00..80121.45 rows=2377 width=0) (never executed)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                    ->  Parallel Seq Scan on _hyper_1_631_chunk  (cost=0.00..1.12 rows=1 width=0) (never executed)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                    ->  Parallel Seq Scan on _hyper_1_635_chunk  (cost=0.00..81408.60 rows=2392 width=0) (never executed)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                    ->  Parallel Seq Scan on _hyper_1_638_chunk  (cost=0.00..74496.37 rows=2231 width=0) (never executed)
                          Filter: ((timestamp_client)::date = '2020-03-24'::date)
                    ->  Parallel Seq Scan on _hyper_1_641_chunk  (cost=0.00..87332.22 rows=2572 width=0) (never executed)
...
Planning time: 9.304 ms
Execution time: 6.049 ms
```

And twi different results, 1rst result is the right number (700k), second result is 0 (as expected since the query plan is never executed.

**Expected behavior**
Both query should return the same result.

**Actual behavior**

We tested several cases :

1. exact same queries launched simultaneously

```
explain analyse 
select count(*) from my_table_1 where 
timestamp_client::date = '2020-03-28';
```

and 

```
explain analyse 
select count(*) from my_table_1 where 
timestamp_client::date = '2020-03-28';
```

will lead to a never executed query plan on the second query.

2. similar queries launched simultaneously / same chunk

```
explain analyse 
select count(*) from my_table_1 where 
timestamp_client::date = '2020-03-28';
```

and 

```
explain analyse 
select count(*) from my_table_1 where 
timestamp_client::date = '2020-03-26';
```

will lead to a never executed query plan on the second query.

3. similar queries launched simultaneously, different chunk

```
explain analyse 
select count(*) from my_table_1 where 
timestamp_client::date = '2020-03-28';
```

and 

```
explain analyse 
select count(*) from my_table_1 where 
timestamp_client::date = '2020-03-26';
```

will lead to a never executed query plan on the second query.

3. similar more complex queries launched simultaneously 

```
EXPLAIN ANALYSE
SELECT id, MIN(timestamp_client_start::date) AS timestamp_client_start
FROM my_table_1
WHERE place_id IN (40146, 40267, 40157, 40278, 40168, 40179, 30243, 30336, 39134, 39145, 39156, 40872, 39167, 40762, 39178, 40652, 40773, 40542, 40663, 40432, 40553, 40674, 40322, 40443, 40564, 40212, 40333)
AND timestamp_client::date = '2020-01-07'
GROUP BY cid;
```

and 

```
EXPLAIN ANALYSE
SELECT id, MIN(timestamp_client_start::date) AS timestamp_client_start
FROM my_table_1
WHERE place_id IN (40146, 40267, 40157, 40278, 40168, 40179, 30243, 30336, 39134, 39145, 39156, 40872, 39167, 40762, 39178, 40652, 40773, 40542, 40663, 40432, 40553, 40674, 40322, 40443, 40564, 40212, 40333)
AND timestamp_client::date = '2020-01-10'
GROUP BY cid;
```
will lead to a never executed query plan on the second query.

4. more complex mix simultaneously 

```
EXPLAIN ANALYSE
SELECT id, MIN(timestamp_client_start::date) AS timestamp_client_start
FROM my_table_1
WHERE place_id IN (40146, 40267, 40157, 40278, 40168, 40179, 30243, 30336, 39134, 39145, 39156, 40872, 39167, 40762, 39178, 40652, 40773, 40542, 40663, 40432, 40553, 40674, 40322, 40443, 40564, 40212, 40333)
AND timestamp_client::date = '2020-01-10'
GROUP BY cid;
```

with 

```
explain analyse 
select count(*) from my_table_1 where 
timestamp_client::date = '2020-03-26';
```

will lead to a never executed query plan on the second query.

5. Similar query on differnet tables 

```
explain analyse 
select count(*) from my_table_1 where 
timestamp_client::date = '2020-03-28';
```

and 

```
explain analyse 
select count(*) from my_table_2 where 
timestamp_client::date = '2020-03-28';
```

will lead to a never executed query plan on the second query.

This is all the tests I made, and the issue seems consistent.

Is this issue clear enough for you or do you need more investigations ?

thanks for your help.

### PR DESCRIPTION
**Pull request by svenklemm**
We have to let the leader participate in plan execution
because the number of workers planned for a query
might be different from the number of workers
available. And even though a parallel plan was created
no parallel workers might be available during execution,
leading to incorrect results unless the leader participates
in execution.

This commit also changes the parallel EXPLAINs to not run with
ANALYZE because the output is not stable as it depends on
worker assignment.

Fixes #1793

### CODE REVIEW

File: src/chunk_append/exec.c [hunk 1]
```diff
@@ -449,7 +449,15 @@ choose_next_subplan_non_parallel(ChunkAppendState *state)
...
 choose_next_subplan_for_leader(ChunkAppendState *state)
 {
-	state->current = NO_MATCHING_SUBPLANS;
+	/*
+	 * If no workers got launched for this parallel plan
+	 * we have to let leader participate in subplan
+	 * execution.
+	 */
+	if (state->pcxt->nworkers_launched == 0)
+		choose_next_subplan_for_worker(state);
```
Comment (k-rus) [inline src/chunk_append/exec.c:458]: Is this new behaviour tested? How is it difficult to add new test?

Comment (svenklemm) [reply src/chunk_append/exec.c:458]: It would require quite a bit of extra infrastructure to produce a test case.

Comment (k-rus) [reply src/chunk_append/exec.c:458]: Thank you for clarifying.

**Comment by svenklemm** [comment]
You can control the numbers of workers for a plan pretty easily but that still doesnt make output stable except for very simple plans.
