### PR TITLE
Fix timescaledb_post_restore GUC handling

### LINKED ISSUE #4267: [Bug]: timescaledb_post_restore does not set timescaledb.restoring to off
### What type of bug is this?

Unexpected error

### What subsystems and features are affected?

Restore

### What happened?

`select public.timescaledb_post_restore();` does not set the `timescaledb.restoring` setting to `off`. It stays `on`.

### TimescaleDB version affected

2.6.1

### PostgreSQL version used

14.2

### What operating system did you use?

docker image timescale/timescaledb:latest-pg14

### What installation method did you use?

Docker

### What platform did you run on?

Other

### Relevant log output and stack trace

```bash
john@john ~ % docker run -d --name timescaledb -p 5432:5432 -e POSTGRES_PASSWORD=password timescale/timescaledb:latest-pg14
edb5c3b5569927380afde0fe1487dbe56cba59175abca6c71f110dc903ae306e
john@john ~ % psql -h localhost -p 5432 -d postgres -U postgres
Password for user postgres: 
Timing is on.
Line style is unicode.
Border style is 2.
Pager usage is off.
Expanded display is used automatically.
psql (14.2)
Type "help" for help.

postgres=# \dx
                                       List of installed extensions
┌─────────────┬─────────┬────────────┬───────────────────────────────────────────────────────────────────┐
│    Name     │ Version │   Schema   │                            Description                            │
├─────────────┼─────────┼────────────┼───────────────────────────────────────────────────────────────────┤
│ plpgsql     │ 1.0     │ pg_catalog │ PL/pgSQL procedural language                                      │
│ timescaledb │ 2.6.1   │ public     │ Enables scalable inserts and complex queries for time-series data │
└─────────────┴─────────┴────────────┴───────────────────────────────────────────────────────────────────┘
(2 rows)

postgres=# select public.timescaledb_pre_restore();
┌─────────────────────────┐
│ timescaledb_pre_restore │
├─────────────────────────┤
│ t                       │
└─────────────────────────┘
(1 row)

Time: 10.144 ms
postgres=# show timescaledb.restoring;
┌───────────────────────┐
│ timescaledb.restoring │
├───────────────────────┤
│ on                    │
└───────────────────────┘
(1 row)

Time: 2.588 ms
postgres=# \q
john@john ~ % psql -h localhost -p 5432 -d postgres -U postgres
Password for user postgres: 
Timing is on.
Line style is unicode.
Border style is 2.
Pager usage is off.
Expanded display is used automatically.
psql (14.2)
Type "help" for help.

postgres=# show timescaledb.restoring;
┌───────────────────────┐
│ timescaledb.restoring │
├───────────────────────┤
│ on                    │
└───────────────────────┘
(1 row)

Time: 9.110 ms
postgres=# select setting, reset_val from pg_settings where name = 'timescaledb.restoring';
┌─────────┬───────────┐
│ setting │ reset_val │
├─────────┼───────────┤
│ on      │ on        │
└─────────┴───────────┘
(1 row)

Time: 6.071 ms
postgres=# select public.timescaledb_post_restore();
┌──────────────────────────┐
│ timescaledb_post_restore │
├──────────────────────────┤
│ t                        │
└──────────────────────────┘
(1 row)

Time: 9.437 ms
postgres=# select setting, reset_val from pg_settings where name = 'timescaledb.restoring';
┌─────────┬───────────┐
│ setting │ reset_val │
├─────────┼───────────┤
│ on      │ on        │
└─────────┴───────────┘
(1 row)

Time: 4.517 ms
postgres=# \q
john@john ~ % psql -h localhost -p 5432 -d postgres -U postgres
Password for user postgres: 
Timing is on.
Line style is unicode.
Border style is 2.
Pager usage is off.
Expanded display is used automatically.
psql (14.2)
Type "help" for help.

postgres=# select public.timescaledb_post_restore();
┌──────────────────────────┐
│ timescaledb_post_restore │
├──────────────────────────┤
│ t                        │
└──────────────────────────┘
(1 row)

Time: 17.626 ms
postgres=# select setting, reset_val from pg_settings where name = 'timescaledb.restoring';
┌─────────┬───────────┐
│ setting │ reset_val │
├─────────┼───────────┤
│ off     │ off       │
└─────────┴───────────┘
(1 row)

Time: 5.546 ms
```

### How can we reproduce the bug?

```bash
1. connect to the database
2. call `select public.timescaledb_pre_restore();`
3. disconnect from the database
4. connect to the database
5. call `select public.timescaledb_post_restore();`
6. `show timescaledb.restoring;` returns `on`. I would have expected this to be `off`. I cannot insert into hypertables at this point.
7. disconnect from the database
8. connect to the database
9. call `select public.timescaledb_post_restore();`
10. `show timescaledb.restoring;` returns `off`.
```

### PR DESCRIPTION
**Pull request by svenklemm**
In the session timescaledb_post_restore() was called the value for
timescaledb.restoring might not be changed because the reset_val
for the GUC was still on. We have to use explicit SET in this
session to adjust the GUC.

Fixes #4267

### CODE REVIEW

**Review by jnidzwetzki — APPROVED** [review]

File: sql/restoring.sql [hunk 1]
```diff
@@ -26,7 +26,8 @@ DECLARE
 BEGIN
     SELECT current_database() INTO db;
     EXECUTE format($$ALTER DATABASE %I RESET timescaledb.restoring $$, db);
-    RESET timescaledb.restoring;
+    -- we cannot use reset here because the reset_val might not be off
+    SET timescaledb.restoring TO off;
     PERFORM _timescaledb_internal.restart_background_workers();
```
Comment (konskov) [inline sql/restoring.sql:31]: I remember there were [some concerns](https://github.com/timescale/timescaledb/pull/4290#discussion_r863539422) that this will create problems with `pg_dumpall`. Are they still valid with this solution?

Comment (svenklemm) [reply sql/restoring.sql:31]: post_restore would be run after `pg_dumpall` so it cannot have an effect on it

**Review by RafiaSabih — APPROVED** [review]
