### PR TITLE
Fix handling of types with custom partitioning

### LINKED ISSUE #1250: The column type is used instead of return type of `time_partitioning_func` in many functions
**Relevant system information:**
 - OS: Fedora 30
 - PostgreSQL version (output of `postgres --version`): 11
 - TimescaleDB version (output of `\dx` in `psql`): 1.3.0
 - Installation method: Docker

**Describe the bug**
I created a hypertable with `time_partitioning_func` function to return the time value used in partitioning. However, functions such as `drop_chunks()`,`show_chunks()` and `set_chunk_time_interval()` doesn't work correctly as they are apparently looking into the type of the column rather than return value of `time_partitioning_func` function.

**To Reproduce**
1. Create a sample hypertable using `time_partitioning_func`:

```
CREATE TYPE report AS (last_seen timestamp with time zone, contents text);

CREATE TABLE customer_reports(reports report[] NOT NULL);

CREATE FUNCTION first_report_last_seen (report[])
RETURNS timestamptz
LANGUAGE SQL
IMMUTABLE
AS 'SELECT $1[1].last_seen';

SELECT create_hypertable(
    main_table => 'customer_reports',
    time_column_name => 'reports',
    time_partitioning_func => 'first_report_last_seen'
);
```

2. Now, try to run one of the mentioned functions, and it'll produce an error:
```
# SELECT set_chunk_time_interval('terminated_flows', interval '0.080000 hour');
ERROR:  invalid dimension type: "reports" must be an integer, date or timestamp
```

**Expected behavior**
The functions should properly work in this case.

**Actual behavior**
The error message appears and function doesn't do anything

### PR DESCRIPTION
**Pull request by JLockerman**
In various places, most notably drop_chunks and show_chunks, we
dispatch based on the type of the "time" column of the hypertable, for
things such as determining which interval type to use. With a custom
partition function, this logic is incorrect, as we should instead be
determining this based on the return type of the partitioning function.

This commit changes all relevant access of dimension.column_type to a
new function, ts_dimension_get_partition_type, which has the correct
behavior: it returns the partitioning function's return type, if one
exists, and only otherwise uses the column type. After this commit, all
references to column_type directly should have a comment explaining why
this is appropriate.

fixes #1250

### CODE REVIEW

**Comment by mfreed** [comment]
@JLockerman Can you confirm whether this PR fixes this issue as well?    https://github.com/timescale/timescaledb/issues/1250#issuecomment-503658988

File: test/sql/chunk_utils.sql [hunk 1]
```diff
@@ -347,6 +347,8 @@ BEGIN;
     SELECT * FROM test.show_subtables('drop_chunk_test_date');
 ROLLBACK;
 
+SET timezone TO '+0';
```
Comment (svenklemm) [inline test/sql/chunk_utils.sql]: why are you setting timezone to 0 i'd rather see tests run with a timezone to make sure this is handled properly

File: test/sql/chunk_utils.sql [hunk 2]
```diff
@@ -369,3 +371,58 @@ SELECT _timescaledb_internal.chunk_id_from_relid(tableoid) FROM chunk_id_from_re
...
+SELECT * FROM test.show_subtables('test_weird_type');
+SELECT show_chunks('test_weird_type', older_than=>'2019/06/06 4:00+0'::TIMESTAMPTZ);
+SELECT show_chunks('test_weird_type', older_than=>'2019/06/06 10:00+0'::TIMESTAMPTZ);
+
+SELECT drop_chunks('2019/06/06 6:00+0'::TIMESTAMPTZ, 'test_weird_type');
+SELECT * FROM test.show_subtables('test_weird_type');
+SELECT show_chunks('test_weird_type', older_than=>'2019/06/06 10:00+0'::TIMESTAMPTZ);
+
+DROP TABLE test_weird_type;
+DROP FUNCTION extract_time;
```
Comment (svenklemm) [inline test/sql/chunk_utils.sql]: this won't work on 9.6 you need to specify the argument types

File: src/chunk.c [hunk 3]
```diff
@@ -1266,6 +1266,7 @@ chunk_get_chunks_in_time_range(Oid table_relid, Datum older_than_datum, Datum ne
 
 		time_dim = hyperspace_get_open_dimension(ht->space, 0);
 
+		// FIXME should this be partitioning_type instead?
```
Comment (svenklemm) [inline src/chunk.c]: this should probably be fixed or removed :)

File: src/hypertable.c [hunk 4]
```diff
@@ -214,6 +214,7 @@ ts_hypertable_get_time_type(PG_FUNCTION_ARGS)
 	time_dimension = hyperspace_get_open_dimension(ht->space, 0);
 	if (time_dimension == NULL)
 		PG_RETURN_NULL();
+	/* This is deliberately column_type not partitioning_type */
```
Comment (svenklemm) [inline src/hypertable.c]: should probably explain why here

File: src/chunk.c (hunk 3 above)
Comment (JLockerman) [reply src/chunk.c]: @svenklemm @cevian  well should it? (if we don't know, the `FIXME` is better than having us forget about it)

**Comment by JLockerman** [comment]
@mfreed that one won't be fixed, but due to how we handle partitioning functions, I'm a little leery of trying to fix it right now (we need to make sure that it's still a valid input to the function).

**Comment by JLockerman** [comment]
In fact, I'm going to block altering the type of open dimensions with a custom partitioning function.

File: src/chunk.c (hunk 3 above)
Comment (svenklemm) [reply src/chunk.c]: oh i thought you left this as todo for yourself

Comment (svenklemm) [reply src/chunk.c]: i think it should be partitioning_type though because column_type makes no sense

Comment (JLockerman) [reply src/chunk.c]: @svenklemm mayyybe, but that would be a strictly weaker condition than we have here; it would allow multiple chunks which have different time-column types to be dropped together.

Honestly, I'm inclined to say that allowing `drop_chunks` to affect multiple tables is a miss-feature, and I don't care if it works; pretty much anything will break it anyway.
