### PR TITLE
Stop background worker on ALTER DATABASE SET TABLESPACE and CREATE DATABASE WITH TEMPLATE

### LINKED ISSUE #1078: ALTER DATABASE name SET TABLESPACE --> can't do that because of background timescaledb workers
**Relevant system information:**
 - OS: Ubuntu 18.04.2 LTS
 - PostgreSQL version (output of `postgres --version`): postgres (PostgreSQL) 11.2 (Ubuntu 11.2-1.pgdg18.04+1)
 - TimescaleDB version (output of `\dx` in `psql`):  timescaledb  1.2.0
 - Installation method: apt install

**Describe the bug**
when moving a database to a new tablespace, the background worker keeps it from doing so, since ``alter database set tablespace ...`` requires the background worker to be disconnected from the DB.

Similar to #1043

**To Reproduce**
1. psql template1
2. ``ALTER DATABASE name SET TABLESPACE new_tablespace``
3. See the error message, that there is still one connected client, it can't move the DB to a new tablespace
4. Restart postgresql without timescaledb background worker, try (2) again. It works now.

**Expected behavior**
Similar to #1043 it should stop the background worker for the time that the DB is moved to a new tablespace, then resume again. TBD... but that's probably what a postgresql DBA would expect.

**Actual behavior**
Could not move a DB to a new tablespace

### PR DESCRIPTION
**Pull request by svenklemm**
Alter database set tablespace will error out if there are still
active sessions to the database so we need to stop background workers
to not prevent the command from succeeding.

Fixes #1078

### CODE REVIEW

File: src/loader/loader.c [hunk 1]
```diff
@@ -360,6 +360,22 @@ post_analyze_hook(ParseState *pstate, Query *query)
...
+				AlterDatabaseStmt *stmt = (AlterDatabaseStmt *) query->utilityStmt;
+				if (list_length(stmt->options) == 1)
+				{
+					DefElem *option = linitial(stmt->options);
+					if (option->defname && strcmp(option->defname, "tablespace") == 0)
+					{
+						Oid db_oid = get_database_oid(stmt->dbname, false);
+
+						if (OidIsValid(db_oid))
+							ts_bgw_message_send_and_wait(STOP, db_oid);
```
Comment (cevian) [inline src/loader/loader.c]: should this be a STOP or a RESTART? What starts the bgws up again afterwards. (also should add to test a way to see the the bgws start after this command).

Comment (svenklemm) [reply src/loader/loader.c]: i was worried about race conditions with restart but it seems to work fine, i changed alter database rename to RESTART aswell

File: test/expected/bgw_launcher.out [hunk 2]
```diff
@@ -435,14 +435,23 @@ SELECT wait_worker_counts(1,1,0,0);
...
 CREATE DATABASE db_rename_test;
 \c db_rename_test :ROLE_SUPERUSER
 SET client_min_messages=error;
 CREATE EXTENSION timescaledb;
-\c :TEST_DBNAME :ROLE_SUPERUSER
+\c :TEST_DBNAME_2 :ROLE_SUPERUSER
 ALTER DATABASE db_rename_test RENAME TO db_rename_test2;
 DROP DATABASE db_rename_test2;
+-- test create database with timescaledb database as template
+CREATE DATABASE db_from_template WITH TEMPLATE :TEST_DBNAME;
```
Comment (cevian) [inline test/expected/bgw_launcher.out]: I would like to see testing of the fact that bgw workers get started for the new database (and also below after the alter)

File: test/expected/bgw_launcher.out [hunk 3]
```diff
@@ -435,14 +489,41 @@ SELECT wait_worker_counts(1,1,0,0);
...
-\c :TEST_DBNAME :ROLE_SUPERUSER
-DROP DATABASE :TEST_DBNAME_2;
 -- test rename database
 CREATE DATABASE db_rename_test;
 \c db_rename_test :ROLE_SUPERUSER
 SET client_min_messages=error;
 CREATE EXTENSION timescaledb;
-\c :TEST_DBNAME :ROLE_SUPERUSER
+\c :TEST_DBNAME_2 :ROLE_SUPERUSER
+SELECT wait_for_bgw_scheduler('db_rename_test');
```
Comment (cevian) [inline test/expected/bgw_launcher.out]: don't we want this to run after the rename? Or at least both before and after?

File: test/expected/bgw_launcher.out [hunk 4]
```diff
@@ -435,14 +489,41 @@ SELECT wait_worker_counts(1,1,0,0);
...
+DROP TABLESPACE IF EXISTS tablespace1;
+RESET client_min_messages;
+CREATE TABLESPACE tablespace1 OWNER :ROLE_DEFAULT_PERM_USER LOCATION :TEST_TABLESPACE1_PATH;
+SELECT wait_for_bgw_scheduler(:'TEST_DBNAME');
+ wait_for_bgw_scheduler 
+------------------------
+ BGW Scheduler found.
+(1 row)
+
+ALTER DATABASE :TEST_DBNAME SET TABLESPACE tablespace1;
```
Comment (cevian) [inline test/expected/bgw_launcher.out]: don't we want a SELECT wait_for_bgw_scheduler(:'TEST_DBNAME'); after this line?

File: test/expected/bgw_launcher.out (hunk 3 above)
Comment (svenklemm) [reply test/expected/bgw_launcher.out]: we wanna test that rename works when there is a background worker active so we need to be sure the background worker has been started, testing it after would test that the restart actually worked which is not what this pr is about but could be tested here aswell
