### PR TITLE
Fix compression policy on tables using INTEGER

### LINKED ISSUE #3773: Compression policy fails if the table uses integer and not bigint
**Relevant system information:**
 - OS:  Ubuntu 18.04.5
 - PostgreSQL PostgreSQL 12.8 
 - TimescaleDB version 2.5.0
 - Installation method: AWS Image

**Describe the bug**

The `show_chunks` function's `older_than` argument needs the data to be the same type as the time column. 

However, in the `_timescaledb_internal.policy_compression_integer` function, it casts values to BIGINT. So if your time column is an INT, the compression policy will fail. 

In the below code link, the `lag_integer` value is a BIGINT. 
https://github.com/timescale/timescaledb/blob/20543bf66b4de035d7890cdb642eed4cef2fed53/sql/policy_internal.sql#L89

**To Reproduce**
Create a table with an `INTEGER` time column, use `set_integer_now_func` to set the function type, and then add a compression policy.

You will start seeing errors in the logs:
```
2021-11-02 11:19:30.087 UTC [12436] ERROR:  invalid time argument type "bigint"
2021-11-02 11:19:30.087 UTC [12436] HINT:  Try casting the argument to "integer".
2021-11-02 11:19:30.087 UTC [12436] CONTEXT:  PL/pgSQL function _timescaledb_internal.policy_compression_integer(integer,integer,bigint,integer,boolean,boolean) line 17 at FOR over SELECT rows
	SQL statement "CALL _timescaledb_internal.policy_compression_integer(
	            job_id, htid, lag_integer,
	            maxchunks, verbose_log, recompress_enabled )"
	PL/pgSQL function _timescaledb_internal.policy_compression(integer,jsonb) line 62 at CALL
```

### PR DESCRIPTION
**Pull request by fabriziomello**
Commit fffd6c2350f5b3237486f3d49d7167105e72a55b fixes problem
related to PortalContext using PL/pgSQL procedure to execute the policy.
Unfortunately this new implementation introduced a problem when we use
INTEGER and not BIGINT for the time dimension.

Fixed it by dealing correclty with the integer types: SMALLINT, INTEGER
and BIGINT.

Also refatored the policy compression procedure replacing the two
procedures `policy_compression_{interval|integer}` by a simple
`policy_compression_execute` casting dimension type dynamically.

Fixes #3773

### CODE REVIEW

**Review by svenklemm — COMMENTED** [review]
please add following test:
```
create table m_int(time int not null);
select create_hypertable('m_int','time',chunk_time_interval:=1000);
create or replace function now_int() returns int as $$ SELECT 1 $$ language sql stable;
select set_integer_now_func('m_int','now_int');
alter table m_int set (timescaledb.compress);
select add_compression_policy('m_int',10) AS "JOB_ID" \gset
call run_job(:JOB_ID);
```

File: sql/policy_internal.sql [hunk 1]
```diff
@@ -19,163 +19,125 @@ AS '@MODULE_PATHNAME@', 'ts_policy_refresh_cagg_proc'
...
-
-  SELECT format('%I.%I',schema_name, table_name) INTO htoid
-  FROM _timescaledb_catalog.hypertable
-  WHERE id = htid;
-
-  --for the integer case , we have to compute the lag w.r.t 
+  -- for the integer cases, we have to compute the lag w.r.t
   -- the integer_now function and then pass on to show_chunks
-  lag_integer := _timescaledb_internal.subtract_integer_from_now( htoid, lag);
+  IF pg_typeof(lag) IN ('BIGINT'::regtype, 'INTEGER'::regtype, 'SMALLINT'::regtype) THEN
```
Comment (svenklemm) [inline sql/policy_internal.sql:42]:
```suggestion
  IF pg_typeof(lag) IN ('BIGINT', 'INTEGER', 'SMALLINT') THEN
```

Comment (fabriziomello) [reply sql/policy_internal.sql:42]: It doesn't work because `pg_typeof` function returns `REGTYPE`.

```sql
fabrizio=# \df pg_typeof
                           List of functions
   Schema   |   Name    | Result data type | Argument data types | Type 
------------+-----------+------------------+---------------------+------
 pg_catalog | pg_typeof | regtype          | "any"               | func
(1 row)

fabrizio=# SELECT pg_typeof('BIGINT'::regtype) IN ('BIGINT', 'INTEGER', 'SMALLINT');
 ?column? 
----------
 f
(1 row)
```

**Review by svenklemm — APPROVED** [review]

**Comment by svenklemm** [comment]
Don't forget to update changelog.

File: sql/policy_internal.sql (hunk 1 above)
Comment (fabriziomello) [reply sql/policy_internal.sql:42]: And without explicit type cast to `REGTYPE` it will be recognized as `unknown`

```sql
fabrizio=# SELECT pg_typeof('BIGINT'), pg_typeof('BIGINT'::regtype);
 pg_typeof | pg_typeof 
-----------+-----------
 unknown   | regtype
(1 row)
```

**Comment by fabriziomello** [comment]
> Don't forget to update changelog.

Updated! Thanks!

File: tsl/test/sql/compression_bgw.sql [hunk 2]
```diff
@@ -74,30 +74,76 @@ CALL run_job(:compressjob_id);
...
-CREATE TABLE test_table_int(time bigint, val int);
-SELECT create_hypertable('test_table_int', 'time', chunk_time_interval => 1);
-
-create or replace function dummy_now() returns BIGINT LANGUAGE SQL IMMUTABLE as  'SELECT 5::BIGINT';
-select set_integer_now_func('test_table_int', 'dummy_now');
-insert into test_table_int select generate_series(1,5), 10;
-alter table test_table_int set (timescaledb.compress);
-select add_compression_policy('test_table_int', 2::int) AS compressjob_id
-\gset
+--compression policy for smallint, integer or bigint based partition hypertable
```
Comment (gayyappan) [inline tsl/test/sql/compression_bgw.sql:77]: Could you add this for the distributed hypertable case as well?

**Review by gayyappan — COMMENTED** [review]
Changes look good to me. Request for some additional tests with distributed hypertables.

File: tsl/test/sql/compression_bgw.sql (hunk 2 above)
Comment (fabriziomello) [reply tsl/test/sql/compression_bgw.sql:77]: Added!

**Comment by fabriziomello** [comment]
> Changes look good to me. Request for some additional tests with distributed hypertables.

Added more tests!

**Review by gayyappan — APPROVED** [review]
