### PR TITLE
Handle DST changes in gapfill

### LINKED ISSUE #6344: [Bug]: time_bucket_gapfill with timezones doesn't handle daylight savings
### What type of bug is this?

Incorrect result

### What subsystems and features are affected?

Gapfill

### What happened?

When `time_bucket_gapfill` with the optional timezone argument is used on a period which includes a switch between normal and daylight savings time, the gapfill starts in one mode (DST or not) and stays in it for the remainder of gapfills. 
i.e. for the query
```
SELECT
    time_bucket_gapfill('1 month', "timestamp", 'Europe/Berlin','2023-05-01 05:00:00.000', '2023-12-01 05:00:00.000') AS bucket,
    avg(speed) AS value,
    "guid"
FROM
    "events"
WHERE
    "guid" = '8412b80...'
    AND "timestamp" >= '2023-05-01 05:00:00.000'
    AND "timestamp" <= '2023-12-01 05:00:00.000'
GROUP BY
    "guid", "bucket"
ORDER BY
    "bucket" ASC;
```
We can see three issues manifest in the result bellow:

1. Since the bucket size is one month, the buckets are to start at midnight of the `Europe/Berlin` timezone which is 23:00 of the previous day by UTC time. The first three buckets are correct, but the April bucket should have DST applied and thus start at 22:00 like the last three results in the first image.
2. The gapfill continues beyond the buckets which have data and have no need for gapfilling as can be seen in the highlighted results in the first image. This may be due to the bucket timestamps being misaligned by one hour and thus not equal.
3. The duplicate buckets break sorting as can be in the last nine buckets. This happens despite the query clearly having an ORDER BY clause. If an additional order by value is added, the buckets get properly sorted.

image

To confirm that the gapfill ignores DST and just always uses the same bucket hours, we can change the lower `timestamp` limit to May and get all gapfilled buckets starting at 22:00. We also get the same sorting and duplicate problems as before, but now the gapfilled dates are wrong as well and are all set to the 30th of the month.

image

The expected behavior would be for the gapfill bucket times to follow the same logic as the normal `time_bucket` buckets and have daylight savings offsets applied to them. I believe this would then solve the issue of multiple buckets for the same bucket period (in this case month), though I'm not sure why the sorting gets broken.

### TimescaleDB version affected

2.12.2

### PostgreSQL version used

13.12

### What operating system did you use?

WSL Ubuntu 18.04 LTS x64

### What installation method did you use?

Docker

### What platform did you run on?

On prem/Self-hosted

### Relevant log output and stack trace

_No response_

### How can we reproduce the bug?

```bash
1. Create or have a table with a timestamp column and a value column to aggregate over.
2. Have at least one row in the table that's within the queried period
3. Use a `time_bucket_gapfill` function with timezones in a query over a period which includes a daylight savings switch (2023-03-26 for Europe/Berlin). Bucket can be as little as 1 day to manifest the issue.
```

### PR DESCRIPTION
**Pull request by antekresic**
This change makes gapfill calculate timezone offsets like we do in time_bucket when there is a supplied timezone. Without this, timezones would not align and we get timestamp mismatches which cause double entries for a single bucket.

Fixes #6344

### CODE REVIEW

File: tsl/src/nodes/gapfill/gapfill_exec.c [hunk 1]
```diff
@@ -656,10 +656,32 @@ gapfill_advance_timestamp(GapFillState *state)
...
 			 */
-			next = DirectFunctionCall2(state->have_timezone ? timestamptz_pl_interval :
-															  timestamp_pl_interval,
-									   TimestampTzGetDatum(state->gapfill_start),
-									   IntervalPGetDatum(state->next_offset));
+			if (state->have_timezone)
+			{
+				bool isnull;
+				/* TODO: optimize by constifying and caching the datum if possible */
+				Datum tzname = gapfill_exec_expr(state, get_timezone_arg(state), &isnull);
```
Comment (antekresic) [inline tsl/src/nodes/gapfill/gapfill_exec.c:663]: Opted for simple approach, we can optimize the performance if necessary later on.

**Review by konskov — APPROVED** [review]

File: tsl/src/nodes/gapfill/gapfill_exec.c (hunk 1 above)
Comment (akuzm) [reply tsl/src/nodes/gapfill/gapfill_exec.c:663]: What is needed for caching, something more than saving this datum in the GapFillState?

**Review by akuzm — APPROVED** [review]

**Comment by intermittentnrg** [comment]
It seems likely that this PR, or something else introduced in 2.13,  introduced the bug reported in #6788
