### PR TITLE
Fix hypertable expansion for UNION ALL

### LINKED ISSUE #1837: Union All is broken on 1.7.0
**Relevant system information:**
 - OS: Fedora 31
 - PostgreSQL version (output of `postgres --version`): 11.7 / 12.2
 - TimescaleDB version (output of `\dx` in `psql`): 1.7.0
 - Installation method: using Docker

**Describe the bug**
**union all** between a regulartable and hypertable is not working. where as **union** seems to be working fine. 
This works:
1. pg 11.x + timescaledb 1.6.1 - OK
2. pg 11.x + timescaledb 1.7.0 - returns only one row from the regulartable
3. pg 12.x + timescaledb 1.7.0 - returns an exception

> unexpected field count in "D" message

**To Reproduce**
```
create table regulartable (time timestamptz, value numeric);
create table hypertable (time timestamptz, value numeric);
select create_hypertable('hypertable', 'time');
insert into hypertable values(now(), 1);
insert into regulartable values(now(), 2);

select time, value from regulartable 
union all
select time, value from hypertable ;
```

**Expected behavior**
A final table with two rows with both the rows present. 

**Actual behavior**
Depending upon the PG version, either an error or incomplete data

**Additional context**
union seems to be working fine

### PR DESCRIPTION
**Pull request by svenklemm**
When doing a UNION ALL query between a hypertable and a regular
table the hypertable would not get expanded leading to
no data of the hypertable included in the resultset.

Fixes #1837

### CODE REVIEW

File: src/planner.c [hunk 1]
```diff
@@ -417,14 +417,30 @@ classify_relation(const PlannerInfo *root, const RelOptInfo *rel, Hypertable **p
...
+			 * An entry of reloptkind RELOPT_OTHER_MEMBER_REL might still
+			 * be a hypertable here if it was pulled up from a subquery
+			 * as happens with UNION ALL for example. So we have to
+			 * check for that to properly detect that pattern.
+			 */
+			if (parent_rte->rtekind == RTE_SUBQUERY)
+			{
+				ht = get_hypertable(rte->relid, CACHE_FLAG_CHECK);
+				if (ht != NULL)
+					reltype = TS_REL_HYPERTABLE;
```
Comment (erimatnor) [inline src/planner.c:431]: This is probably the correct classification. But could this be classified as `TS_REL_HYPERTABLE_CHILD` given that the hypertable is child of the subquery? Or should we even another classification for this case?

File: test/expected/plan_expand_hypertable-10.out [hunk 2]
```diff
@@ -2293,6 +2293,178 @@ INSERT INTO outer_join_2 VALUES(1,'a');
 
 DROP TABLE outer_join_1;
 DROP TABLE outer_join_2;
+-- test UNION
+SELECT time FROM regular_timestamptz UNION SELECT time FROM metrics_timestamptz ORDER BY 1;
```
Comment (erimatnor) [inline test/expected/plan_expand_hypertable-10.out:2297]: Good that we have a test for this now.

File: test/expected/plan_expand_hypertable-10.out [hunk 3]
```diff
@@ -2293,6 +2293,178 @@ INSERT INTO outer_join_2 VALUES(1,'a');
...
+ Thu Jan 27 00:00:00 2000 PST
+ Fri Jan 28 00:00:00 2000 PST
+ Sat Jan 29 00:00:00 2000 PST
+ Sun Jan 30 00:00:00 2000 PST
+ Mon Jan 31 00:00:00 2000 PST
+ Tue Feb 01 00:00:00 2000 PST
+(32 rows)
+
+-- test UNION ALL
+SELECT time FROM regular_timestamptz UNION ALL SELECT time FROM metrics_timestamptz ORDER BY 1;
```
Comment (mkindahl) [inline test/expected/plan_expand_hypertable-10.out:2335]: It might be sufficient to just count the number of rows rather than show all rows. Many rows in the test output just make it harder to check for the error when something goes wrong.

Comment (svenklemm) [reply test/expected/plan_expand_hypertable-10.out:2335]: It is not sufficient, using count will mask errors in target list handling, it also changes the plan to a very different shape.

File: src/planner.c (hunk 1 above)
Comment (svenklemm) [reply src/planner.c:431]: TS_REL_HYPERTABLE_CHILD is the result of hypertable expansion done by postgres because it includes the base table as expanded child (we used to do the same some time ago but haven't for a while). For TS_REL_HYPERTABLE_CHILD no further action is needed while TS_REL_HYPERTABLE still needs expansion which is the case for hypertable pulled up from subqueries. So I think TS_REL_HYPERTABLE is correct, we could potentially add a new classification but I'm not sure what we would gain from it, it would certainly make this patch much bigger.
