### PR TITLE
Fix memory context bug executing TRUNCATE.

### LINKED ISSUE #3182: TRUNCATE table in a loop
When using TRUNCATE in a loop, it seems that TRUNCATE only works one time and does not do anything after.
We are using PostgresSQL 13.2 with Timescale 2.2
Here is the code to reproduce the same issue

```
DO $$
DECLARE 
  n_record   int;
BEGIN
  CREATE TABLE IF NOT EXISTS test_truncate ( id int );
  FOR i IN 1..10 LOOP
    INSERT INTO test_truncate ( id ) SELECT * FROM generate_series( 1, 100 );
    SELECT COUNT(*) INTO n_record FROM test_truncate;
    RAISE NOTICE 'Before Truncate : %', n_record;
  
    TRUNCATE test_truncate;
--    DELETE FROM test_truncate;
  
    SELECT COUNT(*) INTO n_record FROM test_truncate;
    RAISE NOTICE 'After Truncate : %', n_record;
  
  END LOOP;
  DROP TABLE test_truncate;
END $$; 
```

### LINKED ISSUE #3580: Segfault during TRUNCATE restart Identity
**Relevant system information:**
OS: [e.g. Ubuntu 16.04, Windows 10 x64, etc]: Docker / timescale/timescaledb:2.4.1-pg13

PostgreSQL version (output of postgres --version): 13.4
TimescaleDB version (output of \dx in psql): 2.4.1
Installation method: [e.g., "using Docker", "apt install", "source"] : "Using Docker"

**Describe the bug**
Issuing a truncate command causes segfault which is of random occurrence. Sometimes, it happens on the first attempt of TRUNCATE but sometimes calling the same TRUNCATE command again causes the server to crash. The command looks like this:
```
TRUNCATE TABLE "transaction_records_history","order_records_history","settlement_records_history","records_history"  RESTART IDENTITY;
```
If you choose to avoid any of the tables from the above command, the segfault doesn't occur and which is why I wasn't able to isolate the segfault with specific tables/instructions.

**To Reproduce**
[SQL Instructions](https://github.com/timescale/Support-Dev-Collab/files/7075802/modified_dump_lo.txt) 

**Expected behavior**
The truncate should work as expected 

**Actual behavior**
The truncate causes segfault 

**Screenshots**

**Additional context**
Coredump:
```
Core was generated by `postgres: m0jesnqad4-an: tsdbadmin tsdb 172.20.33.232(53510) TRUNCATE TABLE   '.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f25dc186ae3 in process_truncate (args=0x7ffcec35ae90) at /build/timescaledb/src/process_utility.c:931
931	/build/timescaledb/src/process_utility.c: No such file or directory.
(gdb) bt
#0  0x00007f25dc186ae3 in process_truncate (args=0x7ffcec35ae90) at /build/timescaledb/src/process_utility.c:931
#1  0x00007f25dc185cca in process_ddl_command_start (args=0x7ffcec35ae90) at /build/timescaledb/src/process_utility.c:3784
#2  timescaledb_ddl_command_start (pstmt=0x55bd33de5f08, query_string=<optimized out>, context=PROCESS_UTILITY_QUERY, params=0x0, queryEnv=<optimized out>, dest=0x55bd32b5de20 <spi_printtupDR>, completion_tag=0x7ffcec35afb0)
    at /build/timescaledb/src/process_utility.c:4019
#3  0x000055bd32696edf in _SPI_execute_plan (plan=plan@entry=0x55bd33de5a58, paramLI=paramLI@entry=0x0, snapshot=snapshot@entry=0x0, crosscheck_snapshot=crosscheck_snapshot@entry=0x0, read_only=read_only@entry=false,
    fire_triggers=fire_triggers@entry=true, tcount=<optimized out>) at ./build/../src/backend/executor/spi.c:2335
#4  0x000055bd32697794 in SPI_execute_plan_with_paramlist (plan=0x55bd33de5a58, params=0x0, read_only=<optimized out>, tcount=tcount@entry=0) at ./build/../src/backend/executor/spi.c:576
#5  0x00007f25dc04673f in exec_stmt_execsql (estate=estate@entry=0x7ffcec35b530, stmt=stmt@entry=0x55bd33dcd4d8) at ./build/../src/pl/plpgsql/src/pl_exec.c:4234
#6  0x00007f25dc04731b in exec_stmt (estate=estate@entry=0x7ffcec35b530, stmt=0x55bd33dcd4d8) at ./build/../src/pl/plpgsql/src/pl_exec.c:2053
#7  0x00007f25dc04a756 in exec_stmts (estate=0x7ffcec35b530, stmts=0x55bd33dcd528) at ./build/../src/pl/plpgsql/src/pl_exec.c:1944
#8  0x00007f25dc04ab1e in exec_stmt_block (estate=estate@entry=0x7ffcec35b530, block=block@entry=0x55bd33dcd5d8) at ./build/../src/pl/plpgsql/src/pl_exec.c:1885
#9  0x00007f25dc0480fb in exec_stmt (estate=estate@entry=0x7ffcec35b530, stmt=0x55bd33dcd5d8) at ./build/../src/pl/plpgsql/src/pl_exec.c:1977
#10 0x00007f25dc04b309 in plpgsql_exec_trigger (func=func@entry=0x55bd33d0a490, trigdata=0x7ffcec35b920) at ./build/../src/pl/plpgsql/src/pl_exec.c:1027
#11 0x00007f25dc055464 in plpgsql_call_handler (fcinfo=0x7ffcec35b7f0) at ./build/../src/pl/plpgsql/src/pl_handler.c:256
#12 0x000055bd32634963 in ExecCallTriggerFunc (trigdata=trigdata@entry=0x7ffcec35b920, tgindx=tgindx@entry=0, finfo=0x55bd33e53578, instr=0x0, per_tuple_context=0x55bd33dba530) at ./build/../src/backend/commands/trigger.c:2084
#13 0x000055bd3263b5cb in ExecBSTruncateTriggers (estate=estate@entry=0x55bd33dd71b8, relinfo=relinfo@entry=0x55bd33e46958) at ./build/../src/backend/commands/trigger.c:2907
#14 0x000055bd32626bd2 in ExecuteTruncateGuts (explicit_rels=explicit_rels@entry=0x55bd33de9538, relids=<optimized out>, relids@entry=0x55bd33e46d68, relids_logged=relids_logged@entry=0x0, behavior=DROP_RESTRICT,
    restart_seqs=<optimized out>) at ./build/../src/backend/commands/tablecmds.c:1821
#15 0x000055bd3262702d in ExecuteTruncate (stmt=stmt@entry=0x55bd33c8f9f0) at ./build/../src/backend/commands/tablecmds.c:1661
#16 0x000055bd327d90b8 in standard_ProcessUtility (pstmt=0x55bd33c8faa0,
    queryString=0x55bd33c8ed08 "TRUNCATE TABLE \"transaction_records_history\",\"order_records_history\",\"settlement_records_history\",\"records_history\"  RESTART IDENTITY;", context=PROCESS_UTILITY_TOPLEVEL, params=0x0, queryEnv=0x0,
    dest=0x55bd33c8fd60, qc=0x7ffcec35c2f0) at ./build/../src/backend/tcop/utility.c:716
#17 0x00007f25fed9eae2 in loader_process_utility_hook (pstmt=0x55bd33c8faa0,
    query_string=0x55bd33c8ed08 "TRUNCATE TABLE \"transaction_records_history\",\"order_records_history\",\"settlement_records_history\",\"records_history\"  RESTART IDENTITY;", context=<optimized out>, params=0x0,
    queryEnv=<optimized out>, dest=<optimized out>, completion_tag=0x7ffcec35c2f0) at /build/timescaledb/src/loader/loader.c:502
#18 0x00007f25fed945d6 in pgss_ProcessUtility (pstmt=0x55bd33c8faa0,
    queryString=0x55bd33c8ed08 "TRUNCATE TABLE \"transaction_records_history\",\"order_records_history\",\"settlement_records_history\",\"records_history\"  RESTART IDENTITY;", context=PROCESS_UTILITY_TOPLEVEL, params=0x0, queryEnv=0x0,
    dest=0x55bd33c8fd60, qc=0x7ffcec35c2f0) at ./build/../contrib/pg_stat_statements/pg_stat_statements.c:1156
--Type <RET> for more, q to quit, c to continue without paging--
#19 0x00007f25dc1c28cd in ?? () from /usr/lib/postgresql/13/lib/plugins/pgextwlist.so
#20 0x00007f25dc185b73 in prev_ProcessUtility (args=<optimized out>) at /build/timescaledb/src/process_utility.c:89
#21 0x00007f25dc186be9 in process_truncate (args=0x7ffcec35bfd0) at /build/timescaledb/src/process_utility.c:1027
#22 0x00007f25dc185cca in process_ddl_command_start (args=0x7ffcec35bfd0) at /build/timescaledb/src/process_utility.c:3784
#23 timescaledb_ddl_command_start (pstmt=0x55bd33c8faa0, query_string=<optimized out>, context=PROCESS_UTILITY_TOPLEVEL, params=0x0, queryEnv=<optimized out>, dest=0x55bd33c8fd60, completion_tag=0x7ffcec35c2f0)
    at /build/timescaledb/src/process_utility.c:4019
#24 0x000055bd327d741c in PortalRunUtility (portal=portal@entry=0x55bd33d3d688, pstmt=pstmt@entry=0x55bd33c8faa0, isTopLevel=isTopLevel@entry=true, setHoldSnapshot=setHoldSnapshot@entry=false, dest=0x55bd33c8fd60, qc=0x7ffcec35c2f0)
    at ./build/../src/backend/tcop/pquery.c:1145
#25 0x000055bd327d7540 in PortalRunMulti (portal=portal@entry=0x55bd33d3d688, isTopLevel=isTopLevel@entry=true, setHoldSnapshot=setHoldSnapshot@entry=false, dest=dest@entry=0x55bd33c8fd60, altdest=altdest@entry=0x55bd33c8fd60,
    qc=qc@entry=0x7ffcec35c2f0) at ./build/../src/backend/tcop/pquery.c:1301
#26 0x000055bd327d79b8 in PortalRun (portal=0x55bd33d3d688, count=9223372036854775807, isTopLevel=<optimized out>, run_once=<optimized out>, dest=0x55bd33c8fd60, altdest=0x55bd33c8fd60, qc=0x7ffcec35c2f0)
    at ./build/../src/backend/tcop/pquery.c:786
#27 0x000055bd327d3595 in exec_simple_query (query_string=<optimized out>) at ./build/../src/backend/tcop/postgres.c:1239
#28 0x000055bd327d5143 in PostgresMain (argc=<optimized out>, argv=<optimized out>, dbname=<optimized out>, username=<optimized out>) at ./build/../src/backend/tcop/postgres.c:4339
#29 0x000055bd32754bcd in BackendRun (port=0x55bd33cd9a90, port=0x55bd33cd9a90) at ./build/../src/backend/postmaster/postmaster.c:4526
#30 BackendStartup (port=0x55bd33cd9a90) at ./build/../src/backend/postmaster/postmaster.c:4210
#31 ServerLoop () at ./build/../src/backend/postmaster/postmaster.c:1739
#32 0x000055bd32755b41 in PostmasterMain (argc=17, argv=<optimized out>) at ./build/../src/backend/postmaster/postmaster.c:1412
#33 0x000055bd3249ff4f in main (argc=17, argv=0x55bd33c87c60) at ./build/../src/backend/main/main.c:210

```

### LINKED ISSUE #3622: Truncate table within function call take no effect (Timescale breaks truncate!)
**Relevant system information:**
 - OS: CentOS 8
 - PostgreSQL version 13.4
 - TimescaleDB version 2.4.1
 - Installation method: pgdg rpm package

**Describe the bug**
When Timescale is installed (create extension timescaledb), then truncate commands within functions take no effects on standard tables. Truncate is executed (without errors or warnings), but data in tables stay in place. This is a serious issue because it affects core PostgreSQL behavior with unpredictable consequences.

It should be simple to reproduce:

```
create table foo(bar int);
insert into foo (bar) values (1);

do $$
begin
  truncate table foo;
end $$; 
```

Probably related to #3182

### PR DESCRIPTION
**Pull request by fabriziomello**
Inside the `process_truncate` function is created a new relations list
removing the distributed hypertables and this new list is assigned to
the current statement relation list. This new list is allocated into
the `PortalContext` that is destroyed at the end of the statement
execution.

The problem arise on the subsequent `TRUNCATE` call because the
compiled plpgsql code is cached into another memory context and the
elements of the relations inside this cache is pointing to an invalid
memory area because the `PortalContext` is destroyed.

Fixed it by allocating the new relations list to the same memory
context of the original list.

Fixes #3580, fixes #3622, fixes #3182

### CODE REVIEW

**Review by erimatnor — APPROVED** [review]

File: tsl/src/remote/dist_ddl.c [hunk 1]
```diff
@@ -471,19 +471,20 @@ dist_ddl_preprocess(ProcessUtilityArgs *args)
...
-			 * process_utility.c, so the list might actually be empty. */
+
+			/* Calculate number of regular tables. Note that number of
+			 * distributed hypertables should be the same of the relations
+			 * list */
 			unsigned int num_regular_tables =
 				list_length(stmt->relations) - num_hypertables - num_dist_hypertable_members;
 
-			Assert(num_regular_tables <= list_length(stmt->relations));
+			Assert(num_regular_tables == list_length(stmt->relations));
```
Comment (mkindahl) [inline tsl/src/remote/dist_ddl.c:481]: Why are these going to be equal? If there are hypertables in the list, I would assume that the number of regular tables can be less than the total number of relations.

**Review by mkindahl — COMMENTED** [review]
We do not use a `.` last in the title line.

File: test/expected/truncate.out [hunk 2]
```diff
@@ -152,6 +152,54 @@ SELECT * FROM truncate_normal;
...
+-- fix for bug #3580
+CREATE TABLE truncate_nested (color int);
+INSERT INTO truncate_nested VALUES (2);
+SELECT * FROM truncate_normal, truncate_nested;
+ color | color 
+-------+-------
+     1 |     2
+(1 row)
+
+CREATE FUNCTION truncate_nested()
```
[the remark this answers is not in the document]
Comment (fabriziomello) [reply test/expected/truncate.out:164]: Fixed!

File: tsl/src/remote/dist_ddl.c (hunk 1 above)
Comment (fabriziomello) [reply tsl/src/remote/dist_ddl.c:481]: Ooops... forgot to revert it during coding!

File: src/process_utility.c [hunk 3]
```diff
@@ -1008,15 +1010,12 @@ process_truncate(ProcessUtilityArgs *args)
...
-
-	if (stmt->relations != NIL)
+	/* Truncate only regular tables */
+	if (relations != NIL)
 	{
-		/* Call standard PostgreSQL handler for remaining tables */
-		prev_ProcessUtility(args);
+		TruncateStmt relations_stmt = *stmt;
+		relations_stmt.relations = relations;
+		ExecuteTruncate(&relations_stmt);
```
Comment (svenklemm) [inline src/process_utility.c:1018]: This will not play nicely with other extensions using this hook

**Comment by fabriziomello** [comment]
> We do not use a `.` last in the title line.

Fixed!

File: src/process_utility.c (hunk 3 above)
Comment (fabriziomello) [reply src/process_utility.c:1018]: Can you please elaborate a bit more the problem you're talking about?

Comment (svenklemm) [reply src/process_utility.c:1018]: prev_ProcessUtility calls the processutility hook when another extension register the hook before us, with this change it wouldnt be called anymore

Comment (fabriziomello) [reply src/process_utility.c:1018]: The problem you're talking about is because the way we fixed it we're finishing the `ProcessUtility` flow.

Comment (fabriziomello) [reply src/process_utility.c:1018]: @svenklemm and I discovered another bug on `TRUNCATE` against the master:

```sql
fabrizio=# CREATE EXTENSION timescaledb;
WARNING:  
WELCOME TO
 _____ _                               _     ____________  
|_   _(_)                             | |    |  _  \ ___ \ 
  | |  _ _ __ ___   ___  ___  ___ __ _| | ___| | | | |_/ / 
  | | | |  _ ` _ \ / _ \/ __|/ __/ _` | |/ _ \ | | | ___ \ 
  | | | | | | | | |  __/\__ \ (_| (_| | |  __/ |/ /| |_/ /
  |_| |_|_| |_| |_|\___||___/\___\__,_|_|\___|___/ \____/
               Running version 2.5.0-dev
For more information on TimescaleDB, please visit the following links:

 1. Getting started: https://docs.timescale.com/timescaledb/latest/getting-started
 2. API reference documentation: https://docs.timescale.com/api/latest
 3. How TimescaleDB is designed: https://docs.timescale.com/timescaledb/latest/overview/core-concepts

Note: Please enable telemetry to help us improve our product by running: ALTER DATABASE "fabrizio" SET timescaledb.telemetry_level = 'basic';

CREATE EXTENSION
fabrizio=# SELECT 'foo'::regclass;
ERROR:  relation "foo" does not exist
LINE 1: SELECT 'foo'::regclass;
               ^
fabrizio=# TRUNCATE foo;
TRUNCATE TABLE
```

The `TRUNCATE` command should fail here because the relation `foo` does not exist.

**Comment by fabriziomello** [comment]
Fixed it by allocating the new relations list to the `TopMemoryContext` just when it changes.

File: src/process_utility.c [hunk 4]
```diff
@@ -908,11 +908,13 @@ handle_truncate_hypertable(ProcessUtilityArgs *args, TruncateStmt *stmt, Hyperta
 static DDLResult
 process_truncate(ProcessUtilityArgs *args)
 {
+	MemoryContext oldctx = MemoryContextSwitchTo(TopMemoryContext);
```
[the remark this answers is not in the document]
Comment (fabriziomello) [reply src/process_utility.c]: Changed to switch to the same memory context of the parse tree.

**Review by svenklemm — COMMENTED** [review]
Maybe we can make the memorycontext switches more surgical and only run the stuff that actually needs to be in the other memorycontext in that context instead of only switching once at top of function.

**Comment by fabriziomello** [comment]
> Maybe we can make the memorycontext switches more surgical and only run the stuff that actually needs to be in the other memorycontext in that context instead of only switching once at top of function.

But I did it... did you see? https://github.com/timescale/timescaledb/pull/3626/files#diff-9816cecf26e0199a4235ff8b1ac830af68a06ebee40a46421d4e877c81c4e16bR1026
