### PR TITLE
Fix compressed chunk check when disabling compression

### LINKED ISSUE #2844: Unable to disable compression on hypertable after decompressing all compressed chunks
**Relevant system information:**
- OS: Ubuntu 20.04.1
- PostgreSQL version (output of postgres --version): 12.5
- TimescaleDB version (output of \dx in psql): 2.0.0
- Installation method: using Docker

**Describe the bug**
Attempting to perform an `ALTER TABLE` to disable compression on a compressed hypertable after decompressing all the compressed chunks fails.
This behaviour seems to be related with the dropped chunks' metadata kept in `_timescaledb_catalog.chunk`. I could only reproduce the issue on a hypertable having at least, one continuous aggregate (check documentation for method `chunk_tuple_delete` in [this](https://github.com/timescale/timescaledb/blob/master/src/chunk.c) file).

**To Reproduce**
Check the attached [SQL script](https://github.com/timescale/timescaledb/files/5837753/bug-reproduce.txt) which provides a minimal example. It can be tested on a brand-new TimescaleDB v2.0.0 Docker container, on the default database.

**Expected behavior**
After decompressing all the compressed chunks in the hypertable, performing an:

```sql
ALTER TABLE <table> SET (timescaledb.compress = FALSE);
```
should work, but it fails.

**Actual behavior**
The `ALTER TABLE` command fails with the following error:
```
> ALTER TABLE test SET (timescaledb.compress = FALSE);
ERROR:  cannot change configuration on already compressed chunks
DETAIL:  There are compressed chunks that prevent changing the existing compression configuration.
```

**Possible bugfix**
I've been investigating this further (checking the TimescaleDB C code that raises the following message):

>ERROR: cannot change configuration on already compressed chunks
>  Detail: There are compressed chunks that prevent changing the existing compression configuration.

This message seems to be generated by function `check_modify_compression_options` in [this](https://github.com/timescale/timescaledb/blob/master/tsl/src/compression/create.c) file. Flag `compressed_chunk_exists` raises this error, and for it to be set compression must be enabled and at least one chunk must be compressed (checked using function `ts_chunk_exists_with_compression` from [this](https://github.com/timescale/timescaledb/blob/master/src/chunk.c) file).
From what can I see, this function just scans relation `_timescaledb_catalog.chunk`, searching for a row for the given hypertable that does not have attribute `compressed_chunk_id` as `NULL`. However, it **does not check whether the chunk has been dropped**.

This should be fixed by applying a filter in the scan performed by function `ts_chunk_exists_with_compression` to exclude dropped chunks.

### PR DESCRIPTION
**Pull request by svenklemm**
The check for existence of compressed chunks when disabling
compression would not ignore dropped chunks making it impossible
to disable compression on hypertables with continuous aggregates
that had dropped chunks.
This patch ignores dropped chunks in this check and also sets
compressed_chunk_id to NULL in the metadata for deleted chunks.

Fixes #2844

### CODE REVIEW

File: src/chunk.c [hunk 1]
```diff
@@ -2606,6 +2606,7 @@ chunk_tuple_delete(TupleInfo *ti, DropBehavior behavior, bool preserve_chunk_cat
 
 		Assert(!form.dropped);
 
+		form.compressed_chunk_id = INVALID_CHUNK_ID;
```
Comment (gayyappan) [inline src/chunk.c:2609]: compressed_chunk_id should be marked as NULL.

File: src/chunk.c [hunk 2]
```diff
@@ -2728,10 +2729,15 @@ ts_chunk_exists_with_compression(int32 hypertable_id)
 	init_scan_by_hypertable_id(&iterator, hypertable_id);
 	ts_scanner_foreach(&iterator)
 	{
-		bool isnull =
+		bool isnull_dropped;
+		bool isnull_chunk_id =
```
Comment (gayyappan) [inline src/chunk.c:2733]: I don't think we need these changes if the compressed_chunk_id is marked correctly as null (when the chunk is dropped but catalog entry is preserved)

File: src/chunk.c [hunk 3]
```diff
@@ -2728,10 +2729,15 @@ ts_chunk_exists_with_compression(int32 hypertable_id)
...
 			slot_attisnull(ts_scan_iterator_slot(&iterator), Anum_chunk_compressed_chunk_id);
+		bool dropped = DatumGetBool(
```
Comment (gayyappan) [inline src/chunk.c:2735]: Also probably need a script to fix this for chunks that are marked as dropped but have compressed_chunk_id still set incorrectly.

**Review by gayyappan — CHANGES_REQUESTED** [review]

File: src/chunk.c (hunk 2 above)
Comment (svenklemm) [reply src/chunk.c:2733]: I think excluding chunks marked as dropped is more important than the other change

File: src/chunk.c (hunk 1 above)
Comment (svenklemm) [reply src/chunk.c:2609]: INVALID_CHUNK_ID will turn into database NULL on write (in src/chunk.c)

File: src/chunk.c (hunk 2 above)
Comment (gayyappan) [reply src/chunk.c:2733]: yes, makes it clearer

**Review by gayyappan — APPROVED** [review]

**Review by mkindahl — COMMENTED** [review]
I also think we need an update script here.

File: sql/updates/latest-dev.sql [hunk 4]
```diff
@@ -0,0 +1,4 @@
+
+-- set compressed_chunk_id to NULL for dropped chunks
+UPDATE _timescaledb_catalog.chunk SET compressed_chunk_id = NULL WHERE dropped = true AND compressed_chunk_id IS NOT NULL;
```
Comment (mkindahl) [inline sql/updates/latest-dev.sql:3]: Won't this orphan a compressed chunk if the uncompressed chunk is marked as dropped? In short, what if `compressed_chunk_id` refers to a chunk that actually exists?

Comment (svenklemm) [reply sql/updates/latest-dev.sql:3]: no we only keep metadata of uncompressed chunk

**Review by mkindahl — APPROVED** [review]
