### PR TITLE
Fix trigger relcache handling for COPY 

### LINKED ISSUE #351: COPY triggers "WARNING: relcache reference leak"
PostgreSQL 10.1, timescaledb 0.7.1.

COPYing data to a timescale table always (if the `COPY` creates a new underlying hyperchunk or not) triggers a `relcache reference leak` warning (https://github.com/postgres/postgres/blob/master/src/backend/utils/resowner/resowner.c#L528):

```
=> \d+ data_records
                                       Table "public.data_records"
    Column     |       Type       | Collation | Nullable | Default | Storage | Stats target | Description 
---------------+------------------+-----------+----------+---------+---------+--------------+-------------
 plc_sensor_id | integer          |           | not null |         | plain   |              | 
 time          | bigint           |           | not null |         | plain   |              | 
 value         | double precision |           | not null |         | plain   |              | 
Indexes:
    "data_records_plc_sensor_id_time_index" btree (plc_sensor_id, "time")
    "data_records_time_idx" btree ("time" DESC)
    "data_records_time_plc_sensor_id_index" btree ("time", plc_sensor_id)
Foreign-key constraints:
    "data_records_plc_sensor_id_fkey" FOREIGN KEY (plc_sensor_id) REFERENCES plc_sensors(id)
Child tables: _timescaledb_internal._hyper_7_36_chunk

=> \copy data_records (time, plc_sensor_id, value) FROM '/tmp/foo.csv' DELIMITER ',';
WARNING:  relcache reference leak: relation "_hyper_7_37_chunk" not closed
COPY 100
=> \copy data_records (time, plc_sensor_id, value) FROM '/tmp/foo.csv' DELIMITER ',';
WARNING:  relcache reference leak: relation "_hyper_7_37_chunk" not closed
COPY 100
=> \copy data_records (time, plc_sensor_id, value) FROM '/tmp/foo.csv' DELIMITER ',';
WARNING:  relcache reference leak: relation "_hyper_7_37_chunk" not closed
COPY 100
=> \d+ data_records
                                       Table "public.data_records"
    Column     |       Type       | Collation | Nullable | Default | Storage | Stats target | Description 
---------------+------------------+-----------+----------+---------+---------+--------------+-------------
 plc_sensor_id | integer          |           | not null |         | plain   |              | 
 time          | bigint           |           | not null |         | plain   |              | 
 value         | double precision |           | not null |         | plain   |              | 
Indexes:
    "data_records_plc_sensor_id_time_index" btree (plc_sensor_id, "time")
    "data_records_time_idx" btree ("time" DESC)
    "data_records_time_plc_sensor_id_index" btree ("time", plc_sensor_id)
Foreign-key constraints:
    "data_records_plc_sensor_id_fkey" FOREIGN KEY (plc_sensor_id) REFERENCES plc_sensors(id)
Child tables: _timescaledb_internal._hyper_7_36_chunk,
              _timescaledb_internal._hyper_7_37_chunk

```

### PR DESCRIPTION
**Pull request by cevian**
Previously trigger relcache entries were not always freed during
COPY commands in PG10. This PR fixes that.

Fixes #351.

### CODE REVIEW

File: src/copy.c [hunk 1]
```diff
@@ -361,6 +361,12 @@ timescaledb_CopyFrom(CopyState cstate, Relation main_rel, List *range_table, Hyp
 	ExecResetTupleTable(estate->es_tupleTable, false);
 
 	ExecCloseIndices(resultRelInfo);
+
+#if PG10
```
Comment (RobAtticus) [inline src/copy.c]: So I saw this on 9.6 as well. Should this be unguarded? or an alternative for 9.6 given?

Comment (erimatnor) [reply src/copy.c]: Yeah, we should definitely check whether this is a general thing.

Comment (cevian) [reply src/copy.c]: Fixed. Look again?

File: src/copy.c [hunk 2]
```diff
@@ -361,6 +361,30 @@ timescaledb_CopyFrom(CopyState cstate, Relation main_rel, List *range_table, Hyp
...
+	/* Close any trigger target relations */
+	ExecCleanUpTriggerState(estate);
+#elif PG96
+	{
+		/*
+		 * es_target_relations sometimes created in ExecGetTriggerResultRel on
+		 * chunks. During copy to regular tables, this never happens because
+		 * the relation always already exists for the regular table.
```
Comment (erimatnor) [inline src/copy.c]: Do you mean `ResultRelInfo` here instead of `relation`?
