### PR TITLE
Change ChunkAppend leader to use worker subplan

### LINKED ISSUE #1864: Filter with VIEW with hypertables + large array filtering + interval
**Relevant system information:**
 - OS: Ubuntu 18.04
 - PostgreSQL 11.7
 - TimescaleDB version 1.6
 - Installation method: Docker

**Describe the bug**
Case of use: We have a VIEW v AS (SELECT * FROM hypertable1 UNION SELECT * FROM hypertable2), keys device_id integer, sample_time timestamptz, value columns
Bug: We're trying to fetch
SELECT * FROM v
WHERE device_id = ANY(ARRAY[...])
AND sample_time >= '2020-04-26 America/Fortaleza'::timestamptz
AND sample_time < '2020-04-26 America/Fortaleza'::timestamptz + interval '1 day'
We noticed that when the array has 125 or less device_ids, the rows returns correctly (144 per device). When the array size is higher (our common use case is 156 device_ids), the query returns 0 rows.
When we change to
AND sample_time >= '2020-04-26 America/Fortaleza'::timestamptz
AND sample_time < '2020-04-27 America/Fortaleza'::timestamptz
the rows returns correctly with any array size. When we fetch directly from the hypertable2, it returns correctly too.
**To Reproduce**
Maybe creating separate hypertable using many key device_ids filtering should reproduce the error.

**Expected behavior**
I expect to return rows for any (or at least for very large) ARRAY sizes on clause ANY

**Actual behavior**
Summing interval may somehow make rows not to return.

**Screenshots**
image
image

### PR DESCRIPTION
**Pull request by WireBaron**
When running a parallel ChunkAppend query, the code would use a
subplan selection routine for the leader that would return an empty
slot unless it determined there were no workers started. While this
had the desired effect of forcing the workers to do the work of
evaluating the subnodes, returning an empty slot is not always safe.
In particular, Append nodes will interpret an empty slot as a sign
that a given subplan has completed, so a plan resulting in a
parallel MergeAppend under an Append node (very possible under a
UNION of hypertables) might fail to execute some or all of the
subplans.

This change modifies the ChunkAppend so that the leader uses the
same subplan function as the workers. This may result in the leader
being less responsive as it try to fetch a batch of results on its
own if no worker has any results yet. However, if this isn't the
desired behavior, PostgresQL already exposes a GUC option,
parallel_leader_participation, which will prevent the leader from
executing any subplans.

Fixes #1864

### CODE REVIEW

**Comment by svenklemm** [comment]
Please add to Bugfixes section in changelog

File: src/chunk_append/exec.c [hunk 1]
```diff
@@ -648,7 +634,12 @@ chunk_append_initialize_dsm(CustomScanState *node, ParallelContext *pcxt, void *
...
-	state->choose_next_subplan = choose_next_subplan_for_leader;
+	/*
+	 * Leader should use the same subplan selection as normal worker threads. If the user wishes to
+	 * disallow running plans on the leader they should do so via the parallel_leader_participation
+	 * GUC.
+	 */
+	state->choose_next_subplan = choose_next_subplan_for_worker;
 	state->current = INVALID_SUBPLAN_INDEX;
 	state->pcxt = pcxt;
 	state->pstate = pstate;
```
Comment (mkindahl) [inline src/chunk_append/exec.c:645]: This is now duplicated code in both `chunk_append_initialize_dsm` and `chunk_append_initialize_worker`. It would be a good idea to move this out of the functions and into the caller, or at least factor it out into a separate function.

**Comment by WireBaron** [comment]
> Please add to Bugfixes section in changelog

Done.

File: src/chunk_append/exec.c (hunk 1 above)
Comment (WireBaron) [reply src/chunk_append/exec.c:645]: I'm a bit reluctant to refactor this too much as there is a subtle interaction between these functions (initialize_worker uses the parallel state set up by initialize_dsm).  There's really only a couple lines that can be trivially refactored here.
