### PR TITLE
Fix index matching during DML decompression

### LINKED ISSUE #6367: [Bug]: Crash in compressed table if segmentby index is dropped
### What type of bug is this?

Crash

### What subsystems and features are affected?

Compression

### What happened?

If a compressed table is created with a segmentby column an index is created on the compressed table.

If that index is dropped (deliberately or accidentally) from the compressed table, a delete (or any mutation requiring a decompress) will cause a crash.

### TimescaleDB version affected

2.13

### PostgreSQL version used

15.4

### What operating system did you use?

Ubuntu 22.04

### What installation method did you use?

Source

### What platform did you run on?

On prem/Self-hosted

### Relevant log output and stack trace

```bash
(gdb) bt
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=139759077398336) at ./nptl/pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, threadid=139759077398336) at ./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=139759077398336, signo=signo@entry=6) at ./nptl/pthread_kill.c:89
#3  0x00007f1c31a42476 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#4  0x00007f1c31a287f3 in __GI_abort () at ./stdlib/abort.c:79
#5  0x0000558b8e4caa0d in ExceptionalCondition (conditionName=conditionName@entry=0x7f1c0a9d773d "matching_index_rel", errorType=errorType@entry=0x7f1c0a9cc562 "FailedAssertion", 
    fileName=fileName@entry=0x7f1c0a9d6830 "/home/mats/work/timescale/timescaledb+tam/tsl/src/compression/compression.c", lineNumber=lineNumber@entry=3312) at assert.c:69
#6  0x00007f1c0a94f35e in decompress_batches_for_update_delete (ht_state=0x558b8ed00398, chunk=chunk@entry=0x558b8ec2bc38, predicates=predicates@entry=0x558b8ec2b7d8, estate=0x558b8ed000b0)
    at /home/mats/work/timescale/timescaledb+tam/tsl/src/compression/compression.c:3312
#7  0x00007f1c0a94f5c0 in decompress_chunk_walker (ps=0x558b8ed015b0, ctx=0x7fffd29c11b0) at /home/mats/work/timescale/timescaledb+tam/tsl/src/compression/compression.c:3458
#8  0x0000558b8e22d607 in planstate_walk_members (planstates=0x558b8ed01e50, nplans=3, walker=walker@entry=0x7f1c0a94f3f5 <decompress_chunk_walker>, context=context@entry=0x7fffd29c11b0) at nodeFuncs.c:4196
#9  0x0000558b8e2326b8 in planstate_tree_walker (planstate=planstate@entry=0x558b8ed01c38, walker=walker@entry=0x7f1c0a94f3f5 <decompress_chunk_walker>, context=context@entry=0x7fffd29c11b0) at nodeFuncs.c:4118
#10 0x00007f1c0a94f495 in decompress_chunk_walker (ps=0x558b8ed01c38, ctx=ctx@entry=0x7fffd29c11b0) at /home/mats/work/timescale/timescaledb+tam/tsl/src/compression/compression.c:3487
#11 0x0000558b8e232666 in planstate_tree_walker (planstate=planstate@entry=0x558b8ed00898, walker=walker@entry=0x7f1c0a94f3f5 <decompress_chunk_walker>, context=context@entry=0x7fffd29c11b0) at nodeFuncs.c:4103
#12 0x00007f1c0a94f495 in decompress_chunk_walker (ps=0x558b8ed00898, ctx=ctx@entry=0x7fffd29c11b0) at /home/mats/work/timescale/timescaledb+tam/tsl/src/compression/compression.c:3487
#13 0x00007f1c0a9504f9 in decompress_target_segments (ht_state=<optimized out>) at /home/mats/work/timescale/timescaledb+tam/tsl/src/compression/compression.c:3392
#14 0x00007f1c0aa8f3b4 in ExecModifyTable (cs_node=0x558b8ed00398, pstate=0x558b8ed00898) at /home/mats/work/timescale/timescaledb+tam/src/nodes/hypertable_modify.c:822
#15 0x00007f1c0aa8fe9d in hypertable_modify_exec (node=<optimized out>) at /home/mats/work/timescale/timescaledb+tam/src/nodes/hypertable_modify.c:182
#16 0x0000558b8e1ce9ea in ExecCustomScan (pstate=0x558b8ed00398) at nodeCustom.c:115
#17 0x0000558b8e1b8baf in ExecProcNodeFirst (node=0x558b8ed00398) at execProcnode.c:464
#18 0x0000558b8e1b0ea4 in ExecProcNode (node=0x558b8ed00398) at ../../../src/include/executor/executor.h:262
#19 ExecutePlan (estate=estate@entry=0x558b8ed000b0, planstate=0x558b8ed00398, use_parallel_mode=<optimized out>, operation=operation@entry=CMD_DELETE, sendTuples=sendTuples@entry=false, numberTuples=numberTuples@entry=0, 
    direction=ForwardScanDirection, dest=0x558b8ec94420, execute_once=true) at execMain.c:1636
#20 0x0000558b8e1b107d in standard_ExecutorRun (queryDesc=0x558b8ed020c0, direction=ForwardScanDirection, count=0, execute_once=execute_once@entry=true) at execMain.c:363
#21 0x0000558b8e1b1147 in ExecutorRun (queryDesc=queryDesc@entry=0x558b8ed020c0, direction=direction@entry=ForwardScanDirection, count=count@entry=0, execute_once=execute_once@entry=true) at execMain.c:307
#22 0x0000558b8e37f639 in ProcessQuery (plan=plan@entry=0x558b8ec94388, sourceText=<optimized out>, params=0x0, queryEnv=0x0, dest=dest@entry=0x558b8ec94420, qc=qc@entry=0x7fffd29c16b0) at pquery.c:160
#23 0x0000558b8e380256 in PortalRunMulti (portal=portal@entry=0x558b8eb3da30, isTopLevel=isTopLevel@entry=true, setHoldSnapshot=setHoldSnapshot@entry=false, dest=dest@entry=0x558b8ec94420, altdest=altdest@entry=0x558b8ec94420, 
    qc=qc@entry=0x7fffd29c16b0) at pquery.c:1277
#24 0x0000558b8e38086a in PortalRun (portal=portal@entry=0x558b8eb3da30, count=count@entry=9223372036854775807, isTopLevel=isTopLevel@entry=true, run_once=run_once@entry=true, dest=dest@entry=0x558b8ec94420, 
    altdest=altdest@entry=0x558b8ec94420, qc=0x7fffd29c16b0) at pquery.c:791
#25 0x0000558b8e37c841 in exec_simple_query (query_string=query_string@entry=0x558b8eac7fd0 "delete from test1445 where device = 5;") at postgres.c:1250
#26 0x0000558b8e37e7df in PostgresMain (dbname=<optimized out>, username=<optimized out>) at postgres.c:4598
#27 0x0000558b8e2d2de8 in BackendRun (port=port@entry=0x558b8eaf15f0) at postmaster.c:4511
#28 0x0000558b8e2d5f6c in BackendStartup (port=port@entry=0x558b8eaf15f0) at postmaster.c:4239
#29 0x0000558b8e2d61a7 in ServerLoop () at postmaster.c:1806
#30 0x0000558b8e2d777f in PostmasterMain (argc=argc@entry=1, argv=argv@entry=0x558b8ea2f970) at postmaster.c:1478
#31 0x0000558b8e216f6f in main (argc=1, argv=0x558b8ea2f970) at main.c:202
```

### How can we reproduce the bug?

```bash
create table test1445(
    time timestamptz not null,
    device integer,
    temperature float
);

select * from create_hypertable('test1445', 'time', 'device', 4);

insert into test1445
select time, (random()*30)::int, random()*80 - 40
from generate_series(now() - interval '28 days', now() - interval '14 days', '1 minute') as time;

alter table test1445 set (
    timescaledb.compress,
    timescaledb.compress_segmentby = 'device'
);

select compress_chunk(show_chunks('test1445'));

select schema_name, table_name
  from _timescaledb_catalog.hypertable
 where id = (select compressed_hypertable_id from _timescaledb_catalog.hypertable where table_name = 'test1445')
\gset

select indexname from pg_indexes where schemaname = :'schema_name' and tablename = :'table_name' \gset

drop index :schema_name.:indexname;

delete from test1445 where device = 5;
```

### PR DESCRIPTION
**Pull request by antekresic**
Prior to version 2.8, compressed chunks had a different format for indexing. This change attempts to find the best index it can actually use during scanning of compressed data and moves filters around based on the selected index. If no index exists, it should fallback to doing a sequencial scan.

Fixes #6367

### CODE REVIEW

File: tsl/src/compression/compression.c [hunk 1]
```diff
@@ -2777,40 +2777,41 @@ fix_and_reorder_index_filters(Relation comp_chunk_rel, Relation index_rel,
...
  * 2. index (a,x,y)
  * 3. index (x)
- * 4. index (x,y)
- * In this case 2nd index is returned.
+ * In this case 2nd index is returned. If that one didn't exist,
+ * it would return the 1st index.
  */
 static Relation
-find_matching_index(Relation comp_chunk_rel, List *index_filters)
+find_matching_index(Relation comp_chunk_rel, List **index_filters, List **filters)
```
Comment (akuzm) [inline tsl/src/compression/compression.c:2799]: Let's call it `heap_filters`? It's easy to confuse when you have one variable with prefix and one without.

File: tsl/src/compression/compression.c [hunk 2]
```diff
@@ -3123,7 +3174,10 @@ decompress_batches(RowDecompressor *decompressor, ScanKeyData *scankeys, int num
 			pos++;
 		}
 		if (skip_tuple)
+		{
+			num_filtered_rows++;
```
Comment (akuzm) [inline tsl/src/compression/compression.c:3178]: The `skip_tuple` code path is because heap scans can't check for nulls, right? Would be good to add coverage for it (I thought we have it already, maybe it's just codecov being weird).

**Review by svenklemm — APPROVED** [review]

**Review by akuzm — APPROVED** [review]
