### PR TITLE
Relax CAggs JOIN restrictions

### LINKED ISSUE #1446: Create continuous aggregate from multiple tables
Hello everybody,

I have a question regarding time_bucket and continuous aggregation for multiple tables.
I want to use time_bucket() to match timestamps across different time series. Exactly like in this video at minute 38:51: https://youtu.be/lkqmfsWx6GM?t=2331

How should i create a query for a continuous aggregation to get metric_1 of table_1 and metric_2 of table_2 in one continious aggregation view.
In our case there could be different numbers of rows. Some will match and some rows will contain null values when "joined".
So i am planning to use time_bucket_gapfill() when i query the continuous aggregation view later.
Is there an example on how to create a continuous aggregation of multiple tables? In our case there has to be a "join" on time and a device_id (vin).

As an multi step solution i tried creating continuous aggregates for every table.
ca_one and ca_two are both continuous aggregates with 2 second time buckets.

The following query is successful and return exactly what i neeed:

```
SELECT
  ca_one.time_2s,
  ca_one.vin,
  column_first_table,
  column_second_table,
FROM
  ca_one
  LEFT JOIN ca_two ON ca_one.time_2s = ca_two.time_2s
  AND ca_one.vin = ca_two.vin
GROUP BY
  ca_one.time_2s,
  ca_one.vin,
  column_first_table,
  column_second_table;
```

But when i try to use it in a continuous aggregate i get the error:

```
ERROR:  only 1 hypertable is permitted in SELECT query for continuous aggregate
```

I don't know how to get my combined results time efficiently.
Does someone have a solution for this kind of (i think general) use case? Perhaps i am missing something obvious.

Regards
Julius

### PR DESCRIPTION
**Pull request by fabriziomello**
Remove some Continuous Aggregates JOIN restrictions by allowing:
* INNER/LEFT join;
* LATERAL join;
* JOIN between 1 hypertable and N tables, foreign tables, views or
  materialized views;
* Remove restriction of only ONE equality operator on JOIN clause.

Closes #1446, #1516, #1717, #2400, #3314, #4088, #7107

Disable-check: force-changelog-file

### CODE REVIEW

File: tsl/src/continuous_aggs/common.c [hunk 1]
```diff
@@ -688,146 +683,73 @@ cagg_validate_query(const Query *query, const bool finalized, const char *cagg_s
...
+							(errcode(ERRCODE_FEATURE_NOT_SUPPORTED),
+							 errmsg("invalid continuous aggregate view"),
+							 errdetail("Views are not supported in continuous aggregates.")));
+			}
+
+			if (inner_rte->inh == false)
+				ereport(ERROR,
+						(errcode(ERRCODE_FEATURE_NOT_SUPPORTED),
+						 errmsg("invalid continuous aggregate view"),
+						 errdetail("FROM ONLY is not allowed in continuous aggregate.")));
```
Comment (svenklemm) [inline tsl/src/continuous_aggs/common.c:715]: Why are we blocking this?

File: tsl/src/continuous_aggs/common.c [hunk 2]
```diff
@@ -688,146 +683,73 @@ cagg_validate_query(const Query *query, const bool finalized, const char *cagg_s
...
+					rte = copyObject(inner_rte);
 			}
+			else
+			{
+				num_tables++;
+				if (inner_rte->relkind == RELKIND_VIEW)
+					ereport(ERROR,
+							(errcode(ERRCODE_FEATURE_NOT_SUPPORTED),
+							 errmsg("invalid continuous aggregate view"),
+							 errdetail("Views are not supported in continuous aggregates.")));
```
Comment (svenklemm) [inline tsl/src/continuous_aggs/common.c:708]: Why are we blocking views?

File: tsl/src/continuous_aggs/common.c (hunk 1 above)
Comment (fabriziomello) [reply tsl/src/continuous_aggs/common.c:715]: Does make sense users use FROM ONLY in the view definition since hypertables don't allow store data in the parent table?

File: tsl/src/continuous_aggs/common.c (hunk 2 above)
Comment (fabriziomello) [reply tsl/src/continuous_aggs/common.c:708]: There's no techical problem to allow it but we always blocked it before and for now we'll continue blocking it as well. We can do a follow PR in the future expanding it a bit.

File: tsl/src/continuous_aggs/common.c (hunk 1 above)
Comment (svenklemm) [reply tsl/src/continuous_aggs/common.c:715]: It might make sense to block for the hypertable relation cause that would not be very useful for the query but for any other relation we can just allow it and leave this up to user.

File: tsl/src/continuous_aggs/common.c (hunk 2 above)
Comment (svenklemm) [reply tsl/src/continuous_aggs/common.c:708]: I think we can just allow. These kind of restrictions only serve to prevent users from using the feature and are easily circumvented anyway. Less restrictions equals better :). On the technical side nothing changes by allowing this and with FDW tables it's easy to circumvent.

Comment (fabriziomello) [reply tsl/src/continuous_aggs/common.c]: Make sense. Removed the restriction

File: tsl/src/continuous_aggs/common.c (hunk 1 above)
Comment (fabriziomello) [reply tsl/src/continuous_aggs/common.c]: You're correct, looking back into the past this code make sense in the past when we supported only one hypertable. Tweaked it a bit to error out only when using against a hypertable.

**Review by svenklemm — APPROVED** [review]

**Review by akuzm — APPROVED** [review]
