### PR TITLE
Fix relcache callback handling causing crashes

### LINKED ISSUE #3924: [Bug]: Segmentation Fault when VACUUM FULL pg_class
### What type of bug is this?

Crash

### What subsystems and features are affected?

Background worker

### What happened?

VACUUM FULL pg_class while another process is modifying table will cause a variety errors ranging from segmentation fault, to pg_class corruption.

Very similar to #3188 except this occurs after the extension is installed

### TimescaleDB version affected

2.5.1

### PostgreSQL version used

14.1

### What operating system did you use?

Red Hat Enterprise Linux 7.9

### What installation method did you use?

RPM

### What platform did you run on?

On prem/Self-hosted

### Relevant log output and stack trace

```bash
Logs for most recent replication of error

2021-12-13 11:17:29.258 EST [24508] CONTEXT:  PL/pgSQL function inline_code_block line 12 at RAISE
2021-12-13 11:18:53.208 EST [26184] ERROR:  cache lookup failed for relation 155205
2021-12-13 11:18:53.208 EST [26184] STATEMENT:  VACUUM FULL pg_class ;
2021-12-13 11:18:56.981 EST [24508] ERROR:  deadlock detected
2021-12-13 11:18:56.981 EST [24508] DETAIL:  Process 24508 waits for RowExclusiveLock on relation 1259 of database 16384; blocked by process 26184.
        Process 26184 waits for ShareLock on transaction 25128; blocked by process 24508.
        Process 24508: CREATE TABLE a24382 (time timestamp default now(), i BIGINT, i2 BIGINT, t TEXT, t2 TEXT);
        Process 26184: VACUUM FULL pg_class ;
2021-12-13 11:18:56.981 EST [24508] HINT:  See server log for query details.
2021-12-13 11:18:56.981 EST [24508] STATEMENT:  CREATE TABLE a24382 (time timestamp default now(), i BIGINT, i2 BIGINT, t TEXT, t2 TEXT);
2021-12-13 11:18:57.092 EST [26184] ERROR:  duplicate key value violates unique constraint "pg_class_relname_nsp_index"
2021-12-13 11:18:57.092 EST [26184] DETAIL:  Key (relname, relnamespace)=(pg_class, 11) already exists.
2021-12-13 11:18:57.092 EST [26184] STATEMENT:  VACUUM FULL pg_class ;
2021-12-13 11:19:01.754 EST [26184] ERROR:  cache lookup failed for relation 171287
2021-12-13 11:19:01.754 EST [26184] STATEMENT:  VACUUM FULL pg_class ;
2021-12-13 11:19:04.592 EST [24508] ERROR:  deadlock detected
2021-12-13 11:19:04.592 EST [24508] DETAIL:  Process 24508 waits for RowExclusiveLock on relation 1259 of database 16384; blocked by process 26184.
        Process 26184 waits for ShareLock on transaction 26880; blocked by process 24508.
        Process 24508: CREATE TABLE a26127 (time timestamp default now(), i BIGINT, i2 BIGINT, t TEXT, t2 TEXT);
        Process 26184: VACUUM FULL pg_class ;
2021-12-13 11:19:04.592 EST [24508] HINT:  See server log for query details.
2021-12-13 11:19:04.592 EST [24508] STATEMENT:  CREATE TABLE a26127 (time timestamp default now(), i BIGINT, i2 BIGINT, t TEXT, t2 TEXT);
2021-12-13 11:19:06.454 EST [24071] LOG:  server process (PID 26184) was terminated by signal 11: Segmentation fault
2021-12-13 11:19:06.454 EST [24071] DETAIL:  Failed process was running: VACUUM FULL pg_class ;
2021-12-13 11:19:06.454 EST [24071] LOG:  terminating any other active server processes
2021-12-13 11:19:06.455 EST [29849] FATAL:  the database system is in recovery mode

Below is what was being run in psql shell:
(not the session creating the tables)

$ /usr/pgsql-14/bin/psql -d testdb
psql (14.1)
Type "help" for help.

testdb=# VACUUM FULL pg_class ;
VACUUM
testdb=# SELECT  datname, pg_size_pretty( pg_database_size(datname) ) FROM pg_database;
  datname  | pg_size_pretty
-----------+----------------
 postgres  | 8769 kB
 testdb    | 315 MB
 template1 | 8617 kB
 template0 | 8617 kB
(4 rows)

testdb=# VACUUM FULL pg_class ;
ERROR:  cache lookup failed for relation 155205
testdb=# VACUUM FULL pg_class ;
ERROR:  duplicate key value violates unique constraint "pg_class_relname_nsp_index"
DETAIL:  Key (relname, relnamespace)=(pg_class, 11) already exists.
testdb=# VACUUM FULL pg_class ;
ERROR:  cache lookup failed for relation 171287
testdb=# VACUUM FULL pg_class ;
VACUUM
testdb=# VACUUM FULL pg_class ;
server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
The connection to the server was lost. Attempting reset: Failed.
```

### How can we reproduce the bug?

1) Create database and install TimescaleDB extension
2) In a psql session connected to that database run:

```
testdb=# SELECT format('CREATE TABLE a%s (time timestamp default now(), i BIGINT, i2 BIGINT, t TEXT, t2 TEXT);',i) FROM generate_series(1, 200000) i
\gexec
```

While above is running connect via another psql session connect to same database, wait until pg_class is over 20MB then run `VACUUM FULL pg_class` several times.
```

### PR DESCRIPTION
**Pull request by erimatnor**
Fix a crash that could corrupt indexes when running `VACUUM FULL
pg_class`.

The crash happens when caches are queried/updated within a cache
invalidation function, which can lead to corruption and recursive
cache invalidations.

To solve the issue, make sure the relcache invalidation callback is
simple and never invokes the relcache or syscache directly or
indirectly.

Some background: The extension is preloaded and thus have planner
hooks installed irrespective of whether the extension is actually
installed or not in the current database. However, the hooks need to
be disabled as long as the extension is not installed. To avoid always
having to dynamically check for the presence of the extension, the
state is cached in the session.

However, the cached state needs to be updated if the extension changes
(altered/dropped/created). Therefore, the relcache invalidation
callback mechanism is (ab)used in TimescaleDB to signal updates to the
extension state across all active backends.

The signaling is implemented by installing a dummy table as part of
the extension and any invalidation on the relid for that table signals
a change in the extension state. However, as of this change, the
actual state is no longer determined in the callback itself, since it
requires use of the relcache and causes the bad behavior. Therefore,
the only thing that remains in the callback after this change is to
reset the extension state.

The actual state is instead resolved on-demand, but can still be
cached when the extension is in the installed state and the dummy
table is present with a known relid. However, if the extension is not
installed, the extension state can no longer be cached as there is no
way to signal other backends that the state should be reset when they
don't know the dummy table's relid, and cannot resolve it from within
the callback itself.

Fixes #3924

Disable-Check: Commit-Count

### CODE REVIEW

File: src/cache_invalidate.c [hunk 1]
```diff
@@ -59,45 +60,44 @@ cache_invalidate_relcache_all(void)
...
+ * might lead to bad things happening.
  */
 static void
-cache_invalidate_callback(Datum arg, Oid relid)
+cache_invalidate_relcache_callback(Datum arg, Oid relid)
 {
-	static bool in_recursion = false;
-
-	if (ts_extension_invalidate(relid))
+	if (relid == InvalidOid)
```
Comment (mfundul) [inline src/cache_invalidate.c:84]:
```suggestion
	if (!OidIsValid(relid))
```
Doesn't this branch get kind of expensive when taken? For all those callbacks, even if no timescaledb instance has been created you create and destroy 1 memory context per callback.

Comment (erimatnor) [reply src/cache_invalidate.c:84]: This was already there in the old code. AFAIK, a "wildcard' invalidation is rarely issued, but needs to be handled nevertheless. This is the only place in the PG code where I could find such an invalidation:

```c
/*
 * CacheInvalidateRelcacheAll
 *		Register invalidation of the whole relcache at the end of command.
 *
 * This is used by alter publication as changes in publications may affect
 * large number of tables.
 */
void
CacheInvalidateRelcacheAll(void)
{
	PrepareInvalidationState();

	RegisterRelcacheInvalidation(InvalidOid, InvalidOid);
}

```

**Comment by erimatnor** [comment]
I tested manually these two things:

* That the PR code no longer reproduces the `VACUUM FULL pg_class` issue n #3924

File: src/cache_invalidate.c [hunk 2]
```diff
@@ -59,45 +60,44 @@ cache_invalidate_relcache_all(void)
...
-			ts_hypertable_cache_invalidate_callback();
-
-		if (relid == ts_catalog_get_cache_proxy_id(catalog, CACHE_TYPE_BGW_JOB))
-			ts_bgw_job_cache_invalidate_callback();
-
-		if (relid == InvalidOid)
-			cache_invalidate_relcache_all();
+		ts_extension_invalidate();
+		cache_invalidate_relcache_all();
+		ts_cache_invalidate_set_proxy_tables(InvalidOid, InvalidOid);
```
Comment (mkindahl) [inline src/cache_invalidate.c:92]: Nit: this is the only place `ts_cache_invalidate_set_proxy_tables` is used and it is far easier to read if the assignments are here instead of in a different function.

File: src/cache_invalidate.c [hunk 3]
```diff
@@ -59,45 +60,44 @@ cache_invalidate_relcache_all(void)
...
+	}
+	else if (relid == hypertable_proxy_table_oid)
+	{
+		ts_hypertable_cache_invalidate_callback();
+	}
```
Comment (mkindahl) [inline src/cache_invalidate.c:97]: If you invalidate the `hypertable_proxy_table_oid` you should probably invalidate the variable as well since the OID can change.
```suggestion
	else if (relid == hypertable_proxy_table_oid)
	{
		ts_hypertable_cache_invalidate_callback();
		hypertable_proxy_table_oid = InvalidOid;
	}
```

File: src/cache_invalidate.c [hunk 4]
```diff
@@ -59,45 +60,44 @@ cache_invalidate_relcache_all(void)
...
+	else if (relid == bgw_proxy_table_oid)
+	{
+		ts_bgw_job_cache_invalidate_callback();
```
Comment (mkindahl) [inline src/cache_invalidate.c:100]: Here you should also reset `bgw_proxy_table_oid` if it is invalidated.
```suggestion
	else if (relid == bgw_proxy_table_oid)
	{
		ts_bgw_job_cache_invalidate_callback();
		bgw_proxy_table_oid = InvalidOid;
```

File: src/cache_invalidate.c [hunk 5]
```diff
@@ -59,45 +60,44 @@ cache_invalidate_relcache_all(void)
...
 
+static Oid hypertable_proxy_table_oid = InvalidOid;
+static Oid bgw_proxy_table_oid = InvalidOid;
+
+void
+ts_cache_invalidate_set_proxy_tables(Oid hypertable_proxy_oid, Oid bgw_proxy_oid)
+{
+	hypertable_proxy_table_oid = hypertable_proxy_oid;
+	bgw_proxy_table_oid = bgw_proxy_oid;
+}
```
Comment (mkindahl) [inline src/cache_invalidate.c:71]: This is not used anywhere else than in this file, so why does it need external linkage?

File: src/extension.c [hunk 6]
```diff
@@ -62,7 +64,20 @@ static enum ExtensionState extstate = EXTENSION_STATE_UNKNOWN;
...
  */
-Oid ts_extension_oid = InvalidOid;
+static Oid ts_extension_oid = InvalidOid;
+
+Oid
+ts_extension_get_oid(void)
+{
+	if (OidIsValid(ts_extension_oid))
+	{
+		Assert(ts_extension_oid == get_extension_oid(EXTENSION_NAME, true));
```
Comment (mkindahl) [inline src/extension.c:74]: This might trigger problems in debug builds.

**Review by mkindahl — COMMENTED** [review]
A few comments, but I need to continue checking.

File: src/extension.c (hunk 6 above)
Comment (mkindahl) [reply src/extension.c:74]: Just to clarify: this might trigger complicated issues in a debug build that are non-existent in the real build and hence will cause waste of time on non-existent issues. It is probably better to not do this at all, or do it in a location that is not called from invalidation code.

File: src/cache_invalidate.c (hunk 5 above)
Comment (erimatnor) [reply src/cache_invalidate.c:71]: It is called from `catalog.c` when the `Catalog` object is initialized it sets these to valid table relids.

File: src/cache_invalidate.c (hunk 2 above)
Comment (erimatnor) [reply src/cache_invalidate.c:92]: You missed the other place in `catalog.c`

File: src/cache_invalidate.c (hunk 3 above)
Comment (erimatnor) [reply src/cache_invalidate.c:97]: This is not invalidating the `hypertable_proxy_table_oid`, only the cache. The `hypertable_proxy_table_oid` is used to identify the "event" that invalidates the hypertable cache and would only be reset if the extension is dropped (in which case the proxy table no longer exists and installing the extension again would give it a new relid).

If we reset the `hypertable_proxy_table_oid` here we would not be able to identify invalidations any longer.

File: src/cache_invalidate.c (hunk 4 above)
Comment (erimatnor) [reply src/cache_invalidate.c:100]: No, for same reason as above.

File: src/extension.c (hunk 6 above)
Comment (erimatnor) [reply src/extension.c:74]: Should not be a problem since the function is not called from invalidation callback code.

Comment (mkindahl) [reply src/extension.c:74]: Is it possible to add a check for that?

File: src/cache_invalidate.c (hunk 5 above)
Comment (mkindahl) [reply src/cache_invalidate.c:71]: Missed that one. All good.

File: src/cache_invalidate.c (hunk 3 above)
Comment (mkindahl) [reply src/cache_invalidate.c:97]: Hmmm... but if the table is dropped---as part of dropping the extension---this means that `hypertable_proxy_table_oid` is still set to the OID of the now non-existent `_timescaledb_cache.cache_inval_hypertable`, couldn't that cause problems if the cache invalidation code is executed when the extension is not loaded?

I guess not, since OIDs will be strictly increasing and any new OIDs assigned will not match the existing value of `hypertable_proxy_table_oid`.

Comment (erimatnor) [reply src/cache_invalidate.c:97]: The case when dropping the extension is handled in the second part of the if-else clause:

```
else if (ts_extension_is_proxy_table_relid(relid))
	{
		ts_extension_invalidate();
		cache_invalidate_relcache_all();
		ts_cache_invalidate_set_proxy_tables(InvalidOid, InvalidOid);
	}
```

`ts_extension_invalidate()` will reset the extension proxy table Oid, while `ts_cache_invalidate_set_proxy_tables` resets the other two proxy tables.

File: src/extension.c (hunk 6 above)
Comment (erimatnor) [reply src/extension.c:74]: Do you suggest checking that this function is not called from an invalidation callback? 

That makes no sense, IMO. Why single out this function when any function that calls the relcache leads to bad behavior?

We'd need something that generally checks if a relcache function is called from an invalidation callback, and I don't see how that can be done.

File: src/extension.c [hunk 7]
```diff
@@ -156,16 +170,23 @@ extension_set_state(enum ExtensionState newstate)
...
+	 * another backend. Nor is it allowed to lookup the new relid in the
+	 * invalidation callback, since that may lead to bad behavior.
+	 *
+	 * Instead, set the state to "unknown" so that a "slow path" lookup of the
+	 * actual state has to be made next time the state is queried.
 	 */
-	if (in_recursion)
-		return;
+	if (new_state == EXTENSION_STATE_NOT_INSTALLED)
+		new_state = EXTENSION_STATE_UNKNOWN;
```
[the remark this answers is not in the document]
Comment (erimatnor) [reply src/extension.c:188]: I considered removing the "not installed" state, but decided against it for now to minimize changes (also, this is a loader change). `extension_current_state()` actually still determines that the extension is not installed and can therefore distinguish between the cases. It could be useful for debugging and the only reason this state isn't set right now is because I couldn't figure out a good way to signal other backends to get out of it when the extension is created again.

File: src/extension.c (hunk 6 above)
Comment (mkindahl) [reply src/extension.c:74]: > Do you suggest checking that this function is not called from an invalidation callback?

Not suggesting anything, just wondering if there is an easy way to add a check and if it is meaningful. I guess from the rest of your reply that the answer is "no".

**Review by mkindahl — APPROVED** [review]
Approving this since the last comment is not critical.

**Comment by mfundul** [comment]
Will look into this PR more seriously as well.

File: src/cache_invalidate.c [hunk 8]
```diff
@@ -59,45 +60,44 @@ cache_invalidate_relcache_all(void)
...
 static void
-cache_invalidate_callback(Datum arg, Oid relid)
+cache_invalidate_relcache_callback(Datum arg, Oid relid)
 {
-	static bool in_recursion = false;
-
-	if (ts_extension_invalidate(relid))
+	if (!OidIsValid(relid))
 	{
 		cache_invalidate_relcache_all();
```
Comment (mfundul) [inline src/cache_invalidate.c:86]: `cache_invalidate_relcache_all()` calls:
`ts_hypertable_cache_invalidate_callback()`->`ts_cache_invalidate(hypertable_cache_current)`->`cache_destroy(cache)`->`cache->pre_destroy_hook(cache)` which calls:
```
static void
connection_cache_entry_free(void *gen_entry)
{
	ConnectionCacheEntry *entry = gen_entry;

	if (entry->conn != NULL)
	{
		/* Cannot directly read the Log_connections boolean since it is not
		 * exported on Windows */
		const char *log_conns = GetConfigOption("log_connections", true, false);

		if (NULL != log_conns && strcmp(log_conns, "on") == 0)
		{
			/* Log the connection closing if requested. Only log the
			 * associated user ID since cannot lookup the user name here due
			 * to, potentially, not being in a proper transaction state where
			 * it is possible to use the syscache. */
			elog(LOG,
				 "closing cached connection to \"%s\" [UserId: %d]",
				 remote_connection_node_name(entry->conn),
				 entry->id.user_id);
		}

		remote_connection_close(entry->conn);
		entry->conn = NULL;
	}
}
```
which recurses into the syscache again.

Comment (erimatnor) [reply src/cache_invalidate.c:86]: @mfundul Where in this code is the syscache invoked? Is it `GetConfigOption`?

Comment (mfundul) [reply src/cache_invalidate.c:86]: Yes, for instance `GetConfigOption()`->`roles_is_member_of()`:
```
	if (!OidIsValid(MyDatabaseId))
		dba = InvalidOid;
	else
	{
		HeapTuple	dbtup;

		dbtup = SearchSysCache1(DATABASEOID, ObjectIdGetDatum(MyDatabaseId));
		if (!HeapTupleIsValid(dbtup))
			elog(ERROR, "cache lookup failed for database %u", MyDatabaseId);
		dba = ((Form_pg_database) GETSTRUCT(dbtup))->datdba;
		ReleaseSysCache(dbtup);
	}
```

**Comment by mfundul** [comment]
We should probably have a disclaimer in comments above every function that is potentially called in syscache callback context.

Something in the spirit of:
```
/*
 * WARNING: this function may be called in SysCache invalidation context. No SysCache accesses allowed.
 */
```

File: src/cache_invalidate.c (hunk 8 above)
Comment (erimatnor) [reply src/cache_invalidate.c:86]: @mfundul  So, that's syscache, not the relcache. Not sure it makes a difference though. I'll see if I can work around it, but it might require bigger refactoring

Comment (erimatnor) [reply src/cache_invalidate.c:86]: @mfundul Actually, I fail to see how this can happen. There is no pre_destroy_hook for the hypertable cache. I think you are mixing up the hypertable cache and the connection cache.

**Review by mfundul — APPROVED** [review]
Other than the above LGTM.

File: tsl/src/fdw/relinfo.c [hunk 9]
```diff
@@ -425,8 +425,7 @@ fdw_relinfo_create(PlannerInfo *root, RelOptInfo *rel, Oid server_oid, Oid local
 	 */
 	fpinfo->fdw_startup_cost = DEFAULT_FDW_STARTUP_COST;
 	fpinfo->fdw_tuple_cost = DEFAULT_FDW_TUPLE_COST;
-	Assert(ts_extension_oid != InvalidOid);
-	fpinfo->shippable_extensions = list_make1_oid(ts_extension_oid);
+	fpinfo->shippable_extensions = list_make1_oid(ts_extension_get_oid());
```
Comment (mfundul) [inline tsl/src/fdw/relinfo.c:428]: Maybe add this here:
```
Assert(OidIsValid(fpinfo->shippable_extensions));
```

Comment (erimatnor) [reply tsl/src/fdw/relinfo.c:428]: I removed the assertion since the function `ts_extension_get_oid()` cannot return an invalid OID.

File: test/t/CMakeLists.txt [hunk 10]
```diff
@@ -0,0 +1,12 @@
...
+if(CMAKE_BUILD_TYPE MATCHES Debug)
+  list(APPEND PROVE_TEST_FILES ${PROVE_DEBUG_TEST_FILES})
+endif(CMAKE_BUILD_TYPE MATCHES Debug)
+
+foreach(P_FILE ${PROVE_TEST_FILES})
+  configure_file(${P_FILE} ${CMAKE_CURRENT_BINARY_DIR}/${P_FILE} COPYONLY)
+endforeach(P_FILE)
+
+set(MODULE_PATHNAME "$libdir/timescaledb-${PROJECT_VERSION_MOD}")
+configure_file(functions.sql.in functions.sql)
```
[the remark this answers is not in the document]
Comment (erimatnor) [reply test/t/CMakeLists.txt:12]: Some test sql files use `:MODULE_PATHNAME`, because it is set at runtime via psql variables. The solution I use here is different and sets the `@MODULE_PATHNAME@` to replace it at configuration (cmake) time. This is also why I added the .in extension. I think both are valid approaches, but the runtime-option isn't easily available for TAP tests.

Also, this sql file isn't strictly a test, but rather a library file. But not sure that matters.
