### PR TITLE
Fix join propagation for nested joins

### LINKED ISSUE #2790: Full Outer Join giving wrong result on hyper tables
**Relevant system information:**
 - OS: [Ubuntu 18]
 - PostgreSQL version :[PostgreSQL 11.10 on x86_64-pc-linux-musl, compiled by gcc (Alpine 9.3.0) 9.3.0, 64-bit]
 - TimescaleDB version : [2.0.0]
 - Installation method: [docker]

**Describe the bug**
The behavior of full outer join in hyper tables is erroneous. Same query run on plain Postgres tables produces correct results. Data from one side of the outer join is removed.
[timescale issue-github.zip](https://github.com/timescale/timescaledb/files/5769994/timescale.issue-github.zip)

**To Reproduce**
**Plain Postgres table**
    • Create a blank database & restore the postgres dump file ts_github.sql (from attachment)
    • Run the  query provided in query.sql file (from attachment).
Note that the count of records returned by the query is 1536. The count of rows return by the first part of the query (if ran separately) is 1536. The count of rows returned by the second part of the query (if ran separately) is 96. The outer join which combines the results of both queries produces 1536 rows which is correct.
**Hyper Table**
    • Add TimescaleDb extension using : CREATE EXTENSION IF NOT EXISTS timescaledb CASCADE;
    • Create hyper tables using : SELECT create_hypertable('second_fact', 'timestamp', chunk_time_interval => interval '1 day', if_not_exists => TRUE, migrate_data => TRUE);
    • Rerun the same query from query.sql file.
Note that the count of records returned by the query is 96. The count of rows return by the first part of the query (if ran separately) is 1536. The count of rows returned by the second part of the query (if ran separately) is 96. The outer join which combines the results of both queries produces 96 rows which is incorrect.

**Expected behavior**
1536 rows should get returned

**Actual behavior**
96 rows are getting retunred.

**Additional context**
Reproducible On
    • timescale/timescaledb:latest-pg11
    • PostgreSQL 11.5 on x86_64-pc-linux-musl, compiled by gcc (Alpine 8.3.0) 8.3.0, 64-bit with TimescaleDB extension 1.4.2
      
Not Reproducible On
    • timescaledb:latest-pg12
    • PostgreSQL 12.4 (Ubuntu 12.4-1.pgdg18.04+1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0, 64-bit & timescale db 1.7.4

### PR DESCRIPTION
**Pull request by svenklemm**
Join propagation would propagate join quals for nested joins even
when it was not safe to do so leading to wrong query results.

Fixes #2790

### CODE REVIEW

**Review by pmwkaa — COMMENTED** [review]
I think it requires a test case

File: src/plan_expand_hypertable.c [hunk 1]
```diff
@@ -1172,6 +1178,7 @@ ts_plan_expand_hypertable_chunks(Hypertable *ht, PlannerInfo *root, RelOptInfo *
 		.all_quals = NIL,
 		.join_conditions = NIL,
 		.propagate_conditions = NIL,
+		.join_level = 0,
```
Comment (mkindahl) [inline src/plan_expand_hypertable.c:1181]: This is the default for values not mentioned in the initializer, so strictly speaking not necessary.

**Review by mkindahl — COMMENTED** [review]
Typo in the commit message: "save" shall probably be "safe".

I also miss a test case.

**Comment by svenklemm** [comment]
> I think it requires a test case

I'll add testcase based on the linked issue but want to boil down the example a little

File: src/plan_expand_hypertable.c [hunk 2]
```diff
@@ -838,13 +839,18 @@ collect_quals_walker(Node *node, CollectQualCtx *ctx)
...
 		f->quals = process_quals(f->quals, ctx, false);
-		collect_join_quals(f->quals, ctx, false);
+		/* if this is a nested join we don't propagate join quals */
+		collect_join_quals(f->quals, ctx, ctx->join_level >= 1);
 	}
 	else if (IsA(node, JoinExpr))
 	{
 		JoinExpr *j = castNode(JoinExpr, node);
 		j->quals = process_quals(j->quals, ctx, IS_OUTER_JOIN(j->jointype));
 		collect_join_quals(j->quals, ctx, IS_OUTER_JOIN(j->jointype));
```
Comment (gayyappan) [inline src/plan_expand_hypertable.c:849]: The parameter name (is_outer_join)  for collect_join_quals should be renamed. It is misleading. Could you rename the parameter to propgate_join_qual or something more appropriate ?  Some comments  about the parameter usage would also be helpful for future reference.

File: test/expected/plan_expand_hypertable-11.out [hunk 3]
```diff
@@ -2475,6 +2475,75 @@ SELECT time FROM regular_timestamptz UNION ALL SELECT time FROM metrics_timestam
...
+                           Index Cond: ("time" > 'Thu Jan 20 00:00:00 2000 PST'::timestamp with time zone)
+                           Filter: (device_id = 2)
+                     ->  Index Scan Backward using _hyper_7_168_chunk_metrics_timestamptz_2_time_idx on _hyper_7_168_chunk m2_4
+                           Index Cond: ("time" > 'Thu Jan 20 00:00:00 2000 PST'::timestamp with time zone)
+                           Filter: (device_id = 2)
+                     ->  Index Scan Backward using _hyper_7_169_chunk_metrics_timestamptz_2_time_idx on _hyper_7_169_chunk m2_5
+                           Index Cond: ("time" > 'Thu Jan 20 00:00:00 2000 PST'::timestamp with time zone)
+                           Filter: (device_id = 2)
+               ->  Append
+                     ->  Index Scan using _hyper_6_160_chunk_metrics_timestamptz_time_idx on _hyper_6_160_chunk m1_5
```
Comment (gayyappan) [inline test/expected/plan_expand_hypertable-11.out:2504]: since we have the same tables and identical column names in o1 and o2, I am finding it hard to figure out which join this is.  It would help if you use 2 alases like m3 and m4 to make the plan easier to  follow.

File: test/expected/plan_expand_hypertable-11.out [hunk 4]
```diff
@@ -2475,6 +2475,75 @@ SELECT time FROM regular_timestamptz UNION ALL SELECT time FROM metrics_timestam
  Tue Feb 01 00:00:00 2000 PST
 (128 rows)
 
+-- test nested join qual propagation
+:PREFIX
+SELECT * FROM (
+SELECT m1.time FROM metrics_timestamptz m1 FULL OUTER JOIN metrics_timestamptz_2 m2 ON true WHERE m2.time = m1.time AND m1.device_id = m2.device_id AND m2.time < '2000-01-10' AND m1.device_id = 1
```
Comment (gayyappan) [inline test/expected/plan_expand_hypertable-11.out:2481]: Good to test some more variants here:
SELECT * FROM (q1 outer join q2 ) , 
1) with q1 as select * from m1 **left outer join** m2 ON  **<non -trivial clause >** here.
2) with q1 as select * from m1 **inner join** m2 ON **<non-trivial clause>**

**Comment by mkindahl** [comment]
> Join propagation would propage join quals for nested joins even
> when it was not save to do so leading to wrong query results.
> 
> Fixes #2790

Still a typo: I think "save" should be "safe".

**Comment by svenklemm** [comment]
> > Join propagation would propage join quals for nested joins even
> > when it was not save to do so leading to wrong query results.
> > Fixes #2790
> 
> Still a typo: I think "save" should be "safe".

fixed

**Review by mkindahl — APPROVED** [review]

**Review by pmwkaa — APPROVED** [review]
