### PR TITLE
error compressing wide table

### LINKED ISSUE #4398: [Bug]: error compressing wide table
### What type of bug is this?

Unexpected error

### What subsystems and features are affected?

Compression

### What happened?

We have wide tables (with up to ~1000 columns).
When I try to compress a table, it fails like:

### TimescaleDB version affected

2.7

### PostgreSQL version used

14.3

### What operating system did you use?

centos7

### What installation method did you use?

Source

### What platform did you run on?

On prem/Self-hosted

### Relevant log output and stack trace

```bash
postgres=# SELECT compress_chunk(c) FROM show_chunks('widetable', INTERVAL '1 days') c;
2022-05-28 23:19:20.076 MST [10906] ERROR:  row is too big: size 46616, maximum size 8160
ERROR:  row is too big: size 46616, maximum size 8160
Time: 74773.753 ms (01:14.774)
postgres=# \errverbose 
ERROR:  54000: row is too big: size 46616, maximum size 8160
LOCATION:  RelationGetBufferForTuple, hio.c:361

Here's an old backtrace from when I sent this problem to priscila@timescale.com on 26 May 2020 asking that it be forwarded to developers.

> > > (gdb) bt
> > > #1  0x000000000087e440 in errfinish ()
> > > #2  0x00000000004cbb2d in RelationGetBufferForTuple ()
> > > #3  0x00000000004c01d8 in heap_insert ()
> > > #4  0x00007f2e6c22d294 in row_compressor_flush (row_compressor=0x7ffe20544010, mycid=561, changed_groups=true)
> > >     at /home/pryzbyj/timescaledb/tsl/src/compression/compression.c:784
> > > #5  0x00007f2e6c22e0fe in row_compressor_append_sorted_rows (sorted_desc=<optimized out>, sorted_rel=0x113f140, row_compressor=0x7ffe20544010)
> > >     at /home/pryzbyj/timescaledb/tsl/src/compression/compression.c:600
> > > #6  compress_chunk (in_table=<optimized out>, out_table=<optimized out>, column_compression_info=column_compression_info@entry=0x3933910, 
> > >     num_compression_infos=num_compression_infos@entry=536) at /home/pryzbyj/timescaledb/tsl/src/compression/compression.c:260
> > > #7  0x00007f2e6c230fbe in compress_chunk_impl (chunk_relid=19174912, hypertable_relid=<optimized out>)
> > >     at /home/pryzbyj/timescaledb/tsl/src/compression/compress_utils.c:232
> > > #8  tsl_compress_chunk_wrapper (chunk_relid=chunk_relid@entry=84253857, if_not_compressed=<optimized out>)
> > >     at /home/pryzbyj/timescaledb/tsl/src/compression/compress_utils.c:325
> > > #9  0x00007f2e6c23134e in tsl_compress_chunk (fcinfo=0x11d0ba0) at /home/pryzbyj/timescaledb/tsl/src/compression/compress_utils.c:334
```

### How can we reproduce the bug?

_No response_

### PR DESCRIPTION
**Pull request by sb230132**
Consider a compressed hypertable has many columns (like more than 600 columns). In call to compress_chunk(), the compressed tuple size exceeds, 8K which causes error as "row is too big: size 10856, maximum size 8160."

This patch estimates the tuple size of compressed hypertable and reports a warning when compression is enabled on hypertable. Thus user gets aware of this warning before calling compress_chunk().

Fixes #4398

### CODE REVIEW

File: src/hypertable.c [hunk 1]
```diff
@@ -2551,6 +2552,30 @@ ts_hypertable_create_compressed(Oid table_relid, int32 hypertable_id)
...
+						9960,
+						8164)));
+#else
+		ereport(WARNING,
+				(errmsg("Estimated row size of compressed hypertable is %u. Assuming data gets "
+						"compressed to half the original size which is %u, which still exceeds "
+						"maximum size %zu. This can cause compression of chunks to fail.",
+						row_size,
+						(row_size / 2),
+						MaxHeapTupleSize)));
```
Comment (mkindahl) [inline src/hypertable.c:2576]: The error message is usually smaller and without too many details, while additional details and suggestions for how to solve the problem can be added using `errdetail` or `errhint` respectively. See [Error Message Style Guide](https://www.postgresql.org/docs/current/error-style-guide.html) in the PostgreSQL manual.

```suggestion
		ereport(WARNING,
				(errmsg("compressed row size might exceed maximum row size"),
				 errdetail("Estimated row size of compressed hypertable is %u. Assuming data gets "
						"compressed to half the original size which is %u, this can exceed the "
						"maximum size of %zu and can cause compression of chunks to fail.",
						row_size,
						(row_size / 2),
						MaxHeapTupleSize)));
```

File: src/hypertable.c [hunk 2]
```diff
@@ -2911,4 +2936,4 @@ ts_hypertable_update_dimension_partitions(const Hypertable *ht)
 	}
 
 	return false;
-}
```
Comment (mkindahl) [inline src/hypertable.c:2914]: You seem to have accidentally removed the newline at the end of the file.

File: tsl/test/sql/compression_errors.sql [hunk 3]
```diff
@@ -347,4 +347,18 @@ SELECT COMPRESS_CHUNK(X) FROM SHOW_CHUNKS('test') X;
...
+SELECT * FROM create_hypertable('ts_table', 'tm');
+--should report a warning
+ALTER TABLE ts_table SET(timescaledb.compress, timescaledb.compress_segmentby = 'c1',
+					   timescaledb.compress_orderby = 'tm');
+INSERT INTO ts_table SELECT * FROM data_table;
+--should fail
+SELECT compress_chunk(c) FROM show_chunks('ts_table') c;
+--cleanup tables
+DROP TABLE data_table cascade;
+DROP TABLE ts_table cascade;
```
Comment (mkindahl) [inline tsl/test/sql/compression_errors.sql:364]: Missing newline at end of file.

File: src/hypertable.c [hunk 4]
```diff
@@ -2551,6 +2552,30 @@ ts_hypertable_create_compressed(Oid table_relid, int32 hypertable_id)
 	Relation rel;
 
 	rel = table_open(table_relid, AccessExclusiveLock);
+	int32 row_size = MAXALIGN(SizeofHeapTupleHeader);
+	/* estimate tuple width of compressed hypertable */
+	row_size += get_relation_data_width(table_relid, NULL);
+	/* assuming data gets compressed to half of its original size */
+	if ((row_size / 2) > MaxHeapTupleSize)
```
Comment (mkindahl) [inline src/hypertable.c:2559]: Why did you pick a compression ratio of 50%?

**Review by mkindahl — CHANGES_REQUESTED** [review]

File: src/hypertable.c (hunk 4 above)
Comment (svenklemm) [reply src/hypertable.c:2559]: This calculation is not correct since a toasted pointer consumes 18 bytes. 

https://www.postgresql.org/docs/current/storage-toast.html

Comment (mkindahl) [reply src/hypertable.c:2559]: > This calculation is not correct since a TOAST pointer consumes 18 bytes.
> 
> https://www.postgresql.org/docs/current/storage-toast.html

Hmm... so this means that if you assume that all columns smaller than 18 bytes are toasted, you would be safe.

Basically, something like `columns.map(|x| max(x.size, 18)).sum() > MaxHeapTupleSize`.

Comment (svenklemm) [reply src/hypertable.c:2559]: It's more like `sum(if col.varlen then 18 else col.size end) > MaxHeapTupleSize`
Also get_relation_data_width since not the right function to use here as you want the theoretical limits of the tuple not which values are currently stored if any.

File: src/hypertable.c (hunk 2 above)
Comment (sb230132) [reply src/hypertable.c:2914]: I do not see any change in this file at the end.

File: src/hypertable.c [hunk 5]
```diff
@@ -2911,4 +2944,4 @@ ts_hypertable_update_dimension_partitions(const Hypertable *ht)
 	}
 
 	return false;
-}
+}
```
Comment (mkindahl) [inline src/hypertable.c:2947]:
```suggestion
}

```

File: src/hypertable.c (hunk 2 above)
Comment (mkindahl) [reply src/hypertable.c]: There is a "red sign" below this comment. If you hover over it, it shows that there is an newline missing.

File: src/hypertable.c [hunk 6]
```diff
@@ -2551,6 +2551,39 @@ ts_hypertable_create_compressed(Oid table_relid, int32 hypertable_id)
...
+	if (row_size > MaxHeapTupleSize)
+	{
+#ifndef NDEBUG
+		ereport(WARNING,
+				(errmsg("compressed row size might exceed maximum row size"),
+				 errdetail("Estimated row size of compressed hypertable is %u. This exceeds the "
+						   "maximum size of %u and can cause compression of chunks to fail.",
+						   9956,
+						   8164)));
+#else
```
Comment (mkindahl) [inline src/hypertable.c:2578]: I am not sure why you need a separate case for when `NDEBUG` is not defined.

File: src/hypertable.c [hunk 7]
```diff
@@ -2551,6 +2551,39 @@ ts_hypertable_create_compressed(Oid table_relid, int32 hypertable_id)
...
 
 	rel = table_open(table_relid, AccessExclusiveLock);
+	int32 row_size = MAXALIGN(SizeofHeapTupleHeader);
+	/* estimate tuple width of compressed hypertable */
+	for (int i = 1; i <= RelationGetNumberOfAttributes(rel); i++)
+	{
+		bool is_varlena = false;
+		Oid outfunc;
+		Form_pg_attribute att = TupleDescAttr(rel->rd_att, i - 1);
+		if (att->attisdropped)
```
Comment (svenklemm) [inline src/hypertable.c:2561]: That is not correct, dropped attributes still consume space

File: src/hypertable.c (hunk 6 above)
Comment (sb230132) [reply src/hypertable.c:2578]: On some platforms the maximum row size returned is 8160 and on some its 8164. This causes tests to fail.
Thus hardcoding values on debug specific builds.

Comment (mkindahl) [reply src/hypertable.c:2576]: But `NDEBUG` is the symbol used to enable or disable `assert`. Also, since you have put the numbers in the detailed message, you can set the verbosity to "terse" to exclude printing the detailed error message. See [Error Reporting and Logging](https://www.postgresql.org/docs/current/runtime-config-logging.html) and [psql](https://www.postgresql.org/docs/14/app-psql.html) in the PostgreSQL documentation.

File: src/hypertable.c (hunk 4 above)
Comment (mkindahl) [reply src/hypertable.c]: But since this is checking the size of the column of the _uncompressed_ table, which could be a fixed size column that is smaller than 18 bytes (e.g., an integer), it would mean that once the column is compressed, it will turn into an array, which will then (hopefully) be toasted and will then occupy 18 bytes.

Wouldn't this check fail for a table with, say, 600 integer columns (which would occupy 600 * 8 = 4800 bytes in the uncompressed table and 600 * 18 = 10800 in the compressed table)?

Comment (svenklemm) [reply src/hypertable.c]: it should be checking the compressed table, otherwise it has to take segment by and order by into account

File: src/hypertable.c (hunk 6 above)
Comment (sb230132) [reply src/hypertable.c]: "terse" is set as part of log_error_verbosity which controls what should be logged in server logs.
In the tests, messages are sent to client (psql).
client_min_messages default is (NOTICE) even if i set to WARNING, detailed message is sent by server.

Code block defined inside NDEBUG executes only in debug builds i suppose.
Current patch i removed NDEBUG block and i see this error diffs.


@@ -628,7 +628,7 @@
 ALTER TABLE ts_table SET(timescaledb.compress, timescaledb.compress_segmentby = 'c1',
 					   timescaledb.compress_orderby = 'tm');
 WARNING:  compressed row size might exceed maximum row size
-DETAIL:  Estimated row size of compressed hypertable is 9952. This exceeds the maximum size of 8164 and can cause compression of chunks to fail.
+DETAIL:  Estimated row size of compressed hypertable is 9952. This exceeds the maximum size of 8160 and can cause compression of chunks to fail.

Comment (mkindahl) [reply src/hypertable.c]: You can use `\set VERBOSITY terse` to skip the error details in the test. Check for this in the other test files.

File: src/hypertable.c (hunk 4 above)
Comment (mkindahl) [reply src/hypertable.c]: If we do the check on the compressed table, then the check would be accurate, but unless I am misreading it, the check right now is on the uncompressed table, so then the calculations are off.

We can still make a conservative estimate by assuming that columns in the uncompressed table take at least 18 bytes, and that we have the additional columns, which would account also for segmentby columns that have a size that is less than 18 bytes, and hence be stored with the "uncompressed" size.

Not sure how the orderby would affect the row size.

File: src/hypertable.c (hunk 6 above)
Comment (sb230132) [reply src/hypertable.c]: Fixed.

**Review by mkindahl — APPROVED** [review]

**Review by fabriziomello — APPROVED** [review]
