### PR TITLE
Fix buffer overflow in partition scheme

### LINKED ISSUE #4050: [Bug]: Sanitizer test PG14.1 Sanitizer ubuntu-20.04 failed
### What type of bug is this?

Crash

### What subsystems and features are affected?

Other

### What happened?

The "Sanitizer test PG14.1 Sanitizer ubuntu-20.04" test keeps failing in CI/CD (see: https://github.com/timescale/timescaledb/runs/5027310902?check_suite_focus=true). 

### TimescaleDB version affected

2.6.0-dev

### PostgreSQL version used

14.1

### What operating system did you use?

ubuntu-20.04

### What installation method did you use?

Source

### What platform did you run on?

Other

### Relevant log output and stack trace

```bash
=================================================================
==postgres==13451==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x62500046e900 at pc 0x55d60a9b8010 bp 0x7ffe2a84e760 sp 0x7ffe2a84e750
READ of size 4 at 0x62500046e900 thread T0
    #0 0x55d60a9b800f in match_clause_to_partition_key /home/runner/pgbuild/src/backend/partitioning/partprune.c:1802
    #1 0x55d60a9b6b3b in gen_partprune_steps_internal /home/runner/pgbuild/src/backend/partitioning/partprune.c:1153
    #2 0x55d60a9bb6f7 in gen_partprune_steps /home/runner/pgbuild/src/backend/partitioning/partprune.c:739
    #3 0x55d60a9bc066 in make_partitionedrel_pruneinfo /home/runner/pgbuild/src/backend/partitioning/partprune.c:543
    #4 0x55d60a9bdf8d in make_partition_pruneinfo /home/runner/pgbuild/src/backend/partitioning/partprune.c:313
    #5 0x55d60a82bced in create_append_plan /home/runner/pgbuild/src/backend/optimizer/plan/createplan.c:1312
    #6 0x55d60a82246f in create_plan_recurse /home/runner/pgbuild/src/backend/optimizer/plan/createplan.c:417
    #7 0x55d60a830945 in create_sort_plan /home/runner/pgbuild/src/backend/optimizer/plan/createplan.c:2105
    #8 0x55d60a8226f5 in create_plan_recurse /home/runner/pgbuild/src/backend/optimizer/plan/createplan.c:484
    #9 0x55d60a832bb0 in create_agg_plan /home/runner/pgbuild/src/backend/optimizer/plan/createplan.c:2234
    #10 0x55d60a822770 in create_plan_recurse /home/runner/pgbuild/src/backend/optimizer/plan/createplan.c:504
    #11 0x55d60a82ee2a in create_customscan_plan /home/runner/pgbuild/src/backend/optimizer/plan/createplan.c:4158
    #12 0x55d60a82fae3 in create_scan_plan /home/runner/pgbuild/src/backend/optimizer/plan/createplan.c:770
    #13 0x55d60a82244b in create_plan_recurse /home/runner/pgbuild/src/backend/optimizer/plan/createplan.c:408
    #14 0x55d60a8241b9 in create_plan /home/runner/pgbuild/src/backend/optimizer/plan/createplan.c:344
    #15 0x55d60a877cb2 in standard_planner /home/runner/pgbuild/src/backend/optimizer/plan/planner.c:407
    #16 0x7f433d38418c in timescaledb_planner /home/runner/work/timescaledb/timescaledb/src/planner.c:416
    #17 0x55d60a87b081 in planner /home/runner/pgbuild/src/backend/optimizer/plan/planner.c:269
    #18 0x55d60acdbb66 in pg_plan_query /home/runner/pgbuild/src/backend/tcop/postgres.c:847
    #19 0x55d60acdc3f3 in pg_plan_queries /home/runner/pgbuild/src/backend/tcop/postgres.c:939
    #20 0x55d60b1f6b2e in BuildCachedPlan /home/runner/pgbuild/src/backend/utils/cache/plancache.c:935
    #21 0x55d60b1f831f in GetCachedPlan /home/runner/pgbuild/src/backend/utils/cache/plancache.c:1217
    #22 0x55d60a254637 in ExecuteQuery /home/runner/pgbuild/src/backend/commands/prepare.c:230
    #23 0x55d60acf05bb in standard_ProcessUtility /home/runner/pgbuild/src/backend/tcop/utility.c:754
    #24 0x7f43470be9ee in loader_process_utility_hook /home/runner/work/timescaledb/timescaledb/src/loader/loader.c:568
    #25 0x7f433d3a8993 in prev_ProcessUtility /home/runner/work/timescaledb/timescaledb/src/process_utility.c:90
    #26 0x7f433d3b7041 in timescaledb_ddl_command_start /home/runner/work/timescaledb/timescaledb/src/process_utility.c:4296
    #27 0x55d60acf12db in ProcessUtility /home/runner/pgbuild/src/backend/tcop/utility.c:523
    #28 0x55d60ace94b1 in PortalRunUtility /home/runner/pgbuild/src/backend/tcop/pquery.c:1155
    #29 0x55d60acea759 in FillPortalStore /home/runner/pgbuild/src/backend/tcop/pquery.c:1028
    #30 0x55d60aceb554 in PortalRun /home/runner/pgbuild/src/backend/tcop/pquery.c:760
    #31 0x55d60acdd001 in exec_simple_query /home/runner/pgbuild/src/backend/tcop/postgres.c:1214
    #32 0x55d60ace251e in PostgresMain /home/runner/pgbuild/src/backend/tcop/postgres.c:4486
    #33 0x55d60aa05383 in BackendRun /home/runner/pgbuild/src/backend/postmaster/postmaster.c:4530
    #34 0x55d60aa1027f in BackendStartup /home/runner/pgbuild/src/backend/postmaster/postmaster.c:4252
    #35 0x55d60aa11000 in ServerLoop /home/runner/pgbuild/src/backend/postmaster/postmaster.c:1745
    #36 0x55d60aa13544 in PostmasterMain /home/runner/pgbuild/src/backend/postmaster/postmaster.c:1417
    #37 0x55d60a5fd65e in main /home/runner/pgbuild/src/backend/main/main.c:209
    #38 0x7f434aeef0b2 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x270b2)
    #39 0x55d60996c4bd in _start (/home/runner/postgresql/bin/postgres+0x27da4bd)

0x62500046e900 is located 0 bytes to the right of 8192-byte region [0x62500046c900,0x62500046e900)
allocated by thread T0 here:
    #0 0x55d6099f8e07 in __interceptor_malloc (/home/runner/postgresql/bin/postgres+0x2866e07)
    #1 0x55d60b302d8a in AllocSetAlloc /home/runner/pgbuild/src/backend/utils/mmgr/aset.c:920
    #2 0x55d60b32848d in MemoryContextAllocZeroAligned /home/runner/pgbuild/src/backend/utils/mmgr/mcxt.c:956
    #3 0x55d60a96ad0b in make_restrictinfo_internal /home/runner/pgbuild/src/backend/optimizer/util/restrictinfo.c:118
    #4 0x55d60a96c54d in make_restrictinfo /home/runner/pgbuild/src/backend/optimizer/util/restrictinfo.c:89
    #5 0x7f433d38c3c9 in timebucket_annotate /home/runner/work/timescaledb/timescaledb/src/plan_expand_hypertable.c:745
    #6 0x7f433d38cd43 in timebucket_annotate_walker /home/runner/work/timescaledb/timescaledb/src/plan_expand_hypertable.c:1163
    #7 0x7f433d392c39 in ts_plan_expand_timebucket_annotate /home/runner/work/timescaledb/timescaledb/src/plan_expand_hypertable.c:1194
    #8 0x7f433d37fbf0 in timescaledb_get_relation_info_hook /home/runner/work/timescaledb/timescaledb/src/planner.c:988
    #9 0x55d60a944f00 in get_relation_info /home/runner/pgbuild/src/backend/optimizer/util/plancat.c:482
    #10 0x55d60a96086e in build_simple_rel /home/runner/pgbuild/src/backend/optimizer/util/relnode.c:307
    #11 0x55d60a83a297 in add_base_rels_to_query /home/runner/pgbuild/src/backend/optimizer/plan/initsplan.c:114
    #12 0x55d60a83a400 in add_base_rels_to_query /home/runner/pgbuild/src/backend/optimizer/plan/initsplan.c:122
    #13 0x55d60a849e19 in query_planner /home/runner/pgbuild/src/backend/optimizer/plan/planmain.c:166
    #14 0x55d60a86e544 in grouping_planner /home/runner/pgbuild/src/backend/optimizer/plan/planner.c:1442
    #15 0x55d60a87648b in subquery_planner /home/runner/pgbuild/src/backend/optimizer/plan/planner.c:1019
    #16 0x55d60a877c81 in standard_planner /home/runner/pgbuild/src/backend/optimizer/plan/planner.c:400
    #17 0x7f433d38418c in timescaledb_planner /home/runner/work/timescaledb/timescaledb/src/planner.c:416
    #18 0x55d60a87b081 in planner /home/runner/pgbuild/src/backend/optimizer/plan/planner.c:269
    #19 0x55d60acdbb66 in pg_plan_query /home/runner/pgbuild/src/backend/tcop/postgres.c:847
    #20 0x55d60acdc3f3 in pg_plan_queries /home/runner/pgbuild/src/backend/tcop/postgres.c:939
    #21 0x55d60b1f6b2e in BuildCachedPlan /home/runner/pgbuild/src/backend/utils/cache/plancache.c:935
    #22 0x55d60b1f831f in GetCachedPlan /home/runner/pgbuild/src/backend/utils/cache/plancache.c:1217
    #23 0x55d60a254637 in ExecuteQuery /home/runner/pgbuild/src/backend/commands/prepare.c:230
    #24 0x55d60acf05bb in standard_ProcessUtility /home/runner/pgbuild/src/backend/tcop/utility.c:754
    #25 0x7f43470be9ee in loader_process_utility_hook /home/runner/work/timescaledb/timescaledb/src/loader/loader.c:568
    #26 0x7f433d3a8993 in prev_ProcessUtility /home/runner/work/timescaledb/timescaledb/src/process_utility.c:90
    #27 0x7f433d3b7041 in timescaledb_ddl_command_start /home/runner/work/timescaledb/timescaledb/src/process_utility.c:4296
    #28 0x55d60acf12db in ProcessUtility /home/runner/pgbuild/src/backend/tcop/utility.c:523
    #29 0x55d60ace94b1 in PortalRunUtility /home/runner/pgbuild/src/backend/tcop/pquery.c:1155

Shadow bytes around the buggy address:
  0x0c4a80085cd0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c4a80085ce0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c4a80085cf0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c4a80085d00: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c4a80085d10: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x0c4a80085d20:[fa]fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c4a80085d30: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c4a80085d40: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c4a80085d50: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c4a80085d60: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c4a80085d70: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==postgres==13451==ABORTING
```

### How can we reproduce the bug?

```bash
Run the "Sanitizer test PG14.1 Sanitizer ubuntu-20.04" test in github CI/CD
```

### PR DESCRIPTION
**Pull request by mfundul**
Reallocate the partitioning attributes arrays when forcing GROUP BY
aggregates down.

Fixes #4050

### CODE REVIEW

**Review by mkindahl — APPROVED** [review]
LGTM

File: tsl/src/fdw/data_node_scan_plan.c [hunk 1]
```diff
@@ -302,10 +302,17 @@ force_group_by_push_down(PlannerInfo *root, RelOptInfo *hyper_rel)
...
-	/* Only reallocate the partitioning attributes array if it is smaller than
+	/* Only reallocate the partitioning attributes arrays if it is smaller than
 	 * the new size */
 	if (partscheme->partnatts < new_partnatts)
+	{
+		partscheme->partopfamily = repalloc(partscheme->partopfamily, new_partnatts * sizeof(Oid));
+		partscheme->partopcintype =
+			repalloc(partscheme->partopcintype, new_partnatts * sizeof(Oid));
+		partscheme->partcollation =
+			repalloc(partscheme->partcollation, new_partnatts * sizeof(Oid));
```
Comment (erimatnor) [inline tsl/src/fdw/data_node_scan_plan.c:313]: Should we also reallocate `hyper_rel->nullable_partexprs` here?

**Review by svenklemm — APPROVED** [review]

File: tsl/src/fdw/data_node_scan_plan.c [hunk 2]
```diff
@@ -302,10 +302,17 @@ force_group_by_push_down(PlannerInfo *root, RelOptInfo *hyper_rel)
...
 		hyper_rel->partexprs = (List **) palloc0(sizeof(List *) * new_partnatts);
```
Comment (erimatnor) [inline tsl/src/fdw/data_node_scan_plan.c:314]: repalloc0 here as well?

File: tsl/src/fdw/data_node_scan_plan.c [hunk 3]
```diff
@@ -302,13 +306,32 @@ force_group_by_push_down(PlannerInfo *root, RelOptInfo *hyper_rel)
...
+			partopfamily[i] = partscheme->partopfamily[i];
+			partopcintype[i] = partscheme->partopcintype[i];
+			partcollation[i] = partscheme->partcollation[i];
+			nullable_partexprs[i] = hyper_rel->nullable_partexprs[i];
+		}
+		partscheme->partopfamily = partopfamily;
+		partscheme->partopcintype = partopcintype;
+		partscheme->partcollation = partcollation;
+		hyper_rel->nullable_partexprs = nullable_partexprs;
+
```
Comment (mkindahl) [inline tsl/src/fdw/data_node_scan_plan.c:328]: This is what `realloc` does, so why do it explicitly? Also note that you can declare variables inside the if-body, which avoids the need to reset the `i` below and avoid a potential bug.

Comment (mfundul) [reply tsl/src/fdw/data_node_scan_plan.c:328]: Realloc doesn't zero out the free space, which is a problem cause we probably need the `InvalidOid` and `NULL` pointers in there.

**Review by svenklemm — APPROVED** [review]

File: tsl/src/fdw/data_node_scan_plan.c (hunk 3 above)
Comment (mkindahl) [reply tsl/src/fdw/data_node_scan_plan.c:328]: In that case, I think that `palloc0` and `memcpy` is a better alternative and easier to maintain, but I leave the choice to you. Either way, you need a comment about why you do it this way, otherwise, somebody will "optimize" this and introduce a subtle bug.
