### PR TITLE
Fix segfault when setting chunk replica identity

### LINKED ISSUE #7406: [Bug]: PG Segfault when ETL upsert triggers insert to empty hypertable
### What type of bug is this?

Crash

### What subsystems and features are affected?

Data ingestion

### What happened?

Sling is running an ETL from external SQL Server DB. I wanted to trigger on insert+update to the target table, to generate new rows when there is a change to get deltas. Postgres would segfault and enter recovery mode. Workaround was to type manual "UPDATE X WHERE" for single record to generate the first delta row in the hyper table, then restart the ETL.

Running truncate on the delta hypertable causes the crash to reappear.

### TimescaleDB version affected

timescaledb-2-postgresql-16/noble,now 2.17.1~ubuntu24.04

### PostgreSQL version used

postgresql-16/now 16.4-1.pgdg22.04+2

### What operating system did you use?

Ubuntu 24.04.01

### What installation method did you use?

Deb/Apt

### What platform did you run on?

On prem/Self-hosted

### Relevant log output and stack trace

```bash
2024-10-29 11:37:59.165 AWST [6783] LOG:  server process (PID 3102803) was terminated by signal 11: Segmentation fault
2024-10-29 11:37:59.165 AWST [6783] DETAIL:  Failed process was running: create temporary table temp29Eub as
                with src_table as (
                        select "pack_summary_id", "event_id", "summary_group_id", "product_id", "pack_id", "pack_count", [...] from "public"."szdb_pack_summary_tmp"
                )
                , updates as (
                        update "public"."szdb_pack_summary" tgt
                        set "event_id" = src."event_id", "summary_group_id" = src."summary_group_id", "product_id" = src."product_id", "pack_id" = src."pack_id", "pack_count" = src."pack_count", [...]
```

### How can we reproduce the bug?

```bash
The ETL command that triggers the bug is:

create temporary table temp29Eub as
        with src_table as (
                select "pack_summary_id", "event_id", "summary_group_id", "product_id", "pack_id", "pack_count", [...]
)
, updates as (
update "public"."szdb_pack_summary" tgt
set "event_id" = src."event_id", "summary_group_id" = src."summary_group_id", "product_id" = src."product_id", "pack_id" = src."pack_id", [...]
from src_table src
where src."pack_summary_id" = tgt."pack_summary_id"
returning tgt.*
)
select * from updates


Setup for the database is
CREATE TABLE szdb_pack_summary_diff (
    pack_summary_id integer NOT NULL,
    time timestamptz NOT NULL,
    packs bigint,
    count bigint,
    weight double precision,
    event_id integer NOT NULL,
    product_id integer,
    pack_id integer
);
SELECT create_hypertable('szdb_pack_summary_diff', by_range('time', INTERVAL '1 week'));

CREATE OR REPLACE FUNCTION szdb_diff_pack_summary() RETURNS TRIGGER AS $$
BEGIN
    IF NEW.fruit_count <> OLD.fruit_count THEN
        INSERT INTO szdb_pack_summary_diff (pack_summary_id, time, packs, count, weight, event_id, product_id, pack_id)
        VALUES (NEW.pack_summary_id, NOW(), NEW.pack_count - OLD.pack_count, NEW.fruit_count - OLD.fruit_count, NEW.weight_grams - OLD.weight_grams, NEW.event_id, NEW.product_id, NEW.pack_id);
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION szdb_init_pack_summary() RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO szdb_pack_summary_diff (pack_summary_id, time, packs, count, weight, event_id, product_id, pack_id)
    VALUES (NEW.pack_summary_id, NOW(), NEW.pack_count, NEW.fruit_count, NEW.weight_grams, NEW.event_id, NEW.product_id, NEW.pack_id);

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER after_insert_drop_summary_diff AFTER
INSERT ON szdb_pack_summary
FOR EACH ROW EXECUTE FUNCTION szdb_init_pack_summary();

CREATE TRIGGER after_update_drop_summary_diff AFTER
UPDATE ON szdb_pack_summary
FOR EACH ROW EXECUTE FUNCTION szdb_diff_pack_summary();
```

### PR DESCRIPTION
**Pull request by fabriziomello**
The segfault happened executing `AlterTableInternal` for setting the REPLICA IDENTITY during chunk creation (introduced by https://github.com/timescale/timescaledb/issues/5512) that is dispatched by a trigger invoked by a DDL statement.

Fixed it by using our internal `ts_alter_table_with_event_trigger` handler function to setup the event trigger context.

Fixes #7406

### CODE REVIEW

File: src/chunk.c [hunk 1]
```diff
@@ -900,7 +900,9 @@ chunk_set_replica_identity(const Chunk *chunk)
 	}
 
 	ts_catalog_database_info_become_owner(ts_catalog_database_info_get(), &sec_ctx);
+	EventTriggerAlterTableStart((Node *) &cmd);
 	AlterTableInternal(chunk->table_id, list_make1(&cmd), false);
+	EventTriggerAlterTableEnd();
 	ts_catalog_restore_user(&sec_ctx);
 	table_close(ht_rel, NoLock);
```
Comment (mkindahl) [inline src/chunk.c:907]: This can be called in a nested fashion since the start and end commands remember the previous value of `currentCommand`. You might want to add a comment explaining why the start and end are necessary though, for your future self.

File: src/chunk.c
Comment (mkindahl) [inline src/chunk.c:1]: We have one more call to `AlterTableInternal` in `set_attoptions` which looks like it could cause a similar problem. You might want to fix that at the same time (but you might want to check a call to this function in a debugger to make sure that it is not set up higher in the call stack).

File: src/chunk.c [hunk 2]
```diff
@@ -900,7 +900,9 @@ chunk_set_replica_identity(const Chunk *chunk)
 	}
 
 	ts_catalog_database_info_become_owner(ts_catalog_database_info_get(), &sec_ctx);
+	EventTriggerAlterTableStart((Node *) &cmd);
 	AlterTableInternal(chunk->table_id, list_make1(&cmd), false);
```
Comment (mkindahl) [inline src/chunk.c:904]: The first argument to AlterTableInternal should be an OID and it indeed looks like `table_id` is taken from the `ObjectAddress` for the chunk. You might want to double-check, but it seems to make no difference for this particular case.

**Review by mkindahl — APPROVED** [review]
The commit comment is very focused on the code, so you might want to re-write it to explain the context so your future self can understand what the problem was.

This problem can occur when you insert into a hypertable from inside a trigger, so starting there might be a good idea, that is:

Insert into hypertable calls `AlterTableInternal` [why?]... if called from inside a trigger, this will not have `currentCommand` set up [why and why does it work if not in a trigger?]... we need to wrap the call in `...Start` and `...End`.

A few suggestions for adding comments and one more call to `AlterTableInternal` that you might want to deal with (but fine to submit as separate PR if you prefer that).

Approving since the code looks fine and I see no issues with the fix.

**Comment by fabriziomello** [comment]
> The commit comment is very focused on the code, so you might want to re-write it to explain the context so your future self can understand what the problem was.
> 

Ok.

> This problem can occur when you insert into a hypertable from inside a trigger, so starting there might be a good idea, that is:

Will recheck but it was not so simple like this to reproduce the case.


> > Insert into hypertable calls `AlterTableInternal` [why?]... 

Because of this PR https://github.com/timescale/timescaledb/pull/5515. But looking now at the implementation looks like we didn't did a good job because we `always` call the `AlterTableInternal`, so I think we should improve it a bit:
```diff
➜ git diff                                                         
diff --git a/src/chunk.c b/src/chunk.c
index c2535d368..89105ba4a 100644
--- a/src/chunk.c
+++ b/src/chunk.c
@@ -875,6 +875,14 @@ static void
 chunk_set_replica_identity(const Chunk *chunk)
 {
    Relation ht_rel = relation_open(chunk->hypertable_relid, AccessShareLock);
+
+   /* Do nothing if hypertable is using the default replica identity */
+   if (ht_rel->rd_rel->relreplident == REPLICA_IDENTITY_DEFAULT)
+   {
+       table_close(ht_rel, NoLock);
+       return;
+   }
+
    ReplicaIdentityStmt stmt = {
        .type = T_ReplicaIdentityStmt,
        .identity_type = ht_rel->rd_rel->relreplident,
```


> if called from inside a trigger, this will not have `currentCommand` set up [why and why does it work if not in a trigger?]... we need to wrap the call in `...Start` and `...End`.
> 

Will recheck!

> A few suggestions for adding comments and one more call to `AlterTableInternal` that you might want to deal with (but fine to submit as separate PR if you prefer that).
> 

The other one need to investigate if it is possible to raise the same problem.

File: src/chunk.c (hunk 1 above)
Comment (fabriziomello) [reply src/chunk.c]: Actually we have a function `ts_alter_table_with_event_trigger` to wrap the event trigger context and execute the `AlterTableInternal` that have the enough comments about why it is necessary.

**Review by mkindahl — APPROVED** [review]
