### PR TITLE
Fix permission problems with dropping hypertables and chunks

### LINKED ISSUE #226: can't drop a hypertable
With timescaledb version 0.5.0:

I am not sure if I do everything right, but the user (not a superuser), who created a hypertable, can't drop the hypertable:

```
postgres=# create database foo owner po1;
CREATE DATABASE
postgres=# \c foo
You are now connected to database "foo" as user "postgres".
foo=# create extension timescaledb;
CREATE EXTENSION
```

(`$ psql -U po1 foo`):

```
foo=> CREATE TABLE "test_t" ("baz" integer NOT NULL, "time" bigint NOT NULL, "value" double precision NOT NULL);
CREATE TABLE
foo=> SELECT create_hypertable('test_t', 'time', chunk_time_interval => 2592000000);
 create_hypertable 
-------------------
 
(1 row)

foo=> DROP TABLE "test_t";
ERROR:  permission denied for relation hypertable
CONTEXT:  SQL statement "DELETE FROM _timescaledb_catalog.hypertable h
    WHERE h.id = drop_hypertable.hypertable_id"
PL/pgSQL function _timescaledb_internal.drop_hypertable(integer,boolean) line 8 at SQL statement
foo=> select * from _timescaledb_catalog.hypertable;
 id | schema_name | table_name | associated_schema_name | associated_table_prefix | num_dimensions 
----+-------------+------------+------------------------+-------------------------+----------------
  1 | public      | test_t     | _timescaledb_internal  | _hyper_1                |              1
(1 row)

foo=> SELECT has_table_privilege('_timescaledb_catalog.hypertable', 'delete');
 has_table_privilege 
---------------------
 f
(1 row)

foo=> \dp _timescaledb_catalog.*
                                              Access privileges
        Schema        |          Name          |   Type   | Access privileges | Column privileges | Policies 
----------------------+------------------------+----------+-------------------+-------------------+----------
 _timescaledb_catalog | chunk                  | table    | postgres=arwdDxt/postgres    +|                   | 
                      |                        |          | =r/postgres             |                   | 
 _timescaledb_catalog | chunk_constraint       | table    | postgres=arwdDxt/postgres    +|                   | 
                      |                        |          | =r/postgres             |                   | 
 _timescaledb_catalog | chunk_constraint_name  | sequence |                   |                   | 
 _timescaledb_catalog | chunk_id_seq           | sequence |                   |                   | 
 _timescaledb_catalog | chunk_index            | table    | postgres=arwdDxt/postgres    +|                   | 
                      |                        |          | =r/postgres             |                   | 
 _timescaledb_catalog | chunk_index_id_seq     | sequence |                   |                   | 
 _timescaledb_catalog | dimension              | table    | postgres=arwdDxt/postgres    +|                   | 
                      |                        |          | =r/postgres             |                   | 
 _timescaledb_catalog | dimension_id_seq       | sequence |                   |                   | 
 _timescaledb_catalog | dimension_slice        | table    | postgres=arwdDxt/postgres    +|                   | 
                      |                        |          | =r/postgres             |                   | 
 _timescaledb_catalog | dimension_slice_id_seq | sequence |                   |                   | 
 _timescaledb_catalog | hypertable             | table    | postgres=arwdDxt/postgres    +|                   | 
                      |                        |          | =r/postgres             |                   | 
 _timescaledb_catalog | hypertable_id_seq      | sequence |                   |                   | 
 _timescaledb_catalog | hypertable_index       | table    | postgres=arwdDxt/postgres    +|                   | 
                      |                        |          | =r/postgres             |                   | 
 _timescaledb_catalog | tablespace             | table    | postgres=arwdDxt/postgres    +|                   | 
                      |                        |          | =r/postgres             |                   | 
 _timescaledb_catalog | tablespace_id_seq      | sequence |                   |                   | 
(15 rows)
```

### PR DESCRIPTION
**Pull request by cevian**
This change fixes permissions with dropping hypertables and chunks.
Fixes #226.

### CODE REVIEW

File: sql/ddl_internal.sql [hunk 1]
```diff
@@ -506,15 +528,23 @@ CREATE OR REPLACE FUNCTION _timescaledb_internal.truncate_hypertable(
...
     AND ht.table_name = truncate_hypertable.table_name;
 
-    PERFORM  _timescaledb_internal.drop_chunk(c.id, FALSE)
-    FROM _timescaledb_catalog.chunk c
-    WHERE hypertable_id = hypertable_row.id;
+    FOR chunk_row IN SELECT c.*
+        FROM _timescaledb_catalog.chunk c
+        WHERE hypertable_id = hypertable_row.id 
+        LOOP
+            --TODO: should this cascade?
```
Comment (olofr) [inline sql/ddl_internal.sql]: Shouldn't this have a cascade_mod the same way as above to match the semantics ? Or do we intend to block any dependencies hypertable -> ordinary tables ?

File: sql/ddl_internal.sql [hunk 2]
```diff
@@ -267,18 +280,27 @@ CREATE OR REPLACE FUNCTION _timescaledb_internal.drop_chunks_older_than(
...
-    INNER JOIN _timescaledb_catalog.hypertable h ON (h.id = c.hypertable_id)
-    INNER JOIN  _timescaledb_internal.dimension_get_time(h.id) time_dimension ON(true)
-    INNER JOIN _timescaledb_catalog.dimension_slice ds
-        ON (ds.dimension_id =  time_dimension.id)
-    INNER JOIN _timescaledb_catalog.chunk_constraint cc
-        ON (cc.dimension_slice_id = ds.id AND cc.chunk_id = c.id)
-    WHERE ds.range_end <= older_than_time
-    AND (drop_chunks_older_than.schema_name IS NULL OR h.schema_name = drop_chunks_older_than.schema_name)
-    AND (drop_chunks_older_than.table_name IS NULL OR h.table_name = drop_chunks_older_than.table_name);
+    FOR chunk_row IN SELECT *
```
Comment (erimatnor) [inline sql/ddl_internal.sql]: Seems there's a lot of overlap between this function and `truncate_hypertable()`. This has also regressed now since removing `drop_chunk()`. Would be good to make some function that isolates this FOR-loop to one implementation/function that makes the DROP chunk statement. You could even have one loop that accepts a NULL time value to mean "all" chunks from beginning of time. That would cover both use-cases.

File: sql/ddl_internal.sql (hunk 1 above)
Comment (erimatnor) [reply sql/ddl_internal.sql]: I think it must always cascade, otherwise truncating chunk tables with views or foreign keys referencing them will fail without CASCADE, which it wouldn't do on regular tables. I think creating views or other objects directly on chunks as opposed to the main table should probably come with that caveat.

File: src/catalog.c [hunk 3]
```diff
@@ -111,8 +111,8 @@ const static InternalFunctionDef internal_function_definitions[_MAX_INTERNAL_FUN
 		.args = 3
 	},
 	[DDL_DROP_CHUNK] = {
-		.name = "drop_chunk",
-		.args = 3
+		.name = "drop_chunk_metadata",
```
Comment (erimatnor) [inline src/catalog.c]: Now the semantics of `DDL_DROP_CHUNK` is unclear, including the DDL-upcall function  `process_drop_chunk`.

File: src/process_utility.c [hunk 4]
```diff
@@ -328,19 +326,26 @@ process_drop_table(DropStmt *stmt)
 			ht = hypertable_cache_get_entry(hcache, relid);
 			if (NULL != ht)
 			{
+				CatalogSecurityContext sec_ctx;
+
 				if (list_length(stmt->objects) != 1)
 					elog(ERROR, "Cannot drop a hypertable along with other objects");
 
+				catalog_become_owner(catalog_get(), &sec_ctx);
```
Comment (erimatnor) [inline src/process_utility.c]: Now the SQL upcalls require the precondition of being called while being the catalog owner, although they are accessible (and callable) by anyone (as opposed to a C function that cannot be called easily). At the very least, we should probably document that these functions only work if called as the catalog owner (in case a user calls, e.g., drop_hypertable manually, or someone changing the SQL code calls that function). Maybe also add a user check in the functions to ensure that they are called with the right user.

File: src/process_utility.c [hunk 5]
```diff
@@ -328,19 +326,26 @@ process_drop_table(DropStmt *stmt)
 			ht = hypertable_cache_get_entry(hcache, relid);
 			if (NULL != ht)
 			{
+				CatalogSecurityContext sec_ctx;
```
Comment (erimatnor) [inline src/process_utility.c]: could we just move this to the top level of this function? I don't see a problem with doing that right now, and it would avoid a lot of repetitive stuff.

File: src/process_utility.c (hunk 4 above)
Comment (cevian) [reply src/process_utility.c]: So 2 points:

Comment (cevian) [reply src/process_utility.c]: So 2 points:
1) These functions don't have a precondition of being run as any user. They will just fail with a permission error if the user doesn't have the right permissions. This is both safe and the right thing to do.
2) Functions in _timescaledb_internal are not for user-consumption. I don't see a need to document any of these extensively. Although I can if you insist.

File: sql/ddl_internal.sql [hunk 6]
```diff
@@ -267,18 +280,27 @@ CREATE OR REPLACE FUNCTION _timescaledb_internal.drop_chunks_older_than(
...
+        FROM _timescaledb_catalog.chunk c
+        INNER JOIN _timescaledb_catalog.hypertable h ON (h.id = c.hypertable_id)
+        INNER JOIN  _timescaledb_internal.dimension_get_time(h.id) time_dimension ON(true)
+        INNER JOIN _timescaledb_catalog.dimension_slice ds
+            ON (ds.dimension_id =  time_dimension.id)
```
[the remark this answers is not in the document]
Comment (cevian) [reply sql/ddl_internal.sql]: fixed

File: sql/ddl_internal.sql [hunk 7]
```diff
@@ -267,18 +280,27 @@ CREATE OR REPLACE FUNCTION _timescaledb_internal.drop_chunks_older_than(
...
+        INNER JOIN _timescaledb_catalog.chunk_constraint cc
+            ON (cc.dimension_slice_id = ds.id AND cc.chunk_id = c.id)
+        WHERE ds.range_end <= older_than_time
+        AND (drop_chunks_older_than.schema_name IS NULL OR h.schema_name = drop_chunks_older_than.schema_name)
```
[the remark this answers is not in the document]
Comment (cevian) [reply sql/ddl_internal.sql]: added docs

File: sql/ddl_internal.sql (hunk 2 above)
Comment (cevian) [reply sql/ddl_internal.sql]: Yep changed `drop_chunk_older_than` to accept NULL times. Made truncate_hypertable call that function.

File: src/catalog.c (hunk 3 above)
Comment (cevian) [reply src/catalog.c]: changed names. Is that what you meant?

File: src/process_utility.c (hunk 5 above)
Comment (cevian) [reply src/process_utility.c]: done

**Comment by cevian** [comment]
@erimatnor please review again

File: sql/ddl_internal.sql [hunk 8]
```diff
@@ -259,26 +272,39 @@ $BODY$
 $BODY$;
 
 -- Drop chunks older than the given timestamp. If a hypertable name is given,
--- drop only chunks associated with this table.
+-- drop only chunks associated with this table. Any of the three arguments
+-- can be NULL meaning "all values".
 CREATE OR REPLACE FUNCTION _timescaledb_internal.drop_chunks_older_than(
```
Comment (erimatnor) [inline sql/ddl_internal.sql]: Nit: I would actually make this an "internal" function that would be discouraged to call directly,  and then have two functions: `drop_chunks()` and `drop_chunks_older_than()` that  don't accept NULL arguments but internally calls the "internal" function.

File: sql/ddl_internal.sql [hunk 9]
```diff
@@ -506,15 +532,9 @@ CREATE OR REPLACE FUNCTION _timescaledb_internal.truncate_hypertable(
...
-
-    SELECT * INTO STRICT hypertable_row
-    FROM _timescaledb_catalog.hypertable ht
-    WHERE ht.schema_name = truncate_hypertable.schema_name
-    AND ht.table_name = truncate_hypertable.table_name;
-
-    PERFORM  _timescaledb_internal.drop_chunk(c.id, FALSE)
-    FROM _timescaledb_catalog.chunk c
-    WHERE hypertable_id = hypertable_row.id;
+    --TODO: should this cascade?
```
Comment (erimatnor) [inline sql/ddl_internal.sql]: I think this CASCADE stuff should be determined in this PR.

I've been trying to backtrack and figure out what the discussion regarding CASCADE behavior has been thus far. But it is not clear what the decision is and the comment here seems to indicate it is undecided.

IMHO, the only way to make truncate work the same way as regular Postgres is to actually truncate the subtables instead of removing them. That would solve the cascade problem and would work with dependent objects as expected. Not clear to me why truncate isn't actually doing truncate (I know this decisions was made before, but I have doubts it was the right one). If someone really wants to delete the tables, they should call `DROP TABLE` or `drop_chunks()`. If we really want to delete the chunks during truncate, we should do it by always cascading because otherwise the TRUNCATE command might fail, which I am not sure would be right. At the very least we should in that case have an informative message saying that there are dependent objects that has to be removed first, but this is a bit weird since that is not required with regular Postgres.

File: sql/ddl_internal.sql [hunk 10]
```diff
@@ -259,26 +272,39 @@ $BODY$
...
+        INNER JOIN _timescaledb_catalog.chunk_constraint cc
+            ON (cc.dimension_slice_id = ds.id AND cc.chunk_id = c.id)
+        WHERE (older_than_time IS NULL OR ds.range_end <= older_than_time)
+        AND (drop_chunks_older_than.schema_name IS NULL OR h.schema_name = drop_chunks_older_than.schema_name)
+        AND (drop_chunks_older_than.table_name IS NULL OR h.table_name = drop_chunks_older_than.table_name)
+    LOOP
+        EXECUTE format(
+                $$
+                DROP TABLE %I.%I
+                $$, chunk_row.schema_name, chunk_row.table_name
```
Comment (erimatnor) [inline sql/ddl_internal.sql]: If we don't have CASCADE support here, what happens when there are dependent objects and someone calls `drop_chunks_older_than()` as part of a retention policy script? I guess the retention policy will simply fail and the database might, e.g., run out of disk space? That sounds bad. CASCADE should at least be an option IMO.

File: sql/ddl_internal.sql (hunk 8 above)
Comment (cevian) [reply sql/ddl_internal.sql]: I am confused. This is an internal function by virtue of it being in the _timescaledb_internal schema. What do you mean?

File: sql/ddl_internal.sql (hunk 9 above)
Comment (cevian) [reply sql/ddl_internal.sql]: I am ok changing this to run truncate instead of drop on the chunks. I think @olofr might have an opinion here.

File: sql/ddl_internal.sql (hunk 10 above)
Comment (cevian) [reply sql/ddl_internal.sql]: Yep  adding an option is probably a good idea. Will do.

File: sql/ddl_internal.sql (hunk 9 above)
Comment (olofr) [reply sql/ddl_internal.sql]: I think a TRUNCATE should ideally remove chunks as the chunks are something under the hood. I don't understand why we can't let the `TRUNCATE hypertable  [ CASCADE | RESTRICT ]` just become `DROP TABLE chunk  [ CASCADE | RESTRICT ]`  with the CASCADE option inherited for each chunk. Shouldn't that have the same dependency effects as a truncate on a normal table ?

**Comment by cevian** [comment]
Ah yes for some reason I thought truncate did not have a CASCADE option.
Will fix.

File: sql/ddl_internal.sql (hunk 9 above)
Comment (erimatnor) [reply sql/ddl_internal.sql]: @olofr The problem with removing chunks is that it requires also removing dependent objects, which is not the case for a TRUNCATE on a regular table. So even if I agree with the under-the-hood argument in general, this would mean our TRUNCATE would be semantically different when dropping tables under the hood. Another difference is that we won't fire any ON TRUNCATE triggers on chunks, which means we won't support ON TRUNCATE triggers on hypertables in general (in fact, it would just silently not work, unless we modify processUtility to block adding such triggers). If we really want to remove chunks I think the correct way to deal with this is to first do TRUNCATE on all chunks, and only after that we'd DROP the chunks.

Comment (cevian) [reply sql/ddl_internal.sql]: I've implemented @olofr suggestion I think CASCADE is semantically similar in TRUNCATE and DROP (in both cases dependent objects are dropped). TRUNCATE triggers can only be fired on a table level and so if you add a truncate trigger to a hypertable everything would work fine. I don't think TRUNCATE triggers on chunks make sense, and would prefer to block them.

Comment (cevian) [reply sql/ddl_internal.sql]: Namely, this "which is not the case for a TRUNCATE on a regular table" is wrong. Truncate CASCADE does remove dependent objects.

Comment (erimatnor) [reply sql/ddl_internal.sql]: I am not sure I agree that TRUNCATE on chunks doesn't make sense. We've talked about supporting other chunk-level operations (and customer's have asked for it afaik), so I see no reason to restricting ourselves unnecessarily in this particular case. A user might for example want to get notified in a trigger when a chunk is TRUNCATED, either to block it on a particular chunk with valuable data, or, for just simply knowing when the data covering that particular time period is deleted (due to a retention policy or for other reasons). I think we should also keep an open mind for potential future use cases we haven't thought about. 

In general, I don't think we should restrict functionality or change semantics unless (1) it is too cumbersome to implement technically, or, (2) we cannot make it work correctly.

Btw, I don't think TRUNCATE CASCADE removes, e.g., a view on a chunk since the table remains, whereas DROP will remove the view. So, implementing TRUNCATE with DROP would be different. Still, I could accept removing views since it is a bit of a corner-case, but I still think we should support TRUNCATE triggers on chunks if we can, for example by doing what I suggested: recursing TRUNCATE to chunks first, then dropping tables. That seems to be the best of both worlds and shouldn't be hard to implement.

Comment (cevian) [reply sql/ddl_internal.sql]: Will do.

Comment (cevian) [reply sql/ddl_internal.sql]: Fixed now

**Comment by cevian** [comment]
@mfreed doc change is that drop_chunks now takes an additional parameter for CASCADE and there is now a drop_chunks for integer-based time.
