### PR TITLE
Fix fdw_relinfo_get assertion failure on DELETE

### LINKED ISSUE #3136: Segfault when running count(*) on view.
**Relevant system information:**
 - OS: Scientific Linux 7 x86_64 (EL clone)
 - PostgreSQL version: 13.2
 - TimescaleDB version: 2.2.0
 - Installation method: yum

**Describe the bug**
Running `SELECT count(*) FROM dynreq_per_vhost;` will cause a segfault, crashing the coordinator node.
`dynreq_per_vhost` is a view over table `nginx_access`.

**To Reproduce**
```
CREATE TABLE nginx_access(
    atime               timestamp NOT NULL,
    vhost_id            INT NOT NULL,
    vhost_alias_id      INT NOT NULL,
    ip                  INET NOT NULL,
    method              VARCHAR(8),
    uri                 VARCHAR(8192),
    status              SMALLINT NOT NULL,
    cache               VARCHAR(12),
    req_len             INT NOT NULL,
    bytes_sent          INT NOT NULL,
    body_size           INT NOT NULL,
    msec                INT NOT NULL,
    referer             VARCHAR(8192),
    useragent           VARCHAR(255),
    devicetype          SMALLINT NOT NULL,
    ssl_proto           VARCHAR(10),
    ssl_cipher          VARCHAR(128),
    ssl_reused          SMALLINT NOT NULL,
    ssl_early           SMALLINT NOT NULL,
    http2               SMALLINT NOT NULL
);
CREATE INDEX idx_nginx_access_vhost_id ON nginx_access(vhost_id);

SELECT create_distributed_hypertable('nginx_access', 'atime', 'vhost_id', chunk_time_interval => 10800);

CREATE OR REPLACE VIEW dynreq_per_vhost AS
    SELECT vhost_id,date_trunc('hour', atime) AS hour,COUNT(*) FROM nginx_access WHERE cache='MISS' GROUP BY vhost_id,date_trunc('hour', atime) ORDER BY vhost_id,hour;
```

Create the above table and view, then run the query.
In our experimental 1 coordinator + 3 data node setup, this has a 100% chance of producing a segfault.
Is this caused by the nested COUNT(*) perhaps?

**Expected behavior**
Expected a rowcount produced by the view.

**Actual behavior**
Coordinator node crashed with a segfault.

Log data:
```
2021-04-20 11:07:39.744 CEST [377104] LOG:  server process (PID 640644) was terminated by signal 11: Segmentation fault
2021-04-20 11:07:39.744 CEST [377104] DETAIL:  Failed process was running: select count(*) from dynreq_per_vhost;
2021-04-20 11:07:39.744 CEST [377104] LOG:  terminating any other active server processes
2021-04-20 11:07:39.744 CEST [640597] WARNING:  terminating connection because of crash of another server process
2021-04-20 11:07:39.744 CEST [640597] DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.
2021-04-20 11:07:39.744 CEST [640597] HINT:  In a moment you should be able to reconnect to the database and repeat your command.
2021-04-20 11:07:39.745 CEST [640735] FATAL:  the database system is in recovery mode
```

### PR DESCRIPTION
**Pull request by svenklemm**
The code in fdw_relinfo_get assumed rel->fdw_private and
rel->fdw_private->fdw_relation_info were always allocated
which is not true for DELETEs for instance.

Might fix #3136

### CODE REVIEW

File: tsl/src/fdw/relinfo.c [hunk 1]
```diff
@@ -81,10 +81,15 @@ apply_fdw_and_server_options(TsFdwRelInfo *fpinfo)
 TsFdwRelInfo *
 fdw_relinfo_get(RelOptInfo *rel)
 {
-	TimescaleDBPrivate *rel_private = rel->fdw_private;
+	TimescaleDBPrivate *rel_private;
+
+	if (!rel->fdw_private)
+		rel->fdw_private = palloc0(sizeof(TimescaleDBPrivate));
```
Comment (nikkhils) [inline tsl/src/fdw/relinfo.c:87]: This will always populate the `rel->fdw_private` field. 

I wonder if this will have any unwanted side effects. So the question is; are there any issues with creating a zeroed out `fdw_private` on other code paths?

Comment (svenklemm) [reply tsl/src/fdw/relinfo.c]: we always create it like that so all the code should be able to handle it, also the Assert for fdw_private being NULL wasnt hit in my tests but it felt better to add this too since the assert below was hit and those two are similar and we can't say for sure if there isn't a query where fdw_private will be NULL

**Review by nikkhils — APPROVED** [review]
LGTM

File: tsl/src/fdw/relinfo.c [hunk 2]
```diff
@@ -81,10 +81,15 @@ apply_fdw_and_server_options(TsFdwRelInfo *fpinfo)
 TsFdwRelInfo *
 fdw_relinfo_get(RelOptInfo *rel)
 {
-	TimescaleDBPrivate *rel_private = rel->fdw_private;
+	TimescaleDBPrivate *rel_private;
+
+	if (!rel->fdw_private)
+		rel->fdw_private = ts_create_private_reloptinfo(rel);
```
Comment (mfundul) [inline tsl/src/fdw/relinfo.c:87]: `ts_create_private_reloptinfo()` appears to set `rel->fdw_private` itself, so it's not needed to assign `rel->fdw_private =`.

File: tsl/src/fdw/relinfo.c [hunk 3]
```diff
@@ -96,7 +101,7 @@ fdw_relinfo_alloc(RelOptInfo *rel, TsFdwRelInfoType reltype)
 	TsFdwRelInfo *fpinfo;
 
 	if (NULL == rel->fdw_private)
-		rel->fdw_private = palloc0(sizeof(*rel_private));
+		rel->fdw_private = ts_create_private_reloptinfo(rel);
```
Comment (mfundul) [inline tsl/src/fdw/relinfo.c:104]: Same as above.

**Review by mfundul — APPROVED** [review]
