### PR TITLE
Remove parallel safe from partialize_agg

### LINKED ISSUE #4922: [Bug]: Inconsistent and Incorrect Aggregations
### What type of bug is this?

Incorrect result

### What subsystems and features are affected?

Multi-node

### What happened?

Queries utilising partial aggregation return incorrect and inconsistent results.

Example:
Query 1
`SELECT sum(value)
FROM table;`

Query 2
`SELECT SUM(value) FROM (
SELECT value
FROM table
ORDER BY 1) a;`

Query 1 will produce incorrect results, where Query 2 will bypass partial aggregation on the data nodes and return correctly.

### TimescaleDB version affected

2.8.1

### PostgreSQL version used

14.5

### What operating system did you use?

Ubuntu 22.04.1 x64

### What installation method did you use?

Docker

### What platform did you run on?

Amazon Web Services (AWS)

### Relevant log output and stack trace

_No response_

### How can we reproduce the bug?

Running `timescaledb-ha pg14.5-ts2.8.1-p0` on 1 access node with 4 data nodes using EKS with all nodes in the same availability zone.

```SQL
create table example_table_name
(
    time  timestamp not null,
    key_1 text,
    key_2 text,
    key_3 text,
    value double precision
);

SELECT create_distributed_hypertable(example_table_name, "time");

SELECT set_chunk_time_interval(example_table_name, INTERVAL '1h');

SELECT add_retention_policy(example_table_name, INTERVAL '30d');
```

Data of the form `(1664496000, 'a', '1efa7394-5540-410d-a468-b5f204d66ff9', 'b', 1)`

I had to insert 2M rows across 400 chunks before I saw this bug appear. Note that I have seen this issue occur on multiple tables now, all of which have the same partitioning and retention policies, but different schemas. `AVG` is also affected, the issue is not limited to `SUM`.

Editing to add: this also happens when the value is an int, and the string columns are unnecessary

### PR DESCRIPTION
**Pull request by fabriziomello**
Previous PR #4307 mark `partialize_agg` and `finalize_agg` as parallel safe but this change is leading to incorrect results in some cases.

Those functions are supposed work in parallel but seems is not the case and it is not evident yet the root cause and how to properly use it in parallel queries so we decided to revert this change and provide correct results to users.

Fixes #4922

### CODE REVIEW

File: tsl/test/sql/partialize_finalize.sql [hunk 1]
```diff
@@ -296,3 +296,44 @@ select _timescaledb_internal.finalize_agg( 'aggregate_to_test_ffunc_extra(int, a
...
+
+INSERT INTO issue4922 (time, value)
+SELECT time, (random()*30) as value
+FROM generate_series(now() - interval '100 hours', now(), '1 sec') AS time;
+
+SET force_parallel_mode = 'on';
+SET parallel_setup_cost = 0;
+
+-- Compare the results (should return NO ROWS)
+(SELECT
```
Comment (akuzm) [inline tsl/test/sql/partialize_finalize.sql:317]: Slightly confused by this test -- which subselect is the broken one? Maybe we could generate stable pseudo-random data and just show the results of both subselects. For pseudo-random we can use something like this: https://github.com/timescale/timescaledb/blob/main/tsl/test/sql/dist_param.sql#L20-L33

**Review by akuzm — APPROVED** [review]
OK as a quick fix, but I wonder what's the root cause.

File: tsl/test/sql/partialize_finalize.sql (hunk 1 above)
Comment (akuzm) [reply tsl/test/sql/partialize_finalize.sql:317]: Also might be good to have an explain query so that we are absolutely sure it runs in parallel, because parallel execution is notoriously hard to achieve sometimes.

File: sql/partialize_finalize.sql [hunk 2]
```diff
@@ -8,24 +8,23 @@
 -- parallel-safe.
 
 CREATE OR REPLACE FUNCTION _timescaledb_internal.partialize_agg(arg ANYELEMENT)
-RETURNS BYTEA AS '@MODULE_PATHNAME@', 'ts_partialize_agg' LANGUAGE C STABLE PARALLEL SAFE;
+RETURNS BYTEA AS '@MODULE_PATHNAME@', 'ts_partialize_agg' LANGUAGE C VOLATILE;
```
Comment (akuzm) [inline sql/partialize_finalize.sql:11]: Even volatile? I'd think it should be immutable, it's a pure function.

File: sql/partialize_finalize.sql [hunk 3]
```diff
@@ -8,24 +8,23 @@
 -- parallel-safe.
```
Comment (akuzm) [inline sql/partialize_finalize.sql:8]: The comment above needs updating.

File: sql/partialize_finalize.sql (hunk 2 above)
Comment (erimatnor) [reply sql/partialize_finalize.sql:11]: Yeah, why not keep STABLE and just remove parallel safe?

Comment (erimatnor) [reply sql/partialize_finalize.sql:11]: Is it because some aggs can be volatile themselves?

Comment (akuzm) [reply sql/partialize_finalize.sql:11]: > Is it because some aggs can be volatile themselves?

Postgres check the volatility of the entire expression tree, so this shouldn't matter.

Comment (fabriziomello) [reply sql/partialize_finalize.sql:11]: I didn't thought too much about it because the idea here is to REVERT to the previous state.

File: tsl/test/sql/partialize_finalize.sql (hunk 1 above)
Comment (fabriziomello) [reply tsl/test/sql/partialize_finalize.sql:317]: You're correct will update the tests.

File: sql/partialize_finalize.sql (hunk 2 above)
Comment (erimatnor) [reply sql/partialize_finalize.sql:11]: Yeah, I also think that this function is essentially just a planner hint and not actually executed.

File: tsl/test/sql/partialize_finalize.sql (hunk 1 above)
Comment (fabriziomello) [reply tsl/test/sql/partialize_finalize.sql]: Tests updated
