### PR TITLE
Take advisory lock for job tuple

### LINKED ISSUE #4863: [Bug] Assetion (num_found == 0) hit in ts_bgw_job_find_with_lock
Happened in the tests: https://github.com/timescale/timescaledb/actions/runs/3289398597/jobs/5420879807

```
Core was generated by `postgres: TimescaleDB Background Worker Scheduler                             '.
Program terminated with signal SIGABRT, Aborted.
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
(gdb) (null)

(gdb) #0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
        set = {__val = {0, 0, 0, 0, 0, 94749247508224, 4611686018427387904, 
            0, 0, 139743648273642, 0, 94749247508270, 128, 0, 
            140736465821504, 139743642347040}}
        pid = <optimized out>
        tid = <optimized out>
        ret = <optimized out>
#1  0x00007f189a159859 in __GI_abort () at abort.c:79
        save_stage = 1
        act = {__sigaction_handler = {sa_handler = 0x7f189a2ecbf7, 
            sa_sigaction = 0x7f189a2ecbf7}, sa_mask = {__val = {1, 
              139743642705950, 3, 140736465821684, 12, 139743642705954, 2, 
              7147835159851565057, 7292003139051534136, 140736465821792, 
              7291948129093622672, 94749261942576, 8863777214396080128, 
              140736465821776, 9223372036854775808, 20}}, 
          sa_flags = -1022533536, sa_restorer = 0x562c87b71b90 <BackendList>}
        sigs = {__val = {32, 0 <repeats 15 times>}}
#2  0x0000562c8789c9bb in ExceptionalCondition (
    conditionName=<optimized out>, errorType=<optimized out>, 
    fileName=<optimized out>, lineNumber=<optimized out>) at assert.c:67
No locals.
#3  0x00007f1890201c9d in ts_bgw_job_find_with_lock (bgw_job_id=1008, 
    mctx=0x562c88271c80, tuple_lock_mode=2, lock_type=TXN_LOCK, block=true, 
    got_lock=0x7fffc30d668f)
    at /home/runner/work/timescaledb/timescaledb/src/bgw/job.c:609
        ti = 0x7fffc30d6400
        iterator = {ctx = {internal = {tinfo = {scanrel = 0x7f189034d2d0, 
                slot = 0x562c882720a8, ituple = 0x0, 
                ituple_desc = 0x7f18903511f0, lockresult = TM_Ok, lockfd = {
                  ctid = {ip_blkid = {bi_hi = 0, bi_lo = 0}, ip_posid = 0}, 
                  xmax = 0, cmax = 0, traversed = false}, count = 2, 
                mctx = 0x562c88271c80}, scan = {index_scan = 0x562c88271e38, 
                table_scan = 0x562c88271e38}, scan_mcxt = 0x562c88271c80, 
              registered_snapshot = true, started = true, ended = false}, 
            table = 54688, index = 54720, tablerel = 0x7f189034d2d0, 
            indexrel = 0x7f1890350ec0, scankey = 0x7fffc30d64e8, flags = 0, 
            nkeys = 1, norderbys = 0, limit = 0, want_itup = false, 
            lockmode = 5, result_mctx = 0x562c88271c80, tuplock = 0x0, 
            scandirection = ForwardScanDirection, snapshot = 0x562c88271da0, 
            data = 0x0, prescan = 0x0, postscan = 0x0, filter = 0x0, 
            tuple_found = 0x0}, tinfo = 0x7fffc30d6400, scankey = {{
              sk_flags = 0, sk_attno = 1, sk_strategy = 3, sk_subtype = 0, 
              sk_collation = 950, sk_func = {
                fn_addr = 0x562c877d5550 <int4eq>, fn_oid = 65, fn_nargs = 2, 
                fn_strict = true, fn_retset = false, fn_stats = 2 '\002', 
                fn_extra = 0x0, fn_mcxt = 0x562c88271c80, fn_expr = 0x0}, 
              sk_argument = 1008}, {sk_flags = 0, sk_attno = 0, 
              sk_strategy = 0, sk_subtype = 0, sk_collation = 0, sk_func = {
                fn_addr = 0x0, fn_oid = 0, fn_nargs = 0, fn_strict = false, 
                fn_retset = false, fn_stats = 0 '\000', fn_extra = 0x0, 
                fn_mcxt = 0x0, fn_expr = 0x0}, sk_argument = 0}, {
              sk_flags = 0, sk_attno = 0, sk_strategy = 0, sk_subtype = 0, 
              sk_collation = 0, sk_func = {fn_addr = 0x0, fn_oid = 0, 
                fn_nargs = 0, fn_strict = false, fn_retset = false, 
                fn_stats = 0 '\000', fn_extra = 0x0, fn_mcxt = 0x0, 
                fn_expr = 0x0}, sk_argument = 0}, {sk_flags = 0, 
              sk_attno = 0, sk_strategy = 0, sk_subtype = 0, 
              sk_collation = 0, sk_func = {fn_addr = 0x0, fn_oid = 0, 
                fn_nargs = 0, fn_strict = false, fn_retset = false, 
                fn_stats = 0 '\000', fn_extra = 0x0, fn_mcxt = 0x0, 
                fn_expr = 0x0}, sk_argument = 0}, {sk_flags = 0, 
              sk_attno = 0, sk_strategy = 0, sk_subtype = 0, 
              sk_collation = 0, sk_func = {fn_addr = 0x0, fn_oid = 0, 
                fn_nargs = 0, fn_strict = false, fn_retset = false, 
                fn_stats = 0 '\000', fn_extra = 0x0, fn_mcxt = 0x0, 
                fn_expr = 0x0}, sk_argument = 0}}}
        num_found = 1
        job = 0x562c882724f8
        tag = {locktag_field1 = 51816, locktag_field2 = 1008, 
          locktag_field3 = 0, locktag_field4 = 29749, locktag_type = 10 '\n', 
          locktag_lockmethodid = 2 '\002'}
#4  0x00007f1890201d68 in ts_bgw_job_get_share_lock (bgw_job_id=1008, 
    mctx=0x562c88271c80)
    at /home/runner/work/timescaledb/timescaledb/src/bgw/job.c:628
        got_lock = true
        job = 0x7fffc30d66d0
        __func__ = "ts_bgw_job_get_share_lock"
#5  0x00007f1890208e0a in scheduled_bgw_job_transition_state_to (
    sjob=0x562c881fee58, new_state=JOB_STATE_STARTED)
    at /home/runner/work/timescaledb/timescaledb/src/bgw/scheduler.c:280
        prev_state = JOB_STATE_SCHEDULED
        job_stat = 0x562c87853c32 <GetCurrentTimestamp+34>
        owner_uid = 32767
        __func__ = "scheduled_bgw_job_transition_state_to"
#6  0x00007f1890209785 in scheduled_ts_bgw_job_start (sjob=0x562c881fee58, 
    bgw_register=0x0)
    at /home/runner/work/timescaledb/timescaledb/src/bgw/scheduler.c:398
        pid = -1022531840
        status = 32767
        __func__ = "scheduled_ts_bgw_job_start"
#7  0x00007f189020a378 in start_scheduled_jobs (bgw_register=0x0)
    at /home/runner/work/timescaledb/timescaledb/src/bgw/scheduler.c:588
        sjob = 0x562c881fee58
        lc__state = {l = 0x562c881fe1b8, i = 0}
        ordered_scheduled_jobs = 0x562c881fe1b8
        lc = 0x562c881ff688
```

### PR DESCRIPTION
**Pull request by mkindahl**
Job ids are locked using an advisory lock rather than a row lock on the
jobs table, but this lock is not taken in the job API functions
(`alter_job`, `delete_job`, etc.), which appears to cause a race
condition resulting in addition of multiple rows with the same job id.

This commit adds an advisory `RowExclusiveLock` on the job id while
altering it to match the advisory locks taken while performing other
modifications.

Closes #4863

### CODE REVIEW

File: tsl/src/bgw_policy/job_api.c [hunk 1]
```diff
@@ -201,10 +201,20 @@ static BgwJob *
 find_job(int32 job_id, bool null_job_id, bool missing_ok)
 {
 	BgwJob *job;
+	bool got_lock;
+	LOCKTAG tag;
 
 	if (null_job_id && !missing_ok)
 		ereport(ERROR, (errcode(ERRCODE_INVALID_PARAMETER_VALUE), errmsg("job ID cannot be NULL")));
 
+	/* take advisory lock before relation lock */
```
Comment (jnidzwetzki) [inline tsl/src/bgw_policy/job_api.c:210]: Could you extend this comment a bit? Currently, the motivation for the lock is only stated in the commit message. 
Without knowing the commit message, the motivation for the second lock might be hard to understand. Maybe you could take a part of the commit message and paste it here.

File: tsl/src/bgw_policy/job_api.c [hunk 2]
```diff
@@ -201,10 +201,20 @@ static BgwJob *
...
+	if (!(got_lock = ts_lock_job_id(job_id,
+									RowShareLock,
+									/* session_lock */ false,
+									&tag,
+									/* block */ true)))
+		return NULL;
+
 	job = ts_bgw_job_find(job_id, CurrentMemoryContext, !missing_ok);
```
Comment (jnidzwetzki) [inline tsl/src/bgw_policy/job_api.c:218]: Is there a particular reason (except that the parameter `missing_ok` is currently not supported) why we don't use `ts_bgw_job_find_with_lock` here? If we would use this function, we would not have to take care of the advisory lock ourselves.

Comment (mkindahl) [reply tsl/src/bgw_policy/job_api.c:218]: It causes strange failures and I wanted to investigate as a follow-up PR. This is duplicate code, so I think that we should use the same function for both cases.

**Review by jnidzwetzki — APPROVED** [review]
I have one comment and one minor question. The rest looks good to me.

File: tsl/src/bgw_policy/job_api.c (hunk 1 above)
Comment (mkindahl) [reply tsl/src/bgw_policy/job_api.c:210]: Good point. Will do.

Comment (mkindahl) [reply tsl/src/bgw_policy/job_api.c]: Done

**Review by akuzm — APPROVED** [review]

File: tsl/src/bgw_policy/job_api.c [hunk 3]
```diff
@@ -201,10 +201,24 @@ static BgwJob *
...
+	 * rather than a row lock to prevent the job from being modified while
+	 * running. Since we use this function to find a job for either running
+	 * manually or for altering it, we need to grab that advisory lock here as
+	 * well. */
+	if (!(got_lock = ts_lock_job_id(job_id,
+									RowShareLock,
+									/* session_lock */ false,
+									&tag,
+									/* block */ true)))
+		return NULL;
```
Comment (akuzm) [inline tsl/src/bgw_policy/job_api.c:220]: By the way, when is this null, when the job is modified concurrently? Codecov says it's not covered, maybe there's an easy way to construct an isolation test for this...

Comment (mkindahl) [reply tsl/src/bgw_policy/job_api.c:220]: We're bad on handling these cases (there are several) so not sure how easy it is to create a test case for this, but will take a look if there is an easy way.

Comment (mkindahl) [reply tsl/src/bgw_policy/job_api.c:220]: This particular return can't fire, so we should probably just replace it with an assert. The return value can be `false` if it is a non-blocking wait and the lock is taken, not otherwise.

Comment (mkindahl) [reply tsl/src/bgw_policy/job_api.c]: Done.
