### PR TITLE
Fix crash on SELECT WHERE NOT with empty table

### LINKED ISSUE #1883: Postgres crashes on INSERT ... SELECT ... WHERE NOT EXISTS with empty table
**Relevant system information:**
 - OS: Ubuntu 18.04
 - PostgreSQL version (output of `postgres --version`): PostgreSQL 12.2 on x86_64-pc-linux-musl, compiled by gcc (Alpine 9.2.0) 9.2.0, 64-bit
 - TimescaleDB version (output of `\dx` in `psql`): 1.7.0
 - Installation method: Docker timescale/timescaledb:latest-pg12

**Describe the bug**
Postgres crashes on INSERT ... SELECT ... WHERE NOT EXISTS on the same hypertable if child tables are not initialized.

**To Reproduce**
```sql
CREATE TABLE readings (
	toe TIMESTAMPTZ NOT NULL,
	sensor_id INT NOT NULL,
	value INT NOT NULL
);
SELECT create_hypertable(
	'readings',
	'toe',
	chunk_time_interval => interval '1 day',
	if_not_exists => TRUE,
	migrate_data => TRUE
);
INSERT INTO readings 
SELECT '2020-05-09 10:34:35.296288+00', 1, 0 
WHERE NOT EXISTS (
	SELECT 1 
	FROM readings 
	WHERE sensor_id = 1 
		AND toe = '2020-05-09 10:34:35.296288+00'
);
```

**Expected behavior**
Insert happens.

**Actual behavior**
Postgres crashes.

### PR DESCRIPTION
**Pull request by pmwkaa**
Apparently modify table state is not created with an empty tables, which lead to NULL pointer evaluation.

Fixes #1883.

### CODE REVIEW

File: src/chunk_dispatch_state.c [hunk 1]
```diff
@@ -53,6 +53,8 @@ on_chunk_insert_state_changed(ChunkInsertState *cis, void *data)
 	ChunkDispatchState *state = data;
 	ModifyTableState *mtstate = state->mtstate;
 
+	if (mtstate == NULL)
```
Comment (svenklemm) [inline src/chunk_dispatch_state.c:56]: could you add a comment here that this may be NULL on pg12 under certain conditions

Comment (erimatnor) [reply src/chunk_dispatch_state.c:56]: Along the same lines, I would like to understand what is going on and why it is OK to just do nothing here before accepting this fix.

**Comment by erimatnor** [comment]
After some analysis, I found the issue. The planner[ injects a gating plan node above any node that has pseusdo-constant quals](https://github.com/postgres/postgres/blob/5060275aa8a1ead56e0a41308d7a43049a6cbe43/src/backend/optimizer/plan/createplan.c#L747
) (baserestrictinfo in the corresponding RelOptInfo). This didn't happen until PG12 introduced a new RTE_RESULT range table type, which is the child where we're injecting the ChunkDispatch node. Since our ChunkDispatch "inherits" the RelOptInfo from the child node, it will also inherit the restriction clauses. Thus the planner thinks it needs to inject another gating clause. 

To fix this, we need to check for such a gating node and handle the case. We could optionally prune the extra node, since there's already such a node below ChunkDispatch. This is some code that should fix the issue (doesn't do the pruning, but is easy to add if we want to):

```
static PlanState *
get_chunk_dispatch_state(ModifyTableState *mtstate, PlanState *substate)
{
	switch (nodeTag(substate))
	{
	case T_CustomScanState:
	{
		CustomScanState *csstate = castNode(CustomScanState, substate);

		if (strcmp(csstate->methods->CustomName, CHUNK_DISPATCH_STATE_NAME) == 0)
			return substate;
	}
	break;
	case T_ResultState:
		return get_chunk_dispatch_state(mtstate, castNode(ResultState, substate)->ps.lefttree);
		break;
	default:
		break;
	}

	return NULL;
}

/*
 * HypertableInsert (with corresponding executor node) is a plan node that
 * implements INSERTs for hypertables. It is mostly a wrapper around the
 * ModifyTable plan node that simply calls the wrapped ModifyTable plan without
 * doing much else, apart from some initial state setup.
 *
 * The wrapping is needed to setup state in the execution phase, and give access
 * to the ModifyTableState node to sub-plan states in the PlanState tree. For
 * instance, the ChunkDispatchState node needs to set the arbiter index list in
 * the ModifyTableState node whenever it inserts into a new chunk.
 */
static void
hypertable_insert_begin(CustomScanState *node, EState *estate, int eflags)
{
	HypertableInsertState *state = (HypertableInsertState *) node;
	PlanState *ps;

	ps = ExecInitNode(&state->mt->plan, estate, eflags);
	node->custom_ps = list_make1(ps);

	if (IsA(ps, ModifyTableState))
	{
		ModifyTableState *mtstate = (ModifyTableState *) ps;
		int i;

		/*
		 * Find all ChunkDispatchState subnodes and set their parent
		 * ModifyTableState node
		 */
		for (i = 0; i < mtstate->mt_nplans; i++)
		{
			ChunkDispatchState *cdstate = (ChunkDispatchState *) get_chunk_dispatch_state(mtstate, mtstate->mt_plans[i]);

			if (cdstate)
				ts_chunk_dispatch_state_set_parent(cdstate, mtstate);
		}
	}
}
```

File: src/hypertable_insert.c [hunk 2]
```diff
@@ -36,35 +59,35 @@ static void
...
+	{
+		ChunkDispatchState *cdstate =
+			(ChunkDispatchState *) get_chunk_dispatch_state(mtstate, mtstate->mt_plans[i]);
 
-					ts_chunk_dispatch_state_set_parent(cdstate, mtstate);
-				}
-			}
+		if (cdstate)
+		{
+			found_cdstate = true;
```
Comment (erimatnor) [inline src/hypertable_insert.c:84]: This boolean seems unnecessary since it is just for assertion and you can check the pointer directly by moving the cdstate declaration outside the loop. The boolean will probably give a warning of unused variable in case assertions are off.

File: src/hypertable_insert.c [hunk 3]
```diff
@@ -36,35 +59,35 @@ static void
...
-		 * Find all ChunkDispatchState subnodes and set their parent
-		 * ModifyTableState node
-		 */
-		for (i = 0; i < mtstate->mt_nplans; i++)
-		{
-			if (IsA(mtstate->mt_plans[i], CustomScanState))
-			{
-				CustomScanState *csstate = (CustomScanState *) mtstate->mt_plans[i];
+	Assert(IsA(ps, ModifyTableState));
+	mtstate = (ModifyTableState *) ps;
```
Comment (erimatnor) [inline src/hypertable_insert.c:71]: This does assertion and casting in one go:
```suggestion
	mtstate = castNode(ModifyTableState, ps);
```

File: src/hypertable_insert.c (hunk 2 above)
Comment (WireBaron) [reply src/hypertable_insert.c:84]: The logic of that would look wrong as it would seem you would only be asserting if the last plan found a cdstate.  If you go this route, I'd recommend dropping the for loop and copying this assertion from the set_parent code:
```
	/* Inserts on hypertables should always have one subplan */
	Assert(mtstate->mt_nplans == 1);
```

Comment (erimatnor) [reply src/hypertable_insert.c:84]: Good point @WireBaron. Then I'd keep the bool but mark it `PG_USED_FOR_ASSERTS_ONLY`

File: src/hypertable_insert.c [hunk 4]
```diff
@@ -21,6 +21,29 @@
...
+		{
+			CustomScanState *csstate = castNode(CustomScanState, substate);
+
+			if (strcmp(csstate->methods->CustomName, CHUNK_DISPATCH_STATE_NAME) == 0)
+				return substate;
+
+			break;
+		}
+		case T_ResultState:
+			return get_chunk_dispatch_state(mtstate, castNode(ResultState, substate)->ps.lefttree);
```
Comment (mkindahl) [inline src/hypertable_insert.c:39]: Now we only recurse into the left tree, not the right tree. Can a custom scan state be in the right tree?

Comment (erimatnor) [reply src/hypertable_insert.c:39]: Right tree is always NULL in Result nodes: https://github.com/postgres/postgres/blob/a9cf48a4cf0c878684a2f52a3a88e29399b2065e/src/backend/optimizer/plan/createplan.c#L6745

I think it is common practice to use only the left branch in nodes that support only one child.

Comment (pmwkaa) [reply src/hypertable_insert.c:39]: Looks like the gating plan uses only `lefttree` here according to the `create_gating_plan()` and `make_result()` functions

Comment (erimatnor) [reply src/hypertable_insert.c:39]: The corresponding place where the ResultState node is created: https://github.com/postgres/postgres/blob/a9cf48a4cf0c878684a2f52a3a88e29399b2065e/src/backend/executor/nodeResult.c#L210

(outerPlanState == left tree)
