### PR TITLE
Fixes command tag return for INSERTS on hypertables.

### LINKED ISSUE #28: Insert always reports 0 rows inserted
Reproduce:
```sql
CREATE TABLE tt(c timestamp with time zone);
SELECT create_hypertable('tt', 'c');
INSERT INTO tt VALUES('2016-11-15 17:30:00+05:30');
INSERT 0 0
```

Result should be
`INSERT 0 1`

### PR DESCRIPTION
**Pull request by cevian**
Previously, an INSERT on a hypertable would always return
INSERT 0 0 as the command tag. This makes it return the proper
number of items inserted for the second number. Fixes #28.

### CODE REVIEW

File: src/insert.c [hunk 1]
```diff
@@ -33,6 +33,8 @@
 #include "insert_chunk_state.h"
 #include "insert_statement_state.h"
 
+void add_number_tuples_processed(uint64);
```
Comment (olofr) [inline src/insert.c]: I prefer a .h file even if it is small. Not sure where we landed on that though.

Comment (cevian) [inline src/insert.c]: I agree with you. Just got lazy. Now fixed.

File: src/init.c [hunk 2]
```diff
@@ -48,6 +51,7 @@ _PG_fini(void)
 {
 	_process_utility_fini();
 	_planner_fini();
```
Comment (olofr) [inline src/init.c]: BTW, is there a reason we don't call *_fini() in strict reverse order that we call *_init() ?

Comment (cevian) [inline src/init.c]: Nope, and that would probably avoid some class of bugs. Will change in this PR and document.

**Comment by cevian** [comment]
@erimatnor would be nice to get another set of eyes since a new hook

File: src/init.c (hunk 2 above)
Comment (cevian) [inline src/init.c]: Implemented

File: src/executor.c [hunk 3]
```diff
@@ -0,0 +1,39 @@
+#include<postgres.h>
+#include<executor/executor.h>
```
Comment (erimatnor) [inline src/executor.c]: Missing whitespace

File: src/insert.c [hunk 4]
```diff
@@ -140,6 +141,10 @@ insert_main_table_trigger(PG_FUNCTION_ARGS)
 	}
 	PG_END_TRY();
 
+	/* add 1 to the number of processed tuples in the commandTag. Without this tuples that return 
+	 * NULL in before triggers are not counted. */
+	add_number_tuples_processed(1);
```
Comment (erimatnor) [inline src/insert.c]: I'd prefer that this "public" function was prefixed with the module where it is implemented, e.g., `executor_set_number_of_processed_tuples()`. Then one knows where to look for this  function and it will ensure no name collisions across modules. Namespace/prefixing is also in our style guide.

**Comment by cevian** [comment]
Addressed all of Erik's nits.
