### PR TITLE
Check insert privileges to create chunk

### LINKED ISSUE #2393: Multinode: Table ownership required to INSERT (and presumably other DML statements)
**Relevant system information:**
 - OS: Ubuntu 20.04
 - PostgreSQL version: 12.3 (Ubuntu 12.3-1.pgdg20.04+1)
 - TimescaleDB version: 2.0.0-beta5
 - Installation method: apt install

**Describe the bug**
This is multi-node TimescaleDB. The current user has the appropriate PostgreSQL level permissions for DML-type operations, however an `INSERT` fails if that statement requires the creation of a new chunk. Consider:
```
postgres=# \c metadb capacity
Password for user capacity: 
You are now connected to database "metadb" as user "capacity".
metadb=> \du capacity
               List of roles
 Role name | Attributes |     Member of     
-----------+------------+-------------------
 capacity  |            | {capacity_writer}

metadb=> \z pool
                                       Access privileges
  Schema  | Name | Type  |           Access privileges           | Column privileges | Policies 
----------+------+-------+---------------------------------------+-------------------+----------
 capacity | pool | table | capacity_admin=arwdDxt/capacity_admin+|                   | 
          |      |       | capacity_writer=arwdD/capacity_admin +|                   | 
          |      |       | capacity_reader=r/capacity_admin      |                   | 
(1 row)

metadb=> insert into pool (timestamp, pop, name) values (now(), 'hi', 'mom');
ERROR:  [dn03]: must be owner of hypertable "pool"
```
The `capacity` user is a member of `capacity_writer`, but the `pool` table is owned by `capacity_admin`. The `INSERT` fails on the data node (`dn03` in this case), and the logs there show
```
2020-09-11 01:22:39.935 UTC [609969] capacity@metadb ERROR:  must be owner of hypertable "pool"
2020-09-11 01:22:39.935 UTC [609969] capacity@metadb STATEMENT:  SELECT * FROM _timescaledb_internal.create_chunk($1, $2, $3, $4)
```
In discussing this on Slack, @erimatnor stated
> normally we would switch into a privileged role (table owner) to create the chunk. This happens on single node, but it seems we switch back to the role executing the statement just before we call this on the remote end (data node). So, it does seem there is something we need to do to fix this

**To Reproduce**
See above.

**Expected behavior**
`INSERT` should succeed if the user has the appropriate Pg privileges.

**Actual behavior**
`INSERT` failed, See above.

### PR DESCRIPTION
**Pull request by mkindahl**
To create a chunk in a hypertable, it is currently necessary to be the
owner of the hypertable of the chunk. If a user has insert privileges
only, it will fail with an error message, which causes problems when
inserting data into distributed hypertables since the user cannot
create new chunks.

This commit changes this and only requires that the user has insert
privileges on the hypertable of the chunk for allowing creation of a
new chunk.

Closes #2393

### CODE REVIEW

**Comment by mkindahl** [comment]
This cannot be reproduced in the tests since it requires construction of separate data nodes. It was reproduced manually with the following results:

Before commit:
```
postgres=# SET ROLE somebody;
SET
postgres=> INSERT INTO conditions
postgres-> SELECT time, 1+(random()*30)::int, random()*80
postgres-> FROM generate_series('2019-01-01 00:00:00'::timestamptz, '2019-02-01 00:00:00', '1 min') AS time;
ERROR:  [data_node_1]: must be owner of hypertable "conditions"
```

After commit:
```
postgres=# SET ROLE somebody;
SET
postgres=> INSERT INTO conditions
SELECT time, (random()*30)::int+1, random()*80
FROM generate_series('2019-01-01 00:00:00'::timestamptz, '2019-02-01 00:00:00', '1 min') AS time;
INSERT 0 44641
```

File: tsl/src/chunk_api.c [hunk 1]
```diff
@@ -315,10 +315,17 @@ chunk_create(PG_FUNCTION_ARGS)
...
 
 	Assert(NULL != ht);
 
-	ts_hypertable_permissions_check(hypertable_relid, GetUserId());
+	acl_result = pg_class_aclcheck(hypertable_relid, GetUserId(), ACL_INSERT);
+	if (acl_result != ACLCHECK_OK)
+		ereport(ERROR,
+				(errcode(ERRCODE_INSUFFICIENT_PRIVILEGE),
+				 errmsg("permission denied for table \"%s\"", get_rel_name(hypertable_relid)),
+				 errdetail("Insert privileges required on \"%s\"to create chunks.",
```
Comment (erimatnor) [inline tsl/src/chunk_api.c]:
```suggestion
				 errdetail("Insert privileges required on \"%s\" to create chunks.",
```

File: tsl/test/expected/chunk_api-12.out [hunk 2]
```diff
@@ -80,7 +80,8 @@ CONTEXT:  JSON data, line 1:  {"time: [1515024000000000] "device...
 -- Valid chunk, but no permissions
 SET ROLE :ROLE_DEFAULT_PERM_USER_2;
 SELECT * FROM _timescaledb_internal.create_chunk('chunkapi',' {"time": [1515024000000000, 1519024000000000], "device": [-9223372036854775808, 1073741823]}', 'ChunkSchema', 'My_chunk_Table_name');
-ERROR:  must be owner of hypertable "chunkapi"
+ERROR:  permission denied for table "chunkapi"
```
Comment (erimatnor) [inline tsl/test/expected/chunk_api-12.out:83]: I would expect a test where INSERT is granted to `ROLE_DEFAULT_PERM_USER_2` after this error and then try again with success.

**Review by erimatnor — COMMENTED** [review]
> This cannot be reproduced in the tests since it requires construction of separate data nodes. 

AFAIK, it should be possible to trigger this issue if you are a user, which is not the owner of the hypertable, and then insert a data point that creates a chunk on a data node. This shouldn't require separate database instances to reproduce.

It should also be possible to test the function and permissions in a limited way by simply calling `_timescaledb_internal.create_chunk()` directly in a test.

File: tsl/test/expected/chunk_api-12.out (hunk 2 above)
Comment (mkindahl) [reply tsl/test/expected/chunk_api-12.out:83]: Fixed.

**Comment by mkindahl** [comment]
> > This cannot be reproduced in the tests since it requires construction of separate data nodes.
> 
> AFAIK, it should be possible to trigger this issue if you are a user, which is not the owner of the hypertable, and then insert a data point that creates a chunk on a data node. This shouldn't require separate database instances to reproduce.
> 
> It should also be possible to test the function and permissions in a limited way by simply calling `_timescaledb_internal.create_chunk()` directly in a test.

Managed to create one, but did it as a new test.

File: tsl/test/expected/chunk_api-11.out [hunk 3]
```diff
@@ -80,15 +80,26 @@ CONTEXT:  JSON data, line 1:  {"time: [1515024000000000] "device...
...
+(1 row)
+
+SET ROLE :ROLE_DEFAULT_PERM_USER;
 \set VERBOSITY terse
 -- Create a chunk that does not collide and with custom schema and name
 SELECT * FROM _timescaledb_internal.create_chunk('chunkapi',' {"time": [1515024000000000, 1519024000000000], "device": [-9223372036854775808, 1073741823]}', 'ChunkSchema', 'My_chunk_Table_name');
  chunk_id | hypertable_id | schema_name |     table_name      | relkind |                                            slices                                            | created 
 ----------+---------------+-------------+---------------------+---------+----------------------------------------------------------------------------------------------+---------
-        2 |             1 | ChunkSchema | My_chunk_Table_name | r       | {"time": [1515024000000000, 1519024000000000], "device": [-9223372036854775808, 1073741823]} | t
+        2 |             1 | ChunkSchema | My_chunk_Table_name | r       | {"time": [1515024000000000, 1519024000000000], "device": [-9223372036854775808, 1073741823]} | f
```
Comment (k-rus) [inline tsl/test/expected/chunk_api-11.out:102]: It doesn't look right that the result of the test has changed. I guess the reason for the change is that `create_chunk` is called above. Something needs to be fixed here.

**Review by k-rus — CHANGES_REQUESTED** [review]
An existing test was modified in a way that it doesn't make sense and confusing now.

File: tsl/test/expected/chunk_api-11.out (hunk 3 above)
Comment (mkindahl) [reply tsl/test/expected/chunk_api-11.out:102]: This was a request from @erimatnor. The original test just checked that an error was generated, but he requested a check that adding permissions should make the error go away, hence the additional row.

Comment (k-rus) [reply tsl/test/expected/chunk_api-11.out:102]: Then the comment in front of this select needs to be corrected. It doesn't make sense now, since no chunk is created.

Comment (mkindahl) [reply tsl/test/expected/chunk_api-11.out]: Since this addition inserts a line that is used later, I just inserted the same line but as a different user. This makes the diff look the same later, and only changes the user that inserts the row.

**Comment by mkindahl** [comment]
> Please use an existing test suite like dist_hypertable

Merged it with `dist_grants`.

File: tsl/test/expected/chunk_api-12.out [hunk 4]
```diff
@@ -80,17 +80,23 @@ CONTEXT:  JSON data, line 1:  {"time: [1515024000000000] "device...
...
 SELECT * FROM _timescaledb_internal.create_chunk('chunkapi',' {"time": [1515024000000000, 1519024000000000], "device": [-9223372036854775808, 1073741823]}', 'ChunkSchema', 'My_chunk_Table_name');
-ERROR:  must be owner of hypertable "chunkapi"
-SET ROLE :ROLE_DEFAULT_PERM_USER;
+ERROR:  permission denied for table "chunkapi"
+DETAIL:  Insert privileges required on "chunkapi" to create chunks.
 \set ON_ERROR_STOP 1
-\set VERBOSITY terse
--- Create a chunk that does not collide and with custom schema and name
+-- Try that granting insert on table allow create_chunk to be
+-- called. This will also create a chunk that does not collied and has
```
Comment (svenklemm) [inline tsl/test/expected/chunk_api-12.out:87]: collied => collide

File: tsl/test/expected/chunk_api-11.out [hunk 5]
```diff
@@ -80,17 +80,23 @@ CONTEXT:  JSON data, line 1:  {"time: [1515024000000000] "device...
...
+GRANT INSERT ON chunkapi TO :ROLE_DEFAULT_PERM_USER_2;
+SET ROLE :ROLE_DEFAULT_PERM_USER_2;
 SELECT * FROM _timescaledb_internal.create_chunk('chunkapi',' {"time": [1515024000000000, 1519024000000000], "device": [-9223372036854775808, 1073741823]}', 'ChunkSchema', 'My_chunk_Table_name');
  chunk_id | hypertable_id | schema_name |     table_name      | relkind |                                            slices                                            | created 
 ----------+---------------+-------------+---------------------+---------+----------------------------------------------------------------------------------------------+---------
         2 |             1 | ChunkSchema | My_chunk_Table_name | r       | {"time": [1515024000000000, 1519024000000000], "device": [-9223372036854775808, 1073741823]} | t
 (1 row)
 
+SET ROLE :ROLE_DEFAULT_PERM_USER;
+\set VERBOSITY terse
```
Comment (svenklemm) [inline tsl/test/expected/chunk_api-11.out:99]: why do you have to change VERBOSITY here?

File: tsl/test/expected/chunk_api-11.out [hunk 6]
```diff
@@ -80,17 +80,23 @@ CONTEXT:  JSON data, line 1:  {"time: [1515024000000000] "device...
...
 SELECT * FROM _timescaledb_internal.create_chunk('chunkapi',' {"time": [1515024000000000, 1519024000000000], "device": [-9223372036854775808, 1073741823]}', 'ChunkSchema', 'My_chunk_Table_name');
-ERROR:  must be owner of hypertable "chunkapi"
-SET ROLE :ROLE_DEFAULT_PERM_USER;
+ERROR:  permission denied for table "chunkapi"
+DETAIL:  Insert privileges required on "chunkapi" to create chunks.
 \set ON_ERROR_STOP 1
-\set VERBOSITY terse
--- Create a chunk that does not collide and with custom schema and name
+-- Try that granting insert on table allow create_chunk to be
+-- called. This will also create a chunk that does not collied and has
```
Comment (WireBaron) [inline tsl/test/expected/chunk_api-11.out:87]:
```suggestion
-- Try that granting insert on table allows create_chunk to be
-- called. This will also create a chunk that does not collide and has
```

**Review by WireBaron — COMMENTED** [review]
Looks good overall, but I'm curious who the owner of the newly created chunk is?  It seems there might be issue if it's the inserting user.

File: tsl/test/expected/chunk_api-11.out (hunk 5 above)
Comment (mkindahl) [reply tsl/test/expected/chunk_api-11.out:99]: It was in the original code so I just kept it. It shows up as new because I have moved the `SET ROLE` around. It is set to `default` before this set of commands to show `DETAIL` of the error message, but that level of verbosity is not needed later, so it is set back to `terse`.

File: tsl/test/expected/chunk_api-12.out (hunk 4 above)
Comment (mkindahl) [reply tsl/test/expected/chunk_api-12.out:87]: Fixed.

**Comment by mkindahl** [comment]
> Looks good overall, but I'm curious who the owner of the newly created chunk is? It seems there might be issue if it's the inserting user.

This calls `ts_create_chunk_table` which says:

>   Create a chunk's table.
> 
> A chunk inherits from the main hypertable and will have the same owner. Since
> chunks can be created either in the TimescaleDB internal schema or in a
> user-specified schema, some care has to be taken to use the right
> permissions, depending on the case:

**Review by svenklemm — APPROVED** [review]

**Review by WireBaron — APPROVED** [review]

**Review by erimatnor — APPROVED** [review]
