### PR TITLE
Fix crash in 1-step integer policy creation

### LINKED ISSUE #5907: Server crashes on adding policies for continuous aggregate when retention policy for underlying hypertable exists
### What type of bug is this?

Crash

### What subsystems and features are affected?

Continuous aggregate

### What happened?

When trying to add policies for a continuous aggregate that is based on a hypertable partitioned by an int field and having a retention policy, I get a server crash.

It looks like validate_and_create_policies() calls function ts_jsonb_get_int64_field() incorrectly (it passes "false" to the function argument declared as "bool *field_found").
All the other callers of ts_jsonb_get_int64_field() do it right.

### TimescaleDB version affected

2.12.0-dev

### PostgreSQL version used

15.3

### What operating system did you use?

Ubuntu 22.04 x86_64

### What installation method did you use?

Source

### What platform did you run on?

On prem/Self-hosted

### Relevant log output and stack trace

```bash
Core was generated by `postgres: law regression [local] SELECT                                       '.
Program terminated with signal SIGSEGV, Segmentation fault.

warning: Section `.reg-xstate/981804' in core file too small.
#0  0x00007f283274eb81 in ts_jsonb_get_int64_field (json=0x55a47929bc30, key=0x7f28326b57e9 "drop_after", 
    field_found=0x0) at .../timescaledb/src/jsonb_utils.c:224
224             *field_found = true;
(gdb) bt
#0  0x00007f283274eb81 in ts_jsonb_get_int64_field (json=0x55a47929bc30, key=0x7f28326b57e9 "drop_after", 
    field_found=0x0) at .../timescaledb/src/jsonb_utils.c:224
#1  0x00007f2832608cfe in validate_and_create_policies (all_policies=..., if_exists=false)
    at .../timescaledb/tsl/src/bgw_policy/policies_v2.c:131
#2  0x00007f283260940e in policies_add (fcinfo=0x55a4790ab3f8)
    at .../timescaledb/tsl/src/bgw_policy/policies_v2.c:297
#3  0x00007f2832731b71 in ts_policies_add (fcinfo=0x55a4790ab3f8)
    at .../timescaledb/src/cross_module_fn.c:58
#4  0x000055a47724a380 in ExecInterpExpr (state=0x55a4790ab310, econtext=0x55a4790ab010, 
    isnull=0x7ffd03d7fd4f) at execExprInterp.c:727
#5  0x000055a47724c714 in ExecInterpExprStillValid (state=0x55a4790ab310, econtext=0x55a4790ab010, 
    isNull=0x7ffd03d7fd4f) at execExprInterp.c:1826
#6  0x000055a4772aa715 in ExecEvalExprSwitchContext (state=0x55a4790ab310, econtext=0x55a4790ab010, 
    isNull=0x7ffd03d7fd4f) at ../../../src/include/executor/executor.h:344
#7  0x000055a4772aa78d in ExecProject (projInfo=0x55a4790ab308)
    at ../../../src/include/executor/executor.h:378
#8  0x000055a4772aa9d7 in ExecResult (pstate=0x55a4790aaef8) at nodeResult.c:136
#9  0x000055a4772634f6 in ExecProcNodeFirst (node=0x55a4790aaef8) at execProcnode.c:464
#10 0x000055a4772565f2 in ExecProcNode (node=0x55a4790aaef8) at ../../../src/include/executor/executor.h:262
#11 0x000055a4772594f9 in ExecutePlan (estate=0x55a4790aacc0, planstate=0x55a4790aaef8, 
    use_parallel_mode=false, operation=CMD_SELECT, sendTuples=true, numberTuples=0, 
    direction=ForwardScanDirection, dest=0x55a478fff138, execute_once=true) at execMain.c:1636
#12 0x000055a477256d29 in standard_ExecutorRun (queryDesc=0x55a478f51fe0, direction=ForwardScanDirection, 
    count=0, execute_once=true) at execMain.c:363
#13 0x000055a477256b14 in ExecutorRun (queryDesc=0x55a478f51fe0, direction=ForwardScanDirection, count=0, 
    execute_once=true) at execMain.c:307
#14 0x000055a4774d423c in PortalRunSelect (portal=0x55a478eff5e0, forward=true, count=0, 
    dest=0x55a478fff138) at pquery.c:924
#15 0x000055a4774d3e5a in PortalRun (portal=0x55a478eff5e0, count=9223372036854775807, isTopLevel=true, 
    run_once=true, dest=0x55a478fff138, altdest=0x55a478fff138, qc=0x7ffd03d80150) at pquery.c:768
#16 0x000055a4774cccd4 in exec_simple_query (
    query_string=0x55a478e8c5a0 "SELECT timescaledb_experimental.add_policies('cagg');") at postgres.c:1250
#17 0x000055a4774d1c05 in PostgresMain (dbname=0x55a478ebb458 "regression", username=0x55a478ebb438 "law")
    at postgres.c:4598
#18 0x000055a4773f6f8d in BackendRun (port=0x55a478eb2b70) at postmaster.c:4511
#19 0x000055a4773f6814 in BackendStartup (port=0x55a478eb2b70) at postmaster.c:4239
#20 0x000055a4773f26e7 in ServerLoop () at postmaster.c:1806
#21 0x000055a4773f1e44 in PostmasterMain (argc=3, argv=0x55a478df4a70) at postmaster.c:1478
#22 0x000055a4772e5ad5 in main (argc=3, argv=0x55a478df4a70) at main.c:202
```

### How can we reproduce the bug?

```bash
CREATE EXTENSION timescaledb;

CREATE TABLE t(a integer NOT NULL, b integer);
SELECT create_hypertable('t', 'a', chunk_time_interval=> 10);

CREATE OR REPLACE FUNCTION unix_now() returns int LANGUAGE SQL IMMUTABLE as $$ SELECT extract(epoch from now())::INT $$;
SELECT set_integer_now_func('t', 'unix_now');

SELECT add_retention_policy('t', 20);

CREATE MATERIALIZED VIEW cagg(a, sumb) WITH (timescaledb.continuous)
AS SELECT time_bucket(1, a), sum(b)
   FROM t GROUP BY time_bucket(1, a);

SELECT timescaledb_experimental.add_policies('cagg');
```

### PR DESCRIPTION
**Pull request by konskov**
Previously when a retention policy existed on the underlying hypertable,
we would get a segmentation fault when trying to add a Cagg refresh
policy, due to passing a bool instead of pointer to bool argument to
function `ts_jsonb_get_int64_field` in a particular code path.
Fixed by passing the expected pointer type.

Fixes #5907

### CODE REVIEW

File: tsl/src/bgw_policy/policies_v2.c [hunk 1]
```diff
@@ -128,9 +128,15 @@ validate_and_create_policies(policies_info all_policies, bool if_exists)
...
+			bool found_drop_after = false;
 			drop_after_HT = ts_jsonb_get_int64_field(orig_ht_reten_job->fd.config,
 													 POL_RETENTION_CONF_KEY_DROP_AFTER,
-													 false);
+													 &found_drop_after);
+			if (!found_drop_after)
+				ereport(ERROR,
+						(errcode(ERRCODE_INTERNAL_ERROR),
+						 errmsg("could not find %s in config for job",
+								POL_RETENTION_CONF_KEY_DROP_AFTER)));
```
Comment (RafiaSabih) [inline tsl/src/bgw_policy/policies_v2.c:139]: Please add some comments explaining why this is required.

File: tsl/test/sql/cagg_policy.sql [hunk 2]
```diff
@@ -630,3 +630,18 @@ SELECT * FROM deals_best_daily ORDER BY bucket LIMIT 2;
 -- expect to get an up-to-date notice
 CALL refresh_continuous_aggregate('deals_best_weekly', '2022-04-24', '2022-05-05');
 SELECT * FROM deals_best_weekly;
+
+-- github issue 5907
```
Comment (RafiaSabih) [inline tsl/test/sql/cagg_policy.sql:634]: instead of mentioning issue number, it will be better if we mention what is being tested here exactly.

**Review by RafiaSabih — CHANGES_REQUESTED** [review]

File: tsl/test/sql/cagg_policy.sql (hunk 2 above)
Comment (konskov) [reply tsl/test/sql/cagg_policy.sql]: added a line about what this test is meant to check

**Review by RafiaSabih — APPROVED** [review]
