### PR TITLE
Fix error printout on correct security label

### LINKED ISSUE #3760: postgresql upgrade results in error `TimescaleDB label is for internal use only`
**Relevant system information:**
 - OS: Debian 10
 - PostgreSQL version (output of `postgres --version`): postgres (PostgreSQL) 14.0 (Debian 14.0-1.pgdg100+1)
 - TimescaleDB version (output of `\dx` in `psql`): 2.5.0
 - Installation method: apt

**Describe the bug**
When attempting to upgrade from PostgreSQL 13 to 14, and using `pg_upgrade`, the process generates an error:

From `pg_upgrade_dump_235085.log`:
```
command: "/usr/lib/postgresql/14/bin/pg_restore" --host /tmp --port 50432 --username postgres --create --exit-on-error --verbose --dbname template1 "pg_upgrade_dump_235085.custom" >> "pg_upgrade_dump_235085.log" 2>&1
pg_restore: connecting to database for restore
pg_restore: creating DATABASE "edgestats"
pg_restore: connecting to new database "edgestats"
pg_restore: creating SECURITY LABEL "DATABASE "edgestats""
pg_restore: while PROCESSING TOC:
pg_restore: from TOC entry 110846; 0 0 SECURITY LABEL DATABASE "edgestats" edgestats
pg_restore: error: could not execute query: ERROR:  TimescaleDB label is for internal use only
Command was: SECURITY LABEL FOR "timescaledb" ON DATABASE "edgestats" IS 'dist_uuid:ef362ddd-2a35-4d1e-84de-ed8d2b27f88c';
```

**To Reproduce**
1. Start from a postgres 13 installation
2. Run `pg_upgrade`

**Expected behavior**
Database to be upgraded

**Actual behavior**
```
pg_restore: error: could not execute query: ERROR:  TimescaleDB label is for internal use only
```

### PR DESCRIPTION
**Pull request by mkindahl**
For all security labels from provider `timescaledb` an error was
printed, which make `pg_restore` fail because the security labels are
printed to the dump.

Instead, we only print an error if the security label is not of the
correct format.

Fixes #3760

### CODE REVIEW

**Comment by afiskon** [comment]
Looks OK but it would be nice to add a few more test cases to improve the code coverage.

**Review by afiskon — APPROVED** [review]

File: src/loader/loader.c [hunk 1]
```diff
@@ -470,6 +470,44 @@ post_analyze_hook(ParseState *pstate, Query *query, JumbleState *jstate)
...
+	int hyphens = 0;
+	int lengths[] = { 8, 4, 4, 4, 12 };
+
+	if (strlen(str) != 36)
+		return false;
+	for (; *str; ++str)
+	{
+		if (!isxdigit(*str) && *str != '-')
+			return false;
+		if (hyphens > sizeof(lengths) / sizeof(*lengths) ||
```
Comment (mfundul) [inline src/loader/loader.c:493]:
```suggestion
		if (hyphens >= sizeof(lengths) / sizeof(*lengths) ||
```

Comment (mfundul) [reply src/loader/loader.c:493]: You should add a test case with a lot of hyphens, maybe more than 10.

File: src/loader/loader.c [hunk 2]
```diff
@@ -470,6 +470,44 @@ post_analyze_hook(ParseState *pstate, Query *query, JumbleState *jstate)
...
 
+/*
+ * Simplified check if a string is an UUID.
+ *
+ * This assumes that the UUID is a string consisting of dash-separated
+ * hexadecimal numbers and the string of of exact length 36 characters,
+ * containing 4 dashes, and with groups of digits of the size 8-4-4-4-12.
+ */
+static bool
+is_uuid(const char *str)
```
Comment (pmwkaa) [inline src/loader/loader.c:481]: Maybe it makes sense to reuse PostgreSQL types/functions for such validation

**Review by pmwkaa — APPROVED** [review]

File: src/loader/loader.c (hunk 1 above)
Comment (mfundul) [reply src/loader/loader.c:493]: I guess more than 5 doesn't make sense with this code, but the 5th one would do stack overflow.

Comment (mkindahl) [reply src/loader/loader.c:493]: For 32-bit machines: `sizeof(lengths) / sizeof(*lengths)` = `20 / 4` = `5`, but `lengths[5]` would be out of bounds since there are only five elements in the array.

> You should add a test case with a lot of hyphens, maybe more than 10.

I would argue that this case cannot be triggered since it would fail earlier because of mismatching group sizes. However, I added two cases with more and fewer hyphens.

File: src/loader/loader.c [hunk 3]
```diff
@@ -505,8 +543,21 @@ loader_process_utility_hook(PlannedStmt *pstmt, const char *query_string,
...
 			if (stmt->provider && strcmp(stmt->provider, SECLABEL_DIST_PROVIDER) == 0)
-				ereport(ERROR, (errmsg("TimescaleDB label is for internal use only")));
+			{
+				const char *uuid = strchr(stmt->label, SECLABEL_DIST_TAG_SEPARATOR);
+				if (!uuid || strncmp(stmt->label, SECLABEL_DIST_TAG, uuid - stmt->label) != 0 ||
+					!is_uuid(&uuid[1]))
+					ereport(ERROR,
+							(errmsg("TimescaleDB label is for internal use only"),
+							 errdetail("Security label is \"%s\".", stmt->label),
+							 errhint("Security label has to be of format \"dist_uuid:<UUID>\".")));
```
Comment (erimatnor) [inline src/loader/loader.c:559]: I don't think this hint is appropriate since dist_uuid is not something a user should set. If this error happens, then either the dist_uuid is corrupted or the code mistook another UUID for the dist_uuid. In neither case should the user try to change the format to fix this issue or add this label him/herself.

I would probably just get rid of the hint.

File: src/loader/loader.c (hunk 1 above)
Comment (erimatnor) [reply src/loader/loader.c:493]: PostgreSQL has a `lengthof` macro to get the size in slots of an array. It's probably cleaner to use that.

File: src/loader/loader.c (hunk 3 above)
Comment (mkindahl) [reply src/loader/loader.c:559]: Understanding why something is a problem and tracking down the issue is just as important as being able to fix it. This hint is intended for users to understand what is wrong, and not so much for being able to repair it, so I think there is value in having this hint for debugging purposes.

File: src/loader/loader.c (hunk 2 above)
Comment (erimatnor) [reply src/loader/loader.c:481]: I was thinking the same thing. Why not just call `uuid_in` on this string? If necessary, capture and rewrite the error.

Comment (mkindahl) [reply src/loader/loader.c:481]: The function is `uuid_in`, which generate an error if it fails parsing, and capturing the error and replacing it with a different one was more complicated than writing this function. If you feel strongly about it, I can replace it.

File: src/loader/loader.c (hunk 1 above)
Comment (mkindahl) [reply src/loader/loader.c]: > I guess more than 5 doesn't make sense with this code, but the 5th one would do stack overflow.
Fixed

**Comment by mkindahl** [comment]
> Looks OK but it would be nice to add a few more test cases to improve the code coverage.

Added test cases to cover the cases highlighted by coverity.

File: src/loader/loader.c (hunk 2 above)
Comment (mkindahl) [reply src/loader/loader.c]: Switched to use `uuid_in`, as suggested.

**Review by mfundul — APPROVED** [review]

File: src/loader/loader.c [hunk 4]
```diff
@@ -470,6 +470,41 @@ post_analyze_hook(ParseState *pstate, Query *query, JumbleState *jstate)
...
+static void
+check_uuid(const char *label)
+{
+	const MemoryContext oldcontext = CurrentMemoryContext;
+	const char *uuid = strchr(label, SECLABEL_DIST_TAG_SEPARATOR);
+	if (!uuid || strncmp(label, SECLABEL_DIST_TAG, uuid - label) != 0)
+		ereport(ERROR,
+				(errmsg("TimescaleDB label is for internal use only"),
+				 errdetail("Security label is \"%s\".", label),
+				 errhint("Security label has to be of format \"dist_uuid:<UUID>\".")));
```
Comment (erimatnor) [inline src/loader/loader.c:485]: My previous comment about dropping the hint still applies.

**Review by erimatnor — APPROVED** [review]

File: src/loader/loader.c (hunk 4 above)
Comment (mkindahl) [reply src/loader/loader.c:485]: I prefer to have this present for debugging purposes and trust users rather than to hide useful information that could help in resolving an issue.
