### PR TITLE
Stats improvement for Uncompressed Chunks

### LINKED ISSUE #3376: Size of the chunks increase without being decompressed if decompress_chunk(i) fails in middle
**Relevant system information:**
OS: [e.g. Ubuntu 16.04, Windows 10 x64, etc]: Docker / timescale/timescaledb:2.3.0-pg12
 - PostgreSQL version (output of `postgres --version`): 12.7
 - TimescaleDB version (output of `\dx` in `psql`): 2.3.0
 - Installation method: [e.g., "using Docker", "apt install", "source"] :  "Using Docker"

**Describe the bug**
If `select decompress_chunk(i) FROM show_chunks('<hypertable>') i` fails in the middle because there was 'a chunk' which was already decompressed, the chunks on which it has acted upon (before the failure) still shows as compressed (which is expected) but their size increases somehow( which isn't expected).  Upon repeated execution of the above failing command, the size increase continuously with the status still remain as 'compressed'

**To Reproduce**
```
drop table sensor_data;

create table sensor_data( 
time timestamptz not null, 
sensor_id integer not null, 
cpu double precision null,
temperature double precision null );

select from create_hypertable('sensor_data','time');

INSERT INTO sensor_data
	SELECT
		time + (INTERVAL '1 minute' * random()) AS time,
		sensor_id,
		random() AS cpu,
		random()* 100 AS temperature
	FROM
		generate_series(now() - INTERVAL '1 months', now() - INTERVAL '1 week', INTERVAL '1 minute') AS g1(time),
		generate_series(1, 100, 1 ) AS g2(sensor_id)
	ORDER BY
		time;
```
```
SELECT *,pg_size_pretty(total_bytes) FROM chunks_detailed_size('sensor_data');
     SELECT chunk_name,pg_size_pretty(total_bytes) as total_size FROM chunks_detailed_size('sensor_data');
    chunk_name    | total_size
------------------+------------
 _hyper_1_1_chunk | 51 MB
 _hyper_1_2_chunk | 97 MB
 _hyper_1_3_chunk | 97 MB
 _hyper_1_4_chunk | 87 MB
 ```
```
alter table sensor_data set (timescaledb.compress, 
timescaledb.compress_orderby = 'time DESC');

defaultdb=> select compress_chunk(i) FROM show_chunks('sensor_data', older_than => '8 days'::INTERVAL) i;                   
------------------------------------------
 _timescaledb_internal._hyper_1_1_chunk
 _timescaledb_internal._hyper_1_2_chunk
 _timescaledb_internal._hyper_1_3_chunk
(3 rows)

SELECT chunk_name,pg_size_pretty(total_bytes) as total_size FROM chunks_detailed_size('sensor_data') order by chunk_name;;
    chunk_name    | total_size
------------------+------------
 _hyper_1_1_chunk | 11 MB
 _hyper_1_2_chunk | 20 MB
 _hyper_1_3_chunk | 20 MB
 _hyper_1_4_chunk | 87 MB
(4 rows)
```
```
select decompress_chunk('_timescaledb_internal._hyper_1_2_chunk');
            decompress_chunk
----------------------------------------
 _timescaledb_internal._hyper_1_2_chunk

SELECT chunk_name,pg_size_pretty(total_bytes) as total_size FROM chunks_detailed_size('sensor_data') order by chunk_name;;
    chunk_name    | total_size
------------------+------------
 _hyper_1_1_chunk | 11 MB
 _hyper_1_2_chunk | 80 MB
 _hyper_1_3_chunk | 20 MB
 _hyper_1_4_chunk | 87 MB
(4 rows)
```
```
select decompress_chunk(i) FROM show_chunks('sensor_data', older_than => '8 days'::INTERVAL) i;
ERROR:  chunk "_hyper_1_2_chunk" is not compressed

SELECT chunk_name,pg_size_pretty(total_bytes) as total_size FROM chunks_detailed_size('sensor_data') order by chunk_name;;
    chunk_name    | total_size
------------------+------------
 _hyper_1_1_chunk | 41 MB <== notice here that the size is increased
 _hyper_1_2_chunk | 80 MB
 _hyper_1_3_chunk | 20 MB
 _hyper_1_4_chunk | 87 MB
(4 rows)

select chunk_name,is_compressed from timescaledb_information.chunks;
    chunk_name    | is_compressed
------------------+---------------
 _hyper_1_1_chunk | t <== the status is still shown as compressed.
 _hyper_1_2_chunk | f
 _hyper_1_3_chunk | t
 _hyper_1_4_chunk | f
(4 rows)
```
Also if it's repeated, the chunk size increases again. Ex:
```
SELECT chunk_name,pg_size_pretty(total_bytes) as total_size FROM chunks_detailed_size('sensor_data') order by chunk_name;;
    chunk_name    | total_size
------------------+------------
 _hyper_1_1_chunk | 72 MB <== the size increased again, and status is still 't' in metadata
 _hyper_1_2_chunk | 80 MB
 _hyper_1_3_chunk | 20 MB
 _hyper_1_4_chunk | 87 MB
(4 rows)
```

**Expected behavior**
If the idea is to fail the complete transaction, the size of the chunks before failure should not increase. 

**Actual behavior**
Size of the chunks before the command fails increases and is repeatable

### PR DESCRIPTION
**Pull request by shhnwz**
During the compression autovacuum use to be disabled for uncompressed chunk and enable after decompression. This leads to postgres maintainence issue. Let's not disable autovacuum for uncompressed chunk anymore. Let postgres take care of the stats in its natural way.

Fixes #3376 #4578 #4156

### CODE REVIEW

File: tsl/src/compression/api.c [hunk 1]
```diff
@@ -415,10 +374,7 @@ compress_chunk_impl(Oid hypertable_relid, Oid chunk_relid)
 	/* acquire locks on src and compress hypertable and src chunk */
 	LockRelationOid(cxt.srcht->main_table_relid, AccessShareLock);
 	LockRelationOid(cxt.compress_ht->main_table_relid, AccessShareLock);
-	LockRelationOid(cxt.srcht_chunk->table_id, ShareLock);
-
-	/* Disabling autovacuum on chunk which should be empty while in compressed state */
-	disable_autovacuum_on_chunk(chunk_relid);
+	LockRelationOid(cxt.srcht_chunk->table_id, ExclusiveLock);
```
Comment (akuzm) [inline tsl/src/compression/api.c:377]: Why do we need to change the lock type here?

**Comment by akuzm** [comment]
The issue also says: 
> we should instead use the get_relation_stats_hook to handle compressed chunk stats.

Do we have to change it in this PR as well?

File: tsl/src/compression/api.c (hunk 1 above)
Comment (shhnwz) [reply tsl/src/compression/api.c:377]: To avoid the side effect of removing disable_autovacuum_on_chunk. Test "compression_chunk_race" was failing. After debugging figured out that SharedLock leads to deadlock during parallel compression job. If we see decompression code this table has ExclusiveLock. Previously, disable_autovacuum_on_chunk was taking RowExclusiveLock during update, unknowingly preventing the deadlock.

Comment (svenklemm) [reply tsl/src/compression/api.c:377]: The ALTER TABLE command that disabled autovacuum had an implicit ExclusiveLock

File: sql/updates/reverse-dev.sql [hunk 2]
```diff
@@ -2,3 +2,5 @@ DROP FUNCTION _timescaledb_internal.ping_data_node(NAME, INTERVAL);
 
 CREATE OR REPLACE FUNCTION _timescaledb_internal.ping_data_node(node_name NAME) RETURNS BOOLEAN
 AS '@MODULE_PATHNAME@', 'ts_data_node_ping' LANGUAGE C VOLATILE;
+
+DROP FUNCTION IF EXISTS _timescaledb_internal.get_approx_row_count(oid); --shhnwz
```
Comment (fabriziomello) [inline sql/updates/reverse-dev.sql:6]:
```suggestion
DROP FUNCTION IF EXISTS _timescaledb_internal.get_approx_row_count(REGCLASS);
```

**Comment by svenklemm** [comment]
You shouldnt link internal issues in commit messages, the current commit message also links to wrong issue.

**Comment by shhnwz** [comment]
> 

Thanks @svenklemm , 
Updated the Comment with reported issues from the customer.

**Review by svenklemm — APPROVED** [review]

**Comment by svenklemm** [comment]
We should probably propagate ANALYZE/VACUUM on the hypertable to the compressed hypertable

File: .github/gh_matrix_builder.py [hunk 3]
```diff
@@ -141,10 +141,22 @@ def macos_config(overrides):
 # partialize_finalize is ignored due to #4937
 pg15_installcheck_args = "IGNORES='partialize_finalize'"
 
+# transparent_decompress_chunk-13 is ignored due to #5118
```
Comment (akuzm) [inline .github/gh_matrix_builder.py:144]: #5118 is this one, right? Can you explain this in more details?

File: .github/gh_matrix_builder.py [hunk 4]
```diff
@@ -141,10 +141,22 @@ def macos_config(overrides):
...
+pg13_installcheck_args = (
+    "IGNORES='bgw_db_scheduler bgw_db_scheduler_fixed transparent_decompress_chunk-13'"
```
Comment (akuzm) [inline .github/gh_matrix_builder.py:146]: bgw tests are generally flaky, but we shouldn't be ignoring them in this PR I think.

File: sql/size_utils.sql [hunk 5]
```diff
@@ -394,6 +394,86 @@ $BODY$ SET search_path TO pg_catalog, pg_temp;
...
+    local_compressed_chunk_oid  OID;
+    max_compressed_row_count BIGINT = 1000;
+    is_compressed_chunk INTEGER;
+BEGIN
+    SELECT relname, nspname FROM pg_class c
+    INNER JOIN pg_namespace n ON (n.OID = c.relnamespace)
+    INTO local_table_name, local_schema_name
+    WHERE c.OID = relation;
+
+    -- If OID is Hypertable
```
Comment (akuzm) [inline sql/size_utils.sql:418]:
```suggestion
    -- The input relation is Hypertable
```

File: sql/size_utils.sql [hunk 6]
```diff
@@ -394,6 +394,86 @@ $BODY$ SET search_path TO pg_catalog, pg_temp;
...
+           INNER JOIN pg_namespace n ON (n.nspname = h.schema_name);
+
+           compressed_row_count = _timescaledb_internal.get_approx_row_count(compressed_hypertable_oid);
+           RETURN (uncompressed_row_count + (compressed_row_count * max_compressed_row_count));
+        ELSE
+           uncompressed_row_count = _timescaledb_internal.get_approx_row_count(relation);
+           RETURN uncompressed_row_count;
+        END IF;
+    END IF;
+    -- IF OID is CHUNK
```
Comment (akuzm) [inline sql/size_utils.sql:439]:
```suggestion
    -- The input relation is a chunk.
```

File: sql/size_utils.sql [hunk 7]
```diff
@@ -394,6 +394,86 @@ $BODY$ SET search_path TO pg_catalog, pg_temp;
...
+    IF EXISTS (SELECT 1 FROM _timescaledb_catalog.chunk WHERE table_name = local_table_name AND schema_name = local_schema_name) THEN
+        with compressed_chunk as (select 1 as is_compressed_chunk from _timescaledb_catalog.chunk c
+        inner join _timescaledb_catalog.hypertable h on (c.hypertable_id = h.compressed_hypertable_id)
+        where c.table_name = local_table_name and c.schema_name = local_schema_name ),
+        chunk_temp as (select compressed_chunk_id from _timescaledb_catalog.chunk c where c.table_name = local_table_name and c.schema_name = local_schema_name)
+        select ct.compressed_chunk_id, cc.is_compressed_chunk from chunk_temp ct LEFT OUTER JOIN compressed_chunk cc ON 1 = 1
+        INTO local_compressed_chunk_id, is_compressed_chunk;
+        -- 'input is chunk #1';
+        IF is_compressed_chunk IS NULL AND local_compressed_chunk_id IS NOT NULL THEN
+        -- 'uncompressed chunk + compressed chunk #2';
```
Comment (akuzm) [inline sql/size_utils.sql:449]:
```suggestion
        -- Have both compressed and uncompressed parts for this chunk.
```

File: sql/size_utils.sql [hunk 8]
```diff
@@ -394,6 +394,86 @@ $BODY$ SET search_path TO pg_catalog, pg_temp;
...
+            (ch.id = local_compressed_chunk_id and ch.schema_name = ns.nspname))
+            SELECT c.oid FROM pg_class c INNER JOIN compressed_ns_oid
+            ON ( c.relnamespace = compressed_ns_oid.oid AND c.relname = compressed_ns_oid.table_name)
+            INTO local_compressed_chunk_oid;
+
+            uncompressed_row_count = _timescaledb_internal.get_approx_row_count(relation);
+            compressed_row_count = _timescaledb_internal.get_approx_row_count(local_compressed_chunk_oid);
+            RETURN uncompressed_row_count + (compressed_row_count * max_compressed_row_count);
+        ELSIF is_compressed_chunk IS NULL AND local_compressed_chunk_id IS NULL THEN
+        -- 'uncompressed chunk only #3';
```
Comment (akuzm) [inline sql/size_utils.sql:460]:
```suggestion
        -- Have only uncompressed part for this chunk.
```

File: sql/size_utils.sql [hunk 9]
```diff
@@ -394,6 +394,86 @@ $BODY$ SET search_path TO pg_catalog, pg_temp;
...
+            uncompressed_row_count = _timescaledb_internal.get_approx_row_count(relation);
+            RETURN uncompressed_row_count;
+        ELSE
+        -- 'compressed chunk only #4';
```
Comment (akuzm) [inline sql/size_utils.sql:464]:
```suggestion
        -- Have only compressed part for this chunk.
```

File: sql/size_utils.sql [hunk 10]
```diff
@@ -394,6 +394,86 @@ $BODY$ SET search_path TO pg_catalog, pg_temp;
...
+           uncompressed_row_count = _timescaledb_internal.get_approx_row_count(relation);
+           RETURN uncompressed_row_count;
+        END IF;
+    END IF;
+    -- IF OID is CHUNK
+    IF EXISTS (SELECT 1 FROM _timescaledb_catalog.chunk WHERE table_name = local_table_name AND schema_name = local_schema_name) THEN
+        with compressed_chunk as (select 1 as is_compressed_chunk from _timescaledb_catalog.chunk c
+        inner join _timescaledb_catalog.hypertable h on (c.hypertable_id = h.compressed_hypertable_id)
+        where c.table_name = local_table_name and c.schema_name = local_schema_name ),
+        chunk_temp as (select compressed_chunk_id from _timescaledb_catalog.chunk c where c.table_name = local_table_name and c.schema_name = local_schema_name)
```
Comment (akuzm) [inline sql/size_utils.sql:444]: The chunk name + schema are unique in the database, right? Maybe you could remove the join with `hypertable` and combine this in a single select then.

**Review by akuzm — APPROVED** [review]

File: sql/size_utils.sql (hunk 10 above)
Comment (shhnwz) [reply sql/size_utils.sql:444]: Actually, this query is meant to initialize necessary local variables required to process further cases. Depending upon the cases respective local variables are utilized. Join with hypertable is required to confirm that the chunk hypertable_id belongs to compressed_hypertable_id.

File: sql/size_utils.sql (hunk 5 above)
Comment (shhnwz) [reply sql/size_utils.sql:418]: done.

File: sql/size_utils.sql (hunk 6 above)
Comment (shhnwz) [reply sql/size_utils.sql:439]: done

File: sql/size_utils.sql (hunk 7 above)
Comment (shhnwz) [reply sql/size_utils.sql:449]: done.

File: sql/size_utils.sql (hunk 8 above)
Comment (shhnwz) [reply sql/size_utils.sql:460]: done.

File: sql/size_utils.sql (hunk 9 above)
Comment (shhnwz) [reply sql/size_utils.sql:464]: done.
