### PR TITLE
Check unique indexes when enabling compression

### LINKED ISSUE #5892: [Bug]: Enforce timescaledb.compress_segmentby for unique indexes
### What type of bug is this?

Performance issue

### What subsystems and features are affected?

Compression

### What happened?

Having:

- a table that has a unique index
- that is compressed without the unique columns
- is inserted to with the `ON CONFLICT DO NOTHING`
- will decompress *a lot* of data to verify the constraint.

Example, when using a primary key, we are presented with a good message that our `segmentby` is wrong:

```sql
feike=# create table a(location smallint not null, device_id smallint not null, time timestamptz not null, value float8 not null, primary key (location, device_id, time));
CREATE TABLE
feike=# select create_hypertable('a', 'time');
 create_hypertable 
-------------------
 (3,public,a,t)
(1 row)

feike=# alter table a set (timescaledb.compress);
ERROR:  column "location" must be used for segmenting or ordering
DETAIL:  The constraint "a_pkey" cannot be enforced with the given compression configuration.
```

However, this does not happen if we have created a unique index, even though the same objections exist as for the primary key case:
```sql
feike=# create table b(location smallint not null, device_id smallint not null, time timestamptz not null, value float8 not null);
CREATE TABLE
feike=# create unique index on b(location, device_id, time);
CREATE INDEX
feike=# select create_hypertable('b', 'time');
 create_hypertable 
-------------------
 (5,public,b,t)
(1 row)

feike=# alter table b set (timescaledb.compress);
ALTER TABLE
```

### TimescaleDB version affected

2.11.1

### PostgreSQL version used

15.3

### What operating system did you use?

Ubuntu 22.04.2

### What installation method did you use?

Deb/Apt

### What platform did you run on?

Not applicable

### Relevant log output and stack trace

_No response_

### How can we reproduce the bug?

```sql
drop table b;
create table b(location smallint not null, device_id smallint not null, time timestamptz not null, value float8 not null);
create unique index on b(location, device_id, time);
select create_hypertable('b', 'time');
alter table b set (timescaledb.compress, timescaledb.compress_segmentby='location');

insert into b
select
    (random()*100)::smallint,
    (random()*100)::smallint,
    now() - random() * interval '3 months',
    random()
FROM
    generate_series(1,1000000)
ON CONFLICT DO NOTHING;

-- compress all the chunks
select
    compress_chunk(format('%I.%I', chunk_schema, chunk_name))
from
    timescaledb_information.chunks
where
    hypertable_schema = 'public'
    and hypertable_name = 'b';

-- this needs to inspect pretty much every compressed tuple, as the segmentby
-- and the uniqueness do not align 
explain (analyze, verbose, buffers)
INSERT INTO b
select
    *
FROM
    b
where
    device_id = 8
ON CONFLICT DO NOTHING;
```

```text
                                                                                                                                                                            QUERY PLAN                                                                                                                                                                             
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 Custom Scan (HypertableModify)  (cost=0.03..7112.14 rows=1414000 width=20) (actual time=3639.240..3639.249 rows=0 loops=1)
   Buffers: shared hit=4223606 read=28 dirtied=15162 written=15130
   ->  Insert on public.b  (cost=0.03..7112.14 rows=1414000 width=20) (actual time=3639.240..3639.249 rows=0 loops=1)
         Conflict Resolution: NOTHING
         Tuples Inserted: 9895
         Conflicting Tuples: 0
         Buffers: shared hit=4223606 read=28 dirtied=15162 written=15130
         ->  Custom Scan (ChunkDispatch)  (cost=0.03..7112.14 rows=1414000 width=20) (actual time=0.356..3615.154 rows=9895 loops=1)
               Output: b_1.location, b_1.device_id, b_1."time", b_1.value
               Buffers: shared hit=4193816 read=28 dirtied=15162 written=15130
               ->  Append  (cost=0.03..7112.14 rows=1414000 width=20) (actual time=0.015..70.690 rows=9895 loops=1)
                     Buffers: shared hit=13822 dirtied=4
                     ->  Custom Scan (DecompressChunk) on _timescaledb_internal._hyper_7_57_chunk  (cost=0.03..3.01 rows=101000 width=20) (actual time=0.014..2.227 rows=283 loops=1)
                           Output: _hyper_7_57_chunk.location, _hyper_7_57_chunk.device_id, _hyper_7_57_chunk."time", _hyper_7_57_chunk.value
                           Filter: (_hyper_7_57_chunk.device_id = 8)
                           Rows Removed by Filter: 27445
                           Buffers: shared hit=625
                           ->  Seq Scan on _timescaledb_internal.compress_hyper_8_71_chunk  (cost=0.00..3.01 rows=101 width=118) (actual time=0.004..0.020 rows=101 loops=1)
                                 Output: compress_hyper_8_71_chunk.location, compress_hyper_8_71_chunk.device_id, compress_hyper_8_71_chunk."time", compress_hyper_8_71_chunk.value, compress_hyper_8_71_chunk._ts_meta_count, compress_hyper_8_71_chunk._ts_meta_sequence_num, compress_hyper_8_71_chunk._ts_meta_min_1, compress_hyper_8_71_chunk._ts_meta_max_1
                                 Buffers: shared hit=2
                     ->  Custom Scan (DecompressChunk) on _timescaledb_internal._hyper_7_58_chunk  (cost=0.03..3.01 rows=101000 width=20) (actual time=0.060..5.659 rows=746 loops=1)
                           Output: _hyper_7_58_chunk.location, _hyper_7_58_chunk.device_id, _hyper_7_58_chunk."time", _hyper_7_58_chunk.value
                           Filter: (_hyper_7_58_chunk.device_id = 8)
                           Rows Removed by Filter: 77078
                           Buffers: shared hit=1026
                           ->  Seq Scan on _timescaledb_internal.compress_hyper_8_72_chunk  (cost=0.00..3.01 rows=101 width=118) (actual time=0.005..0.033 rows=101 loops=1)
                                 Output: compress_hyper_8_72_chunk.location, compress_hyper_8_72_chunk.device_id, compress_hyper_8_72_chunk."time", compress_hyper_8_72_chunk.value, compress_hyper_8_72_chunk._ts_meta_count, compress_hyper_8_72_chunk._ts_meta_sequence_num, compress_hyper_8_72_chunk._ts_meta_min_1, compress_hyper_8_72_chunk._ts_meta_max_1
                                 Buffers: shared hit=2
                     ->  Custom Scan (DecompressChunk) on _timescaledb_internal._hyper_7_59_chunk  (cost=0.03..3.01 rows=101000 width=20) (actual time=0.125..5.349 rows=772 loops=1)
                           Output: _hyper_7_59_chunk.location, _hyper_7_59_chunk.device_id, _hyper_7_59_chunk."time", _hyper_7_59_chunk.value
                           Filter: (_hyper_7_59_chunk.device_id = 8)
                           Rows Removed by Filter: 76453
                           Buffers: shared hit=1023
                           ->  Seq Scan on _timescaledb_internal.compress_hyper_8_73_chunk  (cost=0.00..3.01 rows=101 width=118) (actual time=0.008..0.035 rows=101 loops=1)
                                 Output: compress_hyper_8_73_chunk.location, compress_hyper_8_73_chunk.device_id, compress_hyper_8_73_chunk."time", compress_hyper_8_73_chunk.value, compress_hyper_8_73_chunk._ts_meta_count, compress_hyper_8_73_chunk._ts_meta_sequence_num, compress_hyper_8_73_chunk._ts_meta_min_1, compress_hyper_8_73_chunk._ts_meta_max_1
                                 Buffers: shared hit=2
                     ->  Custom Scan (DecompressChunk) on _timescaledb_internal._hyper_7_60_chunk  (cost=0.03..3.01 rows=101000 width=20) (actual time=0.059..4.794 rows=707 loops=1)
                           Output: _hyper_7_60_chunk.location, _hyper_7_60_chunk.device_id, _hyper_7_60_chunk."time", _hyper_7_60_chunk.value
                           Filter: (_hyper_7_60_chunk.device_id = 8)
                           Rows Removed by Filter: 70879
                           Buffers: shared hit=1005
                           ->  Seq Scan on _timescaledb_internal.compress_hyper_8_74_chunk  (cost=0.00..3.01 rows=101 width=118) (actual time=0.005..0.028 rows=101 loops=1)
                                 Output: compress_hyper_8_74_chunk.location, compress_hyper_8_74_chunk.device_id, compress_hyper_8_74_chunk."time", compress_hyper_8_74_chunk.value, compress_hyper_8_74_chunk._ts_meta_count, compress_hyper_8_74_chunk._ts_meta_sequence_num, compress_hyper_8_74_chunk._ts_meta_min_1, compress_hyper_8_74_chunk._ts_meta_max_1
                                 Buffers: shared hit=2
                     ->  Custom Scan (DecompressChunk) on _timescaledb_internal._hyper_7_61_chunk  (cost=0.03..3.01 rows=101000 width=20) (actual time=0.066..5.390 rows=718 loops=1)
                           Output: _hyper_7_61_chunk.location, _hyper_7_61_chunk.device_id, _hyper_7_61_chunk."time", _hyper_7_61_chunk.value
                           Filter: (_hyper_7_61_chunk.device_id = 8)
                           Rows Removed by Filter: 76850
                           Buffers: shared hit=1024
                           ->  Seq Scan on _timescaledb_internal.compress_hyper_8_75_chunk  (cost=0.00..3.01 rows=101 width=118) (actual time=0.006..0.037 rows=101 loops=1)
                                 Output: compress_hyper_8_75_chunk.location, compress_hyper_8_75_chunk.device_id, compress_hyper_8_75_chunk."time", compress_hyper_8_75_chunk.value, compress_hyper_8_75_chunk._ts_meta_count, compress_hyper_8_75_chunk._ts_meta_sequence_num, compress_hyper_8_75_chunk._ts_meta_min_1, compress_hyper_8_75_chunk._ts_meta_max_1
                                 Buffers: shared hit=2
                     ->  Custom Scan (DecompressChunk) on _timescaledb_internal._hyper_7_62_chunk  (cost=0.03..3.01 rows=101000 width=20) (actual time=0.062..5.005 rows=743 loops=1)
                           Output: _hyper_7_62_chunk.location, _hyper_7_62_chunk.device_id, _hyper_7_62_chunk."time", _hyper_7_62_chunk.value
                           Filter: (_hyper_7_62_chunk.device_id = 8)
                           Rows Removed by Filter: 71964
                           Buffers: shared hit=1007 dirtied=1
                           ->  Seq Scan on _timescaledb_internal.compress_hyper_8_76_chunk  (cost=0.00..3.01 rows=101 width=118) (actual time=0.005..0.030 rows=101 loops=1)
                                 Output: compress_hyper_8_76_chunk.location, compress_hyper_8_76_chunk.device_id, compress_hyper_8_76_chunk."time", compress_hyper_8_76_chunk.value, compress_hyper_8_76_chunk._ts_meta_count, compress_hyper_8_76_chunk._ts_meta_sequence_num, compress_hyper_8_76_chunk._ts_meta_min_1, compress_hyper_8_76_chunk._ts_meta_max_1
                                 Buffers: shared hit=2
                     ->  Custom Scan (DecompressChunk) on _timescaledb_internal._hyper_7_63_chunk  (cost=0.03..3.01 rows=101000 width=20) (actual time=0.059..5.152 rows=774 loops=1)
                           Output: _hyper_7_63_chunk.location, _hyper_7_63_chunk.device_id, _hyper_7_63_chunk."time", _hyper_7_63_chunk.value
                           Filter: (_hyper_7_63_chunk.device_id = 8)
                           Rows Removed by Filter: 77184
                           Buffers: shared hit=1022 dirtied=1
                           ->  Seq Scan on _timescaledb_internal.compress_hyper_8_77_chunk  (cost=0.00..3.01 rows=101 width=118) (actual time=0.005..0.031 rows=101 loops=1)
                                 Output: compress_hyper_8_77_chunk.location, compress_hyper_8_77_chunk.device_id, compress_hyper_8_77_chunk."time", compress_hyper_8_77_chunk.value, compress_hyper_8_77_chunk._ts_meta_count, compress_hyper_8_77_chunk._ts_meta_sequence_num, compress_hyper_8_77_chunk._ts_meta_min_1, compress_hyper_8_77_chunk._ts_meta_max_1
                                 Buffers: shared hit=2
                     ->  Custom Scan (DecompressChunk) on _timescaledb_internal._hyper_7_64_chunk  (cost=0.03..3.01 rows=101000 width=20) (actual time=0.066..5.186 rows=767 loops=1)
                           Output: _hyper_7_64_chunk.location, _hyper_7_64_chunk.device_id, _hyper_7_64_chunk."time", _hyper_7_64_chunk.value
                           Filter: (_hyper_7_64_chunk.device_id = 8)
                           Rows Removed by Filter: 77674
                           Buffers: shared hit=1026
                           ->  Seq Scan on _timescaledb_internal.compress_hyper_8_78_chunk  (cost=0.00..3.01 rows=101 width=118) (actual time=0.005..0.033 rows=101 loops=1)
                                 Output: compress_hyper_8_78_chunk.location, compress_hyper_8_78_chunk.device_id, compress_hyper_8_78_chunk."time", compress_hyper_8_78_chunk.value, compress_hyper_8_78_chunk._ts_meta_count, compress_hyper_8_78_chunk._ts_meta_sequence_num, compress_hyper_8_78_chunk._ts_meta_min_1, compress_hyper_8_78_chunk._ts_meta_max_1
                                 Buffers: shared hit=2
                     ->  Custom Scan (DecompressChunk) on _timescaledb_internal._hyper_7_65_chunk  (cost=0.03..3.01 rows=101000 width=20) (actual time=0.055..5.632 rows=776 loops=1)
                           Output: _hyper_7_65_chunk.location, _hyper_7_65_chunk.device_id, _hyper_7_65_chunk."time", _hyper_7_65_chunk.value
                           Filter: (_hyper_7_65_chunk.device_id = 8)
                           Rows Removed by Filter: 76749
                           Buffers: shared hit=1026
                           ->  Seq Scan on _timescaledb_internal.compress_hyper_8_79_chunk  (cost=0.00..3.01 rows=101 width=118) (actual time=0.006..0.042 rows=101 loops=1)
                                 Output: compress_hyper_8_79_chunk.location, compress_hyper_8_79_chunk.device_id, compress_hyper_8_79_chunk."time", compress_hyper_8_79_chunk.value, compress_hyper_8_79_chunk._ts_meta_count, compress_hyper_8_79_chunk._ts_meta_sequence_num, compress_hyper_8_79_chunk._ts_meta_min_1, compress_hyper_8_79_chunk._ts_meta_max_1
                                 Buffers: shared hit=2
                     ->  Custom Scan (DecompressChunk) on _timescaledb_internal._hyper_7_66_chunk  (cost=0.03..3.01 rows=101000 width=20) (actual time=0.101..5.810 rows=824 loops=1)
                           Output: _hyper_7_66_chunk.location, _hyper_7_66_chunk.device_id, _hyper_7_66_chunk."time", _hyper_7_66_chunk.value
                           Filter: (_hyper_7_66_chunk.device_id = 8)
                           Rows Removed by Filter: 77211
                           Buffers: shared hit=1029
                           ->  Seq Scan on _timescaledb_internal.compress_hyper_8_80_chunk  (cost=0.00..3.01 rows=101 width=118) (actual time=0.009..0.043 rows=101 loops=1)
                                 Output: compress_hyper_8_80_chunk.location, compress_hyper_8_80_chunk.device_id, compress_hyper_8_80_chunk."time", compress_hyper_8_80_chunk.value, compress_hyper_8_80_chunk._ts_meta_count, compress_hyper_8_80_chunk._ts_meta_sequence_num, compress_hyper_8_80_chunk._ts_meta_min_1, compress_hyper_8_80_chunk._ts_meta_max_1
                                 Buffers: shared hit=2
                     ->  Custom Scan (DecompressChunk) on _timescaledb_internal._hyper_7_67_chunk  (cost=0.03..3.01 rows=101000 width=20) (actual time=0.075..5.197 rows=763 loops=1)
                           Output: _hyper_7_67_chunk.location, _hyper_7_67_chunk.device_id, _hyper_7_67_chunk."time", _hyper_7_67_chunk.value
                           Filter: (_hyper_7_67_chunk.device_id = 8)
                           Rows Removed by Filter: 76915
                           Buffers: shared hit=1026
                           ->  Seq Scan on _timescaledb_internal.compress_hyper_8_81_chunk  (cost=0.00..3.01 rows=101 width=118) (actual time=0.005..0.031 rows=101 loops=1)
                                 Output: compress_hyper_8_81_chunk.location, compress_hyper_8_81_chunk.device_id, compress_hyper_8_81_chunk."time", compress_hyper_8_81_chunk.value, compress_hyper_8_81_chunk._ts_meta_count, compress_hyper_8_81_chunk._ts_meta_sequence_num, compress_hyper_8_81_chunk._ts_meta_min_1, compress_hyper_8_81_chunk._ts_meta_max_1
                                 Buffers: shared hit=2
                     ->  Custom Scan (DecompressChunk) on _timescaledb_internal._hyper_7_68_chunk  (cost=0.03..3.01 rows=101000 width=20) (actual time=0.062..5.180 rows=793 loops=1)
                           Output: _hyper_7_68_chunk.location, _hyper_7_68_chunk.device_id, _hyper_7_68_chunk."time", _hyper_7_68_chunk.value
                           Filter: (_hyper_7_68_chunk.device_id = 8)
                           Rows Removed by Filter: 77051
                           Buffers: shared hit=1025
                           ->  Seq Scan on _timescaledb_internal.compress_hyper_8_82_chunk  (cost=0.00..3.01 rows=101 width=118) (actual time=0.006..0.034 rows=101 loops=1)
                                 Output: compress_hyper_8_82_chunk.location, compress_hyper_8_82_chunk.device_id, compress_hyper_8_82_chunk."time", compress_hyper_8_82_chunk.value, compress_hyper_8_82_chunk._ts_meta_count, compress_hyper_8_82_chunk._ts_meta_sequence_num, compress_hyper_8_82_chunk._ts_meta_min_1, compress_hyper_8_82_chunk._ts_meta_max_1
                                 Buffers: shared hit=2
                     ->  Custom Scan (DecompressChunk) on _timescaledb_internal._hyper_7_69_chunk  (cost=0.03..3.01 rows=101000 width=20) (actual time=0.086..3.536 rows=467 loops=1)
                           Output: _hyper_7_69_chunk.location, _hyper_7_69_chunk.device_id, _hyper_7_69_chunk."time", _hyper_7_69_chunk.value
                           Filter: (_hyper_7_69_chunk.device_id = 8)
                           Rows Removed by Filter: 49767
                           Buffers: shared hit=934
                           ->  Seq Scan on _timescaledb_internal.compress_hyper_8_83_chunk  (cost=0.00..3.01 rows=101 width=118) (actual time=0.005..0.025 rows=101 loops=1)
                                 Output: compress_hyper_8_83_chunk.location, compress_hyper_8_83_chunk.device_id, compress_hyper_8_83_chunk."time", compress_hyper_8_83_chunk.value, compress_hyper_8_83_chunk._ts_meta_count, compress_hyper_8_83_chunk._ts_meta_sequence_num, compress_hyper_8_83_chunk._ts_meta_min_1, compress_hyper_8_83_chunk._ts_meta_max_1
                                 Buffers: shared hit=2
                     ->  Custom Scan (DecompressChunk) on _timescaledb_internal._hyper_7_70_chunk  (cost=0.03..3.01 rows=101000 width=20) (actual time=0.063..5.381 rows=762 loops=1)
                           Output: _hyper_7_70_chunk.location, _hyper_7_70_chunk.device_id, _hyper_7_70_chunk."time", _hyper_7_70_chunk.value
                           Filter: (_hyper_7_70_chunk.device_id = 8)
                           Rows Removed by Filter: 76884
                           Buffers: shared hit=1024 dirtied=2
                           ->  Seq Scan on _timescaledb_internal.compress_hyper_8_84_chunk  (cost=0.00..3.01 rows=101 width=118) (actual time=0.005..0.033 rows=101 loops=1)
                                 Output: compress_hyper_8_84_chunk.location, compress_hyper_8_84_chunk.device_id, compress_hyper_8_84_chunk."time", compress_hyper_8_84_chunk.value, compress_hyper_8_84_chunk._ts_meta_count, compress_hyper_8_84_chunk._ts_meta_sequence_num, compress_hyper_8_84_chunk._ts_meta_min_1, compress_hyper_8_84_chunk._ts_meta_max_1
                                 Buffers: shared hit=2
 Query Identifier: -1198599302444820833
 Planning:
   Buffers: shared hit=2519 read=44
 Planning Time: 2.850 ms
 Execution Time: 3639.799 ms
(129 rows)
```

### PR DESCRIPTION
**Pull request by mkindahl**
When enabling compression on a table, there is a check of unique constraints and primary key constraints, but no check if there is just a unique index. This means that it is possible to create a compressed table without getting a warning that you should include the columns in the index into the segmentby field, which can lead to suboptimal query times.

This commit adds a check for the unique index as well and ensure that a similar warning is printed as for a unique constraint.

Fixes #5892

### CODE REVIEW

File: tsl/src/compression/create.c [hunk 1]
```diff
@@ -844,11 +854,10 @@ validate_existing_constraints(Hypertable *ht, CompressColInfo *colinfo)
 			attnums = (int16 *) ARR_DATA_PTR(arr);
 			for (j = 0; j < numkeys; j++)
 			{
-				FormData_hypertable_compression *col_def =
+				Form_hypertable_compression col_def =
```
Comment (nikkhils) [inline tsl/src/compression/create.c:857]: converting it from a pointer into a struct?
Won't that cause issues with the `Ensure` below?

File: tsl/test/expected/compression_errors.out [hunk 2]
```diff
@@ -782,3 +782,25 @@ SELECT compress_chunk(show_chunks('readings'), TRUE);
...
+);
+CREATE UNIQUE index ON table_unique_index(location, device_id, time);
+SELECT table_name FROM create_hypertable('table_unique_index', 'time');
+     table_name     
+--------------------
+ table_unique_index
+(1 row)
+
+\set ON_ERROR_STOP 0
+ALTER TABLE table_unique_index SET (timescaledb.compress);
```
Comment (nikkhils) [inline tsl/test/expected/compression_errors.out:803]: We have added a WARNING and not an ERROR. So we don't need this ON_ERROR_STOP?

File: tsl/src/compression/create.c (hunk 1 above)
Comment (mkindahl) [reply tsl/src/compression/create.c:857]: I am just using the existing definition rather than explicitly defining a pointer.
```c
typedef FormData_hypertable_compression *Form_hypertable_compression;
```

File: tsl/src/compression/create.c [hunk 3]
```diff
@@ -802,9 +802,18 @@ validate_existing_constraints(Hypertable *ht, CompressColInfo *colinfo)
...
-		/* we check primary ,unique and exclusion constraints.
-		 * move foreign key constarints over to compression table
-		 * ignore triggers
+		/* Save away the supporting index, if any, that we check so that we
+		 * can ignore it in the index checking and not get duplicate messages.
+		 *
+		 * We are saving all checked indexes here even though only the unique
+		 * index is a problem at this point. It potentially avoids a second
+		 * check of an index that we have already checked. */
+		if (form->conindid)
```
Comment (fabriziomello) [inline tsl/src/compression/create.c:811]:
```suggestion
		if (OidIsValid(form->conindid))
```
I guess we should check for a valid oid here, no?

Comment (mkindahl) [reply tsl/src/compression/create.c]: Either one works, PostgreSQL use both forms internally. Applied it.

File: tsl/test/expected/compression_errors.out (hunk 2 above)
Comment (mkindahl) [reply tsl/test/expected/compression_errors.out:802]: Correct. Fixed that.

File: tsl/test/sql/compression_errors.sql [hunk 4]
```diff
@@ -469,3 +469,18 @@ SELECT compress_chunk(show_chunks('readings'), TRUE);
...
+-- column.
+CREATE TABLE table_unique_index(
+       location smallint not null,
+       device_id smallint not null,
+       time timestamptz not null,
+       value float8 not null
+);
+CREATE UNIQUE index ON table_unique_index(location, device_id, time);
+SELECT table_name FROM create_hypertable('table_unique_index', 'time');
+ALTER TABLE table_unique_index SET (timescaledb.compress);
```
Comment (fabriziomello) [inline tsl/test/sql/compression_errors.sql:485]:
```suggestion
-- Will warn because the lack of segmentby/orderby compression options
ALTER TABLE table_unique_index SET (timescaledb.compress);
ALTER TABLE table_unique_index SET (timescaledb.compress = off);
-- Will enable compression without warnings
ALTER TABLE table_unique_index SET (timescaledb.compress, timescaledb.compress_segmentby = 'location', timescaledb.compress_orderby = 'device_id');
```
What about extend a bit this regression test?

Comment (mkindahl) [reply tsl/test/sql/compression_errors.sql:486]: Added these and a few extra. PTAL.

File: tsl/test/expected/compression_errors.out [hunk 5]
```diff
@@ -782,3 +782,42 @@ SELECT compress_chunk(show_chunks('readings'), TRUE);
...
+ table_unique_index
+(1 row)
+
+-- Will warn because the lack of segmentby/orderby compression options
+ALTER TABLE table_unique_index SET (timescaledb.compress);
+WARNING:  column "location" should be used for segmenting or ordering
+WARNING:  column "device_id" should be used for segmenting or ordering
+ALTER TABLE table_unique_index SET (timescaledb.compress = off);
+ALTER TABLE table_unique_index SET (timescaledb.compress, timescaledb.compress_segmentby = 'location');
+WARNING:  column "device_id" should be used for segmenting or ordering
```
Comment (sb230132) [inline tsl/test/expected/compression_errors.out:808]: Why there is no warning for "time" column ?

**Review by sb230132 — COMMENTED** [review]
Since we did not support UPDATE/DELETE on compressed hypertable, we had these checks to ensure columns mentioned in constraints match either segmentby or orderby columns when enabling compression.

Future plan is to remove all these checks.

**Review by nikkhils — APPROVED** [review]
LGTM

**Comment by mkindahl** [comment]
> Since we did not support UPDATE/DELETE on compressed hypertable, we had these checks to ensure columns mentioned in constraints match either segmentby or orderby columns when enabling compression.
> 
> Future plan is to remove all these checks.

I think these checks are good to have, but they should not be errors.

The reason why they are good to have is because if you pick the wrong column, you have to run a full decompression (in the current implementation) to figure out if there are any conflicts, but if you use the columns of the index as part of the segmentby columns, checking does not require decompression.

The reason they should not be errors is because it works anyway, it is just not very efficient.

File: tsl/test/expected/compression_errors.out (hunk 5 above)
Comment (mkindahl) [reply tsl/test/expected/compression_errors.out:808]: Because the time column is implicitly added to the orderby:

```c
	ownerid = ts_rel_get_owner(ht->main_table_relid);
	segmentby_cols = ts_compress_hypertable_parse_segment_by(with_clause_options, ht);
	orderby_cols = ts_compress_hypertable_parse_order_by(with_clause_options, ht);
>>	orderby_cols = add_time_to_order_by_if_not_included(orderby_cols, segmentby_cols, ht);

	if (TS_HYPERTABLE_HAS_COMPRESSION_ENABLED(ht))
		check_modify_compression_options(ht, with_clause_options, orderby_cols);

	compresscolinfo_init(&compress_cols, ht->main_table_relid, segmentby_cols, orderby_cols);
```
