### PR TITLE
Fix occasional scheduler quit with `delete_job`

### LINKED ISSUE #5711: [Bug]: Scheduler accidentally getting killed when calling `delete_job`
### What type of bug is this?

Unexpected error

### What subsystems and features are affected?

Background worker

### What happened?

Could not reproduce locally but this did happen in a few CI runs. The problem was uncovered by a flaky test: see issue #5224.  

### TimescaleDB version affected

latest

### PostgreSQL version used

14.6

### What operating system did you use?

Ubuntu

### What installation method did you use?

Source

### What platform did you run on?

On prem/Self-hosted

### Relevant log output and stack trace

_No response_

### How can we reproduce the bug?

```bash
reproducible on CI
```

### PR DESCRIPTION
**Pull request by konskov**
Previously it was possible to send pg_cancel to the scheduler
instead of the background worker for the job.
That was because we attempted to take an advisory lock on the
job id, which was assumed to be held by the background worker
for the job. However, it is possible either for the job's
worker or for the scheduler to
be the one holding the lock. The scheduler takes this lock after
the job's worker has exited, to update the job's scheduled
status.
This patch adds a check to determine if the background worker
holding the lock is the scheduler. If it's the scheduler, wait
for the lock to be released without canceling the worker.

Fixes #5711, #5224

### CODE REVIEW

File: src/bgw/job.c [hunk 1]
```diff
@@ -723,11 +723,23 @@ get_job_lock_for_delete(int32 job_id)
...
+				/* Simply assuming that this pid corresponds to the background worker
+				 * running the job is not sufficient. The scheduler could also be the
+				 * one holding the lock, when transitioning the state of the job back
+				 * to scheduled state. So we must check we don't kill the scheduler.
+				 * See https://github.com/timescale/timescaledb/issues/5224
+				 */
+				const char *worker_name = GetBackgroundWorkerTypeByPid(proc->pid);
+				const char *bgw_scheduler_name = "TimescaleDB Background Worker Scheduler";
+				/* do not kill the scheduler */
+				if (strcmp(worker_name, bgw_scheduler_name) != 0)
```
Comment (kgyrtkirk) [inline src/bgw/job.c:735]: I saw this during test runs - I see that its still in draft but wanted to note that:

this doesn't look 100% right to me

I believe this method wanted to provide a postcondition of `the job is not running anymore`  ; however with this fix  that will not be true anymore in all cases - as it may just mask it

is this the final fix?

Comment (kgyrtkirk) [reply src/bgw/job.c:735]: I understand that it might be in transistioning state for this job - but from that I don't think its implied that its being "put back" into the `SCHEDULED` state - could it be transitioning into something else?

on the other hand I agree that...this will remove the most serious issue - meaning the kill of the schq thread

**Review by kgyrtkirk — APPROVED** [review]
Can you please change the PR title / commit message to reflect that this is not a test fix - and optionally open an ticket describing the uncovered issue?

File: src/bgw/job.c [hunk 2]
```diff
@@ -723,11 +723,23 @@ get_job_lock_for_delete(int32 job_id)
...
-					 proc->pid);
-				DirectFunctionCall1(pg_cancel_backend, Int32GetDatum(proc->pid));
+				/* Simply assuming that this pid corresponds to the background worker
+				 * running the job is not sufficient. The scheduler could also be the
+				 * one holding the lock, when transitioning the state of the job back
+				 * to scheduled state. So we must check we don't kill the scheduler.
+				 * See https://github.com/timescale/timescaledb/issues/5224
+				 */
+				const char *worker_name = GetBackgroundWorkerTypeByPid(proc->pid);
+				const char *bgw_scheduler_name = "TimescaleDB Background Worker Scheduler";
```
Comment (jnidzwetzki) [inline src/bgw/job.c:733]: What is the reason for defining `bgw_scheduler_name` here? Couldn't we use [this define](https://github.com/timescale/timescaledb/blob/d9849325d0d0f81a13db1e41aa56f8b567945e72/src/bgw/scheduler.c#L44)?

Comment (konskov) [reply src/bgw/job.c]: Thank you, fixed

**Review by jnidzwetzki — APPROVED** [review]

**Review by mkindahl — APPROVED** [review]
I find it slightly odd that we are killing a background worker just because we want to delete a job. Shouldn't this it be possible even if the job is running? However, I agree that this solved the immediate problem of accidentally killing the scheduler instead of a normal background worker.
