### PR TITLE
Abort sessions after extension reload

### LINKED ISSUE #4191: [Bug]: Segfault in SELECT query after upgrade to 2.5.2
### What type of bug is this?

Crash

### What subsystems and features are affected?

Continuous aggregate

### What happened?

Running queries on a continuous aggregate in one session will trigger a segfault with an odd error message if the extension is updated in another session.

### TimescaleDB version affected

2.5.2

### PostgreSQL version used

13.5

### What operating system did you use?

Ubuntu 20.04.3 LTS

### What installation method did you use?

Source

### What platform did you run on?

On prem/Self-hosted

### Relevant log output and stack trace

_No response_

### How can we reproduce the bug?

```bash
mats@fury:~/issues/s311$ psql s311
Expanded display is used automatically.
Null display is "[NULL]".
psql (13.5)
Type "help" for help.

s311=# CREATE EXTENSION timescaledb VERSION "2.5.1";
WARNING:  
WELCOME TO
 _____ _                               _     ____________  
|_   _(_)                             | |    |  _  \ ___ \ 
  | |  _ _ __ ___   ___  ___  ___ __ _| | ___| | | | |_/ / 
  | | | |  _ ` _ \ / _ \/ __|/ __/ _` | |/ _ \ | | | ___ \ 
  | | | | | | | | |  __/\__ \ (_| (_| | |  __/ |/ /| |_/ /
  |_| |_|_| |_| |_|\___||___/\___\__,_|_|\___|___/ \____/
               Running version 2.5.1
For more information on TimescaleDB, please visit the following links:

 1. Getting started: https://docs.timescale.com/timescaledb/latest/getting-started
 2. API reference documentation: https://docs.timescale.com/api/latest
 3. How TimescaleDB is designed: https://docs.timescale.com/timescaledb/latest/overview/core-concepts

Note: TimescaleDB collects anonymous reports to better understand and assist our users.
For more information and how to disable, please see our docs https://docs.timescale.com/timescaledb/latest/how-to-guides/configuration/telemetry.

CREATE EXTENSION
s311=# 
s311=# 
s311=# CREATE TABLE conditions(
s311(#     time TIMESTAMPTZ NOT NULL,
s311(#     device_id INTEGER,
s311(#     humidity FLOAT
s311(# );
NOTICE:  switching extension state from EXTENSION_STATE_TRANSITIONING to EXTENSION_STATE_UNKNOWN
NOTICE:  switching extension state from EXTENSION_STATE_UNKNOWN to EXTENSION_STATE_CREATED
CREATE TABLE
s311=# 
s311=# SELECT * FROM create_hypertable('conditions', 'time');
 hypertable_id | schema_name | table_name | created 
---------------+-------------+------------+---------
             1 | public      | conditions | t
(1 row)

s311=# 
s311=# INSERT INTO conditions
s311-# SELECT time, (random()*3 + 1)::int, random()*100
s311-# FROM generate_series(now() - INTERVAL '7 days', now(), '1 hour') AS time;
INSERT 0 169
s311=# 
s311=# CREATE MATERIALIZED VIEW conditions_summary_daily
s311-# WITH (timescaledb.continuous) AS
s311-# SELECT device_id,
s311-#        time_bucket(INTERVAL '1 day', "time") AS bucket,
s311-#        AVG(humidity)
s311-# FROM conditions
s311-# GROUP BY device_id, bucket;
NOTICE:  refreshing continuous aggregate "conditions_summary_daily"
HINT:  Use WITH NO DATA if you do not want to refresh the continuous aggregate on creation.
CREATE MATERIALIZED VIEW
s311=# SELECT count(*) FROM conditions_summary_daily;
 count 
-------
    31
(1 row)

s311=# SELECT count(*) FROM conditions_summary_daily;
ERROR:  attempt to redefine parameter "timescaledb.enable_optimizations"
s311=# SELECT count(*) FROM conditions_summary_daily;
server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
The connection to the server was lost. Attempting reset: Failed.
!?>
```

### PR DESCRIPTION
**Pull request by mkindahl**
If a session is started and loads (and caches, by OID) functions in the
extension to use them in, for example, a `SELECT` query on a continuous
aggregate, the extension will be marked as loaded internally.

If an `ALTER EXTENSION` is then executed in a separate session, it will
update `pg_extension` to hold the new version, and any other sessions
will see this as the new version, including the session that already
loaded the previous version of the shared library.

Since the pre-update session has loaded some functions from the old
version already, running the same queries with the old named functions
will trigger a reload of the new version of the shared library to get
the new functions (same name, but different OID), but since this has
already been loaded in a different version, it will trigger an error
that GUC variables are re-defined.

Further queries after that will then corrupt the database causing a
crash.

This commit fixes this by recording the version loaded rather than if
it has been loaded and check that the version did not change after a
query has been analyzed (in the `post_analyze_hook`). If the version
changed, it will generate a fatal error to force an abort of the
session.

Fixes #4191

### CODE REVIEW

File: src/loader/loader.c [hunk 1]
```diff
@@ -670,6 +669,23 @@ static void inline do_load()
...
+	/* If the right version of the library is already loaded, we will just
+	 * skip the actual loading. If the wrong version of the library is loaded,
+	 * we need to kill the session since it will not be able to continue
+	 * operate. */
+	if (*soversion)
+	{
+		if (strcmp(soversion, version) == 0)
+			return;
+		ereport(FATAL,
+				(errcode(ERRCODE_DUPLICATE_OBJECT),
```
Comment (fabriziomello) [inline src/loader/loader.c:681]: Can we add some test here???

Comment (mkindahl) [reply src/loader/loader.c:681]: No, that is unfortunately not possible since it requires upgrading between different versions of the server. The problem only manifests itself when upgrading from one version of the server to a different version of the server.

**Comment by mkindahl** [comment]
## Before

```
mats@fury:~/issues/s311$ psql s311
Expanded display is used automatically.
Null display is "[NULL]".
psql (13.5)
Type "help" for help.

s311=# CREATE EXTENSION timescaledb VERSION "2.5.1";
WARNING:  
WELCOME TO
 _____ _                               _     ____________  
|_   _(_)                             | |    |  _  \ ___ \ 
  | |  _ _ __ ___   ___  ___  ___ __ _| | ___| | | | |_/ / 
  | | | |  _ ` _ \ / _ \/ __|/ __/ _` | |/ _ \ | | | ___ \ 
  | | | | | | | | |  __/\__ \ (_| (_| | |  __/ |/ /| |_/ /
  |_| |_|_| |_| |_|\___||___/\___\__,_|_|\___|___/ \____/
               Running version 2.5.1
For more information on TimescaleDB, please visit the following links:

 1. Getting started: https://docs.timescale.com/timescaledb/latest/getting-started
 2. API reference documentation: https://docs.timescale.com/api/latest
 3. How TimescaleDB is designed: https://docs.timescale.com/timescaledb/latest/overview/core-concepts

Note: TimescaleDB collects anonymous reports to better understand and assist our users.
For more information and how to disable, please see our docs https://docs.timescale.com/timescaledb/latest/how-to-guides/configuration/telemetry.

CREATE EXTENSION
s311=# 
s311=# 
s311=# CREATE TABLE conditions(
s311(#     time TIMESTAMPTZ NOT NULL,
s311(#     device_id INTEGER,
s311(#     humidity FLOAT
s311(# );
NOTICE:  switching extension state from EXTENSION_STATE_TRANSITIONING to EXTENSION_STATE_UNKNOWN
NOTICE:  switching extension state from EXTENSION_STATE_UNKNOWN to EXTENSION_STATE_CREATED
CREATE TABLE
s311=# 
s311=# SELECT * FROM create_hypertable('conditions', 'time');
 hypertable_id | schema_name | table_name | created 
---------------+-------------+------------+---------
             1 | public      | conditions | t
(1 row)

s311=# 
s311=# INSERT INTO conditions
s311-# SELECT time, (random()*3 + 1)::int, random()*100
s311-# FROM generate_series(now() - INTERVAL '7 days', now(), '1 hour') AS time;
INSERT 0 169
s311=# 
s311=# CREATE MATERIALIZED VIEW conditions_summary_daily
s311-# WITH (timescaledb.continuous) AS
s311-# SELECT device_id,
s311-#        time_bucket(INTERVAL '1 day', "time") AS bucket,
s311-#        AVG(humidity)
s311-# FROM conditions
s311-# GROUP BY device_id, bucket;
NOTICE:  refreshing continuous aggregate "conditions_summary_daily"
HINT:  Use WITH NO DATA if you do not want to refresh the continuous aggregate on creation.
CREATE MATERIALIZED VIEW
s311=# SELECT count(*) FROM conditions_summary_daily;
 count 
-------
    31
(1 row)
```

Do an `ALTER EXTENSION` in a different session.

```
s311=# SELECT count(*) FROM conditions_summary_daily;
ERROR:  attempt to redefine parameter "timescaledb.enable_optimizations"
s311=# SELECT count(*) FROM conditions_summary_daily;
server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
The connection to the server was lost. Attempting reset: Failed.
!?> 
!?> \q
```

## After

```
mats@fury:~/issues/s311$ psql s311 
Expanded display is used automatically.
Null display is "[NULL]".
psql (13.5)
Type "help" for help.

s311=# CREATE EXTENSION timescaledb VERSION "2.5.1";
WARNING:  
WELCOME TO
 _____ _                               _     ____________  
|_   _(_)                             | |    |  _  \ ___ \ 
  | |  _ _ __ ___   ___  ___  ___ __ _| | ___| | | | |_/ / 
  | | | |  _ ` _ \ / _ \/ __|/ __/ _` | |/ _ \ | | | ___ \ 
  | | | | | | | | |  __/\__ \ (_| (_| | |  __/ |/ /| |_/ /
  |_| |_|_| |_| |_|\___||___/\___\__,_|_|\___|___/ \____/
               Running version 2.5.1
For more information on TimescaleDB, please visit the following links:

 1. Getting started: https://docs.timescale.com/timescaledb/latest/getting-started
 2. API reference documentation: https://docs.timescale.com/api/latest
 3. How TimescaleDB is designed: https://docs.timescale.com/timescaledb/latest/overview/core-concepts

Note: TimescaleDB collects anonymous reports to better understand and assist our users.
For more information and how to disable, please see our docs https://docs.timescale.com/timescaledb/latest/how-to-guides/configuration/telemetry.

CREATE EXTENSION
s311=# CREATE TABLE conditions(
    time TIMESTAMPTZ NOT NULL,
    device_id INTEGER,
    humidity FLOAT
);
NOTICE:  switching extension state from EXTENSION_STATE_TRANSITIONING to EXTENSION_STATE_UNKNOWN
NOTICE:  switching extension state from EXTENSION_STATE_UNKNOWN to EXTENSION_STATE_CREATED
CREATE TABLE
s311=# SELECT * FROM create_hypertable('conditions', 'time');
 hypertable_id | schema_name | table_name | created 
---------------+-------------+------------+---------
             1 | public      | conditions | t
(1 row)

s311=# INSERT INTO conditions
SELECT time, (random()*3 + 1)::int, random()*100
FROM generate_series(now() - INTERVAL '7 days', now(), '1 hour') AS time;
INSERT 0 169
s311=# CREATE MATERIALIZED VIEW conditions_summary_daily
WITH (timescaledb.continuous) AS
SELECT device_id,
       time_bucket(INTERVAL '1 day', "time") AS bucket,
       AVG(humidity)
FROM conditions
GROUP BY device_id, bucket;
NOTICE:  refreshing continuous aggregate "conditions_summary_daily"
HINT:  Use WITH NO DATA if you do not want to refresh the continuous aggregate on creation.
CREATE MATERIALIZED VIEW
s311=# SELECT count(*) FROM conditions_summary_daily;
 count 
-------
    32
(1 row)
```

Do an `ALTER EXTENSION` in a different session.

```
s311=# SELECT count(*) FROM conditions_summary_daily;
FATAL:  extension has been loaded with another version
DETAIL:  The new version is "2.7.0-dev", this session is using version "2.5.1".
HINT:  The session needs to be restarted.
server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
The connection to the server was lost. Attempting reset: Succeeded.
```

**Review by fabriziomello — APPROVED** [review]

**Comment by mfundul** [comment]
You should also add this to the changelog, right?

**Comment by mkindahl** [comment]
> You should also add this to the changelog, right?

Done.

**Comment by mfundul** [comment]
It looks like there is some logic overlap between this PR and https://github.com/timescale/timescaledb/pull/4193/
I am not sure yet if this changes things.

**Comment by mkindahl** [comment]
> It looks like there is some logic overlap between this PR and #4193 I am not sure yet if this changes things.

It should not. This PR is about checking a reloaded extension, #4193 is about handling invalidations. The invalidation code is in need of a serious rewrite, but that is a separate topic that we intend to address after these immediate issues are fixed.

File: src/loader/loader.c [hunk 2]
```diff
@@ -679,17 +695,8 @@ static void inline do_load()
 	 * here again by the outer call after inval_relcache completes. This is
 	 * double-check locking, in effect.
 	 */
-	if (loaded)
-		return;
-
```
Comment (mfundul) [inline src/loader/loader.c:684]: This comment is made irrelevant by removing:
```
	if (loaded)
		return;
```

Comment (mkindahl) [reply src/loader/loader.c]: Comment removed.

**Comment by mfundul** [comment]
If `extension_check()` is called multiple times then an exception will be generated in `do_load()`, which wasn't the case with the older code. In the old code it was a no-op. Can this be a problem?

**Comment by mfundul** [comment]
> If `extension_check()` is called multiple times then an exception will be generated in `do_load()`, which wasn't the case with the older code. In the old code it was a no-op. Can this be a problem?

Scratch that, I see it's been taken care of.

**Comment by mfundul** [comment]
Final question, do we support different library versions with the same version identifier with `ALTER_EXTENSION`?

E.g.
User has installed Apache version. Then does `ALTER EXTENSION` to reinstall TSL version. In this case the version string would match.

**Comment by mkindahl** [comment]
> Final question, do we support different library versions with the same version identifier with `ALTER_EXTENSION`?
> 
> E.g. User has installed Apache version. Then does `ALTER EXTENSION` to reinstall TSL version. In this case the version string would match.

Not sure what you mean here. If you want to change the license, you set the `timescaledb.licence` to the correct license, which will load the library. Not sure how `ALTER EXTENSION` would be used for this? Could you give an example statement?

**Review by mfundul — APPROVED** [review]

File: src/loader/loader.c [hunk 3]
```diff
@@ -670,26 +671,26 @@ static void inline do_load()
...
-		return;
+	/* If the right version of the library is already loaded, we will just
+	 * skip the actual loading. If the wrong version of the library is loaded,
+	 * we need to kill the session since it will not be able to continue
+	 * operate. */
+	if (*soversion)
+	{
+		if (strcmp(soversion, version) == 0)
+			return;
+		ereport(FATAL,
```
[the remark this answers is not in the document]
Comment (mkindahl) [reply src/loader/loader.c:682]: It is intended to be `FATAL` since it is necessary to restart the session. Do you have a suggestion for a better message?

File: src/loader/loader.c [hunk 4]
```diff
@@ -270,7 +271,7 @@ should_load_on_create_extension(Node *utility_stmt)
 	if (!is_extension)
 		return false;
 
-	if (!loaded)
+	if (!*soversion)
```
[the remark this answers is not in the document]
Comment (erimatnor) [reply src/loader/loader.c:275]: I still think a descriptive function is much better given that this is repeated in several places and there are no comments in the other places, So, I prefer an aptly named function over code comments.

File: src/loader/loader.c [hunk 5]
```diff
@@ -670,26 +672,26 @@ static void inline do_load()
...
+	{
+		if (strcmp(soversion, version) == 0)
+			return;
+		ereport(FATAL,
+				(errcode(ERRCODE_DUPLICATE_OBJECT),
+				 errmsg("extension has been loaded with another version"),
+				 errdetail("The new version is \"%s\", this session is using version \"%s\".",
+						   version,
+						   soversion),
+				 errhint("The session will be restarted.")));
```
Comment (erimatnor) [inline src/loader/loader.c:689]: I think this hint should elided  altogether. A hint is supposed to be a suggestion to the user on how to "fix" or get around and error, it shouldn't provide general information like this. If the logging is FATAL, aborting the session happens in any case and the user will notice so this hint serves no purposet.

File: src/loader/loader.c [hunk 6]
```diff
@@ -670,26 +672,26 @@ static void inline do_load()
...
+	 * skip the actual loading. If the wrong version of the library is loaded,
+	 * we need to kill the session since it will not be able to continue
+	 * operate. */
+	if (*soversion)
+	{
+		if (strcmp(soversion, version) == 0)
+			return;
+		ereport(FATAL,
+				(errcode(ERRCODE_DUPLICATE_OBJECT),
+				 errmsg("extension has been loaded with another version"),
```
Comment (erimatnor) [inline src/loader/loader.c:685]: Should probably say which extension this concerns since it is non-obvious for the user

File: src/loader/loader.c (hunk 4 above)
[the remark this answers is not in the document]
Comment (mkindahl) [reply src/loader/loader.c]: Added function above.

File: src/loader/loader.c (hunk 5 above)
Comment (mkindahl) [reply src/loader/loader.c]: Merged the hint with the detailed message. I think it is informative to understand that the session *need* to be restarted.
