### PR TITLE
Fix retention policy on distributed hypertables

### LINKED ISSUE #2040: Reenable deparsing of drop_chunks in policy job
When running drop chunks policies the drop_chunks call is not automatically deparsed (for distributed hypertables) unless one invokes the user-visible SQL function. Such deparsing was ensured by the function `﻿chunk_invoke_drop_chunks` when called from the background job.

However, the invocation of this function was unintentionally removed by a previous refactor due to issues related to materialized hypertables. In short, `drop_chunks` is blocked on materialized hypertables, but the background job always calls drop_chunks using a hypertable, which is, in case of a cagg, a materialized hypertable.

To solve this issue, and to reenable background jobs for distributed hypertable, on needs to ensure that materialized hypertables as reverse-lookuped back to the cagg relid before invoking `chunk_invoke_drop_chunks`.

### PR DESCRIPTION
**Pull request by mkindahl**
If a retention policy is set up on a distributed hypertable, it will
not propagate the drop chunks call to the data nodes since the drop
chunks call is done through an internal call.

This commit fixes this by creating a drop chunks call internally and
executing it as a function. This will then propagate to the data nodes.

Fixes timescale/timescaledb-private#833
Fixes #2040

### CODE REVIEW

File: tsl/src/chunk.c [hunk 1]
```diff
@@ -218,19 +215,17 @@ chunk_invoke_drop_chunks(Oid relid, Datum older_than, Datum older_than_type)
...
-
 	char *const schema_name = ts_extension_schema_name();
-	char *const function_name = DROP_CHUNKS_FUNCNAME;
 	List *fqn = list_make2(makeString(schema_name), makeString(function_name));
-	funclist = FuncnameGetCandidates(fqn, DROP_CHUNKS_NARGS, NIL, false, false, false);
+	funclist = FuncnameGetCandidates(fqn, lengthof(argarr), NIL, false, false, false);
 
-	if (funclist->next != NULL)
+	if (!funclist || funclist->next != NULL)
 		elog(ERROR, "could not find drop_chunks function");
```
Comment (svenklemm) [inline tsl/src/chunk.c:224]: should use LookupFuncName here

File: src/continuous_agg.c [hunk 2]
```diff
@@ -404,6 +404,38 @@ ts_continuous_aggs_get_minimum_invalidation_time(int64 modification_time,
...
 }
 
+/* Find a continuous aggregate by the materialized hypertable id */
+ContinuousAgg *
+ts_continuous_agg_find_by_mat_hypertable_id(int32 mat_hypertable_id)
+{
+	ContinuousAgg *ca = NULL;
+	ScanIterator iterator =
+		ts_scan_iterator_create(CONTINUOUS_AGG, RowExclusiveLock, CurrentMemoryContext);
+	elog(LOG, "looking for hypertable with id %d", mat_hypertable_id);
```
Comment (svenklemm) [inline src/continuous_agg.c:414]: i guess this is left from debugging

File: tsl/src/chunk.c (hunk 1 above)
Comment (svenklemm) [reply tsl/src/chunk.c:226]: LookupFuncName allows you to pass Oid[] for the args so you dont need to construct Consts which probably allows you to remove 10 lines of code

Comment (mkindahl) [reply tsl/src/chunk.c:226]: Ah, that's what you meant. Sounds useful, will take a look.

Comment (svenklemm) [reply tsl/src/chunk.c:226]: well i guess you still need that for the actual call

Comment (mkindahl) [reply tsl/src/chunk.c:226]: Yes, just realized that.

File: src/continuous_agg.c [hunk 3]
```diff
@@ -404,6 +404,38 @@
...
+	/* Note that this scan can only match at most once */
+	init_scan_by_mat_hypertable_id(&iterator, mat_hypertable_id);
+	ts_scanner_foreach(&iterator)
+	{
+		bool should_free;
+		HeapTuple tuple = ts_scan_iterator_fetch_heap_tuple(&iterator, false, &should_free);
+		Form_continuous_agg form = (Form_continuous_agg) GETSTRUCT(tuple);
+		ca = ts_scan_iterator_alloc_result(&iterator, sizeof(*ca));
+		continuous_agg_init(ca, form);
+		elog(LOG,
```
Comment (erimatnor) [inline src/continuous_agg.c:425]: Shouldn't this be DEBUG or be removed?

File: tsl/test/sql/dist_policy.sql [hunk 4]
```diff
@@ -0,0 +1,73 @@
...
+       ('2017-01-01 06:01', 1, 1.2),
+       ('2017-01-01 09:11', 3, 4.3),
+       ('2017-01-01 08:01', 1, 7.3),
+       ('2017-01-02 08:01', 2, 0.23),
+       ('2018-07-02 08:01', 87, 0.0),
+       ('2018-07-01 06:01', 13, 3.1),
+       ('2018-07-01 09:11', 90, 10303.12),
+       ('2018-07-01 08:01', 29, 64);
+
+SELECT add_retention_policy('disttable', INTERVAL '4 months', true) as drop_chunks_job_id \gset
```
Comment (erimatnor) [inline tsl/test/sql/dist_policy.sql:48]: I guess a dist table cannot have a continuous aggregate (don't recall if we yet block this case)? Otherwise it would be good ro test a  policy on a continuous aggregate, even if this isn't supported yet for multinode.

File: tsl/test/expected/dist_policy.out [hunk 5]
```diff
@@ -0,0 +1,100 @@
...
+ 
+(1 row)
+
+SELECT count(*)
+  FROM _timescaledb_catalog.chunk AS c
+     , _timescaledb_catalog.hypertable AS ht
+ WHERE c.hypertable_id = ht.id AND ht.table_name = 'disttable';
+ count 
+-------
+     0
```
Comment (erimatnor) [inline tsl/test/expected/dist_policy.out:83]: I suggest a test case when som chunks are left after drop chunks. A retention policy  typically doesn't drop all data.

File: tsl/test/expected/dist_policy.out [hunk 6]
```diff
@@ -0,0 +1,100 @@
...
+(1 row)
+
+-- Now simulate drop_chunks running automatically by calling it explicitly
+SELECT test_drop_chunks(:drop_chunks_job_id);
+ test_drop_chunks 
+------------------
+ 
+(1 row)
+
+SELECT count(*)
```
Comment (erimatnor) [inline tsl/test/expected/dist_policy.out:77]: Would like to see that the chunks were actually dropped on the data nodes.

File: tsl/test/expected/dist_policy.out [hunk 7]
```diff
@@ -0,0 +1,100 @@
...
+       ('2017-01-01 06:01', 1, 1.2),
+       ('2017-01-01 09:11', 3, 4.3),
+       ('2017-01-01 08:01', 1, 7.3),
+       ('2017-01-02 08:01', 2, 0.23),
+       ('2018-07-02 08:01', 87, 0.0),
+       ('2018-07-01 06:01', 13, 3.1),
+       ('2018-07-01 09:11', 90, 10303.12),
+       ('2018-07-01 08:01', 29, 64);
+SELECT add_retention_policy('disttable', INTERVAL '4 months', true) as drop_chunks_job_id \gset
+SELECT count(*)
```
Comment (erimatnor) [inline tsl/test/expected/dist_policy.out:61]: Can you use show_chunks here instead of a custom query?

File: tsl/src/chunk.c (hunk 1 above)
Comment (svenklemm) [reply tsl/src/chunk.c:226]: hmmm i would still prefer LookupFuncName here cause that would validate argument datatypes

File: tsl/test/expected/dist_policy.out [hunk 8]
```diff
@@ -0,0 +1,100 @@
...
+-- Need to be super user to create extension and add data nodes
+\c :TEST_DBNAME :ROLE_CLUSTER_SUPERUSER;
+CREATE OR REPLACE FUNCTION test_drop_chunks(job_id INTEGER)
+RETURNS VOID
+AS :TSL_MODULE_PATHNAME, 'ts_test_auto_drop_chunks'
+LANGUAGE C VOLATILE STRICT;
+-- Cleanup from other potential tests. This avoid additional notice
+-- messages when adding data nodes.
+SET client_min_messages TO ERROR;
+DROP DATABASE IF EXISTS data_node_1;
```
Comment (svenklemm) [inline tsl/test/expected/dist_policy.out:13]: why are you dropping databases here? this guarantees this is not gonna play well with other tests, you should drop databases you create at end of you script and choose a database name that does not conflict with existing scripts

File: tsl/src/chunk.c [hunk 9]
```diff
@@ -200,7 +197,7 @@ chunk_invoke_drop_chunks(Oid relid, Datum older_than, Datum older_than_type)
 	int i, num_results = 0;
 	SetExprState *state;
 	Oid restype;
-	Const *argarr[DROP_CHUNKS_NARGS] = {
+	Const *argarr[] = {
```
Comment (gayyappan) [inline tsl/src/chunk.c:200]: Could you keep this as DROP_CHUNKS_NARGS? Using  DROP_CHUNKS_NARGS is explicit, the correct number of elts are initialized and additionally is self documenting as it doesn't need looking through the code to find out what is going on.

File: tsl/src/chunk.c [hunk 10]
```diff
@@ -192,6 +188,7 @@ chunk_set_default_data_node(PG_FUNCTION_ARGS)
 int
 chunk_invoke_drop_chunks(Oid relid, Datum older_than, Datum older_than_type)
 {
+	char *const function_name = "drop_chunks";
```
Comment (gayyappan) [inline tsl/src/chunk.c:191]: Could you please retain DROP_CHUNKS_FUNCNAME macro?

File: tsl/src/chunk.c (hunk 1 above)
Comment (gayyappan) [reply tsl/src/chunk.c:226]: I second using LookupFuncName

File: tsl/test/expected/dist_policy.out (hunk 8 above)
Comment (gayyappan) [reply tsl/test/expected/dist_policy.out:13]: Yes,  I ran into CI issues with similar named data nodes that would fail intermittently and took a while to figure out what was going on. Suggest unique data node name for the test.

File: tsl/test/expected/dist_policy.out (hunk 6 above)
Comment (gayyappan) [reply tsl/test/expected/dist_policy.out:77]: You could use chunks_detailed_size to see the distribution on the nodes.

File: tsl/src/chunk.c (hunk 9 above)
Comment (gayyappan) [reply tsl/src/chunk.c:201]: I disagree with that. The number of args should be explicitly specified when creating the array. It is a programming error if the number of args don't match the array specification. It it actually easier to find the programming error when you explicitly specify the number of args and see a mismatch. Are you saying that DROP_CHUNKS_NARGS is incorrect and needs modification?

File: tsl/src/chunk.c (hunk 10 above)
Comment (gayyappan) [reply tsl/src/chunk.c:192]: This is  more a stylistic than correctness. Our code base uses macros for string constants (a standard practice for numeric and string constants in C). The original code actually has it and here you are undoing that.

File: tsl/src/chunk.c (hunk 9 above)
Comment (mkindahl) [reply tsl/src/chunk.c:201]: It was incorrect, yes. The point is that we want to either capture problems at compile-time, or avoid the problem if we cannot. Could you explain why you think it is important to both see the number of arguments explicitly in the array declaration as well as in the array initializer?

Comment (mkindahl) [reply tsl/src/chunk.c]: Never mind, I restored the constant names.

File: src/continuous_agg.c [hunk 11]
```diff
@@ -404,6 +404,33 @@ ts_continuous_aggs_get_minimum_invalidation_time(int64 modification_time,
...
 
+/* Find a continuous aggregate by the materialized hypertable id */
+ContinuousAgg *
+ts_continuous_agg_find_by_mat_hypertable_id(int32 mat_hypertable_id)
+{
+	ContinuousAgg *ca = NULL;
+	ScanIterator iterator =
+		ts_scan_iterator_create(CONTINUOUS_AGG, RowExclusiveLock, CurrentMemoryContext);
+
+	/* Note that this scan can only match at most once */
```
Comment (k-rus) [inline src/continuous_agg.c:415]: Is it good to put it into assertion instead of the comment?

Comment (k-rus) [reply src/continuous_agg.c:415]: I guess the assert will be on `ca == NULL`

File: src/continuous_agg.c [hunk 12]
```diff
@@ -404,6 +404,33 @@ ts_continuous_aggs_get_minimum_invalidation_time(int64 modification_time,
...
+	init_scan_by_mat_hypertable_id(&iterator, mat_hypertable_id);
+	ts_scanner_foreach(&iterator)
+	{
+		bool should_free;
+		HeapTuple tuple = ts_scan_iterator_fetch_heap_tuple(&iterator, false, &should_free);
+		Form_continuous_agg form = (Form_continuous_agg) GETSTRUCT(tuple);
+		ca = ts_scan_iterator_alloc_result(&iterator, sizeof(*ca));
```
Comment (k-rus) [inline src/continuous_agg.c:422]: It's nice to separate declaration bock from the body for readability:
```suggestion

		ca = ts_scan_iterator_alloc_result(&iterator, sizeof(*ca));
```

File: tsl/src/bgw_policy/job.c [hunk 13]
```diff
@@ -304,26 +303,29 @@ policy_retention_execute(int32 job_id, Jsonb *config)
...
-									  InvalidOid,
-									  boundary_type,
-									  InvalidOid,
-									  DEBUG2,
-									  NULL);
-	num_dropped = list_length(dc_temp);
-	ts_cache_release(hcache);
+	/* We need to do a reverse lookup here since we might have the
+	   materialized hypertable and need to call drop_chunks with the
+	   continuous aggregate if that is the case. */
```
Comment (k-rus) [inline tsl/src/bgw_policy/job.c:317]: It took me awhile to understand the comment. Here is my suggestion if it improves:
```suggestion
	/* We need to do a reverse lookup here since the given hypertable
	   might be a materialized hypertable, and thus need to call drop_chunks
	    on the continuous aggregate instead. */
```

File: tsl/test/expected/dist_policy.out [hunk 14]
```diff
@@ -0,0 +1,161 @@
...
+-- Please see the included NOTICE for copyright information and
+-- LICENSE-TIMESCALE for a copy of the license.
+-- Need to be super user to create extension and add data nodes
+\c :TEST_DBNAME :ROLE_CLUSTER_SUPERUSER;
+\unset ECHO
+psql:include/remote_exec.sql:5: NOTICE:  schema "test" already exists, skipping
+CREATE OR REPLACE FUNCTION test_drop_chunks(job_id INTEGER)
+RETURNS VOID
+AS :TSL_MODULE_PATHNAME, 'ts_test_auto_drop_chunks'
+LANGUAGE C VOLATILE STRICT;
```
Comment (k-rus) [inline tsl/test/expected/dist_policy.out:11]: @svenklemm You commented previously to use new API instead of such functions: https://github.com/timescale/timescaledb/pull/2192#pullrequestreview-461552940
Is it something to consider here for @mkindahl ?

File: tsl/test/expected/dist_policy.out [hunk 15]
```diff
@@ -0,0 +1,161 @@
...
+node_name         | dist_policy_data_node_3
+host              | localhost
+port              | 55432
+database          | dist_policy_data_node_3
+node_created      | t
+database_created  | t
+extension_created | t
+
+\x off
+GRANT USAGE ON FOREIGN SERVER dist_policy_data_node_1, dist_policy_data_node_2, dist_policy_data_node_3 TO PUBLIC;
```
Comment (k-rus) [inline tsl/test/expected/dist_policy.out:48]: It's good time to change role from superuser to a user after this granting, e.g.:
```suggestion
GRANT USAGE ON FOREIGN SERVER dist_policy_data_node_1, dist_policy_data_node_2, dist_policy_data_node_3 TO PUBLIC;
SET ROLE :ROLE_1;
```

File: tsl/test/expected/dist_policy.out [hunk 16]
```diff
@@ -0,0 +1,161 @@
...
+);
+SELECT * FROM create_distributed_hypertable('conditions', 'time', 'device', 3);
+ hypertable_id | schema_name | table_name | created 
+---------------+-------------+------------+---------
+             1 | public      | conditions | t
+(1 row)
+
+INSERT INTO conditions
+SELECT time, device, random()*80
+FROM generate_series(NOW() - INTERVAL '4 weeks', NOW(), '8 hours') AS time,
```
Comment (k-rus) [inline tsl/test/expected/dist_policy.out:62]: This will generate different chunks depending on the time when the test is executed.

Comment (mkindahl) [reply tsl/test/expected/dist_policy.out:62]: It should not, since they are spaced exactly 8 hours apart. Do you have an alternative suggestion?

File: tsl/test/expected/dist_policy.out (hunk 14 above)
Comment (svenklemm) [reply tsl/test/expected/dist_policy.out:11]: atm it requires a bit effort because calling the procedure directly requires you to have the config jsonb object so i'm fine leaving it like that for now but once we have `run_job` all those `ts_test_auto_' helper functions for policies will be removed

File: tsl/test/expected/dist_policy.out (hunk 16 above)
Comment (k-rus) [reply tsl/test/expected/dist_policy.out:63]: Don't use `now()`, but use a constant value. 
I don't see how 8 hours interval in data can make it deterministic with default chunk interval of 1 week. Each chunks start at a constant time and interval independently of the first data time.

File: tsl/test/expected/dist_policy.out (hunk 14 above)
Comment (k-rus) [reply tsl/test/expected/dist_policy.out:11]: @svenklemm Thank you for clarifying!

File: tsl/test/expected/dist_policy.out (hunk 16 above)
Comment (mkindahl) [reply tsl/test/expected/dist_policy.out:63]: I don't see how I can get the background thread to process the policy correctly without using `now()`.

Comment (k-rus) [reply tsl/test/expected/dist_policy.out:63]: I think you can check existing bgw test, e.g., `compression_bgw.sql` tests policies without using `now()`.

Comment (k-rus) [reply tsl/test/expected/dist_policy.out:63]: Another approach to do point inserts where each chunk contains only one row, then `now()` can be used. There are such examples too.

Comment (mkindahl) [reply tsl/test/expected/dist_policy.out]: Created code that inserts one row in each chunk, but still using `now()`.

File: tsl/test/expected/dist_policy.out [hunk 17]
```diff
@@ -0,0 +1,163 @@
...
+SELECT * FROM create_distributed_hypertable('conditions', 'time', 'device', 3,
+       chunk_time_interval => INTERVAL '1 week');
+ hypertable_id | schema_name | table_name | created 
+---------------+-------------+------------+---------
+             1 | public      | conditions | t
+(1 row)
+
+INSERT INTO conditions
+SELECT time, device, random()*80
+FROM generate_series(NOW() - INTERVAL '4 weeks', NOW(), '1 week') AS time,
```
Comment (svenklemm) [inline tsl/test/expected/dist_policy.out:64]: using now like that will produce flaky test

Comment (erimatnor) [reply tsl/test/expected/dist_policy.out:64]: yes, this can produce different number of chunks and different chunk names depending on when you run the test.

File: tsl/test/expected/dist_policy.out [hunk 18]
```diff
@@ -0,0 +1,163 @@
...
+ 
+(1 row)
+
+SELECT remove_retention_policy('conditions');
+ remove_retention_policy 
+-------------------------
+ 
+(1 row)
+
+INSERT INTO conditions
```
Comment (erimatnor) [inline tsl/test/expected/dist_policy.out:160]: Is this maybe here by mistake? I don't see what the purpose of this INSERT would be.

File: tsl/test/expected/dist_policy.out [hunk 19]
```diff
@@ -0,0 +1,163 @@
...
+SELECT time, device, random()*80
+FROM generate_series(NOW() - INTERVAL '4 weeks', NOW(), '1 week') AS time,
+     generate_series(1,3) AS device
+ORDER BY time, device;
+SELECT add_retention_policy('conditions', INTERVAL '2 weeks', true) as drop_chunks_job_id \gset
+-- Now simulate drop_chunks running automatically by calling it
+-- explicitly. Show chunks before and after.
+SELECT * FROM test.remote_exec(NULL, $$ SELECT show_chunks('conditions'); $$);
```
Comment (erimatnor) [inline tsl/test/expected/dist_policy.out:70]: Would be good to do `show_chunks` also the AN to see that its chunks line up with the chunks on the data node

File: tsl/test/expected/dist_policy.out (hunk 18 above)
Comment (mkindahl) [reply tsl/test/expected/dist_policy.out:160]: If you look at the bug report, there is an error when trying to insert after removing the retention policy, which is what we test that it works here.

File: tsl/test/expected/dist_policy.out (hunk 17 above)
Comment (mkindahl) [reply tsl/test/expected/dist_policy.out:64]: It is used in a number of other tests. In addition, I do not understand how it can produce a flaky test. It creates one row for each chunk spaced exactly 1 week apart, which is the same as the chunk interval size. This should be able to place more than one row in a chunk.

File: tsl/test/expected/dist_policy.out (hunk 19 above)
Comment (k-rus) [reply tsl/test/expected/dist_policy.out:70]: I second this request.

File: tsl/test/sql/dist_policy.sql [hunk 20]
```diff
@@ -0,0 +1,59 @@
...
+
+-- Add data nodes
+\x on
+SELECT * FROM add_data_node('dist_policy_data_node_1', host => 'localhost',
+                            database => 'dist_policy_data_node_1');
+SELECT * FROM add_data_node('dist_policy_data_node_2', host => 'localhost',
+                            database => 'dist_policy_data_node_2');
+SELECT * FROM add_data_node('dist_policy_data_node_3', host => 'localhost',
+                            database => 'dist_policy_data_node_3');
+\x off
```
Comment (k-rus) [inline tsl/test/sql/dist_policy.sql:27]: What is the reason for the expanded output? I would even prefer to silence output completely as this test is not testing `add_data_node`.

File: tsl/test/sql/dist_policy.sql [hunk 21]
```diff
@@ -0,0 +1,59 @@
...
+-- Need to be super user to create extension and add data nodes
+\c :TEST_DBNAME :ROLE_CLUSTER_SUPERUSER;
+
+\unset ECHO
+\o /dev/null
+\ir include/remote_exec.sql
+\o
+\set ECHO all
+
+CREATE OR REPLACE FUNCTION test_drop_chunks(job_id INTEGER)
```
Comment (k-rus) [inline tsl/test/sql/dist_policy.sql:14]: This name is confusing, since policy was renamed and it tests the retention policy:
```suggestion
CREATE OR REPLACE FUNCTION test_retention(job_id INTEGER)
```

File: tsl/test/expected/dist_policy.out (hunk 17 above)
Comment (mkindahl) [reply tsl/test/expected/dist_policy.out]: Switched to integer-based time.

File: tsl/test/sql/dist_policy.sql (hunk 20 above)
Comment (mkindahl) [reply tsl/test/sql/dist_policy.sql:27]: It does not harm and it shows that the execution proceeded as expected. If there is a failure in these functions, it will cascade to other failures in the test and then it is good to know that the `add_data_node` failure is the reason.

File: tsl/test/expected/dist_policy.out (hunk 18 above)
Comment (erimatnor) [reply tsl/test/expected/dist_policy.out:311]: Ok, appreciate the extra comment with explanation
