### PR TITLE
Restart scheduler on error

### LINKED ISSUE #5091: [Bug]: Automatically restart background worker scheduler
### What type of bug is this?

Other

### What subsystems and features are affected?

Background worker

### What happened?

If the scheduler exits for any reason, no more workers will be scheduled since the scheduler do not restart automatically.

This is because the scheduler is started with `BGW_NEVER_RESTART` as restart time.

### TimescaleDB version affected

2.9.0

### PostgreSQL version used

14.3

### What operating system did you use?

Ubuntu 22.04 x86_64

### What installation method did you use?

Source

### What platform did you run on?

Not applicable

### Relevant log output and stack trace

_No response_

### How can we reproduce the bug?

Wait for the scheduler to exit with an error. This can be triggered creating duplicate job entries in the bgw_job table, for example.

### PR DESCRIPTION
**Pull request by mkindahl**
If the scheduler receives an error, it will never restart again since `bgw_restart_time` is set to `BGW_NEVER_RESTART`, which will prevent all jobs from executing.

This commit fixes the issue by adding a GUC that can be set to the restart time for the scheduler, and set the default to 30 seconds. It also adds some additional variables to be able to shutdown the scheduler with a non-zero exit code, which allows the restart functionality to be tested.

Fixes #5091

### CODE REVIEW

File: src/loader/bgw_launcher.c [hunk 1]
```diff
@@ -84,6 +84,8 @@ typedef enum SchedulerState
 
 static volatile sig_atomic_t got_SIGHUP = false;
 
+int ts_guc_bgw_scheduler_restart_time = 30;
```
Comment (jnidzwetzki) [inline src/loader/bgw_launcher.c:87]: I assume these are seconds, but it might be good to add a comment about the dimension of this variable.

File: src/loader/bgw_launcher.c [hunk 2]
```diff
@@ -238,10 +240,24 @@ terminate_background_worker(BackgroundWorkerHandle *handle)
 }
 
 extern void
-ts_bgw_cluster_launcher_register(void)
+ts_bgw_cluster_launcher_init(void)
 {
 	BackgroundWorker worker;
 
+	DefineCustomIntVariable(/* name= */ "timescaledb.bgw_scheduler_restart_time",
+							/* short_desc= */ "restart time for scheduler in seconds",
```
Comment (jnidzwetzki) [inline src/loader/bgw_launcher.c:248]: Nit:
```suggestion
							/* short_desc= */ "Restart time for scheduler in seconds",
```

**Review by jnidzwetzki — APPROVED** [review]

**Comment by jnidzwetzki** [comment]
@mkindahl 

Have you seen the `bgw_scheduler_control` regression check return an error code when invoked multiple times?

```
test bgw_scheduler_control        ... ok        50458 ms
test bgw_scheduler_control        ... FAILED (test process exited with exit code 1)     5048 ms
```

**Comment by mkindahl** [comment]
> > @mkindahl
> > Have you seen the `bgw_scheduler_control` regression check return an error code when invoked multiple times?
> > ```
> > test bgw_scheduler_control        ... ok        50458 ms
> > test bgw_scheduler_control        ... FAILED (test process exited with exit code 1)     5048 ms
> > ```
> 
> Hmm... I though I'd fixed it.
> 
> Managed to fix it locally: let's see if it works now.

For some reason. `stop_background_workers` were not taking effect, so switched to using `pg_terminate_backend`. It seems `stop_background_workers` is killing a scheduler for a different database. Not sure why, but that looks like a bug that is unrelated to this pull request.

**Review by svenklemm — APPROVED** [review]
