### PR TITLE
Propagate privileges from hypertables to chunks

### LINKED ISSUE #1927: ERROR:  permission denied for table _hyper_1_12_chunk
Hello,

Using
 - OS: [Ubuntu 16.04]
 - PostgreSQL version (11.5)
 - TimescaleDB version (1.6.0~ubuntu16.04)

I cannot find a section in the official docs about permission handling with hypertables.

I have created hypertable in Postgres and trying to take a dump of all tables using pg_dump command having back_user with select permission.

Now whenever new table _hyper_1_xx_chunk created, pg_dump command throws an error `permission denied for table _hyper_1_13_chunk`.

After I give permission manually `grant select on all tables in schema _timescaledb_internal to back_user` pg_dump command runs successfully.

How can I fix this issue? Is there a way to apply permission automatically whenever a new _hyper_1_xx_chunk file create?

Because of this issue we were not able to take db dump daily.

Thanks.
Nishit Shah

### PR DESCRIPTION
**Pull request by mkindahl**
Whenever chunks are created, no privileges are added to the chunks.
For accesses that go through the hypertable permission checks are
ignored so reads and writes will succeed anyway. However, for direct
accesses to the chunks, permission checks are done, which creates
problems for, e.g., `pg_dump`.

This commit fixes this by propagating `GRANT` and `REVOKE` statements
to the chunks when executed on the hypertable, and whenever new chunks
are created, privileges are copied from the hypertable.

Fixes #1927

### CODE REVIEW

**Comment by svenklemm** [comment]
Can you add tests that grant/revoke on individual chunks still works

File: src/chunk.c [hunk 1]
```diff
@@ -737,6 +788,9 @@ ts_chunk_create_table(Chunk *chunk, Hypertable *ht, const char *tablespacename)
 		 */
 		create_toast_table(&stmt.base, objaddr.objectId);
```
Comment (gayyappan) [inline src/chunk.c:789]: does toast table need the right ACLs as well?

File: test/sql/grant_hypertable.sql [hunk 2]
```diff
@@ -0,0 +1,45 @@
...
+\z conditions
+\z _timescaledb_internal.*chunk
+
+-- Revoke one of the privileges and show that it propagate to the
+-- chunks.
+REVOKE INSERT ON conditions FROM PUBLIC;
+\z conditions
+\z _timescaledb_internal.*chunk
+
+-- Add some more chunks and show that it inherits the grants from the
```
Comment (gayyappan) [inline test/sql/grant_hypertable.sql:39]: also need a test that shows that a user (non super user) can SELECT but not insert.  The tests have additional roles DEFAULT_PERM_USER that can be used for this .

Comment (mkindahl) [reply test/sql/grant_hypertable.sql:39]: It seems redundant. The current list shows that permissions are propagated correctly and adding select tests would just check that the permissions support actually works. I think these tests are about testing that permissions are propagated, not testing that permissions are correctly implemented in PostgreSQL.

File: src/chunk.c (hunk 1 above)
Comment (mkindahl) [reply src/chunk.c:789]: Good point, will check.

Comment (mkindahl) [reply src/chunk.c:789]: Doesn't seem like this is necessary. The ACLs to toast tables are always NULL and any permission checking done is done on the "real" table, not the toast table.

Here is from `create_toast_table`:

```c
	toast_relid = heap_create_with_catalog(toast_relname,
										   namespaceid,
										   rel->rd_rel->reltablespace,
										   toastOid,
										   toast_typid,
										   InvalidOid,
										   rel->rd_rel->relowner,
										   rel->rd_rel->relam,
										   tupdesc,
										   NIL,
										   RELKIND_TOASTVALUE,
										   rel->rd_rel->relpersistence,
										   shared_relation,
										   mapped_relation,
										   ONCOMMIT_NOOP,
										   reloptions,
										   false,      /* NOTE[mats]: use_user_acl */
										   true,
										   true,
										   InvalidOid,
										   NULL);
```

Docs for `use_user_acl`:

```
 *	use_user_acl: true if should look for user-defined default permissions;
 *		if false, relacl is always set NULL
```

The `toastOid` passed in is `InvalidOid` (which means "create a new OID") when used from `NewHeapCreateToastTable`, which is what we are calling here.

In addition, `ExecGrant_Relation` (which is the implementation of the grant statement for relations) does not recurse to TOAST tables for changing grants (even though the relid for the toast table is available), which suggest that they are not used.

**Comment by mkindahl** [comment]
> Can you add tests that grant/revoke on individual chunks still works

Done.

File: src/chunk.c [hunk 3]
```diff
@@ -657,6 +657,54 @@ get_am_name_for_rel(Oid relid)
...
+	/* We only bother about setting the chunk ACL if the hypertable ACL is
+	 * non-null */
+	acl_datum = SysCacheGetAttr(RELOID, ht_tuple, Anum_pg_class_relacl, &is_null);
+	if (!is_null)
+	{
+		HeapTuple chunk_tuple, newtuple;
+		Datum new_val[Natts_pg_class] = { 0 };
+		bool new_null[Natts_pg_class] = { false };
+		bool new_repl[Natts_pg_class] = { false };
+		Acl *acl = DatumGetAclPCopy(acl_datum);
```
Comment (erimatnor) [inline src/chunk.c:684]: Why do we need a copy here? Should it be freed given that this could accumulate memory on the insert path?

File: test/expected/grant_hypertable.out [hunk 4]
```diff
@@ -0,0 +1,172 @@
...
+
+REVOKE SELECT ON _timescaledb_internal._hyper_1_1_chunk FROM PUBLIC;
+\z _timescaledb_internal._hyper_1_1_chunk
+                                                Access privileges
+        Schema         |       Name       | Type  |       Access privileges       | Column privileges | Policies 
+-----------------------+------------------+-------+-------------------------------+-------------------+----------
+ _timescaledb_internal | _hyper_1_1_chunk | table | super_user=arwdDxt/super_user+|                   | 
+                       |                  |       | =w/super_user                 |                   | 
+(1 row)
+
```
Comment (WireBaron) [inline test/expected/grant_hypertable.out:172]: From this morning, it seems like the one thing missing here is testing whether changing the permissions on the hypertable overwrites the new chunk permissions.

**Comment by mkindahl** [comment]
> Can you add 2 more test:
> 
>     * grant chunk something not yet on hypertable, add to hypertable and revoke from hypertable -> extra grant should still be on chunk

That cannot reasonably work. How can we distinguish how grants are added to the chunk. 

So, if we add `SELECT` to chunk, and then add `SELECT` on hypertable and revoke it again on hypertable, we cannot distinguish how it was added in the first place, not without starting to keep our own privileges for chunks, which is possible but definitely out of scope for this PR.

>     * revoke a permission from chunk it got through propagation, add and revoke something else from hypertable -> permission revoked from first step should still not be on chunk

Done.

**Comment by svenklemm** [comment]
The thing to add to the hypertable is different from the thing you add to chunk, just want a test that a chunk can have additional permissions 
 grant chunk something not yet on hypertable, add something else to hypertable and revoke something else from hypertable -> extra grant should still be on chunk

**Comment by mkindahl** [comment]
> The thing to add to the hypertable is different from the thing you add to chunk, just want a test that a chunk can have additional permissions
> grant chunk something not yet on hypertable, add something else to hypertable and revoke something else from hypertable -> extra grant should still be on chunk

Ah, that should work. Sort of the reverse of the second one.

File: src/chunk.c (hunk 3 above)
Comment (mkindahl) [reply src/chunk.c:684]: Right, we don't need a copy. Remains from the first code draft. Removed.

**Comment by mkindahl** [comment]
> > The thing to add to the hypertable is different from the thing you add to chunk, just want a test that a chunk can have additional permissions
> > grant chunk something not yet on hypertable, add something else to hypertable and revoke something else from hypertable -> extra grant should still be on chunk
> 
> Ah, that should work. Sort of the reverse of the second one.

Added.

File: test/expected/grant_hypertable.out (hunk 4 above)
Comment (mkindahl) [reply test/expected/grant_hypertable.out:172]: There are a few checks for that added. Please have a look.

**Comment by svenklemm** [comment]
there is a file missing in your PR

**Comment by mkindahl** [comment]
> there is a file missing in your PR

Added.

**Comment by svenklemm** [comment]
Seems like this PR does not propagate column privileges, is this deliberate?

**Comment by mkindahl** [comment]
> Seems like this PR does not propagate column privileges, is this deliberate?

It was deliberate, yes.

The main reason for this issue is that it should be possible to run `pg_dump` with default database privileges set or when privileges are added to a hypertable, not to be able to handle more advanced usage where you can provide privileges to read specific columns directly from a chunk. Most normal access should be through the hypertable.

**Comment by ClaytonJY** [comment]
This can be especially nasty if you removed a role with chunk permissions before this bug was fixed; the chunks will retain permissions from nameless roles identified by their former `uid`, which will cause tools like `pg_upgrade` to fail since it can't grant those permissions in the new instance.

I was bit by this on Timescale Cloud, and after working with their support team, the only solution we came up with was to drop those chunks and re-insert the data into the hypertable. This can be done with a transaction for each chunk by copying the data to a temp table before dropping the chunk; this lets concurrent queries always see complete data.
