### PR TITLE
Restart scheduler on error

### LINKED ISSUE #5091: [Bug]: Automatically restart background worker scheduler
### What type of bug is this?

Other

### What subsystems and features are affected?

Background worker

### What happened?

If the scheduler exits for any reason, no more workers will be scheduled since the scheduler do not restart automatically.

This is because the scheduler is started with `BGW_NEVER_RESTART` as restart time.

### TimescaleDB version affected

2.9.0

### PostgreSQL version used

14.3

### What operating system did you use?

Ubuntu 22.04 x86_64

### What installation method did you use?

Source

### What platform did you run on?

Not applicable

### Relevant log output and stack trace

_No response_

### How can we reproduce the bug?

Wait for the scheduler to exit with an error. This can be triggered creating duplicate job entries in the bgw_job table, for example.

### PR DESCRIPTION
**Pull request by mkindahl**
If the scheduler receives an error, it will never restart again since `bgw_restart_time` is set to `BGW_NEVER_RESTART`, which will prevent all jobs from executing.

This commit adds the GUC `timescaledb.bgw_scheduler_restart_time` that can be set to the restart time for the scheduler. It defaults to 60 seconds, which is the default restart interval for background workers PostgreSQL defines.

It also adds `timescaledb.debug_bgw_scheduler_exit_status` to be able to shutdown the scheduler with a non-zero exit status, which allows the restart functionality to be tested.

It also ensures that `backend_type` is explicitly set up rather than  copied from `application_name` and add some more information to `application_name`. It also updates the tests to use `backend_type` where applicable.

Disable-check: loader-change

### CODE REVIEW

**Comment by mkindahl** [comment]
Compared to #6195 this adds code to the start of the launcher that correct the status for any schedulers that have slots and hence will restart eventually. Reproducing it in a test is difficult because of how the schedulers are used in tests, but this short script demonstrates the issue:

```sql
create view tsdb_bgw as
       select datname, pid, backend_type, application_name from pg_stat_activity
       where backend_type like '%TimescaleDB%';

alter system set timescaledb.debug_bgw_scheduler_exit_status to 1;
alter system set timescaledb.bgw_scheduler_restart_time to 10;
select pg_reload_conf();

-- Kill the schedulers
select pid, pg_terminate_backend(pid) from pg_stat_activity where backend_type like '%Scheduler%';
select pg_sleep(1);
select datname, backend_type, count(*) from tsdb_bgw group by datname, backend_type;

-- Wait for the schedulers to restart.
select pg_sleep(10);
select datname, backend_type, count(*) from tsdb_bgw group by datname, backend_type;

-- Kill the launcher, it should restart immediately.
select pid, pg_terminate_backend(pid) from pg_stat_activity where backend_type like '%Launcher%';
select pg_sleep(1);

-- This should only show one scheduler for each database.
select datname, backend_type, count(*) from tsdb_bgw group by datname, backend_type;
```

**Review by akuzm — APPROVED** [review]

File: src/guc.c [hunk 1]
```diff
@@ -1067,6 +1081,19 @@ _guc_init(void)
 							 /* assign_hook= */ NULL,
 							 /* show_hook= */ NULL);
 
+	DefineCustomIntVariable(/* name= */ MAKE_EXTOPTION("debug_bgw_scheduler_exit_status"),
```
Comment (erimatnor) [inline src/guc.c:1084]: Nit: you don't need to expose full GUCs to achieve this debug functionality.  You can just check for a settings variable. Then the code can also be localized to where it is needed.

File: src/guc.c [hunk 2]
```diff
@@ -183,6 +183,20 @@ bool ts_guc_debug_require_batch_sorted_merge = false;
...
+ * Normally it exits with a zero which means that it will not restart. If an
+ * error is raised, it exits with error code 1, which will trigger a
+ * restart.
+ *
+ * This variable exists to be able to trigger a restart for a normal exit,
+ * which is useful when debugging.
+ *
+ * See backend/postmaster/bgworker.c
+ */
+int ts_debug_bgw_scheduler_exit_status = 0;
```
Comment (erimatnor) [inline src/guc.c:198]: Shouldn't this also be define in debug builds only, like the GUG itself?

File: src/loader/bgw_launcher.c [hunk 3]
```diff
@@ -332,15 +349,89 @@ db_hash_entry_create_if_not_exists(HTAB *db_htab, Oid db_oid)
...
+
+/*
+ * Terminate a background worker.
+ *
+ * This is copied from pg_signal_backend() in
+ * src/backend/storage/ipc/signalfuncs.c but tweaked to not require a database
+ * connection since the launcher does not have one.
+ */
+static enum SignalBackendResult
+ts_signal_backend(int pid, int sig)
```
Comment (erimatnor) [inline src/loader/bgw_launcher.c:373]: Is it possible to get this code to run in a test?

File: tsl/test/expected/bgw_scheduler_restart.out [hunk 4]
```diff
@@ -0,0 +1,85 @@
...
+
+ALTER SYSTEM RESET timescaledb.shutdown_bgw_scheduler;
+ALTER SYSTEM RESET timescaledb.debug_bgw_scheduler_exit_status;
+SELECT pg_reload_conf();
+ pg_reload_conf 
+----------------
+ t
+(1 row)
+
+SELECT pg_sleep(60);		-- Wait for scheduler to restart.
```
Comment (erimatnor) [inline tsl/test/expected/bgw_scheduler_restart.out:64]: These sleeps seem to add 80 seconds (1+ minute) to the test suite. That is quite a lot for one test. Also, sleeps for synchronization is inherently flaky so it would be good to come up with a solution where the processes could synchronize, e.g., around a lock or similar? 

Is there maybe a way you can wait on a pid?

Comment (erimatnor) [reply tsl/test/expected/bgw_scheduler_restart.out:64]: Internally there's at least `WaitForBackgroundWorkerStartup` and `WaitForBackgroundWorkerShutdown`. Can't we expose them via SQL functions to avoid sleeping?

File: src/loader/bgw_launcher.c (hunk 3 above)
Comment (mkindahl) [reply src/loader/bgw_launcher.c:373]: Not easily, no. It is just a copy of the `pg_signal_backend` code so it does not seems worth it to add a test for it.

Comment (erimatnor) [reply src/loader/bgw_launcher.c:373]: I am not so worried about this code being incorrect. But if it is never executed, there seems to be other paths calling this that are never executed either.

Comment (mkindahl) [reply src/loader/bgw_launcher.c:373]: I managed to extend the test to cover the situation described in the comment. Not running it as a flake test since it has a high risk of interfering with other tests and also setting the restart time to 10 seconds rather than the default 60 seconds.

File: src/guc.c (hunk 2 above)
Comment (mkindahl) [reply src/guc.c:198]: Made the variable generally available, since it is useful for debugging production systems.

File: tsl/test/expected/bgw_scheduler_restart.out (hunk 4 above)
Comment (mkindahl) [reply tsl/test/expected/bgw_scheduler_restart.out]: Using shorter restart times and also not running the tests as part of the flaky tests.

File: tsl/test/expected/bgw_scheduler_restart.out [hunk 5]
```diff
@@ -0,0 +1,174 @@
...
+ t
+(1 row)
+
+-- It will restart automatically, but we wait one second to give it a
+-- chance to start.
+SELECT pg_sleep(1);
+ pg_sleep 
+----------
+ 
+(1 row)
```
[the remark this answers is not in the document]
Comment (mkindahl) [reply tsl/test/expected/bgw_scheduler_restart.out]: Added procedures to check for stopped and started background workers. Timeout is quite high, but it should rarely be used.

File: src/loader/bgw_launcher.c (hunk 3 above)
Comment (mkindahl) [reply src/loader/bgw_launcher.c:373]: I added a wait function that will repeat in a loop for workers to stop or start.

**Review by fabriziomello — APPROVED** [review]
LGTM
