### PR TITLE
Fix DecompressChunk path generation

### LINKED ISSUE #2211: Assertion failure in DecompressChunk
#0  0x00007f2e7c236355 in raise () from /usr/lib/libc.so.6
#1  0x00007f2e7c21f853 in abort () from /usr/lib/libc.so.6
#2  0x00005588e3c4736a in ExceptionalCondition (conditionName=0x5588e3e394ac "!(T <= total_pages)", errorType=0x5588e3e39356 "FailedAssertion", fileName=0x5588e3e393a6 "costsize.c", lineNumber=839) at assert.c:54
#3  0x00005588e396bed1 in index_pages_fetched (tuples_fetched=3110, pages=29523, index_pages=1708, root=0x5588e5866e80) at costsize.c:839
#4  0x00005588e396b9b6 in cost_index (path=0x5588e58c2ee0, root=0x5588e5866e80, loop_count=1, partial_path=false) at costsize.c:647
#5  0x00005588e39c5ac6 in create_index_path (root=0x5588e5866e80, index=0x5588e58bf540, indexclauses=0x5588e58c2c60, indexorderbys=0x0, indexorderbycols=0x0, pathkeys=0x5588e58c2e58, indexscandir=ForwardScanDirection, indexonly=false, required_outer=0x0, loop_count=1,
    partial_path=false) at pathnode.c:1054
#6  0x00005588e397a147 in build_index_paths (root=0x5588e5866e80, rel=0x5588e58bfe80, index=0x5588e58bf540, clauses=0x7ffd21516fe0, useful_predicate=false, scantype=ST_ANYSCAN, skip_nonnative_saop=0x7ffd21516e8e, skip_lower_saop=0x7ffd21516e8f) at indxpath.c:1029
#7  0x00005588e3979b89 in get_index_paths (root=0x5588e5866e80, rel=0x5588e58bfe80, index=0x5588e58bf540, clauses=0x7ffd21516fe0, bitindexpaths=0x7ffd21516ee0) at indxpath.c:744
#8  0x00005588e3978cc4 in create_index_paths (root=0x5588e5866e80, rel=0x5588e58bfe80) at indxpath.c:276
#9  0x00007f2e792cca44 in create_compressed_scan_paths (root=0x5588e5866e80, compressed_rel=0x5588e58bfe80, parallel_workers=1, info=0x5588e58bf3e8, sort_info=0x7ffd215173f0) at /home/sven/projects/timescaledb/tsl/src/nodes/decompress_chunk/decompress_chunk.c:995
#10 0x00007f2e792cb305 in ts_decompress_chunk_generate_paths (root=0x5588e5866e80, chunk_rel=0x5588e58ccb78, ht=0x5588e5d658c0, chunk=0x5588e58bed68) at /home/sven/projects/timescaledb/tsl/src/nodes/decompress_chunk/decompress_chunk.c:369
#11 0x00007f2e7928a8f2 in tsl_set_rel_pathlist_query (root=0x5588e5866e80, rel=0x5588e58ccb78, rti=2, rte=0x5588e5869ec0, ht=0x5588e5d658c0) at /home/sven/projects/timescaledb/tsl/src/planner.c:83
#12 0x00007f2e7937a375 in apply_optimizations (root=0x5588e5866e80, reltype=TS_REL_CHUNK_CHILD, rel=0x5588e58ccb78, rte=0x5588e5869ec0, ht=0x5588e5d658c0) at /home/sven/projects/timescaledb/src/planner.c:658
#13 0x00007f2e7937a88e in timescaledb_set_rel_pathlist (root=0x5588e5866e80, rel=0x5588e58ccb78, rti=2, rte=0x5588e5869ec0) at /home/sven/projects/timescaledb/src/planner.c:782
#14 0x00007f2e7939f4a0 in set_rel_pathlist (root=0x5588e5866e80, rel=0x5588e58ccb78, rti=2, rte=0x5588e5869ec0) at /home/sven/projects/timescaledb/src/import/allpaths.c:251
#15 0x00007f2e7939f2c9 in ts_set_append_rel_pathlist (root=0x5588e5866e80, rel=0x5588e585a998, rti=1, rte=0x5588e5859850) at /home/sven/projects/timescaledb/src/import/allpaths.c:176
#16 0x00007f2e7937a2cb in reenable_inheritance (root=0x5588e5866e80, rel=0x5588e585a998, rti=1, rte=0x5588e5859850) at /home/sven/projects/timescaledb/src/planner.c:628
#17 0x00007f2e7937a768 in timescaledb_set_rel_pathlist (root=0x5588e5866e80, rel=0x5588e585a998, rti=1, rte=0x5588e5859850) at /home/sven/projects/timescaledb/src/planner.c:756
#18 0x00005588e3964f4b in set_rel_pathlist (root=0x5588e5866e80, rel=0x5588e585a998, rti=1, rte=0x5588e5859850) at allpaths.c:540
#19 0x00005588e3964af0 in set_base_rel_pathlists (root=0x5588e5866e80) at allpaths.c:352
#20 0x00005588e396485c in make_one_rel (root=0x5588e5866e80, joinlist=0x5588e5868618) at allpaths.c:222
#21 0x00005588e3998f85 in query_planner (root=0x5588e5866e80, qp_callback=0x5588e3998ae7 <minmax_qp_callback>, qp_extra=0x0) at planmain.c:271
#22 0x00005588e39989a5 in build_minmax_path (root=0x5588e585a100, mminfo=0x5588e585a8e0, eqop=2060, sortop=2064, nulls_first=true) at planagg.c:445
#23 0x00005588e39981a9 in preprocess_minmax_aggregates (root=0x5588e585a100) at planagg.c:178
#24 0x00005588e399c1cb in grouping_planner (root=0x5588e585a100, inheritance_update=false, tuple_fraction=0) at planner.c:2016
#25 0x00005588e399a6ca in subquery_planner (glob=0x5588e5859bc0, parse=0x5588e5586b68, parent_root=0x0, hasRecursion=false, tuple_fraction=0) at planner.c:1012
#26 0x00005588e3999339 in standard_planner (parse=0x5588e5586b68, cursorOptions=256, boundParams=0x0) at planner.c:406
#27 0x00007f2e793798a4 in timescaledb_planner (parse=0x5588e5586b68, cursor_opts=256, bound_params=0x0) at /home/sven/projects/timescaledb/src/planner.c:297
#28 0x00005588e39990c5 in planner (parse=0x5588e5586b68, cursorOptions=256, boundParams=0x0) at planner.c:273
#29 0x00005588e3ab4370 in pg_plan_query (querytree=0x5588e5586b68, cursorOptions=256, boundParams=0x0) at postgres.c:878
#30 0x00005588e3ab44a1 in pg_plan_queries (querytrees=0x5588e5859648, cursorOptions=256, boundParams=0x0) at postgres.c:968
#31 0x00005588e3ab47d9 in exec_simple_query (query_string=0x5588e5585858 "select max(time) from metrics where device_id = 1;") at postgres.c:1143
#32 0x00005588e3ab9102 in PostgresMain (argc=1, argv=0x5588e55b34a0, dbname=0x5588e55b32e8 "dev", username=0x5588e55b32c8 "sven") at postgres.c:4247
#33 0x00005588e3a025e7 in BackendRun (port=0x5588e55ac3e0) at postmaster.c:4448
#34 0x00005588e3a01cc7 in BackendStartup (port=0x5588e55ac3e0) at postmaster.c:4139
#35 0x00005588e39fdc45 in ServerLoop () at postmaster.c:1704
#36 0x00005588e39fd3e8 in PostmasterMain (argc=3, argv=0x5588e557f6b0) at postmaster.c:1377
#37 0x00005588e3913a65 in main (argc=3, argv=0x5588e557f6b0) at main.c:228

### LINKED ISSUE #2424: Duplicate rows when selecting with conditional ordering on compressed hypertable
### **Relevant system information:**
 - OS: Ubuntu 19.10
 - PostgreSQL version (output of `postgres --version`): 12.3
 - TimescaleDB version (output of `\dx` in `psql`): 1.7.2
 - Installation method: using Docker

### **Describe the bug**
When using `CASE WHEN` in `ORDER BY` on a compressed hypertable, and conditionally ordering a `numeric` or `text` field, all rows returned are duplicated. This seems to happen when having conditional ordering **only on one** `numeric`/`text` field. Having two of those fields in two different conditional ordering statements in the same query produces result without duplicates. Replacing `price` in conditional ordering with `microseconds` - an integer field - in the query posted below, also returns result without duplicates

**One thing in common with all `numeric`/`text` fields in our table is, that there are no plain indexes on them. There is however a `UNIQUE` index on the `text` field.**

There are **no duplicates** in our table. Selecting with the same query from plain postgres table produces correct result, without any duplicates. Here's an example of our query:

```
SELECT ticker_id, timestamp, microseconds, price, amount, type FROM tickers
WHERE timestamp >= '2020-08-01T16:00Z' AND timestamp < '2020-08-02T00:00Z' AND fk_exchange = 4 AND fk_trade_pair = 29
ORDER BY timestamp DESC, microseconds DESC, type, CASE WHEN type='BUY' THEN price END DESC, CASE WHEN type='SELL' THEN price END ASC, id DESC;
```

Example of the result, where each row is duplicated:
```
TICKER_ID                               TIMESTAMP               MICROS          PRICE           AMOUNT  TYPE
...
6abdca2a-884e-0f8c-86ee-4afa71435b97	2020-08-01 23:59:00+00	58812000	117.00000000	16910	SELL
6abdca2a-884e-0f8c-86ee-4afa71435b97	2020-08-01 23:59:00+00	58812000	117.00000000	16910	SELL
7f7cfe72-43ca-a153-21a9-e71ddd17ec62	2020-08-01 23:59:00+00	57367000	117.00000000	2085	SELL
7f7cfe72-43ca-a153-21a9-e71ddd17ec62	2020-08-01 23:59:00+00	57367000	117.00000000	2085	SELL
...
```
Query plan for the above query, with conditional ordering on one field:
```
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|QUERY PLAN                                                                                                                                                                                                                                                                                                                                                                                            |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|Gather Merge  (cost=5091.03..9691.03 rows=40000 width=115)                                                                                                                                                                                                                                                                                                                                            |
|  Workers Planned: 1                                                                                                                                                                                                                                                                                                                                                                                  |
|  ->  Sort  (cost=4091.02..4191.02 rows=40000 width=115)                                                                                                                                                                                                                                                                                                                                              |
|        Sort Key: _hyper_14_1591_chunk."timestamp" DESC, _hyper_14_1591_chunk.microseconds DESC, _hyper_14_1591_chunk.type, (CASE WHEN (_hyper_14_1591_chunk.type = 'BUY'::trade_type) THEN _hyper_14_1591_chunk.price ELSE NULL::numeric END) DESC, (CASE WHEN (_hyper_14_1591_chunk.type = 'SELL'::trade_type) THEN _hyper_14_1591_chunk.price ELSE NULL::numeric END), _hyper_14_1591_chunk.id DESC|
|        ->  Result  (cost=6.37..1033.48 rows=40000 width=115)                                                                                                                                                                                                                                                                                                                                         |
|              ->  Custom Scan (DecompressChunk) on _hyper_14_1591_chunk  (cost=6.37..433.48 rows=68000 width=51)                                                                                                                                                                                                                                                                                      |
|                    Filter: (("timestamp" >= '2020-08-01 16:00:00+00'::timestamp with time zone) AND ("timestamp" < '2020-08-02 00:00:00+00'::timestamp with time zone))                                                                                                                                                                                                                              |
|                    ->  Bitmap Heap Scan on compress_hyper_17_1684_chunk  (cost=45.26..433.48 rows=68 width=252)                                                                                                                                                                                                                                                                                      |
|                          Recheck Cond: (fk_trade_pair = 29)                                                                                                                                                                                                                                                                                                                                          |
|                          Filter: ((_ts_meta_max_1 >= '2020-08-01 16:00:00+00'::timestamp with time zone) AND (_ts_meta_min_1 < '2020-08-02 00:00:00+00'::timestamp with time zone) AND (fk_exchange = 4))                                                                                                                                                                                            |
|                          ->  Bitmap Index Scan on compress_hyper_17_1684_chunk__compressed_hypertable_17_fk_trade  (cost=0.00..45.24 rows=2261 width=0)                                                                                                                                                                                                                                              |
|                                Index Cond: (fk_trade_pair = 29)                                                                                                                                                                                                                                                                                                                                      |
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

```

Our table structure with indexes and compression:
```
CREATE TABLE IF NOT EXISTS TICKERS
(
    id            BIGSERIAL                           NOT NULL,
    timestamp     TIMESTAMPTZ                         NOT NULL,
    type          TRADE_TYPE                          NOT NULL,
    microseconds  INTEGER                             NOT NULL,
    FK_TRADE_PAIR SMALLINT REFERENCES TRADE_PAIR (ID) NOT NULL,
    FK_EXCHANGE   SMALLINT REFERENCES EXCHANGE (ID)   NOT NULL,

    price         NUMERIC(16, 8)                      NOT NULL,
    amount        NUMERIC(22, 8)                      NOT NULL,
    ticker_id     TEXT                                NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS tickers_fk_exchange_fk_trade_pair_ticker_id_timestamp_key ON TICKERS (FK_EXCHANGE, FK_TRADE_PAIR, ticker_id, timestamp DESC);
CREATE INDEX IF NOT EXISTS tickers_fk_exchange_fk_trade_pair_timestamp_microseconds_idx ON TICKERS (FK_EXCHANGE, FK_TRADE_PAIR, timestamp DESC, microseconds DESC);

ALTER TABLE tickers SET (
    timescaledb.compress,
    timescaledb.compress_segmentby = 'fk_exchange, fk_trade_pair',
    timescaledb.compress_orderby = 'timestamp DESC, microseconds DESC'
);
SELECT add_compress_chunks_policy('tickers', INTERVAL '1 days');
```

### **Expected behavior**
We expect the above query to return result without duplicates.

### **Actual behavior**
The query returns duplicate results.

### **Additional context**
Stackoverflow post: https://stackoverflow.com/questions/63978001/postgres-conditional-ordering-returning-duplicate-values

### PR DESCRIPTION
**Pull request by svenklemm**
The non-parallel pathes generated by DecompressChunk were
incorrectly marked as parallel_safe even when the child scan
was not parallel aware. Leading to incorrect query results
when those pathes were used in a parallel plan.
Additionaly DecompressChunk code didnt set total_table_pages on
PlannerInfo leading to an assertion failure in BitmapHeapscan
path creation.

Fixes #2211
Fixes #2424

### CODE REVIEW

File: tsl/src/nodes/decompress_chunk/decompress_chunk.c [hunk 1]
```diff
@@ -946,11 +946,12 @@ decompress_chunk_path_create(PlannerInfo *root, CompressionInfo *info, int paral
...
 	path->cpath.methods = &decompress_chunk_path_methods;
 
-	Assert(parallel_workers == 0 || compressed_path->parallel_safe);
-
-	path->cpath.path.parallel_aware = false;
-	path->cpath.path.parallel_safe = compressed_path->parallel_safe;
+	/* This path is only safe in a parallel plan if the Scan below
+	 * the DecompressChunk is parallel aware, otherwise the Scan
+	 * might produce duplicate tuples. */
+	path->cpath.path.parallel_safe = compressed_path->parallel_aware;
```
Comment (erimatnor) [inline tsl/src/nodes/decompress_chunk/decompress_chunk.c:952]: The common practice I've seen is that this value is set from the `RelOptInfo` being planned, e.g., like this:

```
path->cpath.path.parallel_safe => compressed_rel->consider_parallel;
```

Sometimes also taking into account the parallel safeness of the subpath. So, I am wondering if we shouldn't make this call earlier when we create the `RelOptInfo` instead, so that it can be inherited consistently by all paths we consider. This seems very hard-coded to this particular path.

Comment (svenklemm) [reply tsl/src/nodes/decompress_chunk/decompress_chunk.c:952]: safeness is not enough as can be seen by #2424

File: tsl/src/nodes/decompress_chunk/decompress_chunk.c [hunk 2]
```diff
@@ -970,6 +971,10 @@ create_compressed_scan_paths(PlannerInfo *root, RelOptInfo *compressed_rel, int
 {
 	Path *compressed_path;
 
+	/* clamp total_table_pages to 10 pages since this is the
+	 * minimum estimate for number of pages */
+	root->total_table_pages = Max(compressed_rel->pages, 10);
```
Comment (pmwkaa) [inline tsl/src/nodes/decompress_chunk/decompress_chunk.c:976]: Maybe use some PostgreSQL macro or variable for that instead of hard coding the value?

**Review by pmwkaa — APPROVED** [review]

File: tsl/src/nodes/decompress_chunk/decompress_chunk.c (hunk 1 above)
Comment (erimatnor) [reply tsl/src/nodes/decompress_chunk/decompress_chunk.c:952]: You answer does not address my concern. 

Consider this: nowhere in the PostgreSQL code can I find a place where a path's `parallel_safe` setting is set based on the `parallel_aware` setting of another path; this should tell us something. Neither the code nor you PR description gives a good motivation or explanation for this setting and why it makes sense to deviate from the standard pattern seen elsewhere. 

The common pattern is as I described above, i.e., using `consider_parallel, which in most cases is propagated upwards by PostgreSQL to, e.g., upper and join rels automatically`. This seems logical since the relation being planned holds such information that gets applied to all paths considered for the planned relation.

Perhaps the setting of `consider_parallel` can take into account the parallel awareness of subnodes, but then that should happen at the relation level since there could be other, potentially parallel safe paths, that computes this relation (RelOptInfo).

So, my ask is twofold:

- Please provide an explanation why setting `parallel_safe` based on `parallel_aware` of the subpath makes sense in this particular case as an outlier.
- Please provide an explanation why we shouldn't make this decision primarily at the relation rather than the path level.

Comment (svenklemm) [reply tsl/src/nodes/decompress_chunk/decompress_chunk.c:952]: All the fields on RelOptInfo apply to parallel and non-parallel path generation so they cannot be used for this test.

File: tsl/src/nodes/decompress_chunk/decompress_chunk.c (hunk 2 above)
Comment (gayyappan) [inline tsl/src/nodes/decompress_chunk/decompress_chunk.c:976]: why is this not ``` root->total_table_pages = compressed_rel->pages ```. If we don't have the compressed_rel size yet, shouldn't that be estimated before the assignment here?

**Review by gayyappan — APPROVED** [review]

File: tsl/src/nodes/decompress_chunk/decompress_chunk.c (hunk 2 above)
Comment (svenklemm) [reply tsl/src/nodes/decompress_chunk/decompress_chunk.c:976]: estimate_rel_size will have been called at that point for the rel
