### PR TITLE
Forbid recompression on nullable orderby columns

### LINKED ISSUE #9444: recompression produces overlapping batches for nullable orderby column
The overlaps are not properly detected in presence of nulls, because the minmax metadata doesn't have nulls.

Here is an example with a mixed-null compressed batch, i.e. both null and not-null values in the batch. The minmax metadata is not null.

```
CREATE TABLE t1(time int NOT NULL, val int);
SELECT create_hypertable('t1', 'time', chunk_time_interval => 10000);
ALTER TABLE t1 SET (timescaledb.compress, timescaledb.compress_orderby='val');
INSERT INTO t1 SELECT 1, g FROM generate_series(1,800) g;
INSERT INTO t1 SELECT 1, NULL FROM generate_series(1,200);
SELECT compress_chunk(show_chunks('t1'));
INSERT INTO t1 SELECT 1, g FROM generate_series(901,1400) g;
SELECT compress_chunk(show_chunks('t1'), if_not_compressed => true);
SET timescaledb.batch_sorted_merge = 'off';

/* This query orders NULLS LAST, so we can't have a non-NULL value after a NULL value. */
SELECT count(*) AS wrong_rows FROM (
  SELECT val, lead(val) OVER (ORDER BY val) AS next FROM t1 ORDER BY val
) t WHERE val IS NULL AND next IS NOT NULL;

/* Fixed after recompression. */
SELECT compress_chunk(decompress_chunk(x)) FROM show_chunks('t1') x;

SELECT count(*) AS wrong_rows FROM (
  SELECT val, lead(val) OVER (ORDER BY val) AS next FROM t1 ORDER BY val
) t WHERE val IS NULL AND next IS NOT NULL;
```

### PR DESCRIPTION
**Pull request by natalya-aksman**
Fixes #9444.

### CODE REVIEW

File: tsl/src/compression/api.c [hunk 1]
```diff
@@ -686,6 +704,19 @@ recompress_chunk_impl(Chunk *chunk, Oid *uncompressed_chunk_id, bool recompress)
 			 NameStr(chunk->fd.table_name));
 		return false;
 	}
+	/* #9444: do not recompress when order by columns are nullable, do decompress/compress instead.
+	 * It is due to compression min/max metadata not handling NULLs.
+	 * When we implement chunks with min/max NULL-handling metadata, this restriction can be lifted.
+	 */
+	else if (!is_chunk_orderby_nonnullable(chunk_settings))
```
Comment (Poroma-Banerjee) [inline tsl/src/compression/api.c]: Only partial recompression (segmentwise) won't work right?

Comment (natalya-aksman) [reply tsl/src/compression/api.c]: No, in-memory recompression will not work either, as this check is done before deciding which recompression we should use.

**Comment by natalya-aksman** [comment]
Looks like we won't be able to recompress compressed Caggs because Cagg columns do not inherit NOT NULL properties from the source table columns. See [comment here](https://github.com/timescale/timescaledb/issues/9444#issuecomment-4226302864). 
Not sure how to proceed. If this fix goes in as is Caggs won't ever be recompressed.

**Comment by natalya-aksman** [comment]
> Looks like we won't be able to recompress compressed Caggs because Cagg columns do not inherit NOT NULL properties from the source table columns. See [comment here](https://github.com/timescale/timescaledb/issues/9444#issuecomment-4226302864). Not sure how to proceed. If this fix goes in as is Caggs won't ever be recompressed.

Actually, if compressed Cagg's `orderby` columns are partition columns they will have NOT NULL constraint on them and that should be good enough for most of the Caggs. So we can go ahead with this fix.

File: tsl/test/expected/cagg_direct_compress.out [hunk 2]
```diff
@@ -56,6 +56,9 @@ SELECT DISTINCT _timescaledb_functions.chunk_status_text(chunk) FROM show_chunks
 
 -- Recompress all uncompressed chunks
 SELECT compress_chunk(show_chunks('conditions_hourly'), recompress => true) IS NOT NULL AS compress;
```
Comment (natalya-aksman) [inline tsl/test/expected/cagg_direct_compress.out:58]: This Cagg (`conditions_hourly`) has default `compress_orderby='bucket,device_id'`, that's why it's not being recompressed. If it were `compress_orderby='bucket'` it would be recompressed because `bucket` is a partitioning column set to NOT NULL, but `device_id` is not.

File: tsl/src/compression/api.c (hunk 1 above)
Comment (antekresic) [reply tsl/src/compression/api.c]: In-memory recompression works on a segment group level (all batches in the segment are recompressed) so we shouldn't block it here. This issue doesn't affect it.

Comment (natalya-aksman) [reply tsl/src/compression/api.c]: I see, will apply the check to segmentwise recompression only.

File: tsl/src/compression/api.c [hunk 3]
```diff
@@ -704,6 +722,19 @@ recompress_chunk_impl(Chunk *chunk, Oid *uncompressed_chunk_id, bool recompress)
 							"set timescaledb.enable_segmentwise_recompression to on")));
 			return false;
 		}
+		/* #9444: do not recompress when order by columns are nullable, do decompress/compress
+		 * instead. It is due to compression min/max metadata not handling NULLs. When we implement
+		 * chunks with min/max NULL-handling metadata, this restriction can be lifted.
+		 */
+		else if (!is_chunk_orderby_nonnullable(chunk_settings))
```
Comment (Poroma-Banerjee) [inline tsl/src/compression/api.c]: I think this check should be with along with the `ts_chunk_is_partial` check. 

In memory recompression should be preferable than manual decompress/compress.

```c
if (ts_chunk_is_partial(chunk) && is_chunk_orderby_nonnullable(chunk_settings)) 
{
    recompress_chunk_segmentwise_impl()
}
else 
{
    recompress_chunk_in_memory_impl()
}
```

**Review by Poroma-Banerjee — APPROVED** [review]

File: tsl/src/compression/api.c (hunk 3 above)
Comment (natalya-aksman) [reply tsl/src/compression/api.c]: But if a chunk is partial, can we do  in memory recompress on it? Is it an option?

Comment (Poroma-Banerjee) [reply tsl/src/compression/api.c]: you're right. It won't work.

**Review by antekresic — APPROVED** [review]
Approved with intentions to unblock this before the release.

There is probably an alternative approach where we don't need to block segmentwise recompression but it would be less efficient in certain scenarios than it today. Still better than full recompression of the chunk.

**Comment by natalya-aksman** [comment]
> Approved with intentions to unblock this before the release.
> 
> There is probably an alternative approach where we don't need to block segmentwise recompression but it would be less efficient in certain scenarios than it today. Still better than full recompression of the chunk.

Makes sense to not merge this PR until this alternative approach is implemented.

**Review by akuzm — APPROVED** [review]
As discussed offline, might be good to make a copy of the function instead of the flag to simplify the control flow.
