### PR TITLE
Verify compressed chunk validity for insert path

### LINKED ISSUE #3400: "chunk not found" during insertion to already compressed chunk while the policy is recompressing
Relevant system information:
OS: Docker / timescale/timescaledb:2.3.0-pg12
PostgreSQL version (output of postgres --version): 12.7
TimescaleDB version (output of \dx in psql): 2.3.0
Installation method: [e.g., "using Docker", "apt install", "source"] : "Using Docker"

**Describe the bug**
"chunk not found" error is presented during insertion to an already compressed chunk while the policy is recompressing  

**To Reproduce**
```
drop table sensor_data;

create table sensor_data( 
time timestamptz not null, 
sensor_id integer not null, 
cpu double precision null,
temperature double precision null );

select from create_hypertable('sensor_data','time');

INSERT INTO sensor_data
	SELECT
		time + (INTERVAL '1 minute' * random()) AS time,
		sensor_id,
		random() AS cpu,
		random()* 100 AS temperature
	FROM
		generate_series(now() - INTERVAL '1 months', now() - INTERVAL '1 week', INTERVAL '1 minute') AS g1(time),
		generate_series(1, 100, 1 ) AS g2(sensor_id)
	ORDER BY
		time;

alter table sensor_data set (timescaledb.compress, timescaledb.compress_orderby = 'time DESC');
```

```
select add_compression_policy('sensor_data','1 minute'::INTERVAL);
```

```
--Confirm all the chunks are compressed--
SELECT c.chunk_name,c.range_start,c.range_end,c.is_compressed,pg_size_pretty(d.total_bytes) FROM public.chunks_detailed_size('public.sensor_data') d, timescaledb_information.chunks c WHERE d.chunk_name=c.chunk_name order by c.range_start;
    chunk_name     |      range_start       |       range_end        | is_compressed | pg_size_pretty
-------------------+------------------------+------------------------+---------------+----------------
 _hyper_3_14_chunk | 2021-06-03 00:00:00+00 | 2021-06-10 00:00:00+00 | t             | 5496 kB
 _hyper_3_15_chunk | 2021-06-10 00:00:00+00 | 2021-06-17 00:00:00+00 | t             | 20 MB
 _hyper_3_16_chunk | 2021-06-17 00:00:00+00 | 2021-06-24 00:00:00+00 | t             | 20 MB
 _hyper_3_17_chunk | 2021-06-24 00:00:00+00 | 2021-07-01 00:00:00+00 | t             | 20 MB
 _hyper_3_18_chunk | 2021-07-01 00:00:00+00 | 2021-07-08 00:00:00+00 | t             | 512 kB
(5 rows)
```

```
--Do an insert on one of the chunks, ex: second chunk 
INSERT
	INTO
	sensor_data
SELECT
	time + (INTERVAL '1 minute' * random()) AS time,
	sensor_id,
	random() AS cpu,
	random()* 100 AS temperature
FROM
	generate_series('2021-06-10 00:00:00+00', '2021-06-16 00:00:00+00', INTERVAL '1 minute') AS g1(time),
	generate_series(1, 100, 1 ) AS g2(sensor_id)
ORDER BY
	time;
```

```
--force run compression by removing and adding the policy--
SELECT remove_compression_policy('sensor_data');
SELECT add_compression_policy('sensor_data','1 minute'::INTERVAL);
--just after the above command, do an insert so that both compression and insertion are happening--
INSERT
	INTO
	sensor_data
SELECT
	time + (INTERVAL '1 minute' * random()) AS time,
	sensor_id,
	random() AS cpu,
	random()* 100 AS temperature
FROM
	generate_series('2021-06-10 00:00:00+00', '2021-06-16 00:00:00+00', INTERVAL '1 minute') AS g1(time),
	generate_series(1, 100, 1 ) AS g2(sensor_id)
ORDER BY
	time;
 
**ERROR:  chunk not found**
```

**Expected behavior**
Insertion should be successful without any error

**Actual behavior**
Insertion fails with 'chunk not found'

### PR DESCRIPTION
**Pull request by gayyappan**
When a insert into a compressed chunk is blocked by a
concurrent recompress_chunk, the latter process could move
the storage for the compressed chunk. Verify validity of
the compressed chunk before proceeding to acquire locks.

Fixes #3400

### CODE REVIEW

File: src/nodes/chunk_insert_state.c [hunk 1]
```diff
@@ -566,7 +565,18 @@ ts_chunk_insert_state_create(const Chunk *chunk, ChunkDispatch *dispatch)
 						 "insert into a compressed chunk that has primary or unique constraint is "
 						 "not supported")));
 		}
-		compress_rel = table_open(compress_chunk_relid, RowExclusiveLock);
+		/* fetch the chunk again after acquiring lock and verify if it is
+		 * still compressed. Then get the correct compressed chunk id
+		 * ( github issue 3400)
+		 */
+		Chunk *orig_chunk = ts_chunk_get_by_id(chunk->fd.id, true);
```
Comment (mfundul) [inline src/nodes/chunk_insert_state.c:572]: The function `ts_chunk_insert_state_create()` uses a lot of `chunk->` pointers before, after, and outside the `if (has_compressed_chunk)` condition. Even the result of the `if (has_compressed_chunk)` condition cannot be trusted as it has been calculated before taking the lock.

In my opinion the function should be refactored so that its arguments don't have a `const Chunk *chunk` pointer at all. This should be possible to do with 2 arguments, the table id and the chunk id. The table id will allow to take the lock and the chunk id will allow to get the `Chunk` pointer after the lock has been taken. Taking the lock and the `Chunk` pointer should be the first things this function does.

Comment (gayyappan) [reply src/nodes/chunk_insert_state.c]: the new lines of code have been moved to a separate function.

**Review by afiskon — APPROVED** [review]

**Review by svenklemm — APPROVED** [review]

File: src/nodes/chunk_insert_state.c [hunk 2]
```diff
@@ -513,6 +513,31 @@ adjust_projections(ChunkInsertState *cis, ChunkDispatch *dispatch, Oid rowtype)
...
+ *      important because lock acquisition order is always orignal chunk,
+ *      followed by compressed chunk to prevent deadlocks.
+ * We now try to acquire a lock on the compressed chunk, if one exists.
+ * Note that the insert could have been blocked by a recompress_chunk operation.
+ * So the compressed chunk could have moved under us. We need to refetch the chunk
+ * to get the correct compressed chunk id (github issue 3400)
+ */
+static Relation
+lock_associated_compressed_chunk(int32 chunk_id, bool *has_compressed_chunk)
+{
```
Comment (mkindahl) [inline src/nodes/chunk_insert_state.c:526]: You have the `chunk` already in the caller. Why are you not passing that to the function instead of fetching it again?

File: src/nodes/chunk_insert_state.c [hunk 3]
```diff
@@ -513,6 +513,27 @@ adjust_projections(ChunkInsertState *cis, ChunkDispatch *dispatch, Oid rowtype)
 	}
 }
 
+/* Assumption: we have acquired a lock on the chunk table.
+ * We now try to acquire a lock on the compressed chunk, if one exists.
+ * Note that the insert could have been blocked by a recompress_chunk operation.
+ * So the compressed chunk could have moved under us. We need to refetch the chunk
```
[the remark this answers is not in the document]
Comment (gayyappan) [reply src/nodes/chunk_insert_state.c:521]: Yes, that's correct.  So Insert would be blocked by recompress_chunk at that point and waiting for a lock on the original (uncompressed) chunk. When recompress_chunk completes, insert gets the lock, but now we have to get the new compressed_chunk_id   (that was created by recompress_chunk)

File: src/nodes/chunk_insert_state.c (hunk 2 above)
Comment (gayyappan) [reply src/nodes/chunk_insert_state.c:526]: See explanation above.
