### PR TITLE
Fix havingqual processing for caggs

### LINKED ISSUE #2655: Segmentation Fault on Continuous Aggregate Data Refresh
**Relevant system information:**
 - OS: Ubuntu 18.04.5 LTS
 - PostgreSQL version: 12.5
 - TimescaleDB version: 2.0.0-rc3 
 - Installation method: apt install
 - `raw_data` hypertable contains about 2.5M rows per minute and few hundred million rows in total. Though I also tested this on a 100 row table and got the same result.

**Describe the bug**
When a continuous aggregate is created or refreshed with a `GROUP BY...HAVING...` clause it causes a segmentation fault. .

**To Reproduce**

```
CREATE MATERIALIZED VIEW search_query_count_1m
WITH (timescaledb.continuous) as
SELECT  search_query, 
        count(search_query) as count,
        time_bucket(INTERVAL '1 minute', time) AS bucket
FROM raw_data 
WHERE search_query is not null 
AND LENGTH(TRIM(both from search_query))>0 
GROUP BY search_query, bucket
HAVING count(search_query) > 50;
```

**Expected behavior**
The continuous aggregate to be successfully created and the view to only contain search queries with counts> 50. 

**Actual behavior**
A segmentation fault crashes the Postgres server

Logs:

```
2020-11-17 20:41:46.357 UTC [28429] LOG:  server process (PID 4039) was terminated by signal 11: Segmentation fault
2020-11-17 20:41:46.357 UTC [28429] DETAIL:  Failed process was running: CALL refresh_continuous_aggregate('search_query_count_1m', NULL, NULL);
2020-11-17 20:41:46.357 UTC [28429] LOG:  terminating any other active server processes
2020-11-17 20:41:46.357 UTC [3834] repuser@[unknown] WARNING:  terminating connection because of crash of another server process
2020-11-17 20:41:46.357 UTC [3834] repuser@[unknown] DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory. 
```

**Additional context**
In some additional testing this seems to not happen if the `HAVING` clause contains an `avg()` function instead of a `count()` function based off of the same hypertable. But two differeing `HAVING count()...` queries caused the same issue. The same query when ran standalone and not for creating a continuous aggregate completes fine.

### PR DESCRIPTION
**Pull request by gayyappan**
If the targetlist for the cagg query has both subexprs and exprs
from the having clause, the havingqual for the partial view
is generated incorrectly. Fix this issue by checking havingqual
against all the entries in the targetlist instead of first match.

Fixes #2655

### CODE REVIEW

File: tsl/src/continuous_aggs/create.c [hunk 1]
```diff
@@ -1348,40 +1348,50 @@ replace_having_qual_mutator(Node *node, cagg_havingcxt *cxt)
...
+ * Example:
+ * SELECT x, count(x) , time_bucket(...)
+ * FROM ...
+ * HAVING count(x) > 10 and sum(y) > 11 --->havingQual
+ *
+ * count(x) : already appears in the targetlist of the query and should be
+ * replaced by the corresponding entry from modtlist. We have to compare count(x)
+ * with all the entries in the tlist so that we do not match subexprs when the
+ * complete expr (e.g do not match x instead of count(x) ) is in the tlist.
+ * (issue 2655)
```
Comment (mkindahl) [inline tsl/src/continuous_aggs/create.c:1384]: This is not particularly easy to follow. If you add the `mod_tlist` and `orig_tlist` for the example above it will be easier to follow how the replacement works.

Also, do you have a test case for the situation you describe above, that is, a test case that would break if you do not compare `count(x)` with all the entries in the tlist.

**Review by mkindahl — COMMENTED** [review]
LGTM, but can you add a test case for the situation you describe and add some clarifications to the comment so that it is easier to follow?

File: tsl/src/continuous_aggs/create.c (hunk 1 above)
Comment (mkindahl) [reply tsl/src/continuous_aggs/create.c:1384]: I was wondering about the specific corner-case where you have both the subexpression and the "top-expression" in the tlist.

Comment (gayyappan) [reply tsl/src/continuous_aggs/create.c:1384]: Both search_query and count(search_query) appear in the tlist (in the query)
HAVING has count(search-query)
```
CREATE MATERIALIZED VIEW search_query_count_1m WITH (timescaledb.continuous) 
AS
 SELECT  search_query,count(search_query) as count, 
         time_bucket(INTERVAL '1 minute', time) AS bucket
 FROM raw_data
 WHERE search_query is not null AND LENGTH(TRIM(both from search_query))>0
 GROUP BY search_query, bucket 
HAVING count(search_query) > 3 OR sum(cnt) > 1;
```

Comment (mkindahl) [reply tsl/src/continuous_aggs/create.c:1384]: Thank you, then it is covered.

Comment (mkindahl) [reply tsl/src/continuous_aggs/create.c:1384]: Could you please show the tlist and the modlist in the example as well, so that it is clear to future developers?

Comment (gayyappan) [reply tsl/src/continuous_aggs/create.c:1384]: added more comments

**Review by mkindahl — APPROVED** [review]
LGTM

**Review by svenklemm — APPROVED** [review]
