### PR TITLE
Fix SkipScan distinct column identification

### LINKED ISSUE #3330: Performance regression with skip scan enabled
**Relevant system information:**
 - OS: CentOS
 - PostgreSQL version (output of `postgres --version`): 12
 - TimescaleDB version (output of `\dx` in `psql`): 2.2.1
 - Installation method: source

**Describe the bug**
With skip scan enabled, some simple plans become ~20x or more slower.

**To Reproduce**
Create test table
```
create table t1 as select a,b,2 from generate_series(1,10) a, generate_series(1,50000) b;
create index on t1 (a,b desc);
```
Run with skip scan off
```
set timescaledb.enable_skipscan=0;
explain(analyze)
select distinct on (a) *
from t1
where a = 10 and b <= 5000
order by a,b desc;
```

```
Unique  (cost=0.42..2407.02 rows=10 width=12) (actual time=0.035..0.843 rows=1 loops=1)
  ->  Index Scan using t1_a_b_idx on t1  (cost=0.42..2407.02 rows=4961 width=12) (actual time=0.034..0.689 rows=5000 loops=1)
        Index Cond: ((a = 10) AND (b <= 5000))
Planning Time: 0.128 ms
Execution Time: 0.875 ms
```

Run with skip scan on
```
set timescaledb.enable_skipscan=1;
explain(analyze)
select distinct on (a) *
from t1
where a = 10 and b <= 5000
order by a,b desc;
```

```
Unique  (cost=0.42..9.08 rows=10 width=12) (actual time=0.022..21.640 rows=1 loops=1)
  ->  Custom Scan (SkipScan) on t1  (cost=0.42..9.08 rows=10 width=12) (actual time=0.021..21.495 rows=5000 loops=1)
        ->  Index Scan using t1_a_b_idx on t1  (cost=0.42..2407.02 rows=4961 width=12) (actual time=0.001..20.892 rows=5000 loops=1)
              Index Cond: ((a = 10) AND (b <= 5000))
Planning Time: 0.187 ms
Execution Time: 21.674 ms
```

Side note... of course it's also possible to rewrite the `SELECT` query to something like `SELECT * FROM t1 WHERE a=10 and b <= 5000 ORDER BY a,b DESC LIMIT 1` which will be even faster. Still, I don't expect a 20x increase in query duration on the previous query.

### PR DESCRIPTION
**Pull request by svenklemm**
The SkipScan code assumed the first entry in PathKeys would match the distinct column. This is not always true as postgres will remove entries from PathKeys it considers constant leading to SkipScan operating on the wrong column under those circumstances. This did most likely not cause any wrong results as the other constraints for SkipScan to apply still had to be satisfied but resulted in very inefficient query execution for those affected
queries.
This patch refactors the SkipScan code to use the distinctClause from the Query instead.

Fixes #3330

Disable-check: commit-count

### CODE REVIEW

File: tsl/src/nodes/skip_scan/planner.c [hunk 1]
```diff
@@ -372,25 +382,108 @@ skip_scan_path_create(PlannerInfo *root, IndexPath *index_path, double ndistinct
...
 		return NULL;
 
 	return skip_scan_path;
 }
 
+/* Extract the Var to use for the SkipScan and do the TupleConversion
+ * if required.
+ */
+static Var *
+get_distinct_var(PlannerInfo *root, IndexPath *index_path, SkipScanPath *skip_scan_path)
```
Comment (mkindahl) [inline tsl/src/nodes/skip_scan/planner.c:401]: You also update the skip scan path. You should make that clear through, e.g., naming. Otherwise, it is assumed that this is a pure getter, which it is not.

File: tsl/src/nodes/skip_scan/planner.c [hunk 2]
```diff
@@ -514,52 +581,12 @@ get_idx_key(IndexOptInfo *idxinfo, AttrNumber attno)
 			return i;
 	}
 
+	abort();
+
```
Comment (mkindahl) [inline tsl/src/nodes/skip_scan/planner.c:585]: Function `pg_unreachable` below runs `abort`. Remains from debugging?

**Review by mkindahl — APPROVED** [review]
LGTM. Please check the comments.

File: tsl/src/nodes/skip_scan/planner.c (hunk 2 above)
Comment (svenklemm) [reply tsl/src/nodes/skip_scan/planner.c:585]: yes, removed

**Review by mfundul — APPROVED** [review]

File: tsl/src/nodes/skip_scan/planner.c [hunk 3]
```diff
@@ -83,7 +90,7 @@ skip_scan_plan_create(PlannerInfo *root, RelOptInfo *relopt, CustomPath *best_pa
 	CustomScan *skip_plan = makeNode(CustomScan);
 	IndexPath *index_path = path->index_path;
 
-	OpExpr *op = fix_indexqual(index_path->indexinfo, path->skip_clause, path->distinct_column);
+	OpExpr *op = fix_indexqual(index_path->indexinfo, path->skip_clause, path->table_attno);
```
Comment (gayyappan) [inline tsl/src/nodes/skip_scan/planner.c:93]: path->index_attno instead of path->table_attno here after mod to fix_indexqual?

File: tsl/src/nodes/skip_scan/planner.c [hunk 4]
```diff
@@ -593,15 +624,15 @@ sort_indexquals(IndexOptInfo *indexinfo, List *quals)
...
+fix_indexqual(IndexOptInfo *index, RestrictInfo *rinfo, AttrNumber table_attno)
 {
 	/* technically our placeholder col > NULL is unsatisfiable, and in some instances
 	 * the planner will realize this and use is as an excuse to remove other quals.
 	 * in order to prevent this, we prepare this qual ourselves.
 	 */
 
 	/* fix_indexqual_references */
-	int indexcol = get_idx_key(index, distinct_column);
+	int indexcol = get_idx_key(index, table_attno);
```
Comment (gayyappan) [inline tsl/src/nodes/skip_scan/planner.c:635]: could pass the index_attno directly instead of lookup here. Don't  see table_attno being used.

**Review by gayyappan — APPROVED** [review]
LGTM. Minor comments about names
