### PR TITLE
Fix segfault on COPY to hypertable

### LINKED ISSUE #1840: Segfault on COPY to hypertable on 1.7.0
- OS: CentOS
 - PostgreSQL version (output of `postgres --version`): 11.2 as well as 12.2
 - TimescaleDB version (output of `\dx` in `psql`): 1.7.0
 - Installation method: Source

**Describe the bug**
Postgres segfaults when COPYing to a hypertable with a `NOT NULL` constraint that you're violating in the `COPY`.

**To Reproduce**
Setup:
```
create table test (a int not null, b timestamptz);
select create_hypertable('public.test', 'b');
```

Then copy:
```
=# copy test (a,b) from stdin (delimiter ',', null 'N');
Enter data to be copied followed by a newline.
End with a backslash and a period on a line by itself, or an EOF signal.
>> N,'2020-01-01'
>> server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
Time: 13372.671 ms (00:13.373)
```

Stack trace:
```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x0000000000630b1a in exec_rt_fetch (estate=0x2505aa0, rti=3907656) at ../../../src/include/executor/executor.h:539
539		return estate->es_range_table_array[rti - 1];
Missing separate debuginfos, use: debuginfo-install postgresql-12.2-rosmerta0002.el7.x86_64
(gdb) bt
#0  0x0000000000630b1a in exec_rt_fetch (estate=0x2505aa0, rti=3907656) at ../../../src/include/executor/executor.h:539
#1  ExecConstraints (resultRelInfo=resultRelInfo@entry=0x2565cf0, slot=slot@entry=0x250bff8, estate=estate@entry=0x2505aa0) at execMain.c:1951
#2  0x00007f517de36e5e in copyfrom (ccstate=ccstate@entry=0x250c4b8, ht=0x25cb630, range_table=0x0) at /home/florisvannee/timescaledb/src/copy.c:390
#3  0x00007f517de37220 in timescaledb_DoCopy (stmt=stmt@entry=0x23f17f8, queryString=0x23f0b10 "copy test (a,b) from stdin (delimiter ',', null 'N');", processed=processed@entry=0x7ffdc0f8c9a0, ht=ht@entry=0x25cb630)
    at /home/florisvannee/timescaledb/src/copy.c:702
#4  0x00007f517de4c29a in process_copy (args=0x7ffdc0f8c9e0) at /home/florisvannee/timescaledb/src/process_utility.c:405
#5  process_ddl_command_start (args=0x7ffdc0f8c9e0) at /home/florisvannee/timescaledb/src/process_utility.c:3140
#6  timescaledb_ddl_command_start (pstmt=<optimized out>, query_string=<optimized out>, context=PROCESS_UTILITY_TOPLEVEL, params=0x0, queryEnv=<optimized out>, dest=<optimized out>, completion_tag=0x7ffdc0f8cf50 "")
    at /home/florisvannee/timescaledb/src/process_utility.c:3403
```

Cause seems to be that the `ExecConstraints` call is passed a `resultRelInfo` that's not been properly initialized with all necessary values.

### PR DESCRIPTION
**Pull request by mkindahl**
When copying from standard input the range table was not set up to
handle the constraints for the target table and instead is initialized
to null. In addition, the range table index was set to zero, causing an
underflow when executing the constraint check. This commit fixes this
by initializing the range table and setting the index correctly.

The code worked correctly for PG12, so the code is also refactored to
ensure that the range table and index is set the same way in all
versions.

Fixes #1840

### CODE REVIEW

**Comment by mkindahl** [comment]
This fails the `misc` test, which seems to be related to PG12 where-clauses where the column is not incorporated into the range table. Investigating.

**Comment by mkindahl** [comment]
> This fails the `misc` test, which seems to be related to PG12 where-clauses where the column is not incorporated into the range table. Investigating.

Found the issue and have pushed a new version.

File: src/copy.c [hunk 1]
```diff
@@ -554,28 +563,26 @@ timescaledb_CopyGetAttnums(TupleDesc tupDesc, Relation rel, List *attnamelist)
...
-	List *range_table = NIL;
 	ListCell *cur;
-	RangeTblEntry *rte;
 	char *xactReadOnly;
-
-	rte = makeNode(RangeTblEntry);
-	rte->rtekind = RTE_RELATION;
-	rte->relid = RelationGetRelid(rel);
-	rte->relkind = rel->rd_rel->relkind;
+#if PG12_GE
```
Comment (gayyappan) [inline src/copy.c:570]: It would be good to split this into 2 functions and make the addition of the range table entry a separate function and call that explicitly.

File: src/copy.c [hunk 2]
```diff
@@ -554,28 +563,26 @@ timescaledb_CopyGetAttnums(TupleDesc tupDesc, Relation rel, List *attnamelist)
 }
 
 static void
-copy_security_check(Relation rel, List *attnums)
+copy_constraints_and_check(ParseState *pstate, Relation rel, List *attnums)
```
Comment (gayyappan) [inline src/copy.c:566]: confused by the name of this function. Why isn't it just add_range_table_entry or something similar?

Comment (mkindahl) [reply src/copy.c:566]: It also checks permissions, which is the reason for the original name. No strong opinion on the name.
