### PR TITLE
Fix crashes in batch sort merge over expressions

### LINKED ISSUE #7975: [Bug]: Crash in count(DISTINCT time+1) over compressed chunks during sorted batch merge
### What type of bug is this?

Crash

### What subsystems and features are affected?

Compression

### What happened?

Bug encountered while testing for https://github.com/timescale/eng-database/issues/693.

`SELECT count(DISTINCT 3*time) FROM skip_scan_ht` on a compressed table crashed due to failed Assert (not a Var) when trying to plan sorted batch merge.
Same crash happens after disabling SkipScan, i.e. it's an existing issue with compressed chunks code.

    

### TimescaleDB version affected

2.20

### PostgreSQL version used

17.4

### What operating system did you use?

Ubuntu 24.04

### What installation method did you use?

Not applicable

### What platform did you run on?

Not applicable

### Relevant log output and stack trace

```bash
TRAP: failed Assert("false"), File: "/home/naksman/timescaledb/timescaledb/tsl/src/nodes/decompress_chunk/planner.c", Line: 1184, PID: 7775
postgres: postgres postgres [local] EXPLAIN(ExceptionalCondition+0xbb)[0x55d2f7205a89]
/usr/local/pgsql17/lib/timescaledb-tsl-2.20.0-dev.so(+0xb2f0c)[0x7efd30cd4f0c]
postgres: postgres postgres [local] EXPLAIN(+0x54c825)[0x55d2f6e9c825]
postgres: postgres postgres [local] EXPLAIN(+0x5457f8)[0x55d2f6e957f8]
postgres: postgres postgres [local] EXPLAIN(+0x544f52)[0x55d2f6e94f52]
postgres: postgres postgres [local] EXPLAIN(+0x546a0b)[0x55d2f6e96a0b]
postgres: postgres postgres [local] EXPLAIN(+0x544fac)[0x55d2f6e94fac]
postgres: postgres postgres [local] EXPLAIN(+0x5482f9)[0x55d2f6e982f9]
postgres: postgres postgres [local] EXPLAIN(+0x54522a)[0x55d2f6e9522a]
postgres: postgres postgres [local] EXPLAIN(create_plan+0x75)[0x55d2f6e94e3a]
postgres: postgres postgres [local] EXPLAIN(standard_planner+0x322)[0x55d2f6ea9a88]
/usr/local/pgsql17/lib/timescaledb-2.20.0-dev.so(+0xb98f0)[0x7efd30e1d8f0]
postgres: postgres postgres [local] EXPLAIN(planner+0x43)[0x55d2f6ea973f]
postgres: postgres postgres [local] EXPLAIN(pg_plan_query+0x82)[0x55d2f700931f]
postgres: postgres postgres [local] EXPLAIN(standard_ExplainOneQuery+0x1dc)[0x55d2f6c764ce]
/usr/local/pgsql17/lib/timescaledb-tsl-2.20.0-dev.so(+0x9688d)[0x7efd30cb888d]
postgres: postgres postgres [local] EXPLAIN(+0x3262ba)[0x55d2f6c762ba]
postgres: postgres postgres [local] EXPLAIN(ExplainQuery+0x991)[0x55d2f6c75f17]
postgres: postgres postgres [local] EXPLAIN(standard_ProcessUtility+0xa88)[0x55d2f7013b7a]
/usr/local/pgsql17/lib/timescaledb-2.20.0-dev.so(+0x65ebf)[0x7efd30dc9ebf]
/usr/local/pgsql17/lib/timescaledb-2.20.0-dev.so(+0x724f6)[0x7efd30dd64f6]
postgres: postgres postgres [local] EXPLAIN(ProcessUtility+0x109)[0x55d2f70130ba]
postgres: postgres postgres [local] EXPLAIN(+0x6c1994)[0x55d2f7011994]
postgres: postgres postgres [local] EXPLAIN(+0x6c16d1)[0x55d2f70116d1]
postgres: postgres postgres [local] EXPLAIN(PortalRun+0x253)[0x55d2f7010f94]
postgres: postgres postgres [local] EXPLAIN(+0x6b9a04)[0x55d2f7009a04]
postgres: postgres postgres [local] EXPLAIN(PostgresMain+0x847)[0x55d2f700ee27]
postgres: postgres postgres [local] EXPLAIN(+0x6b5809)[0x55d2f7005809]
postgres: postgres postgres [local] EXPLAIN(postmaster_child_launch+0x119)[0x55d2f6f19f1c]
postgres: postgres postgres [local] EXPLAIN(+0x5d0456)[0x55d2f6f20456]
postgres: postgres postgres [local] EXPLAIN(+0x5cd487)[0x55d2f6f1d487]
postgres: postgres postgres [local] EXPLAIN(PostmasterMain+0x1536)[0x55d2f6f1cd4c]
postgres: postgres postgres [local] EXPLAIN(+0x47a7f1)[0x55d2f6dca7f1]
/lib/x86_64-linux-gnu/libc.so.6(+0x2a1ca)[0x7efd3bffc1ca]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x8b)[0x7efd3bffc28b]
postgres: postgres postgres [local] EXPLAIN(_start+0x25)[0x55d2f6a2d535]
2025-04-16 11:22:28.339 EDT [7765] LOG:  server process (PID 7775) was terminated by signal 6: Aborted
2025-04-16 11:22:28.339 EDT [7765] DETAIL:  Failed process was running: explain SELECT count(DISTINCT time+1) FROM foo_ht;
```

### How can we reproduce the bug?

```bash
CREATE TABLE foo_ht(time int NOT NULL, dev int, dev_name text, val int);
    SELECT create_hypertable('foo_ht', 'time', chunk_time_interval => 250, create_default_indexes => false);
    INSERT INTO foo_ht(time,dev,dev_name,val) SELECT t, d, 'device_' || d::text, random() FROM generate_series(0, 100) t, generate_series(1, 10) d;
    ALTER TABLE foo_ht SET (timescaledb.compress,timescaledb.compress_orderby='time desc', timescaledb.compress_segmentby='dev');
    SELECT compress_chunk(ch) FROM show_chunks('foo_ht') ch;

    ---  Crashes because cannot find Var in count(DISTINCT time+1) argument
    ---  Sorted batch merge plan needs a Var to use for merging.
    ---  Crashes with SkipScan disabled, i.e. not related to SkipScan.
    explain SELECT count(DISTINCT time+1) FROM foo_ht;
        server closed the connection unexpectedly
```

### PR DESCRIPTION
**Pull request by natalya-aksman**
Fix crashes in batch sort merge over eligible OpExprs which were not recognized while setting up batch sort merge for decompression. 
Related to https://github.com/timescale/timescaledb/pull/7528.

Fixes #7975.

### CODE REVIEW

File: tsl/src/nodes/decompress_chunk/planner.c [hunk 1]
```diff
@@ -965,9 +966,10 @@ ts_label_sort_with_costsize(PlannerInfo *root, Sort *plan, double limit_tuples)
 static Var *
 find_var_subexpression(void *expr, Index varno)
 {
-	if (IsA(expr, Var))
+	Expr *transformed_expr = ts_sort_transform_expr((Expr *) expr);
```
Comment (svenklemm) [inline tsl/src/nodes/decompress_chunk/planner.c:969]: hmm wouldn't it be better to recurse into the expr to find the var instead call executing sort transform here

Comment (natalya-aksman) [reply tsl/src/nodes/decompress_chunk/planner.c:969]: We are using exactly the same logic which was used to do transform sort to set up PathKeys for BatchSortMerge, which is the point of the fix. 

Because we use this method while planning to see if we can transform valid expressions into Var PathKeys to use in BatchSortMerge. Then later we reverse those PathKeys back before execution, and then we try to get same Vars from PathKeys while actually setting up BatchSortMerge, but we use different logic, and that's why it breaks in many scenarios.

This method i.e. `ts_sort_transform_expr` also uses recursion i.e. it does recurse into valid expressions to look for Vars, but in this way we are consistent both when we check if we can use BatchSortMerge, and then wehn we actually using BatchSortMerge. We get same logic.

Comment (natalya-aksman) [reply tsl/src/nodes/decompress_chunk/planner.c:969]: See https://github.com/timescale/timescaledb/blob/9200d2f21f5eff3098e93d18266b94cbf06736e9/src/planner/planner.c#L1194    and  https://github.com/timescale/timescaledb/blob/9200d2f21f5eff3098e93d18266b94cbf06736e9/src/planner/planner.c#L1219   how we first transform PathKeys and then reset them back during TS planning.

Then in https://github.com/timescale/timescaledb/blob/9200d2f21f5eff3098e93d18266b94cbf06736e9/tsl/src/nodes/decompress_chunk/planner.c#L1149  we go for the same reset PathKeys to get same transformed Vars back.

**Review by akuzm — APPROVED** [review]
I think this is OK, this way we won't have mismatched logic. The copying inside `ts_sort_transform` might be a little excessive in this case, but not sure it's worth adding complications to avoid it.

**Comment by natalya-aksman** [comment]
> I think this is OK, this way we won't have mismatched logic. The copying inside `ts_sort_transform` might be a little excessive in this case, but not sure it's worth adding complications to avoid it.

We only do it for one key i.e. the last PathKey as BatchSortMerge can be only done for the last PathKey. So hopefully it's OK. The alternative is that maybe we can just save those transformed PathKeys somewhere in our custom paths instead of replacing them and then transforming them back?

**Comment by natalya-aksman** [comment]
> I think this is OK, this way we won't have mismatched logic. The copying inside `ts_sort_transform` might be a little excessive in this case, but not sure it's worth adding complications to avoid it.

On the other hand, we already checked for eligible expressions when transforming sort keys, so whatever PathKeys we have at the time of setting up BatchSortMerge should be valid, we just need to get Vars from that. We don't need to transform them again, I agree with @svenklemm here.

File: tsl/src/nodes/decompress_chunk/planner.c (hunk 1 above)
Comment (natalya-aksman) [reply tsl/src/nodes/decompress_chunk/planner.c]: I see that we should trust the initial check in sort_transform which will only allow valid expression Pathkeys to be transformed into Vars. When we set up BatchSortMerge we can just get Vars out Pathkeys via normal recursion.  It is done now, i.e. I addressed your comment @svenklemm .

**Review by svenklemm — APPROVED** [review]
