### PR TITLE
Fix option "timescaledb.create_group_indexes"

### LINKED ISSUE #4249: [Bug]: create_group_indexes option in caggs does not work properly
### What type of bug is this?

Incorrect result

### What subsystems and features are affected?

Continuous aggregate

### What happened?

Using the create_group_indexes option in caggs gives the same result whether you set the option to true or false. In both cases, it does not create group indexes.

More information in this docs issue: https://github.com/timescale/docs/issues/807

### TimescaleDB version affected

2.6.0

### PostgreSQL version used

14

### What operating system did you use?

whatever the default timescaledb-latest image is based on

### What installation method did you use?

Docker

### What platform did you run on?

On prem/Self-hosted

### Relevant log output and stack trace

_No response_

### How can we reproduce the bug?

```bash
create table test (
time timestamptz,
symbol int,
value numeric
);

select create_hypertable('test', 'time');

insert into test
(select generate_series(
	'2020-01-01',
    '2022-01-25', INTERVAL '30 sec'
  ),
  round(random()*10),
  random()*5);

 
create materialized view cagg_index_default
with (timescaledb.continuous) as 
select
	time_bucket('1 day', "time") as bucket,
	sum(value),
	symbol 
from test 
group by bucket, symbol 

create materialized view cagg_index_false
with (timescaledb.continuous, timescaledb.create_group_indexes = false) as 
select
	time_bucket('1 day', "time") as bucket,
	sum(value),
	symbol 
from test 
group by bucket, symbol 

create materialized view cagg_index_true
with (timescaledb.continuous, timescaledb.create_group_indexes = true) as 
select
	time_bucket('1 day', "time") as bucket,
	sum(value),
	symbol 
from test 
group by bucket, symbol 


select i.*
from pg_indexes i
join pg_class c
    on schemaname = relnamespace::regnamespace::text 
    and tablename = relname
where tablename like '_materialized_hypertable%'
order by tablename
    
select * from timescaledb_information.continuous_aggregates ca
```

### PR DESCRIPTION
**Pull request by konskov**
Previously this option was ignored when creating a
continuous aggregate, even when explicitly set to true.

Fixes #4249

### CODE REVIEW

**Review by svenklemm — COMMENTED** [review]
Dont forget to add CHANGELOG entry

File: tsl/test/sql/continuous_aggs.sql [hunk 1]
```diff
@@ -1226,3 +1226,72 @@ FROM issue3248 GROUP BY 1,2;
...
+
+\gset
+
+\d+ :mat_hyper_cagg_index_true
+
+SELECT format('%I.%I', materialization_hypertable_schema,
+materialization_hypertable_name) AS mat_hyper_cagg_index_false
+FROM timescaledb_information.continuous_aggregates where view_name like 'cagg_index_false';
+
+\gset
```
Comment (mfundul) [inline tsl/test/sql/continuous_aggs.sql:1289]:
```suggestion
SELECT format('%I.%I', materialization_hypertable_schema,
materialization_hypertable_name) AS mat_hyper_cagg_index_false
FROM timescaledb_information.continuous_aggregates where view_name like 'cagg_index_false' \gset
```
To speed up the queries, instead of executing them twice.

File: tsl/test/expected/continuous_aggs.out [hunk 2]
```diff
@@ -1738,3 +1738,107 @@ SELECT
...
+ (48,public,test_group_idx,t)
+(1 row)
+
+insert into test_group_idx
+(select generate_series(
+	'2020-01-01',
+    '2020-02-25', INTERVAL '30 sec'
+  ),
+  round(random()*10),
+  random()*5);
```
Comment (fabriziomello) [inline tsl/test/expected/continuous_aggs.out:1760]:
```suggestion
insert into test_group_idx
select t, round(random()*10), random()*5
from generate_series('2020-01-01', '2020-02-25', INTERVAL '12 hours') t;
```
Why too many rows in the tests?? Do we really need it??? What about use `12 hours` so it will produce two rows for each time bucket.

File: tsl/test/expected/continuous_aggs.out [hunk 3]
```diff
@@ -1738,3 +1738,107 @@ SELECT
...
+ agg_2_2  | bytea                    |           |          |         | extended |              | 
+ symbol   | integer                  |           |          |         | plain    |              | 
+ chunk_id | integer                  |           |          |         | plain    |              | 
+Indexes:
+    "_materialized_hypertable_49_bucket_idx" btree (bucket DESC)
+    "_materialized_hypertable_49_symbol_bucket_idx" btree (symbol, bucket DESC)
+Triggers:
+    ts_insert_blocker BEFORE INSERT ON _timescaledb_internal._materialized_hypertable_49 FOR EACH ROW EXECUTE FUNCTION _timescaledb_internal.insert_blocker()
+Child tables: _timescaledb_internal._hyper_49_106_chunk,
+              _timescaledb_internal._hyper_49_107_chunk
```
Comment (fabriziomello) [inline tsl/test/expected/continuous_aggs.out:1804]: I'm always wondering about it and why we don't define a standard because there are several places using test support functions like `test.show_columns` and `test.show_columnsp` (test/sql/utils/testsupport.sql).

**Comment by mfundul** [comment]
You should fix the commit message to show `Fixes #4249`. Also please update the title of the PR and the body to reflect the new commit message.

**Comment by mfundul** [comment]
I think we need an extra test case. In the last test case, you create a CAGG with default parameters. We should make sure that `ALTER MATERIALIZED VIEW` also works. E.g. default => true => false

**Comment by konskov** [comment]
Hmm I'm not sure I understand how to test that. According to [our documentation](https://docs.timescale.com/api/latest/continuous-aggregates/alter_materialized_view/#alter-materialized-view-continuous-aggregate) (and  implementation) setting the option `create_group_indexes` is not possible with `ALTER MATERIALIZED VIEW`, it's an option that can be set only upon cagg creation. If I try and set this option with `ALTER` I will get the error: `ERROR:  cannot alter create_group_indexes option for continuous aggregates`. So I didn't understand what the extra test case is meant to check?

**Review by mfundul — APPROVED** [review]

**Review by svenklemm — APPROVED** [review]

**Review by fabriziomello — APPROVED** [review]

**Comment by charislam** [comment]
Thanks @konskov! 💖 Quick clarification so I can improve the docs: is the default behavior `true`?

**Comment by konskov** [comment]
@charislam yes, the default behavior is `true`.
