### PR TITLE
Fix gapfill crash with locf NULL values treated as missing

### LINKED ISSUE #6078: Crash with a particular query that uses `time_bucket_gapfill`, `time_weight` and `locf` (see description for a test case)
### What type of bug is this?

Crash

### What subsystems and features are affected?

Background worker, Gapfill, Other

### What happened?

After chatting on Slack about a specific use case we had, we got an example solution which we incorporated in our setup. It seemed to work fine, but the next day we noticed occasional errors happening at random intervals throughout the day. 

We started investigating and debugging (mainly by eliminating data and logic) until we got to the query posted below which triggers the problem and shows `ERROR: SSL SYSCALL error: EOF detected`

Some additional findings we found when testing:

1. When we replace `average(time_weight('linear',"x"."time","x"."value"))` with just `avg("x"."value")` the problem goes away.
2. When we keep using the `time_weight` ’ed version but change `TRUE` to `FALSE` for the `treat_null_as_missing` argument of the `locf` function, the problem also goes away.
3. When we change the timestamp of the second row in the `data` CTE so it falls out of the time range we are trying to query (even by 1 millisecond), the problem also goes way.

So in our opinion the problem is somehow caused by using the combination of `time_bucket_gapfill`, `time_weight` and `locf` and tweaking the inputs of any of these seems to prevent the issue from happening. Unfortunately our use case requires exactly these settings (😏) so we would love to find a solutions for this.

Thanks!


### TimescaleDB version affected

2.11.2

### PostgreSQL version used

15.4

### What operating system did you use?

Ubuntu 22.04 ARM

### What installation method did you use?

Docker

### What platform did you run on?

On prem/Self-hosted

### Relevant log output and stack trace

```bash
2023-09-15 13:00:47 UTC [25984]: [6504557f.6580-2] persister@helixer,app=[unknown] [57P03] FATAL:  the database system is in recovery mode
2023-09-15 13:00:47 UTC [25991]: [6504557f.6587-1] @,app= [00000] LOG:  TimescaleDB background worker launcher connected to shared catalogs
2023-09-15 13:00:47 UTC [84]: [65040295.54-206] @,app= [00000] LOG:  database system is ready to accept connections
2023-09-15 13:00:47 UTC [25983]: [6504557e.657f-7] @,app= [00000] LOG:  checkpoint complete: wrote 2050 buffers (6.6%); 0 WAL file(s) added, 0 removed, 1 recycled; write=0.044 s, sync=0.004 s, total=0.051 s; sync files=74, longest=0.001 s, average=0.001 s; distance=18862 kB, estimate=18862 kB
2023-09-15 13:00:47 UTC [25983]: [6504557e.657f-6] @,app= [00000] LOG:  checkpoint starting: end-of-recovery immediate
2023-09-15 13:00:47 UTC [25983]: [6504557e.657f-5] @,app= [00000] LOG:  redo done at 0/2A27DF18 system usage: CPU: user: 0.02 s, system: 0.00 s, elapsed: 0.03 s
2023-09-15 13:00:47 UTC [25984]: [6504557f.6580-1] [unknown]@[unknown],app=[unknown] [00000] LOG:  connection received: host=10.244.0.42 port=57308
2023-09-15 13:00:47 UTC [25983]: [6504557e.657f-4] @,app= [00000] LOG:  redo starts at 0/29014608
2023-09-15 13:00:47 UTC [25983]: [6504557e.657f-3] @,app= [00000] LOG:  database system was not properly shut down; automatic recovery in progress
2023-09-15 13:00:47 UTC [25983]: [6504557e.657f-2] @,app= [00000] LOG:  recovered replication state of node 1 to 0/E293070
2023-09-15 13:00:46 UTC [25983]: [6504557e.657f-1] @,app= [00000] LOG:  database system was interrupted; last known up at 2023-09-15 12:57:40 UTC
2023-09-15 13:00:46 UTC [84]: [65040295.54-205] @,app= [00000] LOG:  all server processes terminated; reinitializing
2023-09-15 13:00:46 UTC [84]: [65040295.54-202] @,app= [00000] LOG:  server process (PID 25871) was terminated by signal 11: Segmentation fault
```


### How can we reproduce the bug?

```bash
Run the blow query:


WITH ids(id) AS (                                                                                                                                                                             
  VALUES                                                                                                                                                                                      
    ('9930d121-3667-4f41-8f5b-db834fb95cc7')                                                                                                                                                  
),
"data" ("id", "time", "value") AS (                                                                                                                                                           
  VALUES                                                                                                                                                                                           
    ('9930d121-3667-4f41-8f5b-db834fb95cc7', '2023-09-15 12:52:57.308+00'::TIMESTAMPTZ, 147673::FLOAT8),
    ('9930d121-3667-4f41-8f5b-db834fb95cc7', '2023-09-15 12:52:59.308+00'::TIMESTAMPTZ, 149400::FLOAT8)                                                                                      
),                                                                                                                                                                                                                                                                                                                                                                                 
"gapfill" AS ( SELECT                                                                                                                                                                         
  "x"."id",                                                                                                                                                                                   
  public.time_bucket_gapfill(INTERVAL '1 second', "x"."time", '2023-09-15 12:52:59.141+00:00'::TIMESTAMPTZ, '2023-09-15 12:53:00.141+00:00'::TIMESTAMPTZ) AS bucket,                             
  public.locf(average(time_weight('LOCF', "x"."time", "x"."value")), (                                                                                                                                                                                                                                                                                                                                                           
    SELECT "p"."value"                                                                                                                                                                        
    FROM data AS p                                                                                                                                                                          
    WHERE "p"."id" = "x"."id" AND "p"."time" < '2023-09-15 12:52:59.141+00:00'                                                                                                             
    ORDER BY "p"."time" DESC                                                                                                                                                                  
    LIMIT 1                                                                                                                                                                                   
  ), TRUE) AS value                                                                                                                                                                           
FROM (                                                                                                                                                                                        
SELECT id, '-Infinity'::TIMESTAMPTZ AS time, NULL AS value FROM ids                                                                                                                             
UNION ALL                                                                                                                                                                                     
SELECT * FROM data x                                                                                                                                                                          
WHERE "x"."time" > '2023-09-15 12:52:59.141+00:00' AND "x"."time" < '2023-09-15 12:53:00.141+00:00'                                                                                  
) AS x                                                                                                                                                                                        
WHERE "x"."id" IN ('9930d121-3667-4f41-8f5b-db834fb95cc7')                                                                                            
GROUP BY "x"."id", "bucket"                                                                                                                                                                   
ORDER BY "bucket" DESC                                                                                                                                                                        
)                                                                                                                                                                                             
SELECT * FROM gapfill WHERE bucket <> '-Infinity'
```

### PR DESCRIPTION
**Pull request by natalya-aksman**
Fixes #6078
Calculate `locf` for missing NULLs on the correct tuple slot.

### CODE REVIEW

**Review by svenklemm — APPROVED** [review]

**Comment by svenklemm** [comment]
needs changelog entry

File: tsl/src/nodes/gapfill/gapfill_exec.c [hunk 1]
```diff
@@ -1380,7 +1380,11 @@ gapfill_exec_expr(GapFillState *state, Expr *expr, bool *isnull)
 	ExprState *exprstate = ExecInitExpr(expr, &state->csstate.ss.ps);
 	ExprContext *exprcontext = GetPerTupleExprContext(state->csstate.ss.ps.state);
 
-	exprcontext->ecxt_scantuple = state->scanslot;
+	/* We can execute expression over a generated tuple which fills the gap (state->scanslot)
+	 * or over an input tuple (state->subslot) to override NULL value when NULLs are treated as
+	 * missing. Use the correct tuple slot for the purpose.
+	 */
+	exprcontext->ecxt_scantuple = (TupIsNull(state->scanslot) ? state->subslot : state->scanslot);
```
Comment (akuzm) [inline tsl/src/nodes/gapfill/gapfill_exec.c:1387]: This is a generic function that is called for calculating many different expressions, not only locf. This logic is locf-specific and not applicable to e.g. evaluating the start/finish arguments. Let's pass the argument tuple table slot as an argument to this function.

File: tsl/src/nodes/gapfill/gapfill_exec.c [hunk 2]
```diff
@@ -1380,7 +1380,11 @@ gapfill_exec_expr(GapFillState *state, Expr *expr, bool *isnull)
 	ExprState *exprstate = ExecInitExpr(expr, &state->csstate.ss.ps);
 	ExprContext *exprcontext = GetPerTupleExprContext(state->csstate.ss.ps.state);
 
-	exprcontext->ecxt_scantuple = state->scanslot;
+	/* We can execute expression over a generated tuple which fills the gap (state->scanslot)
+	 * or over an input tuple (state->subslot) to override NULL value when NULLs are treated as
+	 * missing. Use the correct tuple slot for the purpose.
+	 */
```
Comment (akuzm) [inline tsl/src/nodes/gapfill/gapfill_exec.c:1386]: scanslot is an unsuitable name for this. In Postgres it means the tuple produced inside the scan but before projection. In fact in this plan it contains only the scan tuples that were generated, not the ones that were returned from subplan as is. I think this is the source of confusion, the current code treats it as "last scan tuple" or something. Maybe we should have the explicit "last scan tuple" variable? Then it can be used for locf and other functions directly without additional checks.

Note that "null values" and "null slots" are different, null slot means "no row", not "row with null value".

Comment (akuzm) [reply tsl/src/nodes/gapfill/gapfill_exec.c:1386]: In general it seems that it's not related to locf null-handling logic in particular. The null values are contained to locf and shouldn't change the state of the gapfill executor. The gapfill state transitions are dependent only on the settings and the input tuples, not the interpolation function, right? I think it would be good to avoid weird states and provide the predictable "last scan tuple" for the interpolation functions.

Comment (natalya-aksman) [reply tsl/src/nodes/gapfill/gapfill_exec.c:1386]: Yes, we call locf null-handling logic from two different contexts and it assumes the set up from one of the contexts which does not work for the other context. Making it the same valid context for both scenarios via "last scan tuple" looks like a good idea, will look into it.

Comment (natalya-aksman) [reply tsl/src/nodes/gapfill/gapfill_exec.c:1386]: So, to summarize:

- pass tuple slot into `gapfill_exec_expr`
- add `last_scan_tuple_slot` to GapFill state, which is used for interpolation functions
- call `gapfill_exec_expr` with the correct slot depending on the caller - whether it's an interpolation function or if we are computing expressions for generated gap-filling tuples.

Comment (natalya-aksman) [reply tsl/src/nodes/gapfill/gapfill_exec.c:1389]: Decided to only do the 1st item during the team meeting.

File: tsl/src/nodes/gapfill/gapfill_exec.c [hunk 3]
```diff
@@ -786,7 +787,7 @@ gapfill_begin(CustomScanState *node, EState *estate, int eflags)
 					(errcode(ERRCODE_INVALID_PARAMETER_VALUE),
 					 errmsg("invalid time_bucket_gapfill argument: finish must be a simple "
 							"expression")));
-		arg_value = gapfill_exec_expr(state, get_finish_arg(state), &isnull);
+		arg_value = gapfill_exec_expr(state, state->scanslot, get_finish_arg(state), &isnull);
```
Comment (akuzm) [inline tsl/src/nodes/gapfill/gapfill_exec.c:790]: In "begin" function, I think we can explicitly pass NULL here, because it's clear we're not evaluating the expression on some scan row, it happens before the scan begins.

File: tsl/src/nodes/gapfill/gapfill_exec.c [hunk 4]
```diff
@@ -1375,12 +1378,16 @@ gapfill_aggref_mutator(Node *node, void *context)
...
  */
 Datum
-gapfill_exec_expr(GapFillState *state, Expr *expr, bool *isnull)
+gapfill_exec_expr(GapFillState *state, TupleTableSlot *ecxt_slot, Expr *expr, bool *isnull)
 {
 	ExprState *exprstate = ExecInitExpr(expr, &state->csstate.ss.ps);
 	ExprContext *exprcontext = GetPerTupleExprContext(state->csstate.ss.ps.state);
 
-	exprcontext->ecxt_scantuple = state->scanslot;
+	/* We can execute expression over a generated tuple which fills the gap (state->scanslot)
```
Comment (akuzm) [inline tsl/src/nodes/gapfill/gapfill_exec.c:1386]: Let's move the comment to the relevant call site as well.

**Review by akuzm — APPROVED** [review]

File: tsl/src/nodes/gapfill/gapfill_exec.c (hunk 3 above)
Comment (akuzm) [reply tsl/src/nodes/gapfill/gapfill_exec.c:790]: It might be syntactically allowed, so we might need a test... Maybe as a follow up PR if this turns out complicated.

Comment (natalya-aksman) [reply tsl/src/nodes/gapfill/gapfill_exec.c:790]: Agree! Will do.

Comment (natalya-aksman) [reply tsl/src/nodes/gapfill/gapfill_exec.c]: Done.

File: tsl/src/nodes/gapfill/gapfill_exec.c (hunk 4 above)
Comment (natalya-aksman) [reply tsl/src/nodes/gapfill/gapfill_exec.c]: Done.

**Comment by natalya-aksman** [comment]
@akuzm: to follow up on the team discussion, added more tests with 2 correlations vars in the lookup expression and with a correlation var with different attnum, to make sure they are picked up from the correct tuple and correspond to the correct attribute in a tuple. Looks like if we give the lookup a correct tuple it picks up correct values from it.
