### PR TITLE
Fix targetlist for cagg views

### LINKED ISSUE #3051: Update from v2.0.0 to v2.1.0 fails because of ALTER on continuous aggregate
**Relevant system information:**
 - PostgreSQL version: 12
 - TimescaleDB version: 2.0.0
 - Installation method: docker

**Describe the bug**
when performing the ALTER EXTENSION query, the following error is thrown:
```sql
ALTER EXTENSION timescaledb UPDATE
INFO:  cmd executed: ALTER MATERIALIZED VIEW "<view_name>" SET (timescaledb.materialized_only=false)
ERROR:  SELECT rule's target entry 1 has different column name from column "t"
DETAIL:  SELECT target entry is named "someName".
CONTEXT:  SQL statement "ALTER MATERIALIZED VIEW "<view_name>"" SET (timescaledb.materialized_only=false) "
```
**To Reproduce**
1. Create a materialized view with a similar definition to this one:

```
 SELECT time_bucket('00:15:00'::interval, "<original_table>i".t) AS "someName",
    count("<original_table>".something) AS count,
   FROM "<original_table>"
  GROUP BY (time_bucket('00:15:00'::interval, "<original_table>".t)), "<original_table>".somethingElse;
```

**Expected behavior**
Update goes well

**Actual behavior**
Update fails

### LINKED ISSUE #3405: Upgrade to 2.3.1 fails due to renamed columns in continuous aggregate
**Relevant system information:**
 - OS: Ubuntu 18.04
 - PostgreSQL version (output of `postgres --version`): 12.6
 - TimescaleDB version (output of `\dx` in `psql`): 2.1.0
 - Installation method: AMI originally, upgrading via apt install
 
**Describe the bug**
When columns in a continuous aggregate are renamed, the upgrade to 2.3.1 fails.

**To Reproduce**
1. On TimescaleDB 2.1.0, create a hypertable and a continuous aggregate
2. Use `ALTER MATERIALIZED VIEW x RENAME COLUMN` to rename a column -- for example, to rename `bucket` to `time`
3. Follow the upgrade procedures to upgrade to TimescaleDB 2.3.1
4. Upgrade will fail while running a migrate step for the continuous aggregate

**Expected behavior**
Upgrading should handle renaming a column in the continuous aggregate.

**Actual behavior**
The upgrade fails because of the renamed column.

**Screenshots**
```
ubuntu@ip-172-31-23-183:~$ psql --user postgres;
psql (12.6 (Ubuntu 12.6-1.pgdg18.04+1))
Type "help" for help.

postgres=# create database tsdb_test;
CREATE DATABASE
postgres=# \c tsdb_test;
You are now connected to database "tsdb_test" as user "postgres".
tsdb_test=# create extension timescaledb version '2.1.0';
WARNING:
WELCOME TO
 _____ _                               _     ____________
|_   _(_)                             | |    |  _  \ ___ \
  | |  _ _ __ ___   ___  ___  ___ __ _| | ___| | | | |_/ /
  | | | |  _ ` _ \ / _ \/ __|/ __/ _` | |/ _ \ | | | ___ \
  | | | | | | | | |  __/\__ \ (_| (_| | |  __/ |/ /| |_/ /
  |_| |_|_| |_| |_|\___||___/\___\__,_|_|\___|___/ \____/
               Running version 2.1.0
For more information on TimescaleDB, please visit the following links:

 1. Getting started: https://docs.timescale.com/getting-started
 2. API reference documentation: https://docs.timescale.com/api
 3. How TimescaleDB is designed: https://docs.timescale.com/introduction/architecture

Note: TimescaleDB collects anonymous reports to better understand and assist our users.
For more information and how to disable, please see our docs https://docs.timescaledb.com/using-timescaledb/telemetry.

CREATE EXTENSION
tsdb_test=# \dx
                                      List of installed extensions
    Name     | Version |   Schema   |                            Description
-------------+---------+------------+-------------------------------------------------------------------
 plpgsql     | 1.0     | pg_catalog | PL/pgSQL procedural language
 timescaledb | 2.1.0   | public     | Enables scalable inserts and complex queries for time-series data
(2 rows)

tsdb_test=# CREATE TABLE conditions (
tsdb_test(#     time        TIMESTAMPTZ       NOT NULL,
tsdb_test(#     location    TEXT              NOT NULL,
tsdb_test(#     temperature DOUBLE PRECISION  NULL
tsdb_test(# );
CREATE TABLE
tsdb_test=# SELECT create_hypertable('conditions', 'time');
    create_hypertable
-------------------------
 (1,public,conditions,t)
(1 row)

tsdb_test=# create materialized view conditions_daily WITH (timescaledb.continuous) AS
tsdb_test-# SELECT location, time_bucket(INTERVAL '1 day', time) AS bucket, AVG(temperature) FROM conditions GROUP BY lo
cation, bucket;
NOTICE:  continuous aggregate "conditions_daily" is already up-to-date
CREATE MATERIALIZED VIEW
tsdb_test=# SELECT add_continuous_aggregate_policy('conditions_daily', start_offset => INTERVAL '1 month', end_offset =>
 INTERVAL '1 day', schedule_interval => INTERVAL '1 hour');
 add_continuous_aggregate_policy
---------------------------------
                            1000
(1 row)

tsdb_test=# ALTER MATERIALIZED VIEW conditions_daily RENAME COLUMN bucket to "time";
ALTER TABLE
tsdb_test=# \q

ubuntu@ip-172-31-23-183:~$ psql -X --user postgres tsdb_test;
psql (12.6 (Ubuntu 12.6-1.pgdg18.04+1))
Type "help" for help.

tsdb_test=# alter extension timescaledb update;
INFO:  cmd executed: ALTER MATERIALIZED VIEW conditions_daily SET (timescaledb.materialized_only='f')
ERROR:  SELECT rule's target entry 2 has different column name from column "time"
DETAIL:  SELECT target entry is named "bucket".
CONTEXT:  SQL statement "ALTER MATERIALIZED VIEW conditions_daily SET (timescaledb.materialized_only='f') "
PL/pgSQL function inline_code_block line 25 at EXECUTE
tsdb_test=#
```

**Additional context**

### PR DESCRIPTION
**Pull request by mkindahl**
If the names for entries in the targetlist for the direct and partial
views of the continuous aggregate does not match the attribute names in
the tuple descriptor for the result tuple of the user view an error
will be generated. This commit fixes this by setting the targetlist
resource names of the columns in the direct and partial view to the 
corresponding attribute name of the user view relation tuple
descriptor.

Fixes #3051
Fixes #3405

### CODE REVIEW

**Comment by mkindahl** [comment]
Unsure how to test this since it requires the fix to be applied to the source version in the update. Adding a `ALTER MATERIALIZED VIEW...RENAME COLUMN` to the update tests will cause the tests to fail since it is not in released versions, but the fix is in the latest version.

File: tsl/src/continuous_aggs/create.c [hunk 1]
```diff
@@ -1855,12 +1856,23 @@ cagg_update_view_definition(ContinuousAgg *agg, Hypertable *mat_ht,
...
+	TupleDesc desc = RelationGetDescr(user_view_rel);
+	int i = 0;
 	forboth (lc1, view_query->targetList, lc2, user_query->targetList)
 	{
 		TargetEntry *view_tle, *user_tle;
+		FormData_pg_attribute *attr = TupleDescAttr(desc, i);
 		view_tle = lfirst_node(TargetEntry, lc1);
 		user_tle = lfirst_node(TargetEntry, lc2);
-		view_tle->resname = user_tle->resname;
+		ereport(LOG,
```
Comment (gayyappan) [inline tsl/src/continuous_aggs/create.c:1867]: I think you added this for testing. We do not need a LOG message here. 
We need a test case for this change.
Would also help to have a comment in the code explaining why we have to match the names using the user_view_rel  and not the query. It is not obvious why there would be a discrepancy.

**Review by gayyappan — COMMENTED** [review]
The commit message is not clear. Could you rewrite it to describe the problem better?

File: tsl/src/continuous_aggs/create.c (hunk 1 above)
Comment (mkindahl) [reply tsl/src/continuous_aggs/create.c]: Log message removed. Test case added (also an update test, which is what the original bug report was about). Tried to add an explanation.

**Comment by mkindahl** [comment]
> Unsure how to test this since it requires the fix to be applied to the source version in the update. Adding a `ALTER MATERIALIZED VIEW...RENAME COLUMN` to the update tests will cause the tests to fail since it is not in released versions, but the fix is in the latest version.

Added an update test to check if the rename works. It is not obvious how to "fix" the problem by renaming columns of the views. Even if that is done, the error is still generated.

**Comment by mkindahl** [comment]
> > Unsure how to test this since it requires the fix to be applied to the source version in the update. Adding a `ALTER MATERIALIZED VIEW...RENAME COLUMN` to the update tests will cause the tests to fail since it is not in released versions, but the fix is in the latest version.
> 
> Added an update test to check if the rename works. It is not obvious how to "fix" the problem by renaming columns of the views. Even if that is done, the error is still generated.

Update test is working since the rebuilding is done using the new library, not the original one with the bug in it.

File: tsl/src/continuous_aggs/create.c [hunk 2]
```diff
@@ -1851,16 +1852,26 @@ cagg_update_view_definition(ContinuousAgg *agg, Hypertable *mat_ht,
...
+	TupleDesc desc = RelationGetDescr(user_view_rel);
+	int i = 0;
 	forboth (lc1, view_query->targetList, lc2, user_query->targetList)
 	{
 		TargetEntry *view_tle, *user_tle;
+		FormData_pg_attribute *attr = TupleDescAttr(desc, i);
 		view_tle = lfirst_node(TargetEntry, lc1);
 		user_tle = lfirst_node(TargetEntry, lc2);
-		view_tle->resname = user_tle->resname;
+		view_tle->resname = user_tle->resname = NameStr(attr->attname);
```
Comment (mfundul) [inline tsl/src/continuous_aggs/create.c:1873]: Is there maybe a lifetime problem with this C string here? `TupleDesc` has been taken from `user_view_rel`, which is closed early (`relation_close(user_view_rel, NoLock);`) and those `resname` pointers are still being used after that.

Comment (mkindahl) [reply tsl/src/continuous_aggs/create.c:1873]: Good catch, yes it can be a problem. It works normally because `relation_close` only decrement the reference count, but if `RELCACHE_FORCE_RELEASE` is set then the memory will be freed directly and would trigger a problem. Moved the `relation_close` to after the `StoreViewQuery`.

**Review by mfundul — APPROVED** [review]

**Comment by afiskon** [comment]
I agree with @gayyappan  that the commit message is a little bit too complicated. I would simply say that the commit fixes given bugs, and that more details can be found in the corresponding comments.

**Review by afiskon — APPROVED** [review]

**Review by gayyappan — APPROVED** [review]
Request to alter the comment slightly.  
ALTER .. RENAME  should propagate the changes to the view as well. Discussed with Mats and decided this will be done in a follow-up PR.
