### PR TITLE
Fix ALTER SET/DROP NULL contstraint on dist hypertable

### LINKED ISSUE #3860: [Enhancement]: Support Dropping NULL Constraint on Distributed Hypertables
### What type of bug is this?

Unexpected error

### What subsystems and features are affected?

Distributed hypertable

### What happened?

The [documentation](https://docs.timescale.com/timescaledb/latest/how-to-guides/hypertables/alter/) suggests that `ALTER TABLE` commands work on distributed hypertables, but it appears that not all alterations are supported. When trying to drop a `NULL` constraint on a column an error was returned stating this operation isn't supported on distributed hypertables: `ERROR:  operation not supported on distributed hypertable`

### TimescaleDB version affected

2.5.0

### PostgreSQL version used

13.5

### What operating system did you use?

Managed Timescale

### What installation method did you use?

Not applicable

### What platform did you run on?

Managed Service for TimescaleDB (MST/Aiven)

### Relevant log output and stack trace

```bash
db-pool=> \dx
                                      List of installed extensions
    Name     | Version |   Schema   |                            Description                            
-------------+---------+------------+-------------------------------------------------------------------
 plpgsql     | 1.0     | pg_catalog | PL/pgSQL procedural language
 timescaledb | 2.5.0   | public     | Enables scalable inserts and complex queries for time-series data
(2 rows)

db-pool=> ALTER TABLE my_table ALTER COLUMN my_column DROP NOT NULL;
ERROR:  operation not supported on distributed hypertable
```

### How can we reproduce the bug?

```bash
Create a distributed hypertable with a column with a `NOT NULL` constraint. Attempt to update the column to remove the constraint.
```

### PR DESCRIPTION
**Pull request by pmwkaa**
This change adds support for `ALTER TABLE SET/DROP NULL` commands
to the list of supported commands that can be run with
distributed hypertable.

Fix #3860

### CODE REVIEW

**Review by erimatnor — COMMENTED** [review]
Looks like there's something wrong with the tests since there's a CI failure.

Also, as good practice, I think we should always have a proper commit log description. I realize that this isn't a big fix, but I think nevertheless that it is useful to have an explanation in the log for what the problem was and how it is fixed. People reading the commit log might not have access to the original issue.

File: tsl/src/remote/dist_ddl.c [hunk 1]
```diff
@@ -681,6 +681,8 @@ dist_ddl_process_alter_table(ProcessUtilityArgs *args)
 			case AT_AddConstraintRecurse:
 			case AT_DropConstraint:
 			case AT_DropConstraintRecurse:
+			case AT_SetNotNull:
+			case AT_DropNotNull:
```
Comment (mkindahl) [inline tsl/src/remote/dist_ddl.c:685]: Why does adding these lines solve the problem?

**Review by mkindahl — COMMENTED** [review]
Please add a description of what this pull request solves and how.

It's hard for me to understand the context and the solution without a description and I should not have to dig through the issue to understand what the problem is and how your pull request solve the problem.

File: tsl/src/remote/dist_ddl.c (hunk 1 above)
Comment (pmwkaa) [reply tsl/src/remote/dist_ddl.c:685]: That's basically a whitelist of ALTER commands that can be run on dist hypertable

**Review by akuzm — APPROVED** [review]

**Review by erimatnor — APPROVED** [review]
