### PR TITLE
Fix timeout handling in async library

### LINKED ISSUE #2645: compress_chunk() fails with timeout on distributed chunk
``` SQL
select compress_chunk('_timescaledb_internal._dist_hyper_20_30_chunk');
ERROR:  async operation timed out
```

Source of the problem:

When executing remote function we expect it to finish within 1 hour, using hard-coded timeout value: https://github.com/timescale/timescaledb/blob/master/tsl/src/remote/async.h#L140 and then downgrade it to 1 min here: https://github.com/timescale/timescaledb/blob/master/tsl/src/remote/async.c#L644

### LINKED ISSUE #2646: Improve handling of timeouts and cancellations in distributed queries
A distributed query should not timeout unless by user request or `statement_timeout` being reached (on the access node or data nodes).

We should try to execute queries until any of these conditions are met, the query completes by itself, or some other error occurs.

If the query is cancelled on the access node, we need to cancel all the queries on the data node connections, or, alternatively, close the connections.

### PR DESCRIPTION
**Pull request by erimatnor**
This change removes a hard-coded 1 minute connection timeout that
would cause long-running queries and commands (e.g., compressing a
chunk) to time out before completion. Queries can still be canceled by
the user or the database when `statement_timeout` is reached.

One exception where timeouts is still used is cleanup during
transaction abort (e.g., sending a `ROLLBACK` statement to a data node
in the abort handler). Queries sent at this stage should have a
timeout since they occur in the transaction abort handler after the
main query has already been canceled or reached `statement_timeout`.

Fixes #2645
Closes #2646

### CODE REVIEW

**Comment by erimatnor** [comment]
Adding a little bit more context for this PR here.

Testing is of course a bit tricky given that this is about timeouts. We don't want a test that, e.g., waits 1 minute or more to test that we don't timeout requests that take longer than 1 minute. I did test the following manually

```
CALL distributed_exec($$ SELECT pg_sleep(70); $$);
```

this query timeouts without the fix, but works correctly with the changes in this PR.

Also, I opted to more or less copy the code for handling cleanup request/responses from the postgres_fdw. Our connection/async code is originally based on the postgres_fdw, but in this case the code wasn't adopted correctly for our use case. Therefore, this PR reintroduces some code from the postgres_fdw to correctly handle responses to "cleanup" queries sent during abort handling. In the future, we probably want to do some major refactoring of the async library to better adapt the code for our use case (e.g., multi-remote node handling vs just one remote node in postgres_fdw). For instance, currently, abort queries are not sent and received asynchronously across data nodes.

File: tsl/src/remote/async.c [hunk 1]
```diff
@@ -512,6 +512,137 @@ async_request_wait_ok_result(AsyncRequest *req)
...
+ * abort to get the remote side back to the appropriate state.
+ *
+ * endtime is the time at which we should give up and assume the remote
+ * side is dead.
+ *
+ * An AsyncReponse is always returned, indicating last PGresult received,
+ * a timeout, or error.
+ */
+AsyncResponse *
+async_request_cleanup_result(AsyncRequest *req, TimestampTz endtime)
```
Comment (erimatnor) [inline tsl/src/remote/async.c:529]: This function is adopted more or less verbatim from postgres_fdw (PG12).

File: tsl/src/remote/async.c [hunk 2]
```diff
@@ -512,6 +512,137 @@ async_request_wait_ok_result(AsyncRequest *req)
...
+				/* If timeout has expired, give up, else get sleep time. */
+				if (now >= endtime)
+				{
+					timed_out = true;
+					goto exit;
+				}
+				TimestampDifference(now, endtime, &secs, &microsecs);
+
+				/* To protect against clock skew, limit sleep to one minute. */
+				cur_timeout = Min(60000, secs * USECS_PER_SEC + microsecs);
```
Comment (k-rus) [inline tsl/src/remote/async.c:580]: `60000` is a minute, right? Can a constant with meaningful name be used here?

File: tsl/src/remote/async.c [hunk 3]
```diff
@@ -512,6 +512,137 @@ async_request_wait_ok_result(AsyncRequest *req)
...
+
+				/* Sleep until there's something to do */
+				wc = WaitLatchOrSocket(MyLatch,
+									   WL_LATCH_SET | WL_SOCKET_READABLE
+#if PG12_GE
+										   | WL_EXIT_ON_PM_DEATH
+#endif
+										   | WL_TIMEOUT,
```
Comment (k-rus) [inline tsl/src/remote/async.c:588]: It might be good to extract this flag combination into a constant or function as it seems to be similar to the flag combination in https://github.com/timescale/timescaledb/blob/master/tsl/src/remote/connection.c#L1524-L1525

File: tsl/src/remote/async.c [hunk 4]
```diff
@@ -512,6 +512,137 @@ async_request_wait_ok_result(AsyncRequest *req)
...
+			{
+				remote_connection_set_processing(req->conn, false);
+				async_request_set_state(req, COMPLETED);
+				break; /* query is complete */
+			}
+
+			PQclear(last_res);
+			last_res = res;
+		}
+	exit:;
```
Comment (k-rus) [inline tsl/src/remote/async.c:619]: Goto labels are usually without any indentation. Should this place be consistent too?

**Review by k-rus — APPROVED** [review]
LGTM, few minor nits in review comments.

I had an issue to understand the commit message. I have to read the issues and the code to understand it, thus it would be good to improve it.

In the commit message:
>Fix an issue were remote queries to data nodes always timed out after
1 minute.

It is not fully clear why it is an issue with just this description. I suggest to mention that the timeout leads that long-running operations cannot complete. I would also combine with the next paragraph of the commit message. For example:

> Fix an issue were remote queries to data nodes always timed out after
1 minute, which leads to aborted long-running queries. Instead the queries can
still be canceled by the user or the database when `statement_timeout`
is reached.

It is also good to make explicit what the fix does. Currently it is necessary to guess that the PR removes timeout except the cleanup case.

The following sentence is to harsh, imho, and should not be in public history:
>Further,
since the adopted code wasn't used as intended, and was changed
without a good understanding of the consequences, it didn't work the
way it should.

I suggest to remove entire paragraph with this sentence.

I suggest to be explicit from which PG version the added function was copied in
>The included changes introduce a new function, based on the original
postgres_fdw, that does the correct timeout handling for cleanup
queries, then removes the erroneous timeout handling in the main
query/response handling code.

File: tsl/src/remote/async.c (hunk 4 above)
Comment (erimatnor) [reply tsl/src/remote/async.c:619]: This was run through formatting, and I guess it is indented to show that is inside the context of the try-catch braces.

File: tsl/src/remote/async.c (hunk 2 above)
Comment (erimatnor) [reply tsl/src/remote/async.c:580]: Copied from postgresql code, but will add a better name.

File: tsl/src/remote/async.c [hunk 5]
```diff
@@ -512,6 +512,137 @@ async_request_wait_ok_result(AsyncRequest *req)
...
 
+/*
+ * Get the result of an async request during cleanup.
+ *
+ * Cleanup is typically necessary for a query that is being interrupted by
+ * transaction abort, or a query that was initiated as part of transaction
+ * abort to get the remote side back to the appropriate state.
+ *
+ * endtime is the time at which we should give up and assume the remote
+ * side is dead.
```
[the remark this answers is not in the document]
Comment (erimatnor) [reply tsl/src/remote/async.c:523]: It is the absolute time when we should give up.

File: tsl/src/remote/async.c [hunk 6]
```diff
@@ -512,6 +512,137 @@ async_request_wait_ok_result(AsyncRequest *req)
...
+		{
+			PGresult *res;
+
+			while (PQisBusy(pg_conn))
+			{
+				int wc;
+				TimestampTz now = GetCurrentTimestamp();
+				long secs;
+				int microsecs;
+				long cur_timeout;
```
Comment (mkindahl) [inline tsl/src/remote/async.c:569]: It is usually quite useful to indicate the unit of a timeout for variables that contain timeouts. Avoids confusion when the variable is used.
```suggestion
				long cur_timeout_msec;
```

File: tsl/src/remote/async.c [hunk 7]
```diff
@@ -512,6 +512,137 @@ async_request_wait_ok_result(AsyncRequest *req)
...
+
+				/* If timeout has expired, give up, else get sleep time. */
+				if (now >= endtime)
+				{
+					timed_out = true;
+					goto exit;
+				}
+				TimestampDifference(now, endtime, &secs, &microsecs);
```
Comment (mkindahl) [inline tsl/src/remote/async.c:577]: A more useful name for `secs` and `microsecs` is probably that it is the difference between the times, that is, the remaining seconds and microseconds.
```suggestion
				TimestampDifference(now, endtime, &remaining_secs, &remaining_usecs);
```

File: tsl/src/remote/async.c (hunk 3 above)
Comment (mkindahl) [reply tsl/src/remote/async.c:588]: Second that. Even if just constants in this function is is a lot easier to read, especially considering that they are different between PG versions.

File: tsl/src/remote/async.c [hunk 8]
```diff
@@ -512,6 +512,137 @@ async_request_wait_ok_result(AsyncRequest *req)
...
+
+				/* Data available in socket? */
+				if (wc & WL_SOCKET_READABLE)
+				{
+					if (0 == PQconsumeInput(pg_conn))
+					{
+						conn_issue = true;
+						goto exit;
+					}
+				}
```
Comment (mkindahl) [inline tsl/src/remote/async.c:604]: Easier to read if you combine the conditionals.
```suggestion
				if ((wc & WL_SOCKET_READABLE) && !PQconsumeInput(pg_conn))
				{
					conn_issue = true;
					goto exit;
				}
```

File: tsl/src/remote/txn.c [hunk 9]
```diff
@@ -269,23 +270,11 @@ exec_cleanup_command(TSConnection *conn, const char *query)
...
+	if (!success)
 		async_response_report_error(response, WARNING);
-		async_response_close(response);
 
-		/* drain the set until empty of all possibly queued errors */
-		while ((response = async_request_set_wait_any_response_deadline(set, end_time)))
-			async_response_close(response);
-	}
+	async_response_close(response);
+
```
Comment (mkindahl) [inline tsl/src/remote/txn.c:277]: This hunk removes code that reaps the request queue, which is supposed to be handled by the `async_request_cleanup_result`, but if there is a bug this will not have happened. Is it possible to add some sort of check that there are no outstanding requests?

**Review by mkindahl — APPROVED** [review]
Looks good, and I see no issues that should block a push, so approving.

I would, however, suggest a more succinct commit message that just focuses on what the code actually did before, why that did not work, and what the commit changes the code to do. How things should or should not work is subjective and even though I agree with the comments, being more concrete will help maintenance and debugging in the future.

File: tsl/src/remote/async.c (hunk 5 above)
[the remark this answers is not in the document]
Comment (k-rus) [reply tsl/src/remote/async.c:523]: This I understand, sorry, I should be more clear that the absolute time of the end of timeout. Is it about a timeout (timeout for giving up)? If so, may be explicitly to mention in the comment?

File: tsl/src/remote/txn.c (hunk 9 above)
Comment (erimatnor) [reply tsl/src/remote/txn.c:277]: As you mention, `async_request_cleanup_result` now handles the cleanup. Any assertions/checks that all results have been drained should happen in that function.

File: tsl/src/remote/async.c (hunk 3 above)
Comment (erimatnor) [reply tsl/src/remote/async.c]: I actually realized I could merge the code paths since they were based on the same original function. Now the code should be cleaner and the flags only appear in one place.

File: tsl/src/remote/async.c (hunk 4 above)
Comment (k-rus) [reply tsl/src/remote/async.c]: Can it be due to `;` on the same line as the label?

**Review by mkindahl — APPROVED** [review]
Some minor comments.

File: tsl/src/remote/txn.c (hunk 9 above)
Comment (erimatnor) [reply tsl/src/remote/txn.c:277]: The contract provided by libpq is that you should call `PGgetResult` until it returns NULL, which is what the drain function does. From the docs:

`
 A null pointer is returned when the command is complete and there will be no more results. PGgetResult must be called repeatedly until it returns a null pointer, indicating that the command is done.
`

I don't understand what the purpose is to double-check this, since we already reached the desired condition. It is a bit like asserting that a pointer is NULL in the if clause that checked for NULL. Further, it is not clear to me that any internal state of the connection would accurately reflect a "drained" connection, since the way to know it is drained is to call PGgetResult until it returns NULL, which we already do.

File: tsl/src/remote/async.c (hunk 8 above)
Comment (erimatnor) [reply tsl/src/remote/async.c]: This is how PostgreSQL did it. I can optimize it.

File: tsl/src/remote/async.c (hunk 4 above)
Comment (erimatnor) [reply tsl/src/remote/async.c]: The semicolon is necessary because otherwise there's a parser error given that there is no code before the closing brace. This is the way the code was when importing it from postgresql.

Comment (k-rus) [reply tsl/src/remote/async.c]: I understand that it is necessary, sorry I wasn't clear: you can move it to another line, so they are not on the same line?

File: tsl/src/remote/async.c (hunk 5 above)
[the remark this answers is not in the document]
Comment (erimatnor) [reply tsl/src/remote/async.c:521]: I am not sure I understand how to improve the comment. Do you explicitly want the word "timeout" in the comment?

File: tsl/src/remote/async.c (hunk 4 above)
Comment (erimatnor) [reply tsl/src/remote/async.c]: Again, the formatter prevents that. It removes the extra newline so moving the `;` to a new line doesn't make a difference. FWIW, I don't think it is wrong to have the goto tag at the "right" indentation level. Besides, this is what the formatter gives us.
