### PR TITLE
Handle Sort nodes in ConstraintAwareAppend

### LINKED ISSUE #1577: Query fails: invalid child of constraint-aware append: 40
**Relevant system information:**
 - OS: timescale/toimesclaedb:1.5.1-pg11 Docker running on Debian
 - PostgreSQL version (output of `postgres --version`): postgres (PostgreSQL) 11.5
 - TimescaleDB version (output of `\dx` in `psql`): 1.5.1
 - Installation method: using Docker

**Describe the bug**
The query below started returning the error
`ERROR:  invalid child of constraint-aware append: 40
SQL state: XX000`
 after we inserted data for some days. It was running fine when we first implemented and tested the query in our application and only recently started to throw errors. 

Failing Query:
```
SELECT LAST("Timestamp", "Timestamp") as "Timestamp",
                    "MachineId" AS "MachineId",
                    "MeasureValueId" as "MeasureValueId",
                    LAST("Value", "Timestamp") AS "Value"
                FROM public."MeasureValues"
                WHERE "Timestamp" > NOW() - interval '2day' AND ("MachineId" IN (54,29,34,36,37,38,39,40,41,1,2,90,3,12,13,14,15,16,17,18,19,20,21,4,22,23,24,25,26,27,60,61,62,63,5,64,65,66,67,68,69,6,7,8,9,10,11,28,31,32,30,47,48,49,50))
                    AND "MeasureValueId" in (2,20)				
                GROUP BY 2, 3
```
Interestingly, if I use a narrower timeframe or reduce the number of ids in the WHERE clause, the issue is not reproducible.

Successful Query:
```
SELECT LAST("Timestamp", "Timestamp") as "Timestamp",
                    "MachineId" AS "MachineId",
                    "MeasureValueId" as "MeasureValueId",
                    LAST("Value", "Timestamp") AS "Value"
                FROM public."MeasureValues"
                WHERE "Timestamp" > NOW() - interval '1 minute' AND ("MachineId" IN (54,29,34,36,37,38,39,40,41,1,2,90,3,12,13,14,15,16,17,18,19,20,21,4,22,23,24,25,26,27,60,61,62,63,5,64,65,66,67,68,69,6,7,8,9,10,11,28,31,32,30,47,48,49,50))
                    AND "MeasureValueId" in (2,20)				
                GROUP BY 2, 3
```
Another successful query:
```
SELECT LAST("Timestamp", "Timestamp") as "Timestamp",
                    "MachineId" AS "MachineId",
                    "MeasureValueId" as "MeasureValueId",
                    LAST("Value", "Timestamp") AS "Value"
                FROM public."MeasureValues"
                WHERE "Timestamp" > NOW() - interval '2 day' AND ("MachineId" IN (54,29,34,36,37,38,39))
                    AND "MeasureValueId" in (2,20)				
                GROUP BY 2, 3
```

**To Reproduce**
The timespan and amount of ID's in the database seems to matter a lot. I tried to reproduce the issue on a staging system and in the development environment but was not able to reproduce the issue. The only time I have observed this issue is on the production database. See Context below for schema and other information. 

**Expected behavior**
Error sould not be returned

**Actual behavior**
Query fails with `ERROR:  invalid child of constraint-aware append: 40
SQL state: XX000`

**Screenshots**
none available

**Additional context**
Create Table from PGAdmin for table MeasureValues:
```
CREATE TABLE public."MeasureValues"
(
    "Timestamp" timestamp without time zone NOT NULL,
    "MeasureValueId" integer NOT NULL,
    "MachineId" integer NOT NULL,
    "Value" double precision,
    CONSTRAINT "PK_MeasureValues" PRIMARY KEY ("Timestamp", "MachineId", "MeasureValueId")
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE public."MeasureValues"
    OWNER to postgres;

-- Index: MeasureValues_Timestamp_idx

-- DROP INDEX public."MeasureValues_Timestamp_idx";

CREATE INDEX "MeasureValues_Timestamp_idx"
    ON public."MeasureValues" USING btree
    ("Timestamp" DESC)
    TABLESPACE pg_default;

-- Trigger: ts_cagg_invalidation_trigger

-- DROP TRIGGER ts_cagg_invalidation_trigger ON public."MeasureValues";

CREATE TRIGGER ts_cagg_invalidation_trigger
    AFTER INSERT OR DELETE OR UPDATE 
    ON public."MeasureValues"
    FOR EACH ROW
    EXECUTE PROCEDURE _timescaledb_internal.continuous_agg_invalidation_trigger(3\000);

-- Trigger: ts_insert_blocker

-- DROP TRIGGER ts_insert_blocker ON public."MeasureValues";

CREATE TRIGGER ts_insert_blocker
    BEFORE INSERT
    ON public."MeasureValues"
    FOR EACH ROW
    EXECUTE PROCEDURE _timescaledb_internal.insert_blocker();
```

Hypertable was created with 
```
SELECT create_hypertable('"MeasureValues"', 'Timestamp', chunk_time_interval => interval '3 days');
ALTER TABLE "MeasureValues" SET (timescaledb.compress = true , timescaledb.compress_orderby = '"Timestamp"' , timescaledb.compress_segmentby = '"MachineId", "MeasureValueId"')
```

Results of Query `SELECT time_bucket('1 day', "Timestamp"), COUNT(*) FROM "MeasureValues" WHERE "Timestamp" > NOW() - interval '10 days' GROUP BY 1`
```
"2019-12-06 00:00:00"	1013329
"2019-11-30 00:00:00"	1602934
"2019-11-29 00:00:00"	1735952
"2019-11-26 00:00:00"	885878
"2019-12-05 00:00:00"	1729184
"2019-12-04 00:00:00"	1633966
"2019-11-27 00:00:00"	1876988
"2019-11-28 00:00:00"	1886359
"2019-12-03 00:00:00"	2021177
"2019-12-01 00:00:00"	1544254
"2019-12-02 00:00:00"	1820820
```

Results of Query `SELECT COUNT(*) FROM "MeasureValues"`
`261338425`

There is also a continuous aggreation view defined:

```
CREATE VIEW "PerDayMeasureValueStatistics" ("Timestamp", "MachineId", "MeasureValueId", "TotalCount", "LastTimestamp", "LastValue")
WITH (timescaledb.continuous,
    timescaledb.refresh_lag = '1h',
    timescaledb.refresh_interval = '1h')
AS 
SELECT time_bucket('1 day', "Timestamp") as "Timestamp"
	, "MachineId"
	, "MeasureValueId"
	, COUNT("Value") as "TotalCount"
	, LAST("Timestamp", "Timestamp") as "LastTimestamp"
	, LAST("Value", "Timestamp") as "LastValue"
	FROM public."MeasureValues" 
	GROUP BY time_bucket('1 day', "Timestamp"), "MachineId", "MeasureValueId";
```
Also, auto-compression policy is enabled for chunks older than 3 days.

Please don't hesitate to ask if I can provide any more information.

### PR DESCRIPTION
**Pull request by svenklemm**
When a MergeAppendPath has children that do not produce sorted
output a Sort node will be injected during plan creation, those
plans would trigger an error about invalid child nodes in
ConstraintAwareAppend. This PR makes ConstraintAwareAppend handle
those plans correctly.

Fixes #1577

### CODE REVIEW

File: src/constraint_aware_append.c [hunk 1]
```diff
@@ -54,18 +54,18 @@ static Plan *
...
 	{
-		Result *res = (Result *) plan;
+		case T_Result:
+		case T_Sort:
+			return plan->lefttree;
 
-		if (res->plan.lefttree != NULL && res->plan.righttree == NULL)
-			return res->plan.lefttree;
-		if (res->plan.righttree != NULL && res->plan.lefttree == NULL)
-			return res->plan.righttree;
```
Comment (k-rus) [inline src/constraint_aware_append.c]: The removed code suggests me that it would be nice to assert that `right tree` is `NULL`.

Comment (k-rus) [reply src/constraint_aware_append.c]: I realised that the assertion is not needed, since it should not happen by the node constructions.
