### PR TITLE
Modify continuous_aggregate_stats view definition

### LINKED ISSUE #1781: Continuous Aggs last_run_success Shows False
**Relevant system information:**
 - OS: Centos 8
 - PostgreSQL version (output of `postgres --version`): 11.7
 - TimescaleDB version (output of `\dx` in `psql`): 1.6.1
 - Installation method: yum install

**Describe the bug**
In the continuous aggs stats views, the `last_run_success` field consistently shows "false" despite obvious successful runs, and no increase in failed run counts.

**To Reproduce**
1. Create a continuous agg
2. View the stats for that agg in the timescaledb_information catalogues
3. See the `last_run_success` column shows FALSE

**Expected behavior**
I would expect this to show TRUE unless the last run actually failed

**Actual behavior**
This shows FALSE even when the last run was successful.
**Screenshots**
Screen Shot 2020-03-27 at 10 40 01 AM

**Additional context**
This appears to just be cosmetic, but the information is confusing, since all signs point to the cagg working as expected, except this columns.

### PR DESCRIPTION
**Pull request by gayyappan**
last_run_success value is reset when a job is started.
So mask the value if the status of a job is
running, otherwise it will show an incorrect state.

Fixes #1781 
For reviewers, here is the output from a running job and a scheduled job.  (the change in this PR is for the running job case).
test=# SELECT now(), * from timescaledb_information.continuous_aggregate_stats ;
              now              | view_name | completed_threshold | invalidation_threshold | job_id |     
 last_run_started_at      |    last_successful_finish     | **last_run_status | job_status** | last_run_durat
ion |      next_scheduled_run       | total_runs | total_successes | total_failures | total_crashes 
-------------------------------+-----------+---------------------+------------------------+--------+-----
--------------------------+-------------------------------+-----------------+------------+---------------
----+-------------------------------+------------+-----------------+----------------+---------------
 2020-03-30 15:45:19.330586-04 | mat_m1    |                     |                        |   1000 | 2020
-03-30 15:40:19.465616-04 | 2020-03-30 15:40:19.495706-04 | **Success         | scheduled  |** 00:00:00.03009
    | 2020-03-30 15:45:19.495706-04 |          1 |               1 |              0 |             0
(1 row)

test=# SELECT now(), * from timescaledb_information.continuous_aggregate_stats ;
              now              | view_name | completed_threshold | invalidation_threshold | job_id |     
 last_run_started_at      |    last_successful_finish     | **last_run_status | job_status** | last_run_durat
ion | next_scheduled_run | total_runs | total_successes | total_failures | total_crashes 
-------------------------------+-----------+---------------------+------------------------+--------+-----
--------------------------+-------------------------------+-----------------+------------+---------------
----+--------------------+------------+-----------------+----------------+---------------
 2020-03-30 15:45:21.833573-04 | mat_m1    | 21                  | 21                     |   1000 | 2020
-03-30 15:45:21.124055-04 | 2020-03-30 15:45:21.112443-04 |                 **| running**    |               
    | -infinity          |          3 |               2 |              0 |             1
(1 row)

### CODE REVIEW

File: sql/views.sql [hunk 1]
```diff
@@ -154,14 +154,17 @@ CREATE OR REPLACE VIEW timescaledb_information.continuous_aggregate_stats as
...
-    CASE when bgw_job_stat.last_run_success = 't' then 'Success'
-         when bgw_job_stat.last_run_success = 'f' then 'Failed'
-    END AS last_run_status,
-    case when bgw_job_stat.last_finish < '4714-11-24 00:00:00+00 BC' then 'running'
-       when bgw_job_stat.next_start is not null then 'scheduled'
-    end as job_status,
-    case when bgw_job_stat.last_finish > bgw_job_stat.last_start then (bgw_job_stat.last_finish - bgw_job_stat.last_start)
-    end as last_run_duration,
+    CASE WHEN bgw_job_stat.last_finish < '4714-11-24 00:00:00+00 BC' THEN NULL 
+         WHEN bgw_job_stat.last_finish is not null THEN
```
Comment (mkindahl) [inline sql/views.sql]:
```suggestion
         WHEN bgw_job_stat.last_finish IS NOT NULL THEN
```

File: sql/views.sql [hunk 2]
```diff
@@ -154,14 +154,17 @@ CREATE OR REPLACE VIEW timescaledb_information.continuous_aggregate_stats as
...
     bgw_job_stat.last_successful_finish as last_successful_finish,
-    CASE when bgw_job_stat.last_run_success = 't' then 'Success'
-         when bgw_job_stat.last_run_success = 'f' then 'Failed'
-    END AS last_run_status,
-    case when bgw_job_stat.last_finish < '4714-11-24 00:00:00+00 BC' then 'running'
-       when bgw_job_stat.next_start is not null then 'scheduled'
-    end as job_status,
-    case when bgw_job_stat.last_finish > bgw_job_stat.last_start then (bgw_job_stat.last_finish - bgw_job_stat.last_start)
-    end as last_run_duration,
+    CASE WHEN bgw_job_stat.last_finish < '4714-11-24 00:00:00+00 BC' THEN NULL
```
Comment (mkindahl) [inline sql/views.sql]: Not very fond of magic values like this, it make things hard to maintain, but nothing to do in this PR.

File: sql/views.sql [hunk 3]
```diff
@@ -154,14 +154,17 @@ CREATE OR REPLACE VIEW timescaledb_information.continuous_aggregate_stats as
...
-    case when bgw_job_stat.last_finish > bgw_job_stat.last_start then (bgw_job_stat.last_finish - bgw_job_stat.last_start)
-    end as last_run_duration,
+    CASE WHEN bgw_job_stat.last_finish < '4714-11-24 00:00:00+00 BC' THEN NULL 
+         WHEN bgw_job_stat.last_finish is not null THEN
+              CASE WHEN bgw_job_stat.last_run_success = 't' THEN 'Success'
+                   WHEN bgw_job_stat.last_run_success = 'f' THEN 'Failed'
+               END
+    END as last_run_status,
+    CASE WHEN bgw_job_stat.last_finish < '4714-11-24 00:00:00+00 BC' THEN 'running'
+       WHEN bgw_job_stat.next_start is not null THEN 'scheduled'
```
Comment (mkindahl) [inline sql/views.sql]:
```suggestion
       WHEN bgw_job_stat.next_start IS NOT NULL THEN 'scheduled'
```

Comment (mkindahl) [inline sql/views.sql]: You are mixing the case of result columns. I would suggest to be consistent. Not sure if it is good time to change the text now since it might break APIs, but consider if you want to use Capitalized, lowercase, or UPPERCASE for all texts. We should also be consistent with other views.

(I think it is customary to use UPPERCASE for these kinds of enumeration-like constants, but I have no strong opinion on what we should use, except that we should try to do what users expect based on what other systems use and not invent our own convention.)

Comment (gayyappan) [reply sql/views.sql]: modified.

Comment (gayyappan) [reply sql/views.sql]: fixed.

File: sql/views.sql (hunk 1 above)
Comment (gayyappan) [reply sql/views.sql]: changed.

**Comment by gayyappan** [comment]
> Do we not have a test case that would show the difference? Should we?
The change applies to a Running bgw job. So not easy to have a reproducible test case.
