### PR TITLE
Use segmentwise recompression in compress policy

### LINKED ISSUE #6255: [Bug]: Compressed chunks getting inflated after upgrading to 2.12.2
### What type of bug is this?

Unexpected error

### What subsystems and features are affected?

Background worker, Compression

### What happened?

Hi! I'm following up after reporting this on the Timescale Slack server. This issue prevents normal function of the automatic compression policies, safe ingestion of old data into the architecture, and due the exponential increase in disk size, problems in keeping the database and streaming replicas working.

After upgrading from 2.10.0 to 2.12.2, it seems like the compression policy worker is "inflating" old compressed chunks without doing anything, and seemingly failing on a deadlock while doing so. The behavior we see is the worker grabbing a partially compressed chunk, "inflating" the related uncompressed chunk table to its previously uncompressed size, and then failing to recompress anything, with a deadlock error showing in the log.

In the Postgres log it seems I'm also missing some exception details from these two exception handlers here:
https://github.com/timescale/timescaledb/blob/98623ea1d97be06106a6ce593296253c1c5f38c1/sql/policy_internal.sql#L115 
https://github.com/timescale/timescaledb/blob/98623ea1d97be06106a6ce593296253c1c5f38c1/sql/policy_internal.sql#L126 

Looks like _message and _detail aren't set unlike the block above here:
https://github.com/timescale/timescaledb/blob/98623ea1d97be06106a6ce593296253c1c5f38c1/sql/policy_internal.sql#L101

Thus the log mentioning the deadlock message in one case, but empty "()" details and messages in the others.

These are the statistics of one of the partially compressed chunks for example:

20231027_chunk_1557_deadtup_after_analyze

An uncompressed chunk is roughly 14GB, 4 days of data, ~30 million rows per day, ~120 million rows total over the span of the chunk, which ends up compressed to 900MB. It's a very narrow schema, the table definition is the following, with the compression segmented by the `id` column:

```sql
 CREATE TABLE public.sample (
	id int8 NOT NULL,
	tstamp timestamptz NOT NULL,
	value_int64 int8 NULL,
	value_double float8 NULL,
	value_float float4 NULL,
	value_bool bool NULL,
	quality bool NOT NULL,
	CONSTRAINT sample_pkey PRIMARY KEY (id, tstamp),
	CONSTRAINT sample_id_fkey FOREIGN KEY (id) REFERENCES public.signal_base(id)
);
```

The amount of ids present in a single chunk is in the order of 300k, which gives us around 400 rows per signal id on average. We have these chunks with very, very few sporadic inserts of old data. A couple hundred rows inserted, compared to the existing ~120 million rows in the span of the entire chunk. From what I see around 10 chunks are partially compressed, from the couple hundred we have in total.

The bussiness use case makes it so insertion of old data is almost inexistent (we continually ingest oil field installation sensor data, continually being polled from the field). Deletes/updates over old data is an usecase we outright dont perform nor support within the system. There is the odd case where some particular instrument is a little bit more complicated and has a log, that could possibly have some older values, but that's it. It's **impossible** we've reinserted 4 days of values again over the same compressed chunk without noticing, like the statistics say (240 million inserts), I doubt the system could even handle it, so it makes no sense for the background job to try to inflate the chunk to its full size. At most it should inflate the impacted segments, which for a couple hundred uncompressed samples inserted post-compression it would mean probably less than a hundred id segments were affected.

After the compression policy job is done with a partially compressed chunk (verified the status flag is 9 in the chunks catalog, which I understand it means compressed | partially_compressed ), we're end up with a compressed chunk with the 120 million rows, of 900MB and an uncompressed 14GB chunk with a **couple hundred** rows alive. So practically all of it is "dead" tuples for postgres.

If we perform a VACUUM (FULL) of the chunk, its size returns to normal, but we're still left with most of the data in the compressed chunk, plus barely a couple hundred uncompressed rows in this other adjacent chunk. This means that if we enable the compression policy again, and the background worker picks up this chunk, it tries to do **exactly the same**, that is, inflating it to 14GB and blowing up our disk usage and itself in the process. So for now we've **disabled all automatic compression policies**.

`recompress_chunk` doesn't finishes. It locks the table, with Postgres registering an ever increasing amount of sessions, and after almost 2h I have to stop the function due this. This table is mostly constantly queried

We have at least another database, albeit smaller, with the exact same problem: The background job inflates a couple of partially compressed chunks to it's whole size, blowing up the disk usage of the master and streaming replica, causing issues on both systems.

### TimescaleDB version affected

2.12.2

### PostgreSQL version used

14.2

### What operating system did you use?

Debian 10 x64 

### What installation method did you use?

Deb/Apt

### What platform did you run on?

On prem/Self-hosted

### Relevant log output and stack trace

```bash
2023-10-26 06:04:07 -03 [30519]WARNING:  decompressing chunk "_timescaledb_internal._hyper_91_1553_chunk" failed when compression policy is executed
2023-10-26 06:04:07 -03 [30519]DETAIL:  Message: (), Detail: ().
2023-10-26 06:04:07 -03 [30519]CONTEXT:  PL/pgSQL function _timescaledb_functions.policy_compression_execute(integer,integer,anyelement,integer,boolean,boolean) line 70 at RAISE
	SQL statement "CALL _timescaledb_functions.policy_compression_execute(
	        job_id, htid, lag_value::INTERVAL,
	        maxchunks, verbose_log, recompress_enabled
	      )"
	PL/pgSQL function _timescaledb_functions.policy_compression(integer,jsonb) line 51 at CALL
2023-10-26 06:04:07 -03 [30519]WARNING:  compressing chunk "_timescaledb_internal._hyper_91_1553_chunk" failed when compression policy is executed
2023-10-26 06:04:07 -03 [30519]DETAIL:  Message: (), Detail: ().
2023-10-26 06:04:07 -03 [30519]CONTEXT:  PL/pgSQL function _timescaledb_functions.policy_compression_execute(integer,integer,anyelement,integer,boolean,boolean) line 81 at RAISE
	SQL statement "CALL _timescaledb_functions.policy_compression_execute(
	        job_id, htid, lag_value::INTERVAL,
	        maxchunks, verbose_log, recompress_enabled
	      )"
	PL/pgSQL function _timescaledb_functions.policy_compression(integer,jsonb) line 51 at CALL

 2023-10-26 06:10:42 -03 [30519]WARNING:  compressing chunk "_timescaledb_internal._hyper_91_1850_chunk" failed when compression policy is executed
2023-10-26 06:10:42 -03 [30519]DETAIL:  Message: (deadlock detected), Detail: (Process 30519 waits for AccessExclusiveLock on relation 26960 of database 16402; blocked by process 32373.
	Process 32373 waits for AccessShareLock on relation 96361368 of database 16402; blocked by process 30519.).
2023-10-26 06:10:42 -03 [30519]CONTEXT:  PL/pgSQL function _timescaledb_functions.policy_compression_execute(integer,integer,anyelement,integer,boolean,boolean) line 56 at RAISE
	SQL statement "CALL _timescaledb_functions.policy_compression_execute(
	        job_id, htid, lag_value::INTERVAL,
	        maxchunks, verbose_log, recompress_enabled
	      )"
	PL/pgSQL function _timescaledb_functions.policy_compression(integer,jsonb) line 51 at CALL


2023-10-26 06:10:42 -03 [30519]LOG:  job 1052 (Compression Policy [1052]) exiting with success: execution time 2220932.13 ms
```

### How can we reproduce the bug?

```bash
I don't have a simple reproduction of this bug to share.
```

### PR DESCRIPTION
**Pull request by antekresic**
Change compression policy to use segmentwise
recompression when possible to increase performance. Segmentwise recompression decompresses rows into memory, thus reducing IO load when recompressing, making it much faster for bigger chunks.

Fixes #6255

### CODE REVIEW

File: sql/policy_internal.sql [hunk 1]
```diff
@@ -123,26 +124,20 @@ BEGIN
         )
       ) AND recompress_enabled IS TRUE THEN
       BEGIN
-        PERFORM @extschema@.decompress_chunk(chunk_rec.oid, if_compressed => true);
+        -- first check if there's an index. Might have to use a heuristic to determine if index usage would be efficient,
+        -- or if we'd better fall back to decompressing & recompressing entire chunk
+        SELECT _timescaledb_functions.get_compressed_chunk_index_for_recompression(chunk_rec.oid) INTO STRICT compressed_chunk_index;
+        IF compressed_chunk_index IS NOT NULL THEN
```
Comment (svenklemm) [inline sql/policy_internal.sql:130]:
```suggestion
        IF _timescaledb_functions.get_compressed_chunk_index_for_recompression(chunk_rec.oid) IS NOT NULL THEN
```

**Review by svenklemm — APPROVED** [review]

**Review by konskov — APPROVED** [review]
