### PR TITLE
Forbid Batch Sort Merge on nullable orderby columns

### LINKED ISSUE #9445: wrong order in batch sorted merge on unordered chunk with nullable orderby columns
```
CREATE TABLE t(time int NOT NULL, device int, val int);
SELECT create_hypertable('t', 'time', chunk_time_interval => 10000);
ALTER TABLE t SET (timescaledb.compress,
    timescaledb.compress_segmentby='device',
    timescaledb.compress_orderby='val DESC');

-- One batch: 200 NULLs + values 1..300. _ts_meta_max = 300.
-- In DESC order the first decompressed tuple is NULL, not 300.
INSERT INTO t SELECT 1, 1, NULL FROM generate_series(1, 200);
INSERT INTO t SELECT 1, 1, g FROM generate_series(1, 300) g;
SELECT compress_chunk(show_chunks('t'));

-- Two more batches via direct compress (chunk becomes unordered).
SET timescaledb.enable_direct_compress_insert = true;
INSERT INTO t SELECT 1, 1, g FROM generate_series(500, 800) g;
INSERT INTO t SELECT 1, 1, g FROM generate_series(900, 1000) g;

SET timescaledb.debug_require_batch_sorted_merge = 'force';

-- In DESC order NULLs come first; a NULL after a non-NULL is wrong.
SELECT count(*) AS wrong_rows FROM (
    SELECT val, lag(val) OVER (ORDER BY val DESC) AS prev FROM t
) t WHERE val IS NULL AND prev IS NOT NULL;

-- Fixed after full recompression.
SELECT compress_chunk(decompress_chunk(x)) FROM show_chunks('t') x;

SELECT count(*) AS wrong_rows FROM (
    SELECT val, lag(val) OVER (ORDER BY val DESC) AS prev FROM t
) t WHERE val IS NULL AND prev IS NOT NULL;
```

### PR DESCRIPTION
**Pull request by natalya-aksman**
Fixes timescale/timescaledb#9445

Forbid BSM on nullable orderby columns.

Check whether orderby columns are declared NOT NULL, if they are not declared NOT NULL check whether they  appear as non-nullable vars in the query predicates.

As an additional optimization in a separate PR, we can skip NULL direction check on non-nullable columns but it is out of scope for this bug fix. Opened Enhancement request timescale/eng-database#809.

`compression_sorted_merge*` tests were adjusted to reflect new BSM logic in regards to NULLs in orderby columns.

### CODE REVIEW

**Review by svenklemm — APPROVED** [review]

File: tsl/src/nodes/columnar_scan/columnar_scan.c [hunk 1]
```diff
@@ -2673,14 +2674,58 @@ find_const_segmentby(RelOptInfo *chunk_rel, const CompressionInfo *info)
...
+			if (IsA(ri->clause, NullTest) &&
+				((NullTest *) ri->clause)->nulltesttype == IS_NOT_NULL &&
+				bms_num_members(clause_attnos) == 1) /* this column only */
+			{
+				NullTest *nt = castNode(NullTest, ri->clause);
+				if (!contain_nonstrict_functions((Node *) nt->arg))
+					return true;
+			}
+
+			if (!contain_nonstrict_functions((Node *) ri->clause))
```
Comment (akuzm) [inline tsl/src/nodes/columnar_scan/columnar_scan.c]: I think it's a sligthtly different concept from what we need here, a strict function can still return a null on a non-null argument. Perhaps `find_nonnullable_vars` can be a better match.

File: tsl/src/nodes/columnar_scan/columnar_scan.c [hunk 2]
```diff
@@ -2709,45 +2754,60 @@ match_pathkeys_to_compression_orderby(List *pathkeys, List *chunk_em_exprs,
 			return false;
 		}
 
+		/* Bail out on BSM if orderby column is nullable */
+		if (for_bsm && !is_var_notnull(compression_info, var))
+		{
+			return false;
+		}
+
```
Comment (akuzm) [inline tsl/src/nodes/columnar_scan/columnar_scan.c]: Let's explain why. The idea is that at the moment the minmax metadata we have doesn't include NULLs, so it's difficult to use it for null-sensitive ordering.

Comment (akuzm) [reply tsl/src/nodes/columnar_scan/columnar_scan.c]: Since we're already exploring adding a new type of metadata, this restriction could be lifted for chunks that have this new type.

File: tsl/src/nodes/columnar_scan/columnar_scan.c [hunk 3]
```diff
@@ -2709,45 +2754,60 @@ match_pathkeys_to_compression_orderby(List *pathkeys, List *chunk_em_exprs,
...
-			}
-			else if (orderby_desc && orderby_nullsfirst != pk->pk_nulls_first)
-			{
-				this_pathkey_reverse = true;
-			}
-			else
-			{
-				return false;
-			}
+			this_pathkey_reverse = (pk->pk_cmptype == COMPARE_LT ? orderby_desc : !orderby_desc);
```
Comment (akuzm) [inline tsl/src/nodes/columnar_scan/columnar_scan.c]: This is already a different optimization based on non-nullability? I think we should avoid it for the bug fix, not to introduce any plan changes in a patch release.

File: tsl/src/nodes/columnar_scan/columnar_scan.c (hunk 1 above)
Comment (akuzm) [reply tsl/src/nodes/columnar_scan/columnar_scan.c]: Maybe it makes sense to keep the things very simple and just ignore the WHERE clauses for now, since we're making a bug fix that will be backported.

Comment (natalya-aksman) [reply tsl/src/nodes/columnar_scan/columnar_scan.c]: Good point about `find_nonnullable_vars`, will change to that. I still think we can check WHERE clause because it will make BSM more applicable even with the fix.

File: tsl/src/nodes/columnar_scan/columnar_scan.c (hunk 2 above)
Comment (natalya-aksman) [reply tsl/src/nodes/columnar_scan/columnar_scan.c]: Will add a comment about both the above points.

File: tsl/src/nodes/columnar_scan/columnar_scan.c (hunk 3 above)
Comment (natalya-aksman) [reply tsl/src/nodes/columnar_scan/columnar_scan.c]: Agree, but it's a good optimization to make in general. But better do it in a separate PR.

**Review by akuzm — APPROVED** [review]
