### PR TITLE
Ignore invalid relid when deleting hypertable

### LINKED ISSUE #4140: [Bug]: Unable to drop extension after compressing a table in extension schema.
### What type of bug is this?

Unexpected error

### What subsystems and features are affected?

Compression

### What happened?

When creating and then compressing a table during extension installation, it is no longer possible to drop the extension.

### TimescaleDB version affected

2.5.2

### PostgreSQL version used

14

### What operating system did you use?

Ubuntu, MacOS

### What installation method did you use?

Docker, Source, Other

### What platform did you run on?

Other

### Relevant log output and stack trace

```bash
test=# CREATE EXTENSION nouninstall;
CREATE EXTENSION
test=# DROP EXTENSION nouninstall;
ERROR:  cache lookup failed for relation 0
```

### How can we reproduce the bug?

Place the following .control and .sql file in pg's extension directory, then in a psql shell execute `CREATE EXTENSION nouninstall; DROP EXTENSION nouninstall;`

```
// nouninstall.control
comment = 'Timescale nouninstaller'
default_version = '0.1'
module_pathname = '$libdir/nouninstall'
relocatable = false
schema = nouninstall
superuser = true
```

```
// nouninstall--0.1.sql
CREATE SCHEMA IF NOT EXISTS _ps_trace;
CREATE SCHEMA IF NOT EXISTS ps_trace;

CREATE DOMAIN ps_trace.trace_id uuid NOT NULL CHECK (value != '00000000-0000-0000-0000-000000000000');

CREATE TABLE IF NOT EXISTS _ps_trace.span
(
    trace_id ps_trace.trace_id NOT NULL,
    span_id bigint NOT NULL,
    parent_span_id bigint NULL,
    start_time timestamptz NOT NULL,
    end_time timestamptz NOT NULL,
    PRIMARY KEY (span_id, trace_id, start_time),
    CHECK (start_time <= end_time)
);
CREATE INDEX ON _ps_trace.span USING BTREE (trace_id, parent_span_id) INCLUDE (span_id); -- used for recursive CTEs for trace tree queries

SELECT public.create_hypertable(
        '_ps_trace.span'::regclass,
        'start_time'::name,
        partitioning_column=>'trace_id'::name,
        number_partitions=>1::int,
        chunk_time_interval=>'07:57:57.345608'::interval,
        create_default_indexes=>false
    );

ALTER TABLE _ps_trace.span SET (timescaledb.compress, timescaledb.compress_segmentby='trace_id,span_id');
```

### PR DESCRIPTION
**Pull request by mkindahl**
When running `performDeletion` is necessary to have a valid relation
id, but when doing a lookup using `ts_hypertable_get_by_id` this might
actually return a hypertable entry pointing to a table that does not
exist because it has been deleted previously. In this case, only the
catalog entry should be removed, but it is not necessary to delete the
actual table.

This scenario can occur if both the hypertable and a compressed table
are deleted as part of running a `sql_drop` event, for example, if a
compressed hypertable is defined inside an extension. In this case, the
compressed hypertable (indeed all tables) will be deleted first, and
the lookup of the compressed hypertable will find it in the metadata
but a lookup of the actual table will fail since the table does not
exist.

Fixes #4140

### CODE REVIEW

**Comment by mfundul** [comment]
What about the call site in `hypertable_tuple_delete()` in `src/hypertable.c`?

```
	if (!compressed_hypertable_id_isnull)
	{
		Hypertable *compressed_hypertable = ts_hypertable_get_by_id(compressed_hypertable_id);
		/* The hypertable may have already been deleted by a cascade */
		if (compressed_hypertable != NULL)
			ts_hypertable_drop(compressed_hypertable, DROP_RESTRICT);
	}
```

**Comment by mkindahl** [comment]
> What about the call site in `hypertable_tuple_delete()` in `src/hypertable.c`?
> 
> ```
> 	if (!compressed_hypertable_id_isnull)
> 	{
> 		Hypertable *compressed_hypertable = ts_hypertable_get_by_id(compressed_hypertable_id);
> 		/* The hypertable may have already been deleted by a cascade */
> 		if (compressed_hypertable != NULL)
> 			ts_hypertable_drop(compressed_hypertable, DROP_RESTRICT);
> 	}
> ```
> 
> Wouldn't this case leak the catalog entry?

Why would that leak the catalog entry? Could you outline the scenario?

**Comment by mfundul** [comment]
> Why would that leak the catalog entry? Could you outline the scenario?

I misunderstood the code I guess, scratch that.

File: tsl/test/sql/compression_ddl.sql [hunk 1]
```diff
@@ -490,3 +490,19 @@ WHERE reltablespace in
...
+-- generate an error. This scenario can be triggered if an extension
+-- is created with compressed hypertables since the tables are dropped
+-- as part of the drop of the extension.
+CREATE TABLE issue4140("time" timestamptz NOT NULL, device_id int);
+SELECT create_hypertable('issue4140', 'time');
+ALTER TABLE issue4140 SET(timescaledb.compress);
+SELECT format('%I.%I', schema_name, table_name)::regclass AS ctable
+FROM _timescaledb_catalog.hypertable
+WHERE id = (SELECT compressed_hypertable_id FROM _timescaledb_catalog.hypertable WHERE table_name = 'issue4140') \gset
+SELECT timescaledb_pre_restore();
```
Comment (mfundul) [inline tsl/test/sql/compression_ddl.sql:505]: Why do you need `timescaledb_pre_restore()`?

**Review by mfundul — APPROVED** [review]

**Review by gayyappan — COMMENTED** [review]
I think this should instead trap the DROP TABLE statement in process_utility.c.  If it is a compressed chunk/table, fix up the catalog at that point instead of allowing partial deletes to go through i.e. the catalog is never in an invalid state.
This way DROP TABLE < > does not leave our catalog in a bad state.

File: tsl/test/sql/compression_ddl.sql (hunk 1 above)
Comment (gayyappan) [reply tsl/test/sql/compression_ddl.sql:505]: Could you please clarify? Do you mean this scenario cannot happen in other situations, only during an extension update? Is it possible, for instance,  to drop_chunks on a compressed hypertable and get into a bad catalog state?

**Comment by mkindahl** [comment]
> I think this should instead trap the DROP TABLE statement in process_utility.c. If it is a compressed chunk/table, fix up the catalog at that point instead of allowing partial deletes to go through i.e. the catalog is never in an invalid state. This way DROP TABLE < > does not leave our catalog in a bad state.

The drop table statement is already caught and generates an error. This situation can only occur if a delete is done as part of an internal cascade when deleting an extension.

File: src/hypertable.c [hunk 2]
```diff
@@ -694,13 +694,18 @@ ts_hypertable_delete_by_id(int32 hypertable_id)
 void
 ts_hypertable_drop(Hypertable *hypertable, DropBehavior behavior)
 {
-	ObjectAddress hypertable_addr = (ObjectAddress){
-		.classId = RelationRelationId,
-		.objectId = hypertable->main_table_relid,
-	};
+	/* The actual table might have been deleted already, but we still need to
+	 * clean up the catalog entry. */
+	if (hypertable->main_table_relid != InvalidOid)
```
Comment (fabriziomello) [inline src/hypertable.c:699]:
```suggestion
	if (OidIsValid(hypertable->main_table_relid))
```

File: tsl/test/sql/compression_ddl.sql (hunk 1 above)
Comment (mkindahl) [reply tsl/test/sql/compression_ddl.sql:505]: I know it cannot happen through a normal hypertable drop with a compressed hypertable, because I tested that.

It is not relevant for dropping a chunk because the error is triggered because the *compressed hypertable* is dropped before the code reaches the actual lookup of the compressed hypertable.

Comment (mkindahl) [reply tsl/test/sql/compression_ddl.sql:505]: This particular situation happens because `sql_drop` event is used to delete the tables when the extension is dropped.

In this case, the `sql_drop` event is called after the table is actually deleted, so the tables are deleted first and then `ts_timescaledb_process_ddl_event` is called. Once the code to process this delete event is handled, the tables are already gone, so the lookup of the relid fails, triggering the error.

It is entirely possible that running drop chunks on other tables might trigger an error, in particular if internal tables are deleted willy-nilly, but that is out of scope for this issue.

**Review by fabriziomello — APPROVED** [review]
