### PR TITLE
Fix upserts on altered tables.

### LINKED ISSUE #538: Upsert fails with segfault
This issue was originally reported by `mintekhab` on Timescale's Slack. 

```
2018-05-09 07:34:53 UTC::@:[3255]: LOG:  server process (PID 18575) was terminated by signal 11: Segmentation fault
2018-05-09 07:34:53 UTC::@:[3255]: DETAIL:  Failed process was running: INSERT INTO bookingtrends_v4 (bookingtime, hashstring, pointofsale, device, eventtype, lineofbusiness, p
ackageind, offline_online_ind, count, tpid, eapid)
    VALUES (1522443247, 'd9a14db3c923edfe912a84ef70076ae00c1c51300212b1234a7fb6d5d319a705', 'EXPEDIA.COM', 'Traditional Browser', 1, '{"AIR","DESTSVC","DESTSVC","DESTSVC","
HOTEL","HOTEL"}', 'TRUE', 'Online', 1, 1, 0) 
    ON CONFLICT(bookingtime, hashstring)
    DO UPDATE SET count=excluded."count" ;
2018-05-09 07:34:53 UTC::@:[3255]: LOG:  terminating any other active server processes
2018-05-09 07:34:53 UTC::@:[3255]: LOG:  all server processes terminated; reinitializing
2018-05-09 07:34:53 UTC::@:[18583]: LOG:  database system was interrupted; last known up at 2018-05-09 07:30:29 UTC
2018-05-09 07:34:53 UTC::@:[18583]: LOG:  database system was not properly shut down; automatic recovery in progress
2018-05-09 07:34:53 UTC::@:[18583]: LOG:  redo starts at BE/BFCF6310
2018-05-09 07:34:53 UTC::@:[18583]: LOG:  invalid record length at BE/BFCF63F0: wanted 24, got 0
2018-05-09 07:34:53 UTC::@:[18583]: LOG:  redo done at BE/BFCF63B8
2018-05-09 07:34:53 UTC::@:[18583]: LOG:  MultiXact member wraparound protections are now enabled
2018-05-09 07:34:53 UTC::@:[3255]: LOG:  database system is ready to accept connections
2018-05-09 07:34:53 UTC::@:[18587]: LOG:  autovacuum launcher started
```

Backtrace:

```
0x00000000007df800 in pg_detoast_datum_packed ()
#0  0x00000000007df800 in pg_detoast_datum_packed ()
#1  0x00000000007b5da0 in text_to_cstring ()
#2  0x00000000007deb85 in FunctionCall1Coll ()
#3  0x00000000007e006d in OutputFunctionCall ()
#4  0x00000000007e0c34 in OidOutputFunctionCall ()
#5  0x00000000005cc9c3 in ?? ()
#6  0x00000000005ccb1d in ExecConstraints ()
#7  0x00000000005e78f1 in ?? ()
#8  0x00000000005e8305 in ExecModifyTable ()
#9  0x00000000005ce2e8 in ExecProcNode ()
#10 0x00000000005ce368 in ExecProcNode ()
#11 0x00000000005cbe2a in standard_ExecutorRun ()
#12 0x00007f3c4d6db4fb in ?? () from /usr/pgsql-9.6/lib/pg_stat_statements.so
#13 0x00007f3c4d4c4e37 in timescaledb_ExecutorRun () from /usr/pgsql-9.6/lib/timescaledb.so
#14 0x00000000006e384f in ?? ()
#15 0x00000000006e3a9a in ?? ()
#16 0x00000000006e4164 in PortalRun ()
#17 0x00000000006e0e01 in ?? ()
#18 0x00000000006e24cc in PostgresMain ()
#19 0x0000000000682345 in PostmasterMain ()
#20 0x0000000000609f78 in main ()
```

### PR DESCRIPTION
**Pull request by cevian**
Previously, upserts (ON CONFLICT) clauses did not work well on tables
where the hypertable attribute numbers did not match chunk attribute
numbers. This is common if the hypertable has dropped columns or
there were other alter commands run on the hypertable before
chunks were created.

This PR fixes the projection of the returning clause as well
as the update clauses. It also fixes the where clause for ON CONFLICT
UPDATE. These fixes are mostly about mapping the attribute numbers
from the hypertable attnos->chunk attnos. Some slot tupleDesc also
needed to be changed to the tupleDesc of the chunk.

Note that because of the limitations in PG 9.6 we had to copy over
some expressions from the ModifyTable plan node inside the chunk
dispatch. These original expressions are irrecoverable from the
ModifyTableState node or the ProjectionInfo structs in 9.6.

Fixes #538

### CODE REVIEW

**Comment by RobAtticus** [comment]
CI is not happy

File: src/chunk_dispatch_state.c [hunk 1]
```diff
@@ -83,6 +83,14 @@ chunk_dispatch_exec(CustomScanState *node)
 		if (cis->arbiter_indexes != NIL)
 			state->parent->mt_arbiterindexes = cis->arbiter_indexes;
 
+		/* slot for the "existing" tuple in ON CONFLICT UPDATE IS chunk schema */
+		if (cis->tup_conv_map != NULL && state->parent->mt_existing != NULL)
+		{
+			TupleDesc	chunk_desc = cis->tup_conv_map->outdesc;
+
+			ExecSetSlotDescriptor(state->parent->mt_existing, chunk_desc);
```
[the remark this answers is not in the document]
Comment (cevian) [reply src/chunk_dispatch_state.c]: So turns out `mt_conflproj` is the same as `orig->pi_state.resultslot` that is edited in `get_adjusted_projection_info_onconflicupdate`

File: src/chunk_insert_state.c [hunk 2]
```diff
@@ -204,6 +205,168 @@ create_chunk_result_relation_info(ChunkDispatch *dispatch, Relation rel, Index r
...
+	Assert(where_quals != NIL);
+	/* map hypertable attnos -> chunk attnos for the hypertable */
+	where_quals = (List *) map_variable_attnos_compat((Node *) where_quals, varno, 0, map, map_size,
+													  rowtype, &found_whole_row);
+	/* map hypertable attnos -> chunk attnos for the "excluded" table */
+	where_quals = (List *) map_variable_attnos_compat((Node *) where_quals, INNER_VAR, 0, map, map_size,
+													  rowtype, &found_whole_row);
+#if PG96
+	return ExecInitExpr((Expr *) where_quals, NULL);
+#else
```
Comment (erimatnor) [inline src/chunk_insert_state.c]: Do we want an `#elif PG10` here? Otherwise we're saying the else-clause is for all other versions. We should probably be explicit about support...

File: src/chunk_insert_state.c [hunk 3]
```diff
@@ -204,6 +205,168 @@ create_chunk_result_relation_info(ChunkDispatch *dispatch, Relation rel, Index r
...
+	i = 0;
+	foreach(lc, update_tles)
+	{
+		TargetEntry *t = lfirst(lc);
+		Form_pg_attribute attribute;
+
+		Assert(i < chunk_desc->natts);
+		attribute = chunk_desc->attrs[i];
+
+		if (strcmp(NameStr(attribute->attname), t->resname) != 0)
```
Comment (erimatnor) [inline src/chunk_insert_state.c]: Use `namestrcmp` here

File: src/chunk_insert_state.c [hunk 4]
```diff
@@ -204,6 +205,168 @@ create_chunk_result_relation_info(ChunkDispatch *dispatch, Relation rel, Index r
...
+			elog(ERROR, "TLE order in onConflictUpdate does not match chunk attribute order");
```
Comment (erimatnor) [inline src/chunk_insert_state.c]: Could probably improve this error message. Not clear what `onConflictUpdate` is? Seems to refer to a field in a struct or something. Should probably not go in error message.

File: src/chunk_insert_state.c [hunk 5]
```diff
@@ -204,6 +205,168 @@ create_chunk_result_relation_info(ChunkDispatch *dispatch, Relation rel, Index r
...
+	 */
+	variable_attnos_map = convert_tuples_by_name_map(chunk_desc,
+													 hypertable_desc,
+													 gettext_noop("could not convert row type"));
+	variable_attnos_map_size = hypertable_desc->natts;
+
+	if (rri->ri_projectReturning != NULL)
+	{
+		rri->ri_projectReturning =
+			get_adjusted_projection_info_returning(
```
Comment (erimatnor) [inline src/chunk_insert_state.c]: Inconsistent use of initial newline after opening paranthesis.
Also, for consistency, put one arg per line if breaking a function like this (also applies below)

File: src/chunk_dispatch.h [hunk 6]
```diff
@@ -28,6 +28,10 @@ typedef struct ChunkDispatch
 	ResultRelInfo *hypertable_result_rel_info;
 	OnConflictAction on_conflict;
 	List	   *arbiter_indexes;
+	int			returning_index;
```
Comment (erimatnor) [inline src/chunk_dispatch.h]: Does it make sense to consider just passing a pointer to the plan or something, instead of recreating a lot of fields?

Comment (cevian) [reply src/chunk_dispatch.h]: I considered that but decided against that because I want to reduce the exposure of plan stuff inside execution nodes. I think this indirection helps decouple the two.
