### PR TITLE
Check custom scan node registration

### LINKED ISSUE #3901: [Bug]: PG Upgrade from 12->13 fails with error
### What type of bug is this?

Unexpected error

### What subsystems and features are affected?

Other

### What happened?

Attempting to upgrade from PG12 to PG13 but was faced with the below error :

---loadable_libraries.txt---
could not load library "$libdir/timescaledb-2.5.0": ERROR: extensible node type "ConstraintAwareAppend" already exists 
In database: _timescaledb
We've seen such instances before and the resolution is to match their version of TimescaleDB across all of the databases they have. But in this case, this didn't work and the below error came  :

```
Error while upgrading extensions: ERROR:  functionality not supported under the current "timescale" license
HINT:  Upgrade your license to 'timescale' to use this free community feature.
CONTEXT:  SQL statement "ALTER MATERIALIZED VIEW custom_metric_readings_cagg_project_nums SET (timescaledb.materialized_only='t') "
PL/pgSQL function inline_code_block line 21 at EXECUTE

<psycopg2.extensions.Diagnostics object at 0x7fe86c0caa30>
```

For context, the service had two databases:

defaultdb : 2.4.2
_timescaledb : 2.5.0 (this database I believe is used by the platform for internal purposes)

Some scenarios that were tested:
1. Downgrade the timescaledb extension on _timescaledb to 2.4.2 to match defaultdb. Perform upgrade to PG13. Fails
2. DROP EXTENSION timescaledb on the _timescaledb instance. Perform upgrade to PG13. Fails

### TimescaleDB version affected

2.4.2

### PostgreSQL version used

12.9

### What operating system did you use?

MST

### What installation method did you use?

Other

### What platform did you run on?

Managed Service for TimescaleDB (MST/Aiven)

### Relevant log output and stack trace

_No response_

### How can we reproduce the bug?

_No response_

### PR DESCRIPTION
**Pull request by mkindahl**
When loading several different versions of shared libraries after a
restart, it might attempt to register the custom scan nodes several
times.  This is fixed by adding a function that checks if the custom
scan method was already registered and skips registering it if it was.

Fixes #3901

### CODE REVIEW

**Review by akuzm — APPROVED** [review]
The return value is always ignored, do we need it at all?

File: src/utils.h [hunk 1]
```diff
@@ -167,4 +168,24 @@ ts_clear_flags_32(uint32 bitmap, uint32 flags)
...
+ *
+ * When registering a custom scan node, it might be called multiple times when
+ * different databases have different versions of the extension installed, so
+ * this function can be used to try to register a custom scan method but not
+ * fail if it has already been registered.
+ *
+ * @retval true The custom scan method was registered
+ * @retval false The custom scan method was not registered
+ */
+static inline bool
```
Comment (fabriziomello) [inline src/utils.h:182]: Do we need to return `bool` since the callers doesn't do anything with the returned value?

Comment (mkindahl) [reply src/utils.h:182]: Was thinking that it could be useful, but let's cross that bridge when we come to it. Removed.

**Review by fabriziomello — APPROVED** [review]
