### PR TITLE
Fixes insert for 32bit architecture

### LINKED ISSUE #336: Crashes consistently on Arm 32 bit architecture when inserting into hypertable.
I have just downloaded version 0.7 under Armbian (Debian-stretch based) for a CubieTruck board. I installed Postgres 9.6 off the repos on a virgin Armbian re-install. Machine is clean as a whistle. 

Compiled timescaledb 0.7 after downloading the tarball. 

Followed instructions in the tutorial rigorously, three times. Each time, same thing - crashes the server. 

```
nvidia@tegra-ubuntu:~$ ssh tbrowne@192.168.1.192
tbrowne@192.168.1.192's password: 
  ____      _     _      _                   _    
 / ___|   _| |__ (_) ___| |_ _ __ _   _  ___| | __
| |  | | | | '_ \| |/ _ \ __| '__| | | |/ __| |/ /
| |__| |_| | |_) | |  __/ |_| |  | |_| | (__|   < 
 \____\__,_|_.__/|_|\___|\__|_|   \__,_|\___|_|\_\
                                                  

Welcome to ARMBIAN 5.35 user-built Debian GNU/Linux 9 (stretch) 4.13.16-sunxi   
System load:   1.03 0.38 0.14  	Up time:       1 min		
Memory usage:  2 % of 2011MB 	IP:            192.168.1.192
CPU temp:      38°C           	
Usage of /:    1% of 112G   	

[ General system configuration (beta): armbian-config ]

Last login: Tue Nov 28 22:51:51 2017 from 192.168.1.101

tbrowne@cubietruck:~$ psql
psql (9.6.6)
Type "help" for help.

tbrowne=# drop database tutorial;
ERROR:  database "tutorial" does not exist
tbrowne=# create database tutorial;
CREATE DATABASE
tbrowne=# \c tutorial
You are now connected to database "tutorial" as user "tbrowne".
tutorial=# CREATE EXTENSION IF NOT EXISTS timescaledb CASCADE;
CREATE EXTENSION
tutorial=# CREATE TABLE conditions (
tutorial(#   time        TIMESTAMPTZ       NOT NULL,
tutorial(#   location    TEXT              NOT NULL,
tutorial(#   temperature DOUBLE PRECISION  NULL,
tutorial(#   humidity    DOUBLE PRECISION  NULL
tutorial(# );
CREATE TABLE
tutorial=# 
tutorial=# SELECT create_hypertable('conditions', 'time');
 create_hypertable 
-------------------
 
(1 row)

tutorial=# INSERT INTO conditions(time, location, temperature, humidity)
tutorial-#   VALUES (NOW(), 'office', 70.0, 50.0);
server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
The connection to the server was lost. Attempting reset: Failed.
!> 
```

I'm sure you're not targeting arm32 architecture but I thought at least it should work on this little device? Maybe lots of IoT use cases for timeseries data? Happy to put up an account for you if you want to ssh into the Cubie and try it out for yourself. 

Personally will be targeting much bigger boxes but I like doing dev work on these weak CPUs because I get a much better idea of relative performance.

### PR DESCRIPTION
**Pull request by cevian**
Fixes problem with insert on 32bit architecture. Fixes #336.

### CODE REVIEW

File: src/dimension_slice.c [hunk 1]
```diff
@@ -354,10 +354,10 @@ dimension_slice_insert_relation(Relation rel, DimensionSlice *slice)
 
 	memset(values, 0, sizeof(values));
 	slice->fd.id = catalog_table_next_seq_id(catalog_get(), DIMENSION_SLICE);
-	values[Anum_dimension_slice_id - 1] = slice->fd.id;
```
Comment (RobAtticus) [inline src/dimension_slice.c]: just for reference, what are these if you don't cast them?

Comment (RobAtticus) [reply src/dimension_slice.c]: also, are there other places we need to check and explicitly cast?

Comment (cevian) [reply src/dimension_slice.c]: So if you don't pass it through *GetDatum then this is just a memory copy. This works if the memory representation of what you are setting is the same as what the Datum uses. However, this is architecture dependent. I tried to find all similar places.
