### PR TITLE
Fix timestamp out of range

### LINKED ISSUE #4117: CA Using TIME_BUCKET_NG Doesn't Refresh Data Correctly (a.k.a allow going back in time from `origin`)
### What type of bug is this?

Incorrect result, Unexpected error

### What subsystems and features are affected?

Continuous aggregate

### What happened?

I created a CA using the new `TIMESCALEDB_EXPERIMENTAL.TIME_BUCKET_NG` function and assigned it a refresh policy. The fresh policy would not update data correctly.

### TimescaleDB version affected

2.6.0

### PostgreSQL version used

14.2

### What operating system did you use?

Ubuntu 20.04.4 LTS

### What installation method did you use?

Deb/Apt

### What platform did you run on?

Not applicable

### Relevant log output and stack trace

Inline with the steps to reproduce.

### How can we reproduce the bug?

# Existing

My starting point prior to upgrading to 2.6.0 for doing a CA using a 1 DAY bucket.

```bash
CREATE MATERIALIZED VIEW one_day
    WITH (timescaledb.continuous) AS
        SELECT
            TIME_BUCKET('1 DAY', recorded_at) AS recorded_at,
            A                                 AS A,
            B                                 AS B,
            MIN(C)                            AS C,
            AVG(D)                            AS D,
            AVG(E)                            AS E,
            AVG(F)                            AS F
        FROM data
        GROUP BY 1, 2, 3
        WITH NO DATA;

ALTER MATERIALIZED VIEW one_day SET (timescaledb.materialized_only = true);
SELECT remove_continuous_aggregate_policy('one_day');
SELECT add_continuous_aggregate_policy('one_day',
    start_offset      => NULL,
    end_offset        => NULL,
    schedule_interval => INTERVAL '5 MINUTE'
);
```

# 2.6.0

I then attempted to recreate that same aggregate from above using the same refresh policy. It was at this point I started to encounter errors.

When I tried to use the function in this format:
```
TIMESCALEDB_EXPERIMENTAL.TIME_BUCKET_NG('1 DAY', recorded_at, timezone => 'US/Pacific') AS recorded_at,
```

It resulted in the following error:
```
ERROR:  only immutable expressions allowed in time bucket function
HINT:  Use an immutable expression as third argument to the time bucket function.
```

At this point I checked the I ran the following command to see what usages there are:

```
\df+ TIMESCALEDB_EXPERIMENTAL.TIME_BUCKET_NG
```

I saw there was an immutable one that seemed to take in the required parameters so I continued to recreate my CA:

```
CREATE MATERIALIZED VIEW one_day
    WITH (timescaledb.continuous) AS
        SELECT
            TIMESCALEDB_EXPERIMENTAL.TIME_BUCKET_NG('1 DAY', recorded_at, 'US/Pacific') AS recorded_at,
            A                                                                           AS A,
            B                                                                           AS B,
            MIN(C)                                                                      AS C,
            AVG(D)                                                                      AS D,
            AVG(E)                                                                      AS E,
            AVG(F)                                                                      AS F
        FROM data
        GROUP BY 1, 2, 3
        WITH NO DATA;

ALTER MATERIALIZED VIEW one_day SET (timescaledb.materialized_only = true);
SELECT remove_continuous_aggregate_policy('one_day');
SELECT add_continuous_aggregate_policy('one_day',
    start_offset      => NULL,
    end_offset        => NULL,
    schedule_interval => INTERVAL '5 MINUTE'
);
```

The CA wasn't getting refresh which lead me to check the job status which showed failures. Next I checked the logs and found the following messages:

```
2022-02-20 14:45:12.955 PST [569130] LOG:  job 1070 threw an error
2022-02-20 14:45:12.955 PST [569130] ERROR:  timestamp out of range
2022-02-20 14:45:12.957 PST [1774658] LOG:  background worker "Refresh Continuous Aggregate Policy [1070]" (PID 569130) exited with exit code 1
```

My hunch was using `NULL` for the `start_offset` and `end_offset` might be causing an issue. I updated them to the following:

```
SELECT add_continuous_aggregate_policy('one_day',
    start_offset      => INTERVAL '50 YEAR',
    end_offset        => INTERVAL '10 SECOND',
    schedule_interval => INTERVAL '5 MINUTE'
);
```

Again the CA wasn't being updated so I went back to the logs and found the following message:

```
2022-02-20 14:57:59.870 PST [584067] LOG:  job 1079 threw an error
2022-02-20 14:57:59.870 PST [584067] ERROR:  origin must be before the given date
```

If this is case it seems like the backend process should I either do `MAX(NOW() - start_offset, origin)` or reject the policy at creation time.

I adjusted the refresh policy to the following:

```
SELECT add_continuous_aggregate_policy('one_day',
    start_offset      => INTERVAL '20 YEAR',
    end_offset        => INTERVAL '10 SECOND',
    schedule_interval => INTERVAL '5 MINUTE'
);
```

Finally the refresh policies started firing without errors. After running some test queries it seemed that the data was stale, lagging by one day. Upon inspection of the logs I found the following:

```
2022-02-20 14:53:55.138 PST [579252] LOG:  refreshing continuous aggregate "one_day" in window [ 2012-02-21 00:00:00-08, 2022-02-20 00:00:00-08 ]
```

It seems that it is rounding the range used for selection which I believe is incorrect. I would want data that is older than `10 SECONDS` selected for insertion.

At this point I rolled back my CA to use the `TIME_BUCKET` function.
```

### PR DESCRIPTION
**Pull request by RafiaSabih**
When start or end for a refresh job is null, then it gives an error while bucketing because start and end are already min and max timestamp value before bucketing. Hence, skip bucketing for this case.

Partly fixes #4117

### CODE REVIEW

File: tsl/src/bgw_policy/continuous_aggregate_api.c [hunk 1]
```diff
@@ -110,21 +110,21 @@ get_time_from_config(const Dimension *dim, const Jsonb *config, const char *json
...
 int64
-policy_refresh_cagg_get_refresh_start(const Dimension *dim, const Jsonb *config)
+policy_refresh_cagg_get_refresh_start(const Dimension *dim, const Jsonb *config, bool *start_isnull)
 {
-	bool start_isnull;
-	int64 res = get_time_from_config(dim, config, POL_REFRESH_CONF_KEY_START_OFFSET, &start_isnull);
+	int64 res = get_time_from_config(dim, config, POL_REFRESH_CONF_KEY_START_OFFSET, start_isnull);
+
 	/* interpret NULL as min value for that type */
 	if (start_isnull)
```
Comment (svenklemm) [inline tsl/src/bgw_policy/continuous_aggregate_api.c:118]: Shouldnt this dereference the pointer now since you change the type
```suggestion
	if (*start_isnull)
```

File: tsl/src/bgw_policy/continuous_aggregate_api.c [hunk 2]
```diff
@@ -110,21 +110,21 @@ get_time_from_config(const Dimension *dim, const Jsonb *config, const char *json
...
 
 int64
-policy_refresh_cagg_get_refresh_end(const Dimension *dim, const Jsonb *config)
+policy_refresh_cagg_get_refresh_end(const Dimension *dim, const Jsonb *config, bool *end_isnull)
 {
-	bool end_isnull;
-	int64 res = get_time_from_config(dim, config, POL_REFRESH_CONF_KEY_END_OFFSET, &end_isnull);
+	int64 res = get_time_from_config(dim, config, POL_REFRESH_CONF_KEY_END_OFFSET, end_isnull);
+
 	if (end_isnull)
```
Comment (svenklemm) [inline tsl/src/bgw_policy/continuous_aggregate_api.c:128]: Same as above
```suggestion
	if (*end_isnull)
```

File: tsl/test/expected/cagg_bgw.out [hunk 3]
```diff
@@ -353,7 +353,10 @@ SELECT * FROM test_continuous_agg_view ORDER BY 1;
            0 |     1
            2 |     5
            4 |     9
-(3 rows)
+           6 |    13
+           8 |    17
+          10 |    10
+(6 rows)
```
Comment (svenklemm) [inline tsl/test/expected/cagg_bgw.out:359]: Why is this changing?

**Review by svenklemm — APPROVED** [review]

File: CHANGELOG.md [hunk 4]
```diff
@@ -7,6 +7,7 @@ accidentally triggering the load of a previous DB version.**
 ## Unreleased
 
 **Bugfixes**
+* #4804 Fix timestamp out of range
```
Comment (akuzm) [inline CHANGELOG.md:10]: In the light of our recent discussion about changelog messages, we could make it more readable for users, something along the lines of the PR description perhaps?

Comment (RafiaSabih) [reply CHANGELOG.md]: Good point, thanks.
