### PR TITLE
Suspend retention policies with caggs conflicts

### LINKED ISSUE #2530: Disable failing retention policies when upgrading to 2.0
Prior to 2.0, it was possible to create a continuous aggregate on a hypertable that had a retention policy. This would make the retention policy fail, but this wasn't made clear. It was also possible to add retention policies after creating continuous aggregates, even if those policies wouldn't work due to conflicting `ignore_invalidation_older_than` settings.

Because of the above situation, it is not unlikely that a database that is upgraded to 2.0 will have retention policies running that are in conflict with continuous aggregates and would therefore always fail. If those retention policies are migrated to 2.0 they will start to work, with possibly unintended consequences. Therefore, we should check during extension update to 2.0 for such retention policies and disable them.

### PR DESCRIPTION
**Pull request by WireBaron**
When upgrading from 1.7, it's possible to have retention policies
which overlap with continuous aggregates.  These make use of the
cascade_to_materializations parameter to avoid invalidating the
aggregate.

In 2.0 there is no equivalent behavior to prevent the retention from
disrupting the aggregate.  So during the 2.0 upgrade, check for any
running retention policies that are dropping chunks still used by a
continuous aggregate and suspend them (scheduled=>false).  This will
also print a notice informing the user of what happened and how to
resume the retention policy if that's what they truly want.

Fixes #2530

### CODE REVIEW

File: sql/updates/latest-dev.sql [hunk 1]
```diff
@@ -63,3 +63,21 @@ CREATE INDEX continuous_aggs_materialization_invalidation_log_idx ON
...
+BEGIN
+    FOR jobid IN
+        SELECT c.id
+        FROM _timescaledb_config.bgw_job a
+        LEFT JOIN _timescaledb_catalog.continuous_agg b ON a.hypertable_id = b.mat_hypertable_id
+        INNER JOIN _timescaledb_config.bgw_job c ON c.hypertable_id = b.raw_hypertable_id
+        WHERE a.proc_name = 'policy_refresh_continuous_aggregate' AND c.proc_name = 'policy_retention' AND c.scheduled
+            AND (a.config->'start_offset')::text::interval > (c.config->'drop_after')::text::interval
+    LOOP
+        RAISE NOTICE 'Retention job with id % will drop chunks while a continuous aggregate is still running on them. Suspending this job for now. If this is the desired behavior, you can reenable the job with: SELECT alter_job(%, scheduled=>true);', jobid, jobid;
```
Comment (mfreed) [inline sql/updates/latest-dev.sql:80]: I'm not sure this notice will suggest to users the potential risks from re-enabling --> they might just blindly do so.  Maybe something like the following, although it is long and may be shortened.

```suggestion
        RAISE NOTICE 'Data retention policy with job id % will drop chunks while a continuous aggregate may refresh the dropped region. Suspending this job for now, as otherwise data in the continuous aggregate view will be replaced with results from the now-deleted region.  To adjust the behavior, alter the 'drop_after' parameter of your data retention policy.  You can re-enable the data retention policy with: SELECT alter_job(%, scheduled=>true);', jobid, jobid;
```

File: sql/updates/latest-dev.sql [hunk 2]
```diff
@@ -63,3 +63,21 @@ CREATE INDEX continuous_aggs_materialization_invalidation_log_idx ON
...
+DECLARE
+  jobid INTEGER;
+BEGIN
+    FOR jobid IN
+        SELECT c.id
+        FROM _timescaledb_config.bgw_job a
+        LEFT JOIN _timescaledb_catalog.continuous_agg b ON a.hypertable_id = b.mat_hypertable_id
+        INNER JOIN _timescaledb_config.bgw_job c ON c.hypertable_id = b.raw_hypertable_id
+        WHERE a.proc_name = 'policy_refresh_continuous_aggregate' AND c.proc_name = 'policy_retention' AND c.scheduled
+            AND (a.config->'start_offset')::text::interval > (c.config->'drop_after')::text::interval
```
Comment (gayyappan) [inline sql/updates/latest-dev.sql:78]: we could have integer offsets as well for cont. aggregates that use integer time buckets.

**Review by svenklemm — APPROVED** [review]

File: sql/updates/latest-dev.sql (hunk 2 above)
Comment (WireBaron) [reply sql/updates/latest-dev.sql:78]: Actually it does work here (I tested this case).  Casting the int to text and then to interval converts the int to a seconds interval, which will do the right thing for determining if the cagg and retention policy overlap.

File: sql/updates/latest-dev.sql (hunk 1 above)
Comment (erimatnor) [reply sql/updates/latest-dev.sql:80]: I would prefer if we split this up in a simple main message and detail/hint as we do for normal errors/notices. Something like:

```
RAISE NOTICE 'suspending retention policy with ID %', jobid
      USING DETAIL = 'The retention policy was not running correctly so it was suspended. Enabling it again might remove data from the continuous aggregates.'
      USING HINT = 'Adjust the policy settings and enable the policy again with: SELECT alter_job(%, scheduled=>true).', jobid;
```

Please try to also follow the error/message style guide as any normal message.

File: sql/updates/latest-dev.sql (hunk 2 above)
Comment (erimatnor) [reply sql/updates/latest-dev.sql:78]: If this works as intended, I suggest a comment to make it clear that the behavior is intentional.

Comment (erimatnor) [reply sql/updates/latest-dev.sql:78]: Do we need to check the `cascade_to_materializations` settings of the policy prior to being converted to the new format? I guess if that parameter was set to true, the policy was not failing and the intention was in fact to drop data from the continuous aggregates.

**Comment by erimatnor** [comment]
@WireBaron I want to make sure that we are  on the same page w.r.t. the reason for suspending a policy.

The PR description seems to emphasize that there might be valid policies with `cascade_to_materializations=true`. But such policies shouldn't necessarily be suspended since the intention of those are to in fact drop data from the continuous aggregates.

The main case that we wanted to protect against in issue #2530 was one where you could have failing retention policies, i.e., those running with  `cascade_to_materializations=false` and at the same time conflicting with `ignore_invalidation_older_than`. 

For instance. This is one use case that we were thinking about:

1. User creates a hypertable "foo"
2. User creates a retention policy on  "foo" with `cascade_to_materialization=false`
3. At some point later, the user creates a cagg on "foo". The retention policy will now start to fail and the only way to know is that no data is dropped and a non-zero exit status reported in the postgres log (it is not marked as an error, so easy to miss). 
4. The user upgrades to 2.0.

File: sql/updates/latest-dev.sql (hunk 1 above)
Comment (WireBaron) [reply sql/updates/latest-dev.sql:80]: Hmm, I do like the idea of providing a more descriptive message here.  However we do encourage people to just just drop and recreate retention policies rather than try to update the jsonb config through alter_job.  Maybe this instead:
```        RAISE NOTICE 'Data retention policy (formerly drop_chunk policy) with job id % will drop chunks while a continuous aggregate is still running on them. Suspending this job as it will likely result in overwriting the aggregate with empty data. If this is actually the desired behavior, you can reenable the job with: SELECT alter_job(%, scheduled=>true);  Otherwise, please create a new rention_policy with a larger drop_after parameter and remove the old policy with: SELECT delete_job(%)', jobid, jobid, jobid;```

Comment (WireBaron) [reply sql/updates/latest-dev.sql:80]: Ahh, just saw Erik's comment, let me rework this a bit more.

File: sql/updates/latest-dev.sql (hunk 2 above)
Comment (WireBaron) [reply sql/updates/latest-dev.sql:78]: We actually can't check `cascade_to_materializations` at this point as we have to do this update after we complete the rc1 update.  So that parameter will no longer exist by the time we do this update.

File: sql/updates/latest-dev.sql (hunk 1 above)
Comment (WireBaron) [reply sql/updates/latest-dev.sql]:
```        
RAISE NOTICE 'Suspending data retention policy with job id %.', jobid
            USING DETAIL = 'The retention policy (formerly drop_chunks policy) will drop chunks while a continuous aggregate is still running on them. This will likely result in overwriting the aggregate with empty data.',
            HINT = ('To restore the retention policy, with the possibility of updating aggregates with dropped data, run: SELECT alter_job(%, scheduled=>true);  Otherwise, please create a new rention_policy with a larger drop_after parameter and remove the old policy with: SELECT delete_job(%);', jobid, jobid);
 ```

Comment (erimatnor) [reply sql/updates/latest-dev.sql]: Note that the first letter of the main message should not be capitalized: https://www.postgresql.org/docs/current/error-style-guide.html

I don't think the hint should be in parentheses.

File: sql/updates/latest-dev.sql (hunk 2 above)
Comment (erimatnor) [reply sql/updates/latest-dev.sql:78]: But I guess it must be possible to check this during the update process at some point. I guess it is fine to not do this and just disable all policies, even those that weren't failing and "did the right thing". But we must decide that this is the semantics we'd like to have and then describe the behavior in the migration doc so that users can be advised to take appropriate action.

File: sql/updates/latest-dev.sql [hunk 3]
```diff
@@ -63,3 +63,23 @@ CREATE INDEX continuous_aggs_materialization_invalidation_log_idx ON
...
+    LOOP
+        RAISE NOTICE 'Suspending data retention policy with job id %.', jobid
```
Comment (erimatnor) [inline sql/updates/latest-dev.sql:80]:
```suggestion
        RAISE NOTICE 'suspending data retention policy with job id %.', jobid
```

Comment (WireBaron) [reply sql/updates/latest-dev.sql]: Fixed

File: sql/updates/latest-dev.sql (hunk 2 above)
Comment (WireBaron) [reply sql/updates/latest-dev.sql:79]: I think the best approach at this point is to raise this notice and change all tables that have this conflict.  It will be annoying for any users who are intentionally doing this, but I can't actually think of a valid use case where a user should intentionally be doing this (it seems just dropping the aggregated chunk would be the solution they'd want to be using).

File: sql/updates/latest-dev.sql (hunk 1 above)
Comment (WireBaron) [reply sql/updates/latest-dev.sql]: Good catch, fixed

**Review by gayyappan — APPROVED** [review]
