### PR TITLE
Fix sort pushdown for partially compressed chunks

### LINKED ISSUE #6975: [Bug]: Could not find pathkey item to sort on partially compressed chunks of a hypertable
### What type of bug is this?

Unexpected error

### What subsystems and features are affected?

Query executor, Query planner

### What happened?

The problem occurs for a query that takes the form:

```
select *
from measurements
       join devices on measurements.device_id = devices.id
where generated_at > '2023-01-04 12:00:00'
  and generated_at < '2023-01-19 12:17:00'
  and device_id = 1
order by generated_at, location_id, device_id, devices.name;
```

The query is not a production like query. It instead comes from the included script that has a more minimal reproduction path to get to the same error. Here
- measurements is a hypertable
- the generated_at clause selects from a partially compressed chunk
- devices is a regular table
- the sorting trips up the query planner. (Note: In the real world I'm not sorting by devices.name but by the primary key of the joined table)

It could be similar to https://github.com/timescale/timescaledb/issues/2232 But that is almost impossible to tell since that ticket is neither moving nor does it have a clean enough reproduction path.

### TimescaleDB version affected

2.14.2

### PostgreSQL version used

14.1

### What operating system did you use?

window 11 x64

### What installation method did you use?

Docker

### What platform did you run on?

Timescale Cloud

### Relevant log output and stack trace

```bash
ERROR: could not find pathkey item to sort
```

### How can we reproduce the bug?

```bash
-- starting on an empty database
-- running docker image: image: timescale/timescaledb:2.14.2-pg14
-- with timescale 2.14.2
SELECT extversion FROM pg_extension where extname = 'timescaledb';

CREATE TABLE measurements (
                              "generated_at" timestamptz not null,
                              "value" int4 not null,
                              "location_id" int4 not null,
                              "device_id" int4 not null
);

CREATE TABLE devices (
                            "id" int4 not null,
                            "name" varchar(255) not null
);

DO $$
  BEGIN
    FOR i IN 1..100000 LOOP
        insert into devices (id, name) values (i, 'device ' || i);
      END LOOP;
  END
$$;

ALTER TABLE "measurements" ADD CONSTRAINT measurements_pkey PRIMARY KEY (location_id, generated_at);

SELECT create_hypertable (
               'measurements',
               'generated_at',
               chunk_time_interval => INTERVAL '7 days',
               if_not_exists => TRUE,
               create_default_indexes => FALSE
           );

-- create a bit of test data we want to retrieve
insert into measurements (generated_at, value, location_id, device_id) values ('2023-01-01 12:00:00', 1, 1, 1);
insert into measurements (generated_at, value, location_id, device_id) values ('2023-01-02 12:00:00', 1, 1, 1);
insert into measurements (generated_at, value, location_id, device_id) values ('2023-01-03 12:00:00', 1, 1, 1);
insert into measurements (generated_at, value, location_id, device_id) values ('2023-01-04 12:00:00', 1, 1, 1);
insert into measurements (generated_at, value, location_id, device_id) values ('2023-01-05 12:00:00', 1, 1, 1);
insert into measurements (generated_at, value, location_id, device_id) values ('2023-01-06 12:00:00', 1, 1, 1);
insert into measurements (generated_at, value, location_id, device_id) values ('2023-01-07 12:00:00', 1, 1, 1);
insert into measurements (generated_at, value, location_id, device_id) values ('2023-01-08 12:00:00', 1, 1, 1);
insert into measurements (generated_at, value, location_id, device_id) values ('2023-01-09 12:00:00', 1, 1, 1);
insert into measurements (generated_at, value, location_id, device_id) values ('2023-01-11 12:00:00', 1, 1, 1);
insert into measurements (generated_at, value, location_id, device_id) values ('2023-01-12 12:00:00', 1, 1, 1);
insert into measurements (generated_at, value, location_id, device_id) values ('2023-01-13 12:00:00', 1, 1, 1);
insert into measurements (generated_at, value, location_id, device_id) values ('2023-01-14 12:00:00', 1, 1, 1);
insert into measurements (generated_at, value, location_id, device_id) values ('2023-01-15 12:00:00', 1, 1, 1);
insert into measurements (generated_at, value, location_id, device_id) values ('2023-01-16 12:00:00', 1, 1, 1);
insert into measurements (generated_at, value, location_id, device_id) values ('2023-01-17 12:00:00', 1, 1, 1);
insert into measurements (generated_at, value, location_id, device_id) values ('2023-01-18 12:00:00', 1, 1, 1);
insert into measurements (generated_at, value, location_id, device_id) values ('2023-01-19 12:00:00', 1, 1, 1);

insert into measurements (generated_at, value, location_id, device_id) values ('2023-01-01 12:01:00', 1, 1, 2);
insert into measurements (generated_at, value, location_id, device_id) values ('2023-01-02 12:01:00', 1, 1, 2);
insert into measurements (generated_at, value, location_id, device_id) values ('2023-01-03 12:01:00', 1, 1, 2);
insert into measurements (generated_at, value, location_id, device_id) values ('2023-01-04 12:01:00', 1, 1, 2);
insert into measurements (generated_at, value, location_id, device_id) values ('2023-01-05 12:01:00', 1, 1, 2);
insert into measurements (generated_at, value, location_id, device_id) values ('2023-01-06 12:01:00', 1, 1, 2);
insert into measurements (generated_at, value, location_id, device_id) values ('2023-01-07 12:01:00', 1, 1, 2);
insert into measurements (generated_at, value, location_id, device_id) values ('2023-01-08 12:01:00', 1, 1, 2);
insert into measurements (generated_at, value, location_id, device_id) values ('2023-01-09 12:01:00', 1, 1, 2);
insert into measurements (generated_at, value, location_id, device_id) values ('2023-01-11 12:01:00', 1, 1, 2);
insert into measurements (generated_at, value, location_id, device_id) values ('2023-01-12 12:01:00', 1, 1, 2);
insert into measurements (generated_at, value, location_id, device_id) values ('2023-01-13 12:01:00', 1, 1, 2);
insert into measurements (generated_at, value, location_id, device_id) values ('2023-01-14 12:01:00', 1, 1, 2);
insert into measurements (generated_at, value, location_id, device_id) values ('2023-01-15 12:01:00', 1, 1, 2);
insert into measurements (generated_at, value, location_id, device_id) values ('2023-01-16 12:01:00', 1, 1, 2);
insert into measurements (generated_at, value, location_id, device_id) values ('2023-01-17 12:01:00', 1, 1, 2);
insert into measurements (generated_at, value, location_id, device_id) values ('2023-01-18 12:01:00', 1, 1, 2);
insert into measurements (generated_at, value, location_id, device_id) values ('2023-01-19 12:01:00', 1, 1, 2);

-- create a lot of junk data that will make sure we don't end up with a SeqScan query plan that will work
DO $$
  BEGIN
    FOR i IN 3..100000 LOOP
        insert into measurements (generated_at, value, location_id, device_id) values ('2023-01-19 12:02:00', 1, i, i);
        insert into measurements (generated_at, value, location_id, device_id) values ('2023-01-19 12:03:00', 1, i, i);
        insert into measurements (generated_at, value, location_id, device_id) values ('2023-01-19 12:04:00', 1, i, i);
        insert into measurements (generated_at, value, location_id, device_id) values ('2023-01-19 12:05:00', 1, i, i);
        insert into measurements (generated_at, value, location_id, device_id) values ('2023-01-19 12:06:00', 1, i, i);
        insert into measurements (generated_at, value, location_id, device_id) values ('2023-01-19 12:07:00', 1, i, i);
        insert into measurements (generated_at, value, location_id, device_id) values ('2023-01-19 12:08:00', 1, i, i);
        insert into measurements (generated_at, value, location_id, device_id) values ('2023-01-19 12:09:00', 1, i, i);
        insert into measurements (generated_at, value, location_id, device_id) values ('2023-01-19 12:10:00', 1, i, i);
        insert into measurements (generated_at, value, location_id, device_id) values ('2023-01-19 12:11:00', 1, i, i);
        insert into measurements (generated_at, value, location_id, device_id) values ('2023-01-19 12:12:00', 1, i, i);
        insert into measurements (generated_at, value, location_id, device_id) values ('2023-01-19 12:13:00', 1, i, i);
        insert into measurements (generated_at, value, location_id, device_id) values ('2023-01-19 12:14:00', 1, i, i);
        insert into measurements (generated_at, value, location_id, device_id) values ('2023-01-19 12:15:00', 1, i, i);
        insert into measurements (generated_at, value, location_id, device_id) values ('2023-01-19 12:16:00', 1, i, i);
        insert into measurements (generated_at, value, location_id, device_id) values ('2023-01-19 12:17:00', 1, i, i);
        insert into measurements (generated_at, value, location_id, device_id) values ('2023-01-19 12:18:00', 1, i, i);
        insert into measurements (generated_at, value, location_id, device_id) values ('2023-01-19 12:19:00', 1, i, i);
        insert into measurements (generated_at, value, location_id, device_id) values ('2023-01-19 12:20:00', 1, i, i);
        insert into measurements (generated_at, value, location_id, device_id) values ('2023-01-19 12:21:00', 1, i, i);
        insert into measurements (generated_at, value, location_id, device_id) values ('2023-01-19 12:22:00', 1, i, i);
        insert into measurements (generated_at, value, location_id, device_id) values ('2023-01-19 12:23:00', 1, i, i);
        insert into measurements (generated_at, value, location_id, device_id) values ('2023-01-19 12:24:00', 1, i, i);
        insert into measurements (generated_at, value, location_id, device_id) values ('2023-01-19 12:25:00', 1, i, i);
        insert into measurements (generated_at, value, location_id, device_id) values ('2023-01-19 12:26:00', 1, i, i);
        insert into measurements (generated_at, value, location_id, device_id) values ('2023-01-19 12:27:00', 1, i, i);
        insert into measurements (generated_at, value, location_id, device_id) values ('2023-01-19 12:28:00', 1, i, i);
        insert into measurements (generated_at, value, location_id, device_id) values ('2023-01-19 12:29:00', 1, i, i);
      END LOOP;
  END
$$;

-- allow compression
ALTER TABLE measurements SET (timescaledb.compress, timescaledb.compress_segmentby = 'location_id,device_id');

-- compress all chunks
DO $$
  DECLARE chunk regclass;
  BEGIN
    FOR chunk IN SELECT format('%I.%I', chunk_schema, chunk_name)::regclass
                 FROM timescaledb_information.chunks
                 WHERE is_compressed = false and hypertable_name = 'measurements'
      LOOP
        RAISE NOTICE 'compressing cunk %', chunk::text;
        PERFORM compress_chunk(chunk);
      END LOOP;
  END
$$;

-- Now we mess around a bit with the chunk to make it partially compressed
delete from measurements where generated_at = '2023-01-07 12:01:00';
delete from measurements where generated_at = '2023-01-08 12:01:00';
insert into measurements (generated_at, value, location_id, device_id) values ('2023-01-07 12:01:00', 1, 1, 2);
insert into measurements (generated_at, value, location_id, device_id) values ('2023-01-08 12:01:00', 1, 1, 2);
update measurements set value = 2 where generated_at = '2023-01-07 12:01:00';

-- And mess with it some more...
DO $$
  BEGIN
    FOR i IN 3..5 LOOP
        update measurements set value = i where generated_at = '2023-01-19 12:02:00' and location_id = i and device_id = i;
        update measurements set value = i where generated_at = '2023-01-19 12:03:00' and location_id = i and device_id = i;
        update measurements set value = i where generated_at = '2023-01-19 12:04:00' and location_id = i and device_id = i;
        update measurements set value = i where generated_at = '2023-01-19 12:05:00' and location_id = i and device_id = i;
        update measurements set value = i where generated_at = '2023-01-19 12:06:00' and location_id = i and device_id = i;
        update measurements set value = i where generated_at = '2023-01-19 12:07:00' and location_id = i and device_id = i;
        update measurements set value = i where generated_at = '2023-01-19 12:08:00' and location_id = i and device_id = i;
        update measurements set value = i where generated_at = '2023-01-19 12:09:00' and location_id = i and device_id = i;
        update measurements set value = i where generated_at = '2023-01-19 12:10:00' and location_id = i and device_id = i;
        update measurements set value = i where generated_at = '2023-01-19 12:11:00' and location_id = i and device_id = i;
        update measurements set value = i where generated_at = '2023-01-19 12:12:00' and location_id = i and device_id = i;
        update measurements set value = i where generated_at = '2023-01-19 12:13:00' and location_id = i and device_id = i;
        update measurements set value = i where generated_at = '2023-01-19 12:14:00' and location_id = i and device_id = i;
        update measurements set value = i where generated_at = '2023-01-19 12:15:00' and location_id = i and device_id = i;
        update measurements set value = i where generated_at = '2023-01-19 12:16:00' and location_id = i and device_id = i;
        update measurements set value = i where generated_at = '2023-01-19 12:17:00' and location_id = i and device_id = i;
        update measurements set value = i where generated_at = '2023-01-19 12:18:00' and location_id = i and device_id = i;
        update measurements set value = i where generated_at = '2023-01-19 12:19:00' and location_id = i and device_id = i;
        update measurements set value = i where generated_at = '2023-01-19 12:20:00' and location_id = i and device_id = i;
        update measurements set value = i where generated_at = '2023-01-19 12:21:00' and location_id = i and device_id = i;
        update measurements set value = i where generated_at = '2023-01-19 12:22:00' and location_id = i and device_id = i;
        update measurements set value = i where generated_at = '2023-01-19 12:23:00' and location_id = i and device_id = i;
        update measurements set value = i where generated_at = '2023-01-19 12:24:00' and location_id = i and device_id = i;
        update measurements set value = i where generated_at = '2023-01-19 12:25:00' and location_id = i and device_id = i;
        update measurements set value = i where generated_at = '2023-01-19 12:26:00' and location_id = i and device_id = i;
        update measurements set value = i where generated_at = '2023-01-19 12:27:00' and location_id = i and device_id = i;
        update measurements set value = i where generated_at = '2023-01-19 12:28:00' and location_id = i and device_id = i;
        update measurements set value = i where generated_at = '2023-01-19 12:29:00' and location_id = i and device_id = i;
      END LOOP;
  END
$$;

-- This now errors with error ERROR: could not find pathkey item to sort.
explain select * from measurements join devices on measurements.device_id = devices.id where generated_at > '2023-01-04 12:00:00' and generated_at < '2023-01-19 12:17:00' and device_id = 1 order by generated_at,location_id,device_id, devices.name;
-- and so will:
select *
from measurements
       join devices on measurements.device_id = devices.id
where generated_at > '2023-01-04 12:00:00'
  and generated_at < '2023-01-19 12:17:00'
  and device_id = 1
order by generated_at, location_id, device_id, devices.name;

--recompress all chunks:
DO $$
  DECLARE chunk regclass;
  BEGIN
    FOR chunk IN SELECT format('%I.%I', chunk_schema, chunk_name)::regclass
                 FROM timescaledb_information.chunks
                 WHERE hypertable_name = 'measurements'
      LOOP
        RAISE NOTICE 're-compressing cunk %', chunk::text;
        PERFORM decompress_chunk(chunk);
        PERFORM compress_chunk(chunk);
      END LOOP;
  END
$$;

-- This now no longer errors
explain select * from measurements join devices on measurements.device_id = devices.id where generated_at > '2023-01-04 12:00:00' and generated_at < '2023-01-19 12:17:00' and device_id = 1 order by generated_at,location_id,device_id, devices.name;
-- and neither does:
select * from measurements join devices on measurements.device_id = devices.id where generated_at > '2023-01-04 12:00:00' and generated_at < '2023-01-19 12:17:00' and device_id = 1 order by generated_at,location_id,device_id, devices.name;
```

### PR DESCRIPTION
**Pull request by antekresic**
Using all sort pathkeys with append node for partially compressed chunks ends up creating invalid plans when using joined columns in ORDER BY clause. Using the pathkey prefix that belongs to the underlying relation fixes the issue and sets us up for possible incremental sort optimization.

Fixes #6975

### CODE REVIEW

File: tsl/src/nodes/decompress_chunk/decompress_chunk.c [hunk 1]
```diff
@@ -971,6 +971,23 @@ ts_decompress_chunk_generate_paths(PlannerInfo *root, RelOptInfo *chunk_rel, Hyp
 															   req_outer);
 			}
 			else
+			{
+				/* Make sure we are only using pathkeys found in the relation */
```
Comment (svenklemm) [inline tsl/src/nodes/decompress_chunk/decompress_chunk.c:975]:
```suggestion
				/* Check all pathkey components can be satisfied by current chunk */
```

File: .unreleased/pr_6992 [hunk 2]
```diff
@@ -0,0 +1,2 @@
+Fixes: #6975 Fix segfault in compress_chunk with primary space partition
+Thanks: @srieding for reporing issue with partially compressed chunks and ordering on joined columns
```
Comment (svenklemm) [inline .unreleased/pr_6992:2]:
```suggestion
Thanks: @srieding for reporting an issue with partially compressed chunks and ordering on joined columns
```

**Review by svenklemm — APPROVED** [review]

File: .unreleased/pr_6992 (hunk 2 above)
Comment (svenklemm) [reply .unreleased/pr_6992:2]: I vaguely remember there being other issues with the same error message,

File: .unreleased/pr_6992 [hunk 3]
```diff
@@ -0,0 +1,2 @@
+Fixes: #6975 Fix segfault in compress_chunk with primary space partition
```
Comment (svenklemm) [inline .unreleased/pr_6992:1]:
```suggestion
```
Pretty sure that is from a different pr

File: .unreleased/pr_6992 (hunk 2 above)
Comment (svenklemm) [reply .unreleased/pr_6992]: https://github.com/timescale/timescaledb/issues/2232

Comment (antekresic) [reply .unreleased/pr_6992]: Yeah, but it doesn't look like it was caused due to this problem.

**Review by nikkhils — APPROVED** [review]
LGTM!
