### PR TITLE
Fix partitioning functions

### LINKED ISSUE #4575: [Bug]: unsupported expression argument node type 112 when calling `_timescaledb_internal.get_partition_hash`
### What type of bug is this?

Unexpected error

### What subsystems and features are affected?

Query executor

### What happened?

When calling the `_timescaledb_internal.get_partition_hash` function from a procedure or immutable function, the query fails with the error message `Query 1 ERROR: ERROR:  unsupported expression argument node type 112`.
I could not find any additional info in the logs.

I initially ran into this bug on 2.7.0 and thought it might be related to: #4489. Therefore i tried upgrading to 2.7.2 where this issue should be fixed, but it seems to not fix this. 

### TimescaleDB version affected

2.7.0 - 2.7.2

### PostgreSQL version used

14.4

### What operating system did you use?

MAC OS 11.6.2

### What installation method did you use?

Docker

### What platform did you run on?

On prem/Self-hosted

### Relevant log output and stack trace

```bash
Query 1 ERROR: ERROR:  unsupported expression argument node type 112
```

### How can we reproduce the bug?

```bash
CREATE OR REPLACE FUNCTION my_function(IN partition_key integer) RETURNS integer
AS 'select _timescaledb_internal.get_partition_hash($1);'
LANGUAGE SQL;

CREATE OR REPLACE FUNCTION my_immutable_function(IN partition_key integer) RETURNS integer
AS 'select _timescaledb_internal.get_partition_hash($1);'
LANGUAGE SQL
IMMUTABLE;

CREATE OR REPLACE PROCEDURE my_procedure(IN partition_key integer)
AS $$
DECLARE
    partition_hash integer; 
BEGIN
	-- Need to do some things based on partition hash
	select _timescaledb_internal.get_partition_hash(partition_key) INTO partition_hash; -- this eventually fails with the unsupported node type error	
END;
$$ LANGUAGE PLPGSQL;

SELECT my_function(1); -- This will not fail
SELECT my_immutable_function(1); -- This will always fail with: Query 1 ERROR: ERROR:  unsupported expression argument node type 112
CALL my_procedure(1); -- This will eventually fail with same error as above
```

### PR DESCRIPTION
**Pull request by fabriziomello**
When executing `get_partition_{hash|for_key}` inside an IMMUTABLE
function we're getting the following error:

`ERROR: unsupported expression argument node type 112`

This error is because the underlying `resolve_function_argtype` was not
dealing with `T_Param` node type.

Fixed it by dealing properly with `T_Param` node type returning the
`paramtype` for the argument type.

Fixes #4575

### CODE REVIEW

**Review by pmwkaa — APPROVED** [review]

File: src/partitioning.c [hunk 1]
```diff
@@ -317,6 +317,9 @@ resolve_function_argtype(FunctionCallInfo fcinfo)
 			/* Argument is function, so our input is its result type */
 			argtype = ((FuncExpr *) node)->funcresulttype;
 			break;
+		case T_Param:
+			argtype = ((Param *) node)->paramtype;
+			break;
 		default:
 			elog(ERROR, "unsupported expression argument node type %u", nodeTag(node));
```
Comment (svenklemm) [inline src/partitioning.c:324]: might be nice to use ts_get_node_name here but that would require adding the primnodes.h nodes to that function

**Review by svenklemm — APPROVED** [review]

File: src/partitioning.c (hunk 1 above)
Comment (fabriziomello) [reply src/partitioning.c:324]: will send a following PR adding it, thanks!
