### PR TITLE
Fix DML decompression issues with bitmap heap scan

### LINKED ISSUE #5658: [Bug]: BitmapHeapScan during DML on compressed chunks not modifying correct tuples
### What type of bug is this?

Data corruption

### What subsystems and features are affected?

Compression

### What happened?

When issuing an UPDATE/DELETE command on compressed chunks and the plan includes a BitmapHeapScan, not all data that should be delete is deleted. This specifically happens when data is inserted in the same transaction the DML command is issued in. There seems to be a problem in snapshot handling.

### TimescaleDB version affected

main branch

### PostgreSQL version used

15

### What operating system did you use?

Ubuntu 22.04.1

### What installation method did you use?

Source

### What platform did you run on?

On prem/Self-hosted

### Relevant log output and stack trace

_No response_

### How can we reproduce the bug?

```bash
create extension if not exists timescaledb ;

DROP TABLE IF EXISTS metrics_compressed;
-- create hypertable with compression
CREATE TABLE metrics_compressed(filler_1 int, filler_2 int, filler_3 int, time timestamptz NOT NULL, device_id int, v0 int, v1 int, v2 float, v3 float);
CREATE INDEX ON metrics_compressed(time);
CREATE INDEX ON metrics_compressed(device_id,time);
SELECT create_hypertable('metrics_compressed','time',create_default_indexes:=false);

ALTER TABLE metrics_compressed DROP COLUMN filler_1;
INSERT INTO metrics_compressed(time,device_id,v0,v1,v2,v3) SELECT time, device_id, device_id+1,  device_id + 2, device_id + 0.5, NULL FROM generate_series('2000-01-01 0:00:00+0'::timestamptz,'2000-01-05 23:55:00+0','2m') gtime(time), generate_series(1,5,1) gdevice(device_id);
ALTER TABLE metrics_compressed DROP COLUMN filler_2;
INSERT INTO metrics_compressed(time,device_id,v0,v1,v2,v3) SELECT time, device_id, device_id-1, device_id + 2, device_id + 0.5, NULL FROM generate_series('2000-01-06 0:00:00+0'::timestamptz,'2000-01-12 23:55:00+0','2m') gtime(time), generate_series(1,5,1) gdevice(device_id);
ALTER TABLE metrics_compressed DROP COLUMN filler_3;
INSERT INTO metrics_compressed(time,device_id,v0,v1,v2,v3) SELECT time, device_id, device_id, device_id + 2, device_id + 0.5, NULL FROM generate_series('2000-01-13 0:00:00+0'::timestamptz,'2000-01-19 23:55:00+0','2m') gtime(time), generate_series(1,5,1) gdevice(device_id);
ANALYZE metrics_compressed;

-- compress chunks
ALTER TABLE metrics_compressed SET (timescaledb.compress, timescaledb.compress_orderby='time DESC', timescaledb.compress_segmentby='device_id');
SELECT compress_chunk(c.schema_name|| '.' || c.table_name)
FROM _timescaledb_catalog.chunk c, _timescaledb_catalog.hypertable ht where c.hypertable_id = ht.id and ht.table_name = 'metrics_compressed' and c.compressed_chunk_id IS NULL
ORDER BY c.table_name DESC;


BEGIN;


SELECT count(*) from metrics_compressed where device_id = 1;

INSERT INTO metrics_compressed(time,device_id,v0,v1,v2,v3) SELECT time, device_id, device_id+1,  device_id + 2, device_id + 1000, NULL FROM generate_series('2000-01-01 0:00:00+0'::timestamptz,'2000-01-05 23:55:00+0','2m') gtime(time), generate_series(1,5,1) gdevice(device_id);

SELECT count(*) from metrics_compressed where device_id = 1;
analyze metrics_compressed;
--set timescaledb.enable_transparent_decompression = off;

explain delete from public.metrics_compressed
where public.metrics_compressed.device_id = 1;

delete from metrics_compressed
where metrics_compressed.device_id = 1;
-- this should be 0 but its not
SELECT count(*) from metrics_compressed where device_id = 1;

commit;
```

### PR DESCRIPTION
**Pull request by antekresic**
Bitmap heap scans are specific in that they store scan state during node initialization. This means they would not pick up on any data that might have been decompressed during a DML command from the compressed chunk. To avoid this, we update the snapshot on the node scan state and issue a rescan to update the internal state.

Fixes #5658 

Disable-check: force-changelog-changed

### CODE REVIEW

**Review by svenklemm — APPROVED** [review]

File: tsl/src/compression/compression.c [hunk 1]
```diff
@@ -2483,6 +2488,24 @@ decompress_chunk_walker(PlanState *ps, List *relids)
...
+				 * data. To circumvent this issue, we change the internal scan state to use the
+				 * transaction snapshot and execute a rescan so the scan state is set correctly and
+				 * includes the new data.
+				 */
+				if (should_rescan)
+				{
+					ScanState *ss = ((ScanState *) ps);
+					if (ss && ss->ss_currentScanDesc)
+					{
+						ss->ss_currentScanDesc->rs_snapshot = GetTransactionSnapshot();
```
Comment (akuzm) [inline tsl/src/compression/compression.c:2505]: Postgres almost never uses `GetTransactionSnapshot()` like this. Why aren't we using `CommandCounterIncrement` like e.g. `fmgr_sql` that calls SQL functions that can modify tables?

Comment (antekresic) [reply tsl/src/compression/compression.c:2505]: They actually they do use `GetTransactionSnapshot()`: https://github.com/postgres/postgres/blob/master/src/backend/executor/functions.c#L1180

I think this snapshot manipulation can be done better but at this point this is the minimal change to fix the issue.

Comment (akuzm) [reply tsl/src/compression/compression.c:2505]: It only does that once if it doesn't have a snapshot already. And also does `PushActiveSnapshot` (no idea what this is). I also wonder how exactly it works in Repeatable Read, when GetSnapshotData always returns the same snapshot, the first in transaction.

Anyway, don't mind me, I realized I'll need to spend a week on this to meaningfully comment :smile: Just saw an unusual thing.

Comment (akuzm) [reply tsl/src/compression/compression.c:2505]: > Anyway, don't mind me, I realized I'll need to spend a week on this to meaningfully comment  Just saw an unusual thing.

The only thing I would suggest is to test this under repeatable read. The correct visibility-handling code should work for all isolation levels without much special-casing.

**Review by fabriziomello — APPROVED** [review]

File: tsl/src/compression/compression.c (hunk 1 above)
Comment (sb230132) [inline tsl/src/compression/compression.c:2505]: Here we are changing state of scan node. I think its safe to reset to its original state once we finish rescanning.

File: tsl/test/sql/compression_update_delete.sql [hunk 2]
```diff
@@ -973,6 +973,21 @@ DELETE FROM tab1 WHERE tab1.device_id = 1;
...
+-- verify that bitmap heap scans work on all the correct data and
+-- none of it left over after the dml command
+BEGIN;
+SELECT count(*) FROM tab1 WHERE device_id = 1;
+INSERT INTO tab1(time,device_id,v0,v1,v2,v3) SELECT time, device_id, device_id+1,  device_id + 2, device_id + 1000, NULL FROM generate_series('2000-01-01 0:00:00+0'::timestamptz,'2000-01-05 23:55:00+0','2m') gtime(time), generate_series(1,5,1) gdevice(device_id);
+SELECT count(*) FROM tab1 WHERE device_id = 1;
+ANALYZE tab1;
+SET enable_seqscan = off;
+SET enable_indexscan = off;
+EXPLAIN (costs off) DELETE FROM tab1 WHERE tab1.device_id = 1;
```
Comment (sb230132) [inline tsl/test/sql/compression_update_delete.sql:986]: Please also add testcase for UPDATE.

File: tsl/src/compression/compression.c (hunk 1 above)
Comment (antekresic) [reply tsl/src/compression/compression.c:2505]: I don't think its necessary, we do this will all other scan type by changing the estate snapshot. They are not reverted back once we revert the estate snapshot.

File: tsl/test/sql/compression_update_delete.sql (hunk 2 above)
Comment (antekresic) [reply tsl/test/sql/compression_update_delete.sql:986]: Is there a particular reason why we should test UPDATE as well? I don't want to add another testcase just for the sake of adding it. This codepath is identical for both commands.

File: tsl/src/compression/compression.c (hunk 1 above)
Comment (antekresic) [reply tsl/src/compression/compression.c:2505]: Isolation tests with various isolation level combinations will be added in PR #5675 

Verified those tests against this PR produced no issues.
