### PR TITLE
Concurrent CAgg refresh improvements

### LINKED ISSUE #8372: [Bug]: Concurrent cagg refrshes in 2.21 not working
### What type of bug is this?

Unexpected error

### What subsystems and features are affected?

Continuous aggregate

### What happened?

I'm trying out the new concurrent cagg refrshes in 2.21: https://github.com/timescale/timescaledb/pull/8187
However, if a refresh is running:
`call refresh_continuous_aggregate('caggs.aws_sum_hour_base_test','2020-01-01 00:10:00', '2021-01-01 00:00:00')`
And I attempt to run another concurrently;
`call refresh_continuous_aggregate('caggs.aws_sum_hour_base_test','1993-01-01 00:10:00', '1994-01-01 00:00:00')`
I always get:
` NOTICE:  continuous aggregate "aws_sum_hour_base_test" is already up-to-date`
Definitely different ranges (and never refreshed). As soon as the first finishes I can run the second one.
I created the cagg WITH NO DATA.

### TimescaleDB version affected

2.21

### PostgreSQL version used

17.5

### What operating system did you use?

Ubuntu 22.04 LTS

### What installation method did you use?

Deb/Apt

### What platform did you run on?

On prem/Self-hosted

### Relevant log output and stack trace

```bash

```

### How can we reproduce the bug?

```bash
Just create a CAgg WITH NO DATA and attempt to run concurrent refreshes with different time ranges.
```

### PR DESCRIPTION
**Pull request by fabriziomello**
In #8117 we allowed concurrent CAgg refreshes by relaxing the strong lock when processing the invalidation by locking those rows and skipping the lock when the lock was already taken. The problem was when we had only one invalidation log to either expand or contract that the first session take the lock and the second skip the lock and return to the user that the CAgg is up-to-date and this is wrong.

So in order to improve and fix this wrong behavior we've splitted the second transaction (data materialization) into two transactions:
1. process the cagg invalidation logs (expand/contract) and insert the ranges to be materialized into a new metadata table named `_timescaledb_catalog.continuous_aggs_materialization_ranges` to process the materialization in the next transaction
2. process the materialization by reading ranges using FOR UPDATE SKIP LOCK from the new metadata table, execute the materialization and at the end remove the row from the new metadata table.

This new approach is like a producer/consumer pattern where the first transaction produce items in the queue to be consumed and processed by the next transaction.

Closes #8372 #8490

Disable-check: commit-count

### CODE REVIEW

File: sql/pre_install/tables.sql [hunk 1]
```diff
@@ -442,6 +442,18 @@ SELECT pg_catalog.pg_extension_config_dump('_timescaledb_catalog.continuous_aggs
 
 CREATE INDEX continuous_aggs_materialization_invalidation_log_idx ON _timescaledb_catalog.continuous_aggs_materialization_invalidation_log (materialization_id, lowest_modified_value ASC);
 
+-- cagg materialization queue
+CREATE TABLE _timescaledb_catalog.continuous_aggs_materialization_queue (
```
Comment (erimatnor) [inline sql/pre_install/tables.sql]: Could we use another name for this table? A queue is usually FIFO or LIFO, but this is more a "work-to-be-done" list which can be processed in parallel and in no particular order, AFAICT.

File: sql/updates/reverse-dev.sql [hunk 2]
```diff
@@ -226,3 +226,16 @@ DROP FUNCTION IF EXISTS _timescaledb_functions.temp_index_keycolumns(oid);
 
 GRANT SELECT ON TABLE _timescaledb_catalog.chunk_index TO PUBLIC;
 
+DO
+$$
+BEGIN
+  IF EXISTS (SELECT FROM _timescaledb_catalog.continuous_aggs_materialization_queue LIMIT 1) THEN
+    RAISE EXCEPTION 'Cannot downgrade because there are pending CAgg refreshes. Please refresh the caggs before downgrade.';
```
Comment (erimatnor) [inline sql/updates/reverse-dev.sql]: Recommend sticking to standard error formatting: message starts non-capitalized and should be relative short. You could add a detail message or hint as well.
```suggestion
    RAISE EXCEPTION 'cannot downgrade because there are pending CAgg refreshes" USING HINT  'Please refresh the caggs before downgrade.';
```

Maybe you want to add ERRCODE as well?

File: tsl/src/continuous_aggs/refresh.c [hunk 3]
```diff
@@ -662,19 +659,21 @@ process_cagg_invalidations_and_refresh(const ContinuousAgg *cagg,
...
-	 * same continuous aggregate when they don't have overlapping refresh
-	 * windows.
+	 * against concurrent invalidation log processing.
+	 *
+	 * It will produce rows in the `continuous_aggs_materialization_queue` table
+	 * to be materialized later either serially or in parallel for non-overlap
+	 * refresh ranges.
 	 */
-	LockRelationOid(hyper_relid, RowExclusiveLock);
+	LockRelationOid(hyper_relid, ExclusiveLock);
```
Comment (erimatnor) [inline tsl/src/continuous_aggs/refresh.c:700]: It would be good to expand the comment to include a note about the lock level, which is changing. I assume you changed this to ExclusiveLock to ensure that only one process generates the "queue" entries. What happens with concurrent processes that hang here?

File: tsl/test/isolation/expected/cagg_concurrent_refresh.out [hunk 4]
```diff
@@ -1,4 +1,4 @@
-Parsed test spec with 11 sessions
+Parsed test spec with 12 sessions
```
Comment (erimatnor) [inline tsl/test/isolation/expected/cagg_concurrent_refresh.out:1]: It would be good to see concurrency tests with different isolation levels, e.g., REPEATABLE READ. I am wondering what happens if one process generates the "queue" entries while others that should read them are running concurrently in REPEATABLE READ. Will they see the entries with ranges they should refresh?

File: sql/updates/reverse-dev.sql (hunk 2 above)
Comment (mkindahl) [reply sql/updates/reverse-dev.sql]: Second that. If you do not provide an error code, it will automatically be an internal error, which is kind of odd (and will also trigger some of our internal CI checks).

File: src/ts_catalog/continuous_aggs_watermark.c [hunk 5]
```diff
@@ -243,6 +243,21 @@ cagg_watermark_update_scan_internal(TupleInfo *ti, void *data)
...
+
+	if (ti->lockresult != TM_Ok)
+	{
+		elog(ERROR,
+			 "unable to lock watermark tuple for cagg %d (lock result %d)",
+			 watermark_update->ht_relid,
+			 ti->lockresult);
+
+		pg_unreachable();
+	}
```
Comment (mkindahl) [inline src/ts_catalog/continuous_aggs_watermark.c]: Since this should not typically happen, `Ensure` is a better alternative.

File: tsl/src/continuous_aggs/invalidation.c [hunk 6]
```diff
@@ -287,6 +294,40 @@ continuous_agg_invalidate_mat_ht(const Hypertable *raw_ht, const Hypertable *mat
 	invalidation_cagg_log_add_entry(mat_ht->fd.id, start, end);
 }
 
+static HeapTuple
+create_materialization_queue_tup(const TupleDesc tupdesc, int32 cagg_hyper_id, int64 start,
+								 int64 end)
```
Comment (mkindahl) [inline tsl/src/continuous_aggs/invalidation.c]: Nit: You're not changing `tupdesc`, so `const` seems reasonable, but you don't change `start` or `end` either, so it is inconsistent. Since `heap_form_tuple` does not accept a `const` `TupleDesc` removing the `const` seems like the prudent option. This is a just a style issue: feel free to ignore.
```suggestion
create_materialization_queue_tup(TupleDesc tupdesc, int32 cagg_hyper_id, int64 start,
								 int64 end)
```

File: tsl/src/continuous_aggs/materialize.c [hunk 7]
```diff
@@ -615,10 +700,36 @@ create_materialization_plan_args(MaterializationContext *context, Materializatio
 {
 	*values = (Datum *) palloc(nargs * sizeof(Datum));
 	*nulls = (char *) palloc(nargs * sizeof(char));
-	(*values)[0] = context->materialization_range.start;
-	(*values)[1] = context->materialization_range.end;
-	(*nulls)[0] = false;
-	(*nulls)[1] = false;
+
```
Comment (mkindahl) [inline tsl/src/continuous_aggs/materialize.c]: Nit: I usually put the "malloc" and "free" at the same level since this is easier to check and less prone to mistakes. It also avoids this "pointer to pointer" convention, which is hard to read and easy to make mistakes with. You have a corresponding free in the calling function, so this is not a problem with this code, but not sure about future changes.

**Review by mkindahl — COMMENTED** [review]
Hmmm... since you just defer the locking to rows in a new metadata table, I am wondering if you're just pushing the problem to a different location. Is this a viable scenario?

1. Process the invalidation log and add ranges to the queue
2. T1 starts to process one range [l,u], hence locks this tuple in the queue table
3. T2 comes in and tries to process [l', u'] where l' > l and u' < u. Since it skips locked tuples, it will that there is nothing to update.
4. T2 tries to read data under the assumption that the cagg is up to date.
5. It is not, so it shows incorrect data.
6. Some time later, T1 finishes processing.

If the above scenario is not a problem, can you add a test to check it? AFAICT, the changes to the isolation test does not cover this case.

File: sql/pre_install/tables.sql (hunk 1 above)
Comment (fabriziomello) [reply sql/pre_install/tables.sql]: Actually this is processed in a FIFO way for a given cagg in a given range

File: src/ts_catalog/continuous_aggs_watermark.c (hunk 5 above)
Comment (fabriziomello) [reply src/ts_catalog/continuous_aggs_watermark.c]: Fixed

File: tsl/src/continuous_aggs/refresh.c (hunk 3 above)
Comment (fabriziomello) [reply tsl/src/continuous_aggs/refresh.c:700]: Removed this lock from here because the code now is "concurrent-aware". We block the rows when processing the materialization invalidation rows and rescan in case of concurrent modifications to make sure we'll aways see the updated rows. So this lock is useless.

File: tsl/test/isolation/expected/cagg_concurrent_refresh.out (hunk 4 above)
Comment (fabriziomello) [reply tsl/test/isolation/expected/cagg_concurrent_refresh.out:1]: Let's add such kind of isolation test after the release. I think we're good to merge this PR as is.

File: sql/pre_install/tables.sql (hunk 1 above)
Comment (erimatnor) [reply sql/pre_install/tables.sql]: Hmm, then keep the name if you prefer. I had the impression that, for a given cagg, there are N processes that concurrently each grab a range (entry)  and the order they get processed are more based which process is first. I guess they aren't blocking on each other because then it is not parallel?

File: tsl/src/continuous_aggs/invalidation.c (hunk 6 above)
Comment (fabriziomello) [reply tsl/src/continuous_aggs/invalidation.c]: Fixed

File: tsl/src/continuous_aggs/materialize.c (hunk 7 above)
Comment (fabriziomello) [reply tsl/src/continuous_aggs/materialize.c]: Make sense, moved the "malloc" to the same level of corresponding "free".

File: sql/updates/reverse-dev.sql (hunk 2 above)
Comment (fabriziomello) [reply sql/updates/reverse-dev.sql]: This is supposed to never happen but I'll improve the message. I think I'll detail the operation that should be executed before downgrade if for some reason exists orphan records in that table.

File: tsl/src/continuous_aggs/refresh.c (hunk 3 above)
Comment (fabriziomello) [reply tsl/src/continuous_aggs/refresh.c:700]: Decided to keep this strong log and add a note that this transaction is very short and the expensive one is the materialization phase that is the next transaction.

File: sql/updates/reverse-dev.sql (hunk 2 above)
Comment (fabriziomello) [reply sql/updates/reverse-dev.sql]: Improved it.

File: sql/pre_install/tables.sql (hunk 1 above)
Comment (fabriziomello) [reply sql/pre_install/tables.sql]: Renamed to `continuous_aggs_materialization_ranges`
