### PR TITLE
Fix UPSERT on hypertables with columns with defaults

### LINKED ISSUE #3036: segmentation fault upon upgrade to 2.1.0
**Relevant system information:**
 - OS: Ubuntu 20.10
 - PostgreSQL version: 11
 - TimescaleDB version: 2.1.0
 - Installation method: Docker, apt install and built from source

**Describe the bug**
Upon upgrade to version 2.1.0, we now get a segmentation fault error in one of our queries.

We upgraded from 1.7.4.

Error happens when I run this query:

```
INSERT INTO rollup_1d_node_metric(time, cluster_id, node_id, cpu_cost, total_cost, memory_bytes,
                                  memory_used_percent, cpu_cores, cpu_used_percent, disk_costs, discount)
SELECT time_bucket('1 day', m.end_time),
       cluster_id,
       node_id,
       sum(cpu_cost),
       sum(total_cost),
       avg(memory_bytes),
       avg(memory_used_percent),
       avg(cpu_cores),
       avg(cpu_used_percent),
       sum(disk_costs),
       avg(discount)
FROM node_metric mm
         INNER JOIN metric m ON mm.metric_id = m.id
WHERE mm.end_time BETWEEN time_bucket('1 day', '2019-07-27 10:03:47.177372'::timestamptz) AND CURRENT_TIMESTAMP
  AND m.end_time BETWEEN time_bucket('1 day', '2019-07-27 10:03:47.177372'::timestamptz) AND CURRENT_TIMESTAMP
GROUP BY 1, 2, 3
ON CONFLICT (time, cluster_id, node_id)
    DO UPDATE
    SET cpu_cost            = excluded.cpu_cost,
        total_cost          = excluded.total_cost,
        memory_bytes        = excluded.memory_bytes,
        memory_used_percent = excluded.memory_used_percent,
        cpu_cores           = excluded.cpu_cores,
        cpu_used_percent    = excluded.cpu_used_percent,
        disk_costs    	    = excluded.disk_costs,
        discount    	    = excluded.discount;
```

Stack trace:
```
elijah@elijah-ThinkPad-T480:~/Programs/timescaledb-2.1.0/build$ sudo coredumpctl gdb
           PID: 20295 (postgres)
           UID: 124 (postgres)
           GID: 131 (postgres)
        Signal: 11 (SEGV)
     Timestamp: Thu 2021-03-18 15:22:06 -04 (35s ago)
  Command Line: postgres: 11/main: elijah replex 127.0.0.1(48846) INSERT
    Executable: /usr/lib/postgresql/11/bin/postgres
 Control Group: /system.slice/system-postgresql.slice/postgresql@11-main.service
          Unit: postgresql@11-main.service
         Slice: system-postgresql.slice
       Boot ID: 685e0b94f39444b5895002698dd4c99a
    Machine ID: f7db69a1e32e431eb89aa481c8a36d31
      Hostname: elijah-ThinkPad-T480
       Storage: /var/lib/systemd/coredump/core.postgres.124.685e0b94f39444b5895002698dd4c99a.20295.1616095326000000.zst
       Message: Process 20295 (postgres) of user 124 dumped core.
                
                Stack trace of thread 20295:
                #0  0x00007fe57d7986e8 ts_chunk_insert_state_create (timescaledb-2.1.0.so + 0x306e8)
                #1  0x00007fe57d79596f ts_chunk_dispatch_get_chunk_insert_state (timescaledb-2.1.0.so + 0x2d96f)
                #2  0x00007fe57d795d1e chunk_dispatch_exec (timescaledb-2.1.0.so + 0x2dd1e)
                #3  0x00005655436b619f ExecProcNode (postgres + 0x2b419f)
                #4  0x000056554369250c ExecProcNode (postgres + 0x29050c)
                #5  0x00005655437e4e27 ProcessQuery (postgres + 0x3e2e27)
                #6  0x00005655437e5130 PortalRunMulti (postgres + 0x3e3130)
                #7  0x00005655437e5c4e PortalRun (postgres + 0x3e3c4e)
                #8  0x00005655437e30c6 exec_execute_message (postgres + 0x3e10c6)
                #9  0x0000565543771bee BackendRun (postgres + 0x36fbee)
                #10 0x0000565543772a88 PostmasterMain (postgres + 0x370a88)
                #11 0x000056554350ce84 main (postgres + 0x10ae84)
                #12 0x00007fe782669cb2 __libc_start_main (libc.so.6 + 0x28cb2)
                #13 0x000056554350cf2e _start (postgres + 0x10af2e)

GNU gdb (Ubuntu 9.2-0ubuntu2) 9.2
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/lib/postgresql/11/bin/postgres...
Reading symbols from /usr/lib/debug/.build-id/0d/08baadc301560a5ca98f1f69aa35464511f4ec.debug...
[New LWP 20295]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `postgres: 11/main: elijah replex 127.0.0.1(48846) INSERT                      '.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007fe57d7986e8 in ts_chunk_insert_state_create () from /usr/lib/postgresql/11/lib/timescaledb-2.1.0.so
(gdb) bt
#0  0x00007fe57d7986e8 in ts_chunk_insert_state_create () from /usr/lib/postgresql/11/lib/timescaledb-2.1.0.so
#1  0x00007fe57d79596f in ts_chunk_dispatch_get_chunk_insert_state () from /usr/lib/postgresql/11/lib/timescaledb-2.1.0.so
#2  0x00007fe57d795d1e in chunk_dispatch_exec () from /usr/lib/postgresql/11/lib/timescaledb-2.1.0.so
#3  0x00005655436b619f in ExecProcNode (node=0x56554422e088) at ./build/../src/include/executor/executor.h:248
#4  ExecModifyTable (pstate=0x56554422d700) at ./build/../src/backend/executor/nodeModifyTable.c:2025
#5  0x000056554369250c in ExecProcNode (node=0x56554422d320) at ./build/../src/include/executor/executor.h:248
#6  ExecutePlan (execute_once=<optimized out>, dest=0x565543b75480 <donothingDR>, direction=<optimized out>, numberTuples=0, 
    sendTuples=<optimized out>, operation=CMD_INSERT, use_parallel_mode=<optimized out>, planstate=0x56554422d320, 
    estate=0x56554422cb20) at ./build/../src/backend/executor/execMain.c:1712
#7  standard_ExecutorRun (queryDesc=0x5655441ecce0, direction=<optimized out>, count=0, execute_once=<optimized out>)
    at ./build/../src/backend/executor/execMain.c:353
#8  0x00005655437e4e27 in ProcessQuery (plan=0x565544274958, 
    sourceText=0x56554420e1e8 "INSERT INTO rollup_1d_node_metric(time, cluster_id, node_id, cpu_cost, total_cost, memory_bytes,\n", ' ' <repeats 34 times>, "memory_used_percent, cpu_cores, cpu_used_percent, disk_costs, discoun"..., params=0x0, queryEnv=0x0, 
    dest=<optimized out>, completionTag=0x7ffec8874bf0 "") at ./build/../src/backend/tcop/pquery.c:161
#9  0x00005655437e5130 in PortalRunMulti (portal=portal@entry=0x565544195530, isTopLevel=isTopLevel@entry=true, 
    setHoldSnapshot=setHoldSnapshot@entry=false, dest=0x565543b75480 <donothingDR>, dest@entry=0x5655440f68e0, 
    altdest=0x565543b75480 <donothingDR>, altdest@entry=0x5655440f68e0, completionTag=completionTag@entry=0x7ffec8874bf0 "")
    at ./build/../src/backend/tcop/pquery.c:1286
#10 0x00005655437e5c4e in PortalRun (portal=0x565544195530, count=9223372036854775807, isTopLevel=<optimized out>, 
    run_once=<optimized out>, dest=0x5655440f68e0, altdest=0x5655440f68e0, completionTag=0x7ffec8874bf0 "")
    at ./build/../src/backend/tcop/pquery.c:799
#11 0x00005655437e30c6 in PostgresMain (argc=<optimized out>, argv=argv@entry=0x565544149328, dbname=<optimized out>, 
    username=<optimized out>) at ./build/../src/backend/tcop/postgres.c:2036
#12 0x0000565543771bee in BackendRun (port=0x565544146de0) at ./build/../src/backend/postmaster/postmaster.c:4409
#13 BackendStartup (port=0x565544146de0) at ./build/../src/backend/postmaster/postmaster.c:4073
#14 ServerLoop () at ./build/../src/backend/postmaster/postmaster.c:1728
#15 0x0000565543772a88 in PostmasterMain (argc=5, argv=<optimized out>) at ./build/../src/backend/postmaster/postmaster.c:1401
#16 0x000056554350ce84 in main (argc=5, argv=0x5655440f0fa0) at ./build/../src/backend/main/main.c:228
(gdb) 
```

### LINKED ISSUE #3037: chunk_map null in call to translate_clause
**Relevant system information:**
- docker image 2.1.0-pg12 running on fedora host
- postgres (PostgreSQL) 12.6
- TimescaleDB version 2.1.0

**Describe the bug**
When inserting a row into tsdb, it segfaults. I recompiled with debugging symbols and found that translate_clause is called with chunk_map NULL, which causes a segfault here:
```
156             clause = castNode(List,
157                 map_variable_attnos_compat((Node *) clause,
158                     INNER_VAR,
159                     0,
160                     chunk_map->attrMap,
```

setup_on_conflict_state is also called with a NULL chunk_map. 

chunk_map appears to be set in setup_on_conflict_state by calling convert_tuples_by_name, which looks like can return NULL if no map is needed. 

**Backtrace**
```
#0  0x00007f9406ba61ac in translate_clause (inclause=0x7f94069ee420, chunk_map=0x0, varno=1, hyper_rel=0x7f9406c977f0, chunk_rel=0x7f9406976278) at /build/timescaledb/src/chunk_insert_state.c:156
#1  0x00007f9406ba6708 in setup_on_conflict_state (state=0x7f940695f480, dispatch=0x7f9406a3ecf8, chunk_map=0x0) at /build/timescaledb/src/chunk_insert_state.c:395
#2  0x00007f9406ba6a91 in adjust_projections (cis=0x7f940695f480, dispatch=0x7f9406a3ecf8, rowtype=496969) at /build/timescaledb/src/chunk_insert_state.c:521
#3  0x00007f9406ba6de1 in ts_chunk_insert_state_create (chunk=0x7f9406a08340, dispatch=0x7f9406a3ecf8) at /build/timescaledb/src/chunk_insert_state.c:613
#4  0x00007f9406ba2ea4 in ts_chunk_dispatch_get_chunk_insert_state (dispatch=0x7f9406a3ecf8, point=0x7f9406a07ca0, on_chunk_changed=0x7f9406ba336a <on_chunk_insert_state_changed>, data=0x7f9406a34d28) at /build/timescaledb/src/chunk_dispatch.c:133
#5  0x00007f9406ba34fa in chunk_dispatch_exec (node=0x7f9406a34d28) at /build/timescaledb/src/chunk_dispatch_state.c:133
#6  0x00005651a5d6e060 in ExecModifyTable ()
```

**To Reproduce**
I haven't tried reproducing it on a clean DB, but here are the query and values we are trying to run:
```
query "INSERT INTO campaign_dates \n
        (cd_name,cd_date,cd_dfp_revenue,cd_dfp_impressions,cd_dfp_georev,cd_dfp_devrev,cd_ga_pageviews,cd_ga_sessions,cd_ga_instant_pageviews,cd_ga_instant_sessions,cd_ga_geo,cd_fb_est_instant_revenue,cd_credits) 
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13)\n        
ON CONFLICT  (cd_date, cd_name) 
DO UPDATE SET\n        
(cd_dfp_revenue,cd_dfp_impressions,cd_dfp_georev,cd_dfp_devrev,cd_ga_pageviews,cd_ga_sessions,cd_ga_instant_pageviews,cd_ga_instant_sessions,cd_ga_geo,cd_fb_est_instant_revenue,cd_fb_campaign_id,cd_fb_impressions,cd_fb_account_id,cd_fb_budget,cd_fb_start_time,cd_fb_spend,cd_fb_is_instant,cd_credits) = 
row(EXCLUDED.cd_dfp_revenue,EXCLUDED.cd_dfp_impressions,EXCLUDED.cd_dfp_georev,EXCLUDED.cd_dfp_devrev,EXCLUDED.cd_ga_pageviews,EXCLUDED.cd_ga_sessions,EXCLUDED.cd_ga_instant_pageviews,EXCLUDED.cd_ga_instant_sessions,EXCLUDED.cd_ga_geo,EXCLUDED.cd_fb_est_instant_revenue,EXCLUDED.cd_fb_campaign_id,EXCLUDED.cd_fb_impressions,EXCLUDED.cd_fb_account_id,EXCLUDED.cd_fb_budget,EXCLUDED.cd_fb_start_time,EXCLUDED.cd_fb_spend,EXCLUDED.cd_fb_is_instant,EXCLUDED.cd_credits)\n        \n    "
values [
    "campaign",
    "2021-03-11",
    0.006983,
    10,
    "[{\"country\":\"Australia\",\"revenue\":0.00273},{\"country\":\"United States\",\"revenue\":0.004253}]",
    "[{\"device\":\"Desktop\",\"revenue\":0.006853},{\"device\":\"Smartphone\",\"revenue\":0.00013}]",
    1,
    1,
    0,
    0,
    "[{\"country\":\"Australia\",\"sessions\":1,\"pageviews\":1}]",
    0,
    "[]"
]
```

Let me know if the schema information would be helpful, or if there is any other information that'd be useful. Thanks.

### PR DESCRIPTION
**Pull request by svenklemm**
When a column with a DEFAULT was added to a hypertable after
hypertable creation this column would have atthasmissing true
for the hypertable itself but not for chunks created after.
This lead to the attribute mapping from the hypertable to
the chunk being non-NULL but the chunk -> hypertable map being
NULL leading to a segfault because the code assumed both maps
would either be NULL or non-NULL.

Fixes #3036 
Fixes #3037

### CODE REVIEW

**Review by mkindahl — APPROVED** [review]
LGTM

File: src/chunk_insert_state.c [hunk 1]
```diff
@@ -385,7 +388,7 @@ setup_on_conflict_state(ChunkInsertState *state, ChunkDispatch *dispatch,
 
 		if (NULL == chunk_map)
 			chunk_map = convert_tuples_by_name(RelationGetDescr(chunk_rel),
-											   RelationGetDescr(first_rel)
+											   RelationGetDescr(hyper_rel)
```
Comment (gayyappan) [inline src/chunk_insert_state.c:391]: The fix is not clear to me: we create a chunk map here if one is not available.  Wouldn't we still run into this if we have more than 2 columns (the test case has only 1 additional column) : i.e. we have a chunk map but some of the columns are missing in the mapping?

Comment (svenklemm) [reply src/chunk_insert_state.c:391]: the fix is on line 156 this is just a cosmetic change

Comment (svenklemm) [reply src/chunk_insert_state.c:391]: the chunk_map passed as argument will only be non-NULL if we have RETURNING clause otherwise it will always be NULL cause caller didn't bother building the map

Comment (svenklemm) [reply src/chunk_insert_state.c:391]: the code would certainly benefit from some more refactoring/cleanup but i wanted to get the bugfix out

Comment (gayyappan) [reply src/chunk_insert_state.c:391]: ok, I see that the map is null if no conversion is required. Yes, confusing to see calls to translate when it is not applicable.

**Review by gayyappan — APPROVED** [review]
