### PR TITLE
Properly handle `max_retries` option

### LINKED ISSUE #3035: Failing Jobs Run Forever, Ignoring max_retries
**Relevant system information:**
 - TimescaleDB version (output of `\dx` in `psql`): 2.1.0

**Describe the bug**
While the documentation describes being able to set a `max_retries` value for a background worker, the [scheduler code on failure
](https://github.com/timescale/timescaledb/blob/954c775275123d22e981261ad1043a287b6b432c/src/bgw/job_stat.c#L198-L278) doesn't seem to actually handle this value, resulting in failed jobs running forever. It does use the retry_interval to reschedule, but it does not ever halt job execution after any number of consecutive failures.

**To Reproduce**
```sql
--create working procedure
CREATE OR REPLACE PROCEDURE failure(job_id int, config jsonb) LANGUAGE PLPGSQL AS
$$
BEGIN
  RAISE NOTICE 'Executing action % with config %', job_id, config;
END
$$;


--add it as a job
SELECT add_job('failure','1h');


--alter its schedule so it runs once a second, with a max_retry of 4, and start it now. Alter job id as necessary
SELECT alter_job(1000, max_retries => 4, schedule_interval => interval '1 second', next_start => now());

--see it running
select * from timescaledb_information.job_stats;

--break the function - this has an unhandled select, which errors out when the procedure is called.
CREATE OR REPLACE PROCEDURE failure(job_id int, config jsonb) LANGUAGE PLPGSQL AS
$$
BEGIN
  RAISE NOTICE 'Executing action % with config %', job_id, config;
  select * from test;
END
$$;

--see it is now failing, and keeps running forever
select * from timescaledb_information.job_stats;
```

**Expected behavior**
I would expect that this job would be disabled after reaching max_retries

**Actual behavior**
The job runs forever.

### PR DESCRIPTION
**Pull request by fabriziomello**
Surprisly we're not taking care of `max_retries` option leading us to
failed jobs running forever.

Fixed it by properly handle the `max_retries` option in our scheduler.

Fixes #3035

### CODE REVIEW

File: src/bgw/job_stat.c [hunk 1]
```diff
@@ -205,6 +205,18 @@ calculate_next_start_on_failure(TimestampTz finish_time, int consecutive_failure
 	float8 multiplier = (consecutive_failures > MAX_FAILURES_MULTIPLIER ? MAX_FAILURES_MULTIPLIER :
 																		  consecutive_failures);
 	MemoryContext oldctx;
+
+	/* stop to execute failing jobs after reached the "max_retries" option */
+	if (job->fd.max_retries > 0 && consecutive_failures >= job->fd.max_retries)
+	{
+		elog(LOG,
+			 "%s: max_retries reached %d, consecutive failures %d",
```
Comment (gayyappan) [inline src/bgw/job_stat.c:213]: Users need to take action on this, if needed. So we should add more info about the job  to the message.
```suggestion
			 "job %d not executed as max_retries reached %d, consecutive failures %d",
```

Comment (fabriziomello) [reply src/bgw/job_stat.c]: Sure, just forgot to improve the log message. Fixed, thanks!

File: src/bgw/job_stat.c [hunk 2]
```diff
@@ -205,6 +205,18 @@ calculate_next_start_on_failure(TimestampTz finish_time, int consecutive_failure
...
+
+	/* stop to execute failing jobs after reached the "max_retries" option */
+	if (job->fd.max_retries > 0 && consecutive_failures >= job->fd.max_retries)
+	{
+		elog(LOG,
+			 "job %d not executed as max_retries reached %d, consecutive failures %d",
+			 job->fd.id,
+			 job->fd.max_retries,
+			 consecutive_failures);
+		return res;
```
Comment (mkindahl) [inline src/bgw/job_stat.c:217]: I would actually suggest to make this (at least) a warning and use `ereport`.

I think it should be a warning since it is something that potentially is a problem and users will look for warnings and errors in the log to figure out "what is wrong". If you look at [Message Severity Levels](https://www.postgresql.org/docs/14/runtime-config-logging.html#RUNTIME-CONFIG-SEVERITY-LEVELS), `LOG` level "Reports information of interest to administrators, e.g., checkpoint activity", while `WARNING` level "Provides warnings of likely problems, e.g., COMMIT outside a transaction block." We could actually consider `ERROR` as well since it says "Reports an error that caused the current command to abort."

I think that you should use `ereport` because some of that information belongs in the error details and is not necessarily interesting to log. For example, if you look in `acl.c` it has an `ereport` that report the failure as a brief message and provide more details in the `errdetail`. So what job number failed makes sense to have in the message, but the number of retries and the maximum belong in the `errdetail`.

```
			ereport(ERROR,
					(errcode(ERRCODE_NAME_TOO_LONG),
					 errmsg("identifier too long"),
					 errdetail("Identifier must be less than %d characters.",
							   NAMEDATALEN)));
```

**Review by akuzm — APPROVED** [review]

File: src/bgw/job_stat.c (hunk 2 above)
Comment (fabriziomello) [reply src/bgw/job_stat.c:217]: Makes sense. Will change to use `ereport`. Now I discovered a bug in the logic leading to log forever the failing job

**Review by mkindahl — DISMISSED** [review]
LGTM

File: src/bgw/job.c [hunk 3]
```diff
@@ -567,6 +567,146 @@ ts_bgw_job_delete_by_id(int32 job_id)
...
+	BgwJobStat *job_stat;
+
+	job_stat = ts_bgw_job_stat_find(job->fd.id);
+
+	/* stop to execute failing jobs after reached the "max_retries" option */
+	if (job->fd.max_retries > 0 && job_stat->fd.consecutive_failures >= job->fd.max_retries)
+	{
+		ereport(WARNING,
+				(errcode(ERRCODE_WARNING),
+				 errmsg("job %d reached max_retries after consecutive failures", job->fd.id),
```
[the remark this answers is not in the document]
Comment (fabriziomello) [reply src/bgw/job.c]: Fixed!

**Review by svenklemm — APPROVED** [review]

File: tsl/test/expected/bgw_db_scheduler.out [hunk 4]
```diff
@@ -560,9 +560,10 @@ SELECT * FROM sorted_bgw_log;
       0 |    800000 | DB Scheduler     | [TESTING] Wait until 984375, started at 800000
       1 |    984375 | DB Scheduler     | [TESTING] Registered new background worker
       2 |    984375 | DB Scheduler     | [TESTING] Wait until 1325000, started at 984375
-      1 |    984375 | test_job_2       | job 1001 threw an error
-      2 |    984375 | test_job_2       | Error job 2
-(24 rows)
+      1 |    984375 | test_job_2       | job 1001 reached max_retries after 5 consecutive failures
+      2 |    984375 | test_job_2       | job 1001 threw an error
+      3 |    984375 | test_job_2       | Error job 2
+(25 rows)
```
Comment (gayyappan) [inline tsl/test/expected/bgw_db_scheduler.out:566]: Could you add  a test that shows that we can alter the job config (after max_retries is reached) and run the job again?  (please also add a comment about the use case for the test in the .sql file when you add the test). Is it possible with mock bgw framework?

Comment (fabriziomello) [reply tsl/test/expected/bgw_db_scheduler.out:566]: Added some more tests to address it.

File: src/bgw/job.c [hunk 5]
```diff
@@ -567,6 +567,148 @@ ts_bgw_job_delete_by_id(int32 job_id)
 	return bgw_job_delete_scan(scankey, job_id);
 }
 
+/* This function only updates the fields modifiable with alter_job. */
+static ScanTupleResult
+bgw_job_tuple_update_by_id(TupleInfo *ti, void *const data)
```
Comment (mkindahl) [inline src/bgw/job.c:572]: These functions make sense to move to the Apache part of the code. Not sure why they were in the TSL part in the first place.

It seems you did not make any changes to the functions when moving them. Is that correct?

File: src/bgw/job.c [hunk 6]
```diff
@@ -567,6 +567,148 @@ ts_bgw_job_delete_by_id(int32 job_id)
...
+{
+	BgwJobStat *job_stat;
+
+	job_stat = ts_bgw_job_stat_find(job->fd.id);
+
+	/* stop to execute failing jobs after reached the "max_retries" option */
+	if (job->fd.max_retries > 0 && job_stat->fd.consecutive_failures >= job->fd.max_retries)
+	{
+		ereport(WARNING,
+				(errcode(ERRCODE_WARNING),
```
Comment (mkindahl) [inline src/bgw/job.c:695]: Why `ERRCODE_WARNING`? Shouldn't you use something like `ERRCODE_CONFIGURATION_LIMIT_EXCEEDED`?

File: src/bgw/job.c [hunk 7]
```diff
@@ -567,6 +567,148 @@ ts_bgw_job_delete_by_id(int32 job_id)
...
+				 errmsg("job %d reached max_retries after %d consecutive failures",
+						job->fd.id,
+						job_stat->fd.consecutive_failures),
```
Comment (mkindahl) [inline src/bgw/job.c:698]: I still think this is too much details for the error message.

Here is an example from the PostgreSQL source (`fd.c`):
```
				(errcode(ERRCODE_INSUFFICIENT_RESOURCES),
				 errmsg("insufficient file descriptors available to start server process"),
				 errdetail("System allows %d, we need at least %d.",
						   max_safe_fds + NUM_RESERVED_FDS,
						   FD_MINFREE + NUM_RESERVED_FDS)));
```

```suggestion
				 errmsg("job %d reached max_retries", job->fd.id),
```

File: src/bgw/job.c [hunk 8]
```diff
@@ -567,6 +567,148 @@ ts_bgw_job_delete_by_id(int32 job_id)
...
+				 errdetail("Job %d unscheduled as max_retries reached %d, consecutive failures %d",
+						   job->fd.id,
+						   job->fd.max_retries,
+						   job_stat->fd.consecutive_failures)));
```
Comment (mkindahl) [inline src/bgw/job.c:702]: Do you want to add a hint on how to enable the job again? Otherwise, it would be necessary for the user to start digging through manuals, which is just frustrating.

File: src/bgw/job.c (hunk 5 above)
Comment (fabriziomello) [reply src/bgw/job.c:572]: I did not make any changes, just moved the code around

File: tsl/src/bgw_policy/job.c [hunk 9]
```diff
@@ -661,3 +661,26 @@ job_execute(BgwJob *job)
 
 	return true;
 }
+
+/*
+ * Check configuration for a job type.
+ */
+void
+job_config_check(Name proc_schema, Name proc_name, Jsonb *config)
```
[the remark this answers is not in the document]
Comment (fabriziomello) [reply tsl/src/bgw_policy/job.c:669]: I moved because the job_api.c module include the job.h and to do what you proposed I should include job_api.h into job.c, so to me it seems weird (cyclic dependency).

File: src/bgw/job.c (hunk 6 above)
Comment (fabriziomello) [reply src/bgw/job.c:695]: Makes sense... fixed!

File: src/bgw/job.c (hunk 7 above)
Comment (fabriziomello) [reply src/bgw/job.c:698]: I changed it to include more details per @svenklemm suggestion

File: src/bgw/job.c (hunk 8 above)
Comment (fabriziomello) [reply src/bgw/job.c]: Added!

File: src/bgw/job.c (hunk 7 above)
Comment (mkindahl) [reply src/bgw/job.c:698]: I think the comment was more about grammar than that any specific information that should be there. Make a call on what you think is reasonable and go with it.

File: tsl/src/bgw_policy/job.c (hunk 9 above)
[the remark this answers is not in the document]
Comment (mkindahl) [reply tsl/src/bgw_policy/job.c:669]: Fair enough, but that suggests that something is wrong with the module structure. Nothing to fix in this pull request though.

**Review by mkindahl — APPROVED** [review]
