### PR TITLE
Fix extension drop handling

### LINKED ISSUE #73: Dropping schema after CREATE EXTENSION leads to bad state
```
CREATE EXTENSION IF NOT EXISTS timescaledb CASCADE;
NOTICE:  installing required extension "postgres_fdw"
CREATE EXTENSION
DROP SCHEMA public CASCADE;
NOTICE:  drop cascades to 2 other objects
DETAIL:  drop cascades to extension postgres_fdw
drop cascades to extension timescaledb
DROP SCHEMA
\d
ERROR:  could not open relation with OID 16439
```

### PR DESCRIPTION
**Pull request by cevian**
Previously, the extension could end up in a bad state if it
was dropped as part of a cascade. This PR fixes that by
checking explicitly for the presence of the proxy table
to make sure we are not in the middle of an extension
drop. Fixes #73.

### CODE REVIEW

File: src/extension.c [hunk 1]
```diff
@@ -56,20 +56,33 @@ enum ExtensionState
...
+	 * during a extension drop, the extension proxy table will be dropped.
+	 * This will automatically cause a relcache invalidation on the proxy
+	 * tables's OID.
+	 */
 	return relid == extension_proxy_oid;
 }
 
+
+static bool
+proxy_table_exists()
```
Comment (erimatnor) [inline src/extension.c]: Is this the best indicator we have of "being in the process of dropping the extension"? I am asking, because the `drop_transaction_id` check from before was at least explicit, rather than this check that depends on the implicit ordering of removal events and the presence of certain tables.

One reason I am asking is because we might decide in the future that we do not need this proxy table, then this check needs to be changed to something else. Another reason is that the ordering of events might not always be the same, although I agree that it is unlikely that the proxy table is removed after the extension. But, on the other hand, the internal semantics of how this happens might change and this check risks breaking.

Wouldn't it be better to just patch up the `drop_transaction_id` mechanism to also check for other DDL DROP commands that can cascade to dropping the extension? For example, we could check for DROP schema and check whether it is the extension's schema. This is a bit more code, but is at least explicit.

File: src/extension.c [hunk 2]
```diff
@@ -92,41 +105,14 @@ extension_event_trigger(PG_FUNCTION_ARGS)
 	if (!CALLED_AS_EVENT_TRIGGER(fcinfo))
 		elog(ERROR, "not fired by event trigger manager");
 
+	/* TODO: does this do anything useful? */
```
Comment (erimatnor) [inline src/extension.c]: In the process of changing this code, I think you also need to revisit whether the state machine that these checks implement still makes sense. 

Now we never set DROPPING state, but I don't see you removing this state either.

File: src/extension.c [hunk 3]
```diff
@@ -92,41 +105,14 @@ extension_event_trigger(PG_FUNCTION_ARGS)
...
-			drop_transaction_id = GetCurrentTransactionId();
-
-			/*
-			 * Notify other backends that the extension was dropped. We do
-			 * this via the relcache invalidation mechanism in Postgres by
-			 * issuing an invalidation on a proxy table. Other backends will
-			 * see an invalidation event on the proxy table and then knows
-			 * they need to move back to INITIAL state.
-			 */
-			CacheInvalidateRelcacheByRelid(extension_proxy_oid);
```
Comment (erimatnor) [inline src/extension.c]: How's this handled with your changes? Don't we need other backends to invalidate their extension state anymore? Did you test how dropping now works with multiple simultaneous backends?

File: src/extension.c (hunk 1 above)
Comment (cevian) [inline src/extension.c]: So from what I could tell, the postgres code is pretty good at making sure dependent objects are dropped before the objects they depend on. So, I think relying on this is pretty safe. So the flow, as I see it is: the proxy table is dropped (which causes a relcache invalidaton of the proxy table internally, more on that below). The relcache invalidation goes to all backends which will reset the extension. Now, as long as the extension cannot go back to CREATED while the drop is in process, we are safe. That's what the `proxy_table_exists()` check guards against.

Comment (cevian) [inline src/extension.c]: I think that's safer than trying to catch every ddl operation that can lead to that because we might always miss some.

File: src/extension.c (hunk 3 above)
Comment (cevian) [inline src/extension.c]: So it turns out that postgres adds an relcache invalidation message for the relid of any table it is dropping. The stacktrace is : 
```
* thread #1: tid = 0xd9b1e7, 0x000000010ae91eae postgres`RegisterRelcacheInvalidation(dbId=54515356, relId=54515644) + 14 at inval.c:498, queue = 'com.apple.main-thread', stop reason = breakpoint 2.1
  * frame #0: 0x000000010ae91eae postgres`RegisterRelcacheInvalidation(dbId=54515356, relId=54515644) + 14 at inval.c:498
    frame #1: 0x000000010ae91d51 postgres`CacheInvalidateHeapTuple(relation=0x000000010b372bf0, tuple=0x00007fff55346ac0, newtuple=0x0000000000000000) + 529 at inval.c:1174
    frame #2: 0x000000010a91efb9 postgres`heap_delete(relation=0x000000010b372bf0, tid=0x00007f8d128d9934, cid=106, crosscheck=0x0000000000000000, wait='\x01', hufd=0x00007fff55346b68) + 4073 at heapam.c:3345
    frame #3: 0x000000010a9201d6 postgres`simple_heap_delete(relation=0x000000010b372bf0, tid=0x00007f8d128d9934) + 70 at heapam.c:3378
    frame #4: 0x000000010a9c5e76 postgres`DeleteAttributeTuples(relid=54515755) + 182 at heap.c:1482
    frame #5: 0x000000010a9c6a0d postgres`heap_drop_with_catalog(relid=54515755) + 381 at heap.c:1848
    frame #6: 0x000000010a9c2d82 postgres`doDeletion(object=0x00007f8d14833b38, flags=0) + 242 at dependency.c:1155
    frame #7: 0x000000010a9c0773 postgres`deleteOneObject(object=0x00007f8d14833b38, depRel=0x00007fff55346e58, flags=0) + 163 at dependency.c:1057
    frame #8: 0x000000010a9c040b postgres`deleteObjectsInList(targetObjects=0x00007f8d1480d770, depRel=0x00007fff55346e58, flags=0) + 315 at dependency.c:246
    frame #9: 0x000000010a9c0575 postgres`performMultipleDeletions(objects=0x00007f8d1480d240, behavior=DROP_CASCADE, flags=0) + 261 at dependency.c:385
    frame #10: 0x000000010aa9daad postgres`RemoveObjects(stmt=0x00007f8d1405bf80) + 909 at dropcmds.c:134
    frame #11: 0x000000010ad11aad postgres`ExecDropStmt(stmt=0x00007f8d1405bf80, isTopLevel='\x01') + 205 at utility.c:1607
    frame #12: 0x000000010ad11243 postgres`ProcessUtilitySlow(parsetree=0x00007f8d1405bf80, queryString="drop schema public cascade;", context=PROCESS_UTILITY_TOPLEVEL, params=0x0000000000000000, dest=0x00007f8d1405c328, completionTag="") + 7107 at utility.c:1486
    frame #13: 0x000000010ad0eeba postgres`standard_ProcessUtility(parsetree=0x00007f8d1405bf80, queryString="drop schema public cascade;", context=PROCESS_UTILITY_TOPLEVEL, params=0x0000000000000000, dest=0x00007f8d1405c328, completionTag="") + 3114 at utility.c:819
    frame #14: 0x000000010b5a761e timescaledb.so`prev_ProcessUtility(parsetree=0x00007f8d1405bf80, queryString="drop schema public cascade;", context=PROCESS_UTILITY_TOPLEVEL, params=0x0000000000000000, dest=0x00007f8d1405c328, completionTag="") + 110 at process_utility.c:34
    frame #15: 0x000000010b5a7580 timescaledb.so`timescaledb_ProcessUtility(parsetree=0x00007f8d1405bf80, queryString="drop schema public cascade;", context=PROCESS_UTILITY_TOPLEVEL, params=0x0000000000000000, dest=0x00007f8d1405c328, completionTag="") + 496 at process_utility.c:90
    frame #16: 0x000000010ad0e25c postgres`ProcessUtility(parsetree=0x00007f8d1405bf80, queryString="drop schema public cascade;", context=PROCESS_UTILITY_TOPLEVEL, params=0x0000000000000000, dest=0x00007f8d1405c328, completionTag="") + 124 at utility.c:332
    frame #17: 0x000000010ad0dbf3 postgres`PortalRunUtility(portal=0x00007f8d1280c040, utilityStmt=0x00007f8d1405bf80, isTopLevel='\x01', setHoldSnapshot='\0', dest=0x00007f8d1405c328, completionTag="") + 371 at pquery.c:1193
    frame #18: 0x000000010ad0ce2f postgres`PortalRunMulti(portal=0x00007f8d1280c040, isTopLevel='\x01', setHoldSnapshot='\0', dest=0x00007f8d1405c328, altdest=0x00007f8d1405c328, completionTag="") + 527 at pquery.c:1342
    frame #19: 0x000000010ad0c46e postgres`PortalRun(portal=0x00007f8d1280c040, count=9223372036854775807, isTopLevel='\x01', dest=0x00007f8d1405c328, altdest=0x00007f8d1405c328, completionTag="") + 910 at pquery.c:815
    frame #20: 0x000000010ad07d4a postgres`exec_simple_query(query_string="drop schema public cascade;") + 1242 at postgres.c:1094
    frame #21: 0x000000010ad06f50 postgres`PostgresMain(argc=1, argv=0x00007f8d140045f0, dbname="single", username="postgres") + 2368 at postgres.c:4076
    frame #22: 0x000000010ac62b12 postgres`BackendRun(port=0x00007f8d138006c0) + 674 at postmaster.c:4285
    frame #23: 0x000000010ac61dcd postgres`BackendStartup(port=0x00007f8d138006c0) + 365 at postmaster.c:3959
    frame #24: 0x000000010ac60e25 postgres`ServerLoop + 597 at postmaster.c:1715
    frame #25: 0x000000010ac5e636 postgres`PostmasterMain(argc=15, argv=0x00007f8d11403800) + 5414 at postmaster.c:1323
    frame #26: 0x000000010ab8f11f postgres`main(argc=15, argv=0x00007f8d11403800) + 751 at main.c:228
    frame #27: 0x00007fff943af5ad libdyld.dylib`start + 1
    frame #28: 0x00007fff943af5ad libdyld.dylib`start + 1
```
The sql was: 
```
single=# select '_timescaledb_cache.cache_inval_extension'::regclass::oid;
   oid
----------
 54515644
(1 row)

Time: 0.534 ms
single=# drop schema public cascade;
```

In `CacheInvalidateHeapTuple` you can actually see that any modification to a pg_class tuple causes an invalidation event on the OID of the tuple (the relid of the corresponding table).

File: src/extension.c [hunk 4]
```diff
@@ -149,7 +135,13 @@ extension_is_loaded(void)
 	 */
 	id = get_extension_oid(EXTENSION_NAME, true);
 
-	if (OidIsValid(id))
+	/*
+	 * the proxy table check is necessary because during an extension drop the
```
Comment (cevian) [inline src/extension.c]: Yes that's what I meant. I'll fix the comment if we agree to this approach.

File: src/extension.c [hunk 5]
```diff
@@ -149,7 +135,13 @@ extension_is_loaded(void)
...
+	 * proxy table will be deleted before the extension itself. You don't want
+	 * to mark the extension as CREATED in this case
+	 */
+
+	if (OidIsValid(id) && proxy_table_exists())
```
Comment (erimatnor) [inline src/extension.c]: So, I vaguely recall that the reason for returning true while the extension was being dropped was that otherwise it would not clean up (invalidate caches) because in `inval_cache_callback()` there is an `extension_is_loaded()` check. Is this no longer the case? I mean, like I expressed above, this might work incidentally due to ordering of events, and the order of `extension_is_loaded()` checks in the code. I am worried that this will break as soon as we add another `extension_is_loaded()` check in the code or the order of events changes.

I guess part of the problem is that `extension_is_loaded()` both checks the state and sets the state, so the state might change between successive calls.

Comment (erimatnor) [inline src/extension.c]: I am all for simplifying this if we feel confident that it is doing the right thing. But please document the expected events that occur and their order. I agree that we can probably trust that the proxy table is dropped before the extension drop finishes, but we cannot know at which point the proxy table is removed after one issues, e.g., `DROP EXTENSION`. Before we had a state immediately following `DROP EXTENSION` and now we just know at some point after that and before the extension is fully removed the proxy table will be removed. In the meantime we still believe the extension is loaded. Does this matter? Again, I am not too keen on relying on these incidental (implicit) order of events, not least because it is hard to understand.

Comment (erimatnor) [inline src/extension.c]: Btw, I think the reason for returning `true` (or some intermediate state) was that the cache invalidation events need to work when dropping, since there is an `extension_is_loaded()` check in the cache invalidation function. Now, this might still happen to work (again incidentally) because the other proxy tables are dropped before the extension proxy table, or something like that. If we are moving to a boolean state machine and always returning false during extension drops (again you are only returning false after the proxy table is dropped which happens in a largely unknown point after drop starts) then we also need to make sure that cache invalidation works, and not only happens to work because tables happen to be removed in some order.

**Comment by cevian** [comment]
@erimatnor massive changes to the PR. Tried to simplify but this stuff is hard so its still complicated :(. Anyway I think this logic is correct now. Documented the ordering dependencies I think this relies on at the top of the file. Please take another look.

File: src/extension.c [hunk 6]
```diff
@@ -21,157 +21,171 @@ static Oid	extension_proxy_oid = InvalidOid;
...
+			 * invalidation event applies to all tables.
 			 */
-			CacheInvalidateRelcacheByRelid(extension_proxy_oid);
-		}
+			if (extension_proxy_oid == relid || !OidIsValid(relid))
+			{
+				extension_update_state();
+				if (EXTENSION_STATE_CREATED != extstate)
+				{
+					return true;/* note this state may be UNKNOWN but should
```
Comment (erimatnor) [inline src/extension.c]: Nit. Move comment above `return true`.

File: src/extension.c [hunk 7]
```diff
@@ -21,157 +21,171 @@ static Oid	extension_proxy_oid = InvalidOid;
...
-	if (!CALLED_AS_EVENT_TRIGGER(fcinfo))
-		elog(ERROR, "not fired by event trigger manager");
+	if (proxy_table_exists())
+	{
+		if (!extension_exists())
+			return EXTENSION_STATE_TRANSITIONING;
+		else
+			return EXTENSION_STATE_CREATED;
+	}
+	else
```
Comment (erimatnor) [inline src/extension.c]: Nit. This else statement is unnecessary. Just do a return...
