### PR TITLE
Fix logic for BGW rescheduling

### LINKED ISSUE #1462: Continuous Aggregates not running after altering refresh_interval
**Relevant system information:**
 - OS: official docker container(On mac)
 - PostgreSQL version: 11.4
 - TimescaleDB version 1.4.2
 - Installation method: Docker

**Describe the bug**
After altering the continuous aggregates view, like
`ALTER VIEW my_ca_view SET (timescaledb.refresh_interval = '30 min');`

The continuous aggregates job will top running.

**To Reproduce**
1. Create a hypertable.
2. Add a continuous aggregates view of the hypertable.
3. Alter the 'refresh_interval'.
4. Error: Job not executed after the expected time.
Note: This is not 100% reproducible.
**Expected behavior**
The job should still running correctly

**Actual behavior**
A clear and concise description of what _actually_ happened.

**Screenshots**
https://imgur.com/7psHIhM

**Additional context**

### PR DESCRIPTION
**Pull request by cevian**
This fixes the logic for what happens when the next start time
is changed on the bgw job:

- When changing the schedule_interval, the new next start time
  is set to last_finish + new_schedule_interval instead of
  now() + new_schedule_interval. This makes it easier to test
  and is semantically more correct
- New logic is added in the scheduler to recalculate the
  scheduler's next start time
- Better tests are added

Fixes #1462

### CODE REVIEW

File: src/bgw/job.c [hunk 1]
```diff
@@ -755,21 +755,24 @@ bgw_job_tuple_update_by_id(TupleInfo *ti, void *const data)
...
-								TimestampGetDatum(nowts),
-								IntervalPGetDatum(&updated_job->fd.schedule_interval)));
-		ts_bgw_job_stat_update_next_start(updated_job, next_start);
+		if (stat != NULL)
+		{
+			next_start = DatumGetTimestampTz(
+				DirectFunctionCall2(timestamptz_pl_interval,
+									TimestampTzGetDatum(stat->fd.last_finish),
+									IntervalPGetDatum(&updated_job->fd.schedule_interval)));
+			ts_bgw_job_stat_update_next_start(updated_job, next_start);
```
Comment (JLockerman) [inline src/bgw/job.c]: Should we have a default next-start-time if there is no previous `stat`?

File: tsl/test/expected/continuous_aggs_bgw.out [hunk 2]
```diff
@@ -154,28 +150,160 @@ SELECT * FROM _timescaledb_config.bgw_job where id=:job_id;
 (1 row)
 
 -- job ran once, successfully
-SELECT job_id, next_start, last_finish as until_next, last_run_success, total_runs, total_successes, total_failures, total_crashes
+SELECT job_id, next_start, last_finish, next_start-last_finish, last_run_success, total_runs, total_successes, total_failures, total_crashes
```
Comment (JLockerman) [inline tsl/test/expected/continuous_aggs_bgw.out]:
```suggestion
SELECT job_id, next_start, last_finish, next_start-last_finish as until_next, last_run_success, total_runs, total_successes, total_failures, total_crashes
```

File: tsl/test/expected/continuous_aggs_bgw.out [hunk 3]
```diff
@@ -154,28 +150,160 @@ SELECT * FROM _timescaledb_config.bgw_job where id=:job_id;
...
+SELECT wait_for_timer_to_run(0);
+WARNING:  waiting
+ wait_for_timer_to_run 
+-----------------------
+ t
+(1 row)
+
+--advance to 12:00 so that it runs one more time; now we know the
+--scheduler has loaded up the job with the old schedule_interval
+SELECT ts_bgw_params_reset_time(12::bigint*60*60*1000*1000, true);
```
Comment (JLockerman) [inline tsl/test/expected/continuous_aggs_bgw.out]: I kind of wish these numbers were a little less magic. I assume this is
`12 * :MINUTES_PER_HOUR * :SECONDS_PER_MINUTE * :MS_PER_S * :US_PER_MS`?

Comment (JLockerman) [reply tsl/test/expected/continuous_aggs_bgw.out]: `12 * :M_P_H * :S_P_M * :MS_P_S * :US_P_MS` 🤔

Comment (svenklemm) [reply tsl/test/expected/continuous_aggs_bgw.out]: extract(epoch from interval '12 hour') * 1000000

File: src/bgw/job.c (hunk 1 above)
Comment (cevian) [reply src/bgw/job.c]: If there is no stat, the scheduler already interprets as -infinity which I think is the right thing
