### PR TITLE
Fix compressing interval columns

### LINKED ISSUE #1726: ERROR:  invalid type for delta-delta compressor 1186
**Relevant system information:**
 - OS: [e.g. Ubuntu 16.04, Windows 10 x64, etc]
CentOS Linux release 7.7.1908 (Core)
 - PostgreSQL version (output of `postgres --version`): [e.g. 10.5, 9.6.10]
postgres (PostgreSQL) 10.11
 - TimescaleDB version (output of `\dx` in `psql`): [e.g. 1.0.0]
 timescaledb | 1.6.0   
 - Installation method: [e.g., "using Docker", "apt install", "source"]
PGDG
**Describe the bug**
I am starting to use compression on metric tables.
For one of them I get an error while compressing:
```
# SELECT compress_chunk(i) from show_chunks('metric_instance_vacuumwrk', older_than => interval '40 days') i;
ERROR:  invalid type for delta-delta compressor 1186
```
Table structure is:
```
CREATE TABLE metric_instance_vacuumwrk (
  time timestamp NOT NULL,
  instance_id INTEGER NOT NULL REFERENCES instance,
  dbname name NOT NULL,
  vacuum_type varchar(20) NOT NULL,
  workers smallint NOT NULL,
  age_max interval
);
SELECT create_hypertable('metric_instance_vacuumwrk', 'time');
ALTER TABLE metric_instance_vacuumwrk SET (
  timescaledb.compress,
  timescaledb.compress_segmentby = 'instance_id',
  timescaledb.compress_orderby = 'dbname, vacuum_type, time DESC'
);
```
Thanks

### PR DESCRIPTION
**Pull request by svenklemm**
When trying to compress a chunk that had a column of datatype
interval delta-delta compression would be selected for the column
but our delta-delta compression does not support interval and
would throw an errow when trying to compress a chunk.

This PR changes the compression selected for interval to dictionary
compression.

Fixes #1726

### CODE REVIEW

File: tsl/src/compression/create.c [hunk 1]
```diff
@@ -81,27 +81,23 @@ get_default_algorithm_id(Oid typeoid)
...
-		{
 			return COMPRESSION_ALGORITHM_GORILLA;
-		}
+
 		case NUMERICOID:
-		{
 			return COMPRESSION_ALGORITHM_ARRAY;
-		}
+
+		case INTERVALOID:
```
Comment (JLockerman) [inline tsl/src/compression/create.c]: technically we don't need this here, it'll just use the default anyway

File: tsl/test/expected/compression.out [hunk 2]
```diff
@@ -805,3 +805,21 @@ EXPLAIN (costs off) SELECT * FROM test_collation WHERE val_2 < 'a' COLLATE "C";
...
+--test datatypes
+CREATE TABLE datatype_test(time timestamptz NOT NULL, i2 int2, i4 int4, i8 int8, f4 float4, f8 float8, d date, ts timestamp, tstz timestamptz, i interval, n numeric, d2 decimal, t text, c char);
+SELECT create_hypertable('datatype_test','time');
+      create_hypertable      
+-----------------------------
+ (11,public,datatype_test,t)
+(1 row)
+
+ALTER TABLE datatype_test SET (timescaledb.compress);
+INSERT INTO datatype_test VALUES ('2000-01-01',2,4,8,4.0,8.0,'2000-01-01','2001-01-01 12:00','2001-01-01 6:00','1 week', 3.41, 4.2, 'text', 'x');
```
Comment (gayyappan) [inline tsl/test/expected/compression.out]: could you add a query to the test case to:
 select from _timescaledb_catalog.hypertable_compression and join with _timescaledb_catalog.compression_algorithm to display the algorithms being used for each column
