### PR TITLE
Fix groupby pathkeys for gapfill in PG16

### LINKED ISSUE #6396: [Bug]: time_bucket_gapfill ERROR when using DISTINCT
### What type of bug is this?

Unexpected error

### What subsystems and features are affected?

Gapfill

### What happened?

When using `DISTINCT` in a `time_bucket_gapfill` query I receive the following error.

`ERROR:  could not find pathkey item to sort`

### TimescaleDB version affected

2.13.0 

### PostgreSQL version used

16

### What operating system did you use?

Windows 10 Enterprise x64

### What installation method did you use?

Not applicable

### What platform did you run on?

On prem/Self-hosted

### Relevant log output and stack trace

_No response_

### How can we reproduce the bug?

```bash
CREATE TABLE stocks_real_time (
  time TIMESTAMPTZ NOT NULL,
  symbol TEXT NOT NULL,
  price DOUBLE PRECISION NULL,
  day_volume INT NULL
);

SELECT create_hypertable('stocks_real_time', by_range('time'));

INSERT INTO stocks_real_time
  VALUES
    (NOW(), 's1', 70.0, 50),
    (NOW(), 's2', 66.5, 60),
    (NOW(), 's3', 77.0, 65);

SELECT
  time_bucket_gapfill('1 day', time) AS day,
  COUNT(DISTINCT symbol) AS symbol_count
FROM stocks_real_time
WHERE time > '2023-12-01'
  AND time < '2023-12-10'
GROUP BY 1
ORDER BY 1 DESC
```

### PR DESCRIPTION
**Pull request by antekresic**
With PG16, group pathkeys can include column which are not in the GROUP BY clause when dealing with ordered aggregates. This means we have to exclude those columns when checking and creating the gapfill custom scan subpath.

Fixes #6396

### CODE REVIEW

**Review by svenklemm — APPROVED** [review]
LGTM

File: tsl/src/nodes/gapfill/gapfill_plan.c [hunk 1]
```diff
@@ -135,7 +135,17 @@ window_function_walker(Node *node, gapfill_walker_context *context)
...
+	groupby_pathkeys = list_copy(root->group_pathkeys);
+#else
+	/* In PG16 group_pathkeys can contain additional pathkeys
+	 * used for optimization on ordered aggregates.
+	 * We only want to deal with group by elements only here.
+	 */
+	groupby_pathkeys = list_copy_head(root->group_pathkeys, root->num_groupby_pathkeys);
+#endif
+	if (list_length(subpath->pathkeys) != list_length(groupby_pathkeys))
 		return false;
```
Comment (akuzm) [inline tsl/src/nodes/gapfill/gapfill_plan.c:149]: On PG16, the length condition is never false, do we need it?
Maybe we can remove it and use `list_copy_head` for all PG versions, for less code.
Or even better, rewrite the loop to use index, to avoid the copying and freeing altogether. In the current code, not all the return paths free the copy.

Comment (antekresic) [reply tsl/src/nodes/gapfill/gapfill_plan.c:149]: Can't use the index everywhere because the `num_groupby_pathkeys` is present only in PG16.

I could rewrite it to use the index instead of copying the list, I would still need a check for versions so we can use `num_groupby_pathkeys` for PG16 and above, `list_length(root->group_pathkeys)` for all other.

**Review by akuzm — APPROVED** [review]
