### PR TITLE
Fix sub-second intervals in hierarchical caggs

### LINKED ISSUE #5277: [Bug]: ERROR: cannot create continuous aggregate with incompatible bucket width
### What type of bug is this?

Unexpected error

### What subsystems and features are affected?

Continuous aggregate

### What happened?

I want to create continuous aggregate c on top of another continuous aggregate b: 
```sql
CREATE MATERIALIZED VIEW b WITH (timescaledb.continuous)
AS SELECT
    time_bucket('9344 ms', "time") as bucket9344,
    MAX(delay) as delay
FROM a
GROUP BY bucket9344
WITH NO DATA;
```
```sql
CREATE MATERIALIZED VIEW c WITH (timescaledb.continuous)
AS SELECT
    time_bucket('74752 ms', "bucket9344") as bucket74752,
    MAX(delay) as delay
FROM b
GROUP BY bucket74752
WITH NO DATA;
```

And I got this error: 
> ERROR:  cannot create continuous aggregate with incompatible bucket width
DETAIL:  Time bucket width of "c" [00:01:14.749] should be multiple of the time bucket width of "b" [00:00:09.344].

But `74752 ms` is 8 times of  `9344 ms`. How can I create `d`? 

Thanks

### TimescaleDB version affected

2.9.2

### PostgreSQL version used

14.6

### What operating system did you use?

Docker image timescale/timescaledb:latest-pg14 on Archlinux host

### What installation method did you use?

Docker

### What platform did you run on?

On prem/Self-hosted

### Relevant log output and stack trace

> org.jkiss.dbeaver.model.sql.DBSQLException: SQL Error [0A000]: ERROR: cannot create continuous aggregate with incompatible bucket width
>   Detail: Time bucket width of "misc.c" [00:01:14.752] should be multiple of the time bucket width of "misc.b" [00:00:09.344].
> 	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:133)
> 	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:575)
> 	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$1(SQLQueryJob.java:484)
> 	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:172)
> 	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:491)
> 	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:878)
> 	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:3526)
> 	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:118)
> 	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:172)
> 	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:116)
> 	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$ResultSetDataPumpJob.run(ResultSetViewer.java:4868)
> 	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:105)
> 	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
> Caused by: org.postgresql.util.PSQLException: ERROR: cannot create continuous aggregate with incompatible bucket width
>   Detail: Time bucket width of "misc.c" [00:01:14.752] should be multiple of the time bucket width of "misc.b" [00:00:09.344].
> 	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2565)
> 	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2297)
> 	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:322)
> 	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:481)
> 	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:401)
> 	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:322)
> 	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:308)
> 	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:284)
> 	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:279)
> 	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:329)
> 	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.lambda$0(JDBCStatementImpl.java:131)
> 	at org.jkiss.dbeaver.utils.SecurityManagerUtils.wrapDriverActions(SecurityManagerUtils.java:94)
> 	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:131)
> 	... 12 more

### How can we reproduce the bug?

```sql
CREATE TABLE IF NOT EXISTS a
(
    "time"  TIMESTAMPTZ(3) NOT NULL,
    "delay" numeric 
);

SELECT create_hypertable(
    'a',
    'time',
    if_not_exists => TRUE,
    chunk_time_interval => INTERVAL '1 m',
    create_default_indexes => FALSE
);

CREATE MATERIALIZED VIEW b WITH (timescaledb.continuous)
AS SELECT
    time_bucket('9344 ms', "time") as bucket9344,
    MAX(delay) as delay
FROM a
GROUP BY bucket9344
WITH NO DATA;

CREATE MATERIALIZED VIEW c WITH (timescaledb.continuous)
AS SELECT
    time_bucket('74752 ms', "bucket9344") as bucket74752,
    MAX(delay) as delay
FROM b
GROUP BY bucket74752
WITH NO DATA;
```

### PR DESCRIPTION
**Pull request by konskov**
Previously we used date_part("epoch", interval) and integer division
internally to determine whether the top cagg's interval is a
multiple of its parent's.
This led to precision loss and wrong results
in the case of intervals with sub-second components.

Fixed by using the `ts_interval_value_to_internal` function to convert
intervals to appropriate integer representation for division.

Fixes #5277

### CODE REVIEW

File: tsl/src/continuous_aggs/create.c [hunk 1]
```diff
@@ -1147,9 +1147,19 @@ get_bucket_width(CAggTimebucketInfo bucket_info)
...
 			Datum epoch = DirectFunctionCall2(interval_part,
 											  PointerGetDatum(cstring_to_text("epoch")),
 											  IntervalPGetDatum(bucket_info.interval));
+			/* Preserve precision if possible for units less than seconds by converting to usecs or
+			 * msecs */
+			if (PG_INT64_MAX / USECS_PER_SEC + PG_INT64_MAX % USECS_PER_SEC > DatumGetFloat8(epoch))
+				epoch = DirectFunctionCall2(float8mul, epoch, float_usecs_per_sec);
+			else if (PG_INT64_MAX / MSECS_PER_SEC + PG_INT64_MAX % MSECS_PER_SEC >
+					 DatumGetFloat8(epoch))
+				epoch = DirectFunctionCall2(float8mul, epoch, float_msecs_per_sec);
```
Comment (akuzm) [inline tsl/src/continuous_aggs/create.c:1162]: I am a little confused by this: epoch is a float8, and depending on its value we convert it either to milliseconds or microseconds. How does the subsequent code know in which units it is?

Comment (konskov) [reply tsl/src/continuous_aggs/create.c:1162]: Thanks a lot for reviewing! You're right to be confused, as we don't know which units it is. Sorry about that. My reasoning was, first try to convert to usec. It's the smallest unit of time supported in intervals so there should be no loss here. If the value is too large to convert to usec, then try to convert to milliseconds, but of course that might not always work.

**Review by RafiaSabih — APPROVED** [review]

**Comment by fabriziomello** [comment]
@konskov isn't easier to use `float8` instead of `int64` for bucket size validation?? Something like:

**Comment by konskov** [comment]
Thank you very much @fabriziomello!

**Review by fabriziomello — APPROVED** [review]

File: tsl/src/continuous_aggs/create.c [hunk 2]
```diff
@@ -1147,11 +1148,13 @@ get_bucket_width(CAggTimebucketInfo bucket_info)
...
 				bucket_info.interval->month = 0;
 			}
+
 			Datum epoch = DirectFunctionCall2(interval_part,
 											  PointerGetDatum(cstring_to_text("epoch")),
 											  IntervalPGetDatum(bucket_info.interval));
+
 			/* Cast float8 to int8. */
-			width = DatumGetInt64(DirectFunctionCall1(dtoi8, epoch));
+			width = DatumGetFloat8(epoch);
```
Comment (gayyappan) [inline tsl/src/continuous_aggs/create.c:1157]: Why are we not converting to milliseconds and using integer comparisons?
floating point comparisons are not reliable, subject to rounding error etc.

Comment (konskov) [reply tsl/src/continuous_aggs/create.c:1157]: thank you @gayyappan for the review! Converting to millis/micros is what I'd initially attempted, but I don't have a strong opinion...

Comment (fabriziomello) [reply tsl/src/continuous_aggs/create.c:1157]: @gayyappan are u talking about using `ts_interval_value_to_internal` function??

Comment (gayyappan) [reply tsl/src/continuous_aggs/create.c:1157]: I haven't looked into how to implement this. My observation is that using floats for comparisons will have rounding errors. It is safer to convert everything to int64 and compare values as integers.  Yes, this function looks like a good candidate to convert the interval as an integer value.

Comment (fabriziomello) [reply tsl/src/continuous_aggs/create.c:1157]: You are correct @gayyappan ... it can be even simpler @konskov:
```diff
diff --git a/tsl/src/continuous_aggs/create.c b/tsl/src/continuous_aggs/create.c
index ada8166d1..8645630b8 100644
--- a/tsl/src/continuous_aggs/create.c
+++ b/tsl/src/continuous_aggs/create.c
@@ -1151,11 +1151,9 @@ get_bucket_width(CAggTimebucketInfo bucket_info)
                bucket_info.interval->day = bucket_info.interval->month * DAYS_PER_MONTH;
                bucket_info.interval->month = 0;
            }
-           Datum epoch = DirectFunctionCall2(interval_part,
-                                             PointerGetDatum(cstring_to_text("epoch")),
-                                             IntervalPGetDatum(bucket_info.interval));
-           /* Cast float8 to int8. */
-           width = DatumGetInt64(DirectFunctionCall1(dtoi8, epoch));
+
+           /* Convert Interval to int64 */
+           width = ts_interval_value_to_internal(IntervalPGetDatum(bucket_info.interval), INTERVALOID);
            break;
        }
        default:
```

File: tsl/src/continuous_aggs/create.c [hunk 3]
```diff
@@ -1128,7 +1128,7 @@ cagg_query_supported(const Query *query, StringInfo hint, StringInfo detail, con
 static inline int64
 get_bucket_width(CAggTimebucketInfo bucket_info)
 {
-	int64 width = 0;
+	float8 width = 0;
```
Comment (fabriziomello) [inline tsl/src/continuous_aggs/create.c:1131]:
```suggestion
	int64 width = 0;
```

File: CHANGELOG.md [hunk 4]
```diff
@@ -13,6 +13,7 @@ accidentally triggering the load of a previous DB version.**
 * #5317 Fix some incorrect memory handling
 * #5367 Rename columns in old-style continuous aggregates
 * #5384 Fix Hierarchical Continuous Aggregates chunk_interval_size
+* #5304 Support sub-second intervals in hierarchical caggs
```
Comment (fabriziomello) [inline CHANGELOG.md:16]: I guess this issue is a bugfix so we should mention it here

Comment (konskov) [reply CHANGELOG.md:16]: should I make any changes here then?

Comment (fabriziomello) [reply CHANGELOG.md:16]:
```suggestion
* #5304 Fix sub-second intervals in Hierarchical Continuous Aggregates
```

**Review by fabriziomello — APPROVED** [review]

File: tsl/src/continuous_aggs/create.c (hunk 1 above)
Comment (fabriziomello) [reply tsl/src/continuous_aggs/create.c]: Fixed it by avoid using epoch and converting Interval to integer.
