### PR TITLE
Throw better error message on incompatible row fetcher settings

### LINKED ISSUE #4518: [Bug]: unexpected PQresult status 7 when starting COPY mode
### What type of bug is this?

Unexpected error

### What subsystems and features are affected?

Multi-node

### What happened?

Got the following error in a join on distributed hypertable:
```
ERROR:  XX000: unexpected PQresult status 7 when starting COPY mode
LOCATION:  row_by_row_fetcher_send_fetch_request, row_by_row_fetcher.c:125
```

### TimescaleDB version affected

main

### PostgreSQL version used

14.4

### What operating system did you use?

Archlinux 2022.07.01 x64

### What installation method did you use?

Source

### What platform did you run on?

On prem/Self-hosted

### Relevant log output and stack trace

```bash
ERROR:  XX000: unexpected PQresult status 7 when starting COPY mode
LOCATION:  row_by_row_fetcher_send_fetch_request, row_by_row_fetcher.c:125
```

### How can we reproduce the bug?

```
select * from
  conditions_dist1 ref_0
where EXISTS (
  select from
            distinct_on_distributed as ref_1,
            lateral (select * from metrics as ref_2) as subq_3
    where
        (select device_id from metrics_compressed limit 1 offset 3) >= ref_0.device
);
```

### PR DESCRIPTION
**Pull request by svenklemm**
When a query has multiple distributed hypertables the row-by-by
fetcher cannot be used. This patch adjusts the fetcher type
selection to always use cursor fetcher when multiple distributed
hypertables are involved.

Fixes #4518

### CODE REVIEW

**Comment by svenklemm** [comment]
I'll add tests once the other row-by-row PR is merged #4516

File: src/planner/planner.c [hunk 1]
```diff
@@ -482,21 +482,21 @@ timescaledb_planner(Query *parse, int cursor_opts, ParamListInfo bound_params)
 			{
 				reset_fetcher_type = true;
 
-				if (ts_guc_remote_data_fetcher == AutoFetcherType)
+				if (context.num_distributed_tables >= 2)
```
Comment (akuzm) [inline src/planner/planner.c:485]: The idea was for manual `ts_guc_remote_data_fetcher` to have preference over everything else. So if you set it manually to row-by-row when it can't work, it is expected to fail. I think this is more straightforward to use, i.e. it doesn't quietly ignore the explicit setting in some cases.

The default is `auto`, so why does it fail in your case, did you change it to row-by-row?

Comment (akuzm) [reply src/planner/planner.c:485]: The error message should be less cryptic though

Comment (svenklemm) [reply src/planner/planner.c:485]: Hmm yes this is due to the guc setting, similar planner gucs in postgres will fall back to working configuration to prevent running in a dead-end. e.g. disable_seqscan will still do seq scan if nothing else works. I think this behaviour is preferable over the current behaviour. If we encounter a situation that is known to not work we should not produce weird errors but instead fall back to working configuration.

Comment (svenklemm) [reply src/planner/planner.c:518]: Changed it to throw error instead

**Review by akuzm — APPROVED** [review]

**Review by RafiaSabih — APPROVED** [review]
