### PR TITLE
Assume custom time type range is same as bigint

### LINKED ISSUE #2523: Custom time types broken for hypertables in master
**Describe the bug**
On master branch there seems to have been an overhaul how custom types for timestamps are handled. In 1.x any custom type that was binary coercible was allowed to be a timestamp type. Now, this is only allowed for *implicitly* convertible types. So, somehow this condition has been both relaxed and made stricter at the same time. Non-binary coercible types that are implicitly convertible are allowed now. Binary coercible types that are not implicitly convertible (eg. either assignment or explicit) are now disallowed.
This actually breaks all of our tables as our custom type has a binary coercible, but assignment-level type conversion.

The code in the 2.x branch is like this:
```
/*
 * Try to coerce a type to a supported time type.
 *
 * To support custom time types in hypertables, we need to know the type's
 * boundaries in order to, e.g., construct dimensional chunk constraints. If
 * the type is IMPLICITLY coercible to one of the supported time types we can
 * just use the boundaries of the supported type. Thus, the custom time type
 * will inherit the time boundaries of the first compatible time type found.
 */
static Oid
coerce_to_time_type(Oid type)
{
	static const Oid supported_time_types[] = { DATEOID, TIMESTAMPOID, TIMESTAMPTZOID,
												INT2OID, INT4OID,	  INT8OID };

	int i;

	for (i = 0; i < lengthof(supported_time_types); i++)
	{
		Oid targettype = supported_time_types[i];

		if (can_coerce_type(1, &type, &targettype, COERCION_IMPLICIT))
			return targettype;
	}

	elog(ERROR, "unsupported time type \"%s\"", format_type_be(type));
	pg_unreachable();
}
```

In the 1.7.x branch, it is like this:
```
ts_type_is_int8_binary_compatible(Oid sourcetype)
{
	HeapTuple tuple;
	Form_pg_cast castForm;
	bool result;

	tuple =
		SearchSysCache2(CASTSOURCETARGET, ObjectIdGetDatum(sourcetype), ObjectIdGetDatum(INT8OID));
	if (!HeapTupleIsValid(tuple))
		return false; /* no cast */
	castForm = (Form_pg_cast) GETSTRUCT(tuple);
	result = castForm->castmethod == COERCION_METHOD_BINARY;
	ReleaseSysCache(tuple);
	return result;
}
```

**To Reproduce**
There is actually a test case in the regression tests that test this behavior. It seems it was altered at the same time this behavior was changed by @erimatnor in https://github.com/timescale/timescaledb/pull/2310/files  (see `test/custom_type.sql.in`). That commit adds an IMPLICIT cast to the custom type that was not there before - probably to make the test case pass with the new behavior.

Can this be changed such that at least it does not break existing databases after an upgrade? This means either changing `coerce_to_time_type` to accept EXPLICIT and/or ASSIGNMENT-level casts:
```
		if (can_coerce_type(1, &type, &targettype, COERCION_EXPLICIT)) // or COERCION_ASSIGNMENT which would fix our particular use case, but maybe there are other types out there that have an EXPLICIT binary compatible cast instead
```

Or changing it in a way that does not call `can_coerce_type` at all, but instead uses a similar check as on the 1.x branch, which only checks for binary coercibility, disregarding implicit/assignment/explicit completely.

### PR DESCRIPTION
**Pull request by erimatnor**
The database must know the valid time range of a custom time type,
similar to how it knows the time ranges of officially supported time
types. However, the only way to "know" the valid time range of a
custom time type is to assume it is the same as the one of a supported
time type.

A previous commit tried to make such assumptions by finding an
appropriate cast from the custom time type to a supported time
type. However, this fails in case there are multiple casts available
that each could return a different type and range.

This change restricts the choice of valid time ranges to only that of
the bigint time type.

Fixes #2523

### CODE REVIEW

**Comment by erimatnor** [comment]
There's an extra commit attached to this PR, which enhances functions for saturating subtraction and addition. Strictly, this could also be a separate PR if people feel strongly about this.

File: src/dimension.c [hunk 1]
```diff
@@ -1001,24 +1001,32 @@ dimension_interval_to_internal(const char *colname, Oid dimtype, Oid valuetype,
...
+			if (IS_TIMESTAMP_TYPE(dimtype))
+				ereport(ERROR,
+						(errcode(ERRCODE_INVALID_PARAMETER_VALUE),
+						 errmsg("invalid interval type for %s dimension", format_type_be(dimtype)),
+						 errhint("Use an interval of type interval or integer.")));
+			else
+				ereport(ERROR,
+						(errcode(ERRCODE_INVALID_PARAMETER_VALUE),
+						 errmsg("invalid interval type for %s dimension", format_type_be(dimtype)),
+						 errdetail("Use an interval of type integer.")));
```
Comment (mkindahl) [inline src/dimension.c:1022]: They only differ in the detail message. Probably good to use a `:?` there instead to avoid mistakes when maintaining this code.

File: src/time_utils.c [hunk 2]
```diff
@@ -468,15 +460,25 @@ ts_time_get_noend_or_max(Oid timetype)
...
+	{
+		min_overflow_result = ts_time_get_min(timetype);
+		max_overflow_result = ts_time_get_max(timetype);
+	}
+
+	if (timeval > 0 && interval > 0 && timeval > (ts_time_get_max(timetype) - interval))
+		return max_overflow_result;
+
+	if (timeval < 0 && interval < 0 && timeval < (ts_time_get_min(timetype) - interval))
+		return min_overflow_result;
```
Comment (mkindahl) [inline src/time_utils.c:481]: You actually only need to compute the max and min values for these cases, so you can remove the code above and just use this:
```suggestion
	if (timeval > 0 && interval > 0 && timeval > (ts_time_get_max(timetype) - interval))
		return ts_time_get_noend_or_max(timetype);

	if (timeval < 0 && interval < 0 && timeval < (ts_time_get_min(timetype) - interval))
		return ts_time_get_nobegin_or_min(timetype);
```

File: src/time_utils.c [hunk 3]
```diff
@@ -492,15 +494,25 @@ ts_time_saturating_add(int64 timeval, int64 interval, Oid timetype)
...
+	{
+		min_overflow_result = ts_time_get_min(timetype);
+		max_overflow_result = ts_time_get_max(timetype);
+	}
+
+	if (timeval < 0 && interval > 0 && timeval < (ts_time_get_min(timetype) + interval))
+		return min_overflow_result;
+
+	if (timeval > 0 && interval < 0 && timeval > (ts_time_get_max(timetype) + interval))
+		return max_overflow_result;
```
Comment (mkindahl) [inline src/time_utils.c:515]: Same here. You can remove the code above and just use:
```suggestion
	if (timeval < 0 && interval > 0 && timeval < (ts_time_get_min(timetype) + interval))
		return ts_time_get_nobegin_or_min(timetype);

	if (timeval > 0 && interval < 0 && timeval > (ts_time_get_max(timetype) + interval))
		return ts_time_get_noend_or_max(timetype);
```

File: src/time_utils.c [hunk 4]
```diff
@@ -468,15 +460,25 @@ ts_time_get_noend_or_max(Oid timetype)
...
+		min_overflow_result = ts_time_get_nobegin(timetype);
+		max_overflow_result = ts_time_get_noend(timetype);
 	}
-	else if (timeval >= (ts_time_get_end(timetype) - interval))
-		return ts_time_get_noend(timetype);
+	else
+	{
+		min_overflow_result = ts_time_get_min(timetype);
+		max_overflow_result = ts_time_get_max(timetype);
+	}
```
Comment (mkindahl) [inline src/time_utils.c:475]: Why not something like this? 

```
min_overflow_result = ts_time_get_nobegin_or_min(timetype);
max_overflow_result = ts_time_get_noend_or_max(timetype);
```

File: src/time_utils.h [hunk 5]
```diff
@@ -40,32 +40,33 @@
 #define TS_TIME_NOBEGIN (PG_INT64_MIN)
 #define TS_TIME_NOEND (PG_INT64_MAX)
 
-#define TS_TIME_IS_INTEGER_TIME(type) (type == INT2OID || type == INT4OID || type == INT8OID)
+#define IS_INTEGER_TYPE(type) (type == INT2OID || type == INT4OID || type == INT8OID)
+#define IS_TIMESTAMP_TYPE(type) (type == TIMESTAMPOID || type == TIMESTAMPTZOID || type == DATEOID)
+#define TS_TIME_IS_VALID_TYPE(type) (IS_INTEGER_TYPE(type) || IS_TIMESTAMP_TYPE(type))
```
Comment (mkindahl) [inline src/time_utils.h:45]: Nit.
```suggestion
#define TS_IS_VALID_TIME_TYPE(type) (IS_INTEGER_TYPE(type) || IS_TIMESTAMP_TYPE(type))
```

File: src/time_utils.c (hunk 2 above)
Comment (erimatnor) [reply src/time_utils.c:481]: The latter function didn't exist, but I guess I can create it.

**Review by mkindahl — APPROVED** [review]

**Review by pmwkaa — APPROVED** [review]

**Review by svenklemm — APPROVED** [review]
