### PR TITLE
Fix index inserts during decompression

### LINKED ISSUE #6205: [Bug]: Error enabling compression on hypertable with unique expression index
### What type of bug is this?

Unexpected error

### What subsystems and features are affected?

Compression

### What happened?

```
alter table mytab set (timescaledb.compress);
ERROR:  XX000: cache lookup failed for attribute 0 of relation 25410
```

### TimescaleDB version affected

2.12.0 and above

### PostgreSQL version used

15.2

### What operating system did you use?

MacOS Sonoma 14.0

### What installation method did you use?

Source

### What platform did you run on?

On prem/Self-hosted

### Relevant log output and stack trace

_No response_

### How can we reproduce the bug?

```bash
create table mytab (col1 varchar(100) not null, col2 integer not null,
value double precision not null default 0, arrival_ts timestamptz not null, departure_ts timestamptz not null
default current_timestamp);

select create_hypertable('mytab', 'departure_ts');
create unique index myidx_unique ON
mytab (lower(col1::text), col2, departure_ts, arrival_ts);
alter table mytab set (timescaledb.compress);
```
```

### PR DESCRIPTION
**Pull request by konskov**
Since version 2.11.0 we would get a segmentation fault during
decompression when there was an expressional or partial index on the
uncompressed chunk.
This patch fixes this by calling `ExecInsertIndexTuples` to insert into
indexes during chunk decompression, instead of `CatalogIndexInsert`.

In addition, when enabling compression on a hypertable, we check the
unique indexes defined on it to provide performance improvement hints
in case the unique index columns are not specified as compression
parameters.
However this check threw an error when expression columns were present
in the index, preventing the user from enabling compression.
This patch fixes this by simply ignoring the expression columns in the
index, since we cannot currently segment by an expression.

Fixes #6205, #6186

### CODE REVIEW

**Review by svenklemm — APPROVED** [review]

File: tsl/src/compression/compression.c [hunk 1]
```diff
@@ -1590,7 +1590,33 @@ row_decompressor_decompress_row(RowDecompressor *decompressor, Tuplesortstate *t
 							0 /*=options*/,
 							decompressor->bistate);
 
-				ts_catalog_index_insert(decompressor->indexstate, decompressed_tuple);
+				EState *estate = CreateExecutorState();
```
Comment (antekresic) [inline tsl/src/compression/compression.c:1593]: If there is any possibility, I would like it if we could avoid creating the estate for every index insertion. Maybe caching it on the decompressor level and reusing is the way to go.

Comment (konskov) [reply tsl/src/compression/compression.c]: I made some changes wrt this, now we cache the estate in the decompressor.

File: tsl/src/compression/compression.c [hunk 2]
```diff
@@ -2107,6 +2131,7 @@ decompress_batches_for_insert(ChunkInsertState *cis, Chunk *chunk, TupleTableSlo
 	table_endscan(heapScan);
 
 	ts_catalog_close_indexes(decompressor.indexstate);
+	FreeExecutorState(decompressor.estate);
```
Comment (antekresic) [inline tsl/src/compression/compression.c:2134]: Out of scope for this PR: we should create a decompressor finisher/closer function, seems like we have some management at the end of its lifecycle.

**Review by antekresic — APPROVED** [review]
LGTM :+1:
