### PR TITLE
Exponentially backoff when out of background workers

### LINKED ISSUE #4562: [Enhancement]: Job scheduler - exponential backoffs
### What type of enhancement is this?

User experience

### What subsystems and features will be improved?

Background worker

### What does the enhancement do?

When a job fails, the next attempt is scheduled with an exponential backoff.
For instance, the first attempt is executed after 10 second, the next attempts are executed after 30 seconds, 2 minutes, 10 minutes...

### Implementation challenges

_No response_

### PR DESCRIPTION
**Pull request by konskov**
The scheduler detects the following three types of job failures:

1.Jobs that fail to launch (due to shortage of background workers)
2.Jobs that throw a runtime error
3.Jobs that crash due to a process crashing

In cases 2 and 3, additive backoff is applied in calculating the next
start time of a failed job.
In case 1 we previously retried to launch all jobs that failed to launch
simultaneously.

This commit introduces exponential backoff in case 1,
randomly selecting a wait time in [2, 2 + 2^f] seconds at microsecond granularity.
The aim is to reduce the collision probability for jobs that compete
for a background worker. The maximum backoff value is 1 minute.
It does not change the behavior for cases 2 and 3.

Fixes #4562

### CODE REVIEW

**Review by mkindahl — COMMENTED** [review]
In general, this looks good, but it would be good if you could add an outline in the commit message where you describe how:

- Jobs that fail while executing are re-tried
- Jobs that fail to start the background worker are re-tried (IIRC, this is different from the one above)
- Jobs that succeed are re-tried

**Review by gayyappan — COMMENTED** [review]
IIRC we had exponential backoff initially and then switched to additive backoff. The problem is with jobs that have fairly longer schedules. Say the job is scheduled to run once a day. With exponential backoff, you will quickly schedule a failed job too far into the future. A better way might be to add an upper bound for the next start time after a failure.
i.e. if job failed:
```
      new_start_time = last_failure_time + schedule interval (with some back off)
      ub_start_time = last_failue_time + '1 h'
      if  ub_start_time < new_start_time
          new_start_time = worst_case.

```

Also make sure to test and catch potential overflow with exponential backoffs.

**Comment by konskov** [comment]
Thank you so much for reviewing! Currently there is an upper bound but it is probably too high (10 times the schedule interval, and for jobs that fail to launch due to background worker shortage, the upper bound is 1 minute). I will change it to something fixed and smaller, '1h' as you suggest.

**Review by svenklemm — APPROVED** [review]

**Review by fabriziomello — APPROVED** [review]

File: src/bgw/job_stat.c [hunk 1]
```diff
@@ -211,15 +212,37 @@ calculate_next_start_on_failure(TimestampTz finish_time, int consecutive_failure
...
+		{
+			// retry every 2 seconds
+			ival = IntervalPGetDatum(&retry_ival);
+		}
+
+		/* ival = retry_period ^ (consecutive_failures - 1)  */
+		/* arbitrarily choose 2 for exponential growth */
+		for (i = 0; i < exponent - 1; i++)
+		{
+			ival = DirectFunctionCall2(interval_mul, ival, Float8GetDatum(2));
```
Comment (mfundul) [inline src/bgw/job_stat.c:233]: Exponential backoff works when the scheduled time is picked randomly between `now()` and `now() + ival` (regardless of jitter). If we always pick `now() + ival` then we risk livelocking the conflicting jobs ad infinitum.

This is orthogonal to jitter, which helps with scheduling at non-integer multiples of time units, so as to not generate high load spikes in the system (e.g. due to everything happening at integer seconds instead of spreading them out).

**Review by mfundul — CHANGES_REQUESTED** [review]

File: src/bgw/job_stat.c (hunk 1 above)
Comment (konskov) [reply src/bgw/job_stat.c:233]: You are right, we are risking that. So for first case (out of background workers) I will change the backoff calculation to  randomly pick a backoff value between [0, 2^f - 1] where f is the number of consecutive failed launches of the job.

**Review by mfundul — CHANGES_REQUESTED** [review]

File: src/bgw/job_stat.c [hunk 2]
```diff
@@ -198,8 +199,19 @@ calculate_next_start_on_failure(TimestampTz finish_time, int consecutive_failure
...
+	 * the aim of backoff is to reduce conflicts in the case of jobs that fail to launch,
+	 * as there are jobs competing for available background workers in that case.
+	 * therefore we introduce some randomness in backoff calculation for that type of failure
+	 * by randomly selecting the exponent in the interval [1, consecutive_failures]
+	 * Otherwise as soon as a worker becomes available, all jobs will try to grab it, but only one
+	 * will anyway so why should they all try at once? so jobs that experience failures will delay
+	 * their next_start a random amount to reduce the probability of collisions
+	 */
+	Assert(consecutive_failures > 0);
+	int rand_exp = random() % consecutive_failures + 1;
```
[the remark this answers is not in the document]
Comment (konskov) [reply src/bgw/job_stat.c]: Thank you for correcting me 😓 I changed that to select a random backoff time in the range at a microsec granularity.

File: src/bgw/job_stat.c [hunk 3]
```diff
@@ -198,8 +199,25 @@ calculate_next_start_on_failure(TimestampTz finish_time, int consecutive_failure
...
+	 * their next_start a random amount to reduce the probability of collisions
+	 */
+	Assert(consecutive_failures > 0);
+	// 2^(consecutive_failures) - 1, at most 2^20
+	int64 max_slots = (1 << consecutive_failures) - 1;
+	// granularity: 1 usec (2^20)
+	int64 micros_per_minute = 1000000;
+	// will get a random int in [0, (2^f - 1) * 1000]
+	// this represents a random amount of microseconds to backoff
+	int64 rand_backoff = random() % (max_slots * micros_per_minute);
```
Comment (mfundul) [inline src/bgw/job_stat.c:220]:
```suggestion
	int64 rand_backoff = random() % (max_slots * USECS_PER_SEC);
```
I don't see anything to do with minutes here.

File: src/bgw/job_stat.c [hunk 4]
```diff
@@ -198,8 +199,25 @@ calculate_next_start_on_failure(TimestampTz finish_time, int consecutive_failure
...
+	 * Otherwise as soon as a worker becomes available, all jobs will try to grab it, but only one
+	 * will anyway so why should they all try at once? so jobs that experience failures will delay
+	 * their next_start a random amount to reduce the probability of collisions
+	 */
+	Assert(consecutive_failures > 0);
+	// 2^(consecutive_failures) - 1, at most 2^20
+	int64 max_slots = (1 << consecutive_failures) - 1;
+	// granularity: 1 usec (2^20)
+	int64 micros_per_minute = 1000000;
+	// will get a random int in [0, (2^f - 1) * 1000]
```
Comment (mfundul) [inline src/bgw/job_stat.c:218]: Is this comment up-to-date?

File: src/bgw/job_stat.c (hunk 3 above)
Comment (konskov) [reply src/bgw/job_stat.c]: Indeed

File: src/bgw/job_stat.c [hunk 5]
```diff
@@ -211,15 +228,40 @@ calculate_next_start_on_failure(TimestampTz finish_time, int consecutive_failure
...
-											 Float8GetDatum(MAX_INTERVALS_BACKOFF));
+		Datum ival_max;
+		if (job)
+			ival_max = DirectFunctionCall2(interval_mul,
+										   IntervalPGetDatum(&job->fd.schedule_interval),
+										   Float8GetDatum(MAX_INTERVALS_BACKOFF));
+		else
+		{
+			ival_max = IntervalPGetDatum(&interval_max);
+		}
```
Comment (mfundul) [inline src/bgw/job_stat.c:264]: you do:
```
		if (job)
		{
		}
		else
		{
		}
```
3 to 4 times here and below. Maybe you should create a meaningful boolean variable for the `if (job)` case, and you should probably only do 1 `if-else` instead of 3 consecutive times to improve readability.

File: src/bgw/job_stat.c [hunk 6]
```diff
@@ -211,15 +229,32 @@ calculate_next_start_on_failure(TimestampTz finish_time, int consecutive_failure
...
 		/* ival_max is the ceiling = MAX_INTERVALS_BACKOFF * schedule_interval */
-		Datum ival_max = DirectFunctionCall2(interval_mul,
-											 IntervalPGetDatum(&job->fd.schedule_interval),
-											 Float8GetDatum(MAX_INTERVALS_BACKOFF));
+		Datum ival_max;
+		// max wait time to launch job is 1 minute
+		Interval interval_max = { .time = 60000000 };
+		Interval retry_ival = { .time = 2000000 };
+		retry_ival.time += rand_backoff;
+		if (!launch_failure)
```
Comment (mfundul) [inline src/bgw/job_stat.c:240]:
```suggestion
		if (launch_failure)
```
I think?

Comment (konskov) [reply src/bgw/job_stat.c:240]: No, that should be the logic there. Launch failure is when the job couldn't be started because of lack of background workers, and in that case, we have the random backoff in seconds calculated above. 
In other cases (job threw runtime error) we have a retry period of 5 minutes, and so the backoff there grows like 5, 10, 20 minutes until it reaches the schedule interval to take the retry period into account. Unless you meant to put the launch_failure case first which would be more readable so I'll do that

**Review by mfundul — APPROVED** [review]
