### PR TITLE
Change cagg refresh to cover buckets

### LINKED ISSUE #2198: Test/improve UX of continuous aggregate refresh in combination with retention policy
Retention via `drop_chunks` on a hypertable that has continuous aggregates can interact in unexpected ways  with refreshes. For instance, if you drop data in a region and then refresh a continuous aggregate in the same region, then the aggregate will lose data. See https://github.com/timescale/timescaledb/issues/2198#issuecomment-690941152 for the description of this corner case.

We should have tests that explore these cases and, ideally, allows preventing accidental deletions of aggregate data via privileges on the continuous aggregate.

Related to #2135

### PR DESCRIPTION
**Pull request by k-rus**
Refresh of a continuous aggregate was expanding refresh window to
include buckets, which contain the start and end of the window. This
was leading to refreshing dropped data into the first bucket in the
corner case, when drop_before of a retention policy is the same as
start_offset of a continuous aggregate policy and the last dropped
chunk happens to intersect with the first bucket. See #2198 for
detailed discussion.

A behavior of a refresh, which is called when chunks are dropped, is
not changed, i.e., buckets, which fully cover chunks ot be dropped,
are refreshed if needed (i.e., there were changes in the chunks, which
were not refreshed yet). It can be done separately if needed.

Fixes #2198

### CODE REVIEW

File: tsl/src/continuous_aggs/invalidation.c [hunk 1]
```diff
@@ -361,7 +361,7 @@ cut_invalidation_along_refresh_window(const CaggInvalidationState *state,
 		/*
 		 * Entry completely enclosed so can be deleted:
 		 *
-		 * |---------------|
+		 * [---------------)
```
Comment (erimatnor) [inline tsl/src/continuous_aggs/invalidation.c:364]: FWIW, I used the different style to denote the difference between refresh window and invalidation. Don't mind changing though if you prefer.

Comment (k-rus) [reply tsl/src/continuous_aggs/invalidation.c:364]: The original style (which is yours, right) doesn't allow to see which side is open or close. This led into error in a diagram in another comment in this file.

File: tsl/src/continuous_aggs/refresh.c [hunk 2]
```diff
@@ -78,50 +78,93 @@ get_largest_bucketed_window(Oid timetype, int64 bucket_width)
...
+		{
+			int64 exclusive_end = result.end;
+			int64 bucketed_end;
+
+			/* The end of the window is non-inclusive so subtract one before
+			 * bucketing in case we're already at the end of the bucket (we don't
+			 * want to add an extra bucket). But we also don't want to subtract if
+			 * we are at the start of the bucket (we don't want to remove a
+			 * bucket). */
+			if (result.end > result.start)
```
Comment (mkindahl) [inline tsl/src/continuous_aggs/refresh.c:158]: If the end of the window is exclusive, shouldn't it always be the case that `result.end > result.start`?

File: tsl/src/continuous_aggs/invalidation.c [hunk 3]
```diff
@@ -380,7 +380,7 @@ cut_invalidation_along_refresh_window(const CaggInvalidationState *state,
 			/*
 			 * Need to cut in right end:
 			 *
-			 *     |------|
+			 *     [------)
 			 * [++++++]
 			 *
 			 * [++]
```
[the remark this answers is not in the document]
Comment (k-rus) [reply tsl/src/continuous_aggs/invalidation.c:386]: The invalidation interval is fully closed/inclusive, so it should be `[+++++]`, while the refresh window is half open, i.e., `[------)`. @mkindahl Does it answer your question?

File: tsl/src/continuous_aggs/refresh.c [hunk 4]
```diff
@@ -78,50 +78,93 @@ get_largest_bucketed_window(Oid timetype, int64 bucket_width)
...
+ * planned for the refresh and was checked with the bucketed refresh window.
+ * It is also applied during refresh on drop.
+ *
+ * shrink - argument used to decide between two options. true means option 1.
+ *
  */
 static InternalTimeRange
-compute_bucketed_refresh_window(const InternalTimeRange *refresh_window, int64 bucket_width)
+compute_bucketed_refresh_window(const InternalTimeRange *const refresh_window,
+								const int64 bucket_width, const bool shrink)
```
[the remark this answers is not in the document]
Comment (k-rus) [reply tsl/src/continuous_aggs/refresh.c:105]: Is it good enogh to say something like this?
> Returns a refresh window, which is aligned with buckets. If shrink is true, then the start of the aligned refresh window corresponds to the start of the first bucket, which is fully included into the given refresh window, and the end - to the end of the last included bucket. If shrink is false, then the start of the first bucket is set to the start of the bucket, which contains beginning of the given refresh window, and the end - the end of the bucket, containing the last point of the given refresh window (not refresh window is exclusive at the end).

File: tsl/src/continuous_aggs/refresh.c [hunk 5]
```diff
@@ -78,50 +78,93 @@ get_largest_bucketed_window(Oid timetype, int64 bucket_width)
...
- * we can only refresh along bucket boundaries, we need to adjust the refresh
- * window to be inclusive in both ends to be able to refresh the given
- * region. For example, if the dotted region below is the original window, the
- * adjusted refresh window includes all four buckets shown.
+ * The buckets can be aligned in two ways:
+ * 1. Align with buckets, which are fully included in the refresh window.
+ *
+ *   ....|.....|..
+ *
+ * 2. Align with buckets, which are fully covering the refresh window.
```
[the remark this answers is not in the document]
Comment (k-rus) [reply tsl/src/continuous_aggs/refresh.c:88]: Fully covering means that buckets cover entire window. In your example of fully covering, buckets 1-4 will fully covering the refresh window, while you show buckets 2-3, which are covered by the refresh window.

I will try to see if I can improve the formulation.

File: tsl/src/continuous_aggs/refresh.c (hunk 4 above)
[the remark this answers is not in the document]
Comment (mkindahl) [reply tsl/src/continuous_aggs/refresh.c:105]: Yes, it looks good.

File: tsl/src/continuous_aggs/refresh.c (hunk 2 above)
Comment (k-rus) [reply tsl/src/continuous_aggs/refresh.c]: This was originally there and I didn't modify the code. However, I agree that the false condition is not possible. cc @erimatnor

**Comment by k-rus** [comment]
@gayyappan @mkindahl Will it make the code more comprehensive (easier to read) if the shrink and expand cases are in different functions, instead of one function with `shrink` parameter, like now?

File: tsl/src/continuous_aggs/refresh.c (hunk 5 above)
[the remark this answers is not in the document]
Comment (mkindahl) [reply tsl/src/continuous_aggs/refresh.c:88]: Ok, I see how you reasoned about the term, but I think it is unclear without the context, so improving the text would be good.

**Comment by mkindahl** [comment]
> @gayyappan @mkindahl Will it make the code more comprehensive (easier to read) if the shrink and expand cases are in different functions, instead of one function with `shrink` parameter, like now?

Since you are passing the parameter as constant, I would think that two separate functions is easier to understand.

File: tsl/src/continuous_aggs/invalidation.c (hunk 3 above)
[the remark this answers is not in the document]
Comment (mkindahl) [reply tsl/src/continuous_aggs/invalidation.c:386]: Yup.

**Comment by k-rus** [comment]
> > @gayyappan @mkindahl Will it make the code more comprehensive (easier to read) if the shrink and expand cases are in different functions, instead of one function with `shrink` parameter, like now?
> 
> Since you are passing the parameter as constant, I would think that two separate functions is easier to understand.

I switched to draft and will separate the functions. I also think it will be easier to understand the start and the end of each case, when the code is not polluted with the other case.

File: tsl/src/continuous_aggs/refresh.c (hunk 4 above)
[the remark this answers is not in the document]
Comment (k-rus) [reply tsl/src/continuous_aggs/refresh.c]: Improved during separation into 2 functions

File: tsl/src/continuous_aggs/refresh.c (hunk 5 above)
[the remark this answers is not in the document]
Comment (k-rus) [reply tsl/src/continuous_aggs/refresh.c]: Hopefully improved

**Comment by k-rus** [comment]
> I switched to draft and will separate the functions. I also think it will be easier to understand the start and the end of each case, when the code is not polluted with the other case.

Done. Currently as a separate commit, but will be squashed or dropped.

**Review by mkindahl — APPROVED** [review]

File: tsl/src/continuous_aggs/refresh.c (hunk 2 above)
Comment (k-rus) [reply tsl/src/continuous_aggs/refresh.c]: Replaced with assert.

File: tsl/src/continuous_aggs/refresh.c [hunk 6]
```diff
@@ -235,7 +319,7 @@ continuous_agg_refresh_with_window(const ContinuousAgg *cagg,
 		};
 
 		InternalTimeRange bucketed_refresh_window =
-			compute_bucketed_refresh_window(&invalidation, cagg->data.bucket_width);
+			compute_circumscribed_bucketed_refresh_window(&invalidation, cagg->data.bucket_width);
```
Comment (gayyappan) [inline tsl/src/continuous_aggs/refresh.c:322]: When we process invalidations, since the refresh window was already aligned to buckets (line 467) and invalidation processing happens after that, can this ever happen:  bucketed_refresh_window != refresh_window?

File: tsl/test/expected/continuous_aggs_invalidation.out [hunk 7]
```diff
@@ -178,7 +189,7 @@ SELECT * FROM cagg_invals;
 (4 rows)
 
 -- Refreshing below the threshold does not move it:
-CALL refresh_continuous_aggregate('cond_10', 20, 49);
+CALL refresh_continuous_aggregate('cond_10', 0, 49);
```
Comment (gayyappan) [inline tsl/test/expected/continuous_aggs_invalidation.out:192]: why do we have to change this call? IIUC The existing call wouldn't affect the invalidations or threshold. Am I missing something here?

File: tsl/src/continuous_aggs/refresh.c (hunk 6 above)
Comment (k-rus) [reply tsl/src/continuous_aggs/refresh.c:322]: @gayyappan `refresh_window` can cover several invalidations, thus `bucketed_refresh_window`, which is calculated by `compute_circumscribed_bucketed_refresh_window`, might be much smaller than `refresh_window` (but it is never bigger).
For example
```
 [++++++++++++++++++++) - refresh_window
 |----|----|----|----|  - buckets
    [+++]    [+]        - invalidations
 [+++++++++)            - bucketed_refresh_window for the first invalidation
           [++++)       - bucketed_refresh_window for the second invalidation
```

File: tsl/test/expected/continuous_aggs_invalidation.out (hunk 7 above)
Comment (k-rus) [reply tsl/test/expected/continuous_aggs_invalidation.out:192]: It is leftover before I added call for `0, 50` above. I will fix this back.

Comment (k-rus) [reply tsl/test/expected/continuous_aggs_invalidation.out]: Fixed

**Review by gayyappan — APPROVED** [review]
Changes look good. 
Additional test requested **if** we don't already have 1 that shrinks both start and end bucket. e.g. refresh_window_aggregate( <cagg>, 1, 11) --> where both 1 and 11 will get moved to different values due to bucket alignment

**Comment by k-rus** [comment]
> Additional test requested **if** we don't already have 1 that shrinks both start and end bucket. e.g. refresh_window_aggregate( , 1, 11) --> where both 1 and 11 will get moved to different values due to bucket alignment

Examples to shrink each side exists.
