### PR TITLE
Function approximate_row_count returns 0 for caggs

### LINKED ISSUE #6051: [Bug]: approximate_row_count returns 0 for caggs
### What type of bug is this?

Incorrect result

### What subsystems and features are affected?

Continuous aggregate

### What happened?

approximate_row_count returns 0 for continuous aggregates

### TimescaleDB version affected

2.11.2

### PostgreSQL version used

15.4

### What operating system did you use?

Ubuntu 11.4.0-1ubuntu1~22.04

### What installation method did you use?

Docker

### What platform did you run on?

Timescale Cloud

### Relevant log output and stack trace

_No response_

### How can we reproduce the bug?

```bash
Query approximate_row_count for any cagg.


tsdbadmin@tsdb[219942]=> SELECT count(*) from public.stats_five_minutes;
   count
-----------
 460133498
(1 row)

tsdbadmin@tsdb[219942]=> SELECT approximate_row_count('public.stats_five_minutes');
 approximate_row_count
-----------------------
                     0
(1 row)
```
```

### PR DESCRIPTION
**Pull request by pdipesh02**
The approximate_row_count function is executed directly on the user view instead of corresponding materialized hypertable which returns 0 for caggs. The function is updated to fetch the details for materialized hypertable information corresponding to cagg and then get the approximate_row_count for the materialized hypertable.

Fixes #6051

### CODE REVIEW

File: sql/size_utils.sql [hunk 1]
```diff
@@ -428,6 +429,19 @@ DECLARE
...
     is_compressed_chunk INTEGER;
 BEGIN
+    -- Check if input relation is continuous aggregate view then
+    -- get the corresponding materialized hypertable and schema name
+    SELECT format('%I.%I', ht.schema_name, ht.table_name)::regclass FROM pg_class c
+    INTO mat_ht
+    INNER JOIN pg_namespace n ON (n.OID = c.relnamespace)
+    INNER JOIN _timescaledb_catalog.continuous_agg a ON (a.user_view_schema = n.nspname AND a.user_view_name = c.relname)
+    INNER JOIN _timescaledb_catalog.hypertable ht ON (a.mat_hypertable_id = ht.id)
+    WHERE c.OID = relation;
```
Comment (fabriziomello) [inline sql/size_utils.sql:439]:
```suggestion
    SELECT format('%I.%I', ht.schema_name, ht.table_name)::regclass
    INTO mat_ht
    FROM pg_class c
    JOIN pg_namespace n ON (n.OID = c.relnamespace)
    JOIN _timescaledb_catalog.continuous_agg a ON (a.user_view_schema = n.nspname AND a.user_view_name = c.relname)
    JOIN _timescaledb_catalog.hypertable ht ON (a.mat_hypertable_id = ht.id)
    WHERE c.OID = relation;
```

Nit. just cosmetic SQL formatting.

It is interesting that your SQL lead to a syntax error on psql console:
```sql
26528 (leader) fabrizio=# SELECT format('%I.%I', ht.schema_name, ht.table_name)::regclass FROM pg_class c INTO mat_ht
    INNER JOIN pg_namespace n ON (n.OID = c.relnamespace)
    INNER JOIN _timescaledb_catalog.continuous_agg a ON (a.user_view_schema = n.nspname AND a.user_view_name = c.relname)
    INNER JOIN _timescaledb_catalog.hypertable ht ON (a.mat_hypertable_id = ht.id)
    WHERE c.OID = 'conditions_summary'::regclass;
ERROR:  42601: syntax error at or near "INTO"
LINE 1: ...ma_name, ht.table_name)::regclass FROM pg_class c INTO mat_h...
                                                             ^
LOCATION:  scanner_yyerror, scan.l:1188
```

Probably it is a `psql` issue because your tests are passing, but with proposed reformatting it works perfect:
```sql
26528 (leader) fabrizio=# SELECT format('%I.%I', ht.schema_name, ht.table_name)::regclass
    INTO mat_ht
    FROM pg_class c
    JOIN pg_namespace n ON (n.OID = c.relnamespace)
    JOIN _timescaledb_catalog.continuous_agg a ON (a.user_view_schema = n.nspname AND a.user_view_name = c.relname)
    JOIN _timescaledb_catalog.hypertable ht ON (a.mat_hypertable_id = ht.id)
    WHERE c.OID = 'conditions_summary'::regclass;
SELECT 1
```

**Review by fabriziomello — APPROVED** [review]
Left a minor comment about reformatting SQL but LGTM.

File: sql/size_utils.sql (hunk 1 above)
Comment (pdipesh02) [reply sql/size_utils.sql]: Thanks @fabriziomello, I have formatted the SQL as suggested.
