### PR TITLE
Fix timestamp out of range refreshing CAgg

### LINKED ISSUE #5474: [Bug]: Refreshing C-Agg with timezone (manually or by job) results in (ERROR:  timestamp out of range) if start_offset is NULL. (also reproducible when start_offset and end_offset, both are null)
### What type of bug is this?

Unexpected error

### What subsystems and features are affected?

Continuous aggregate

### What happened?

Refreshing C-Agg with timezone (manually or by job) results in (ERROR:  timestamp out of range) if start_offset is NULL.

The reproducable instructions are attached below.  few observations I wanted to add:
1. It is **also reproducible** when start_offset and end_offset, both are null.
2. If I insert any data (even a single row) into the hyertable before creating the C-Agg(with timezone), the error **isn't reproduced **  .
3. If timezone isn't specified, it **can't be reproduced** as far as I can check

### TimescaleDB version affected

2.10.1

### PostgreSQL version used

PostgreSQL 15.2

### What operating system did you use?

Timescale Cloud

### What installation method did you use?

Other

### What platform did you run on?

Timescale Cloud

### Relevant log output and stack trace

```bash
CALL run_job(:new_job_id);
ERROR:  timestamp out of range

CALL refresh_continuous_aggregate('sensor_summary_daily', NULL, '2023-03-21 05:00:00+00' );
ERROR:  timestamp out of range
```

### How can we reproduce the bug?

```bash
drop table sensor_data cascade;

create table sensor_data( 
time timestamptz not null, 
sensor_id integer not null, 
cpu double precision null,
temperature double precision null );

SELECT create_hypertable('sensor_data','time');

-- if the insert below is executed, the error is not reproducible
-- INSERT into sensor_data (time, sensor_id, cpu, temperature) VALUES (now(), 1, 1.0, 1.0);


--Create CA, with data OR with no data (doesnt matter, both runs into the same error)
CREATE MATERIALIZED VIEW sensor_summary_daily
    WITH (timescaledb.continuous) AS
        SELECT
            time_bucket('1 hour', time, 'AWST')       AS bucket,
            sensor_id,
            avg(cpu)                                        AS avg_cpu
        FROM sensor_data
        GROUP BY bucket, sensor_id
        -- WITH NO DATA
        ;


-- only start_offset is set to NULL
SELECT add_continuous_aggregate_policy('sensor_summary_daily',
    start_offset      => NULL,
    end_offset        => INTERVAL '1 day',
    schedule_interval => INTERVAL '1 MINUTE'
) new_job_id \gset

-- Also runs into the same error. i.e even with start_offset and end_offset, both set to NULL
-- SELECT add_continuous_aggregate_policy('one_day',
--     start_offset      => NULL,
--     end_offset        => NULL,
--     schedule_interval => INTERVAL '1 MINUTE'
-- ) new_job_id \gset

-- first call succeds but see the second fails
CALL run_job(:new_job_id);

-- second call fails with error
CALL run_job(:new_job_id);
ERROR:  timestamp out of range

-- attempting to insert data
INSERT into sensor_data (time, sensor_id, cpu, temperature) VALUES (now(), 1, 1.0, 1.0);

CALL run_job(:new_job_id);
ERROR:  timestamp out of range

CALL refresh_continuous_aggregate('sensor_summary_daily', NULL, '2023-03-21 05:00:00+00' );
ERROR:  timestamp out of range
```

### PR DESCRIPTION
**Pull request by fabriziomello**
When refreshing from the beginning (window_start=NULL) of a
Continuous Aggregate with variable time bucket we were getting a
`timestamp out of range` error.

Fixed it by setting `-Infinity` when passing `window_start=NULL` when
refreshing a Continuous Aggregate with variable time bucket.

Fixes #5474, #5534

### CODE REVIEW

File: tsl/src/continuous_aggs/refresh.c [hunk 1]
```diff
@@ -565,7 +565,9 @@ continuous_agg_refresh(PG_FUNCTION_ARGS)
 													  get_fn_expr_argtype(fcinfo->flinfo, 1),
 													  refresh_window.type);
 	else
-		refresh_window.start = ts_time_get_min(refresh_window.type);
+		refresh_window.start = ts_continuous_agg_bucket_width_variable(cagg) ?
+								   ts_time_get_nobegin_or_min(refresh_window.type) :
+								   ts_time_get_min(refresh_window.type);
```
Comment (mkindahl) [inline tsl/src/continuous_aggs/refresh.c:571]: Don't you need to fix the calls to `ts_time_get_max` below in a similar manner?

**Review by akuzm — APPROVED** [review]
Would be good to add a comment to the code explaining the corner case.

File: tsl/src/continuous_aggs/refresh.c (hunk 1 above)
Comment (fabriziomello) [reply tsl/src/continuous_aggs/refresh.c:571]: I've just aligned this user API call to our internal logic when we create a new cagg don't passing `WITH NO DATA` in the view definition to also refresh the entire cagg: https://github.com/timescale/timescaledb/blob/main/tsl/src/continuous_aggs/create.c#L2929-L2945

**Review by mkindahl — APPROVED** [review]
