### PR TITLE
Fix ON CONFLICT when using prepared statements and functions

### LINKED ISSUE #1086: INSERT from stored procedure fails and causes crash
**Relevant system information:**
 - OS: Arch Linux
 - PostgreSQL version: postgres (PostgreSQL) 11.1
 - TimescaleDB version: 1.2.1
 - Installation method: source
 - GCC: gcc (GCC) 8.2.1 20181127
 - Kernel: 4.20.12-arch1-1-ARCH

**Describe the bug**

While inserting multiple rows into hypertable from stored procedure I get error messages:
```
Execution failed: pq: could not find arbiter index for hypertable index "6_12_ohlc_1m_ts_pkey" on chunk "_hyper_9_6_chunk"
Execution failed: pq: could not find arbiter index for hypertable index "6_12_ohlc_1m_ts_pkey" on chunk "_hyper_9_6_chunk"
Execution failed: pq: could not find arbiter index for hypertable index "6_12_ohlc_1m_ts_pkey" on chunk "_hyper_9_6_chunk"
Execution failed: pq: could not find arbiter index for hypertable index "6_12_ohlc_1m_ts_pkey" on chunk "_hyper_9_6_chunk"
Execution failed: pq: could not find arbiter index for hypertable index "6_12_ohlc_1m_ts_pkey" on chunk "_hyper_9_6_chunk"
Execution failed: pq: could not find arbiter index for hypertable index "6_12_ohlc_1m_ts_pkey" on chunk "_hyper_9_6_chunk"
Execution failed: pq: could not find arbiter index for hypertable index "6_12_ohlc_1m_ts_pkey" on chunk "_hyper_9_6_chunk"
Execution failed: pq: could not find arbiter index for hypertable index "6_12_ohlc_1m_ts_pkey" on chunk "_hyper_9_6_chunk"
```

Same time INSERT outside of stored procedure works as expected.

PostgreSQL crashes if you try to run multiple CALLs via psql command:

```
CALL
CALL
CALL
CALL
CALL
CALL
ERROR:  could not find arbiter index for hypertable index "6_12_ohlc_1m_ts_pkey" on chunk "_hyper_9_6_chunk"
CONTEXT:  SQL statement "INSERT INTO ohlc_1m_ts (
          market_id,
          open_time,
          open,
          high,
          low,
          close,
          volume,
          volume_quote,
          trades,
          closed
  ) VALUES (
          _market_id,
          _open_time,
          _open,
          _high,
          _low,
          _close,
          _volume,
          _volume_quote,
          _trades,
          _closed
  )
  ON CONFLICT (market_id, open_time) DO UPDATE SET
          high = EXCLUDED.high,
          low = EXCLUDED.low,
          close = EXCLUDED.close,
          trades = EXCLUDED.trades,
          volume = EXCLUDED.volume,
          volume_quote = EXCLUDED.volume_quote,
          closed = EXCLUDED.closed"
PL/pgSQL function tick(integer,timestamp with time zone,numeric,numeric,numeric,numeric,numeric,numeric,boolean,integer) line 3 at SQL statement
server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
connection to server was lost
```

System log states that process has crashed:
```
Feb 28 19:01:53 naquads-thinkpad postgres[22157]: 2019-02-28 19:01:53.413 EET [22157] LOG:  server process (PID 20425) was terminated by signal 11: Segmentation fault
Feb 28 19:01:53 naquads-thinkpad postgres[22157]: 2019-02-28 19:01:53.413 EET [22157] DETAIL:  Failed process was running: CALL tick (1, '2019-02-28T19:01:52+02:00'::timestamptz, 0.22228941700678773, 0.6810783123925709, 0.24151508854715265, 0.31152244431052484, 932.846428>
Feb 28 19:01:53 naquads-thinkpad postgres[22157]: 2019-02-28 19:01:53.413 EET [22157] LOG:  terminating any other active server processes
Feb 28 19:01:53 naquads-thinkpad postgres[22157]: 2019-02-28 19:01:53.415 EET [19788] WARNING:  terminating connection because of crash of another server process
Feb 28 19:01:53 naquads-thinkpad postgres[22157]: 2019-02-28 19:01:53.415 EET [19788] DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared me>
Feb 28 19:01:53 naquads-thinkpad postgres[22157]: 2019-02-28 19:01:53.415 EET [19788] HINT:  In a moment you should be able to reconnect to the database and repeat your command.
Feb 28 19:01:53 naquads-thinkpad postgres[22157]: 2019-02-28 19:01:53.416 EET [22157] LOG:  all server processes terminated; reinitializing
Feb 28 19:01:53 naquads-thinkpad postgres[22157]: 2019-02-28 19:01:53.507 EET [20499] LOG:  database system was interrupted; last known up at 2019-02-28 18:52:45 EET
Feb 28 19:01:53 naquads-thinkpad systemd-coredump[20476]: Process 20425 (postgres) of user 88 dumped core.
                                                          
                                                          Stack trace of thread 20425:
                                                          #0  0x00007f66b51e8a88 n/a (timescaledb-1.2.1.so)
                                                          #1  0x00007f66b51e5fe1 n/a (timescaledb-1.2.1.so)
                                                          #2  0x00007f66b51e6318 n/a (timescaledb-1.2.1.so)
                                                          #3  0x0000561f24999290 n/a (postgres)
                                                          #4  0x0000561f24974d0d standard_ExecutorRun (postgres)
                                                          #5  0x0000561f249a892b n/a (postgres)
                                                          #6  0x0000561f249a910d SPI_execute_plan_with_paramlist (postgres)
                                                          #7  0x00007f66b51a4722 n/a (plpgsql.so)
                                                          #8  0x00007f66b51a5883 n/a (plpgsql.so)
                                                          #9  0x00007f66b51a8314 n/a (plpgsql.so)
                                                          #10 0x00007f66b51a880e plpgsql_exec_function (plpgsql.so)
                                                          #11 0x00007f66b519b626 plpgsql_call_handler (plpgsql.so)
                                                          #12 0x0000561f2491c13f ExecuteCallStmt (postgres)
                                                          #13 0x0000561f24ad01e6 standard_ProcessUtility (postgres)
                                                          #14 0x00007f66b51fc277 n/a (timescaledb-1.2.1.so)
                                                          #15 0x0000561f24acd498 n/a (postgres)
                                                          #16 0x0000561f24acdf90 n/a (postgres)
                                                          #17 0x0000561f24aceb9c PortalRun (postgres)
                                                          #18 0x0000561f24acaa7f n/a (postgres)
                                                          #19 0x0000561f24acc364 PostgresMain (postgres)
                                                          #20 0x0000561f24a56ed2 n/a (postgres)
                                                          #21 0x0000561f24a57e23 PostmasterMain (postgres)
                                                          #22 0x0000561f247d911a main (postgres)
                                                          #23 0x00007f66c3410223 __libc_start_main (libc.so.6)
                                                          #24 0x0000561f247d91ce _start (postgres)
```

**To Reproduce**

All referenced files are in https://gist.github.com/naquad/2bab0d268fd347bb6a6b244b74cbfdef

1. Create database `crash`
2. Create extension TimescaleDB
3. Apply db.sql from Gist above
4. Install Go and its PostgreSQL driver (`go get github.com/lib/pq
`)
5. Run writer: `go run writer.go -dsn "dbname=crash user=your-user sslmode=disable"`

INSERT is working: `go run writer.go -insert -dsn "dbname=crash sslmode=disable user=your-user"`

To make sure this is not a Go driver issue:
`go run generator.go -count 10000 | psql -d crash`

And INSERTs are working:
`go run generator.go -count 10000 -insert | psql -d crash`

**Expected behavior**
Both stored procedure invocation and INSERT statement must write data w/o failures or crashes.

**Actual behavior**
Writes from stored procedure are failing and eventually cause segmentation fault in TimescaleDB 1.2.1.

**Additional context**
Same problem has reproduced in Docker image 1.2.1-pg11 and 1.2.0-pg11.

### PR DESCRIPTION
**Pull request by svenklemm**
A prepared statement or function plan can be turned into a generic plan after a couple executions. When this happens the last plan that run through plan creation gets reused so we need to revert any modifications we did to that plan so reusing it is safe.

Fixes #1086

### CODE REVIEW

**Comment by svenklemm** [comment]
Will add tests in 2nd PR that fixes the index lookup.

File: src/chunk_dispatch_state.c [hunk 1]
```diff
@@ -100,12 +99,15 @@ chunk_dispatch_exec(CustomScanState *node)
 				 * (See:
 				 * https://github.com/postgres/postgres/commit/ee0a1fc84eb29c916687dc5bd26909401d3aa8cd).
 				 */
+				MemoryContextSwitchTo(estate->es_query_cxt);
```
Comment (cevian) [inline src/chunk_dispatch_state.c]: I think it's better to use `old = MemoryContextSwitchTo(estate->es_query_cxt); ... MemoryContextSwitchTo(old);` idiom instead of assuming the old context was `GetPerTupleMemoryContext(estate)`

Comment (svenklemm) [reply src/chunk_dispatch_state.c]: i disagree with using old here, we switch to per tuple context explicitly on line 69 above in the same function, if i were to follow your advice i would have to introduce 2nd memorycontext variable which would not improve the code imo

Comment (cevian) [reply src/chunk_dispatch_state.c]: Ah you are right. Did not see the code above

**Comment by svenklemm** [comment]
its a list of oids so deep copy doesn't add anything

File: src/chunk_dispatch_state.c (hunk 1 above)
Comment (gayyappan) [inline src/chunk_dispatch_state.c]: I don't quite understand this change : ts_chunk_dispatch_get_chunk_insert_state allocates everything i in qry_context. So   cis->arbiter_indexes should already be in the qry_context. what causes the failure here?

File: test/expected/insert.out [hunk 2]
```diff
@@ -755,3 +755,46 @@ SELECT 1 \g | grep -v "Planning" | grep -v "Execution"
                        ->  Result (actual rows=1 loops=1)
 (8 rows)
 
+-- test ON CONFLICT with prepared statements and functions
```
Comment (cevian) [inline test/expected/insert.out]: I think this belongs in upsert.sql. Also It's better to have both excluded.X plus table.X in the upsert clause (you'll see a lot of examples in upsert.sql). Finally, I'd like to see the resulting table rows via a select (we've seen weird behavior before that's caught by simple selects).
