### PR TITLE
Fix UPSERT with prepared statements

### LINKED ISSUE #1165: Segmentation fault,"Failed process was running: insert hypertable"
**Relevant system information:**
 - OS: [SUSE 12]
 - PostgreSQL version (output of `postgres --version`): 11.2
 - TimescaleDB version (output of `\dx` in `psql`):1.2.2
 - Installation method: "source"

**Describe the bug**
error log:
2019-04-12 13:00:21.795 UTC,,,284641,,5cb037a2.457e1,6,,2019-04-12 07:00:50 UTC,,0,LOG,00000,"server process (PID 253718) was terminated by signal 11: Segmentation fault","Failed process was running: insert into t_mpp_11120_1d_rx0l3p_0(time,entity_id,ind_030ix5z4n,ind_03vfryh7a,ind_04apng40b,ind_05aa4w885,ind_05n4v6dpm,ind_05qpaty18,ind_05rkbs2ri,ind_09rvbyr2y,ind_0au4x42mk,ind_0b4g17rpg,ind_0cibtjd1m) select U0.time as time,U0.entity_id as entity_id,U0.ind_030ix5z4n as ind_030ix5z4n,U0.ind_03vfryh7a as ind_03vfryh7a,U0.ind_04apng40b as ind_04apng40b,U0.ind_05aa4w885 as ind_05aa4w885,U0.ind_05n4v6dpm as ind_05n4v6dpm,U0.ind_05qpaty18 as ind_05qpaty18,U0.ind_05rkbs2ri as ind_05rkbs2ri,U0.ind_09rvbyr2y as ind_09rvbyr2y,U0.ind_0au4x42mk as ind_0au4x42mk,U0.ind_0b4g17rpg as ind_0b4g17rpg,U0.ind_0cibtjd1m as ind_0cibtjd1m from (select t01.destination_instance as entity_id,dw_common.time_floor(t00.time,'30m') as time,avg(t00.ind_030ix5z4n) as ind_030ix5z4n,avg(t00.ind_03vfryh7a) as ind_03vfryh7a,avg(t00.ind_04apng40b) as ind_04apng40b,avg(t00.ind_05aa4w885) as ind_05aa4w885,avg(t00.ind_05n4v6dpm) as ind_05n4v6dpm,avg(t00.ind_05qpaty18) as ind_05qpaty18,avg(t00.ind_05rkbs2ri) as ind_05rkbs2ri,avg(t00.ind_09rvby",,,,,,,,""

coredump with gdb:
(gdb) where
#0 0x00007fec434cbd90 in ts_chunk_insert_state_create () from /opt/tsdb/pgsql/lib/timescaledb-1.2.2.so
#1 0x00007fec434c951f in ts_chunk_dispatch_get_chunk_insert_state () from /opt/tsdb/pgsql/lib/timescaledb-1.2.2.so
#2 0x00007fec434c98a4 in chunk_dispatch_exec () from /opt/tsdb/pgsql/lib/timescaledb-1.2.2.so
#3 0x000000000062704b in ExecModifyTable ()
#4 0x0000000000604daa in standard_ExecutorRun ()
#5 0x00007feec385a2f5 in pgss_ExecutorRun () from /opt/tsdb/pgsql/lib/pg_stat_statements.so
#6 0x000000000073cada in ProcessQuery ()
#7 0x000000000073cd01 in PortalRunMulti ()
#8 0x000000000073d7bc in PortalRun ()
#9 0x000000000073b2cd in PostgresMain ()
#10 0x000000000048e399 in ServerLoop ()
#11 0x00000000006d1eda in PostmasterMain ()
#12 0x000000000048edef in main ()

**To Reproduce**
USE TimescaleDB create hypertable , then in postgres the table like this:

CREATE TABLE dw_ies.t_mpp_11182_1d_ejki0_0
(
    "time" timestamp with time zone NOT NULL,
    entity_id text COLLATE pg_catalog."default" NOT NULL,
    ind_042lgvatg numeric(25,5),
    CONSTRAINT t_mpp_11182_1d_ejki0_0_pkey PRIMARY KEY ("time", entity_id)
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE dw_ies.t_mpp_11182_1d_ejki0_0
    OWNER to dw_ies;

CREATE INDEX t_mpp_11182_1d_ejki0_0_time_idx
    ON dw_ies.t_mpp_11182_1d_ejki0_0 USING btree
    ("time" DESC)
    TABLESPACE pg_default;

CREATE TRIGGER ts_insert_blocker
    BEFORE INSERT
    ON dw_ies.t_mpp_11182_1d_ejki0_0
    FOR EACH ROW
    EXECUTE PROCEDURE _timescaledb_internal.insert_blocker();

When a large amount of data is inserted and chunks are automatically created, the database sometimes crashes.

### PR DESCRIPTION
**Pull request by svenklemm**
When doing upsert with prepared statement the code to restore
arbiter_indexes would not trigger when an error occurred on the
INSERT leading to a segfault on the next EXECUTE of the prepared
statement.

Fixes #1165

### CODE REVIEW

File: src/chunk_dispatch_state.c [hunk 1]
```diff
@@ -158,17 +158,6 @@ chunk_dispatch_end(CustomScanState *node)
 	ExecEndNode(substate);
```
Comment (cevian) [inline src/chunk_dispatch_state.c]: There is a now-outdated comment at line 245 of this file.

Comment (cevian) [reply src/chunk_dispatch_state.c]: starts with "Save arbiterIndexes..."
