### PR TITLE
Fix chunks_in queries to use ChunkAppend plans

### LINKED ISSUE #2733: multi-node: extremely slow query plan when ordering by time
**Relevant system information:**
 - OS: Debian 9
 - PostgreSQL version (output of `postgres --version`): postgres (PostgreSQL) 12.4 (Debian 12.4-1.pgdg90+1)
 - TimescaleDB version (output of `\dx` in `psql`): timescaledb | 2.0.0-rc4
 - Installation method: apt from packagecloud.io

**Describe the bug**
When performing a query across multiple data nodes and ordering the result by time, the query is extremely slow.

**To Reproduce**
The cluster this was tested on has 2 nodes. The hypertable has a replication factor of 2, and 2 partitions.
```
select * from haproxy order by time desc limit 5;
```

**Expected behavior**
fast response

**Actual behavior**
slow response (several minutes)
```
Time: 246859.604 ms (04:06.860)
```

**Additional context**
The intent of the query is to sample some of the recent data in the table.

When running this query across each of the data nodes, the response comes back instantly (~13ms). When running it on the access node is when there is a problem.

Access node:
```
# explain select * from haproxy order by time desc limit 5;
                                                     QUERY PLAN                                                      
---------------------------------------------------------------------------------------------------------------------
 Limit  (cost=200.01..200.82 rows=5 width=920)
   ->  Custom Scan (AsyncAppend)  (cost=200.01..2164357.50 rows=13400706 width=920)
         ->  Merge Append  (cost=200.01..2164357.50 rows=13400706 width=920)
               Sort Key: haproxy_1."time" DESC
               ->  Custom Scan (DataNodeScan) on haproxy haproxy_1  (cost=100.00..1015175.21 rows=6700353 width=920)
               ->  Custom Scan (DataNodeScan) on haproxy haproxy_2  (cost=100.00..1015175.21 rows=6700353 width=920)
```

Data node:
```
# explain select * from haproxy order by time desc limit 5;
                                                                      QUERY PLAN                                                                       
-------------------------------------------------------------------------------------------------------------------------------------------------------
 Limit  (cost=0.88..1.31 rows=5 width=763)
   ->  Custom Scan (ChunkAppend) on haproxy  (cost=0.88..785017.84 rows=9084534 width=763)
         Order: haproxy."time" DESC
         ->  Merge Append  (cost=0.88..785017.84 rows=9084534 width=763)
               Sort Key: _dist_hyper_6_19_chunk."time" DESC
               ->  Index Scan using _dist_hyper_6_19_chunk_haproxy_time_idx on _dist_hyper_6_19_chunk  (cost=0.43..344760.36 rows=4513676 width=764)
               ->  Index Scan using _dist_hyper_6_18_chunk_haproxy_time_idx on _dist_hyper_6_18_chunk  (cost=0.43..349412.13 rows=4570858 width=763)
         ->  Merge Append  (cost=0.88..2492282.50 rows=29122564 width=763)
               Sort Key: _dist_hyper_6_17_chunk."time" DESC
               ->  Index Scan using _dist_hyper_6_17_chunk_haproxy_time_idx on _dist_hyper_6_17_chunk  (cost=0.43..1109083.65 rows=14666032 width=763)
               ->  Index Scan using _dist_hyper_6_16_chunk_haproxy_time_idx on _dist_hyper_6_16_chunk  (cost=0.43..1091973.21 rows=14456532 width=764)
         ->  Merge Append  (cost=511439.59..1353779.86 rows=76689000 width=763)
               Sort Key: _dist_hyper_6_15_chunk."time" DESC
               ->  Sort  (cost=0.00..0.00 rows=0 width=0)
                     Sort Key: _dist_hyper_6_15_chunk."time" DESC
                     ->  Sort  (cost=639514.03..735009.03 rows=38198000 width=763)
                           Sort Key: _dist_hyper_6_15_chunk."time" DESC
                           ->  Custom Scan (DecompressChunk) on _dist_hyper_6_15_chunk  (cost=0.13..5058.98 rows=38198000 width=763)
                                 ->  Seq Scan on compress_hyper_8_37_chunk  (cost=0.00..5058.98 rows=38198 width=2908)
               ->  Sort  (cost=0.00..0.00 rows=0 width=0)
                     Sort Key: _dist_hyper_6_14_chunk."time" DESC
                     ->  Sort  (cost=644421.58..740649.08 rows=38491000 width=764)
                           Sort Key: _dist_hyper_6_14_chunk."time" DESC
                           ->  Custom Scan (DecompressChunk) on _dist_hyper_6_14_chunk  (cost=0.13..5099.91 rows=38491000 width=764)
                                 ->  Seq Scan on compress_hyper_8_36_chunk  (cost=0.00..5099.91 rows=38491 width=2908)
         ->  Merge Append  (cost=487419.16..1329378.36 rows=77015000 width=763)
               Sort Key: _dist_hyper_6_13_chunk."time" DESC
               ->  Sort  (cost=0.00..0.00 rows=0 width=0)
                     Sort Key: _dist_hyper_6_13_chunk."time" DESC
                     ->  Sort  (cost=642865.48..738850.48 rows=38394000 width=763)
                           Sort Key: _dist_hyper_6_13_chunk."time" DESC
                           ->  Custom Scan (DecompressChunk) on _dist_hyper_6_13_chunk  (cost=0.13..5154.94 rows=38394000 width=763)
                                 ->  Seq Scan on compress_hyper_8_35_chunk  (cost=0.00..5154.94 rows=38394 width=2908)
               ->  Sort  (cost=0.00..0.00 rows=0 width=0)
                     Sort Key: _dist_hyper_6_12_chunk."time" DESC
                     ->  Sort  (cost=646655.13..743207.63 rows=38621000 width=764)
                           Sort Key: _dist_hyper_6_12_chunk."time" DESC
                           ->  Custom Scan (DecompressChunk) on _dist_hyper_6_12_chunk  (cost=0.13..5174.21 rows=38621000 width=764)
                                 ->  Seq Scan on compress_hyper_8_34_chunk  (cost=0.00..5174.21 rows=38621 width=2908)
         ->  Merge Append  (cost=637159.47..1505301.58 rows=77377000 width=763)
               Sort Key: _dist_hyper_6_11_chunk."time" DESC
               ->  Sort  (cost=0.00..0.00 rows=0 width=0)
                     Sort Key: _dist_hyper_6_11_chunk."time" DESC
                     ->  Sort  (cost=644792.07..741082.07 rows=38516000 width=764)
                           Sort Key: _dist_hyper_6_11_chunk."time" DESC
                           ->  Custom Scan (DecompressChunk) on _dist_hyper_6_11_chunk  (cost=0.13..5055.16 rows=38516000 width=764)
                                 ->  Seq Scan on compress_hyper_8_33_chunk  (cost=0.00..5055.16 rows=38516 width=2908)
               ->  Sort  (cost=0.00..0.00 rows=0 width=0)
                     Sort Key: _dist_hyper_6_10_chunk."time" DESC
                     ->  Sort  (cost=650576.85..747729.35 rows=38861000 width=764)
                           Sort Key: _dist_hyper_6_10_chunk."time" DESC
                           ->  Custom Scan (DecompressChunk) on _dist_hyper_6_10_chunk  (cost=0.13..5109.61 rows=38861000 width=764)
                                 ->  Seq Scan on compress_hyper_8_32_chunk  (cost=0.00..5109.61 rows=38861 width=2908)
         ->  Merge Append  (cost=536173.87..1391711.43 rows=77638000 width=763)
               Sort Key: _dist_hyper_6_9_chunk."time" DESC
               ->  Sort  (cost=0.00..0.00 rows=0 width=0)
                     Sort Key: _dist_hyper_6_9_chunk."time" DESC
                     ->  Sort  (cost=647553.07..744250.57 rows=38679000 width=764)
                           Sort Key: _dist_hyper_6_9_chunk."time" DESC
                           ->  Custom Scan (DecompressChunk) on _dist_hyper_6_9_chunk  (cost=0.13..5108.79 rows=38679000 width=764)
                                 ->  Seq Scan on compress_hyper_8_31_chunk  (cost=0.00..5108.79 rows=38679 width=2908)
               ->  Sort  (cost=0.00..0.00 rows=0 width=0)
                     Sort Key: _dist_hyper_6_8_chunk."time" DESC
                     ->  Sort  (cost=652248.57..749646.07 rows=38959000 width=764)
                           Sort Key: _dist_hyper_6_8_chunk."time" DESC
                           ->  Custom Scan (DecompressChunk) on _dist_hyper_6_8_chunk  (cost=0.13..5153.59 rows=38959000 width=764)
                                 ->  Seq Scan on compress_hyper_8_30_chunk  (cost=0.00..5153.59 rows=38959 width=2908)
         ->  Merge Append  (cost=3540482.87..6537550.57 rows=246914000 width=763)
               Sort Key: _dist_hyper_6_7_chunk."time" DESC
               ->  Sort  (cost=0.00..0.00 rows=0 width=0)
                     Sort Key: _dist_hyper_6_7_chunk."time" DESC
                     ->  Sort  (cost=2055906.65..2362881.65 rows=122790000 width=763)
                           Sort Key: _dist_hyper_6_7_chunk."time" DESC
                           ->  Custom Scan (DecompressChunk) on _dist_hyper_6_7_chunk  (cost=0.13..16408.90 rows=122790000 width=763)
                                 ->  Seq Scan on compress_hyper_8_23_chunk  (cost=0.00..16408.90 rows=122790 width=2908)
               ->  Sort  (cost=0.00..0.00 rows=0 width=0)
                     Sort Key: _dist_hyper_6_6_chunk."time" DESC
                     ->  Sort  (cost=2078253.25..2388563.25 rows=124124000 width=763)
                           Sort Key: _dist_hyper_6_6_chunk."time" DESC
                           ->  Custom Scan (DecompressChunk) on _dist_hyper_6_6_chunk  (cost=0.13..16598.24 rows=124124000 width=763)
                                 ->  Seq Scan on compress_hyper_8_22_chunk  (cost=0.00..16598.24 rows=124124 width=2908)
(81 rows)
```

Also note that removing the `order by time desc` on the access node causes it to take only ~300ms

### PR DESCRIPTION
**Pull request by nikkhils**
It was observed on DNs that "ORDER BY time" queries when the
"chunks_in" exclusion function was specified were running slower than
expected.

Examination of the EXPLAIN output revealed that when "chunks_in" was
specified then the ChunkAppend plan which provides the exclusion of
unwanted chunks was not getting picked up for execution.

Logic in get_explicit_chunk_oids() function has now been improved to
populate the fdw_private structure appropriately if ordering info is
present. Care has been taken to also handle the case where multiple
dimensions are present.

Fixes #2733

### CODE REVIEW

**Review by erimatnor — COMMENTED** [review]
A couple of quick notes before I do full review:

* Would be good to reference the issue in the commit message (i.e., Fixes #xyz)
* Also fill in CHANGELOG listing the fix and Thanks to issue reporter

**Review by svenklemm — COMMENTED** [review]
i think this needs more tests, in particular queries on AN with remote explain  on to make sure it works as expected

**Comment by nikkhils** [comment]
> * Would be good to reference the issue in the commit message (i.e., Fixes #xyz)

Done.

> * Also fill in CHANGELOG listing the fix and Thanks to issue reporter

Done,

**Comment by nikkhils** [comment]
> i think this needs more tests, in particular queries on AN with remote explain on to make sure it works as expected

Added the EXPLAIN output on the AN and verified that that is the exact chunks_in query that gets executed on that appropriate DN.

File: src/hypertable_restrict_info.c [hunk 1]
```diff
@@ -607,23 +607,36 @@ chunk_cmp_reverse(const void *c1, const void *c2)
...
 	unsigned int i;
 
+	if (chunks_in == NULL)
+		chunks = hypertable_restrict_info_get_chunks(hri, ht, lockmode, &num_chunks);
+	else
+	{
+		chunks = chunks_in;
+		Assert(nchunks != 0);
+		num_chunks = nchunks;
+	}
```
Comment (erimatnor) [inline src/hypertable_restrict_info.c:638]:
```suggestion
	if (chunks == NULL)
		chunks = hypertable_restrict_info_get_chunks(hri, ht, lockmode, &num_chunks);

	Assert(num_chunks != 0);
```

File: src/hypertable_restrict_info.c [hunk 2]
```diff
@@ -607,23 +607,36 @@ chunk_cmp_reverse(const void *c1, const void *c2)
...
  */
 List *
 ts_hypertable_restrict_info_get_chunk_oids_ordered(HypertableRestrictInfo *hri, Hypertable *ht,
+												   Chunk **chunks_in, unsigned int nchunks,
 												   LOCKMODE lockmode, List **nested_oids,
 												   bool reverse)
 {
 	unsigned num_chunks;
-	Chunk **chunks = hypertable_restrict_info_get_chunks(hri, ht, lockmode, &num_chunks);
+	Chunk **chunks;
```
Comment (erimatnor) [inline src/hypertable_restrict_info.c:625]: Do we need these two extra variables?

It would probably be sufficient to use the passed in parameters (see example code changes).

```suggestion
	
```

File: src/hypertable_restrict_info.c [hunk 3]
```diff
@@ -607,23 +607,36 @@ chunk_cmp_reverse(const void *c1, const void *c2)
...
+ * restrict ourselves to the passed in chunks list.
+ *
  * nested_oids is a list of lists, chunks that occupy the same time slice will be
  * in the same list. In the list [[1,2,3],[4,5,6]] chunks 1, 2 and 3 are space partitions of
  * the same time slice and 4, 5 and 6 are space partitions of the next time slice.
  *
  */
 List *
 ts_hypertable_restrict_info_get_chunk_oids_ordered(HypertableRestrictInfo *hri, Hypertable *ht,
+												   Chunk **chunks_in, unsigned int nchunks,
```
Comment (erimatnor) [inline src/hypertable_restrict_info.c:620]:
```suggestion
												   Chunk **chunks, unsigned int num_chunks,
```

File: src/hypertable_restrict_info.h [hunk 4]
```diff
@@ -26,7 +26,9 @@ extern List *ts_hypertable_restrict_info_get_chunk_oids(HypertableRestrictInfo *
 														LOCKMODE lockmode);
 
 extern List *ts_hypertable_restrict_info_get_chunk_oids_ordered(HypertableRestrictInfo *hri,
-																Hypertable *ht, LOCKMODE lockmode,
+																Hypertable *ht, Chunk **chunks_in,
+																unsigned int nchunks,
```
Comment (erimatnor) [inline src/hypertable_restrict_info.h:30]:
```suggestion
																Hypertable *ht, Chunk **chunks,
																unsigned int num_chunks,
```

File: src/plan_expand_hypertable.c [hunk 5]
```diff
@@ -945,11 +954,56 @@ get_explicit_chunk_oids(CollectQualCtx *ctx, Hypertable *ht)
...
+
+			num_chunks++;
+
+			if (chunks == NULL)
+			{
+				Assert(num_chunks == 1);
+				chunks = (Chunk **) palloc0(sizeof(Chunk *));
+			}
+			else
+				chunks = (Chunk **) repalloc(chunks, sizeof(Chunk *) * num_chunks);
```
Comment (erimatnor) [inline src/plan_expand_hypertable.c:966]: It looks like this will reallocate memory for every chunk. Since the number of chunks is known a priori, I suggest allocating the exact size array outside the loop:

```
ArrayType *arr = DatumGetArrayTypeP(chunks_arg->constvalue);

if (ARR_NDIM(arr) != 1)
    ereport(ERROR,
                 (errcode(ERRCODE_INVALID_PARAMETER_VALUE),
                  errmsg("invalid number of array dimensions for chunks_in")));

chunks = palloc0(sizeof(Chunk *) * ArrayGetNItems(ARR_NDIM(arr), ARR_DIMS(arr));
```

**Review by erimatnor — COMMENTED** [review]
A couple of more suggestions for code clarity. Moving on to looking at tests.

File: tsl/test/expected/dist_hypertable-11.out [hunk 6]
```diff
@@ -552,6 +552,61 @@ FROM disttable;
...
+                             Remote SQL: SELECT "time" FROM public.disttable WHERE _timescaledb_internal.chunks_in(public.disttable.*, ARRAY[2, 1]) AND (("time" IS NOT NULL)) ORDER BY "time" DESC NULLS FIRST LIMIT 1
+                       ->  Custom Scan (DataNodeScan) on public.disttable disttable_3
+                             Output: disttable_3."time"
+                             Data node: db_dist_hypertable_3
+                             Chunks: _dist_hyper_1_6_chunk, _dist_hyper_1_2_chunk
+                             Remote SQL: SELECT "time" FROM public.disttable WHERE _timescaledb_internal.chunks_in(public.disttable.*, ARRAY[2, 1]) AND (("time" IS NOT NULL)) ORDER BY "time" DESC NULLS FIRST LIMIT 1
+(24 rows)
+
+-- Test that Remote Query (obtained in above output) on DN directly uses ChunkAppend plan
+\c :DATA_NODE_3
```
Comment (erimatnor) [inline tsl/test/expected/dist_hypertable-11.out:587]: There's a GUC, `timescaledb.enable_remote_explain` you can set to show the remote query plan for each data node as part of the access node explain. It might be better to use that in the original AN explain so that we know for sure that the right DN plan is executed when we do the query from the AN. If it gets messy, you can include an extra condition to hit, e.g., just one data node.

Another option is to include `\ir include/remote_exec.sql` which gives you the function `test.remote_exec()` that you can use in the text to execute statements on DNs from the AN. This avoids having to connect to the DN in a new session. Creating new sessions in tests make it harder to run the script in, e.g., a debugger if one should need to do that.

File: tsl/test/expected/dist_hypertable-11.out [hunk 7]
```diff
@@ -2503,7 +2558,54 @@ INSERT INTO twodim VALUES
...
+               Chunks: _dist_hyper_7_19_chunk, _dist_hyper_7_21_chunk, _dist_hyper_7_24_chunk
+               Remote SQL: SELECT "time", "Color", temp FROM public.twodim WHERE _timescaledb_internal.chunks_in(public.twodim.*, ARRAY[10, 11, 13]) ORDER BY "time" ASC NULLS LAST
+         ->  Custom Scan (DataNodeScan) on public.twodim twodim_3
+               Output: twodim_3."time", twodim_3."Color", twodim_3.temp
+               Data node: db_dist_hypertable_3
+               Chunks: _dist_hyper_7_20_chunk, _dist_hyper_7_23_chunk
+               Remote SQL: SELECT "time", "Color", temp FROM public.twodim WHERE _timescaledb_internal.chunks_in(public.twodim.*, ARRAY[10, 12]) ORDER BY "time" ASC NULLS LAST
+(19 rows)
+
+\c :DATA_NODE_1
```
Comment (erimatnor) [inline tsl/test/expected/dist_hypertable-11.out:2588]: Same here as above regarding including remote explain in the query plan.

File: src/hypertable_restrict_info.c (hunk 1 above)
Comment (nikkhils) [reply src/hypertable_restrict_info.c:638]: Not sure I follow @erimatnor, we have to either used the passed in `chunks_in` array or generate it. "chunks" is a local variable which needs to be assigned to the array. We cannot check for "chunks == NULL" above.

File: src/plan_expand_hypertable.c (hunk 5 above)
Comment (nikkhils) [reply src/plan_expand_hypertable.c:966]: The while loop checks for `isnull` for each entry in the array. That's the reason I did a repalloc. But yeah, can palloc like above and adjust the `num_chunks` in the loop appropriately

Comment (erimatnor) [reply src/plan_expand_hypertable.c:966]: Also, `isnull=true` is an error condition so `num_chunks` shouldn't need adjustment. It might still make sense to increment it in the loop though.

File: src/hypertable_restrict_info.c (hunk 1 above)
Comment (nikkhils) [reply src/hypertable_restrict_info.c:638]: Done.

File: src/hypertable_restrict_info.c (hunk 2 above)
Comment (nikkhils) [reply src/hypertable_restrict_info.c:625]: Done

File: src/hypertable_restrict_info.c (hunk 3 above)
Comment (nikkhils) [reply src/hypertable_restrict_info.c:620]: Done

File: src/hypertable_restrict_info.h (hunk 4 above)
Comment (nikkhils) [reply src/hypertable_restrict_info.h:30]: Done

File: tsl/test/expected/dist_hypertable-11.out (hunk 6 above)
Comment (nikkhils) [reply tsl/test/expected/dist_hypertable-11.out]: Thanks. Used the `timescaledb.enable_remote_explain` GUC and removed all connections to datanode etc.

File: src/plan_expand_hypertable.c [hunk 8]
```diff
@@ -925,8 +935,16 @@ get_explicit_chunk_oids(CollectQualCtx *ctx, Hypertable *ht)
 	/* function marked as STRICT so argument can't be NULL */
 	Assert(!chunks_arg->constisnull);
 
-	chunk_id_iterator = array_create_iterator(DatumGetArrayTypeP(chunks_arg->constvalue), 0, NULL);
+	chunk_id_arr = DatumGetArrayTypeP(chunks_arg->constvalue);
+	if (ARR_NDIM(chunk_id_arr) != 1)
```
Comment (erimatnor) [inline src/plan_expand_hypertable.c:939]: Could you add a test case for this?

**Review by erimatnor — APPROVED** [review]
One minor ask/nit.

**Review by svenklemm — APPROVED** [review]
