### PR TITLE
Fix wrong result when using a mutable clause with chunk exclusion

### LINKED ISSUE #9387: [Bug]: : Incorrect query results on hypertable when filtering timestamptz column with ::date cast
### What type of bug is this?

Incorrect result

### What subsystems and features are affected?

Query planner

### What happened?

Relevant system information
TimescaleDB version: 2.25.2
PostgreSQL version: 17.9
OS: Debian 13

Bug description
When executing a SELECT query on a hypertable with a timestamptz time column, using an explicit ::date cast in the WHERE clause (start_stamp < '2026-03-01'::date) results in incorrect data being returned. 

The query ignores the upper boundary condition and returns rows from beyond the specified date limit (up to the end of the chunk). If the string is not explicitly cast to ::date, the query returns the correct boundaries.

Additionally, "SET timescaledb.enable_qual_filtering =off;" "fixing" the issue.

CORRECT query result  (without explicit ::date cast)
SELECT 
    min(start_stamp), 
    max(start_stamp)
FROM example 
WHERE start_stamp >= '2026-02-01' AND start_stamp < '2026-03-01';

          min                           |             max             
--------------------------+-----------------------------
 2026-02-01 01:00:00+01   | 2026-02-28 01:00:00+01
INCORRECT query result (with explicit ::date cast)
SELECT 
    min(start_stamp), 
    max(start_stamp)
FROM example 
WHERE start_stamp >= '2026-02-01' AND start_stamp < '2026-03-01'::date;
          min                            |             max             
--------------------------+-----------------------------
 2026-02-01 01:00:00+01   | 2026-03-04 01:00:00+01

### TimescaleDB version affected

2.25.2

### PostgreSQL version used

17.9

### What operating system did you use?

Debian 13

### What installation method did you use?

Deb/Apt

### What platform did you run on?

On prem/Self-hosted

### Relevant log output and stack trace

```bash

```

### How can we reproduce the bug?

```bash
-- 1. Create table and convert to hypertable
CREATE TABLE example (
    id SERIAL,
    start_stamp TIMESTAMPTZ NOT NULL
);

SELECT create_hypertable(
    'example', 
    'start_stamp', 
    chunk_time_interval => INTERVAL '7 days'
);

-- 2. Insert test data
INSERT INTO example (start_stamp)
SELECT generate_series(
    '2026-01-01 00:00:00+00'::timestamptz,
    '2026-03-10 00:00:00+00'::timestamptz,
    '1 day'::interval
);

-- 3. Execute CORRECT query (without explicit ::date cast)
SELECT 
    min(start_stamp), 
    max(start_stamp)
FROM example 
WHERE start_stamp >= '2026-02-01' AND start_stamp < '2026-03-01';

          min                           |             max             
--------------------------+-----------------------------
 2026-02-01 01:00:00+01   | 2026-02-28 01:00:00+01

-- 4. Execute INCORRECT query (with explicit ::date cast)
SELECT 
    min(start_stamp), 
    max(start_stamp)
FROM example 
WHERE start_stamp >= '2026-02-01' AND start_stamp < '2026-03-01'::date;
          min                            |             max             
--------------------------+-----------------------------
 2026-02-01 01:00:00+01   | 2026-03-04 01:00:00+01
```

### PR DESCRIPTION
**Pull request by akuzm**
We didn't use all the proper conditions when determining whether a clause is proven true by the hypertable restriction info and therefore can be removed. This led to removing a clause which is in fact not true for every row of a chunk, leading to wrong query results. Track which clauses are proven true as we build the hypertable restrictions, to avoid the potential discrepancies.

Fixes: https://github.com/timescale/timescaledb/issues/9387

### CODE REVIEW

File: src/planner/expand_hypertable.c [hunk 1]
```diff
@@ -1343,47 +1329,58 @@ ts_plan_expand_hypertable_chunks(Hypertable *ht, PlannerInfo *root, RelOptInfo *
...
-		bool can_clear_restrictinfo = false;
-		Index child_rtindex = first_chunk_index + i;
+		const Index child_rtindex = first_chunk_index + i;
 		Chunk *chunk = chunks[i];
-		if (try_restriction_filtering)
-		{
-			can_clear_restrictinfo = chunk_fully_covered(hri, chunk);
-		}
+
+		const bool can_remove_quals_proven_try_by_hri =
```
Comment (svenklemm) [inline src/planner/expand_hypertable.c]:
```suggestion
		const bool can_remove_quals_proven_true_by_hri =
```

File: src/planner/expand_hypertable.c [hunk 2]
```diff
@@ -1343,47 +1329,58 @@ ts_plan_expand_hypertable_chunks(Hypertable *ht, PlannerInfo *root, RelOptInfo *
...
+			try_remove_quals_proven_true_by_hri && chunk_fully_covered(hri, chunk);
 
 		/* build_simple_rel will copy baserestrictinfo to the child rel and
 		 * do the necessary attribute mapping. If we can determine that the chunk
 		 * is fully covered by the primary dimension restriction we can remove
 		 * primary dimension restrictions from baserestrictinfo.
 		 */
-		if (can_clear_restrictinfo)
-			rel->baserestrictinfo = filtered_restrictions;
+		if (can_remove_quals_proven_try_by_hri)
```
Comment (svenklemm) [inline src/planner/expand_hypertable.c]:
```suggestion
		if (can_remove_quals_proven_true_by_hri)
```

File: src/planner/expand_hypertable.c [hunk 3]
```diff
@@ -1343,47 +1329,58 @@ ts_plan_expand_hypertable_chunks(Hypertable *ht, PlannerInfo *root, RelOptInfo *
...
+			ht_rel->baserestrictinfo = quals_possibly_false_inside_hri;
+		}
 
 		/* build_simple_rel will add the child to the relarray */
-		RelOptInfo *child_rel = build_simple_rel(root, child_rtindex, rel);
+		RelOptInfo *child_rel = build_simple_rel(root, child_rtindex, ht_rel);
 
-		if (can_clear_restrictinfo)
-			rel->baserestrictinfo = base_restrictions;
+		if (can_remove_quals_proven_try_by_hri)
```
Comment (svenklemm) [inline src/planner/expand_hypertable.c]:
```suggestion
		if (can_remove_quals_proven_true_by_hri)
```

**Review by svenklemm — APPROVED** [review]

**Review by dbeck — APPROVED** [review]
