### PR TITLE
Fix segfault for RelOptInfo without fdw_private

### LINKED ISSUE #3391: Segfault in apply_optimizations
**Relevant system information:**
 - OS: CentOS 7.6
 - PostgreSQL version (output of `postgres --version`): 12.4
 - TimescaleDB version (output of `\dx` in `psql`): verified on 2.2.1 & master
 - Installation method: source

**Describe the bug**

```
create table t1 (a int, b int);
select create_hypertable('t1', 'b', chunk_time_interval=>10);

create table t2 (a int, b int);
select create_hypertable('t2', 'b', chunk_time_interval=>10);

CREATE OR REPLACE FUNCTION f_t1(_a int, _b int)
 RETURNS SETOF t1
 LANGUAGE sql
 STABLE PARALLEL SAFE
AS $function$
   SELECT DISTINCT ON (a) *
   FROM t1
   WHERE
      a = _a and b = _b
   ORDER BY a, b DESC
$function$
;

CREATE OR REPLACE FUNCTION f_t2(_a int, _b int)
 RETURNS SETOF t2
 LANGUAGE sql
 STABLE PARALLEL SAFE
AS $function$
   SELECT DISTINCT ON (j.a) j.*
   FROM
      f_t1(_a, _b) sc,
      t2 j
   WHERE
      j.b = _b AND 
      j.a = _a
   ORDER BY j.a, j.b DESC
$function$
;

CREATE OR REPLACE FUNCTION f_t1_2(_b int)
 RETURNS SETOF t1
 LANGUAGE sql
 STABLE PARALLEL SAFE
AS $function$
   SELECT DISTINCT ON (j.a) jt.*
   FROM
      t1 j,
      f_t1(j.a, _b) jt
$function$
;

-- this segfaults
explain 
SELECT *
   FROM 
      f_t1_2(10) sc,
      f_t2(sc.a, 10)
   ;
```

Likely related is that even a function call that does not segfault, does not exclude the parent chunk, **if** nothing has been inserted to the table before. Once insert+truncate happened, the plan looks much better. After insert+truncate, the query above also doesn't segfault anymore.

```
-- first run all the queries above again to recreate the tables t1 and t2 (except the one that segfaults)
-- then run:
postgres=# explain select * from f_t1(5,5);
                                  QUERY PLAN                                  
------------------------------------------------------------------------------
 Unique  (cost=4.24..14.94 rows=1 width=8)
   ->  Bitmap Heap Scan on t1  (cost=4.24..14.94 rows=1 width=8)
         Recheck Cond: (b = 5)
         Filter: (a = 5)
         ->  Bitmap Index Scan on t1_b_idx  (cost=0.00..4.24 rows=11 width=0)
               Index Cond: (b = 5)
(6 rows)
postgres=# insert into t1 (values (1,2));
INSERT 0 1
postgres=# truncate t1;
TRUNCATE TABLE
postgres=# explain select * from f_t1(5,5);
                   QUERY PLAN                   
------------------------------------------------
 Unique  (cost=0.00..0.00 rows=1 width=8)
   ->  Result  (cost=0.00..0.00 rows=0 width=0)
         One-Time Filter: false
(3 rows)
```

Core file is unclear. It segfaults on a `foreach` loop even though I don't see anything obviously wrong in there. `rel->pathlist` is at least readable in the core dump and doesn't look completely bogus at first glance. There seems to be something going wrong earlier already, perhaps leading to some memory corruption?

```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f8bebf10822 in apply_optimizations (ht=<optimized out>, rte=<optimized out>, rel=0x1b155d0, reltype=TS_REL_HYPERTABLE, root=0x1a8a0d0) at ../src/planner.c:701
701			foreach (lc, rel->pathlist)
(gdb) bt
#0  0x00007f8bebf10822 in apply_optimizations (ht=<optimized out>, rte=<optimized out>, rel=0x1b155d0, reltype=TS_REL_HYPERTABLE, root=0x1a8a0d0) at ../src/planner.c:701
#1  timescaledb_set_rel_pathlist (rte=<optimized out>, rti=<optimized out>, rel=<optimized out>, root=0x1a8a0d0) at ../src/planner.c:804
#2  timescaledb_set_rel_pathlist (root=0x1a8a0d0, rel=<optimized out>, rti=<optimized out>, rte=<optimized out>) at ../src/planner.c:762
#3  0x000000000069257a in set_rel_pathlist (root=root@entry=0x1a8a0d0, rel=0x1b155d0, rti=rti@entry=1, rte=0x1a89568) at allpaths.c:540
#4  0x0000000000692e70 in set_base_rel_pathlists (root=0x1a8a0d0) at allpaths.c:352
#5  make_one_rel (root=root@entry=0x1a8a0d0, joinlist=joinlist@entry=0x1b164a8) at allpaths.c:222
#6  0x00000000006b1bf5 in query_planner (root=root@entry=0x1a8a0d0, qp_callback=qp_callback@entry=0x6b30f0 <standard_qp_callback>, qp_extra=qp_extra@entry=0x7ffc7559fd20) at planmain.c:271
#7  0x00000000006b5c5d in grouping_planner (root=<optimized out>, inheritance_update=false, tuple_fraction=<optimized out>) at planner.c:2048
#8  0x00000000006b830d in subquery_planner (glob=<optimized out>, parse=parse@entry=0x1a89408, parent_root=parent_root@entry=0x18ec420, hasRecursion=hasRecursion@entry=false, tuple_fraction=0) at planner.c:1012
#9  0x0000000000690de9 in set_subquery_pathlist (rte=<optimized out>, rti=<optimized out>, rel=<optimized out>, root=<optimized out>) at allpaths.c:2309
#10 set_rel_size (root=<optimized out>, rel=<optimized out>, rti=<optimized out>, rte=<optimized out>) at allpaths.c:422
#11 0x0000000000692d80 in set_base_rel_sizes (root=<optimized out>) at allpaths.c:323
#12 make_one_rel (root=root@entry=0x18ec420, joinlist=joinlist@entry=0x1a88eb8) at allpaths.c:185
#13 0x00000000006b1bf5 in query_planner (root=root@entry=0x18ec420, qp_callback=qp_callback@entry=0x6b30f0 <standard_qp_callback>, qp_extra=qp_extra@entry=0x7ffc755a0160) at planmain.c:271
#14 0x00000000006b5c5d in grouping_planner (root=<optimized out>, inheritance_update=false, tuple_fraction=<optimized out>) at planner.c:2048
#15 0x00000000006b830d in subquery_planner (glob=glob@entry=0x18ec390, parse=parse@entry=0x1ecc0c8, parent_root=parent_root@entry=0x0, hasRecursion=hasRecursion@entry=false, tuple_fraction=tuple_fraction@entry=0) at planner.c:1012
#16 0x00000000006b9406 in standard_planner (parse=parse@entry=0x1ecc0c8, cursorOptions=cursorOptions@entry=256, boundParams=boundParams@entry=0x0) at planner.c:406
#17 0x00007f8bebf103f0 in timescaledb_planner (parse=0x1ecc0c8, cursor_opts=256, bound_params=0x0) at ../src/planner.c:314
#18 0x0000000000765fde in pg_plan_query (querytree=<optimized out>, cursorOptions=cursorOptions@entry=256, boundParams=boundParams@entry=0x0) at postgres.c:878
#19 0x00000000005b390b in ExplainOneQuery (query=<optimized out>, cursorOptions=256, into=0x0, es=0x1b177d8, queryString=0x182fb70 "explain \nSELECT *\n   FROM \n      f_t1_2(10) sc,\n      f_t2(sc.a, 10)\n   ;", params=0x0, 
    queryEnv=0x0) at explain.c:368
#20 0x00000000005b3e45 in ExplainQuery (pstate=pstate@entry=0x1b176c8, stmt=stmt@entry=0x1830f38, queryString=queryString@entry=0x182fb70 "explain \nSELECT *\n   FROM \n      f_t1_2(10) sc,\n      f_t2(sc.a, 10)\n   ;", 
    params=params@entry=0x0, queryEnv=queryEnv@entry=0x0, dest=dest@entry=0x1a9a758) at explain.c:256
#21 0x000000000076b60d in standard_ProcessUtility (pstmt=pstmt@entry=0x1831978, queryString=queryString@entry=0x182fb70 "explain \nSELECT *\n   FROM \n      f_t1_2(10) sc,\n      f_t2(sc.a, 10)\n   ;", 
    context=context@entry=PROCESS_UTILITY_TOPLEVEL, params=params@entry=0x0, queryEnv=0x0, dest=0x1a9a758, completionTag=0x7ffc755a0860 "") at utility.c:675
#22 0x00007f8bebfe9f8e in loader_process_utility_hook (pstmt=0x1831978, query_string=0x182fb70 "explain \nSELECT *\n   FROM \n      f_t1_2(10) sc,\n      f_t2(sc.a, 10)\n   ;", context=PROCESS_UTILITY_TOPLEVEL, params=0x0, 
    queryEnv=<optimized out>, dest=<optimized out>, completion_tag=0x7ffc755a0860 "") at ../src/loader/loader.c:510
#23 0x00007f8bebf16da3 in prev_ProcessUtility (args=<optimized out>) at ../src/process_utility.c:89
#24 0x00007f8bebf16e8a in timescaledb_ddl_command_start (pstmt=0x1831978, query_string=<optimized out>, context=PROCESS_UTILITY_TOPLEVEL, params=0x0, queryEnv=<optimized out>, dest=0x1a9a758, completion_tag=0x7ffc755a0860 "")
    at ../src/process_utility.c:4013
#25 0x0000000000768ab4 in PortalRunUtility (portal=0x1898800, pstmt=0x1831978, isTopLevel=<optimized out>, setHoldSnapshot=<optimized out>, dest=0x1a9a758, completionTag=0x7ffc755a0860 "") at pquery.c:1175
#26 0x0000000000769845 in FillPortalStore (portal=0x1898800, isTopLevel=<optimized out>) at ../../../src/include/nodes/pg_list.h:79
#27 0x000000000076a2fd in PortalRun (portal=portal@entry=0x1898800, count=count@entry=9223372036854775807, isTopLevel=isTopLevel@entry=true, run_once=run_once@entry=true, dest=dest@entry=0x1831618, altdest=altdest@entry=0x1831618, 
    completionTag=0x7ffc755a0a80 "") at pquery.c:765
#28 0x00000000007663ff in exec_simple_query (query_string=0x182fb70 "explain \nSELECT *\n   FROM \n      f_t1_2(10) sc,\n      f_t2(sc.a, 10)\n   ;") at postgres.c:1215
#29 0x0000000000767ccc in PostgresMain (argc=<optimized out>, argv=argv@entry=0x185c940, dbname=<optimized out>, username=<optimized out>) at postgres.c:4261
#30 0x00000000006f3b47 in BackendRun (port=0x1854a30, port=0x1854a30) at postmaster.c:4484
#31 BackendStartup (port=0x1854a30) at postmaster.c:4167
#32 ServerLoop () at postmaster.c:1725
#33 0x00000000006f49aa in PostmasterMain (argc=argc@entry=3, argv=argv@entry=0x182a280) at postmaster.c:1398
#34 0x0000000000480d44 in main (argc=3, argv=0x182a280) at main.c:228
```

### PR DESCRIPTION
**Pull request by svenklemm**
In nested function invocations hypertable expansion would not work
correctly and a hypertable would not be expanded by timescaledb
code but by postgres table inheritance leading to fdw_private
not being properly initialized.

Fixes #3391

### CODE REVIEW

File: src/planner.h [hunk 1]
```diff
@@ -40,7 +40,8 @@ ts_create_private_reloptinfo(RelOptInfo *rel)
 static inline TimescaleDBPrivate *
 ts_get_private_reloptinfo(const RelOptInfo *rel)
 {
-	return rel->fdw_private;
+	Assert(rel->fdw_private);
```
Comment (fvannee) [inline src/planner.h:43]: If the assert would be always true then the if/else isn't needed. The problem was that this condition is apparently *not* always true, in which case it'll still abort in debug builds?

Comment (svenklemm) [reply src/planner.h:43]: if we end up in the assert here that means this hypertable was not expanded by timescaledb code but by normal postgres table inheritance which is not the end of the world but on oversight and something that is useful to detect in debug build because that is probably on oversight on our part.

**Review by gayyappan — APPROVED** [review]

**Review by mkindahl — APPROVED** [review]
LGTM
