### PR TITLE
Fix segfault after column drop on compressed table

### LINKED ISSUE #5458: [Bug]: Segmentation fault after column dropped from compressed table
### What type of bug is this?

Crash

### What subsystems and features are affected?

Compression

### What happened?

crash during testing ; it seems like the following is the problem:
* table column in c1,c2 order
* segmentby c2
* drop c1
* segfault during windowed read of table

### TimescaleDB version affected

2.10.1  and current main

### PostgreSQL version used

15.2

### What operating system did you use?

Debian12

### What installation method did you use?

Source

### What platform did you run on?

Other, Not applicable

### Relevant log output and stack trace

```bash
Program received signal SIGSEGV, Segmentation fault.
toast_build_flattened_tuple (tupleDesc=0x7f671c198660, values=<optimized out>, isnull=0x5565013247f0) at heaptoast.c:592
592				if (VARATT_IS_EXTERNAL(new_value))
-exec bt
#0  toast_build_flattened_tuple (tupleDesc=0x7f671c198660, values=<optimized out>, isnull=0x5565013247f0) at heaptoast.c:592
#1  0x00005564ff20d558 in ExecEvalWholeRowVar (state=state@entry=0x556501324ae0, op=op@entry=0x556501324bf0, econtext=econtext@entry=0x5565013246c0) at execExprInterp.c:4179
#2  0x00005564ff20da7f in ExecInterpExpr (state=0x556501324ae0, econtext=0x5565013246c0, isnull=0x7fff1be598ef) at execExprInterp.c:616
#3  0x00005564ff20ac6d in ExecInterpExprStillValid (state=0x556501324ae0, econtext=0x5565013246c0, isNull=0x7fff1be598ef) at execExprInterp.c:1826
#4  0x00007f671c4031db in ExecEvalExprSwitchContext (state=<optimized out>, econtext=<optimized out>, isNull=<optimized out>) at /home/dev/pg/REL_15_2/include/postgresql/server/executor/executor.h:341
#5  0x00007f671c40321b in ExecProject (projInfo=0x556501324ad8) at /home/dev/pg/REL_15_2/include/postgresql/server/executor/executor.h:375
#6  0x00007f671c40386f in decompress_chunk_exec (node=0x5565013244a8) at /home/dev/timescaledb/tsl/src/nodes/decompress_chunk/exec.c:394
#7  0x00005564ff22fe2e in ExecCustomScan (pstate=<optimized out>) at nodeCustom.c:115
#8  0x00005564ff21a6dd in ExecProcNodeFirst (node=0x5565013244a8) at execProcnode.c:464
#9  0x00005564ff24a632 in ExecProcNode (node=0x5565013244a8) at ../../../src/include/executor/executor.h:259
#10 0x00005564ff24a6aa in ExecResult (pstate=<optimized out>) at nodeResult.c:115
#11 0x00005564ff21a6dd in ExecProcNodeFirst (node=0x5565013242c0) at execProcnode.c:464
#12 0x00005564ff24c204 in ExecProcNode (node=node@entry=0x5565013242c0) at ../../../src/include/executor/executor.h:259
#13 0x00005564ff24c363 in ExecSort (pstate=<optimized out>) at nodeSort.c:149
#14 0x00005564ff21a6dd in ExecProcNodeFirst (node=0x5565013240a8) at execProcnode.c:464
#15 0x00005564ff251cc4 in ExecProcNode (node=node@entry=0x5565013240a8) at ../../../src/include/executor/executor.h:259
#16 0x00005564ff252161 in begin_partition (winstate=winstate@entry=0x556501323b00) at nodeWindowAgg.c:1112
#17 0x00005564ff255cd2 in ExecWindowAgg (pstate=<optimized out>) at nodeWindowAgg.c:2130
#18 0x00005564ff21a6dd in ExecProcNodeFirst (node=0x556501323b00) at execProcnode.c:464
#19 0x00005564ff21233e in ExecProcNode (node=node@entry=0x556501323b00) at ../../../src/include/executor/executor.h:259
#20 0x00005564ff2123d8 in ExecutePlan (estate=estate@entry=0x5565013238b0, planstate=0x556501323b00, use_parallel_mode=<optimized out>, operation=operation@entry=CMD_SELECT, sendTuples=sendTuples@entry=true, numberTuples=numberTuples@entry=0, direction=ForwardScanDirection, dest=0x5565014b75c8, execute_once=true) at execMain.c:1636
#21 0x00005564ff2131a3 in standard_ExecutorRun (queryDesc=0x5565013bf910, direction=ForwardScanDirection, count=0, execute_once=<optimized out>) at execMain.c:363
#22 0x00005564ff2132d6 in ExecutorRun (queryDesc=queryDesc@entry=0x5565013bf910, direction=direction@entry=ForwardScanDirection, count=count@entry=0, execute_once=<optimized out>) at execMain.c:307
#23 0x00005564ff3c2490 in PortalRunSelect (portal=portal@entry=0x556501281850, forward=forward@entry=true, count=0, count@entry=9223372036854775807, dest=dest@entry=0x5565014b75c8) at pquery.c:924
#24 0x00005564ff3c3dda in PortalRun (portal=portal@entry=0x556501281850, count=count@entry=9223372036854775807, isTopLevel=isTopLevel@entry=true, run_once=run_once@entry=true, dest=dest@entry=0x5565014b75c8, altdest=altdest@entry=0x5565014b75c8, qc=0x7fff1be59e50) at pquery.c:768
#25 0x00005564ff3bfe3c in exec_simple_query (query_string=query_string@entry=0x5565011f7d30 "select count(1) over (partition by time,c),* from  normal.readings c;") at postgres.c:1250
#26 0x00005564ff3c1cda in PostgresMain (dbname=<optimized out>, username=<optimized out>) at postgres.c:4593
#27 0x00005564ff32635b in BackendRun (port=port@entry=0x55650121f330) at postmaster.c:4511
#28 0x00005564ff328397 in BackendStartup (port=port@entry=0x55650121f330) at postmaster.c:4239
#29 0x00005564ff3285ab in ServerLoop () at postmaster.c:1806
#30 0x00005564ff329b79 in PostmasterMain (argc=argc@entry=1, argv=argv@entry=0x5565011b23e0) at postmaster.c:1478
#31 0x00005564ff273ed9 in main (argc=1, argv=0x5565011b23e0) at main.c:202
```
```


### How can we reproduce the bug?

```bash
DROP TABLE IF EXISTS readings;
CREATE TABLE readings(
    time  TIMESTAMP WITH TIME ZONE NOT NULL,
    battery_status  TEXT,   
    battery_temperature  DOUBLE PRECISION
);

insert into readings (time) values ('2022-11-11 11:11:11');

SELECT create_hypertable(:'table_name', 'time', chunk_time_interval => interval '12 hour', migrate_data=>true);

ALTER TABLE :table_name SET (timescaledb.compress,timescaledb.compress_segmentby = 'battery_temperature');
select compress_chunk(show_chunks(:'table_name'));

alter table :current_mode.readings drop column battery_status;
explain 
select c from  :current_mode.readings c;
select c from  :current_mode.readings c;
```

### PR DESCRIPTION
**Pull request by kgyrtkirk**
Decompression produces records which have all the decompressed data set, but it also retains the fields which are used internally during decompression.
These didn't cause any problem - unless an operation is being done with the whole row - in which case all the fields which have ended up being non-null can be a potential segfault source.

Fixes #5458 #5411

### CODE REVIEW

File: tsl/src/nodes/decompress_chunk/exec.c [hunk 1]
```diff
@@ -434,6 +434,13 @@ decompress_chunk_create_tuple(DecompressChunkState *state)
 
 		ExecClearTuple(slot);
 
+		/* some technical columns may left unpopulated in the slot;
+		 * setting isnull prevents issues for row expressions */
+		for (i = 0; i < slot->tts_tupleDescriptor->natts; i++)
+		{
+			slot->tts_isnull[i] = true;
+		}
+
```
Comment (akuzm) [inline tsl/src/nodes/decompress_chunk/exec.c:443]: Which columns exactly? Shouldn't `drop column battery_status` drop them as well?

Probably makes sense to add a test for whole-row var + compressed chunks with diffent columns, like in `compression_alter.sql`. I'm not sure how row type conversion works in this case, and why it even tries to read these columns that are not in the resulting row...

Comment (kgyrtkirk) [reply tsl/src/nodes/decompress_chunk/exec.c:443]: for columns with types (`state->columns[i].type`) like `COUNT_COLUMN` and `SEQUENCE_NUM_COLUMN`  there is a place in the result desc; however its never populated; however when the row-tuple is read it tries to flatten it...

there is a testcase in the changeset which is able to trigger the issue without these changes

by the way: it returns the a much wider row than whats required; however it uses a by-name-lookup so its "not-a-problem" :D

Comment (kgyrtkirk) [reply tsl/src/nodes/decompress_chunk/exec.c:443]: after the drop there is a 3rd column in `tts_tupleDescriptor` with the name : ` {data = "........pg.dropped.3........", '\000' <repeats 35 times>}` which is not populated

I've looked into fixing it differently but the removed column can be anywhere in the row - so its not that easy to erase it; we also have have a projection embedded around here which further complicate things

Comment (gayyappan) [reply tsl/src/nodes/decompress_chunk/exec.c:443]: The problem is the projections from the 2 chunks don't match. The compressed chunk output should be transformed to match that of the uncompressed chunk. 
Compare the plan below with select * from readings. We already have code that adjusts for select *. Need to check why that is not working for this case.
```
test=# explain verbose select c from readings c;
                                                                     QUERY PLAN                                                                     
----------------------------------------------------------------------------------------------------------------------------------------------------
 Append  (cost=1.01..43.76 rows=2850 width=32)
   ->  Custom Scan (DecompressChunk) on _timescaledb_internal._hyper_9_57_chunk c_1  (cost=1.01..1.01 rows=1000 width=32)
         Output: c_1.*
         ->  Seq Scan on _timescaledb_internal.compress_hyper_10_58_chunk  (cost=0.00..1.01 rows=1 width=44)
               Output: compress_hyper_10_58_chunk._ts_meta_count, compress_hyper_10_58_chunk."time", compress_hyper_10_58_chunk.battery_temperature
   ->  Seq Scan on _timescaledb_internal._hyper_9_59_chunk c_2  (cost=0.00..28.50 rows=1850 width=32)
         Output: c_2.*
(7 rows)
```

Comment (gayyappan) [reply tsl/src/nodes/decompress_chunk/exec.c:443]: See decompress_chunk.c for whole_row var handling

Comment (kgyrtkirk) [reply tsl/src/nodes/decompress_chunk/exec.c:443]: I've debugged this a bit more and I'm now more convinced that this is the right solution; let me try to walk you thru why:
* decompression with uncompressed rows works by utilizing an Append node to concatenate the rows of 2 operators
* `Append` also has the requirement that the columns should match-up between its operands
  * in case there are exact columns requests this is not that big of an issue - they are being placed into the targetlist; and as long as the number/types of the targets are in sync I guess Append is happy to do its job
    * `note that` in this case we are selecting specific columns from the standard hypertable as well
  * if we have to select the whole row - it will do it by adding a Var with `attno=0`; there will be 1 column with a complex type...
* whole-rows for compression is handled by interpreting the `attno=0` and expanding them for `compressed_rel` ;  to help build the underlying SeqScan on the compressed table.
  * based on the actual scanned column list on the compressed table the `compression_map` is computed which will be there during execution to route inputs to outputs after decompression
* to make `Append` work the code actually piggybacks on the original rel ; by copying its targetlist for the decompression path
  * however this means that in the above path it will copy the row reference as well: `c_2.*`
  * this will make Append happy because there is no difference between the 2 operands output :+1: 
* the hypertable already have a column dropped!
  * there will be a `pg.dropped` column in the output rowtype of of `Seq Scan c_2` for `c_2.*`
  * because this rowtype was copied to be the output of the `DecompressChunk`; the deleted column will appear there as well...but since it was never really planned to get that column (whole_row stuff in decompress_chunk) - `compression_map` will not have any instructions how to fill it based on the actual input
* I think the removal of `pg.dropped.` columns is done internally by postgres automatically

I think append will not work correctly unless all branches return the same rowtype. And that's why I think the options are:
* go with the current fix
  * or it might be possible to pre-determine which columns will not have their `is_null` populated
* map: probably it might be possible to add some marker to the  decompress_map to handle unknown output columns and set is_null based on that
* wild1: if the input contains whole-row stuff; reference all columns directly for both the hypertable and for the compressed; move all expression evaluation into a new projection on top of the append
* wild2: push-in a projection for the standard seq-scan part to remove these removed columns
* other ideas?

Comment (kgyrtkirk) [reply tsl/src/nodes/decompress_chunk/exec.c:443]: @gayyappan @akuzm

Comment (kgyrtkirk) [reply tsl/src/nodes/decompress_chunk/exec.c:443]: @svenklemm  ; replying to your comment on the other PR [here](https://github.com/timescale/timescaledb/pull/5488#discussion_r1148865909) instead.

row schema for the compressed path is copied over from the non-compressed hypertable; which may have dropped columns.

* `CompressionInfo.chunk_rel` is the base hypertable relation
* decompression uses that to declare that it could a relation like that:
https://github.com/timescale/timescaledb/blob/22841abdf0d2c7b853386d8594d2a317df5f1e07/tsl/src/nodes/decompress_chunk/decompress_chunk.c#L1199
  * actually this kinda makes sense ; because for a compressed chunk that's the "closest thing" to what the compression will be producing

We could try other approaches...but setting the `isnull` bools to true by default can fix this segfault harmlessly without extensive changes

File: tsl/src/nodes/decompress_chunk/exec.c [hunk 2]
```diff
@@ -434,6 +434,13 @@ decompress_chunk_create_tuple(DecompressChunkState *state)
 
 		ExecClearTuple(slot);
 
+		/* some technical columns may left unpopulated in the slot;
+		 * setting isnull prevents issues for row expressions */
+		for (i = 0; i < slot->tts_tupleDescriptor->natts; i++)
+		{
+			slot->tts_isnull[i] = true;
+		}
```
Comment (mkindahl) [inline tsl/src/nodes/decompress_chunk/exec.c:442]: Suggest to use the existing function. It does some more work, but I think it is better to rely on PostgreSQL code for this.
```suggestion
		ExecStoreAllNullTuple(slot);
```

**Review by mkindahl — APPROVED** [review]
I ran into a similar problem in #4268. It seems like some of the code in PostgresSQL does not check the `attisdropped` column and rely on these columns to be NULL. Check, for instance, `heap_compute_data_size` and `toast_build_flattened_tuple` which is only checking for NULL, but not checking if the column is dropped.

Also check how `make_tuple_from_row` in `pl_exec.c` handles dropped columns by setting them to null.

Approving since I think this demonstrably solves the problem and does not really risk introducing any new bugs.

File: tsl/test/sql/compression_errors.sql [hunk 3]
```diff
@@ -364,3 +364,22 @@ INSERT INTO ts_table SELECT * FROM data_table;
...
 DROP TABLE data_table cascade;
 DROP TABLE ts_table cascade;
+
+--invalid reads for row expressions after column dropped on compressed tables #5458
+DROP TABLE IF EXISTS readings;
+CREATE TABLE readings(
+    time  TIMESTAMP WITH TIME ZONE NOT NULL,
+    battery_status  TEXT,
+    battery_temperature  DOUBLE PRECISION
+);
```
Comment (fabriziomello) [inline tsl/test/sql/compression_errors.sql:374]:
```suggestion
CREATE TABLE readings(
    "time"  TIMESTAMPTZ NOT NULL,
    battery_status  TEXT,
    battery_temperature  DOUBLE PRECISION
);
```

File: tsl/test/sql/compression_errors.sql [hunk 4]
```diff
@@ -364,3 +364,22 @@ INSERT INTO ts_table SELECT * FROM data_table;
...
+
+insert into readings (time) values ('2022-11-11 11:11:11');
```
Comment (fabriziomello) [inline tsl/test/sql/compression_errors.sql:376]:
```suggestion
INSERT INTO readings (time) VALUES ('2022-11-11 11:11:11');
```

File: tsl/test/sql/compression_errors.sql [hunk 5]
```diff
@@ -364,3 +364,22 @@ INSERT INTO ts_table SELECT * FROM data_table;
...
+
+SELECT create_hypertable('readings', 'time', chunk_time_interval => interval '12 hour', migrate_data=>true);
+
+ALTER TABLE readings SET (timescaledb.compress,timescaledb.compress_segmentby = 'battery_temperature');
+select compress_chunk(show_chunks('readings'));
```
Comment (fabriziomello) [inline tsl/test/sql/compression_errors.sql:381]:
```suggestion
SELECT compress_chunk(show_chunks('readings'));
```

File: tsl/test/sql/compression_errors.sql [hunk 6]
```diff
@@ -364,3 +364,22 @@ INSERT INTO ts_table SELECT * FROM data_table;
...
+
+alter table readings drop column battery_status;
+insert into readings  values ('2022-11-11 11:11:11',0.2);
+select c from  readings c;
```
Comment (fabriziomello) [inline tsl/test/sql/compression_errors.sql:385]:
```suggestion
ALTER TABLE readings DROP COLUMN battery_status;
INSERT INTO readings ("time",  battery_temperature) VALUES ('2022-11-11 11:11:11', 0.2);
SELECT readings FROM readings;
```

**Review by fabriziomello — APPROVED** [review]
Left some minor cosmetic comments that is up to you. Approved anyway!!!

**Comment by kgyrtkirk** [comment]
Thank you @mkindahl  and @fabriziomello for reviewing this PR!
