### PR TITLE
Set status for backend in background jobs

### LINKED ISSUE #2831: The reported jobs_status in timescaledb_information.job_stats is always Scheduled, even when the job is running.
**Relevant system information:**
 - OS: Ubuntu 18.04
 - PostgreSQL version (output of `postgres --version`): 12.5
 - TimescaleDB version (output of `\dx` in `psql`): 2.0.0
 - Installation method: apt-install

**Describe the bug**
The reported `jobs_status` in `timescaledb_information.job_stats` is always `Scheduled`, even when the job is running.

**To Reproduce**
Create a job with `add_job()`, then check its status in the `job_stats` table while it is running

**Expected behavior**
According to the [API reference](https://docs.timescale.com/latest/api#timescaledb_information-job_stats): 
```
job_status | (TEXT) Status of the job. Valid values are ‘Running’, ‘Scheduled’ and 'Paused'
```
so expected output would be something like:
```
 job_id |      last_run_started_at      |    last_successful_finish     | last_run_status | job_status | last_run_duration |          next_start           | total_runs | total_successes | total_failures
--------+-------------------------------+-------------------------------+-----------------+------------+-------------------+-------------------------------+------------+-----------------+----------------
   1010 | 2021-01-14 16:45:22.418187+00 | 2021-01-14 16:40:22.418084+00 |                 | Running    |                   | -infinity                     |        212 |             211 |              0
```

**Actual behavior**
Actual output shows the job as `Scheduled`
```
 job_id |      last_run_started_at      |    last_successful_finish     | last_run_status | job_status | last_run_duration |          next_start           | total_runs | total_successes | total_failures
--------+-------------------------------+-------------------------------+-----------------+------------+-------------------+-------------------------------+------------+-----------------+----------------
   1010 | 2021-01-14 16:45:22.418187+00 | 2021-01-14 16:40:22.418084+00 |                 | Scheduled  |                   | -infinity                     |        212 |             211 |              0
```

This is the same table in between job executions:
```
 job_id |      last_run_started_at      |    last_successful_finish     | last_run_status | job_status | last_run_duration |          next_start           | total_runs | total_successes | total_failures
--------+-------------------------------+-------------------------------+-----------------+------------+-------------------+-------------------------------+------------+-----------------+----------------
   1010 | 2021-01-14 16:50:30.699341+00 | 2021-01-14 16:50:37.784607+00 | Success         | Scheduled  | 00:00:07.085266   | 2021-01-14 16:55:37.784607+00 |        213 |             213 |              0
```

### PR DESCRIPTION
**Pull request by mkindahl**
The status of background workers is recorded using
`pgstat_record_activity` which allow the status of the worker to be
inspected using the `status` field in `pg_stat_activity`. This is used
by the `timescaledb_information.job_stats` view to show if a job is
running, scheduled, or paused.

However, the activity was never recorded in the code and hence the
field was always NULL. Since this was the default for the `job_status`
field of `timescaledb_information.job_stats` it would always show as
`Scheduled`.

This commit fixes this by adding calls to `pgstat_record_activity` and
suitable locations and also add a default of `Undefined` for the
`job_status` field to capture missing calls of
`pgstat_record_activity`. This is more of a precaution and is unlikely
to ever show.

Fixes #2831

### CODE REVIEW

File: tsl/src/bgw_policy/job.c [hunk 1]
```diff
@@ -504,6 +505,19 @@ job_execute(BgwJob *job)
...
+	/* Here we create a query string from the function/procedure name that we
+	 * are calling. We do not update the status after the execution has
+	 * finished since this is wrapped inside the code that starts and stops
+	 * any job, not just custom jobs. We just provide more detailed
+	 * information here that we are actually calling a specific custom
+	 * function. */
+	query = makeStringInfo();
+	appendStringInfo(query,
+					 "CALL %s.%s()",
+					 NameStr(job->fd.proc_schema),
```
Comment (pmwkaa) [inline tsl/src/bgw_policy/job.c:517]: Does it need quotes? in case if name contains spaces, etc.

**Review by pmwkaa — APPROVED** [review]

File: tsl/src/bgw_policy/job.c [hunk 2]
```diff
@@ -504,6 +505,19 @@ job_execute(BgwJob *job)
...
+					 NameStr(job->fd.proc_name));
+	pgstat_report_activity(STATE_RUNNING, query->data);
```
Comment (svenklemm) [inline tsl/src/bgw_policy/job.c:519]: this needs a test

File: tsl/src/bgw_policy/job.c (hunk 1 above)
Comment (mkindahl) [reply tsl/src/bgw_policy/job.c]: Well, it is just user viewed output, not something that is used for execution, but changed it anyway since it looks nicer.

File: tsl/src/bgw_policy/job.c (hunk 2 above)
Comment (mkindahl) [reply tsl/src/bgw_policy/job.c:519]: Added one. I actually wanted to add a more elaborate test that shows what statement is being executed inside a custom procedure, but that proved to be difficult.

**Review by svenklemm — APPROVED** [review]
