### PR TITLE
Free ChunkInsertStates when the es_per_tuple_exprcontext is freed

### LINKED ISSUE #908: Segfault due to cache invalidation on copy commands that create many chunks
**Relevant system information:**
 - OS: OSX Mojave
 - PostgreSQL version (output of `postgres --version`): 10.6
 - TimescaleDB version (output of `\dx` in `psql`): 1.0.1
 - Installation method: source

**Describe the bug**
Segfault on copy commands that create many chunks. 

**To Reproduce**
After trying to reproduce for a bit the guc timescaledb.max_open_chunks_per_insert being set low can make this happen much sooner. Simply do a copy command that creates multiple chunks with that set very low.

### PR DESCRIPTION
**Pull request by JLockerman**
Instead of freeing ChunkInsertStates immediately when flushed from the
SubspaceStore, defer the freeing until the es_per_tuple_exprcontext is
being cleaned up. This ensures that pointers into the CIS don't become
invalidated without us freeing any of postgres's memory, like we were
doing in the prior fix; this fixes a segfault in COPY.

In the normal INSERT case these frees happen at approximately the same
time so there should be no regression in memory usage, while if there
was a delay in freeing the es_per_tuple_exprcontext our old strategy of
clearing the context ourselves was invalid.

Fixes #908

### CODE REVIEW

File: src/chunk_insert_state.c [hunk 1]
```diff
@@ -556,27 +571,26 @@ ts_chunk_insert_state_destroy(ChunkInsertState *state)
...
+		deletion_context = state->estate->es_per_tuple_exprcontext->ecxt_per_tuple_memory;
+	}
+	else
+	{
+		deletion_context = state->estate->es_query_cxt;
+	}
 
-	state->estate->es_per_tuple_exprcontext = NULL;
+	free_callback_ptr = MemoryContextAlloc(state->estate->es_query_cxt, sizeof(*free_callback_ptr));
+	*free_callback_ptr = free_callback;
```
Comment (cevian) [inline src/chunk_insert_state.c]: why don't we just do 

``` 
*free_callback_ptr = {
		.func = chunk_insert_state_free,
		.arg = state,
	};
``` 
here instead of creating an extra var above?

File: src/chunk_insert_state.c [hunk 2]
```diff
@@ -556,27 +571,26 @@ ts_chunk_insert_state_destroy(ChunkInsertState *state)
...
+	{
+		deletion_context = state->estate->es_per_tuple_exprcontext->ecxt_per_tuple_memory;
+	}
+	else
+	{
+		deletion_context = state->estate->es_query_cxt;
+	}
 
-	state->estate->es_per_tuple_exprcontext = NULL;
+	free_callback_ptr = MemoryContextAlloc(state->estate->es_query_cxt, sizeof(*free_callback_ptr));
```
Comment (cevian) [inline src/chunk_insert_state.c]: shouldn't we allocate in the deletion_context instead of state->estate->es_query_cxt?

File: src/chunk_insert_state.c [hunk 3]
```diff
@@ -556,27 +571,26 @@ ts_chunk_insert_state_destroy(ChunkInsertState *state)
...
+	 * deletion of the ChunkInsertState until the current context if freed.
 	 */
 	if (state->estate->es_per_tuple_exprcontext != NULL)
-		FreeExprContext(state->estate->es_per_tuple_exprcontext, true);
+	{
+		deletion_context = state->estate->es_per_tuple_exprcontext->ecxt_per_tuple_memory;
+	}
+	else
+	{
+		deletion_context = state->estate->es_query_cxt;
```
Comment (cevian) [inline src/chunk_insert_state.c]: does the state->estate->es_query_cxt have pointers into cis? or only  state->estate->es_per_tuple_exprcontext? another words when  state->estate->es_per_tuple_exprcontext == NULL can we free the context right away or do we have to wait? In that case is there a major memory usage increase?

File: src/chunk_insert_state.c (hunk 1 above)
Comment (JLockerman) [reply src/chunk_insert_state.c]: It [doesn't work](https://godbolt.org/z/HKUYbw) 😢

File: src/chunk_insert_state.c (hunk 2 above)
Comment (JLockerman) [reply src/chunk_insert_state.c]: We should, it got overwritten in a merge.

File: src/chunk_insert_state.c (hunk 3 above)
Comment (JLockerman) [reply src/chunk_insert_state.c]: The honest answer is "we don't know", so I don't feel quite comfortable doing that optimization, especially since there's no measurable impact from the fix. If we do manage to get a case where `es_per_tuple_exprcontext == NULL` then we're outside of spec anyway, so I'd rather be conservative; less likely we'll introduce new bugs that way.

File: src/chunk_insert_state.c (hunk 1 above)
Comment (JLockerman) [reply src/chunk_insert_state.c]: fixed
