### PR TITLE
Fix segfault when using OLD/NEW refs in RETURNING clause on PG18

### LINKED ISSUE #9319: [Bug]: Seg fault when using OLD and/or NEW refs RETURNING clause
### What type of bug is this?

Crash

### What subsystems and features are affected?

Data ingestion

### What happened?

👋  Hello. 

I came across a segmentation fault when I tried to use PG18 features, namely the OLD and NEW refs in a RETURNING cause which I'm using in a upsert statement with two objectives:
1. Find if the upsert was an insert and not an update
1. Calculate a delta between the old value and a new one

Note: A discussion on the approach for the real use-case I'm trying to address is not point of the report.

The full example can be found at the end of this content.
```SQL
INSERT INTO sensor_data (time, sensor_id, cpu, temperature)
SELECT
  '2026-02-27',
  sensor_id,
  random() AS cpu,
  random()*100 AS temperature
FROM generate_series(1,4,1) AS g2(sensor_id)
ON CONFLICT (sensor_id, time) DO UPDATE SET
	cpu = EXCLUDED.cpu,
	temperature = EXCLUDED.temperature
RETURNING time, sensor_id, NEW.cpu - OLD.cpu, NEW.temperature - OLD.temperature;
```

### TimescaleDB version affected

2.23.1 and 2.25.1 (latest)

### PostgreSQL version used

18.1

### What operating system did you use?

Sequoia 15.7.3

### What installation method did you use?

Docker:
* timescale/timescaledb-ha:pg18.1-ts2.23.1-all
* timescale/timescaledb-ha:pg18.1-ts2.25.1-all

### What platform did you run on?

Not applicable

### Relevant log output and stack trace

```bash
db-1  | 2026-02-27 13:49:05.867 UTC [1] LOG:  database system is ready to accept connections
db-1  | 2026-02-27 13:49:05.878 UTC [1483] LOG:  TimescaleDB background worker launcher connected to shared catalogs
db-1  | 2026-02-27 13:49:26.228 UTC [1] LOG:  client backend (PID 1495) was terminated by signal 11: Segmentation fault
db-1  | 2026-02-27 13:49:26.228 UTC [1] DETAIL:  Failed process was running: INSERT INTO sensor_data (time, sensor_id, cpu, temperature)
db-1  |         SELECT
db-1  |           '2026-02-27',
db-1  |           sensor_id,
db-1  |           random() AS cpu,
db-1  |           random()*100 AS temperature
db-1  |         FROM generate_series(1,4,1) AS g2(sensor_id)
db-1  |         ON CONFLICT (sensor_id, time) DO UPDATE SET
db-1  |         cpu = EXCLUDED.cpu,
db-1  |         temperature = EXCLUDED.temperature
db-1  |         RETURNING time, sensor_id, NEW.cpu - OLD.cpu, NEW.temperature - OLD.temperature;
db-1  | 2026-02-27 13:49:26.228 UTC [1] LOG:  terminating any other active server processes
db-1  | 2026-02-27 13:49:26.247 UTC [1] LOG:  all server processes terminated; reinitializing
db-1  | 2026-02-27 13:49:26.348 UTC [1551] LOG:  database system was interrupted; last known up at 2026-02-27 13:49:05 UTC
db-1  | 2026-02-27 13:49:26.500 UTC [1551] LOG:  database system was not properly shut down; automatic recovery in progress
db-1  | 2026-02-27 13:49:26.507 UTC [1551] LOG:  redo starts at 0/2FDC0C0
db-1  | 2026-02-27 13:49:26.515 UTC [1551] LOG:  invalid record length at 0/3022C00: expected at least 24, got 0
db-1  | 2026-02-27 13:49:26.516 UTC [1551] LOG:  redo done at 0/3022BD8 system usage: CPU: user: 0.00 s, system: 0.00 s, elapsed: 0.00 s
db-1  | 2026-02-27 13:49:26.526 UTC [1552] LOG:  checkpoint starting: end-of-recovery immediate wait
db-1  | 2026-02-27 13:49:26.594 UTC [1552] LOG:  checkpoint complete: wrote 72 buffers (0.0%), wrote 3 SLRU buffers; 0 WAL file(s) added, 0 removed, 1 recycled; write=0.005 s, sync=0.044 s, total=0.068 s; sync files=59, longest=0.003 s, average=0.001 s; distance=282 kB, estimate=282 kB; lsn=0/3022C00, redo lsn=0/3022C00
db-1  | 2026-02-27 13:49:26.599 UTC [1] LOG:  database system is ready to accept connections
```

### How can we reproduce the bug?

To demonstrate this problem in a simpler form, I came up with the following example:
```SQL

--- Most of these statements come from here: https://www.tigerdata.com/docs/tutorials/latest/simulate-iot-sensor-data 
CREATE TABLE sensors(
  id SERIAL PRIMARY KEY,
  type VARCHAR(50),
  location VARCHAR(50)
);

INSERT INTO sensors (type, location) VALUES
  ('a','floor'),
  ('a', 'ceiling'),
  ('b','floor'),
  ('b', 'ceiling');
  

CREATE TABLE sensor_data (
   PRIMARY KEY (sensor_id, time), ---  A primary key to have a situation when the ON CONFLICT has something to do.

  time TIMESTAMPTZ NOT NULL,
  sensor_id INTEGER,
  temperature DOUBLE PRECISION,
  cpu DOUBLE PRECISION,
  FOREIGN KEY (sensor_id) REFERENCES sensors (id)
) WITH (
  tsdb.hypertable
);

--- Now, using the existing setup, let's insert data.
INSERT INTO sensor_data (time, sensor_id, cpu, temperature)
SELECT
  '2026-02-27',
  sensor_id,
  random() AS cpu,
  random()*100 AS temperature
FROM generate_series(1,4,1) AS g2(sensor_id)
ON CONFLICT (sensor_id, time) DO UPDATE SET
	cpu = EXCLUDED.cpu,
	temperature = EXCLUDED.temperature
RETURNING time, sensor_id, NEW.cpu - OLD.cpu, NEW.temperature - OLD.temperature; --- PANIC: the presence of the OLD and/or NEW causes a segmentation fault.
```

### PR DESCRIPTION
**Pull request by svenklemm**
PostgreSQL 18 added OLD/NEW references in RETURNING clauses. The forked
executor in modify_hypertable_exec.c did not set ecxt_oldtuple/
ecxt_newtuple or manage EEO_FLAG_* flags, causing NULL pointer
dereferences when RETURNING references OLD or NEW.

Update ExecProcessReturning to accept cmdType/oldSlot/newSlot on all PG
versions (pre-PG18 derives the legacy tupleSlot from them) and add the
OLD/NEW tuple setup behind a single PG18_GE block.  Add an oldSlot
parameter to ExecUpdate and materialize the returning slot in
ExecOnConflictUpdate before clearing the existing tuple.

Fixes #9319

### CODE REVIEW

File: src/nodes/modify_hypertable_exec.c [hunk 1]
```diff
@@ -1934,7 +1987,7 @@ ExecUpdate(ModifyTableContext *context, ResultRelInfo *resultRelInfo,
 
 	/* Process RETURNING if present */
 	if (resultRelInfo->ri_projectReturning)
-		return ExecProcessReturning(resultRelInfo, slot, context->planSlot);
+		return ExecProcessReturning(resultRelInfo, CMD_UPDATE, oldSlot, slot, context->planSlot);
```
Comment (redbaron) [inline src/nodes/modify_hypertable_exec.c:1990]: it wasn't on initial report, but MERGE also gained support for the `old` and `new` in the `RETURNING` .

**Comment by svenklemm** [comment]
> The CI check says the tests pass w/o the fix too, probably something is missing there.

This is PG18, that workflow runs PG17
