### PR TITLE
Fix telemetry handling in background worker scheduler

### LINKED ISSUE #2199: Infinite loop of failed to start telemetry reporter
**Relevant system information:**
 - OS: MacOS
 - PostgreSQL version (output of `postgres --version`): 11.7
 - TimescaleDB version (output of `\dx` in `psql`): latest develop
 - Installation method: from source

**Describe the bug**
After creating extension TimescaleDB the log is infinitely flooded with the following warning:
>WARNING:  failed to launch job 1 "Telemetry Reporter": failed to start a background worker

`timescaledb.max_background_workers` wasn't set.

**To Reproduce**
Create TimescaleDB extension without running timescaledb-tune and without setting `timescaledb.max_background_workers`.

**Expected behavior**
It shouldn't warn indefinitely.

**Actual behavior**
The warning is logged every second.

**Screenshots**
Example of the log lines:
```
2020-08-06 10:31:09.651 CEST [86523] WARNING:  failed to launch job 1 "Telemetry Reporter": failed to start a background worker
2020-08-06 10:31:10.653 CEST [86523] WARNING:  failed to launch job 1 "Telemetry Reporter": failed to start a background worker
2020-08-06 10:31:11.655 CEST [86523] WARNING:  failed to launch job 1 "Telemetry Reporter": failed to start a background worker
2020-08-06 10:31:12.656 CEST [86523] WARNING:  failed to launch job 1 "Telemetry Reporter": failed to start a background worker
2020-08-06 10:31:13.658 CEST [86523] WARNING:  failed to launch job 1 "Telemetry Reporter": failed to start a background worker
2020-08-06 10:31:14.659 CEST [86523] WARNING:  failed to launch job 1 "Telemetry Reporter": failed to start a background worker
2020-08-06 10:31:15.661 CEST [86523] WARNING:  failed to launch job 1 "Telemetry Reporter": failed to start a background worker
2020-08-06 10:31:16.663 CEST [86523] WARNING:  failed to launch job 1 "Telemetry Reporter": failed to start a background worker
2020-08-06 10:31:17.664 CEST [86523] WARNING:  failed to launch job 1 "Telemetry Reporter": failed to start a background worker
2020-08-06 10:31:18.667 CEST [86523] WARNING:  failed to launch job 1 "Telemetry Reporter": failed to start a background worker
2020-08-06 10:31:19.669 CEST [86523] WARNING:  failed to launch job 1 "Telemetry Reporter": failed to start a background worker
2020-08-06 10:31:20.670 CEST [86523] WARNING:  failed to launch job 1 "Telemetry Reporter": failed to start a background worker
2020-08-06 10:31:21.672 CEST [86523] WARNING:  failed to launch job 1 "Telemetry Reporter": failed to start a background worker
2020-08-06 10:31:22.673 CEST [86523] WARNING:  failed to launch job 1 "Telemetry Reporter": failed to start a background worker
2020-08-06 10:31:23.675 CEST [86523] WARNING:  failed to launch job 1 "Telemetry Reporter": failed to start a background worker
2020-08-06 10:31:24.676 CEST [86523] WARNING:  failed to launch job 1 "Telemetry Reporter": failed to start a background worker
2020-08-06 10:31:25.678 CEST [86523] WARNING:  failed to launch job 1 "Telemetry Reporter": failed to start a background worker
2020-08-06 10:31:26.679 CEST [86523] WARNING:  failed to launch job 1 "Telemetry Reporter": failed to start a background worker
2020-08-06 10:31:27.682 CEST [86523] WARNING:  failed to launch job 1 "Telemetry Reporter": failed to start a background worker
2020-08-06 10:31:28.683 CEST [86523] WARNING:  failed to launch job 1 "Telemetry Reporter": failed to start a background worker
2020-08-06 10:31:29.684 CEST [86523] WARNING:  failed to launch job 1 "Telemetry Reporter": failed to start a background worker
2020-08-06 10:31:30.686 CEST [86523] WARNING:  failed to launch job 1 "Telemetry Reporter": failed to start a background worker
2020-08-06 10:31:31.688 CEST [86523] WARNING:  failed to launch job 1 "Telemetry Reporter": failed to start a background worker
2020-08-06 10:31:32.690 CEST [86523] WARNING:  failed to launch job 1 "Telemetry Reporter": failed to start a background worker
2020-08-06 10:31:33.693 CEST [86523] WARNING:  failed to launch job 1 "Telemetry Reporter": failed to start a background worker
```

### LINKED ISSUE #2282: "Telemetry Reporter": out of background workers issue, when telemetry is disabled
**Relevant system information:**
 - OS: Ubuntu 18.04.4 LTS
 - PostgreSQL version:  postgres (PostgreSQL) 11.7 (Ubuntu 11.7-2.pgdg18.04+1)
 - TimescaleDB version:  timescaledb | 1.7.2   | public    
 - Installation method: "apt install"

Recently upgraded TimescaleDB from 1.6 to 1.7.2 and notice the "Telemetry Reporter": out of background workers warning

Tried setting Telemetry Reporter config to off and deleting bgw_job, but still see the logs filled with the warning as below.

2020-08-30 03:25:38.055 UTC [10061] WARNING:  failed to launch job 1 "Telemetry Reporter": out of background workers
2020-08-30 03:25:38.055 UTC [10052] WARNING:  failed to launch job 1 "Telemetry Reporter": out of background workers

Settings in Postgres provided below using PSQL

postgres=# show timescaledb.telemetry_level;
 timescaledb.telemetry_level
 off
(1 row)

postgres=# select * FROM _timescaledb_config.bgw_job;
 id | application_name | job_type | schedule_interval | max_runtime | max_retries | retry_period
(0 rows)

postgres=# show max_worker_processes;
 max_worker_processes
 13
(1 row)

postgres=# show timescaledb.max_background_workers ;
 timescaledb.max_background_workers
 8
(1 row)

### PR DESCRIPTION
**Pull request by svenklemm**
This patch changes the scheduler to ignore telemetry jobs when
telemetry is disabled. With this change telemetry jobs will no
longer use background worker resources when telemetry is disabled.

Fixes #2199
Fixes #2282

### CODE REVIEW

File: src/telemetry/telemetry.c [hunk 1]
```diff
@@ -505,6 +505,9 @@ ts_telemetry_main(const char *host, const char *path, const char *service)
 	bool started = false;
 	const char *volatile json = NULL;
 
+	if (!ts_telemetry_on())
```
Comment (erimatnor) [inline src/telemetry/telemetry.c:508]: Should we even get here if telemetry is off? Maybe this should be an assertion, since it seems to be a bug to start telemetry if it is off.

**Review by erimatnor — COMMENTED** [review]
Seems like the changes break tests.

**Review by mkindahl — APPROVED** [review]

File: src/telemetry/telemetry.c (hunk 1 above)
Comment (svenklemm) [reply src/telemetry/telemetry.c:508]: i think it's important to have this here as this is the code that is concerned with telemetry. we could also assert this but the assertion would fail in our test code as there are ways to circumvent the scheduler and some of our tests do
