### PR TITLE
Fix memory handling during scans

### LINKED ISSUE #4148: [Bug]: Crash in planner for JOIN queries.
### What type of bug is this?

Crash

### What subsystems and features are affected?

Other

### What happened?

TimescaleDB crashes on certain queries, this seems to be very easy to trigger as I get roughly 30 coredumps per minute with sqlsmith. 

I will update ticket with more information once i have reproducer.

### TimescaleDB version affected

master

### PostgreSQL version used

14.2

### What operating system did you use?

Archlinux 2022.03.01 x64

### What installation method did you use?

Source

### What platform did you run on?

On prem/Self-hosted

### Relevant log output and stack trace

```bash
#0  0x0000560c4cb103df GetMemoryChunkContext (postgres + 0x8333df)
#1  0x0000560c4cb12763 pfree (postgres + 0x835763)
#2  0x0000560c4c469cb1 btendscan (postgres + 0x18ccb1)
#3  0x0000560c4c452d0e index_endscan (postgres + 0x175d0e)
#4  0x00007fac2beaa435 index_scanner_endscan (timescaledb-2.7.0-dev.so + 0x63435)
#5  0x00007fac2beaa91f ts_scanner_end_scan (timescaledb-2.7.0-dev.so + 0x6391f)
#6  0x00007fac2beaaf71 ts_scan_iterator_close (timescaledb-2.7.0-dev.so + 0x63f71)
#7  0x00007fac2be7ba70 ts_chunk_scan_by_constraints (timescaledb-2.7.0-dev.so + 0x34a70)
#8  0x00007fac2be93f1a ts_hypertable_restrict_info_get_chunks (timescaledb-2.7.0-dev.so + 0x4cf1a)
#9  0x00007fac2be9c46c find_children_chunks (timescaledb-2.7.0-dev.so + 0x5546c)
#10 0x00007fac2be9ccb6 get_chunks (timescaledb-2.7.0-dev.so + 0x55cb6)
#11 0x00007fac2be9d367 ts_plan_expand_hypertable_chunks (timescaledb-2.7.0-dev.so + 0x56367)
#12 0x00007fac2be9890a reenable_inheritance (timescaledb-2.7.0-dev.so + 0x5190a)
#13 0x00007fac2be9919d timescaledb_set_rel_pathlist (timescaledb-2.7.0-dev.so + 0x5219d)
#14 0x0000560c4c783129 set_rel_pathlist (postgres + 0x4a6129)
#15 0x0000560c4c782c8e set_base_rel_pathlists (postgres + 0x4a5c8e)
#16 0x0000560c4c78299f make_one_rel (postgres + 0x4a599f)
#17 0x0000560c4c7c2399 query_planner (postgres + 0x4e5399)
#18 0x0000560c4c7c4b91 grouping_planner (postgres + 0x4e7b91)
#19 0x0000560c4c7c423a subquery_planner (postgres + 0x4e723a)
#20 0x0000560c4c785d98 set_subquery_pathlist (postgres + 0x4a8d98)
#21 0x0000560c4c782df8 set_rel_size (postgres + 0x4a5df8)
#22 0x0000560c4c782bd1 set_base_rel_sizes (postgres + 0x4a5bd1)
#23 0x0000560c4c782891 make_one_rel (postgres + 0x4a5891)
#24 0x0000560c4c7c2399 query_planner (postgres + 0x4e5399)
#25 0x0000560c4c7c4b91 grouping_planner (postgres + 0x4e7b91)
#26 0x0000560c4c7c423a subquery_planner (postgres + 0x4e723a)
#27 0x0000560c4c7c2aa1 standard_planner (postgres + 0x4e5aa1)
#28 0x00007fac2be97f4f timescaledb_planner (timescaledb-2.7.0-dev.so + 0x50f4f)
#29 0x0000560c4c7c27ce planner (postgres + 0x4e57ce)
#30 0x0000560c4c91181e pg_plan_query (postgres + 0x63481e)
#31 0x0000560c4c91196e pg_plan_queries (postgres + 0x63496e)
#32 0x0000560c4c911d5d exec_simple_query (postgres + 0x634d5d)
#33 0x0000560c4c916d48 PostgresMain (postgres + 0x639d48)
#34 0x0000560c4c83d4db BackendRun (postgres + 0x5604db)
#35 0x0000560c4c83cd42 BackendStartup (postgres + 0x55fd42)
#36 0x0000560c4c838acb ServerLoop (postgres + 0x55bacb)
#37 0x0000560c4c838240 PostmasterMain (postgres + 0x55b240)
#38 0x0000560c4c729d26 main (postgres + 0x44cd26)
#39 0x00007fac3536fb25 __libc_start_main (libc.so.6 + 0x27b25)
#40 0x0000560c4c3a176e _start (postgres + 0xc476e)
```

### How can we reproduce the bug?
The database used is the one from regresscheck-shared.
```bash
select * from devices inner join metrics_space_compressed on (true);
```

### PR DESCRIPTION
**Pull request by erimatnor**
Scan functions cannot be called on a per-tuple memory context as they
might allocate data that need to live until the end of the scan. Fix
this in a couple of places to ensure correct memory handling.

Fixes #4148, #4145
Disable-Check: Commit-Count

### CODE REVIEW

File: src/chunk_scan.c [hunk 1]
```diff
@@ -252,9 +252,9 @@ ts_chunk_scan_by_constraints(const Hyperspace *hs, const List *dimension_vecs,
 				prev_chunk_oid = chunk->table_id;
 			}
 
+			MemoryContextSwitchTo(work_mcxt);
 			/* Only one chunk should match */
 			Assert(ts_scan_iterator_next(&chunk_it) == NULL);
```
Comment (pmwkaa) [inline src/chunk_scan.c:257]: I know that this is not related to this PR, but I think placing working code inside the `Assert` statement might break it for the Release build or any other one, which builds without debug enabled, etc

Comment (erimatnor) [reply src/chunk_scan.c:257]: It verifies that only one row is returned, which is the assumption we make since we scan on the primary key. In debug, this is verified to be true, but the check isn't really needed if the assumption is true, which is why it is elided in release builds.

**Comment by erimatnor** [comment]
This should fix the recent Sqlsmith crashes, but we should double-check that the CI job works as expected.

**Comment by erimatnor** [comment]
Would like to merge #4164 first and then run the Sqlsmith tests on this PR before merging.

File: src/telemetry/stats.c [hunk 2]
```diff
@@ -338,27 +337,25 @@ static bool
...
+	oldmcxt = MemoryContextSwitchTo(statsctx->compressed_chunk_stats_iterator.scankey_mcxt);
 	ts_scan_iterator_scan_key_reset(&statsctx->compressed_chunk_stats_iterator);
 	ts_scan_iterator_scan_key_init(&statsctx->compressed_chunk_stats_iterator,
 								   Anum_compression_chunk_size_pkey_chunk_id,
 								   BTEqualStrategyNumber,
 								   F_INT4EQ,
 								   Int32GetDatum(chunk->fd.id));
+	ts_scan_iterator_start_or_restart_scan(&statsctx->compressed_chunk_stats_iterator);
+	ti = ts_scan_iterator_next(&statsctx->compressed_chunk_stats_iterator);
+	MemoryContextSwitchTo(oldmcxt);
```
Comment (mkindahl) [inline src/telemetry/stats.c:356]: Not sure I follow.

If the `scankey_mcxt` is the memory context used while scanning the table using the iterator, shouldn't these functions (`ts_scan_iterator_scan_key_reset`, `ts_scan_iterator_scan_key_init`, etc.) *always* allocate any memory in this context? Why should it be necessary to switch to this context before calling the functions?

Or put another way, shouldn't this memory context switch be inside each function rather than requiring the user of those function realize that it is necessary to switch to a memory context owned by the iterator?

Comment (erimatnor) [reply src/telemetry/stats.c:356]: Yes, but I didn't want to refactor in this PR. Instead, I wanted fix what is already released.

Comment (mkindahl) [reply src/telemetry/stats.c:356]: Does it break if you switch context inside all the scan iterator functions? To me, this seems like the safest approach.

Do you know if there are any other locations with similar issues?

Comment (erimatnor) [reply src/telemetry/stats.c:356]: I don't think there are other locations because we generally don't use "per tuple memory contexts"when scanning and instead just scan things on the main transaction memory context. In fact, these other locations are the reason I didn't want to change too much inside the scan functions as that would affect all other locations. "Don't fix what ain't broken".

In this code, I tried to be vigilant about not eating a lot of memory for these scans as they often involve an unbounded number of chunks. But I guess I didn't fully realize that most PG scan functions allocate new memory and don't use their own memory context internally.

It might make sense to wrap these APIs to use internal memory contexts that makes it easier to use per-tuple contexts,  as you suggest, but I didn't think that kind of refactoring was appropriate for this "fix" PR. 

If you feel it is important that we do it now, I can do it.

Comment (erimatnor) [reply src/telemetry/stats.c]: I added a commit with the changes you suggested. But I need to ensure it passes Sqlsmith.

**Review by svenklemm — APPROVED** [review]
Couldnt reproduce the issue from #4148 with this applied.

File: src/telemetry/stats.c (hunk 2 above)
Comment (mkindahl) [reply src/telemetry/stats.c]: I was concerned about that this fix does not address yet undiscovered issues that are lingering, not that I think the refactoring is necessary. It just seemed like the simplest and safest way to fix the issue.

File: src/scanner.c [hunk 3]
```diff
@@ -187,6 +190,9 @@ prepare_scan(ScannerCtx *ctx)
 	ctx->internal.ended = false;
 	ctx->internal.registered_snapshot = false;
 
+	if (ctx->internal.scan_mcxt == NULL)
+		ctx->internal.scan_mcxt = CurrentMemoryContext;
+
```
Comment (mkindahl) [inline src/scanner.c:195]: Isn't it a bug if this happens? Shouldn't the scan memory context always be set up?

File: src/scanner.c [hunk 4]
```diff
@@ -269,6 +285,9 @@ ts_scanner_start_scan(ScannerCtx *ctx)
 			ctx->index = RelationGetRelid(ctx->indexrel);
 	}
 
+	Assert(ctx->internal.scan_mcxt != NULL);
```
Comment (mkindahl) [inline src/scanner.c:288]: Related to the comment above, this seems to be an invariant, so maybe you should replace the `if` above with an `Assert`?

File: src/scanner.c [hunk 5]
```diff
@@ -375,7 +411,15 @@ ts_scanner_next(ScannerCtx *ctx)
 			/* stop at a valid tuple */
 			return &ictx->tinfo;
 		}
-		is_valid = ts_scanner_limit_reached(ctx) ? false : scanner->getnext(ctx);
+
+		if (ts_scanner_limit_reached(ctx))
+			is_valid = false;
+		else
```
Comment (mkindahl) [inline src/scanner.c:417]: Nit
```suggestion
		if (ts_scanner_limit_reached(ctx))
		{
			is_valid = false;
		}
		else
```

File: src/telemetry/stats.c [hunk 6]
```diff
@@ -338,27 +337,22 @@ static bool
 get_chunk_compression_stats(StatsContext *statsctx, const Chunk *chunk,
 							Form_compression_chunk_size compr_stats)
 {
+	TupleInfo *ti;
+
 	if (!ts_chunk_is_compressed(chunk))
 		return false;
 
+	/* Need to execute the scan functions on the long-lived memory context */
```
Comment (mkindahl) [inline src/telemetry/stats.c:345]: This comment does not seem to be related to any code here. Remove it?

**Review by mkindahl — APPROVED** [review]
Some minor nits, but nothing critical.

File: src/scanner.c (hunk 3 above)
Comment (erimatnor) [reply src/scanner.c:195]: We can decide, but it is not setup in existing code that doesn't use the iterator interface. For instance, in many places we set up the Scanner context like so:

```
	ScannerCtx scanctx = {
		.table = catalog_get_table_id(catalog, CHUNK),
		.index = catalog_get_index(catalog, CHUNK, CHUNK_SCHEMA_NAME_INDEX),
		.nkeys = 1,
		.scankey = scankey,
		.tuple_found = chunk_rename_schema_name,
		.data = new_schema,
		.lockmode = RowExclusiveLock,
		.scandirection = ForwardScanDirection,
	};

```

The intention is to not have to touch the internal context (which is embedded in the `ScennerCtx` struct). We can change this if we want to, but I don't think it is necessary.

File: src/scanner.c (hunk 4 above)
Comment (erimatnor) [reply src/scanner.c:288]: Since we always set it if not set, this assert conveys this fact and assures that we didn't miss this somewhere.

**Comment by erimatnor** [comment]
> Couldnt reproduce the issue from #4148 with this applied.

FYI, the CI checks also include the SQLsmith run on this commit below.
