### PR TITLE
Fix DST shift when generating gapfill buckets

### LINKED ISSUE #8844: [Bug]: mergejoin error with time_bucket_gapfill() and timezone across daylight savings period
### What type of bug is this?

Unexpected error

### What subsystems and features are affected?

Gapfill, Query executor

### What happened?

We're joining two CTEs which make use of [time_bucket_gapfill](https://docs.tigerdata.com/api/latest/hyperfunctions/gapfilling/time_bucket_gapfill/) function and the timezone parameter.

Recently we've received a few instances of `ERROR:  mergejoin input data is out of order` which seem to be to do with querying data which spans day light savings period (the UK has just gone through one on the 26th of October).

It's not affecting every query, and seems to have some correlation with interval size, time period and timestamps of the data being queried.

I have been able to reproduce it using the script below.

Things of note:

- Our original tables are hypertables but I've left that off here as it doesn't seem to make a difference
- If you change the interval from '3 hours' to '1 hours' the error goes away

I suspect the underlying problem is showing if you run one of the CTE's independently and you can see an out of sequence timestamp on the last row.

E.g. 

```sql
SELECT
	TIME_BUCKET_GAPFILL ('3 hours', TIMESTAMP, 'Europe/London') AS BUCKET,
	AVG(FLOW) AS "flowAvg"
FROM
	table1
WHERE timestamp > '2025-10-25 23:00:00' and timestamp < '2025-10-26 08:00:00+00'
GROUP BY
	BUCKET
ORDER BY
	BUCKET ASC
```

returns results for:

```
"2025-10-25 23:00:00+00"	
"2025-10-26 02:00:00+00"	
"2025-10-26 05:00:00+00"	
"2025-10-26 03:00:00+00"	<- this looks wrong
```

I can understand why this is complicated given the repeated 1am to 2am hour in this period / timezone and that doesn't fit nicely into the aggregation period. 

I'm not totally sure myself what results I would expect in this instance.

### TimescaleDB version affected

2.21.3

### PostgreSQL version used

17.6

### What operating system did you use?

Timescale cloud

### What installation method did you use?

Other, Not applicable

### What platform did you run on?

Timescale Cloud

### Relevant log output and stack trace

```bash

```

### How can we reproduce the bug?

```bash
END;BEGIN;

CREATE TABLE public.table1 (
    device_id integer,
    "timestamp" timestamp with time zone,
    flow integer
);

INSERT INTO public.table1 (device_id, "timestamp", flow) VALUES (1234, '2025-10-26 03:20:00+00', 10);

CREATE TABLE public.table2 (
    device_id integer,
    "timestamp" timestamp with time zone,
    volume_delta bigint
);

INSERT INTO public.table2 (device_id, "timestamp", volume_delta) VALUES (1234, '2025-10-26 03:20:00+00', 5);

WITH
	STATS AS (
		SELECT
			TIME_BUCKET_GAPFILL ('3 hours', TIMESTAMP, 'Europe/London') AS BUCKET,
			AVG(FLOW) AS "flowAvg"
		FROM
			table1
		WHERE timestamp > '2025-10-25 23:00:00' and timestamp < '2025-10-26 08:00:00+00'
		GROUP BY
			BUCKET
		ORDER BY
			BUCKET ASC
	),
	VOLUME AS (
		SELECT
			TIME_BUCKET_GAPFILL ('3 hours', TIMESTAMP, 'Europe/London') AS BUCKET,
			SUM(VOLUME_DELTA) AS "volumeSum"
		FROM
			table2
		WHERE timestamp > '2025-10-25 23:00:00' and timestamp < '2025-10-26 08:00:00+00'
		GROUP BY
			BUCKET
		ORDER BY
			BUCKET ASC
	)
SELECT *
FROM STATS
LEFT JOIN VOLUME USING (BUCKET);

ROLLBACK;
```

### PR DESCRIPTION
**Pull request by antekresic**
Gapfill was generating out of order buckets when DST shift occurs. This change accounts for the DST shift and bring gapfill function in line with time_bucket.

Fixes #8844

### CODE REVIEW

File: tsl/src/nodes/gapfill/gapfill_exec.c [hunk 1]
```diff
@@ -654,30 +654,72 @@ gapfill_advance_timestamp(GapFillState *state)
...
+					 * bucket boundaries using the same logic as time_bucket
+					 * with timezone (convert to local, bucket, convert back,
+					 * DST fix-up). Plain UTC arithmetic produces boundaries
+					 * that don't match time_bucket during DST transitions,
+					 * causing out-of-order output (issue #8844).
+					 */
+					Datum period = IntervalPGetDatum(state->gapfill_interval);
+					int64 period_us = state->gapfill_interval->time;
+					TimestampTz candidate = state->next_timestamp;
+					next = candidate;
```
Comment (svenklemm) [inline tsl/src/nodes/gapfill/gapfill_exec.c]:
```suggestion
					next = TimestampTzGetDatum(candidate);
```

**Review by svenklemm — APPROVED** [review]

**Review by Poroma-Banerjee — APPROVED** [review]

**Review by natalya-aksman — APPROVED** [review]
