### PR TITLE
Fix crash while using REINDEX TABLE CONCURRENTLY

### LINKED ISSUE #3122: REINDEX CONCURRENTLY leads to crash
Seems to be index concurrently implementation supposed to be run without active transaction, which is being violated while iterating chunks during REINDEX.

A way to reproduce:

```
CREATE TABLE reindex_test(time timestamp, temp float, PRIMARY KEY(time, temp));
CREATE UNIQUE INDEX reindex_test_time_unique_idx ON reindex_test(time);

SELECT create_hypertable('reindex_test', 'time', chunk_time_interval => 2628000000000);

INSERT INTO reindex_test VALUES ('2017-01-20T09:00:01', 17.5),
                                ('2017-01-21T09:00:01', 19.1),
                                ('2017-04-20T09:00:01', 89.5),
                                ('2017-04-21T09:00:01', 17.1),
                                ('2017-06-20T09:00:01', 18.5),
                                ('2017-06-21T09:00:01', 11.0);

REINDEX TABLE CONCURRENTLY reindex_test;
```

PostgreSQL logs:

Single node

```
TRAP: FailedAssertion("!cp->cache->release_on_commit", File: "/timescaledb/src/cache.c", Line: 313)

309│                                 /*
310│                                  * This assert makes sure that that we don't have a cache
311│                                  * leak when running with debugging
312│                                  */
313├───────────────────────────────> Assert(!cp->cache->release_on_commit);
```

Multi node (executed on a data node)
```
TRAP: FailedAssertion("GetTopTransactionIdIfAny() == InvalidTransactionId", File: "index.c", Line: 3343)
```

### PR DESCRIPTION
**Pull request by pmwkaa**
Fix crash while using REINDEX TABLE CONCURRENTLY

CONCURRENTLY option of the REINDEX TABLE is not supported and
leads to a crash when using with hypertable. Block it and print
the error message.

Fix #3122

### CODE REVIEW

**Comment by pmwkaa** [comment]
Index test on PG11 is failing, working on a template test file

**Review by svenklemm — APPROVED** [review]

File: src/process_utility.c [hunk 1]
```diff
@@ -1478,13 +1478,22 @@ process_reindex(ProcessUtilityArgs *args)
 			{
 				PreventCommandDuringRecovery("REINDEX");
 				ts_hypertable_permissions_check_by_id(ht->fd.id);
-
+#if PG12_GE
+				if (stmt->concurrent)
+				{
+					stmt->concurrent = false;
+					ereport(NOTICE,
+							(errmsg("REINDEX TABLE CONCURRENTLY is unsupported on a hypertable"),
```
Comment (erimatnor) [inline src/process_utility.c:1486]: It is unclear why this isn't an error. People can just drop CONCURRENTLY if they want to reindex. 

I also suggest formulating similar to this PostgreSQL error: ""concurrent index creation on system catalog tables is not supported":

```suggestion
							(errmsg("concurrent index creation on hypertables is not supported"),
```

File: src/process_utility.c [hunk 2]
```diff
@@ -1478,13 +1478,22 @@ process_reindex(ProcessUtilityArgs *args)
...
+							 errdetail("Using non-concurrent implementation.")));
```
Comment (erimatnor) [inline src/process_utility.c:1487]: Again, not sure we need this since we should probably just generate an error above.

```suggestion
							 errdetail("Performing non-concurrent reindexing instead.")));
```

File: src/process_utility.c (hunk 1 above)
Comment (pmwkaa) [reply src/process_utility.c:1486]: I am fine to throw an error here, I've seen that PostgreSQL actually also uses regular implementation in some cases and shows a NOTICE in such cases. I guess we should decide for yourselves

Comment (erimatnor) [reply src/process_utility.c:1486]: Can you point to the place in the PostgreSQL code where they do this? 

It seems odd to me, because if PostgreSQL has implemented  `CONCURRENTLY` I don't understand why they wouldn't use it, unless they do to this bait-and-switch depending on object type.

Comment (pmwkaa) [reply src/process_utility.c]: Sorry, I misunderstood when checked the code for first time, I had a different impression. Switched to produce the error as suggest. Please take a look at the updated PR info above

File: test/sql/CMakeLists.txt [hunk 3]
```diff
@@ -74,8 +74,11 @@ set(SOLO_TESTS
   alter
   alternate_users
   bgw_launcher
-  chunk_utils.sql
-  index
+  chunk_utils
+  index-11
```
Comment (gayyappan) [inline test/sql/CMakeLists.txt:78]: Could you clarify why we need to add this to SOLO_TESTS as well? We already have this in the templated list (line 68).

**Review by gayyappan — APPROVED** [review]
Question about test MakeList.

File: test/sql/CMakeLists.txt (hunk 3 above)
Comment (svenklemm) [reply test/sql/CMakeLists.txt:78]: SOLO_TESTS doesnt actually run any tests it's just a marker that those tests will not run in parallel with other tests but it still needs to be in one of the other lists to actually run

**Comment by svenklemm** [comment]
Needs changelog entry.

File: test/sql/CMakeLists.txt (hunk 3 above)
Comment (pmwkaa) [reply test/sql/CMakeLists.txt:78]: Well we had this before for `index` test. Since index test made as a template, I thought it is necessary to update it here as well. I am not aware why index test was put in the SOLO tests list in the first place, likely it has something to do with tablespace
