### PR TITLE
Fix broken CAgg with JOIN repair function

### LINKED ISSUE #5601: [Bug]: Segfault when repairing a CAgg with JOIN during the extension update
### What type of bug is this?

Crash

### What subsystems and features are affected?

Continuous aggregate

### What happened?

Segfault when repairing a CAgg with JOIN during the extension update from 2.10.1 to 2.10.2

### TimescaleDB version affected

2.10.1

### PostgreSQL version used

15.2

### What operating system did you use?

Ubuntu 22.04 x64

### What installation method did you use?

Source

### What platform did you run on?

Not applicable

### Relevant log output and stack trace

```bash
#0  0x00007f3bcef188ec in ?? () from /usr/lib/libc.so.6
#1  0x00007f3bceec9ea8 in raise () from /usr/lib/libc.so.6
#2  0x00007f3bceeb353d in abort () from /usr/lib/libc.so.6
#3  0x000055bd4c572944 in ExceptionalCondition (conditionName=0x7f3bc5491630 "ptr == NULL || nodeTag(ptr) == type", errorType=0x7f3bc549161f "FailedAssertion",
    fileName=0x7f3bc54915e0 "/usr/local/pg15_stable/include/postgresql/server/nodes/nodes.h", lineNumber=609) at assert.c:69
#4  0x00007f3bc541e2d8 in castNodeImpl (type=T_RangeTblRef, ptr=0x55bd4e4ab960) at /usr/local/pg15_stable/include/postgresql/server/nodes/nodes.h:609
#5  0x00007f3bc54263c2 in cagg_rebuild_view_definition (agg=0x55bd4e36ed80, mat_ht=0x55bd4e1b5658, force_rebuild=true) at /home/sven/projects/timescaledb/tsl/src/continuous_aggs/create.c:3034
#6  0x00007f3bc5426d0a in tsl_cagg_try_repair (fcinfo=0x7ffd4ae7a490) at /home/sven/projects/timescaledb/tsl/src/continuous_aggs/create.c:3198
#7  0x00007f3bc54fb252 in ts_cagg_try_repair (fcinfo=0x7ffd4ae7a490) at /home/sven/projects/timescaledb/src/cross_module_fn.c:96
#8  0x000055bd4c09f00b in ExecuteCallStmt (stmt=0x55bd4e36e298, params=0x55bd4e3d4ac0, atomic=true, dest=0x55bd4c8bd4e0 <spi_printtupDR>) at functioncmds.c:2290
#9  0x000055bd4c3b3198 in standard_ProcessUtility (pstmt=0x55bd4e36e140, queryString=0x55bd4e49b188 "CALL _timescaledb_internal.post_update_cagg_try_repair(vname, true)", readOnlyTree=true, context=PROCESS_UTILITY_QUERY,
    params=0x55bd4e3d4ac0, queryEnv=0x0, dest=0x55bd4c8bd4e0 <spi_printtupDR>, qc=0x7ffd4ae7b540) at utility.c:858
```

### How can we reproduce the bug?

1. Setup in TimescaleDB 2.10.1
```sql
CREATE TABLE ht_cagg_joins(
  day TIMESTAMPTZ NOT NULL,
  city text NOT NULL,
  temperature INT NOT NULL,
  device_id int NOT NULL
);

SELECT create_hypertable('ht_cagg_joins', 'day', chunk_time_interval => INTERVAL '1 day');

CREATE TABLE nt_cagg_joins (
  device_id int not null,
  name text,
  location text
);

CREATE MATERIALIZED VIEW cagg_joins WITH (timescaledb.continuous)
AS
SELECT
  time_bucket(INTERVAL '1 day', day) AS bucket,
  AVG(temperature),
  name
FROM ht_cagg_joins JOIN nt_cagg_joins
ON ht_cagg_joins.device_id = nt_cagg_joins.device_id
GROUP BY 1, 3;

SELECT * FROM cagg_joins; -- will segfault
```

3. Update to TimescaleDB 2.10.2
```sql
ALTER EXTENSION timescaledb UPDATE TO '2.10.2'; -- will segfault
```

### PR DESCRIPTION
**Pull request by fabriziomello**
The internal `cagg_rebuild_view_definition` function was trying to cast a pointer to `RangeTblRef` but it actually is a `RangeTblEntry`.

Fixed it by using the already existing `direct_query` data struct to check if there are JOINs in the CAgg to be repaired.

Fixes #5601

### CODE REVIEW

**Review by akuzm — APPROVED** [review]
Would be good to have some kind of test for this.

**Review by svenklemm — APPROVED** [review]

File: tsl/src/continuous_aggs/create.c [hunk 1]
```diff
@@ -3034,52 +3031,11 @@ cagg_rebuild_view_definition(ContinuousAgg *agg, Hypertable *mat_ht, bool force_
...
-		/* No joins in Cagg, no need to rebuild for this case */
-		relation_close(user_view_rel, NoLock);
-		return;
-	}
-
 	if (!agg->data.materialized_only)
 	{
 		final_query = destroy_union_query(final_query);
 	}
+
```
Comment (RafiaSabih) [inline tsl/src/continuous_aggs/create.c:3038]: (Nit) spurious line change

**Review by RafiaSabih — APPROVED** [review]

File: tsl/src/continuous_aggs/create.c [hunk 2]
```diff
@@ -3091,6 +3053,42 @@ cagg_rebuild_view_definition(ContinuousAgg *agg, Hypertable *mat_ht, bool force_
...
 	remove_old_and_new_rte_from_query(direct_query);
+
+	/*
+	 * If there is a join in CAggs then rebuild it definitley,
+	 * because v2.10.0 has created the definition with missing structs.
+	 */
+	if (force_rebuild)
+	{
+		ListCell *l;
+		foreach (l, direct_query->jointree->fromlist)
```
Comment (svenklemm) [inline tsl/src/continuous_aggs/create.c:3064]: should check for jointree being non-NULL here so we dont segfault

**Review by svenklemm — APPROVED** [review]

File: tsl/src/continuous_aggs/create.c (hunk 2 above)
Comment (fabriziomello) [reply tsl/src/continuous_aggs/create.c:3064]: fixed
