### PR TITLE
Keep locks after reading job status

### LINKED ISSUE #4293: [Bug]: Background Worker Scheduler crash
### What type of bug is this?

Crash

### What subsystems and features are affected?

Background worker, User-Defined Action (UDA)

### What happened?

After 6h to 8h, the TimescaleDB Background Worker Scheduler crashes right after the error `tuple concurrently updated`. There are no other logs at the same time so it looks to be correlated.

We're running some regular data processing using the jobs framework, right now there are 40 jobs registered for number crunching (each with a schedule interval of 10 minutes) and one management job. The management job is run every 5 minutes and checks a config table and then adds or deletes number crunching jobs based on the config, querying the `timescaledb_information.jobs` table each time. This has always worked during testing and when the scheduler job crashed I can rule out the possiblity that the management job attempted to add or delete any job.

After the scheduler job has crashed, we can get it back running using this:
```sql
SELECT _timescaledb_internal.restart_background_workers()
```

### TimescaleDB version affected

2.6.1

### PostgreSQL version used

14.2

### What operating system did you use?

Ubuntu 20.04.4 LTS x64

### What installation method did you use?

Deb/Apt

### What platform did you run on?

On prem/Self-hosted

### Relevant log output and stack trace

```
2022-05-04 15:29:14.011 CEST [111934] CONTEXT:  SQL statement "SELECT pg_sleep(0.1)"
        PL/pgSQL function do_work(integer,jsonb) line 3 at PERFORM
2022-05-04 15:29:14.011 CEST [111934] LOCATION:  ProcessInterrupts, postgres.c:3186
2022-05-04 15:29:14.012 CEST [48422] LOG:  00000: background worker "User-Defined Action [1057]" (PID 111934) exited with exit code 1
2022-05-04 15:29:14.012 CEST [48422] LOCATION:  LogChildExit, postmaster.c:3730
2022-05-04 15:29:14.044 CEST [48501] WARNING:  01000: failed to launch job 1033 "User-Defined Action [1033]": failed to start a background worker
2022-05-04 15:29:14.044 CEST [48501] LOCATION:  scheduled_bgw_job_transition_state_to, scheduler.c:320
2022-05-04 15:29:14.050 CEST [48501] WARNING:  01000: failed to launch job 1034 "User-Defined Action [1034]": failed to start a background worker
2022-05-04 15:29:14.050 CEST [48501] LOCATION:  scheduled_bgw_job_transition_state_to, scheduler.c:320
2022-05-04 15:29:14.055 CEST [48501] WARNING:  01000: failed to launch job 1019 "User-Defined Action [1019]": failed to start a background worker
2022-05-04 15:29:14.055 CEST [48501] LOCATION:  scheduled_bgw_job_transition_state_to, scheduler.c:320
2022-05-04 15:29:14.059 CEST [48501] WARNING:  01000: failed to launch job 1004 "User-Defined Action [1004]": failed to start a background worker
2022-05-04 15:29:14.059 CEST [48501] LOCATION:  scheduled_bgw_job_transition_state_to, scheduler.c:320
2022-05-04 15:29:14.066 CEST [48501] WARNING:  01000: failed to launch job 1010 "User-Defined Action [1010]": failed to start a background worker
2022-05-04 15:29:14.066 CEST [48501] LOCATION:  scheduled_bgw_job_transition_state_to, scheduler.c:320
2022-05-04 15:29:14.072 CEST [48501] WARNING:  01000: failed to launch job 1011 "User-Defined Action [1011]": failed to start a background worker
2022-05-04 15:29:14.072 CEST [48501] LOCATION:  scheduled_bgw_job_transition_state_to, scheduler.c:320
2022-05-04 15:29:49.861 CEST [48501] ERROR:  XX000: tuple concurrently updated
2022-05-04 15:29:49.861 CEST [48501] LOCATION:  simple_heap_update, heapam.c:4181
2022-05-04 15:29:49.867 CEST [48422] LOG:  00000: background worker "TimescaleDB Background Worker Scheduler" (PID 48501) exited with exit code 1
2022-05-04 15:29:49.867 CEST [48422] LOCATION:  LogChildExit, postmaster.c:3730
```

```
#0  errstart (elevel=21, domain=0x0) at utils/error/elog.c:341
#1  0x0000561417bfdb7c in errstart_cold (domain=0x0, elevel=21) at utils/error/elog.c:326
#2  simple_heap_update (relation=<optimized out>, otid=<optimized out>, tup=<optimized out>) at access/heap/heapam.c:4181
#3  0x0000561417d5e160 in CatalogTupleUpdate (heapRel=heapRel@entry=0x7f197eb910c0, otid=0x5614197710ac, tup=0x5614197710a8) at catalog/indexing.c:309
#4  0x00007f197eb15b26 in ts_catalog_update_tid_only (rel=0x7f197eb910c0, tid=<optimized out>, tuple=<optimized out>)
    at /usr/src/debug/timescaledb/src/ts_catalog/catalog.c:663
#5  0x00007f197eb15b4e in ts_catalog_update_tid (rel=<optimized out>, tid=<optimized out>, tuple=<optimized out>)
    at /usr/src/debug/timescaledb/src/ts_catalog/catalog.c:670
#6  0x00007f197eb1018c in bgw_job_stat_tuple_mark_start (ti=0x7ffe0420a810, data=<optimized out>) at /usr/src/debug/timescaledb/src/bgw/job_stat.c:152
#7  0x00007f197eb01d44 in ts_scanner_scan (ctx=ctx@entry=0x7ffe0420a810) at /usr/src/debug/timescaledb/src/scanner.c:451
#8  0x00007f197eb01da1 in ts_scanner_scan_one (ctx=0x7ffe0420a810, fail_if_not_found=false, item_type=0x7f197eb4ac05 "bgw job stat")
    at /usr/src/debug/timescaledb/src/scanner.c:468
#9  0x00007f197eb2e62a in bgw_job_stat_scan_one (indexid=0, nkeys=1, tuple_filter=0x0, lockmode=3, data=0x0, tuple_filter=0x0, 
    tuple_found=0x7f197eb10100 <bgw_job_stat_tuple_mark_start>, nkeys=1, scankey=0x7ffe0420a8f0, indexid=0)
    at /usr/src/debug/timescaledb/src/bgw/job_stat.c:59
#10 bgw_job_stat_scan_job_id.constprop.0 (bgw_job_id=bgw_job_id@entry=1012, tuple_found=tuple_found@entry=0x7f197eb10100 <bgw_job_stat_tuple_mark_start>, 
    data=data@entry=0x0, lockmode=lockmode@entry=3, tuple_filter=0x0) at /usr/src/debug/timescaledb/src/bgw/job_stat.c:73
#11 0x00007f197eb0eaab in ts_bgw_job_stat_mark_start (bgw_job_id=1012) at /usr/src/debug/timescaledb/src/bgw/job_stat.c:413
#12 0x00007f197eb0ec95 in mark_job_as_started (sjob=0x5614197912f8) at /usr/src/debug/timescaledb/src/bgw/scheduler.c:159
#13 scheduled_bgw_job_transition_state_to (sjob=sjob@entry=0x5614197912f8, new_state=new_state@entry=JOB_STATE_STARTED)
    at /usr/src/debug/timescaledb/src/bgw/scheduler.c:301
#14 0x00007f197eb0fa4d in scheduled_ts_bgw_job_start (bgw_register=0x0, sjob=0x5614197912f8) at /usr/src/debug/timescaledb/src/bgw/scheduler.c:389
#15 start_scheduled_jobs (bgw_register=0x0) at /usr/src/debug/timescaledb/src/bgw/scheduler.c:575
#16 ts_bgw_scheduler_process (run_for_interval_ms=<optimized out>, bgw_register=0x0) at /usr/src/debug/timescaledb/src/bgw/scheduler.c:763
#17 0x00007f197eb0fc9a in ts_bgw_scheduler_main (fcinfo=fcinfo@entry=0x7ffe0420aa90) at /usr/src/debug/timescaledb/src/bgw/scheduler.c:888
#18 0x0000561418154d38 in DirectFunctionCall1Coll (func=0x7f197eb0fc20 <ts_bgw_scheduler_main>, collation=collation@entry=0, arg1=arg1@entry=0)
    at utils/fmgr/fmgr.c:801
#19 0x00007f198b003974 in ts_bgw_db_scheduler_entrypoint (fcinfo=<optimized out>) at /usr/src/debug/timescaledb/src/loader/bgw_launcher.c:947
#20 0x0000561417f69888 in StartBackgroundWorker () at postmaster/bgworker.c:875
#21 0x0000561417f76726 in do_start_bgworker (rw=<optimized out>) at postmaster/postmaster.c:5866
#22 maybe_start_bgworkers () at postmaster/postmaster.c:6091
#23 0x0000561417f7697d in sigusr1_handler (postgres_signal_arg=<optimized out>) at postmaster/postmaster.c:5255
#24 <signal handler called>
#25 0x00007f198a204ab9 in select () from target:/usr/lib/libc.so.6
#26 0x0000561417f7788e in ServerLoop () at postmaster/postmaster.c:1709
#27 0x0000561417f794e5 in PostmasterMain (argc=3, argv=0x56141967f2f0) at postmaster/postmaster.c:1417
#28 0x0000561417c87360 in main (argc=3, argv=0x56141967f2f0) at main/main.c:209
```

### How can we reproduce the bug?

Run this in a vanilla database (I used Docker locally) and observe the logs. 

```sql
CREATE OR REPLACE PROCEDURE do_work(job_id int, config jsonb)
AS $func$
BEGIN
  PERFORM pg_sleep(0.1);
  PERFORM alter_job(job_id, next_start => now() + '1 seconds');
END;
$func$
LANGUAGE plpgsql;

DO $$ BEGIN
FOR i IN 1..100 LOOP
  PERFORM add_job(
    proc => 'do_work',
    schedule_interval => '5 second'
  );
END LOOP;
END; $$;
```

And then call `alter_job()` in quick succession:

```bash
watch -n0.2 "psql -c 'select public.alter_job(job_id, next_start => now()) from timescaledb_information.jobs'"
```

### PR DESCRIPTION
**Pull request by mkindahl**
When reading the job status table `bgw_job_stat` and after that
updating it, locks where released after the read, allowing a competing
session to update the job status and trigger a concurrent update error
either in a session doing the update or in the scheduler. Since the
scheduler does not recover after aborting with an error, this caused
the background worker subsystem to stop and not start new jobs.

This commit fixes this by upgrading `RowExclusiveLock` to
`ShareRowExclusiveLock` to ensure that not two sessions tries to update
the row at the same time, remove an initial speculative lock
that are taken when a job status row can be added, and also keeps the
lock until the end of the transaction to prevent other sessions to
update. Since these updating transactions are short, it should not
cause other threads to block long.

Fixes #4293

### CODE REVIEW

**Comment by mkindahl** [comment]
> Thanks for working on this bug and finding a solution! I understand that the current approach does not entirely solve the underlying issue but that it should already provide a remedy to the issue we're facing. Any chances this could go into a release any time soon?

@daniel-k I had to put this on hold temporarily. I'll see if I can pick it up this week. Does that mean you have managed to verify that the patch solves the issue you have?

**Comment by daniel-k** [comment]
>  Does that mean you have managed to verify that the patch solves the issue you have?

Unfortunately no. Is there a build of the TSDB extension based on this branch so I could easily install it in our dev/testing system? And would I be able to go back to the old version afterwards? We're running self-hosted PG14 on Ubuntu 20.04 currently with TSDB 2.6.1.

File: src/bgw/job_stat.c [hunk 1]
```diff
@@ -409,25 +414,16 @@ bgw_job_stat_insert_relation(Relation rel, int32 bgw_job_id, bool mark_start,
...
 ts_bgw_job_stat_mark_start(int32 bgw_job_id)
 {
-	/* Use double-check locking */
+	Relation rel =
+		table_open(catalog_get_table_id(ts_catalog_get(), BGW_JOB_STAT), ShareRowExclusiveLock);
 	if (!bgw_job_stat_scan_job_id(bgw_job_id,
 								  bgw_job_stat_tuple_mark_start,
 								  NULL,
 								  NULL,
 								  RowExclusiveLock))
```
Comment (mfundul) [inline src/bgw/job_stat.c:423]:
```suggestion
		table_open(catalog_get_table_id(ts_catalog_get(), BGW_JOB_STAT), ShareRowExclusiveLock);
	if (!bgw_job_stat_scan_job_id(bgw_job_id,
								  bgw_job_stat_tuple_mark_start,
								  NULL,
								  NULL,
								  ShareRowExclusiveLock))
```
I don't quite understand what's going on here. Do we take 2 different locks on the same table at the same time, where one is a subset of the other?

File: src/bgw/job_stat.c [hunk 2]
```diff
@@ -492,24 +488,15 @@ ts_bgw_job_stat_upsert_next_start(int32 bgw_job_id, TimestampTz next_start)
...
-		/* Recheck while having a self-exclusive lock */
-		if (!bgw_job_stat_scan_job_id(bgw_job_id,
-									  bgw_job_stat_tuple_set_next_start,
-									  NULL,
-									  &next_start,
-									  RowExclusiveLock))
-			bgw_job_stat_insert_relation(rel, bgw_job_id, false, next_start);
-		table_close(rel, ShareRowExclusiveLock);
-	}
+		bgw_job_stat_insert_relation(rel, bgw_job_id, false, next_start);
```
Comment (mfundul) [inline src/bgw/job_stat.c:498]: Same as above in `ts_bgw_job_stat_mark_start()`.

File: src/bgw/job_stat.c (hunk 1 above)
Comment (mkindahl) [reply src/bgw/job_stat.c:455]: No, the `ShareRowExclusiveLock` is not a superset of `RowExclusiveLock` and the difference is that `ShareRowExclusiveLock` is self-exclusive while `RowExclusiveLock` is not. We need to pass a lock mode to `table_open` (this is asserted) and since the `RowExclusiveLock` is released after the scan, we use the `ShareRowExclusiveLock` to block other sessions from updating the lock before we have had the chance to insert a new row (if it is needed).

File: src/bgw/job_stat.c (hunk 2 above)
Comment (mkindahl) [reply src/bgw/job_stat.c:530]: Same answer as above as well.

**Review by mfundul — APPROVED** [review]

**Comment by daniel-k** [comment]
@mkindahl 
I've deployed the new 2.8.1 release a couple of days ago and our bug seems to be solved. Thanks a bunch!

**Comment by mkindahl** [comment]
@daniel-k Glad to hear that it worked. :)
