### PR TITLE
Fix possible segfault in planner

### LINKED ISSUE #184: Segfault in the hypertable cache on insert path.
Using parallel inserts the hypertable_cache segfaults. The bug is present in `0.4.0` but not present in `0.3.0`.

```
#0  cache_fetch (cache=0x0, query=query@entry=0x7fffccd19430) at src/cache.c:106
#1  0x00007fe01a5c63bc in hypertable_cache_get_entry_with_table (cache=<optimized out>, relid=<optimized out>, schema=schema@entry=0x0,
    table=table@entry=0x0) at src/hypertable_cache.c:159
#2  0x00007fe01a5c63e2 in hypertable_cache_get_entry (cache=<optimized out>, relid=<optimized out>) at src/hypertable_cache.c:148
```

Reported by @yadid. Thank you.

### PR DESCRIPTION
**Pull request by cevian**
Previously, the planner had a global context that kept a reference to
the hypertable cache. The reference counting system in that global
context was unsafe and could lead to a segfault. This PR gets rid
of that context and makes the whole system a lot safer.

Fixes #184

### CODE REVIEW

File: src/planner.c [hunk 1]
```diff
@@ -418,46 +409,32 @@ modifytable_plan_walker(Plan **planptr, void *pctx)
...
-	if (gpc.extension_is_loaded)
+	if (extension_is_loaded())
 	{
 		HypertableQueryCtx context;
 
 		/* replace call to main table with call to the replica table */
 		context.parse = parse;
 		context.parent = parse;
 		context.cmdtype = parse->commandType;
+		context.hcache = hypertable_cache_pin();
```
Comment (erimatnor) [inline src/planner.c]: Nit/suggestion. Do C99-style struct init? Or, wrap in a function?

```
HypertableQueryCtx context = {
    .parse = parse,
    .parent = parse,
    ....
};
```

File: src/planner.c [hunk 2]
```diff
@@ -528,29 +505,59 @@ timescaledb_set_rel_pathlist(PlannerInfo *root,
...
+	if (!should_optimize_query(ht))
 		goto out_release;
 
-	ht = hypertable_cache_get_entry(gpc.hcache, rte->relid);
+	if (guc_optimize_non_hypertables)
+	{
+		/* if optimizing all tables, apply optimization to any table */
+		sort_transform_optimization(root, rel);
+	}
+	else if (ht != NULL && rel->reloptkind == RELOPT_OTHER_MEMBER_REL)
```
Comment (erimatnor) [inline src/planner.c]: Seems here you should first check for `RELOPT_OTHER_MEMBER_REL` then do the hypertable lookup rather than the other way around. Although I see that the hypertable is also used for the append optimization. Is there a way to make this cleaner and only lookup the hypertable if needed?

File: src/planner.c [hunk 3]
```diff
@@ -528,29 +505,59 @@ timescaledb_set_rel_pathlist(PlannerInfo *root,
...
-		IS_DUMMY_REL(rel) ||
-		!should_optimize_query() ||
-		!OidIsValid(rte->relid))
-		goto out_release;
+	if (!extension_is_loaded() || IS_DUMMY_REL(rel) || !OidIsValid(rte->relid))
+		return;
 
-	sort_transform_optimization(root, rel);
+	hcache = hypertable_cache_pin();
+	ht = hypertable_cache_get_entry(hcache, rte->relid);
```
Comment (erimatnor) [inline src/planner.c]: This lookup should probably move to after `RELOPT_OTHER_MEMBER` check (see comment below).

File: src/planner.c [hunk 4]
```diff
@@ -521,36 +495,96 @@ should_optimize_append(const Path *path)
 	return false;
 }
 
+
+static bool
```
Comment (erimatnor) [inline src/planner.c]: this could be made inline or a #define

File: src/planner.c [hunk 5]
```diff
@@ -521,36 +495,96 @@ should_optimize_append(const Path *path)
...
+is_append_child(RelOptInfo *rel, RangeTblEntry *rte)
+{
+	return rel->reloptkind == RELOPT_OTHER_MEMBER_REL &&
+		rte->inh == false &&
+		rel->rtekind == RTE_RELATION &&
+		rte->relkind == RELKIND_RELATION;
+}
+
+static bool
```
Comment (erimatnor) [inline src/planner.c]: same here

Comment (cevian) [reply src/planner.c]: fixed

**Comment by mfreed** [comment]
Thanks to @yadid for discovering this issue and assisting us with debugging it.
