### PR TITLE
Block data migration for distributed hypertables

### LINKED ISSUE #2230: Block migrate_data for distributed hypertables
The functionality for migrating data from an existing table when creating a distributed hypertable does not work currently.

Fixing this is non-trivial, so we block this usage.

### PR DESCRIPTION
**Pull request by mkindahl**
Option `migrate_data` does not currently work for distributed
hypertables, so we block it for the time being and generate an error if
an attempt is made to migrate data when creating a distributed
hypertable.

Fixes #2230

### CODE REVIEW

File: src/hypertable.c [hunk 1]
```diff
@@ -1835,6 +1835,11 @@ ts_hypertable_create_internal(PG_FUNCTION_ARGS, bool is_dist_call)
 				(errcode(ERRCODE_INVALID_PARAMETER_VALUE),
 				 errmsg("invalid main_table: cannot be NULL")));
 
+	if (migrate_data && is_dist_call)
+		ereport(ERROR,
+				(errcode(ERRCODE_INVALID_PARAMETER_VALUE),
```
Comment (pmwkaa) [inline src/hypertable.c:1840]: nit: it's up to you, but maybe use FEATURE_NOT_SUPPORTED as an error code instead?

**Review by pmwkaa — APPROVED** [review]

**Review by svenklemm — APPROVED** [review]

File: src/hypertable.c (hunk 1 above)
Comment (mkindahl) [reply src/hypertable.c]: It is better, so switched.
