### PR TITLE
Fix bug with INSERT INTO...SELECT

### LINKED ISSUE #24: Inserting from Hypertable into another table does not work
E.g., this query does not work:

```
INSERT INTO rides_test (SELECT * from rides LIMIT 1);
```

### PR DESCRIPTION
**Pull request by cevian**
Previously, INSERT INTO...SELECT FROM hypertable was broken. This was
caused by incorrectly tracking the commandType in change_name_walker.
Fixes #24.

### CODE REVIEW

File: src/planner.c [hunk 1]
```diff
@@ -74,8 +75,12 @@ change_table_name_walker(Node *node, void *context)
 
 	if (IsA(node, Query))
 	{
+		ChangeTableNameCtx *ctx = (ChangeTableNameCtx *) context;
+		CmdType old = ctx->commandType;
+		ctx->commandType = ((Query *) node)->commandType;
 		return query_tree_walker((Query *) node, change_table_name_walker,
 								 context, QTW_EXAMINE_RTES);
+		ctx->commandType = old;
```
Comment (olofr) [inline src/planner.c]: Could you explain why there is code after the return statement here ?

Comment (cevian) [inline src/planner.c]: Good catch. Fixed.
