### PR TITLE
Include internal dependencies in delete of chunks

### LINKED ISSUE #1889: "drop_chunks with cascade_to_materializations => FALSE" not working with unique contraints
**Relevant system information:**
 - OS: Ubuntu 18.04
 - PostgreSQL version: 11.7
 - TimescaleDB versio: 1.7.0
 - Installation method: apt install

**Describe the bug**
drop chunks not working with unique contraints and continues aggregates.

**To Reproduce**
1. Setup Schema
```SQL
CREATE EXTENSION IF NOT EXISTS timescaledb CASCADE;

CREATE TABLE IF NOT EXISTS client_ids (id SERIAL PRIMARY KEY, name TEXT NOT NULL, UNIQUE(name));

CREATE TABLE IF NOT EXISTS data_records (
    time TIMESTAMPTZ NOT NULL, 
    clientId INT NOT NULL REFERENCES client_ids(id),
    value DOUBLE PRECISION, 
    UNIQUE(time, clientId));

SELECT create_hypertable('data_records',
 'time',
  chunk_time_interval => interval '1h',
  if_not_exists => TRUE);

CREATE VIEW data_records1m 
    WITH (timescaledb.continuous, timescaledb.refresh_lag = '1m', timescaledb.refresh_interval = '1m')
    AS 
        SELECT time_bucket('1m', time) as bucket, 
            clientId, 
            avg(value) as value_avg,
            max(value)-min(value) as value_spread 
        FROM data_records GROUP BY bucket, clientId;
```
2. Seed Example Data
```SQL
INSERT INTO public.client_ids(name)
	VALUES ('test-client');

INSERT INTO public.data_records(
	"time", clientid, value)
	VALUES 
		('2020-05-01T00:00:00+00:00', 1, 3.14),
		('2020-05-02T00:00:00+00:00', 1, 3.14),
		('2020-05-03T00:00:00+00:00', 1, 3.14),
                ('2020-05-04T00:00:00+00:00', 1, 3.14),
                ('2020-05-05T00:00:00+00:00', 1, 3.14),
                ('2020-05-06T00:00:00+00:00', 1, 3.14),
                ('2020-05-07T00:00:00+00:00', 1, 3.14),
                ('2020-05-08T00:00:00+00:00', 1, 3.14),
                ('2020-05-09T00:00:00+00:00', 1, 3.14),
                ('2020-05-10T00:00:00+00:00', 1, 3.14),
                ('2020-05-11T00:00:00+00:00', 1, 3.14),
                ('2020-05-12T00:00:00+00:00', 1, 3.14);
```
3. drop chunks
```SQL
ALTER VIEW data_records1m SET (
   timescaledb.ignore_invalidation_older_than = '9 days'
);

SELECT drop_chunks(INTERVAL '10 days',
    'data_records', cascade_to_materializations => FALSE);
```

**Expected behavior**
Chunks are dropped on main hypertable and aggregates will still be available

**Actual behavior**
drop_chunks will raise an error: (Sorry for german error messages).

It says: > cannot delete index _timescaledb_internal."1_2_data_records_time_clientid_key" because it is used by constraint 1_2_data_records_time_clientid_key from table _timescaledb_internal._hyper_1_1_chunk 

> HINWEIS:  making sure all invalidations for public.data_records1m have been processed prior to dropping chunks

> ERROR:  FEHLER:  kann Index _timescaledb_internal."1_2_data_records_time_clientid_key" nicht löschen, wird von Constraint 1_2_data_records_time_clientid_key für Tabelle _timescaledb_internal._hyper_1_1_chunk benötigt
HINT:  Sie können stattdessen Constraint 1_2_data_records_time_clientid_key für Tabelle _timescaledb_internal._hyper_1_1_chunk löschen.

> SQL state: 2BP01

### PR DESCRIPTION
**Pull request by mkindahl**
If a hypertable is created with an index on it and a continuous
aggregate is further defined on the hypertable, it will create an
internal dependency between the chunks of the hypertable and the chunks
of the continuous aggregate.

When dropping chunks with `cascade_to_materialization` set to `FALSE`,
this will generate an error since the delete is not cascaded to the
internal dependencies.

This commit fixes this by collecting the internal dependencies and
using `performMultipleDelete` rather than `performDelete` to delete
several objects as one operation.

Fixes #1889

### CODE REVIEW

**Comment by mkindahl** [comment]
The test is easily reproducible using the test case in the issue, but when adding it to an existing test or putting it in a separate file, it generates either the error

```
ERROR: older_than must be greater than the timescaledb.ignore_invalidation_older_than parameter of public.records_monthly
```

or 

```
+SELECT drop_chunks(INTERVAL '10 days', 'records',
+       cascade_to_materializations => FALSE);
+ERROR:  the continuous aggregate public.records_monthly is too far behind
+DETAIL:  lowest_completion_time: -290308-12-21 21:11:18 LMT, older_than_time: 2020-05-08 10:49:47 CEST
```

File: src/chunk_index.c [hunk 1]
```diff
@@ -606,7 +660,12 @@ chunk_index_tuple_delete(TupleInfo *ti, void *data)
 		};
 
 		if (OidIsValid(idxobj.objectId))
-			performDeletion(&idxobj, DROP_RESTRICT, 0);
+		{
+			ObjectAddresses *objects = new_object_addresses();
+			chunk_collect_objects_for_deletion(&idxobj, objects);
```
Comment (gayyappan) [inline src/chunk_index.c:665]: Could you comment on the difference between collecting the dependencies and dropping them explicitly here versus
`` performDeletion(&idxobj, DROP_CASCCADE,...); ```

Comment (mkindahl) [reply src/chunk_index.c:680]: Done.

**Comment by mkindahl** [comment]
> Code changes look good. Could you add a test case as well?

That is the problem. When I try to add a test case, I run into other problems as outlined above.

**Comment by mkindahl** [comment]
> > Code changes look good. Could you add a test case as well?
> 
> That is the problem. When I try to add a test case, I run into other problems. See earlier comment.

Managed to construct a test case that works. Split it into two commits to demonstrate that it works. I will merge them before pushing.

**Comment by mkindahl** [comment]
> Change looks good, but it feels like it is still require testing if not the original case but something which will explicitly use this functionality

I managed to create a test case. Please check.

File: tsl/test/sql/continuous_aggs_drop_chunks.sql [hunk 2]
```diff
@@ -0,0 +1,53 @@
+\c :TEST_DBNAME :ROLE_SUPERUSER
```
Comment (pmwkaa) [inline tsl/test/sql/continuous_aggs_drop_chunks.sql:1]: Looks like you are missing a License header here

Comment (mkindahl) [reply tsl/test/sql/continuous_aggs_drop_chunks.sql:5]: Fixed.

Comment (mkindahl) [reply tsl/test/sql/continuous_aggs_drop_chunks.sql:5]: Added.
