### PR TITLE
Fix support for complex aggregate expression

### LINKED ISSUE #2616: Continuous aggregate view with time_bucket expression in target list fails
**Relevant system information:**
 - OS: CentOS Linux release 8.2.2004 (Core)
 - PostgreSQL version (output of `postgres --version`): 12.4
 - TimescaleDB version (output of `\dx` in `psql`): 1.7.4 
 - Installation method: yum

**Describe the bug**
1. The continuous aggregation (cagg) is not aggregating my data. All background worker runs fail, whereas calling the view I seem to get correct results (not materialized)
2. During one of my example test runs it worked as I would have expected it, but inserting a `null` in a value (not timestamp or partition) column makes the continuous aggregation (cagg) fail.

**To Reproduce**
1. Create the following example table, cagg and insert some example data (you may want to adjust the timestamp to something recent)
```sql
CREATE TABLE IF NOT EXISTS water_consumption
(
    sensor_id   integer      not null,
    timestamp   timestamp(0) not null,
    water_index integer,
    constraint water_consumption_pkey
        primary key (sensor_id, timestamp)
);

SELECT create_hypertable('water_consumption', 'timestamp', 'sensor_id', 2);

CREATE INDEX IF NOT EXISTS water_consumption_idx
    on water_consumption (timestamp ASC);

CREATE VIEW water_consumption_aggregation_minute
            WITH (timescaledb.continuous, timescaledb.ignore_invalidation_older_than='6 days')
AS
SELECT sensor_id,
       time_bucket(INTERVAL '1 minute', timestamp) + '1 minute' AS timestamp,
       (max(water_index) - min(water_index))                    AS water_consumption
FROM water_consumption
GROUP BY sensor_id, time_bucket(INTERVAL '1 minute', timestamp);


INSERT INTO public.water_consumption (sensor_id, timestamp, water_index) VALUES (1, '2020-11-03 09:42:30', 1030);
INSERT INTO public.water_consumption (sensor_id, timestamp, water_index) VALUES (1, '2020-11-03 09:42:40', 1032);
INSERT INTO public.water_consumption (sensor_id, timestamp, water_index) VALUES (1, '2020-11-03 09:42:50', 1035);
INSERT INTO public.water_consumption (sensor_id, timestamp, water_index) VALUES (1, '2020-11-03 09:43:30', 1040);
INSERT INTO public.water_consumption (sensor_id, timestamp, water_index) VALUES (1, '2020-11-03 09:43:40', 1045);
INSERT INTO public.water_consumption (sensor_id, timestamp, water_index) VALUES (1, '2020-11-03 09:43:50', 1050);
INSERT INTO public.water_consumption (sensor_id, timestamp, water_index) VALUES (1, '2020-11-03 09:44:30', 1052);
INSERT INTO public.water_consumption (sensor_id, timestamp, water_index) VALUES (1, '2020-11-03 09:44:40', 1057);
INSERT INTO public.water_consumption (sensor_id, timestamp, water_index) VALUES (1, '2020-11-03 09:44:50', 1060);
INSERT INTO public.water_consumption (sensor_id, timestamp, water_index) VALUES (1, '2020-11-03 09:45:30', 1063);
INSERT INTO public.water_consumption (sensor_id, timestamp, water_index) VALUES (1, '2020-11-03 09:45:40', 1067);
INSERT INTO public.water_consumption (sensor_id, timestamp, water_index) VALUES (1, '2020-11-03 09:45:50', 1070);
```
2. Run following commands to get cagg info
```sql
SELECT * FROM timescaledb_information.continuous_aggregates;

SELECT * FROM timescaledb_information.continuous_aggregate_stats;
```
3. In the stats I can see `total_runs` == `total_failures` when i let it run for a few minutes / hours
4. The DB logs give me this:
```
2020-11-03 10:42:43.826 CET [2567182] LOG:  materializing continuous aggregate public.water_consumption_aggregation_minute: nothing to invalidate, new range up to 2020-11-03 09:46:00
2020-11-03 10:42:43.828 CET [2567182] LOG:  job 1039 threw an error
2020-11-03 10:42:43.828 CET [2567182] ERROR:  could not find replacement targetlist entry for attno 5
2020-11-03 10:42:43.828 CET [2567182] CONTEXT:  SQL statement "INSERT INTO _timescaledb_internal._materialized_hypertable_37 SELECT * FROM _timescaledb_internal._partial_view_37 AS I WHERE I.time_partition_col >= '-infinity' AND I.time_partition_col < '2020-11-03 09:46:00';
2020-11-03 10:42:43.830 CET [2417245] LOG:  background worker "Continuous Aggregate Background Job" (PID 2567182) exited with exit code 1
```

5. Additionally I have the following outputs:
```sql
> \d _timescaledb_internal._materialized_hypertable_37`

             Table "_timescaledb_internal._materialized_hypertable_37"
       Column       |            Type             | Collation | Nullable | Default
--------------------+-----------------------------+-----------+----------+---------
 sensor_id          | integer                     |           |          |
 timestamp          | timestamp without time zone |           |          |
 agg_3_3            | bytea                       |           |          |
 agg_3_4            | bytea                       |           |          |
 time_partition_col | timestamp without time zone |           | not null |
 chunk_id           | integer                     |           |          |
Indexes:
    "_materialized_hypertable_37_sensor_id_time_partition_col_idx" btree (sensor_id, time_partition_col DESC)
    "_materialized_hypertable_37_time_partition_col_idx" btree (time_partition_col DESC)
    "_materialized_hypertable_37_timestamp_time_partition_col_idx" btree ("timestamp", time_partition_col DESC)
Triggers:
    ts_insert_blocker BEFORE INSERT ON _timescaledb_internal._materialized_hypertable_37 FOR EACH ROW EXECUTE FUNCTION _timescaledb_internal.insert_blocker()


> \d+ _timescaledb_internal._partial_view_37`
                               View "_timescaledb_internal._partial_view_37"
       Column       |            Type             | Collation | Nullable | Default | Storage  | Description
--------------------+-----------------------------+-----------+----------+---------+----------+-------------
 sensor_id          | integer                     |           |          |         | plain    |
 timestamp          | timestamp without time zone |           |          |         | plain    |
 agg_3_3            | bytea                       |           |          |         | extended |
 agg_3_4            | bytea                       |           |          |         | extended |
 time_partition_col | timestamp without time zone |           |          |         | plain    |
 chunk_id           | integer                     |           |          |         | plain    |
View definition:
 SELECT water_consumption.sensor_id,
    time_bucket('00:01:00'::interval, water_consumption."timestamp") + '00:01:00'::interval AS "timestamp",
    _timescaledb_internal.partialize_agg(max(water_consumption.water_index)) AS agg_3_3,
    _timescaledb_internal.partialize_agg(min(water_consumption.water_index)) AS agg_3_4,
    time_bucket('00:01:00'::interval, water_consumption."timestamp") AS time_partition_col,
    _timescaledb_internal.chunk_id_from_relid(water_consumption.tableoid) AS chunk_id
   FROM water_consumption
  GROUP BY water_consumption.sensor_id, (time_bucket('00:01:00'::interval, water_consumption."timestamp")), (_timescaledb_internal.chunk_id_from_relid(water_consumption.tableoid));
```

**Expected behavior**
The main idea is to have the cagg run as background worker and materialize my aggregations over time, also with the possibility of value (not timestamp or partition) column containing `null`

**Actual behavior**
Manually running the `SELECT` part of my cagg works just fine, however the cagg almost never successfully completes a run. And if does entering a `null`value into a value column makes it fail.

**Additional context / Bonus points**
While this section is called additional context, I would like to ask if someone would have a better idea to aggregate the data into specified timeslices. The idea is to aggregate the consumed water, however since I only take the MAX - MIN value of the timeslice, I lose some part of that aggregation. 
eg: I have a measurements at 11:59:50, 12:00:15, 12:00:30, 12:00:45, 12:00:59, ...
When I run my cagg for the measurements which happened between 12:00:00 and 12:01:00, it takes the last 4 timestamps, but the consumption from 11:59:50 to 12:00:15 is lost and will not be included in that aggregation, nor in the previous one. Ideas?

### PR DESCRIPTION
**Pull request by k-rus**
Fixes support for continuous aggregates when the view query contains
an expression with several aggregates, e.g., `max(val) - min(val)`.
Usage of continuous aggregates with such expression was producing
errors if the aggregate expression was not the last in the SELECT
clause or not all GROUP BY expressions were present in the SELECT
clause.

An expression with several aggregates is materialized with partials
per aggregate. For example, `max(val) - min(val)` will be materialized
in two partial entry columns: one for `max` and one for `min`. Thus
all columns in the materialized hypertable should account for the
number of partials and cannot just use the position in the original
query. This fix makes sure to account for such case.

Fixes #2616

### CODE REVIEW

File: tsl/test/sql/continuous_aggs.sql [hunk 1]
```diff
@@ -930,3 +930,90 @@ GROUP BY
...
+CREATE TABLE water_consumption
+(
+    sensor_id   integer      NOT NULL,
+    timestamp   timestamp(0) NOT NULL,
+    water_index integer
+);
+
+SELECT create_hypertable('water_consumption', 'timestamp', 'sensor_id', 2);
+
+INSERT INTO public.water_consumption (sensor_id, timestamp, water_index) VALUES (1, '2010-11-03 09:42:30', 1030);
```
Comment (erimatnor) [inline tsl/test/sql/continuous_aggs.sql:945]: Probably cleaner and faster to do a single statement:

```
INSERT INTO public.water_consumption (sensor_id, timestamp, water_index) VALUES 
(1, '2010-11-03 09:42:30', 1030),
(1, '2010-11-03 09:42:50', 1035),
...
```

File: tsl/test/sql/continuous_aggs.sql [hunk 2]
```diff
@@ -930,3 +930,90 @@ GROUP BY
...
+       time_bucket(INTERVAL '1 minute', timestamp) + '1 minute' AS timestamp,
+       (max(water_index) - min(water_index))                    AS water_consumption
+FROM water_consumption
+GROUP BY sensor_id, time_bucket(INTERVAL '1 minute', timestamp)
+WITH NO DATA;
+
+CALL refresh_continuous_aggregate('water_consumption_aggregation_minute', NULL, NULL);
+
+-- The results of the view and the query over hypertable should be the same
+SELECT * FROM water_consumption_aggregation_minute;
```
Comment (erimatnor) [inline tsl/test/sql/continuous_aggs.sql:972]: I would suggest adding ORDER BY here on both view and raw query here to avoid flaky behavior. I guess also applies below.

**Review by erimatnor — APPROVED** [review]
LGTM, just a couple of nits and suggestions.

File: tsl/test/sql/continuous_aggs.sql (hunk 2 above)
Comment (k-rus) [reply tsl/test/sql/continuous_aggs.sql]: Good point! Fixed.

File: tsl/test/sql/continuous_aggs.sql (hunk 1 above)
Comment (k-rus) [reply tsl/test/sql/continuous_aggs.sql]: Originally I copied from the issue. Fixed according the suggestion.

File: tsl/src/continuous_aggs/create.c [hunk 3]
```diff
@@ -1184,6 +1184,14 @@ mattablecolumninfo_addentry(MatTableColumnInfo *out, Node *input, int original_q
 			part_te = (TargetEntry *) copyObject(input);
 			/*need to project all the partial entries so that materialization table is filled */
 			part_te->resjunk = false;
+
+			/* Partial entry should have actual position in the column list of the materialization
```
Comment (gayyappan) [inline tsl/src/continuous_aggs/create.c:1188]: Could you remove this comment?

**Review by gayyappan — APPROVED** [review]
Changes look good. Could you please remove the code comment.

File: tsl/test/expected/continuous_aggs.out [hunk 4]
```diff
@@ -1276,3 +1276,138 @@ SELECT * FROM mat_types;
...
+         1 | Wed Nov 03 09:45:00 2010 |                 8
+         1 | Wed Nov 03 09:44:00 2010 |                10
+(4 rows)
+
+SELECT sensor_id,
+       time_bucket(INTERVAL '1 minute', timestamp) + '1 minute' AS timestamp,
+       (max(water_index) - min(water_index))                    AS water_consumption
+FROM water_consumption
+GROUP BY sensor_id, time_bucket(INTERVAL '1 minute', timestamp)
+ORDER BY water_consumption;
```
Comment (erimatnor) [inline tsl/test/expected/continuous_aggs.out:1332]: This works, but seems more logical to order by timestamp (bucket).

Comment (k-rus) [reply tsl/test/expected/continuous_aggs.out:1332]: @erimatnor It doesn't work to use `timestamp` for one test, where `time_bucket` is not part of the select.

Comment (k-rus) [reply tsl/test/expected/continuous_aggs.out:1332]: It was an obvious thing to do first, but it cannot be used for all test queries and I prefer to use the same column in order by for all columns.

File: tsl/src/continuous_aggs/create.c (hunk 3 above)
Comment (k-rus) [reply tsl/src/continuous_aggs/create.c]: Fixed
