### PR TITLE
Fix subquery errors when using AsyncAppend

### LINKED ISSUE #2511: Multinode: CTE query fails with "request already in progress"
**Relevant system information:**
 - OS: Ubuntu 20.04
 - PostgreSQL version: 12.3 (Ubuntu 12.3-1.pgdg20.04+1)
 - TimescaleDB version: 2.0.0-beta5 (multinode)
 - Installation method: apt

**Describe the bug**
Attempting to get the "Top 10" time series for a metric via the following CTE query fails as indicated:
```sql
WITH top_n AS (
SELECT
  name,
  avg(core_util_p99) AS "value"
FROM
  capacity.pool_30m
WHERE
  "timestamp" BETWEEN '2020-09-30T22:38:23.751Z' AND '2020-10-01T22:38:23.752Z'
GROUP BY 1
ORDER BY 2 DESC
LIMIT 10
)
SELECT
  time_bucket('60s', "timestamp") AS "time",
  name AS "service",
  avg(core_util_p99) AS "value"
FROM
  capacity.pool_30m INNER JOIN top_n USING (name)
WHERE
  "timestamp" BETWEEN '2020-09-30T22:38:23.751Z' AND '2020-10-01T22:38:23.752Z'
GROUP BY 1,2
ORDER BY 1,2;
ERROR:  failed to set single row mode for SELECT name, core_util_p99 FROM capacity.pool_30m WHERE _timescaledb_internal.chunks_in(capacity.pool_30m.*, ARRAY[1874, 1893]) AND (("timestamp" >= '2020-09-30 22:38:23.751+00'::timestamp with time zone)) AND (("timestamp" <= '2020-10-01 22:38:23.752+00'::timestamp with time zone))
```
The same error results if the query is re-written to use a sub-select:
```sql
SELECT
  time_bucket('60s',"timestamp") AS "time",
  name AS "service",
  avg(core_util_p99) AS "value"
FROM
  capacity.pool_30m
WHERE
      "timestamp" BETWEEN '2020-09-30T22:38:23.751Z' AND '2020-10-01T22:38:23.752Z'
  AND name IN ( SELECT t.name FROM (
                  SELECT
                    name,
                    avg(core_util_p99) AS "value"
                  FROM
                    capacity.pool_30m
                  WHERE
                        "timestamp" BETWEEN '2020-09-30T22:38:23.751Z' AND '2020-10-01T22:38:23.752Z'
                  GROUP BY 1
                  ORDER BY 2 DESC
                  LIMIT 10) t )
GROUP BY 1,2
ORDER BY 1,2;
ERROR:  failed to set single row mode for SELECT name, core_util_p99 FROM capacity.pool_30m WHERE _timescaledb_internal.chunks_in(capacity.pool_30m.*, ARRAY[1874, 1893]) AND (("timestamp" >= '2020-09-30 22:38:23.751+00'::timestamp with time zone)) AND (("timestamp" <= '2020-10-01 22:38:23.752+00'::timestamp with time zone)) AND ((name <> 'constructor'::text))
```
Per discussions with @mkindahl via Slack I tried again with `timescaledb.remote_data_fetcher = cursor`. The query still fails, but with a different error:
```
ERROR:  can't get a response because previous request hasn't completed. Aborted SQL statement: DECLARE c4 CURSOR FOR
SELECT name, core_util_p99 FROM capacity.pool_30m WHERE _timescaledb_internal.chunks_in(capacity.pool_30m.*, ARRAY[1874, 1893]) AND (("timestamp" >= '2020-09-30 22:38:23.751+00'::timestamp with time zone)) AND (("timestamp" <= '2020-10-01 22:38:23.752+00'::timestamp with time zone))
```

**To Reproduce**
@mkindahl created a simple but analogous version of the `pool_30m` table referenced above and received yet another error:
```sql
WITH top_n AS (
   SELECT
     device,
     avg(temp) AS "avg_temp"
   FROM
     devices
   WHERE
     "time" BETWEEN '2020-02-07T22:38:23.751Z' AND '2020-02-21T22:38:23.752Z'
   GROUP BY 1
   ORDER BY 2 DESC
   LIMIT 10
)
SELECT
  time_bucket('60s', "time") AS "time",
  device,
  avg(temp) AS "avg_temp"
FROM
  devices INNER JOIN top_n USING (device)
WHERE
  "time" BETWEEN '2020-02-07T22:38:23.751Z' AND '2020-02-21T22:38:23.752Z'
GROUP BY 1,2
ORDER BY 1,2;
ERROR:  request already in process
```
@mkindahl further stated
> These errors are all related and has to do with the handling of connections to the data node.

### PR DESCRIPTION
**Pull request by erimatnor**
This change fixes errors when using sub-queries together with
AsyncAppend on distributed hypertables.

Since all subqueries are sent to remote data nodes as separate queries
on the same connection, it is important that one query does not block
the connection once the other query starts to execute. In other words,
a query must complete a request and retrieve the result before another
(sub-)query can execute. During query execution, this means that the
following invariant must hold: An executor node cannot leave a request
(or result) pending on a connection after returning a tuple, since for
the next tuple a different executor node can be called to execute
another sub-query on the same connection. This would be the case if
two sub-queries are, e.g., joined with a nested loop.

AsyncAppend (and associated fetchers) failed the above invariant; the
executor node could leave a request unfinished after returning a
tuple, causing the connection to be in an unexpected state when
another AsyncAppend was called as part of a join with another
sub-query.

It turns out that only cursor fetcher can be used in these cases
without having to fetch and buffer the entire result set of a
sub-query (with a `CURSOR` the request can be broken up in multiple
separate `FETCH` requests that can be interleaved with other
sub-queries). Unfortunately, when executing a query using a `CURSOR`,
it doesn't support parallel execution (on the data node). Previously,
this was solved by defaulting to another "row-by-row" method of
fetching data. However, row-by-row suffers from the same issue of
leaving the connection in an unfinished state unless the whole result
set is read and buffered, which could potentially blow up memory.

The following changes are made to address the situation:

* The cursor fetcher is made the default fetcher so that all queries
  can be executed without errors.
* Fixes are also applied to the cursor fetcher to make sure it does
  not have pending queries after AsyncAppend returns a tuple.
* AsyncAppend is similarly tweaked to avoid leaving connections with
  pending queries.
* The ability to set the `fetch_size` (number of tuples to fetch in
  each `FETCH` request) and other options at the foreign data wrapper
  level is added. This allows changing FDW options globally for all
  data nodes, as the previous method of setting them on each foreign
  server is currently blocked. Setting a smaller `fetch_size` is
  often necessary to trigger the erroneous behavior.

Unfortunately, these changes might lead to a regression in query
performance. With cursor fetcher, queries cannot execute in parallel
mode on data nodes. Further, the previous code was more aggressive
with sending new fetch requests after each batch (for performance
reasons), but this is not possible when sub-query joins are present.

A future optimization could, for instance, use the row-by-row fetcher
by default and fall back to cursor fetcher if it detects joins between
sub-queries.

Fixes #2511

### CODE REVIEW

**Comment by niksajakovljevic** [comment]
I didn't really go deep into the review but from the high level perspective I am wondering if we have considered adding batching into `row by row` fetcher.  We can maybe leverage LIMIT and OFFSET to implement batching which should prevent blowing up memory and allow us to `run` queries in parallel? So for two queries it would look like: 
- send request for query1 and batch 1 (q1b1)
- consume data from q1b1 so we can run another query
- send request for query2 and batch1 (q2b1)
- consume q2b1
- continue with q1b2...

As you've already noticed, I'm just worried that not having parallelism on data nodes would be a major blow to multinode performance....IIRC from some of the benchmarks we did using CURSORs led to 5-10X slowdown...

**Comment by erimatnor** [comment]
> I didn't really go deep into the review but from the high level perspective I am wondering if we have considered adding batching into `row by row` fetcher. We can maybe leverage LIMIT and OFFSET to implement batching which should prevent blowing up memory and allow us to `run` queries in parallel? So for two queries it would look like:
> 
>     * send request for query1 and batch 1 (q1b1)
> 
>     * consume data from q1b1 so we can run another query
> 
>     * send request for query2 and batch1 (q2b1)
> 
>     * consume q2b1
> 
>     * continue with q1b2...
> 
> 
> As you've already noticed, I'm just worried that not having parallelism on data nodes would be a major blow to multinode performance....IIRC from some of the benchmarks we did using CURSORs led to 5-10X slowdown...

Right now, I think we need to focus on correctness over performance. People can still set rowbyrow fetcher if they want parallel support, but then they cannot do some sub/queries in that case. 

We certainly would like to optimize this somehow in the future. I do not think the LIMIT/OFFSET approach will solve the problem, however. In that approach, I believe each new request will be a distinct query that each require a complete planning stage followed by new execution, which will be slower than cursors that keep the query on-going until the last FETCH.

File: tsl/src/remote/cursor_fetcher.c [hunk 1]
```diff
@@ -343,7 +357,7 @@ cursor_fetcher_fetch_data_complete(CursorFetcher *cursor)
 
 	MemoryContextSwitchTo(oldcontext);
 
-	data_fetcher_request_data_async(&cursor->state);
+	// data_fetcher_request_data_async(&cursor->state);
```
Comment (k-rus) [inline tsl/src/remote/cursor_fetcher.c:360]: I guess the line needs to be removed.

**Review by k-rus — APPROVED** [review]

File: tsl/src/remote/async.c [hunk 2]
```diff
@@ -561,38 +563,44 @@ get_single_response_nonblocking(AsyncRequestSet *set)
...
 		PGconn *pg_conn = remote_connection_get_pg_conn(req->conn);
 
-		if (remote_connection_is_processing(req->conn) && req->state == DEFERRED)
-			return async_response_error_create("request already in process");
-
-		if (req->state == DEFERRED)
+		switch (req->state)
 		{
-			req = async_request_send_internal(req, WARNING);
+			case DEFERRED:
```
Comment (niksajakovljevic) [inline tsl/src/remote/async.c:568]: Nit: This refactor seems to be changing semantics of Async API. The idea of `DEFERRED` state was that we can create a request that is not dispatched immediately. If I am not mistaken this refactor will send the request straight way so maybe we should rename this state to `CREATED` or similar.

**Review by niksajakovljevic — APPROVED** [review]
LGTM. However, I would like to see an optimization for detecting if there is a join statement (I assume that should be straight forward) and switch to CURSOR, otherwise have ROW-BY-ROW as default. Anyways, we can leave it for a separate PR.

**Comment by erimatnor** [comment]
> LGTM. However, I would like to see an optimization for detecting if there is a join statement (I assume that should be straight forward) and switch to CURSOR, otherwise have ROW-BY-ROW as default. Anyways, we can leave it for a separate PR.

Yes, further optimizations can be done in separate PRs. Here we are prioritizing fixing the queries that currently don't work.

Btw, not sure we want to switch on JOIN statements as joining with a table on the access node is a valid thing to do without having to necessarily fall back to cursor.

File: tsl/src/remote/async.c (hunk 2 above)
Comment (erimatnor) [reply tsl/src/remote/async.c:568]: I don't think DEFERRED should be possible, so should be removed. But I didn't want to make further changes in this PR, instead focusing on fixing the subquery issues.

Let's discuss the use case for DEFERRED, if any, in another forum. But my guess is that this can be removed.

File: tsl/src/async_append.c [hunk 3]
```diff
@@ -25,12 +25,59 @@
...
+ * query, that means the query on the second data node will not start
+ * executing until the first node has finished. Thus, if there are three data
+ * nodes, the remote communication will proceed as follows:
+ *
+ * 1. Send query to data node 1.
+ * 2. Get data from data node 1.
+ * 3. Send query to data node 2.
+ * 4. Get data from data node 2.
+ * 5. Send query to data node 3.
+ * 6. Get data from data node 4.
```
Comment (pmwkaa) [inline tsl/src/async_append.c:42]: 6. Get data from data node 3 ?

File: tsl/src/async_append.c [hunk 4]
```diff
@@ -25,12 +25,59 @@
...
+
+ * In contrast, AsyncAppend makes sure that all data node requests are sent
+ * before any data is read:
+ *
+ * 1. Send query to data node 1.
+ * 2. Send query to data node 2.
+ * 3. Send query to data node 3.
+ * 4. Get data from data node 1.
+ * 5. Get data from data node 2.
+ * 6. Get data from data node 4.
```
Comment (pmwkaa) [inline tsl/src/async_append.c:55]: 6. Get data from data node 3 ?

File: tsl/src/fdw/option.c [hunk 5]
```diff
@@ -143,13 +144,16 @@ init_ts_fdw_options(void)
 	/* non-libpq FDW-specific FDW options */
 	static const TsFdwOption non_libpq_options[] = {
 		/* cost factors */
+		{ "fdw_startup_cost", ForeignDataWrapperRelationId },
```
Comment (pmwkaa) [inline tsl/src/fdw/option.c:147]: offtopic: are we actually using or intend to use those cost options ?

File: src/guc.c [hunk 6]
```diff
@@ -284,7 +284,7 @@ _guc_init(void)
 							 "Pick data fetcher type based on type of queries you plan to run "
 							 "(rowbyrow or cursor)",
 							 (int *) &ts_guc_remote_data_fetcher,
-							 RowByRowFetcherType,
+							 CursorFetcherType,
```
Comment (pmwkaa) [inline src/guc.c:287]: So we are changing the default fetcher too?
