### PR TITLE
Fix segfault when deleting from compressed chunk

### LINKED ISSUE #5640: Segfault when deleting from compressed chunk
When deleting from compressed chunks attribute number mapping is not handled correctly leading decompressing with wrong filters or segfaults. 

Stacktrace:
```
#0  0x00007f3bc536a79b in fill_predicate_context (ch=0x55bd4e5f4d20, predicates=0x55bd4e2250a0, filters=0x7ffd4ae7d498, is_null=0x7ffd4ae7d4a0) at /home/sven/projects/tsmaster/tsl/src/compression/compression.c:2189
#1  0x00007f3bc536ad8b in decompress_batches_for_update_delete (chunks=0x55bd4e5f56e8, predicates=0x55bd4e2250a0) at /home/sven/projects/tsmaster/tsl/src/compression/compression.c:2358
#2  0x00007f3bc54bbeb5 in ExecModifyTable (cs_node=0x55bd4e5e9478, pstate=0x55bd4e5e9b38) at /home/sven/projects/tsmaster/src/nodes/hypertable_modify.c:806
#3  0x00007f3bc54bad49 in hypertable_modify_exec (node=0x55bd4e5e9478) at /home/sven/projects/tsmaster/src/nodes/hypertable_modify.c:220
#4  0x000055bd4c1640aa in ExecCustomScan (pstate=0x55bd4e5e9478) at nodeCustom.c:115
#5  0x000055bd4c14547a in ExecProcNodeFirst (node=0x55bd4e5e9478) at execProcnode.c:464
#6  0x000055bd4c13883c in ExecProcNode (node=0x55bd4e5e9478) at ../../../src/include/executor/executor.h:259
#7  0x000055bd4c13b6ed in ExecutePlan (estate=0x55bd4e5e91d0, planstate=0x55bd4e5e9478, use_parallel_mode=false, operation=CMD_DELETE, sendTuples=true, numberTuples=0, direction=ForwardScanDirection, dest=0x55bd4e160778,
    execute_once=true) at execMain.c:1636
#8  0x000055bd4c138f63 in standard_ExecutorRun (queryDesc=0x55bd4e160810, direction=ForwardScanDirection, count=0, execute_once=true) at execMain.c:363
#9  0x00007f3bcf670526 in pgss_ExecutorRun (queryDesc=0x55bd4e160810, direction=ForwardScanDirection, count=0, execute_once=true) at ts_stat_statements.c:725
#10 0x00007f3bcea56cd7 in pgss_ExecutorRun (queryDesc=0x55bd4e160810, direction=ForwardScanDirection, count=0, execute_once=true) at pg_stat_statements.c:1008
#11 0x000055bd4c138d39 in ExecutorRun (queryDesc=0x55bd4e160810, direction=ForwardScanDirection, count=0, execute_once=true) at execMain.c:305
#12 0x000055bd4c3af6d9 in ProcessQuery (plan=0x55bd4e2272e8, sourceText=0x55bd4e05c820 "delete from public.metrics_compressed\nwhere \npublic.metrics_compressed.time is not NULL\nreturning \n  public.metrics_compressed.v1 as c0",
    params=0x0, queryEnv=0x0, dest=0x55bd4e160778, qc=0x7ffd4ae7dba0) at pquery.c:160
#13 0x000055bd4c3b129a in PortalRunMulti (portal=0x55bd4e0d5870, isTopLevel=true, setHoldSnapshot=true, dest=0x55bd4e160778, altdest=0x55bd4c8b2a80 <donothingDR>, qc=0x7ffd4ae7dba0) at pquery.c:1277
#14 0x000055bd4c3b0dbd in FillPortalStore (portal=0x55bd4e0d5870, isTopLevel=true) at pquery.c:1026
#15 0x000055bd4c3b06be in PortalRun (portal=0x55bd4e0d5870, count=9223372036854775807, isTopLevel=true, run_once=true, dest=0x55bd4e227488, altdest=0x55bd4e227488, qc=0x7ffd4ae7dde0) at pquery.c:763
#16 0x000055bd4c3a9655 in exec_simple_query (query_string=0x55bd4e05c820 "delete from public.metrics_compressed\nwhere \npublic.metrics_compressed.time is not NULL\nreturning \n  public.metrics_compressed.v1 as c0") at postgres.c:1250
#17 0x000055bd4c3ae4e1 in PostgresMain (dbname=0x55bd4e0916f0 "smith", username=0x55bd4e0916d0 "sven") at postgres.c:4593
#18 0x000055bd4c2d5a4c in BackendRun (port=0x55bd4e08f380) at postmaster.c:4511
#19 0x000055bd4c2d52df in BackendStartup (port=0x55bd4e08f380) at postmaster.c:4239
#20 0x000055bd4c2d11f3 in ServerLoop () at postmaster.c:1806
#21 0x000055bd4c2d096b in PostmasterMain (argc=4, argv=0x55bd4e016120) at postmaster.c:1478
#22 0x000055bd4c1c6833 in main (argc=4, argv=0x55bd4e016120) at main.c:202
```

### PR DESCRIPTION
**Pull request by sb230132**
During UPDATE/DELETE on compressed hypertables, we iterate over plan
tree to collect all scan nodes. For each scan nodes there can be
filter conditions.

Prior to this patch we collect only first filter condition and use
for first chunk which may be wrong. In this patch as and when we
encounter a target scan node, we immediately process those chunks.

Fixes #5640

### CODE REVIEW

**Review by antekresic — CHANGES_REQUESTED** [review]
Needs tests that cover this specific issue.

**Comment by sb230132** [comment]
> Needs tests that cover this specific issue.

For segfault there don't seem to be any testcase for now. However i found testcase which results in unwanted decompression on join tables. For this i have added testcase.

**Review by svenklemm — CHANGES_REQUESTED** [review]
This only fixes part of the issues mentioned by the ticket and does not adress the problems with JOINS.

File: src/nodes/hypertable_modify.c [hunk 1]
```diff
@@ -126,11 +128,13 @@ collect_chunks_from_scan(PlanState *ps, ChunkScanNodes *sn)
 		case T_TidRangeScanState:
 			rte = rt_fetch(((Scan *) ps->plan)->scanrelid, ps->state->es_range_table);
 			current_chunk = ts_chunk_get_by_relid(rte->relid, false);
-			if (current_chunk && ts_chunk_is_compressed(current_chunk))
+			/* ensure chunk belongs to target hypertable and is compressed */
+			if (current_chunk && current_chunk->hypertable_relid == sn->hypertable_id &&
+				ts_chunk_is_compressed(current_chunk))
 			{
 				sn->chunks = lappend(sn->chunks, current_chunk);
-				if (ps->plan->qual && !sn->predicates)
```
[the remark this answers is not in the document]
Comment (sb230132) [reply src/nodes/hypertable_modify.c:132]: yes, i have a struct ChunkScanNodes defined to hold chunks and corresponding predicates.

File: src/nodes/hypertable_modify.c [hunk 2]
```diff
@@ -126,11 +128,13 @@ collect_chunks_from_scan(PlanState *ps, ChunkScanNodes *sn)
 		case T_TidRangeScanState:
 			rte = rt_fetch(((Scan *) ps->plan)->scanrelid, ps->state->es_range_table);
 			current_chunk = ts_chunk_get_by_relid(rte->relid, false);
-			if (current_chunk && ts_chunk_is_compressed(current_chunk))
+			/* ensure chunk belongs to target hypertable and is compressed */
+			if (current_chunk && current_chunk->hypertable_relid == sn->hypertable_id &&
```
[the remark this answers is not in the document]
Comment (sb230132) [reply src/nodes/hypertable_modify.c:132]: Can you please provide a concrete testcase for me to further analyse on the issue.

[the remark this answers is not in the document]
Comment (svenklemm) [reply src/nodes/hypertable_modify.c:132]: The following query will trigger multiple unrelated decompressions:
```DELETE FROM metrics_compressed m1 USING metrics_compressed m2, metrics_compressed m3 WHERE m1.device_id = m2.device_id AND m2.device_id = m3.device_id AND m1.time > '2000-01-10' AND m2.v0 IS NOT NULL AND m3.v1 IS NOT NULL;```

File: tsl/src/compression/compression.c [hunk 3]
```diff
@@ -2355,7 +2355,7 @@ decompress_batches_for_update_delete(List *chunks, List *predicates)
 	SegmentFilter *filter;
 
 	if (predicates)
-		fill_predicate_context(linitial(chunks), predicates, &filters, &is_null);
```
[the remark this answers is not in the document]
Comment (svenklemm) [reply tsl/src/compression/compression.c:2358]: I agree with @kgyrtkirk please do not use nested lists here. Use proper struct if needed or act on the information straight away since only use this information once after and dont need to keep it.

[the remark this answers is not in the document]
Comment (sb230132) [reply tsl/src/compression/compression.c:2358]: Now i iterate over chunks and its corresponding predicates and build scan keys and process the chunks.

**Comment by sb230132** [comment]
> Not sure why you disable the changelog check. You need to add one eventually anyway.

Iam not sure how Disable-check: force-changelog-changed got injected.

This issue is internal. So do we still need to add changelog ?

File: src/nodes/hypertable_modify.c (hunk 2 above)
[the remark this answers is not in the document]
Comment (sb230132) [reply src/nodes/hypertable_modify.c:152]: Fixed now.

**Comment by sb230132** [comment]
> Not sure why you disable the changelog check. You need to add one eventually anyway.



> This only fixes part of the issues mentioned by the ticket and does not adress the problems with JOINS.

For segfault, iam unable to get a testcase. However now i save filters for each chunk separately and process each chunk against its own filters so, the issue of segfault occurring due to mismatch in attribute number should not occur.

**Comment by svenklemm** [comment]
> Not sure why you disable the changelog check. You need to add one eventually anyway.

We don't need changelog entry since the bug is not present in any released version.

File: tsl/test/sql/compression_update_delete.sql [hunk 4]
```diff
@@ -941,3 +941,51 @@ SELECT COUNT(*) FROM :COMPRESS_CHUNK_1 WHERE c4 > 5 AND _ts_meta_min_2 <= 5 and
...
+
+-- compress chunks
+ALTER TABLE tab2 SET (timescaledb.compress, timescaledb.compress_orderby='time DESC', timescaledb.compress_segmentby='device_id');
+SELECT compress_chunk(show_chunks('tab2'));
+
+-- below test will cause chunks of tab2 to get decompressed
+-- without fix for issue #5460
+SET timescaledb.enable_optimizations = OFF;
+BEGIN;
+DELETE FROM tab1 t1 USING tab2 t2 WHERE t1.device_id = t2.device_id AND t2.time > '2000-01-01';
```
Comment (fabriziomello) [inline tsl/test/sql/compression_update_delete.sql:985]: Wouldn't be better to place the EXPLAIN output here to make evident the planner changes?

File: src/nodes/hypertable_modify.c [hunk 5]
```diff
@@ -128,9 +128,14 @@ collect_chunks_from_scan(PlanState *ps, ChunkScanNodes *sn)
...
+				const char *chunk_name;
+				chunk_name = psprintf("%s.%s",
+									  quote_identifier(current_chunk->fd.schema_name.data),
+									  quote_identifier(current_chunk->fd.table_name.data));
+				elog(DEBUG1, "\nChunk being processed: \"%s\"\n", chunk_name);
 				sn->chunks = lappend(sn->chunks, current_chunk);
-				if (ps->plan->qual && !sn->predicates)
-					sn->predicates = ps->plan->qual;
+				/* save filters of this scan node */
+				sn->predicates = lappend(sn->predicates, ps->plan->qual);
```
Comment (svenklemm) [inline src/nodes/hypertable_modify.c:138]: Why are we storing the results of the tree walker in lists and not acting on it immediately once we found a chunk?

Comment (sb230132) [reply src/nodes/hypertable_modify.c]: Fixed.

File: tsl/test/sql/compression_update_delete.sql (hunk 4 above)
Comment (sb230132) [reply tsl/test/sql/compression_update_delete.sql:986]: Fixed. Not sure if explain will result in different plan on different versions. If so i will revert this change.

File: src/nodes/hypertable_modify.c [hunk 6]
```diff
@@ -100,7 +100,29 @@ typedef struct ChunkScanNodes
...
 	/* list of conditions specified in WHERE */
 	List *predicates;
+	/* all above chunks should belong to this parent table */
+	Oid hypertable_id;
+	/* set of chunks which needs to be processed */
+	List *target_chunk_oids;
 } ChunkScanNodes;
+
+static bool
+is_chunk_oid_present(Oid ch_id, List **nodelist)
```
[the remark this answers is not in the document]
Comment (sb230132) [reply src/nodes/hypertable_modify.c]: This code no longer applicable to this patch.

File: src/nodes/hypertable_modify.c (hunk 1 above)
[the remark this answers is not in the document]
Comment (sb230132) [reply src/nodes/hypertable_modify.c:132]: Now with latest patch i dont save chunks and its filter clauses. Instead i immediately call decompress_batches_for_update_delete() to process those chunks.

File: src/nodes/hypertable_modify.c [hunk 7]
```diff
@@ -128,15 +121,22 @@ collect_chunks_from_scan(PlanState *ps, ChunkScanNodes *sn)
...
 			if (current_chunk && ts_chunk_is_compressed(current_chunk))
 			{
-				sn->chunks = lappend(sn->chunks, current_chunk);
-				if (ps->plan->qual && !sn->predicates)
-					sn->predicates = ps->plan->qual;
+				const char *chunk_name;
+				chunk_name = psprintf("%s.%s",
+									  quote_identifier(current_chunk->fd.schema_name.data),
+									  quote_identifier(current_chunk->fd.table_name.data));
+				elog(DEBUG1, "\nChunk being processed: \"%s\"\n", chunk_name);
```
Comment (svenklemm) [inline src/nodes/hypertable_modify.c:128]:
```suggestion
```

Comment (sb230132) [reply src/nodes/hypertable_modify.c]: Fixed.

File: tsl/test/sql/compression_update_delete.sql (hunk 4 above)
Comment (sb230132) [reply tsl/test/sql/compression_update_delete.sql:985]: I had to remove explain as i see inconsistent explain outputs.

```
-               Hash Cond: (t2.device_id = t1.device_id)
+               Hash Cond: (t1.device_id = t2.device_id)
                ->  Append
-                     ->  Seq Scan on _hyper_23_45_chunk t2_1
-                           Filter: ("time" > 'Sat Jan 01 00:00:00 2000 PST'::timestamp with time zone)
-                     ->  Seq Scan on _hyper_23_46_chunk t2_2
-                           Filter: ("time" > 'Sat Jan 01 00:00:00 2000 PST'::timestamp with time zone)
-                     ->  Seq Scan on _hyper_23_47_chunk t2_3
-                           Filter: ("time" > 'Sat Jan 01 00:00:00 2000 PST'::timestamp with time zone)
+                     ->  Seq Scan on _hyper_21_39_chunk t1_1
+                     ->  Seq Scan on _hyper_21_40_chunk t1_2
+                     ->  Seq Scan on _hyper_21_41_chunk t1_3
                ->  Hash
                      ->  Append
-                           ->  Seq Scan on _hyper_21_39_chunk t1_1
-                           ->  Seq Scan on _hyper_21_40_chunk t1_2
-                           ->  Seq Scan on _hyper_21_41_chunk t1_3
+                           ->  Seq Scan on _hyper_23_45_chunk t2_1
+                                 Filter: ("time" > 'Sat Jan 01 00:00:00 2000 PST'::timestamp with time zone)
+                           ->  Seq Scan on _hyper_23_46_chunk t2_2
+                                 Filter: ("time" > 'Sat Jan 01 00:00:00 2000 PST'::timestamp with time zone)
+                           ->  Seq Scan on _hyper_23_47_chunk t2_3
+  
```

File: tsl/test/shared/sql/compression_dml.sql [hunk 8]
```diff
@@ -86,3 +86,13 @@ INSERT INTO mytab SELECT '2022-10-07 05:30:10+05:30'::timestamp with time zone,
 EXPLAIN (costs off) SELECT * FROM :chunk_table;
 DROP TABLE mytab CASCADE;
 
+BEGIN;
+SELECT count(*) FROM metrics_compressed WHERE device_id = 1;
+INSERT INTO metrics_compressed(time,device_id,v0,v1,v2,v3) SELECT time, device_id, device_id+1,  device_id + 2, device_id + 1000, NULL FROM generate_series('2000-01-01 0:00:00+0'::timestamptz,'2000-01-05 23:55:00+0','2m') gtime(time), generate_series(1,5,1) gdevice(device_id);
+SELECT count(*) FROM metrics_compressed WHERE device_id = 1;
+ANALYZE metrics_compressed;
+--set timescaledb.enable_transparent_decompression = off;
```
Comment (antekresic) [inline tsl/test/shared/sql/compression_dml.sql:94]: This line can be removed.

File: tsl/src/compression/compression.c [hunk 9]
```diff
@@ -2340,66 +2342,97 @@ decompress_batches(RowDecompressor *decompressor, ScanKeyData *scankeys, int num
...
+ * Traverse the plan tree to look for Scan nodes on uncompressed chunks.
+ * Once Scan node is found check if chunk is compressed, if so then
+ * decompress those segments which match the filter conditions if present.
+ */
+bool
+decompress_target_segments(PlanState *ps)
+{
+	RangeTblEntry *rte = NULL;
+	Chunk *current_chunk;
+	if (ps == NULL || ts_guc_enable_transparent_decompression == false)
```
Comment (antekresic) [inline tsl/src/compression/compression.c:2414]: I don't think we can use this GUC here. We should add a separate one for DML decompression which blocks UPDATE/DELETE and ON CONFLICT operations just like it is in the current release.

New GUC is left for separate PR.

File: tsl/test/shared/sql/compression_dml.sql (hunk 8 above)
Comment (sb230132) [reply tsl/test/shared/sql/compression_dml.sql]: Fixed.

File: tsl/src/compression/compression.c (hunk 9 above)
Comment (sb230132) [reply tsl/src/compression/compression.c]: Fixed.

File: tsl/test/expected/compression.out [hunk 10]
```diff
@@ -206,10 +206,11 @@ do update set b = excluded.b;
 SELECT * from foo ORDER BY a,b;
  a  |  b  | c  | d  
 ----+-----+----+----
+  3 | 111 | 20 |
```
[the remark this answers is not in the document]
Comment (sb230132) [reply tsl/test/expected/compression.out:209]: In this test we set enable_transparent_decompression to OFF and do some UPDATE/DELETE  on 'foo' table which is compressed.
As part of update/delete we move decompressed rows to uncompressed  chunks. Thus when we do SELECT we see those new rows.

**Review by antekresic — APPROVED** [review]
Looks good, we can postpone compression test refactoring in a followup PR.

**Review by svenklemm — APPROVED** [review]
Some bugs will need to be fixed in followup PRs but approving to unblock other followup PRs.

**Review by kgyrtkirk — COMMENTED** [review]
I was thinking that I've already posted this....can be handled later as a follow up as well
