### PR TITLE
Fix INSERT..SELECT involving dist hypertables

### LINKED ISSUE #3447: insert with SELECT  does not work for a distributed hypertable
**Relevant system information:**
 - OS: Ubuntu 20.04
 - PostgreSQL version 12.6
 - TimescaleDB version (output of `\dx` in `psql`): 2.4.0-dev
 - Installation method: source

**Describe the bug**

**To Reproduce**
1. Create a multi-node set-up:
```
SELECT * FROM add_data_node('dist_policy_data_node_1', host => 'localhost', database => 'dist_policy_data_node_1');
SELECT * FROM add_data_node('dist_policy_data_node_2', host => 'localhost', database => 'dist_policy_data_node_2');
SELECT * FROM add_data_node('dist_policy_data_node_3', host => 'localhost', database => 'dist_policy_data_node_3');
```
2. Create 2 distributed hypertables:
```
CREATE TABLE conditions (time bigint NOT NULL, device int, temp float);
SELECT create_distributed_hypertable('conditions', 'time', chunk_time_interval => 10, replication_factor => 2);

CREATE TABLE measurements (time int NOT NULL, device int, temp float);
SELECT create_distributed_hypertable('measurements', 'time', chunk_time_interval => 10, replication_factor => 2);
```
3. Insert the data in the following manner:
```
INSERT INTO conditions
SELECT t, ceil(abs(timestamp_hash(to_timestamp(t)::timestamp))%4)::int,
       abs(timestamp_hash(to_timestamp(t)::timestamp))%40
FROM generate_series(1, 100, 1) t;

INSERT INTO measurements
SELECT * FROM conditions;
```
4. See error: `ERROR:  request already in progress`

**Expected behavior**
The final `INSERT INTO` should succeed.

**Actual behavior**
I get an exception: `ERROR:  request already in progress`

### PR DESCRIPTION
**Pull request by nikkhils**
If the relation being inserted into and the relation in the SELECT are
both distributed hypertables then do not use COPY. This is because we
will need two connections to the same set of datanodes (one to ingest
data into src table using COPY and one to SELECT from dst table) which
is not supported currently in a single transaction. This restriction
will be lifted in the future.

Fixes #3447

### CODE REVIEW

File: tsl/src/planner.c [hunk 1]
```diff
@@ -231,6 +238,46 @@ tsl_create_distributed_insert_path(PlannerInfo *root, ModifyTablePath *mtpath, I
...
+
+			/* if src hypertable is distributed then only further checks are needed */
+			if (ts_rte_is_hypertable(rte, &distributed) && distributed)
+			{
+				/* check if it's indeed INSERT .. SELECT */
+				foreach (l, root->parse->rtable)
+				{
+					rte = (RangeTblEntry *) lfirst(l);
+
+					if (rte->rtekind == RTE_SUBQUERY)
```
Comment (akuzm) [inline tsl/src/planner.c:256]: Is it not pulled up for INSERTs? I'd expect to see an RTE_RELATION here.

File: tsl/src/planner.c [hunk 2]
```diff
@@ -231,6 +238,46 @@ tsl_create_distributed_insert_path(PlannerInfo *root, ModifyTablePath *mtpath, I
...
+				/* check if the SELECT is referring to a distributed hypertable */
+				if (select_rte)
+				{
+					Query *subquery = select_rte->subquery;
+
+					foreach (l, subquery->rtable)
+					{
+						rte = (RangeTblEntry *) lfirst(l);
+
+						if (ts_rte_is_hypertable(rte, &distributed) && distributed)
```
Comment (akuzm) [inline tsl/src/planner.c:272]: This doesn't recurse, does it? We can construct an arbitrarily deep nesting of RTE_SUBQUERY's and put a distributed table at the bottom, and it'll fail. Probably we have to recurse. To construct an example query, we can prevent the subqueries being pulled up by putting a volatile function in their targetlist, such as `random()`.

File: tsl/src/planner.c (hunk 1 above)
Comment (nikkhils) [reply tsl/src/planner.c:256]: Not it's not pulled up. You see an RTE for the table being inserted into and then an RTE for the subquery followed by RTE entries for the subquery rels

File: tsl/src/planner.c (hunk 2 above)
Comment (nikkhils) [reply tsl/src/planner.c:279]: Ah, right. So I fixed this by checking entries in the `root->simple_rte_array` array starting from the index beyond that of the source hypertable.

**Comment by akuzm** [comment]
I still get the error with your patch if I add `LIMIT 1` or `RETURNING *`:

```
test=# INSERT INTO disttable (time, device, temp_c)
SELECT time, device, temp_c FROM disttable;
INSERT 0 16

test=# INSERT INTO disttable (time, device, temp_c)
SELECT time, device, temp_c FROM disttable LIMIT 1;
ERROR:  request already in progress

test=# INSERT INTO disttable (time, device, temp_c)
SELECT time, device, temp_c FROM disttable 
RETURNING *;
ERROR:  request already in progress
```

**Comment by nikkhils** [comment]
> I still get the error with your patch if I add `LIMIT 1` or `RETURNING *`:
> 
> ```
> test=# INSERT INTO disttable (time, device, temp_c)
> SELECT time, device, temp_c FROM disttable;
> INSERT 0 16
> 
> test=# INSERT INTO disttable (time, device, temp_c)
> SELECT time, device, temp_c FROM disttable LIMIT 1;
> ERROR:  request already in progress
> 
> test=# INSERT INTO disttable (time, device, temp_c)
> SELECT time, device, temp_c FROM disttable 
> RETURNING *;
> ERROR:  request already in progress
> ```

Ah yes, need a proper range table walker to handle all cases. Done now.

File: tsl/test/expected/dist_hypertable-14.out [hunk 3]
```diff
@@ -5020,6 +5020,70 @@ SELECT count(*) FROM disttable;
...
+         ->  Custom Scan (DataNodeDispatch)
+               Batch size: 1000
+               ->  Custom Scan (ChunkDispatch)
+                     ->  Append
+                           ->  Custom Scan (DataNodeScan) on disttable disttable_2
+                           ->  Custom Scan (DataNodeScan) on disttable disttable_3
+                           ->  Custom Scan (DataNodeScan) on disttable disttable_4
+(10 rows)
+
+INSERT INTO disttable (time, device, temp_c)
```
Comment (gayyappan) [inline tsl/test/expected/dist_hypertable-14.out:5079]: Could you also add a test for this case?
INSERT INTO dist2 SELECT  * FROM dist_foo
a) source and target are different  and b) uses *

Comment (nikkhils) [reply tsl/test/expected/dist_hypertable-14.out:5080]: Done. Added a test case for this.

**Review by akuzm — APPROVED** [review]

File: tsl/src/planner.c [hunk 4]
```diff
@@ -190,13 +219,20 @@ tsl_create_distributed_insert_path(PlannerInfo *root, ModifyTablePath *mtpath, I
...
 	 *
 	 * 2. RETURNING clause exists and tuples are expected to be modified on
 	 *    INSERT by a trigger.
 	 *
+	 * 3. INSERT.. SELECT case. If the relation being inserted into and the
+	 *    relation in the SELECT are both distributed hypertables then do not
+	 *    use COPY. This is because we will need two connections to the same set
+	 *    of datanodes (one to ingest data into src table using COPY and one to
+	 *    SELECT from dst table) which is not supported currently in a single
+	 *    transaction. This restriction will be lifted in the future.
```
Comment (erimatnor) [inline tsl/src/planner.c:234]: Clarify that multiplexing multiple queries are normally possible on a single connection, but COPY is special as it switches the connection to the COPY_IN state.

```suggestion
	 * 3. INSERT.. SELECT case. If the relation being inserted into and the
	 *    relation in the SELECT are both distributed hypertables then do not
	 *    use COPY. This is because only one connection is maintained to data
	 *    nodes in order to maintain a single snapshot. Normally, it is possible to 
	 *    multiplex multiple queries on a connection using a CURSOR, but with
	 *    COPY the connection is switched into a COPY_IN state, making
	 *    multiplexing impossible. It might be possible to use two connections to 
	 *    the same data node (one to ingest data into src table using COPY and 
	 *    one to SELECT from dst table), but that requires coordinating on a single
	 *    snapshot to use on both connections. This is a potential future 
	 *    optimization.
```

File: tsl/src/planner.c [hunk 5]
```diff
@@ -179,6 +180,34 @@ copy_mode_enabled(void)
...
+	if (*isdistributed)
+		return true;
+	if (node == NULL)
+		return false;
+	if (IsA(node, RangeTblEntry))
+	{
+		RangeTblEntry *rte = (RangeTblEntry *) node;
+
+		if (rte->rtekind == RTE_RELATION)
+			ts_rte_is_hypertable(rte, isdistributed);
```
Comment (erimatnor) [inline tsl/src/planner.c:197]: We could potentially do better here by checking whether the other distributed hypertable includes the same data nodes. If the set of data nodes is disjoint, the INSERT ... SELECT could still be allowed. 

However, this is not a very common case, but it might be worth at least leaving a comment about it for the future.

File: tsl/test/expected/dist_hypertable-14.out [hunk 6]
```diff
@@ -5020,6 +5020,73 @@ SELECT count(*) FROM disttable;
...
+                                 ->  Custom Scan (AsyncAppend)
+                                       ->  Append
+                                             ->  Custom Scan (DataNodeScan) on disttable disttable_2
+                                             ->  Custom Scan (DataNodeScan) on disttable disttable_3
+                                             ->  Custom Scan (DataNodeScan) on disttable disttable_4
+(13 rows)
+
+EXPLAIN (COSTS OFF)
+INSERT INTO disttable (time, device, temp_c)
+SELECT time, device, temp_c FROM disttable RETURNING *;
```
Comment (erimatnor) [inline tsl/test/expected/dist_hypertable-14.out:5065]: Do we also have an INSERT ... SELECT test which shows DataNodeCopy is used when the SELECTed table is not a distributed hypertable?

File: tsl/src/planner.c [hunk 7]
```diff
@@ -179,6 +180,34 @@ copy_mode_enabled(void)
 	return strcmp(enable_copy, "true") == 0;
 }
 
+/* Query tree walker to examine RTE contents for a distributed hypertable */
+static bool
+distributed_rtes_walker(Node *node, bool *isdistributed)
```
Comment (mkindahl) [inline tsl/src/planner.c:185]: Not sure what the return value represents. Could you document it?

File: tsl/src/planner.c [hunk 8]
```diff
@@ -179,6 +180,34 @@ copy_mode_enabled(void)
...
+		return true;
+	if (node == NULL)
+		return false;
+	if (IsA(node, RangeTblEntry))
+	{
+		RangeTblEntry *rte = (RangeTblEntry *) node;
+
+		if (rte->rtekind == RTE_RELATION)
+			ts_rte_is_hypertable(rte, isdistributed);
+		return false;
```
Comment (mkindahl) [inline tsl/src/planner.c:198]: Nit: you can abort the walk here immediately if `*isdistributed` is set to true. It is not touched anywhere else. That would also mean that you do not need the if in the beginning of the function.
```suggestion
		if (rte->rtekind == RTE_RELATION)
			ts_rte_is_hypertable(rte, isdistributed);
		return *isdistributed;
```

**Review by mkindahl — APPROVED** [review]

**Review by gayyappan — APPROVED** [review]

File: tsl/src/planner.c (hunk 4 above)
Comment (nikkhils) [reply tsl/src/planner.c:234]: Ok, amended

File: tsl/test/expected/dist_hypertable-14.out (hunk 6 above)
Comment (nikkhils) [reply tsl/test/expected/dist_hypertable-14.out:5065]: Yes, there are existing tests in `dist_hypertable.sql.in` for that.

File: tsl/src/planner.c (hunk 5 above)
Comment (nikkhils) [reply tsl/src/planner.c:197]: Added a comment.

File: tsl/src/planner.c (hunk 7 above)
Comment (nikkhils) [reply tsl/src/planner.c:185]: Added a comment

File: tsl/src/planner.c (hunk 8 above)
Comment (nikkhils) [reply tsl/src/planner.c:198]: Done.
