### PR TITLE
Fix ADD COLUMN IF NOT EXISTS error on compressed hypertable

### LINKED ISSUE #4087: [Bug]: Failed to add a column in a hypertable
### What type of bug is this?

Unexpected error

### What subsystems and features are affected?

Distributed hypertable

### What happened?

When trying to add a column to an hypertable
```
ALTER TABLE table_name ADD COLUMN  IF NOT EXISTS  "medium" VARCHAR ;
```
and if the column already exists.
I get the following error
```
Query 1 ERROR: ERROR:  column "medium" of relation "_compressed_hypertable_9" already exists`
```

### TimescaleDB version affected

2.5.0

### PostgreSQL version used

14.1

### What operating system did you use?

-

### What installation method did you use?

Not applicable

### What platform did you run on?

Managed Service for TimescaleDB (MST/Aiven)

### Relevant log output and stack trace

```bash
Query 1 ERROR: ERROR:  column "medium" of relation "_compressed_hypertable_9" already exists
```

### How can we reproduce the bug?

```bash
See the description above
```

### PR DESCRIPTION
**Pull request by konskov**
When an ALTER TABLE ... ADD COLUMN IF NOT EXISTS ... command is executed
and the column already exists, we get an error message that the column already
exists on the compressed hypertable, even though IF NOT EXISTS is specified.
This PR removes this error.

Fix #4087

### CODE REVIEW

File: tsl/src/compression/create.c [hunk 1]
```diff
@@ -923,24 +923,54 @@ disable_compression(Hypertable *ht, WithClauseResult *with_clause_options)
...
+static bool
+add_column_to_compression_table(Hypertable *compress_ht, CompressColInfo *compress_cols,
+								bool missing_ok)
 {
 	Oid compress_relid = compress_ht->main_table_relid;
 	ColumnDef *coldef;
 	AlterTableCmd *addcol_cmd;
+	HeapTuple attTuple;
+	int attnum;
+	bool skipped = false; /* postgres operates on its table first, so the column may have been
```
Comment (mfundul) [inline tsl/src/compression/create.c:935]: You can't really assume this here. Maybe this function is going to be called from a different place in the future. There is no guarantee that postgres operated on its table first.

File: tsl/src/compression/create.c [hunk 2]
```diff
@@ -1057,28 +1087,31 @@ tsl_process_compress_table(AlterTableCmd *cmd, Hypertable *ht,
  * This function specifically adds the column to the internal compression table.
  */
 void
-tsl_process_compress_table_add_column(Hypertable *ht, ColumnDef *orig_def)
+tsl_process_compress_table_add_column(Hypertable *ht, const AlterTableCmd *cmd)
```
Comment (mfundul) [inline tsl/src/compression/create.c:1090]: Why do you want to tie this to an ALTER TABLE command? We should be able to add a column on demand if we like. I don't see what `missing_ok` offers us here. In any case, if we really needed `missing_ok` we could add an extra `bool` argument.

In this case if `missing_ok` is true, then it is a no-op that prints a warning, otherwise it's an exception. Is this the idea here?

File: tsl/src/compression/create.c [hunk 3]
```diff
@@ -923,24 +923,40 @@ disable_compression(Hypertable *ht, WithClauseResult *with_clause_options)
...
+		new_column = true;
+	}
+	else
+	{
+		ReleaseSysCache(attTuple);
+	}
 
 	/* alter the table and add column */
 	AlterTableInternal(compress_relid, list_make1(addcol_cmd), true);
 	modify_compressed_toast_table_storage(compress_cols, compress_relid);
```
Comment (gayyappan) [inline tsl/src/compression/create.c:958]: This is conditional -> do it only if a new column is added

File: tsl/src/compression/create.c [hunk 4]
```diff
@@ -1064,21 +1080,27 @@ tsl_process_compress_table_add_column(Hypertable *ht, ColumnDef *orig_def)
...
+		new_column = add_column_to_compression_table(compress_ht, &compress_cols);
 	}
 	else
 	{
+		no_compression_table = true;
 		Assert(TS_HYPERTABLE_HAS_COMPRESSION_ENABLED(ht));
 	}
 	/* add catalog entries for the new column for the hypertable */
-	compresscolinfo_add_catalog_entries(&compress_cols, orig_htid);
+	if (new_column || no_compression_table)
```
Comment (gayyappan) [inline tsl/src/compression/create.c:1102]: add catalog entries only if this is a new column, otherwise you will have duplicates.

```suggestion
	if (new_column )
```

File: tsl/src/compression/create.c [hunk 5]
```diff
@@ -923,24 +923,40 @@ disable_compression(Hypertable *ht, WithClauseResult *with_clause_options)
...
+
+	attTuple = SearchSysCache2(ATTNAME,
+							   ObjectIdGetDatum(compress_relid),
+							   PointerGetDatum(coldef->colname));
+	if (!HeapTupleIsValid(attTuple))
+	{
+		/* the column doesn't exist yet */
+		new_column = true;
+	}
+	else
```
Comment (gayyappan) [inline tsl/src/compression/create.c:951]: why is Release conditional? Shouldn't this be released before leaving the function?

File: tsl/src/compression/create.c [hunk 6]
```diff
@@ -1064,21 +1080,27 @@ tsl_process_compress_table_add_column(Hypertable *ht, ColumnDef *orig_def)
...
 	if (TS_HYPERTABLE_HAS_COMPRESSION_TABLE(ht))
 	{
 		int32 compress_htid = ht->fd.compressed_hypertable_id;
 		Hypertable *compress_ht = ts_hypertable_get_by_id(compress_htid);
-		add_column_to_compression_table(compress_ht, &compress_cols);
+		new_column = add_column_to_compression_table(compress_ht, &compress_cols);
 	}
 	else
 	{
+		no_compression_table = true;
```
Comment (gayyappan) [inline tsl/src/compression/create.c:1098]: this variable is not needed.

File: tsl/src/compression/create.c [hunk 7]
```diff
@@ -923,24 +923,40 @@ disable_compression(Hypertable *ht, WithClauseResult *with_clause_options)
...
+							   PointerGetDatum(coldef->colname));
+	if (!HeapTupleIsValid(attTuple))
+	{
+		/* the column doesn't exist yet */
+		new_column = true;
+	}
+	else
+	{
+		ReleaseSysCache(attTuple);
+	}
```
Comment (fabriziomello) [inline tsl/src/compression/create.c:954]:
```suggestion
	/* the column doesn't exist yet */
	new_column = !HeapTupleIsValid(attTuple);

	ReleaseSysCache(attTuple);
```

File: tsl/src/compression/create.c (hunk 5 above)
Comment (mkindahl) [reply tsl/src/compression/create.c:951]: It is not needed when the search fails.

**Review by mkindahl — COMMENTED** [review]
Hi! Patch looks good, but a few items that I think might be good to add a test for a compressed distributed table and make sure that it behaves in a sane manner.

The most sensible place to call the function to add a compressed table column is in `process_altertable_end_subcmd`, which is called after the main statement has executed. At this point you know that adding the column succeeded and that all that remains is to add the column to the compressed table. At this point is is not necessary to do any checking if the column exists and you can just proceed with executing the `AlterTableStmt` with the same options as before, but change the table name.

**Comment by mkindahl** [comment]
> Hi! Patch looks good, but a few items that I think might be good to add a test for a compressed distributed table and make sure that it behaves in a sane manner.
> 
> The most sensible place to call the function to add a compressed table column is in `process_altertable_end_subcmd`, which is called after the main statement has executed. At this point you know that adding the column succeeded and that all that remains is to add the column to the compressed table. At this point is is not necessary to do any checking if the column exists and you can just proceed with executing the `AlterTableStmt` with the same options as before, but change the table name.

This might require some rewrite of the `process_altertable_end_table`, which makes the commit a lot bigger since it does not pass down the `AlterTableStmt` to the other functions, so that might be better to do as a refactoring of this code in a separate PR.

File: tsl/test/expected/compression_errors.out [hunk 8]
```diff
@@ -494,3 +494,36 @@ SELECT config FROM _timescaledb_config.bgw_job WHERE id = :compressjob_id;
...
+------------------------------------------
+ _timescaledb_internal._hyper_23_17_chunk
+(1 row)
+
+-- column does not exist the first time
+ALTER TABLE metric ADD COLUMN IF NOT EXISTS "medium" VARCHAR ;
+-- column already exists the second time
+ALTER TABLE metric ADD COLUMN IF NOT EXISTS "medium" VARCHAR ;
+NOTICE:  column "medium" of relation "metric" already exists, skipping
+NOTICE:  column "medium" of relation "_compressed_hypertable_24" already exists, skipping
```
[the remark this answers is not in the document]
Comment (mkindahl) [reply tsl/test/expected/compression_errors.out:525]: It would be possible to set the `missing_ok` to `false` and then use `PG_TRY` and `PG_CATCH` to eliminate the message. Not critical though, so we could do it in a separate PR.

**Comment by fabriziomello** [comment]
@konskov looking more deeply for this PR I think (IMHO) is better to passdown the `AlterTableCmd->missing_ok` value to `tsl_process_compress_table_add_column`, `add_column_to_compression_table` and `compresscolinfo_add_catalog_entries` teaching the last one to check if the column already exists in our catalog if `missing_ok = true`  to skip the insertion that lead us to a duplicate key violation

File: tsl/src/compression/create.c [hunk 9]
```diff
@@ -1067,6 +1067,14 @@ tsl_process_compress_table_add_column(Hypertable *ht, ColumnDef *orig_def)
 
 	coloid = LookupTypeNameOid(NULL, orig_typname, false);
 	compresscolinfo_init_singlecolumn(&compress_cols, colname, coloid);
+
+	FormData_hypertable_compression *ht_comp =
```
Comment (gayyappan) [inline tsl/src/compression/create.c:1071]: I would move the newly added lines to line 1067.
So the check would be the first thing in the function (before any initialization etc) .

**Review by gayyappan — APPROVED** [review]
Minor change requested. Changes look good.

File: tsl/test/expected/dist_compression.out [hunk 10]
```diff
@@ -1388,3 +1388,87 @@ ORDER BY 1;
...
+timescaledb.compress_segmentby = 'dev_id',
+timescaledb.compress_orderby = 'time DESC'
+);
+ 
+INSERT INTO metric(time, val, dev_id)
+SELECT s.*, 3.14+1, 1
+FROM generate_series('2021-07-01 00:00:00'::timestamp,
+                    '2021-08-17 00:02:00'::timestamp, '30 s'::interval) s;
+ 
+SELECT compress_chunk(show_chunks('metric'));
```
Comment (gayyappan) [inline tsl/test/expected/dist_compression.out:1411]: should rewrite the query with order by (so that test output is consistent)
SELECT compress_chunk(ch) FROM show_chunks('metric') ch ORDER BY 1;

File: tsl/src/compression/create.c [hunk 11]
```diff
@@ -1063,10 +1063,19 @@ tsl_process_compress_table_add_column(Hypertable *ht, ColumnDef *orig_def)
...
 	char *colname = orig_def->colname;
-	TypeName *orig_typname = orig_def->typeName;
 
+	FormData_hypertable_compression *ht_comp =
+		ts_hypertable_compression_get_by_pkey(orig_htid, colname);
+	/* don't add column if it already exists */
+	if (ht_comp)
+	{
+		return;
+	}
```
Comment (mfundul) [inline tsl/src/compression/create.c:1073]:
```suggestion
	if (ht_comp)
		return;
```
I'm pretty sure the format check will pass if you simplify it this way.
