### PR TITLE
Fix crash when interrupting create_hypertable

### LINKED ISSUE #1651: Segfault crash cancelling create_hypertable()
**Relevant system information:**
 - OS: CentOS 7
 - PostgreSQL version (output of `postgres --version`): 11.6
 - TimescaleDB version (output of `\dx` in `psql`): 1.6.0
 - Installation method: yum

**Describe the bug**
Pressing ^C in psql while running create_hypertable() causes a crash.

**To Reproduce**
1. Create a big table (one on which create_hypertable() will take at least a few seconds)
2. Run an appropriate create_hypertable() command on that table.
3. Press ^C before it finishes.

**Expected behavior**
The create_hypertable() process is cancelled and the postgresql server does not crash.

**Actual behavior**
The create_hypertable() process is cancelled and every other connection is terminated as the server crashes.

**Screenshots**
```
2020-01-24 14:49:14.814 +11 @ :27006  LOG:  server process (PID 27042) was terminated by signal 11: Segmentation fault
2020-01-24 14:49:14.814 +11 @ :27006  DETAIL:  Failed process was running: SELECT create_hypertable(
          'ip_port_data', 'time',
          migrate_data => 'true',
          chunk_time_interval => 604800
        );
2020-01-24 14:49:14.814 +11 @ :27006  LOG:  terminating any other active server processes
2020-01-24 14:49:14.817 +11 @ :27013  WARNING:  terminating connection because of crash of another server process
2020-01-24 14:49:14.817 +11 @ :27013  DETAIL:  The postmaster has commanded this server process to roll back the current transaction and exit, because another server process exited abnormally and possibly corrupted shared memory.
2020-01-24 14:49:14.817 +11 @ :27013  HINT:  In a moment you should be able to reconnect to the database and repeat your command.
2020-01-24 14:49:14.841 +11 @ :27006  LOG:  all server processes terminated; reinitializing
2020-01-24 14:49:14.998 +11 @ :27046  LOG:  database system was interrupted; last known up at 2020-01-24 14:49:09 +11
2020-01-24 14:49:38.761 +11 @ :27046  LOG:  database system was not properly shut down; automatic recovery in progress
2020-01-24 14:49:38.767 +11 @ :27046  LOG:  redo starts at C/78039A08
2020-01-24 14:49:47.846 +11 @ :27046  LOG:  redo done at C/7C31D538
2020-01-24 14:49:47.917 +11 @ :27046  LOG:  checkpoint starting: end-of-recovery immediate
2020-01-24 14:49:49.038 +11 @ :27046  LOG:  checkpoint complete: wrote 5020 buffers (8.5%); 0 WAL file(s) added, 0 removed, 4 recycled; write=0.071 s, sync=0.784 s, total=1.155 s; sync files=66, longest=0.046 s, average=0.011 s; distance=68494 kB, estimate=68494 kB
2020-01-24 14:49:49.097 +11 @ :27006  LOG:  database system is ready to accept connections
```
**Backtrace**
```
Stack trace of thread 27042:
#0  0x00007f219fd45029 vfprintf (libc.so.6)
#1  0x00007f219fe0dd75 __vsnprintf_chk (libc.so.6)
#2  0x00000000008928bf pvsnprintf (postgres)
#3  0x000000000063b734 appendStringInfoVA (postgres)
#4  0x0000000000851fd1 errcontext_msg (postgres)
#5  0x0000000000591145 CopyFromErrorCallback (postgres)
#6  0x000000000084e977 errfinish (postgres)
#7  0x0000000000742d74 ProcessInterrupts (postgres)
#8  0x00007f2174693f8d timescaledb_CopyFrom.isra.1.constprop.2 (timescaledb-1.6.0.so)
#9  0x00007f2174694644 timescaledb_move_from_table_to_chunks (timescaledb-1.6.0.so)
#10 0x00007f217469e965 ts_hypertable_create_from_info (timescaledb-1.6.0.so)
#11 0x00007f217469efb0 ts_hypertable_create (timescaledb-1.6.0.so)
#12 0x000000000060dbfd ExecMakeFunctionResultSet (postgres)
#13 0x0000000000628f9b ExecProjectSRF (postgres)
#14 0x0000000000629095 ExecProjectSet (postgres)
#15 0x00000000006048ba standard_ExecutorRun (postgres)
#16 0x00000000007474bb PortalRunSelect (postgres)
#17 0x000000000074887f PortalRun (postgres)
#18 0x0000000000744827 exec_simple_query (postgres)
#19 0x0000000000745af2 PostgresMain (postgres)
#20 0x0000000000480556 ServerLoop (postgres)
#21 0x00000000006d8ae9 PostmasterMain (postgres)
#22 0x00000000004813af main (postgres)
#23 0x00007f219fd1a505 __libc_start_main (libc.so.6)
#24 0x0000000000481416 _start (postgres)
```

### PR DESCRIPTION
**Pull request by mkindahl**
When doing a migrate of table data to a hypertable during a call of
create_hypertable, any error, including an interrupt signal, would cause the signal handling to
call `CopyFromErrorCallback` which would read garbage data because a
heap scan descriptor is read as if it was a `CopyState` structure.

This commit fixes that by not adding a new context to the error context
stack when migrating data.

Fixes #1651

### CODE REVIEW

**Comment by mkindahl** [comment]
> Tested locally and it fixes the crash in #1652 too. However, adding a test will be beneficial to avoid future regressions. May be done as a separate PR.

The crash occurs when you migrate data as part of the call to `create_hypertable` and presses ^C. Not sure how you expect this to be written as a regression test.

> The change related to clang-format seems to be outside this PR and is inconsistent with multinode branch.

Right, will remove.

**Comment by k-rus** [comment]
> > Tested locally and it fixes the crash in #1652 too. However, adding a test will be beneficial to avoid future regressions. May be done as a separate PR.
> 
> The crash occurs when you migrate data as part of the call to `create_hypertable` and presses ^C. Not sure how you expect this to be written as a regression test.

It was discussed during stand-up yesterday that a similar approach to reorder test can be done to break into `create_hypertable` execution and produce an error, e.g., PG interrupt. (haven't checked about PG interrupt).



> Fixes #1652

It fixes the segfault, but not the deadlock. So I suggest to change the formulation, so the issue will not be closed.

Comments about the commit message:
1. The commit fixes segfaults during error reports, which can be caused by different reasons, not only interrupt. So I suggest to generalise the commit message.
2. Inconsistent usage of code highlighting: either no code highlighting (as it doesn't work in in commit messages) or highlight `create_hypertable` too.

File: src/copy.c [hunk 1]
```diff
@@ -233,11 +242,18 @@ timescaledb_CopyFrom(CopyChunkState *ccstate, List *range_table, Hypertable *ht)
...
-	errcallback.callback = CopyFromErrorCallback;
-	errcallback.arg = (void *) ccstate->fromctx.cstate;
-	errcallback.previous = error_context_stack;
-	error_context_stack = &errcallback;
+	/* Set up callback to identify error line number.
+	 *
+	 * It is not necessary to add an entry to the error context stack if we do
+	 * not have a CopyState. In that case, we just use the existing error
+	 * already on the context stack. */
+	if (ccstate->context_type == CCS_CSTATE)
```
Comment (erimatnor) [inline src/copy.c]: Do we need to save the `context_type` in the state? I cannot see it being used anywhere.

Comment (mkindahl) [reply src/copy.c]: Not sure I follow: isn't this the location where it is used?

**Comment by mkindahl** [comment]
> One nit. Also wondering about tests. Realize testing might be difficult due to need to interrupt, but would be good to try to cover this case to protect against future regressions.

I am not sure how to test this since it is caused by triggering an interrupt during execution of the migrate function. We could have some sort of error injection, but since this is not implemented in the code yet, we would have to build such a framework, and I think that is out of scope for this PR.

File: CMakeLists.txt [hunk 2]
```diff
@@ -268,7 +268,7 @@ install(
   FILES ${CMAKE_CURRENT_BINARY_DIR}/${EXT_CONTROL_FILE}
   DESTINATION "${PG_SHAREDIR}/extension")
 
-find_program(CLANG_FORMAT clang-format DOC "The path to clang-format")
+find_program(CLANG_FORMAT clang-format-8 DOC "The path to clang-format")
```
[the remark this answers is not in the document]
Comment (mkindahl) [reply CMakeLists.txt]: This was just for being able to compile locally. Removed it from the commit.

**Comment by mkindahl** [comment]
> > > Tested locally and it fixes the crash in #1652 too. However, adding a test will be beneficial to avoid future regressions. May be done as a separate PR.
> > 
> > 
> > The crash occurs when you migrate data as part of the call to `create_hypertable` and presses ^C. Not sure how you expect this to be written as a regression test.
> 
> It was discussed during stand-up yesterday that a similar approach to reorder test can be done to break into `create_hypertable` execution and produce an error, e.g., PG interrupt. (haven't checked about PG interrupt).
> 
> > Fixes #1652
> 
> It fixes the segfault, but not the deadlock. So I suggest to change the formulation, so the issue will not be closed.

Ah, fixed.

> 
> Comments about the commit message:
> 
>     1. The commit fixes segfaults during error reports, which can be caused by different reasons, not only interrupt. So I suggest to generalise the commit message.

Well... the first paragraph describes what caused the problem, but the second paragraph give the solution. Since it was triggered by a bug that reported issue with interrupt, I think this is sufficient for describing the problem, but I can elaborate on the second paragraph.

> 
>     2. Inconsistent usage of code highlighting: either no code highlighting (as it doesn't work in in commit messages) or highlight `create_hypertable` too.

I follow the practice of not doing it in the header line, but in the body. The markup does not work in the header lines, so there is no point.

**Comment by k-rus** [comment]
> > ```
> > 2. Inconsistent usage of code highlighting: either no code highlighting (as it doesn't work in in commit messages) or highlight `create_hypertable` too.
> > ```
> 
> 
> I follow the practice of not doing it in the header line, but in the body. The markup does not work in the header lines, so there is no point.

I mean the body:

>When doing a migrate of table data to a hypertable during a call of
**create_hypertable**

File: src/copy.c (hunk 1 above)
Comment (mkindahl) [reply src/copy.c]: Since it seemed to be a little unclear, I removed the context_type and instead have two fields: one with the heap scan descriptor and one with the copy state. This will make it type-safe(ish?) and avoid the risk of casting between the two types accidentally.

**Comment by mkindahl** [comment]
> Tested locally and it fixes the crash in #1652 too. However, adding a test will be beneficial to avoid future regressions. May be done as a separate PR.

Added as issue #1679.

**Comment by mkindahl** [comment]
> One nit. Also wondering about tests. Realize testing might be difficult due to need to interrupt, but would be good to try to cover this case to protect against future regressions.

I added a separate issue about this. Would be good to get this fix pushed.
