### PR TITLE
Grant permissions to public for pg_dump to work

### LINKED ISSUE #605: owner of timescaledb schemata is not db owner when DB is created from template1 db
**Environment**
PostgreSQL 9.6 
Timescaledb 0.10.0

**Situation 1 : current situation via templatedb1**
timescalcedb is installed and added to shared_prelaod_libraries 
timescaledb extension is added to the template1 db
we have user myuser (nonsuperuser , createdb privs)

user myuser creates database mydb

timescaledb objects are owned by postgres

       List of schemas
        Name          | Owner  
-----------------------+--------
_timescaledb_cache    | postgres
_timescaledb_catalog  | postgres
_timescaledb_internal | postgres
public                | myuser

Problem:
myuser as owner of db mydb is not able to run pg_dump from his db

pg_dump -d mydb -U myuser fails because of lack of privs on timescaledb schemata

**Situation 2:** 
timescalcedb is installed and added to shared_prelaod_libraries 
timescaledb extension is NOT added to the template1 db
we have user myuser (nonsuperuser , createdb privs)

user myuser creates database mydb

we temporarily grant superuser privs to myuser and let him install the timescaledb extension
\c mydb postgres : alter role myuser with superuser;
\c mydb myuser   : creates extension timescaledb;
\c mydb postgres : alter role myuser with nosuperuser;

timescaledb objects are owned by db-owner myuser 

       List of schemas
        Name          | Owner  
-----------------------+--------
_timescaledb_cache    | myuser
_timescaledb_catalog  | myuser
_timescaledb_internal | myuser
public                | myuser

pg_dump -d mydb -U myuser works as myuser is owner of _timescaledb_xx schemata

So basically creating timescaledb via template1 works, but owner of timescaledb schemata is not the db owner but postgres.
Once the user creates the extension the ownership is ok, but here we have the problem that the user must have superuser privs.

Can anything from your side be done in the extension config that the db-owner of the db in which the extension is created is used as owner of the timescaledb schemata?

This would address the root problem and we can add timescaledb directly to our recommended default extensions inside the template1 db.

### LINKED ISSUE #720: Permisson denied for _timescaledb_cache when exporting with pg_dump
I'm trying to export a database running on Aiven Cloud that has a single hypertable and a few regular tables using `pg_dump` by following the [page in the official docs](https://docs.timescale.com/v1.0/using-timescaledb/backup).

The command I am running looks like this:
`pg_dump 'postgres://avnadmin@<aiven_project>.aivencloud.com:<aiven_port>/<my-db-name>?sslmode=require' -Fc -f my-backup`

The backup command fails with the following messages:
```
pg_dump: [archiver (db)] query failed: ERROR:  permission denied for schema _timescaledb_cache
pg_dump: [archiver (db)] query was: LOCK TABLE _timescaledb_cache.cache_inval_hypertable IN ACCESS SHARE MODE
```

Even after trying to exclude the cache schema, by running the command with `-N`, as so:
`pg_dump 'postgres://avnadmin@<aiven_project>.aivencloud.com:<aiven_port>/<my-db-name>?sslmode=require' -N _timescaledb_cache -Fc -f my-backup`

the same message appears (which seems quite odd). The same error seems to occur on a locally deployed instance, so it doesn't seem to be an Aiven issue. What am I missing?

```
pg_dump (PostgreSQL) 10.3 (Ubuntu 10.3-1.pgdg16.04+1)
PostgreSQL@10.5 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 8.1.1 20180712 (Red Hat 8.1.1-5), 64-bit
timescaledb@0.11.0
```

P.S. In case this has some impact on the code, I'll note that I intentionally exclude the password from the command and enter it separately when prompted to avoid storing it in the command history.

### PR DESCRIPTION
**Pull request by svenklemm**
When timescaledb is installed in template1 and a user with only createdb privileges creates a database, the user won't be able to dump the database because of lacking permissions. This PR grants the missing permissions to PUBLIC for pg_dump to succeed.

Fixes #720 
Fixes #605

### CODE REVIEW

**Comment by RobAtticus** [comment]
1. Seems like you need to add `timescaledb` to the .conf in the image
2. Please squash commits when ready

**Comment by svenklemm** [comment]
yes i saw that, was wondering if i should add it to the generic section or if there is a reason why it isnt there atm

**Comment by RobAtticus** [comment]
I believe the regression tests add a few config vars from `test/postgresql.conf` so it wouldn't need to go in the generic section.

File: sql/pre_install/tables.sql [hunk 1]
```diff
@@ -191,6 +191,8 @@ CREATE TABLE IF NOT EXISTS _timescaledb_catalog.installation_metadata (
 SELECT pg_catalog.pg_extension_config_dump('_timescaledb_catalog.installation_metadata', $$WHERE key='exported_uuid'$$);
 
 -- Set table permissions
+GRANT SELECT ON ALL TABLES IN SCHEMA _timescaledb_cache TO PUBLIC;
 GRANT SELECT ON ALL TABLES IN SCHEMA _timescaledb_catalog TO PUBLIC;
 GRANT SELECT ON ALL TABLES IN SCHEMA _timescaledb_config TO PUBLIC;
-GRANT SELECT ON _timescaledb_internal.bgw_job_stat TO PUBLIC;
+GRANT SELECT ON ALL TABLES IN SCHEMA _timescaledb_internal TO PUBLIC;
```
Comment (amytai) [inline sql/pre_install/tables.sql]: My understanding is that the original reason these tables were not given public permissions is because they are considered "internal" schema, and it's not necessary for users to be able to read them. Is there a way to only grant these privileges right before a `pg_dump`?

Comment (svenklemm) [reply sql/pre_install/tables.sql]: If they are supposed to be truly internal then they shouldnt be marked as dumpable.

Comment (svenklemm) [reply sql/pre_install/tables.sql]: And if they are not marked as dumpable then we need to be able to recreate that state from other information.

File: sql/cache.sql [hunk 2]
```diff
@@ -14,3 +14,7 @@ CREATE TABLE IF NOT EXISTS  _timescaledb_cache.cache_inval_extension();
 -- not actually strictly needed but good for sanity as all tables should be dumped.
 SELECT pg_catalog.pg_extension_config_dump('_timescaledb_cache.cache_inval_hypertable', '');
 SELECT pg_catalog.pg_extension_config_dump('_timescaledb_cache.cache_inval_extension', '');
+
+GRANT SELECT ON TABLE _timescaledb_cache.cache_inval_extension TO PUBLIC;
```
Comment (erimatnor) [inline sql/cache.sql]: As the comment suggests, it is actually not clear why we are dumping these tables to begin with. They are only there for cache invalidation purposes and don't actually have any data (and never should have). 

Seems to me that a better solution is actually to not include these in the dump since the they should already be created by create extension.

Comment (erimatnor) [reply sql/cache.sql]: Btw, it's weird and inconsistent that we need GRANTs  on both the `_timescaledb_cache` schema in `tables.sql` and the explicit tables here. 

If we still want to dump these tables, I think this file should either be moved to `pre_install` or we should create these table in `tables.sql` so that we handle all tables and permissions in one place. I think probably the latter is the most consistent and least error prone.

But, IMHO, like my previous comment suggests, these are internal objects that should not be part of the dump.

Comment (svenklemm) [reply sql/cache.sql]: Even though i didnt register them for dumping anymore, pg_dump is still trying to dump them. So the permissions are indeed required for pg_dump to work.

File: sql/cache.sql [hunk 3]
```diff
@@ -11,6 +11,5 @@ CREATE TABLE IF NOT EXISTS  _timescaledb_cache.cache_inval_hypertable();
 -- etc.
 CREATE TABLE IF NOT EXISTS  _timescaledb_cache.cache_inval_extension();
 
--- not actually strictly needed but good for sanity as all tables should be dumped.
-SELECT pg_catalog.pg_extension_config_dump('_timescaledb_cache.cache_inval_hypertable', '');
-SELECT pg_catalog.pg_extension_config_dump('_timescaledb_cache.cache_inval_extension', '');
+GRANT SELECT ON ALL TABLES IN SCHEMA _timescaledb_cache TO PUBLIC;
```
Comment (erimatnor) [inline sql/cache.sql]: I don't think we need this now, right?

Comment (svenklemm) [reply sql/cache.sql]: Unfortunately we do cause pg_dump is still trying to dump those tables.

File: scripts/test_pg_dump.sh [hunk 4]
```diff
@@ -0,0 +1,22 @@
+#!/bin/bash
```
Comment (cevian) [inline scripts/test_pg_dump.sh]: Actually what does this test do that the pg_dump regression tests doesn't do and why can't we do this in a regression test?

Comment (svenklemm) [reply scripts/test_pg_dump.sh]: the regression test are all sql while this runs commands as different users and runs pg_dump at the end. but i will investigate if it could be part of regression test

File: sql/cache.sql (hunk 3 above)
Comment (svenklemm) [reply sql/cache.sql]: OK pg_dump is not actually dumping those anymore without this but it will still fail cause when pg_dump fetches the list of tables it locks them after this step so they dont disappear to figure out inheritance relationships

  /*
   * Extract data from result and lock dumpable tables.  We do the locking
   * before anything else, to minimize the window wherein a table could
   * disappear under us.
   *
   * Note that we have to save info about all tables here, even when dumping
   * only one, because we don't yet know which tables might be inheritance
   * ancestors of the target table.
   */
result refers to the list of all tables
