### PR TITLE
Fix boundary handling in time types and constraints

### LINKED ISSUE #2292: Dimensional chunk constraints do not handle range boundaries
**Describe the bug**
When chunks are created in a hypertable, dimensional CHECK constraints are added for, e.g., the time slice that the chunk is responsible for. However, when close to the boundaries to the supported range of values in the given dimension, the constraints can overflow, generating an error on INSERT.

**To Reproduce**
```
CREATE TABLE smallint_table (time smallint, device int, temp float);
CREATE TABLE
SELECT create_hypertable('smallint_table', 'time', 'device', 2, chunk_time_interval=>10);
NOTICE:  adding not-null constraint to column "time"
DETAIL:  Time dimensions cannot have NULL values
-[ RECORD 1 ]-----+----------------------------
create_hypertable | (9,public,smallint_table,t)

INSERT INTO smallint_table VALUES ('32765', 1, 2.0);
ERROR:  value "32770" is out of range for type smallint
CONTEXT:  SQL statement " ALTER TABLE _timescaledb_internal._hyper_9_9_chunk ADD CONSTRAINT constraint_17 CHECK ( "time" >= '32760' AND "time" < '32770' ) "
PL/pgSQL function _timescaledb_internal.chunk_constraint_add_table_constraint(_timescaledb_catalog.chunk_constraint) line 42 at EXECUTE
```

**Expected behavior**
An open-ended dimensional constraint should be added for the last (and first) slice of a dimension. In the above example it should be `*"time" >= '32760')` instead of `(`"time" >= '32760' AND "time" < '32770' )`

**Actual behavior**
An error is thrown because the system tries to add a CHECK constraint that is out of range.

### PR DESCRIPTION
**Pull request by erimatnor**
Time types, like date and timestamps, have limits that aren't the same
as the underlying storage type. For instance, while a timestamp is
stored as an `int64` internally, its max supported time value is not
`INT64_MAX`. Instead, `INT64_MAX` represents `+Infinity` and the
actual largest possible timestamp is close to `INT64_MAX` (but not
`INT64_MAX-1` either). The same applies to min values.

Unfortunately, time handling code does not check for these boundaries;
in most cases, overflow handling when, e.g., bucketing, are checked
against the max integer values instead of type-specific boundaries. In
other cases, overflows simply throw errors instead of clamping to the
boundary values, which makes more sense in many situations.

Using integer time suffers from similar issues. To take one example,
simply inserting a valid `smallint` value close to the max into a
table with a `smallint` time column fails:

```
INSERT INTO smallint_table VALUES ('32765', 1, 2.0);
ERROR:  value "32770" is out of range for type smallint
```

This happens because the code that adds dimensional constraints always
checks for overflow against `INT64_MAX` instead of the type-specific
max value. Therefore, it tries to create a chunk constraint that ends
at `32770`, which is outside the allowed range of `smallint`.

The resolve these issues, several time-related utility functions have
been implemented that, e.g., return type-specific range boundaries,
and perform saturated addition and subtraction while clamping to
supported boundaries.

Fixes #2292

### CODE REVIEW

File: src/time_utils.c [hunk 1]
```diff
@@ -125,3 +126,280 @@ ts_time_value_from_arg(Datum arg, Oid argtype, Oid timetype)
...
+ * overflow. Instead, -Infinity is returned (date and timestamps), or the min
+ * integer value.
+ */
+int64
+ts_time_saturating_sub(int64 timeval, int64 interval, Oid timetype)
+{
+	int64 time_min = ts_time_get_min(timetype);
+
+	if (timeval < (time_min + interval))
+		return ts_time_get_nobegin(timetype);
```
Comment (mkindahl) [inline src/time_utils.c:402]: There is no test for this. Suggest to add one.

**Review by mkindahl — APPROVED** [review]

File: src/time_utils.c [hunk 2]
```diff
@@ -125,3 +126,280 @@ ts_time_value_from_arg(Datum arg, Oid argtype, Oid timetype)
...
+
+int64
+ts_time_get_nobegin(Oid timetype)
+{
+	/* In internal time, date is in microseconds while being days natively. So
+	 * it needs special handling. */
+	if (timetype == DATEOID)
+		return DT_NOBEGIN;
+
+	return DatumGetInt64(ts_time_datum_get_nobegin(timetype));
```
Comment (svenklemm) [inline src/time_utils.c:355]: This will segfault on 32-bit

File: src/time_utils.c [hunk 3]
```diff
@@ -125,3 +126,280 @@ ts_time_value_from_arg(Datum arg, Oid argtype, Oid timetype)
...
+
+int64
+ts_time_get_noend(Oid timetype)
+{
+	/* In internal time, date is in microseconds while being days natively. So
+	 * it needs special handling. */
+	if (timetype == DATEOID)
+		return DT_NOEND;
+
+	return DatumGetInt64(ts_time_datum_get_noend(timetype));
```
Comment (svenklemm) [inline src/time_utils.c:366]: This will segfault on 32-bit

**Review by svenklemm — CHANGES_REQUESTED** [review]
Calling DatumGetInt64 on non-Int64 Datums will segfault on 32-bit so you need validate datum datatype and call the apropriate getter

File: src/dimension.c [hunk 4]
```diff
@@ -214,37 +216,34 @@ create_range_datum(FunctionCallInfo fcinfo, DimensionSlice *slice)
 }
 
 static DimensionSlice *
-calculate_open_range_default(Dimension *dim, int64 value)
+calculate_open_range_default(const Dimension *dim, int64 value)
```
[the remark this answers is not in the document]
Comment (erimatnor) [reply src/dimension.c:219]: FWIW, I am doing `const` mostly to signal that pass-by-reference objects aren't modified as a side-effect by the function. Why do you think it is important to mark pass-by-value types as `const`? I guess it might help in the local scope against accidental changes within the function, but this is not what I was going for since it is not a side effect.

[the remark this answers is not in the document]
Comment (mkindahl) [reply src/dimension.c:219]: Marking values as `const` is just convenience to avoid problems, not a deal-breaker. I just think we should be consistent.

File: src/time_utils.h [hunk 5]
```diff
@@ -10,6 +10,57 @@
...
+
+/*
+ * -Infinity and +Infinity in internal (Unix) time.
+ */
+#define TS_TIME_NOBEGIN (PG_INT64_MIN)
+#define TS_TIME_NOEND (PG_INT64_MAX)
+
+#define TS_TIME_IS_INTEGER_TIME(type) (type == INT2OID || type == INT4OID || type == INT8OID)
+#define TS_TIME_DATUM_IS_MIN(timeval, type) (timeval == ts_time_datum_get_min(type))
+#define TS_TIME_DATUM_IS_END(timeval, type) (timeval == ts_time_datum_get_end(type))
```
Comment (mkindahl) [inline src/time_utils.h:41]: This will return true for both for `TS_TIME_DATUM_IS_MIN(ts_time_datum_get_min(INT4OID), INT4OID)` and TS_TIME_DATUM_IS_MIN(ts_time_datum_get_end(INT4OID), INT4OID)`. I think you need to distinguish the two in some manner or risk hard-to-find bugs.

File: src/utils.c [hunk 6]
```diff
@@ -118,14 +119,31 @@ ts_time_value_to_internal(Datum time_val, Oid type_oid)
...
+	{
+		/* Integer time types have no distinction between min, max and
+		 * infinity. We don't want min and max to be turned into infinity for
+		 * these types so check for those values first. */
+		if (TS_TIME_DATUM_IS_MIN(time_val, type_oid))
+			return ts_time_get_min(type_oid);
+
+		if (TS_TIME_DATUM_IS_END(time_val, type_oid))
+			return ts_time_get_end(type_oid);
+	}
```
Comment (mkindahl) [inline src/utils.c:132]: This seems to cover this case, but I am not sure if there are others. It would be a lot safer to ensure that this check would not be necessary, that is, ensure that the "end" and "min" values are distinct also for integer types.

**Review by mkindahl — COMMENTED** [review]
Even though you have checks in place, the fact that the "min" value and the "end" value are identical for integer types would lead to subtle bugs if we make a mistake. It would be a lot better if it was possible to have different values for the negative and positive infinity values also for integers.

File: src/utils.c (hunk 6 above)
Comment (erimatnor) [reply src/utils.c:132]: > This seems to cover this case, but I am not sure if there are others. It would be a lot safer to ensure that this check would not be necessary, that is, ensure that the "end" and "min" values are distinct also for integer types.

That's unfortunately impossible with how things currently work. It would require reducing the supported/legal values in order to reserve space for "infinity".

File: src/time_utils.h (hunk 5 above)
Comment (erimatnor) [reply src/time_utils.h:41]: I don't understand. The latter example will return false. Or am I missing something? Can you explain what you mean?

Comment (mkindahl) [reply src/time_utils.h:41]: Typo, corrected above.

Comment (mkindahl) [reply src/time_utils.h:41]: I was referring to that there are no checks that the wrong version of the "overloaded" value is passed in.

File: src/time_utils.c [hunk 7]
```diff
@@ -125,3 +126,271 @@ ts_time_value_from_arg(Datum arg, Oid argtype, Oid timetype)
...
+			return TimestampTzGetDatum(TS_TIMESTAMP_END);
+		case INT2OID:
+			return Int16GetDatum(PG_INT16_MAX);
+		case INT4OID:
+			return Int32GetDatum(PG_INT32_MAX);
+		case INT8OID:
+			return Int64GetDatum(PG_INT64_MAX);
+		default:
+			break;
+	}
```
[the remark this answers is not in the document]
Comment (erimatnor) [reply src/time_utils.c:217]: I am not changing anything from what was there before. Actually, previously, there was no consistent way of dealing with this at all, which meant it was on a case-by-case basis or not handled; which led to several bugs or simply failures when close to boundaries.

The main issue is that we map several types to a common internal type (int64) and this means we have to have a representation of infinity and valid time ranges while representing in internal time. Since integers don't have a native representation of "end' or +- infinity, we have to represent it in some way. The alternative is special-casing this at every place in the code where we deal with this values, which is IMO a much bigger risk for bugs compared to having a representation in one place that can be covered by tests.

If we were to distinctly represent end and infinity with integer values, we'd have to reduce the range of supported values. I am not sure that is a good idea either (although we did previously fail when trying to insert integers close to max, due to one of the bugs).

File: src/utils.c (hunk 6 above)
Comment (mkindahl) [reply src/utils.c:132]: I realize that, and the PR stays approved so you can push if you want, but I think we need to consider if we can improve this in some way in the future.

File: src/time_utils.h (hunk 5 above)
Comment (erimatnor) [reply src/time_utils.h:41]: I still don't understand. If they are the same, why wouldn't this return true?

I guess this is related to the other discussed issue about distinct values for these definitions?

File: src/utils.c (hunk 6 above)
Comment (erimatnor) [reply src/utils.c:132]: I am open to suggestions, but I don't really see how we can improve without either (1) reserving values, or (2) handling every time type separately at every place in the code that needs it.

File: src/time_utils.h (hunk 5 above)
Comment (mkindahl) [reply src/time_utils.h:41]: Yes, it is related to the other discussion. I do not think both should return true.

File: src/utils.c (hunk 6 above)
Comment (mkindahl) [reply src/utils.c:132]: I think it requires a rewrite. I think this PR improves the current situation, so I think we should handle the necessary changes as a separate PR.

**Review by svenklemm — APPROVED** [review]

File: src/time_utils.c [hunk 8]
```diff
@@ -125,3 +126,271 @@ ts_time_value_from_arg(Datum arg, Oid argtype, Oid timetype)
...
+
+	return ts_time_datum_get_end(coerce_to_time_type(timetype));
+}
+
+Datum
+ts_time_datum_get_nobegin(Oid timetype)
```
[the remark this answers is not in the document]
Comment (erimatnor) [reply src/time_utils.c:247]: I did some tweaks to the code to alleviate some of these concerns if you want to take a look.
