### PR TITLE
Fix non-default tablespaces with constraints

### LINKED ISSUE #6338: [Bug]: Chunk Constraint Add failed If there's a default_tablespace and a DEFERABLE CONSTRAINT
### What type of bug is this?

Unexpected error

### What subsystems and features are affected?

Command processing

### What happened?

What I do:
1. create a default tablespace other than pg_default
2. run the constraint-14.sql regress

What I get:
ERROR : syntax error at or near "USING" at character 180
QUERY: ALTER TABLE _timescaledb_internal._hyper_2_4_chunk ADD CONSTRAINT "4_4_hyper_unique_with_looooooooooooooooooooooo_time" UNIQUE ("time") DEFERABLE INITALLY DEFERRED USING INDEX TABLESPACE space

What I think is the problem:
Accordding to PG's document https://www.postgresql.org/docs/current/sql-altertable.html , the format should be  
```
[ CONSTRAINT constraint_name ]
{ NOT NULL |
  NULL |
  CHECK ( expression ) [ NO INHERIT ] |
  DEFAULT default_expr |
  GENERATED ALWAYS AS ( generation_expr ) STORED |
  GENERATED { ALWAYS | BY DEFAULT } AS IDENTITY [ ( sequence_options ) ] |
  UNIQUE [ NULLS [ NOT ] DISTINCT ] index_parameters |
  PRIMARY KEY index_parameters |
  REFERENCES reftable [ ( refcolumn ) ] [ MATCH FULL | MATCH PARTIAL | MATCH SIMPLE ]
    [ ON DELETE referential_action ] [ ON UPDATE referential_action ] }
[ DEFERRABLE | NOT DEFERRABLE ] [ INITIALLY DEFERRED | INITIALLY IMMEDIATE ]
```
i.e., it should be ALTER TABLE xxx UNIQUE ("time") USING INDEX TABLESPACE space DEFERABLE INITALLY DEFERRED, however, the order is wrong in timescaledb.

When I review the code, it shows that in `_timescaledb_internal.chunk_constraint_add_table_constraint`, it use 
```
SELECT T.spcname INTO indx_tablespace
          FROM pg_constraint C, pg_class I, pg_tablespace T
          WHERE C.oid = constraint_oid AND C.contype IN ('p', 'u') AND I.oid = C.conindid AND I.reltablespace = T.oid;

          def := pg_get_constraintdef(constraint_oid);

          IF indx_tablespace IS NOT NULL THEN
            def := format('%s USING INDEX TABLESPACE %I', def, indx_tablespace);
          END IF;
```
Thus, the `USING INDEX TABLESPACE`  will come after the `DEFERABLE`.

### TimescaleDB version affected

2.5.0

### PostgreSQL version used

14.3

### What operating system did you use?

Centos 7

### What installation method did you use?

Source

### What platform did you run on?

On prem/Self-hosted

### Relevant log output and stack trace

_No response_

### How can we reproduce the bug?

```bash
please refer to the what happened part.
```

### PR DESCRIPTION
**Pull request by nikkhils**
If a hypertable uses a non-default tablespace for its primary or unique constraints with additional DEFERRABLE or INITIALLY DEFERRED characteristics then any chunk creation will fail with syntax error. We now set the tablespace via a separate command for such constraints for the chunks.

Fixes #6338

### CODE REVIEW

**Review by mkindahl — APPROVED** [review]

File: sql/updates/latest-dev.sql [hunk 1]
```diff
@@ -442,3 +442,79 @@ BEGIN
...
+        IF indx_tablespace IS NOT NULL THEN
+            EXECUTE pg_catalog.format(
+                $$ ALTER INDEX %I.%I SET TABLESPACE %I $$,
+                chunk_row.schema_name, chunk_constraint_row.constraint_name, indx_tablespace
+            );
+        END IF;
+
+    END IF;
+END
+$BODY$ SET search_path TO pg_catalog, pg_temp;
```
Comment (fabriziomello) [inline sql/updates/latest-dev.sql:520]: Do we need it in latest-dev.sql?? You're not changing the function signature neither the return type, so don't need it because it will be replaced by CREATE OR REPLACE on chunk_constraint.sql

Comment (nikkhils) [reply sql/updates/latest-dev.sql:520]: @fabriziomello depends on when `chunk_constraint.sql` gets called in the update process. If it's called BEFORE then we do need this.

Comment (nikkhils) [reply sql/updates/latest-dev.sql]: @fabriziomello removed it from latest-dev.sql

**Review by fabriziomello — APPROVED** [review]
