### PR TITLE
Do not use row-by-row fetcher for parameterized plans

### LINKED ISSUE #4695: [Bug]: COPY mode error when filtering a distributed hypertable using array expressions
### What type of bug is this?

Unexpected error

### What subsystems and features are affected?

Distributed hypertable, Multi-node

### What happened?

When attempting to filter a distributed hypertable using array expressions on an array generated by a sub-select the following error is returned.

> ERROR:  unexpected PQresult status 7 when starting COPY mode

This behavior is new as of TimescaleDB version 2.8.0 and is related to #4518.

### TimescaleDB version affected

2.8.0

### PostgreSQL version used

14.5

### What operating system did you use?

macOS Monterey (12.5) x64

### What installation method did you use?

Docker

### What platform did you run on?

On prem/Self-hosted

### Relevant log output and stack trace

```bash
tsdb-access  | 2022-09-12 21:25:47.901 UTC [97] LOG:  00000: statement: SELECT
tsdb-access  |      m.ts, 
tsdb-access  |      m.val 
tsdb-access  |  FROM metric m
tsdb-access  |  WHERE
tsdb-access  |      ARRAY[m.lookup_id] && (SELECT array_agg(l.id)::int[] FROM lookup l WHERE l.key = 'host' AND l.val = 'localhost')
tsdb-access  |      AND m.ts BETWEEN '2021-08-17 00:00:00' AND '2021-08-17 01:00:00'
tsdb-access  |  ORDER BY 1 DESC;
tsdb-access  | 2022-09-12 21:25:47.901 UTC [97] LOCATION:  exec_simple_query, postgres.c:1013
tsdb-access  | 2022-09-12 21:25:47.909 UTC [97] ERROR:  XX000: unexpected PQresult status 7 when starting COPY mode
tsdb-access  | 2022-09-12 21:25:47.909 UTC [97] LOCATION:  row_by_row_fetcher_send_fetch_request, row_by_row_fetcher.c:125
tsdb-access  | 2022-09-12 21:25:47.909 UTC [97] STATEMENT:  SELECT
tsdb-access  |      m.ts, 
tsdb-access  |      m.val 
tsdb-access  |  FROM metric m
tsdb-access  |  WHERE
tsdb-access  |      ARRAY[m.lookup_id] && (SELECT array_agg(l.id)::int[] FROM lookup l WHERE l.key = 'host' AND l.val = 'localhost')
tsdb-access  |      AND m.ts BETWEEN '2021-08-17 00:00:00' AND '2021-08-17 01:00:00'
tsdb-access  |  ORDER BY 1 DESC;
tsdb-access  | 2022-09-12 21:25:47.912 UTC [97] LOG:  00000: statement: SELECT
tsdb-access  |      m.ts, 
tsdb-access  |      m.val 
tsdb-access  |  FROM metric m
tsdb-access  |  WHERE
tsdb-access  |      m.lookup_id = ANY((SELECT array_agg(l.id) FROM lookup l WHERE l.key = 'host' AND l.val = 'localhost')::int[])
tsdb-access  |      AND m.ts BETWEEN '2021-08-17 00:00:00' AND '2021-08-17 01:00:00'
tsdb-access  |  ORDER BY 1 DESC;
tsdb-access  | 2022-09-12 21:25:47.912 UTC [97] LOCATION:  exec_simple_query, postgres.c:1013
tsdb-access  | 2022-09-12 21:25:47.914 UTC [97] ERROR:  XX000: unexpected PQresult status 7 when starting COPY mode
tsdb-access  | 2022-09-12 21:25:47.914 UTC [97] LOCATION:  row_by_row_fetcher_send_fetch_request, row_by_row_fetcher.c:125
tsdb-access  | 2022-09-12 21:25:47.914 UTC [97] STATEMENT:  SELECT
tsdb-access  |      m.ts, 
tsdb-access  |      m.val 
tsdb-access  |  FROM metric m
tsdb-access  |  WHERE
tsdb-access  |      m.lookup_id = ANY((SELECT array_agg(l.id) FROM lookup l WHERE l.key = 'host' AND l.val = 'localhost')::int[])
tsdb-access  |      AND m.ts BETWEEN '2021-08-17 00:00:00' AND '2021-08-17 01:00:00'
tsdb-access  |  ORDER BY 1 DESC;
```

### How can we reproduce the bug?

```bash
Create a regular table.
Create a distributed hypertable.
Insert test data into both tables.
Attempt to select from the distributed hypertable using a WHERE clause that uses the ANY or && operators on a sub-query which generates an array of values.

EXAMPLE

CREATE TABLE lookup (id SERIAL NOT NULL, key TEXT, val TEXT);
CREATE TABLE metric (ts TIMESTAMPTZ NOT NULL, val FLOAT8 NOT NULL, lookup_id INT NOT NULL);
SELECT create_distributed_hypertable('metric', 'ts');

INSERT INTO lookup (key, val) VALUES ('host', 'localhost');
INSERT INTO metric (ts, val, lookup_id) SELECT s.*, 3.14+1, 1
FROM generate_series('2021-08-17 00:00:00'::timestamp, '2021-08-17 00:59:59'::timestamp, '1 s'::interval) s;

SELECT
    m.ts, 
    m.val 
FROM metric m
WHERE
    ARRAY[m.lookup_id] && (SELECT array_agg(l.id)::int[] FROM lookup l WHERE l.key = 'host' AND l.val = 'localhost')
    AND m.ts BETWEEN '2021-08-17 00:00:00' AND '2021-08-17 01:00:00'
ORDER BY 1 DESC;

SELECT
    m.ts, 
    m.val 
FROM metric m
WHERE
    m.lookup_id = ANY((SELECT array_agg(l.id) FROM lookup l WHERE l.key = 'host' AND l.val = 'localhost')::int[])
    AND m.ts BETWEEN '2021-08-17 00:00:00' AND '2021-08-17 01:00:00'
ORDER BY 1 DESC;
```

### PR DESCRIPTION
**Pull request by akuzm**
We have to prepare the data node statement in this case, and COPY queries don't work with prepared statements.

Fixes #4695

### CODE REVIEW

File: tsl/src/fdw/scan_exec.c [hunk 1]
```diff
@@ -152,6 +152,24 @@ create_data_fetcher(ScanState *ss, TsFdwScanState *fsstate)
...
+	if (num_params > 0 && fsstate->planned_fetcher_type == RowByRowFetcherType)
+	{
+		if (ts_guc_remote_data_fetcher == AutoFetcherType)
+		{
+			fsstate->planned_fetcher_type = CursorFetcherType;
+		}
+		else
+		{
+			ereport(ERROR,
+					(errmsg("cannot use row-by-row fetcher because the plan is parameterized")));
```
Comment (mkindahl) [inline tsl/src/fdw/scan_exec.c:169]: I think it would be a good idea to elaborate on this error message and give some information why you print it and provide hints on how to fix the problem. In this case it is because the fetcher type is fixed and cannot be changed, so might be good to provide a hint suggesting to set the planner fetcher type to cursor manually or use the auto fetcher type.

File: tsl/src/remote/row_by_row_fetcher.c [hunk 2]
```diff
@@ -116,15 +116,18 @@ row_by_row_fetcher_send_fetch_request(DataFetcher *df)
 		fetcher->state.open = true;
 
 		PGresult *res = PQgetResult(remote_connection_get_pg_conn(fetcher->state.conn));
-		if (!res)
+		if (res == NULL)
```
Comment (mkindahl) [inline tsl/src/remote/row_by_row_fetcher.c:119]: Nothing you need to change, but I usually try to leave these as they are. Any reasonably experience programmers can easily read both manners of null checking.

File: tsl/test/shared/sql/dist_fetcher_type.sql [hunk 3]
```diff
@@ -136,3 +136,40 @@ WHERE EXISTS (
...
+
+SET timescaledb.remote_data_fetcher = 'rowbyrow';
+SELECT
+    m.ts,
+    m.val
+FROM metric m
+WHERE
+    m.lookup_id = ANY((SELECT array_agg(l.id) FROM lookup l WHERE l.key = 'host' AND l.val = 'localhost')::int[])
+    AND m.ts BETWEEN '2021-08-17 00:00:00' AND '2021-08-17 01:00:00'
+ORDER BY 1 DESC LIMIT 1;
```
Comment (mkindahl) [inline tsl/test/shared/sql/dist_fetcher_type.sql:175]: Nit: Missing newline at end of file.

File: tsl/src/remote/row_by_row_fetcher.c (hunk 2 above)
Comment (akuzm) [reply tsl/src/remote/row_by_row_fetcher.c:119]: Yep, I just copy-pasted the proper error handling from another place.

File: tsl/src/fdw/scan_exec.c (hunk 1 above)
Comment (akuzm) [reply tsl/src/fdw/scan_exec.c]: Added a hint about the GUC.

File: tsl/src/fdw/scan_exec.c [hunk 4]
```diff
@@ -152,6 +152,26 @@ create_data_fetcher(ScanState *ss, TsFdwScanState *fsstate)
...
+		if (ts_guc_remote_data_fetcher == AutoFetcherType)
+		{
+			fsstate->planned_fetcher_type = CursorFetcherType;
+		}
+		else
+		{
+			ereport(ERROR,
+					(errmsg("cannot use row-by-row fetcher because the plan is parameterized"),
+					 errhint("use `set timescaledb.remote_data_fetcher = 'cursor'` to choose the "
+							 "fetcher type automatically")));
```
Comment (mkindahl) [inline tsl/src/fdw/scan_exec.c:171]: You have two options here: either select it explicitly or let TimescaleDB select it. Also, Hints use complete sentences (https://www.postgresql.org/docs/current/error-style-guide.html).

```suggestion
					(errmsg("cannot use row-by-row fetcher because the plan is parameterized"),
					 errhint("Set \"timescaledb.remote_data_fetcher\" to \"cursor\" to explicitly set the fetcher type or use \"auto\" to select the fetcher type automatically.")));
```

**Review by svenklemm — APPROVED** [review]

**Review by mkindahl — APPROVED** [review]
