### PR TITLE
Fix rename for distributed hypertable

### LINKED ISSUE #4491: [Bug]: Rename a distributed hypertable from access node is ok, but data node's hypertable's name is not changed
### What type of bug is this?

Incorrect result

### What subsystems and features are affected?

Data node

### What happened?

hello guys
currently i'm using timescaledb2.7.0+pg14.1. there's a problem occured when i modified a distributed hypertable'name:
 i'm execute an sql: "alter table xxx rename to xxx_1;" in the access node, access node says ok. But when i execute an sql: "select * from  xxx_1;" in a data node, it says that "cannot find relation:xxx_1".
i'm not sure it's a bug or not...

### TimescaleDB version affected

2.7.0

### PostgreSQL version used

14.1

### What operating system did you use?

Centos7.6

### What installation method did you use?

RPM

### What platform did you run on?

On prem/Self-hosted, Other

### Relevant log output and stack trace

```bash
no
```

### How can we reproduce the bug?

```bash
execute an sql: "alter table xxx rename to xxx_1;" in the access node,then execute an sql: "select * from  xxx_1;" in a data node.
```

### PR DESCRIPTION
**Pull request by pmwkaa**
Fix ALTER TABLE RENAME TO command execution on a distributed
hypertable, make sure data node list is set and command is
executed on the data nodes.

Fix #4491

### CODE REVIEW

File: tsl/src/remote/dist_ddl.c [hunk 1]
```diff
@@ -1220,14 +1205,16 @@ dist_ddl_end(EventTriggerData *command)
...
-	 * be updated here as well.
-	 */
+	/* Do delayed block of SET SCHEMA and RENAME commands */
 	if (OidIsValid(dist_ddl_state.relid))
 	{
-		HypertableType type = dist_ddl_state_get_hypertable_type();
+		/* Get hypertable type and update data node list */
+		Cache *hcache = ts_hypertable_cache_pin();
+		Hypertable *ht =
+			ts_hypertable_cache_get_entry(hcache, dist_ddl_state.relid, CACHE_FLAG_NONE);
```
Comment (fabriziomello) [inline tsl/src/remote/dist_ddl.c:1214]:
```suggestion
			ts_hypertable_cache_get_entry(hcache, dist_ddl_state.relid, CACHE_FLAG_NONE);
			Assert(ht != NULL);
```
Nit.

**Review by fabriziomello — APPROVED** [review]

**Review by nikkhils — APPROVED** [review]
LGTM!
