### PR TITLE
Fix FK constraint where index and constraint column order differ

### LINKED ISSUE #7226: [Bug]: Insert into hypertable referenced by foreign key gives error
### What type of bug is this?

Unexpected error

### What subsystems and features are affected?

Partitioning

### What happened?

When creating an auxiliary table and referencing a hypertable using a foreign key, it raises the error "index for constraint not found on chunk".

### TimescaleDB version affected

2.16.0-dev

### PostgreSQL version used

16.4

### What operating system did you use?

Ubuntu 24.04.1 LTS

### What installation method did you use?

Source

### What platform did you run on?

On prem/Self-hosted

### Relevant log output and stack trace

```bash
ERROR:  XX000: index for constraint not found on chunk
DETAIL:  Assertion 'OidIsValid(indexoid)' failed.
LOCATION:  clone_constraint_on_chunk, foreign_key.c:164
```

### How can we reproduce the bug?

```bash
CREATE TABLE conditions (
    time TIMESTAMPTZ NOT NULL,
    device_id INT NOT NULL,
    temperature DOUBLE PRECISION NULL,
    PRIMARY KEY (device_id, time)  -- Composite primary key
);

-- create hypertable
SELECT create_hypertable('conditions', 'time');

CREATE TABLE valid_conditions (
    time TIMESTAMPTZ NOT NULL,
    device_id INT NOT NULL,
    note TEXT,
    CONSTRAINT fk_conditions
    FOREIGN KEY (time, device_id) REFERENCES conditions(time, device_id)  -- Foreign key constraint
);

-- test insert
INSERT INTO conditions (time, device_id, temperature) VALUES
    ('2024-08-29 12:00:00+00', 1, 22.5),
    ('2024-08-29 13:00:00+00', 2, 24.0);
```

### PR DESCRIPTION
**Pull request by svenklemm**
The code for finding the constraint index was expecting the index columns to be in the same order as the constraint columns. This patch changes the check to require all columns be present independent of the order.

Fixes #7226

### CODE REVIEW

File: src/foreign_key.c [hunk 1]
```diff
@@ -555,9 +566,13 @@ get_fk_index(Relation rel, int nkeys, AttrNumber *confkeys)
...
 
-		for (int i = 0; i < nkeys; i++)
+		for (int i = 0; i < nkeys && match; i++)
 		{
-			if (indexrel->rd_index->indkey.values[i] != confkeys[i])
+			/*
+			 * Since ordering of the constraint definition and index definition can differ,
+			 * we need to check that all the columns in the constraint are present in the index
+			 */
+			if (!array_has_member(confkeys, nkeys, indexrel->rd_index->indkey.values[i]))
```
Comment (mkindahl) [inline src/foreign_key.c:575]: This check has quadratic complexity. Even though this is usually not a problem since the number of attributes is small it might be good to consider a check that is not quadratic.

Comment (svenklemm) [reply src/foreign_key.c:575]: This check is not in a critical path and nkeys is capped at 32.

File: src/foreign_key.c [hunk 2]
```diff
@@ -533,6 +533,17 @@ constraint_get_trigger(Oid conoid, Oid *updtrigoid, Oid *deltrigoid)
...
 
+static bool
+array_has_member(const AttrNumber *array, int len, AttrNumber member)
+{
+	for (int i = 0; i < len; i++)
+	{
+		if (array[i] == member)
+			return true;
+	}
+	return false;
```
Comment (akuzm) [inline src/foreign_key.c:544]: Weird that it's not covered, does the test work?

**Review by akuzm — APPROVED** [review]

File: src/foreign_key.c (hunk 2 above)
Comment (svenklemm) [reply src/foreign_key.c:544]: oh i guess i can create some fake indexes to have it hit that path
