### PR TITLE
Fix error in show_chunks

### LINKED ISSUE #6611: [Bug]: `created_before` and `compress_created_before` returns wrong chunks
### What type of bug is this?

Incorrect result

### What subsystems and features are affected?

Command processing, Compression

### Given 
```sql
SELECT 
  chunk_name,
  range_start,
  range_end,
  chunk_creation_time
FROM timescaledb_information.chunks 
WHERE hypertable_name = 'some_table';
```
with results:
```
_hyper_29_216_chunk,
2023-01-24 19:00:00.000 -0500,
2023-01-25 19:00:00.000 -0500,
2024-02-06 00:56:15.539 -0500
```
and now is `2024-02-06 10:56:15.539 -0500`

### Expect
```sql
SELECT show_chunks('some_table', created_before => INTERVAL '1 year');
```
to return nothing

### Actual
```sql
SELECT show_chunks('some_table', created_before => INTERVAL '1 year');
```
 returns
```
_timescaledb_internal._hyper_29_216_chunk
```

### TimescaleDB version affected

2.13.1

### PostgreSQL version used

16.1

### What operating system did you use?

Ubuntu 22.04 x64

### What installation method did you use?

Docker

### What platform did you run on?

On prem/Self-hosted

### Relevant log output and stack trace

_No response_

### How can we reproduce the bug?

```bash
See description.
```

### PR DESCRIPTION
**Pull request by nikkhils**
If "created_after/before" is used with a "time" type partitioning column then show_chunks was not showing appropriate list due to a mismatch in the comparison of the "creation_time" metadata (which is stored as a timestamptz) with the internally converted epoch based input argument value. This is now fixed by not doing the unnecessary conversion into the internal format for cases where it's not needed.

Fixes #6611

### CODE REVIEW

File: src/time_utils.c [hunk 1]
```diff
@@ -149,7 +153,10 @@ ts_time_value_from_arg(Datum arg, Oid argtype, Oid timetype, bool need_now_func)
 				 errmsg("invalid time argument type \"%s\"", format_type_be(argtype)),
 				 errhint("Try casting the argument to \"%s\".", format_type_be(timetype))));
 
-	return ts_time_value_to_internal(arg, argtype);
+	if (convert_internal)
+		return ts_time_value_to_internal(arg, argtype);
+	else
+		return DatumGetInt64(arg);
```
Comment (fabriziomello) [inline src/time_utils.c:159]:
```suggestion

	return DatumGetInt64(arg);
```
Nit.

**Review by fabriziomello — APPROVED** [review]

**Comment by kevcenteno** [comment]
Does this also fix `add_compression_policy()` with the `compress_created_before` argument?

File: .unreleased/fix_6617 [hunk 2]
```diff
@@ -0,0 +1 @@
+Fixes: #6617 Fix error in show_chunks
```
[the remark this answers is not in the document]
Comment (nikkhils) [reply .unreleased/fix_6617]: Done

**Comment by nikkhils** [comment]
> add_compression_policy

@kevcenteno the `add_compression_policy` API takes in an interval only as input. I believe the handling for that is good enough. Did you see any issues with it in your testing?

**Comment by kevcenteno** [comment]
@nikkhils I did see the same issue with the `add_compression_policy` when using the `compress_created_before` argument; that is, chunks were immediately being compressed instead of satisfying the interval:

_Given_
`SELECT add_compression_policy('cpu', compress_created_before => INTERVAL '3 hours');`

_Expect_
A chunk that was created 1 hour ago to _not_ be compressed

_Actual_
The chunk that was created 1 hour ago is compressed

This lead me to discovering the `show_chunks`.  In both cases, I used an interval.

File: src/time_utils.c [hunk 3]
```diff
@@ -149,7 +153,10 @@ ts_time_value_from_arg(Datum arg, Oid argtype, Oid timetype, bool need_now_func)
 				 errmsg("invalid time argument type \"%s\"", format_type_be(argtype)),
 				 errhint("Try casting the argument to \"%s\".", format_type_be(timetype))));
 
-	return ts_time_value_to_internal(arg, argtype);
+	if (convert_internal)
+		return ts_time_value_to_internal(arg, argtype);
+
+	return DatumGetInt64(arg);
```
Comment (akuzm) [inline src/time_utils.c:159]: Can this be moved by caller? Two bool parameters might be a little confusing, especially when the function comment starts with __Get the internal time value from a pseudo-type function argument__, but then it has a parameter that says __actually don't get the internal time value__ :)

**Comment by nikkhils** [comment]
> @nikkhils I did see the same issue with the `add_compression_policy` when using the `compress_created_before` argument; that is, chunks were immediately being compressed without satisfying the interval:
> 
> _Given_ `SELECT add_compression_policy('cpu', compress_created_before => INTERVAL '3 hours');`
> 
> _Expect_ A chunk that was created 1 hour ago to _not_ be compressed
> 
> _Actual_ The chunk that was created 1 hour ago is compressed
> 
> This lead me to discovering the `show_chunks` issue. In both cases, I used an interval.

@kevcenteno right. So, the compression policy job calls `show_chunks` underneath. Since this PR now fixes `show_chunks`, the issue with the `add_compression_policy` is also fixed now. Thanks for the report!

File: src/time_utils.c (hunk 3 above)
Comment (nikkhils) [reply src/time_utils.c:159]: @akuzm Umm, I have added a comment before the start of the function about the "internal" option. Ok, removed the "internal" mention in the first line of the comment for this function :-)

**Comment by kevcenteno** [comment]
@nikkhils I suspected as much, but thank you for verifying!

File: src/time_utils.c (hunk 3 above)
Comment (nikkhils) [reply src/time_utils.c:159]: @akuzm any other comments here?

File: .unreleased/fix_6617 [hunk 4]
```diff
@@ -0,0 +1,2 @@
...
+Thanks: @kevcenteno for reporting this bug
```
[the remark this answers is not in the document]
Comment (nikkhils) [reply .unreleased/fix_6617]: @antekresic a better `Thanks` added now.

File: src/time_utils.c (hunk 3 above)
Comment (nikkhils) [reply src/time_utils.c]: @antekresic @akuzm Ok, I removed the bool flag and added explicit implicit conversions now.

**Review by fabriziomello — APPROVED** [review]

**Review by akuzm — APPROVED** [review]
