### PR TITLE
Remove check from relcache invalidation callback

### LINKED ISSUE #3188: Segmentation Fault when VACUUM FULL pg_class
**Relevant system information:**
 - OS: Red Hat Enterprise Linux 7.8
 - PostgreSQL version 12.4 and 12.5
 - TimescaleDB version 2.2.0
 - Installation method: yum install -y timescaledb-2-postgresql-12

**Describe the bug**
VACUUM FULL pg_class while another process is modifying table will cause a variety errors ranging from segmentation fault, to pg_class corruption.

**To Reproduce**
1)  Install timescaleDB 2
yum install -y timescaledb-2-postgresql-12
2) set up postgres DB
initdb -D 12/data_ts_dump
3) modify 12/data_ts_dump/postgresql.conf
shared_preload_libraries = 'timescaledb'
4) start DB
`pg_ctl -D 12/data_ts_dump -c start`
5) run psql

postgres=# CREATE DATABASE testdb; 
postgres=# \c testdb
testdb=# SELECT format('CREATE TABLE a%s (i BIGINT, i2 BIGINT, t TEXT, t2 TEXT);',i) FROM generate_series(1, 200000) i
\gexec

While above is running connect via another psql session, wait until pg_class is over 20MB then
run ` VACUUM FULL pg_class`  several times.

**Expected behavior**
To not crash or corrupt pg_class

**Actual behavior**
A variety of errors depending on the test run.
Below are a sampling of error messages:

ERROR:  duplicate key value violates unique constraint "pg_class_relname_nsp_index"
DETAIL:  Key (relname, relnamespace)=(pg_class, 11) already exists.

ERROR:  duplicate key value violates unique constraint "pg_class_oid_index"
DETAIL:  Key (oid)=(1259) already exists.

ERROR:  cache lookup failed for relation 523694

ERROR:  could not find tuple for relation 2663

ERROR:  could not find pg_class tuple for index 2662

ERROR:  index "pg_toast_508160_index" already contains data

ERROR:  could not read block 2946 in file "base/16384/280748": read only 0 of 8192 bytes

ERROR:  duplicate key value violates unique constraint "pg_class_oid_index"

server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.
The connection to the server was lost. Attempting reset: Failed.
LOG:  server process (PID 22080) was terminated by signal 11: Segmentation fault

**Additional context**

For complicated reasons we need to do a periodic VACUUM FULL of pg_class.
TimescaleDB v1 was installed on a server and added to shared_preload_libraries in the psql conf, but the extension was not added to any database in the cluster.
At one point running the full vacuum of pg_class caused a seg fault. After that sometimes there was seg fault, sometimes the pg_class table "disappeared" (became an empty table w/ one column named VAR_207310).
Once pg_class got corrupted the corruption was picked up by streaming replicas.
While debugging with the database down we upgraded to timescaleDB v2.
That is when I realized I could consistently reproduce the error and that it stopped when timescaledb was removed from shared_preload_libraries config option.

### PR DESCRIPTION
**Pull request by mfundul**
The timescaledb extension checking code uses syscache lookups to
determine whether the proxy table exists. Doing syscache lookups
inside the invalidation callback context was corrupting the syscache.
For this reason, we remove this callback.

Fixes #3188

### CODE REVIEW

File: src/loader/loader.c [hunk 1]
```diff
@@ -573,7 +565,6 @@ _PG_init(void)
 	 * cannot check for extension here since not inside a transaction yet. Nor
```
Comment (nikkhils) [inline src/loader/loader.c:565]: Please remove the above comment or assimilate it with the following comment.

**Review by nikkhils — APPROVED** [review]
LGTM. With one change for the comment.

**Review by pmwkaa — APPROVED** [review]
Do you think it is possible to make a test case for it?
