### PR TITLE
Repair dimension slice table on update

### LINKED ISSUE #1986: Segfault when drop_chunks with 1.7.1
**Relevant system information:**
 - OS: Centos 7.5
 - PostgreSQL version (output of `postgres --version`): 12.3
 - TimescaleDB version (output of `\dx` in `psql`): 1.7.1
 - Installation method: YUM

**Describe the bug**
After the upgrade of Postgresql (10.9 -> 12.3) and TimescaleDB extension (1.6.1 -> 1.7.1) we see repeated segfaults when executing drop_chunks:

Under GDB the segfault yields:

```
Program received signal SIGSEGV, Segmentation fault.
0x00007fa710efc259 in cmp_slices_by_dimension_id () from /usr/pgsql-12/lib/timescaledb-1.7.1.so
```

**To Reproduce**
Not certain how to reproduce it on any other setup. This happens currently in our staging environment.

**Expected behavior**
Chunks dropped and disk space freed.

**Actual behavior**
Segfault

### PR DESCRIPTION
**Pull request by mkindahl**
In #2514 a a race condition between inserts and `drop_chunks` is fixed
and this commit will repair the dimension slices table by
re-constructing missing dimension slices from the corresponding
constraint expressions.

The commit adds view `_timescaledb_internal.missing_dimension_slices`
that will show dimension slices that are missing from the dimension
slices table. This is intended for debugging and is an internal
function.

Closes #1986

### CODE REVIEW

**Comment by mkindahl** [comment]
This will be pushed after #2514 is pushed to `1.7.x` branch.

**Comment by mkindahl** [comment]
Here is the result of a `pg_regress` test that breaks the tables, repair it, and then checks that no dimension slices are missing.

```
-- Test for the repair tables script in the upgrade directory. This
-- will check that the repair script can successfully repair the
-- dimension slice table.
-- First, create some hypertables to get dimension slices added. We
-- create tables so that we get slices for space- as well as
-- time-dimensions.
\c :TEST_DBNAME :ROLE_SUPERUSER
\ir include/repair-tables.sql
-- This file and its contents are licensed under the Apache License 2.0.
-- Please see the included NOTICE for copyright information and
-- LICENSE-APACHE for a copy of the license.
-- Queries for repairing tables that could have been broken in a
-- previous version. This is split out into a separate file so that we
-- can run tests on it.
-- Recreate missing dimension slices that might be missing due to a
-- bug that is fixed in this release. If the dimension slice table is
-- broken and there are dimension slices missing from the table, we
-- will repair it by:
--
--    1. Finding all chunk constraints that have missing dimension
--       slices and extract the constraint expression from the
--       associated constraint.
--       
--    2. Parse the constraint expression and extract the column name,
--       and upper and lower range values as text.
--       
--    3. Use the column type to construct the range values (UNIX
--       microseconds) from these values.
CREATE PROCEDURE repair_dimension_slice()
LANGUAGE SQL
AS $BODY$
INSERT INTO _timescaledb_catalog.dimension_slice
WITH
   -- All dimension slices that are mentioned in the chunk_constraint
   -- table but are missing from the dimension_slice table.
   missing_slices AS (
      SELECT hypertable_id,
      	     chunk_id,
	     dimension_slice_id,
	     constraint_name,
	     attname AS column_name,
	     pg_get_expr(conbin, conrelid) AS constraint_expr
      FROM _timescaledb_catalog.chunk_constraint cc
      JOIN _timescaledb_catalog.chunk ch ON cc.chunk_id = ch.id
      JOIN pg_constraint ON conname = constraint_name
      JOIN pg_namespace ns ON connamespace = ns.oid AND ns.nspname = ch.schema_name
      JOIN pg_attribute ON attnum = conkey[1] AND attrelid = conrelid
      WHERE
	 dimension_slice_id NOT IN (SELECT id FROM _timescaledb_catalog.dimension_slice)
   ),

  -- Unparsed range start and end for each dimension slice id that
  -- is missing.
   unparsed_missing_slices AS (
      SELECT di.id AS dimension_id,
      	     dimension_slice_id,
             constraint_name,
	     column_type,
	     column_name,
	     (SELECT SUBSTRING(constraint_expr, $$>=\s*'?([\w\d\s:+-]+)'?$$)) AS range_start,
	     (SELECT SUBSTRING(constraint_expr, $$<\s*'?([\w\d\s:+-]+)'?$$)) AS range_end
	FROM missing_slices JOIN _timescaledb_catalog.dimension di USING (hypertable_id, column_name)
   )
SELECT DISTINCT
       dimension_slice_id,
       dimension_id,
       CASE
       WHEN column_type = 'timestamptz'::regtype THEN
       	    _timescaledb_internal.time_to_internal(range_start::timestamptz)
       WHEN column_type = 'timestamp'::regtype THEN
       	    _timescaledb_internal.time_to_internal(range_start::timestamp)
       WHEN column_type = 'date'::regtype THEN
       	    _timescaledb_internal.time_to_internal(range_start::date)
       ELSE
       	    CASE
	    WHEN range_start IS NULL
	    THEN -9223372036854775808
	    ELSE _timescaledb_internal.time_to_internal(range_start::bigint)
	    END
       END AS range_start,
       CASE 
       WHEN column_type = 'timestamptz'::regtype THEN
       	    _timescaledb_internal.time_to_internal(range_end::timestamptz)
       WHEN column_type = 'timestamp'::regtype THEN
       	    _timescaledb_internal.time_to_internal(range_end::timestamp)
       WHEN column_type = 'date'::regtype THEN
       	    _timescaledb_internal.time_to_internal(range_end::date)
       ELSE
       	    CASE WHEN range_end IS NULL
	    THEN 9223372036854775807
	    ELSE _timescaledb_internal.time_to_internal(range_end::bigint)
	    END
       END AS range_end
  FROM unparsed_missing_slices;
$BODY$;
CREATE VIEW missing_slices AS
SELECT DISTINCT
    dimension_slice_id,
    constraint_name,
    attname AS column_name,
    pg_get_expr(conbin, conrelid) AS constraint_expr
FROM
    _timescaledb_catalog.chunk_constraint cc
    JOIN _timescaledb_catalog.chunk ch ON cc.chunk_id = ch.id
    JOIN pg_constraint ON conname = constraint_name
    JOIN pg_namespace ns ON connamespace = ns.oid
        AND ns.nspname = ch.schema_name
    JOIN pg_attribute ON attnum = conkey[1]
        AND attrelid = conrelid
WHERE
    dimension_slice_id NOT IN (SELECT id FROM _timescaledb_catalog.dimension_slice);
CREATE OR REPLACE FUNCTION _timescaledb_internal.time_to_internal(time_val ANYELEMENT)
RETURNS BIGINT AS :MODULE_PATHNAME, 'ts_time_to_internal' LANGUAGE C VOLATILE STRICT;
CREATE TABLE chunk_test_int(time integer, temp float8, tag integer, color integer);
CREATE TABLE chunk_test_timestamptz(time timestamptz, temp float8, tag integer, color integer);
CREATE TABLE chunk_test_timestamp(time timestamp, temp float8, tag integer, color integer);
CREATE TABLE chunk_test_date(time date, temp float8, tag integer, color integer);
SELECT create_hypertable('chunk_test_int', 'time', 'tag', 2, chunk_time_interval => 3);
NOTICE:  adding not-null constraint to column "time"
      create_hypertable      
-----------------------------
 (1,public,chunk_test_int,t)
(1 row)

SELECT create_hypertable('chunk_test_timestamptz', 'time', 'tag', 2, chunk_time_interval => '1 day'::interval);
NOTICE:  adding not-null constraint to column "time"
          create_hypertable          
-------------------------------------
 (2,public,chunk_test_timestamptz,t)
(1 row)

SELECT create_hypertable('chunk_test_timestamp', 'time', 'tag', 2, chunk_time_interval => '1 day'::interval);
NOTICE:  adding not-null constraint to column "time"
         create_hypertable         
-----------------------------------
 (3,public,chunk_test_timestamp,t)
(1 row)

SELECT create_hypertable('chunk_test_date', 'time', 'tag', 2, chunk_time_interval => '1 day'::interval);
NOTICE:  adding not-null constraint to column "time"
      create_hypertable       
------------------------------
 (4,public,chunk_test_date,t)
(1 row)

INSERT INTO chunk_test_int VALUES
       (4, 24.3, 1, 1),
       (4, 24.3, 2, 1),
       (10, 24.3, 2, 1);
INSERT INTO chunk_test_timestamptz VALUES
       ('2020-01-01 10:11:12', 24.3, 1, 1),
       ('2020-01-01 10:11:13', 24.3, 2, 1),
       ('2020-01-02 10:11:14', 24.3, 2, 1);
INSERT INTO chunk_test_timestamp VALUES
       ('2020-01-01 10:11:12', 24.3, 1, 1),
       ('2020-01-01 10:11:13', 24.3, 2, 1),
       ('2020-01-02 10:11:14', 24.3, 2, 1);
INSERT INTO chunk_test_date VALUES
       ('2020-01-01 10:11:12', 24.3, 1, 1),
       ('2020-01-01 10:11:13', 24.3, 2, 1),
       ('2020-01-02 10:11:14', 24.3, 2, 1);
SELECT * FROM _timescaledb_catalog.dimension_slice ORDER BY id;
 id | dimension_id |     range_start      |      range_end      
----+--------------+----------------------+---------------------
  1 |            1 |                    3 |                   6
  2 |            2 | -9223372036854775808 |          1073741823
  3 |            2 |           1073741823 | 9223372036854775807
  4 |            1 |                    9 |                  12
  5 |            3 |     1577836800000000 |    1577923200000000
  6 |            4 | -9223372036854775808 |          1073741823
  7 |            4 |           1073741823 | 9223372036854775807
  8 |            3 |     1577923200000000 |    1578009600000000
  9 |            5 |     1577836800000000 |    1577923200000000
 10 |            6 | -9223372036854775808 |          1073741823
 11 |            6 |           1073741823 | 9223372036854775807
 12 |            5 |     1577923200000000 |    1578009600000000
 13 |            7 |     1577836800000000 |    1577923200000000
 14 |            8 | -9223372036854775808 |          1073741823
 15 |            8 |           1073741823 | 9223372036854775807
 16 |            7 |     1577923200000000 |    1578009600000000
(16 rows)

SELECT DISTINCT
       chunk_id,
       dimension_slice_id,
       format('%I.%I', ht.schema_name, ht.table_name)::regclass AS hypertable,
       constraint_name,
       pg_get_expr(conbin, conrelid) AS constraint_expr
FROM _timescaledb_catalog.chunk_constraint cc,
     _timescaledb_catalog.hypertable ht,
     _timescaledb_catalog.chunk ch,
     LATERAL (
     	     SELECT *
	     FROM pg_constraint JOIN pg_namespace ns ON connamespace = ns.oid
	     WHERE conname = constraint_name
     ) AS con
WHERE ht.id = ch.hypertable_id AND ch.id = cc.chunk_id
ORDER BY chunk_id, dimension_slice_id;
 chunk_id | dimension_slice_id |       hypertable       | constraint_name |                                                                constraint_expr                                                                 
----------+--------------------+------------------------+-----------------+------------------------------------------------------------------------------------------------------------------------------------------------
        1 |                  1 | chunk_test_int         | constraint_1    | (("time" >= 3) AND ("time" < 6))
        1 |                  2 | chunk_test_int         | constraint_2    | (_timescaledb_internal.get_partition_hash(tag) < 1073741823)
        2 |                  1 | chunk_test_int         | constraint_1    | (("time" >= 3) AND ("time" < 6))
        2 |                  3 | chunk_test_int         | constraint_3    | (_timescaledb_internal.get_partition_hash(tag) >= 1073741823)
        3 |                  3 | chunk_test_int         | constraint_3    | (_timescaledb_internal.get_partition_hash(tag) >= 1073741823)
        3 |                  4 | chunk_test_int         | constraint_4    | (("time" >= 9) AND ("time" < 12))
        4 |                  5 | chunk_test_timestamptz | constraint_5    | (("time" >= 'Tue Dec 31 16:00:00 2019 PST'::timestamp with time zone) AND ("time" < 'Wed Jan 01 16:00:00 2020 PST'::timestamp with time zone))
        4 |                  6 | chunk_test_timestamptz | constraint_6    | (_timescaledb_internal.get_partition_hash(tag) < 1073741823)
        5 |                  5 | chunk_test_timestamptz | constraint_5    | (("time" >= 'Tue Dec 31 16:00:00 2019 PST'::timestamp with time zone) AND ("time" < 'Wed Jan 01 16:00:00 2020 PST'::timestamp with time zone))
        5 |                  7 | chunk_test_timestamptz | constraint_7    | (_timescaledb_internal.get_partition_hash(tag) >= 1073741823)
        6 |                  7 | chunk_test_timestamptz | constraint_7    | (_timescaledb_internal.get_partition_hash(tag) >= 1073741823)
        6 |                  8 | chunk_test_timestamptz | constraint_8    | (("time" >= 'Wed Jan 01 16:00:00 2020 PST'::timestamp with time zone) AND ("time" < 'Thu Jan 02 16:00:00 2020 PST'::timestamp with time zone))
        7 |                  9 | chunk_test_timestamp   | constraint_9    | (("time" >= 'Wed Jan 01 00:00:00 2020'::timestamp without time zone) AND ("time" < 'Thu Jan 02 00:00:00 2020'::timestamp without time zone))
        7 |                 10 | chunk_test_timestamp   | constraint_10   | (_timescaledb_internal.get_partition_hash(tag) < 1073741823)
        8 |                  9 | chunk_test_timestamp   | constraint_9    | (("time" >= 'Wed Jan 01 00:00:00 2020'::timestamp without time zone) AND ("time" < 'Thu Jan 02 00:00:00 2020'::timestamp without time zone))
        8 |                 11 | chunk_test_timestamp   | constraint_11   | (_timescaledb_internal.get_partition_hash(tag) >= 1073741823)
        9 |                 11 | chunk_test_timestamp   | constraint_11   | (_timescaledb_internal.get_partition_hash(tag) >= 1073741823)
        9 |                 12 | chunk_test_timestamp   | constraint_12   | (("time" >= 'Thu Jan 02 00:00:00 2020'::timestamp without time zone) AND ("time" < 'Fri Jan 03 00:00:00 2020'::timestamp without time zone))
       10 |                 13 | chunk_test_date        | constraint_13   | (("time" >= '01-01-2020'::date) AND ("time" < '01-02-2020'::date))
       10 |                 14 | chunk_test_date        | constraint_14   | (_timescaledb_internal.get_partition_hash(tag) < 1073741823)
       11 |                 13 | chunk_test_date        | constraint_13   | (("time" >= '01-01-2020'::date) AND ("time" < '01-02-2020'::date))
       11 |                 15 | chunk_test_date        | constraint_15   | (_timescaledb_internal.get_partition_hash(tag) >= 1073741823)
       12 |                 15 | chunk_test_date        | constraint_15   | (_timescaledb_internal.get_partition_hash(tag) >= 1073741823)
       12 |                 16 | chunk_test_date        | constraint_16   | (("time" >= '01-02-2020'::date) AND ("time" < '01-03-2020'::date))
(24 rows)

-- Now, we remove some dimension slices to break the table. For that
-- we need to remove some dimension slices. We could remove all, but
-- that will not tell us if the script works even for partial results
-- (which is the normal case), so we remove partial ones. In
-- particular, we have some slices that are referenced by several
-- chunks and we want to check that these works as well.
--
-- For each dimension, we will drop it, list the missing slices,
-- repair the table, and check that the repair added the missing
-- slices. Each test is preceeded by a comment to make diffs clearly
-- distinguishable from each others.
-- To drop rows from dimension_slice table, we need to remove some
-- constraints.
ALTER TABLE _timescaledb_catalog.chunk_constraint
      DROP CONSTRAINT chunk_constraint_dimension_slice_id_fkey;
-- Drop slice 1
DELETE FROM _timescaledb_catalog.dimension_slice WHERE id = 1;
SELECT * FROM missing_slices;
 dimension_slice_id | constraint_name | column_name |         constraint_expr          
--------------------+-----------------+-------------+----------------------------------
                  1 | constraint_1    | time        | (("time" >= 3) AND ("time" < 6))
(1 row)

CALL repair_dimension_slice();
SELECT * FROM missing_slices;
 dimension_slice_id | constraint_name | column_name | constraint_expr 
--------------------+-----------------+-------------+-----------------
(0 rows)

-- Drop slice 2
DELETE FROM _timescaledb_catalog.dimension_slice WHERE id = 2;
SELECT * FROM missing_slices;
 dimension_slice_id | constraint_name | column_name |                       constraint_expr                        
--------------------+-----------------+-------------+--------------------------------------------------------------
                  2 | constraint_2    | tag         | (_timescaledb_internal.get_partition_hash(tag) < 1073741823)
(1 row)

CALL repair_dimension_slice();
SELECT * FROM missing_slices;
 dimension_slice_id | constraint_name | column_name | constraint_expr 
--------------------+-----------------+-------------+-----------------
(0 rows)

-- Drop slice 3
DELETE FROM _timescaledb_catalog.dimension_slice WHERE id = 3;
SELECT * FROM missing_slices;
 dimension_slice_id | constraint_name | column_name |                        constraint_expr                        
--------------------+-----------------+-------------+---------------------------------------------------------------
                  3 | constraint_3    | tag         | (_timescaledb_internal.get_partition_hash(tag) >= 1073741823)
(1 row)

CALL repair_dimension_slice();
SELECT * FROM missing_slices;
 dimension_slice_id | constraint_name | column_name | constraint_expr 
--------------------+-----------------+-------------+-----------------
(0 rows)

-- Drop slice 4
DELETE FROM _timescaledb_catalog.dimension_slice WHERE id = 4;
SELECT * FROM missing_slices;
 dimension_slice_id | constraint_name | column_name |          constraint_expr          
--------------------+-----------------+-------------+-----------------------------------
                  4 | constraint_4    | time        | (("time" >= 9) AND ("time" < 12))
(1 row)

CALL repair_dimension_slice();
SELECT * FROM missing_slices;
 dimension_slice_id | constraint_name | column_name | constraint_expr 
--------------------+-----------------+-------------+-----------------
(0 rows)

-- Drop slice 5
DELETE FROM _timescaledb_catalog.dimension_slice WHERE id = 5;
SELECT * FROM missing_slices;
 dimension_slice_id | constraint_name | column_name |                                                                constraint_expr                                                                 
--------------------+-----------------+-------------+------------------------------------------------------------------------------------------------------------------------------------------------
                  5 | constraint_5    | time        | (("time" >= 'Tue Dec 31 16:00:00 2019 PST'::timestamp with time zone) AND ("time" < 'Wed Jan 01 16:00:00 2020 PST'::timestamp with time zone))
(1 row)

CALL repair_dimension_slice();
SELECT * FROM missing_slices;
 dimension_slice_id | constraint_name | column_name | constraint_expr 
--------------------+-----------------+-------------+-----------------
(0 rows)

-- Drop slice 6
DELETE FROM _timescaledb_catalog.dimension_slice WHERE id = 6;
SELECT * FROM missing_slices;
 dimension_slice_id | constraint_name | column_name |                       constraint_expr                        
--------------------+-----------------+-------------+--------------------------------------------------------------
                  6 | constraint_6    | tag         | (_timescaledb_internal.get_partition_hash(tag) < 1073741823)
(1 row)

CALL repair_dimension_slice();
SELECT * FROM missing_slices;
 dimension_slice_id | constraint_name | column_name | constraint_expr 
--------------------+-----------------+-------------+-----------------
(0 rows)

-- Drop slice 7
DELETE FROM _timescaledb_catalog.dimension_slice WHERE id = 7;
SELECT * FROM missing_slices;
 dimension_slice_id | constraint_name | column_name |                        constraint_expr                        
--------------------+-----------------+-------------+---------------------------------------------------------------
                  7 | constraint_7    | tag         | (_timescaledb_internal.get_partition_hash(tag) >= 1073741823)
(1 row)

CALL repair_dimension_slice();
SELECT * FROM missing_slices;
 dimension_slice_id | constraint_name | column_name | constraint_expr 
--------------------+-----------------+-------------+-----------------
(0 rows)

-- Drop slice 8
DELETE FROM _timescaledb_catalog.dimension_slice WHERE id = 8;
SELECT * FROM missing_slices;
 dimension_slice_id | constraint_name | column_name |                                                                constraint_expr                                                                 
--------------------+-----------------+-------------+------------------------------------------------------------------------------------------------------------------------------------------------
                  8 | constraint_8    | time        | (("time" >= 'Wed Jan 01 16:00:00 2020 PST'::timestamp with time zone) AND ("time" < 'Thu Jan 02 16:00:00 2020 PST'::timestamp with time zone))
(1 row)

CALL repair_dimension_slice();
SELECT * FROM missing_slices;
 dimension_slice_id | constraint_name | column_name | constraint_expr 
--------------------+-----------------+-------------+-----------------
(0 rows)

-- Drop slice 9
DELETE FROM _timescaledb_catalog.dimension_slice WHERE id = 9;
SELECT * FROM missing_slices;
 dimension_slice_id | constraint_name | column_name |                                                               constraint_expr                                                                
--------------------+-----------------+-------------+----------------------------------------------------------------------------------------------------------------------------------------------
                  9 | constraint_9    | time        | (("time" >= 'Wed Jan 01 00:00:00 2020'::timestamp without time zone) AND ("time" < 'Thu Jan 02 00:00:00 2020'::timestamp without time zone))
(1 row)

CALL repair_dimension_slice();
SELECT * FROM missing_slices;
 dimension_slice_id | constraint_name | column_name | constraint_expr 
--------------------+-----------------+-------------+-----------------
(0 rows)

-- Drop slice 10
DELETE FROM _timescaledb_catalog.dimension_slice WHERE id = 10;
SELECT * FROM missing_slices;
 dimension_slice_id | constraint_name | column_name |                       constraint_expr                        
--------------------+-----------------+-------------+--------------------------------------------------------------
                 10 | constraint_10   | tag         | (_timescaledb_internal.get_partition_hash(tag) < 1073741823)
(1 row)

CALL repair_dimension_slice();
SELECT * FROM missing_slices;
 dimension_slice_id | constraint_name | column_name | constraint_expr 
--------------------+-----------------+-------------+-----------------
(0 rows)

-- Drop slice 11
DELETE FROM _timescaledb_catalog.dimension_slice WHERE id = 11;
SELECT * FROM missing_slices;
 dimension_slice_id | constraint_name | column_name |                        constraint_expr                        
--------------------+-----------------+-------------+---------------------------------------------------------------
                 11 | constraint_11   | tag         | (_timescaledb_internal.get_partition_hash(tag) >= 1073741823)
(1 row)

CALL repair_dimension_slice();
SELECT * FROM missing_slices;
 dimension_slice_id | constraint_name | column_name | constraint_expr 
--------------------+-----------------+-------------+-----------------
(0 rows)

-- Drop slice 12
DELETE FROM _timescaledb_catalog.dimension_slice WHERE id = 12;
SELECT * FROM missing_slices;
 dimension_slice_id | constraint_name | column_name |                                                               constraint_expr                                                                
--------------------+-----------------+-------------+----------------------------------------------------------------------------------------------------------------------------------------------
                 12 | constraint_12   | time        | (("time" >= 'Thu Jan 02 00:00:00 2020'::timestamp without time zone) AND ("time" < 'Fri Jan 03 00:00:00 2020'::timestamp without time zone))
(1 row)

CALL repair_dimension_slice();
SELECT * FROM missing_slices;
 dimension_slice_id | constraint_name | column_name | constraint_expr 
--------------------+-----------------+-------------+-----------------
(0 rows)

-- Drop slice 13
DELETE FROM _timescaledb_catalog.dimension_slice WHERE id = 13;
SELECT * FROM missing_slices;
 dimension_slice_id | constraint_name | column_name |                          constraint_expr                           
--------------------+-----------------+-------------+--------------------------------------------------------------------
                 13 | constraint_13   | time        | (("time" >= '01-01-2020'::date) AND ("time" < '01-02-2020'::date))
(1 row)

CALL repair_dimension_slice();
SELECT * FROM missing_slices;
 dimension_slice_id | constraint_name | column_name | constraint_expr 
--------------------+-----------------+-------------+-----------------
(0 rows)

-- Drop slice 14
DELETE FROM _timescaledb_catalog.dimension_slice WHERE id = 14;
SELECT * FROM missing_slices;
 dimension_slice_id | constraint_name | column_name |                       constraint_expr                        
--------------------+-----------------+-------------+--------------------------------------------------------------
                 14 | constraint_14   | tag         | (_timescaledb_internal.get_partition_hash(tag) < 1073741823)
(1 row)

CALL repair_dimension_slice();
SELECT * FROM missing_slices;
 dimension_slice_id | constraint_name | column_name | constraint_expr 
--------------------+-----------------+-------------+-----------------
(0 rows)

-- Drop slice 15
DELETE FROM _timescaledb_catalog.dimension_slice WHERE id = 15;
SELECT * FROM missing_slices;
 dimension_slice_id | constraint_name | column_name |                        constraint_expr                        
--------------------+-----------------+-------------+---------------------------------------------------------------
                 15 | constraint_15   | tag         | (_timescaledb_internal.get_partition_hash(tag) >= 1073741823)
(1 row)

CALL repair_dimension_slice();
SELECT * FROM missing_slices;
 dimension_slice_id | constraint_name | column_name | constraint_expr 
--------------------+-----------------+-------------+-----------------
(0 rows)

-- Drop slice 16
DELETE FROM _timescaledb_catalog.dimension_slice WHERE id = 16;
SELECT * FROM missing_slices;
 dimension_slice_id | constraint_name | column_name |                          constraint_expr                           
--------------------+-----------------+-------------+--------------------------------------------------------------------
                 16 | constraint_16   | time        | (("time" >= '01-02-2020'::date) AND ("time" < '01-03-2020'::date))
(1 row)

CALL repair_dimension_slice();
SELECT * FROM missing_slices;
 dimension_slice_id | constraint_name | column_name | constraint_expr 
--------------------+-----------------+-------------+-----------------
(0 rows)
```

File: sql/views_internal.sql [hunk 1]
```diff
@@ -0,0 +1,28 @@
+-- This file and its contents are licensed under the Apache License 2.0.
+-- Please see the included NOTICE for copyright information and
+-- LICENSE-APACHE for a copy of the license.
+
+CREATE VIEW _timescaledb_internal.missing_dimension_slices AS
```
Comment (svenklemm) [inline sql/views_internal.sql:5]: Hmm not a fan of this view as this is ideally always empty, cant we pull in the integrity check function from update test and make it part of this

Comment (erimatnor) [reply sql/views_internal.sql:5]: I agree with Sven. I don't think we should have permanent views for conditions that shouldn't occur, in particular those that should be fixed. If our fixes do the job, this view will serve no purpose.

Comment (mkindahl) [reply sql/views_internal.sql]: It was mostly intended for debugging and support purposes (either to detect or exclude a problem), which is why it was placed in the internal namespace and I think the best views for this purpose are the ones that are empty. However, if people feel it is not useful, then I'll remove it.

**Comment by svenklemm** [comment]
why is this against 1.7.x branch

**Comment by mkindahl** [comment]
> why is this against 1.7.x branch

Because it is a fix for #2514 that should be on the 1.7.x branch since #1986 is reported on the 1.7 branch.

**Comment by svenklemm** [comment]
> > why is this against 1.7.x branch
> 
> Because it is a fix for #2514 that should be on the 1.7.x branch since #1986 is reported on the 1.7 branch.

But #2514 is against master so this should be against master too.

**Comment by mkindahl** [comment]
> > > why is this against 1.7.x branch
> > 
> > 
> > Because it is a fix for #2514 that should be on the 1.7.x branch since #1986 is reported on the 1.7 branch.
> 
> But #2514 is against master so this should be against master too.

I expected him to backport it, but I have already created one on top of master.

**Review by svenklemm — APPROVED** [review]

**Review by erimatnor — APPROVED** [review]
Approving, although it would be nice to add the update test where we try to mess up an version of the database to see that it gets repaired during the upgrade.

**Comment by k-rus** [comment]
@mkindahl Can you point which PR or fix needs to be merged before this PR is merged?

**Comment by mkindahl** [comment]
> @mkindahl Can you point which PR or fix needs to be merged before this PR is merged?

@k-rus This is mentioned in one of the earliest comments. It is #2514.
