### PR TITLE
Fix TRUNCATE error as non-owner on hypertable

### LINKED ISSUE #4183: [Bug]: Only hypertable owner can TRUNCATE a hypertable
### What type of bug is this?

Unexpected error

### What subsystems and features are affected?

Command processing

### What happened?

If I create a hypertable, and grant `TRUNCATE` on it to a non-owner, that user is not able to truncate the table.

Truncation fails with `ERROR:  must be owner of hypertable "test_hypertable"`

### TimescaleDB version affected

2.6.0

### PostgreSQL version used

14

### What operating system did you use?

Ubuntu

### What installation method did you use?

Docker

### What platform did you run on?

On prem/Self-hosted

### Relevant log output and stack trace

```bash
CREATE ROLE owner WITH LOGIN;
CREATE ROLE
CREATE ROLE truncator WITH LOGIN;
CREATE ROLE
CREATE DATABASE test OWNER owner;
CREATE DATABASE
CREATE TABLE test_plain_table ();
CREATE TABLE
GRANT TRUNCATE ON test_plain_table TO truncator;
GRANT
CREATE TABLE test_hypertable (time TIMESTAMP WITHOUT TIME ZONE NOT NULL, value DOUBLE PRECISION);
CREATE TABLE
GRANT TRUNCATE ON test_hypertable TO truncator;
GRANT
SELECT create_hypertable('test_hypertable', 'time');
      create_hypertable
------------------------------
 (1,public,test_hypertable,t)
(1 row)

TRUNCATE TABLE test_plain_table;
TRUNCATE TABLE
TRUNCATE TABLE test_hypertable;
ERROR:  must be owner of hypertable "test_hypertable"
```

### How can we reproduce the bug?

```bash
#!/usr/bin/env bash

set -o errexit
set -o pipefail

docker run -d --name db --rm -e POSTGRES_PASSWORD=password timescale/timescaledb-ha:pg14-latest

trap "docker stop db" EXIT

until docker exec -ti db psql -h localhost -p 5432 -U postgres -c 'SELECT 1;' 1>/dev/null 2>&1
do
    echo -n '.'
    sleep 1
done
echo ''

docker exec -t db psql -a -U postgres \
    -c 'CREATE ROLE owner WITH LOGIN;' \
    -c 'CREATE ROLE truncator WITH LOGIN;' \
    -c 'CREATE DATABASE test OWNER owner;'

docker exec -t db psql -a -U owner -d test \
    -c 'CREATE TABLE test_plain_table ();' \
    -c 'GRANT TRUNCATE ON test_plain_table TO truncator;' \
    -c 'CREATE TABLE test_hypertable (time TIMESTAMP WITHOUT TIME ZONE NOT NULL, value DOUBLE PRECISION);' \
    -c 'GRANT TRUNCATE ON test_hypertable TO truncator;' \
    -c "SELECT create_hypertable('test_hypertable', 'time');"

docker exec -t db psql -a -U truncator -d test \
    -c 'TRUNCATE TABLE test_plain_table;' \
    -c 'TRUNCATE TABLE test_hypertable;'
```

### PR DESCRIPTION
**Pull request by konskov**
Stop throwing error "must be owner of hypertable" when a user with
TRUNCATE privilege on the hypertable attempts to TRUNCATE.

Previously we had a check that required TRUNCATE to only be
performed by the table owner, not taking into account the user's
TRUNCATE privilege, which is sufficient to allow this operation.

Fixes #4183

### CODE REVIEW

File: test/sql/truncate.sql [hunk 1]
```diff
@@ -110,3 +110,24 @@ TRUNCATE "two_Partitions", truncate_normal CASCADE;
...
+CREATE EXTENSION timescaledb;
+RESET client_min_messages;
+
+\c test_trunc_ht owner
+CREATE TABLE test_hypertable (time TIMESTAMP WITHOUT TIME ZONE NOT NULL, value DOUBLE PRECISION);
+GRANT TRUNCATE ON test_hypertable TO truncator;
+SELECT create_hypertable('test_hypertable', 'time');
+
+\c test_trunc_ht truncator;
+TRUNCATE TABLE test_hypertable;
```
Comment (mfundul) [inline test/sql/truncate.sql:133]: You should add a newline character here.

File: test/sql/truncate.sql [hunk 2]
```diff
@@ -110,3 +110,24 @@ TRUNCATE "two_Partitions", truncate_normal CASCADE;
...
+CREATE ROLE owner WITH LOGIN;
+CREATE ROLE truncator WITH LOGIN;
+CREATE DATABASE test_trunc_ht OWNER owner;
+
+\c test_trunc_ht :ROLE_SUPERUSER
+SET client_min_messages = ERROR;
+CREATE EXTENSION timescaledb;
+RESET client_min_messages;
+
+\c test_trunc_ht owner
```
Comment (mfundul) [inline test/sql/truncate.sql:127]:
```suggestion
\c test_trunc_ht truncator
```

**Review by mfundul — CHANGES_REQUESTED** [review]
You should have a test case where `TRUNCATE` fails before granting permission to `truncator`, which would then succeed.

**Review by mfundul — APPROVED** [review]

**Review by fabriziomello — APPROVED** [review]
