### PR TITLE
Fix update triggers issue caused by decompression

### LINKED ISSUE #6858: [Bug]: Before Update trigger on hypertable make updates fail
### What type of bug is this?

Crash, Unexpected error

### What subsystems and features are affected?

Query executor

### What happened?

We are currently in the process of integrating TimescaleDB into our system, and for the most part, everything has been functioning smoothly. However, we have encountered a bug within our hypertable that appears to be triggered by specific data scenarios, and despite our efforts, we have been unable to pinpoint the root cause.

Since we are not sure about the root cause of it, and the problem does not appear always which makes us think that is a data-dependant issue, we provide here a dump of an small example which consistently reproduces the issue. The dump file is in the next zip: [dump_file.zip](https://github.com/timescale/timescaledb/files/15095995/dump_file.zip)

The issue revolves around a hypertable containing multiple fields, including a crucial column named `effective_date_time` which serves as our partition key. Additionally, we utilise standard columns such as created_at and modified_at, with the latter being updated whenever modifications occur to ensure data accuracy. To achieve this, we implemented a `before_update` trigger on the hypertable, as illustrated below:

```
CREATE OR REPLACE FUNCTION update_modified_at() 
RETURNS TRIGGER 
LANGUAGE PLPGSQL AS $$ 
BEGIN 
    NEW.modified_at = NOW(); 
    RETURN NEW; 
END; $$
```

Just in case, see here the create trigger command:

```
CREATE TRIGGER example_table_before_update_sync_modified_at
BEFORE UPDATE ON example_table
FOR EACH ROW
EXECUTE PROCEDURE update_modified_at();
```

Unfortunately, we have recently encountered an error message when attempting updates on this table, specifically: 
`[2024-04-24 11:15:03] [XX000] ERROR: attempted to lock invisible tuple.`

For instance, the update query provided below triggers this error:

```
UPDATE example_table SET measurement = measurement + 2
WHERE example_table.effective_date_time >= '2020-01-01T00:00:00'::timestamp AT TIME ZONE 'UTC'
```

Our investigations into this error led us to references such as [ https://postgrespro.com/list/thread-id/1502244]( https://postgrespro.com/list/thread-id/1502244), alluding to its resolution in Postgres version 15. Despite performing maintenance tasks such as VACUUM and REINDEX on the `example_table` table, as well as restarting our Postgres instance, we have been unable to resolve the issue.

### TimescaleDB version affected

2.14.2

### PostgreSQL version used

15.6

### What operating system did you use?

Redhat 8 and image timescale/timescaledb:2.14.0-pg15 

### What installation method did you use?

Docker

### What platform did you run on?

Amazon Web Services (AWS), Other

### Relevant log output and stack trace

```bash
2024-04-24 14:31:37.863 UTC [87] ERROR:  attempted to lock invisible tuple
2024-04-24 14:31:37.863 UTC [87] STATEMENT:  UPDATE example_table SET measurement = measurement + 2
        WHERE example_table.effective_date_time >= '2020-01-01T00:00:00'::timestamp AT TIME ZONE 'UTC'
```

### How can we reproduce the bug?

```bash
Create an empty database and a user with access right on it and load the dump as following:


psql --quiet --username USERNAME --database DATABASE < dump.sql
```

The dump.sql file content is attached above: [dump_file.zip](https://github.com/timescale/timescaledb/files/15095995/dump_file.zip) 

Then try to run the next query:

```
UPDATE example_table SET measurement = measurement + 2
WHERE example_table.effective_date_time >= '2020-01-01T00:00:00'::timestamp AT TIME ZONE 'UTC'
```
```

### PR DESCRIPTION
**Pull request by antekresic**
Update triggers were broken due to snapshot manipulation and usage of dynamic snapshots for scanning tuples. Using a static snapshot guarantees we cannot see tuples that would be invisible during an update trigger.

Fixes #6858

### CODE REVIEW

File: tsl/test/sql/compression_update_delete.sql [hunk 1]
```diff
@@ -1511,3 +1511,56 @@ BEGIN; EXPLAIN (costs off, timing off, summary off, analyze) DELETE FROM test_co
...
+CREATE TRIGGER update_trigger_test__before_update_sync_modified_at
+BEFORE UPDATE ON update_trigger_test
+FOR EACH ROW
+EXECUTE PROCEDURE update_modified_at_test();
+
+INSERT INTO update_trigger_test
+SELECT 'f2ca7073-1395-5770-8378-7d0339804580', '2024-04-16 04:50:00+02',
+1100.00, '2024-04-23 11:56:38.494095+02' FROM generate_series(1,2500,1) c;
+
+VACUUM FULL update_trigger_test;
```
Comment (fabriziomello) [inline tsl/test/sql/compression_update_delete.sql:1542]: Why `VACUUM FULL` here??

**Review by svenklemm — APPROVED** [review]

**Comment by akuzm** [comment]
@antekresic can you explain more about this issue? What row was it trying to lock that was invisible?

File: src/nodes/hypertable_modify.c [hunk 2]
```diff
@@ -747,18 +747,22 @@ ExecModifyTable(CustomScanState *cs_node, PlanState *pstate)
...
 			 */
 			ht_state->snapshot = estate->es_snapshot;
-			/* use current transaction snapshot */
-			estate->es_snapshot = GetTransactionSnapshot();
+
 			CommandCounterIncrement();
+			/* use a static copy of current transaction snapshot
+			 * this needs to be a copy so we don't read trigger updates
+			 */
+			estate->es_snapshot = RegisterSnapshot(GetTransactionSnapshot());
```
Comment (akuzm) [inline src/nodes/hypertable_modify.c:765]: Do you mean that on the next update cycle, we're trying the tuple previously modified by the BEFORE UPDATE trigger on the previous cycle? And the "invisible" error happens in `GetTupleForTrigger()`?

I think normally the new tuples from the previous update cycles are skipped because they are `TM_SelfModified` and not `TM_Invisible`. This is determined by `HeapTupleSatisfiesUpdate`. So if we're getting `TM_Invisible`, this means we either forgot to update the command counter after modifying the tuple, or we're taken the new snapshot with command counter higher than the previous update. I guess here it's the latter and you prevent that by making a copy of the snapshot?

Comment (akuzm) [reply src/nodes/hypertable_modify.c:765]: Normally the `es_snapshot` is initialized with a registered snapshot copy (`standard_ExecutorStart`), so this is probably correct. But I wonder if we should re-take the snapshot like this at all? Not sure if it's a standard practice. Normally the update code uses the `es_output_cid` as the current command id for locking the tuples, so maybe just incrementing the output cid after decompression would be enough?

Comment (akuzm) [reply src/nodes/hypertable_modify.c:765]: > But I wonder if we should re-take the snapshot like this at all? Not sure if it's a standard practice. Normally the update code uses the es_output_cid as the current command id for locking the tuples, so maybe just incrementing the output cid after decompression would be enough?

Looks like we must do it, otherwise we won't see the tuples we've decompressed. The `es_output_cid` comes into play later, when we do see the tuples and want to determine if they are updated by us.

File: src/nodes/hypertable_modify.c [hunk 3]
```diff
@@ -747,18 +747,22 @@ ExecModifyTable(CustomScanState *cs_node, PlanState *pstate)
 	 */
 	if ((operation == CMD_DELETE || operation == CMD_UPDATE) && !ht_state->comp_chunks_processed)
 	{
-		if (ts_cm_functions->decompress_target_segments)
+		/* Modify snapshot only if something got decompressed */
+		if (ts_cm_functions->decompress_target_segments &&
+			ts_cm_functions->decompress_target_segments(ht_state))
```
Comment (akuzm) [inline src/nodes/hypertable_modify.c:752]: OK, I think I managed to understand the rationale why we add the `RegisterSnapshot` below. But what about this new check, why is it needed? Your test passes without this change with just the `RegisterSnapshot`. I also double-checked that it fails w/o the `RegisterSnapshot`.

Comment (akuzm) [reply src/nodes/hypertable_modify.c:752]: It seems reasonable to me that the update process should work even if we just increment command counter and take the new snapshot unconditionally always.

Comment (akuzm) [reply src/nodes/hypertable_modify.c:752]: Well, that seems to be the correct way to work with the snapshots there, so maybe we should instead apply it unconditionally? If you only apply it under some complicated conditions, the bugs will be more difficult to find. E.g. now it looks like we should add isolation tests with both REPEATABLE READ and READ COMMITTED to test the `result == TM_Deleted && !IsolationUsesXactSnapshot()` code path. We still have to do the potentially problematic snapshot operations in some cases, and if we add more conditions to invoke them, I would say it doesn't really improve the things.

**Review by akuzm — APPROVED** [review]
Let's try to add an isolation test for the "deleted" branch.
