### PR TITLE
Make errors and messages conform to style guide

### LINKED ISSUE #1790: Give better error hint for continuous_aggs/create.c
Hi,

When creating ContAgg

https://github.com/timescale/timescaledb/blob/2ae4592930be1df40cc490bfc6e8ef3f18af6b4e/tsl/src/continuous_aggs/create.c#L1095

It will call `contain_mutable_functions`. Which if user need to create a view `GROUP BY` something like `date_trunc('hour', some_non_partition_timestamp_column)`  will fail with

> ERROR: only immutable functions are supported for continuous aggregate query
> HINT: Many time-based function that are not immutable have immutable alternatives that require specifying the timezone explicitly

The solution is to specify `date_trunc('hour', some_non_partition_timestamp_column AT TIME ZONE 'GMT')`

Maybe we can write that down in the error message to help user a little bit? This will save a lot of time googling "how to specify timezone in postgres".

My related discussions:

https://timescaledb.slack.com/archives/C4GT3N90X/p1585720471168700
https://timescaledb.slack.com/archives/C4GT3N90X/p1585654002138700

### LINKED ISSUE #2364: Cleanup log messages
There are a number of log message that aren't following the error style guide. In particular, these are common deviations from the recommendations:

* Use lower-case for first letter of main error and never end with period
* Keep the main error message short
* Start detail and error messages with upper-cased first letter and end the message with a period.
* Double-quote object names

It would be nice to fix this for the next major release.

### PR DESCRIPTION
**Pull request by erimatnor**
Errors and messages are overhauled to conform to the official
PostgreSQL style guide. In particular, the following things from the
guide has been given special attention:

* Correct capitalization of first letter: capitalize only for hints,
  and detail messages.
* Correct handling of periods at the end of messages (should be elided
  for primary message, but not detail and hint messages).
* The primary message should be short, factual, and avoid reference to
  implementation details such as specific function names.

Some messages have also been reworded for clarity and to better
conform with the last bullet above (short primary message). In other
cases, messages have been updated to fix references to, e.g., function
parameters that used the wrong parameter name.

Closes #2364
Fixes #1790

### CODE REVIEW

File: src/bgw/job_stat.c [hunk 1]
```diff
@@ -207,7 +207,7 @@ calculate_next_start_on_failure(TimestampTz finish_time, int consecutive_failure
 	MemoryContext oldctx;
 	if (!IS_VALID_TIMESTAMP(finish_time))
 	{
-		elog(LOG, "calculate_next_start_on_failure, got bad finish_time");
+		elog(LOG, "%s: invalid finish time", __func__);
```
Comment (pmwkaa) [inline src/bgw/job_stat.c:210]: it is slightly unsync with the message below, Is that a debug message? Should this be an error?

File: src/loader/bgw_message_queue.c [hunk 2]
```diff
@@ -155,7 +155,7 @@ queue_reset_reader(MessageQueue *queue)
 				(errcode(ERRCODE_INTERNAL_ERROR),
```
Comment (pmwkaa) [inline src/loader/bgw_message_queue.c:155]: Thats kinda odd to ask user to provide a bug report only in one place. I wonder if it makes to make a function out of it and reuse it in different places.

Also I am thinking maybe it is possible to hook into PostgreSQL event handler in order to catch `SIGSEGV` and maybe automatically show or collect stack trace (maybe event send it to us, since we have telemetry already) WDYT?

File: tsl/src/continuous_aggs/create.c [hunk 3]
```diff
@@ -1577,8 +1571,7 @@ fixup_userview_query_tlist(Query *userquery, List *tlist_aliases)
 
 		if (alist_item != NULL)
 			ereport(ERROR,
-					(errcode(ERRCODE_SYNTAX_ERROR),
-					 errmsg("too many column names were specified")));
+					(errcode(ERRCODE_SYNTAX_ERROR), errmsg("too many column names specified")));
```
Comment (pmwkaa) [inline tsl/src/continuous_aggs/create.c:1574]: Maybe use feature unsupported errcode?

File: tsl/src/hypertable.c [hunk 4]
```diff
@@ -223,7 +223,7 @@ update_replication_factor(Hypertable *const ht, const int32 replication_factor_i
 	if (list_length(ht->data_nodes) < replication_factor)
 		ereport(ERROR,
 				(errcode(ERRCODE_INVALID_PARAMETER_VALUE),
```
Comment (pmwkaa) [inline tsl/src/hypertable.c:225]: Also can be used `TS_INSUFFICIENT_NUM_DATA_NODES`, but likely current is more accurate

File: tsl/src/data_node.c [hunk 5]
```diff
@@ -842,7 +842,7 @@ data_node_attach(PG_FUNCTION_ARGS)
 		ereport(ERROR,
 				(errcode(ERRCODE_INVALID_PARAMETER_VALUE),
```
Comment (pmwkaa) [inline tsl/src/data_node.c:843]: This might be not accurate, since this is likely not related to the parameter value. I wonder if it makes sense to use an existing or add a new errcode related to limits

**Review by pmwkaa — APPROVED** [review]
Looks good, couple of notes

File: tsl/src/bgw_policy/retention_api.c [hunk 6]
```diff
@@ -285,29 +287,27 @@ policy_retention_remove(PG_FUNCTION_ARGS)
...
 		else
 		{
 			ContinuousAgg *ca = ts_continuous_agg_find_by_relid(table_oid);
 
 			if (!ca)
 				ereport(ERROR,
 						(errcode(ERRCODE_UNDEFINED_OBJECT),
-						 errmsg("no hypertable or continuous aggregate by the name \"%s\" exists",
-								view_name)));
+						 errmsg(" \"%s\" is not a hypertable or continuous aggregate", view_name)));
```
Comment (mkindahl) [inline tsl/src/bgw_policy/retention_api.c:310]:
```suggestion
						 errmsg("\"%s\" is not a hypertable or continuous aggregate", view_name)));
```

File: tsl/src/compression/create.c [hunk 7]
```diff
@@ -172,9 +172,8 @@ compresscolinfo_add_metadata_columns(CompressColInfo *cc, Relation uncompressed_
 			if (!OidIsValid(type->lt_opr))
 				ereport(ERROR,
 						(errcode(ERRCODE_UNDEFINED_FUNCTION),
-						 errmsg("invalid order by column type: could not identify an less-than "
-								"operator for type %s",
-								format_type_be(attr->atttypid))));
+						 errmsg("invalid order by column type %s", format_type_be(attr->atttypid)),
```
Comment (mkindahl) [inline tsl/src/compression/create.c:175]:
```suggestion
						 errmsg("invalid order-by column type %s", format_type_be(attr->atttypid)),
```

File: tsl/src/bgw_policy/compression_api.c [hunk 8]
```diff
@@ -257,24 +254,30 @@ policy_compression_remove(PG_FUNCTION_ARGS)
...
 
-	int ht_id = ts_hypertable_relid_to_id(hypertable_oid);
+	ht = ts_hypertable_cache_get_cache_and_entry(hypertable_oid, CACHE_FLAG_NONE, &hcache);
 
 	List *jobs = ts_bgw_job_find_by_proc_and_hypertable_id(POLICY_COMPRESSION_PROC_NAME,
 														   INTERNAL_SCHEMA_NAME,
-														   ht_id);
+														   ht->fd.id);
+
+	ts_cache_release(hcache);
```
Comment (mkindahl) [inline tsl/src/bgw_policy/compression_api.c:268]: I am not sure why you rewrite this code. `ts_hypertable_relid_to_id` does exactly this and the hypertable structure is not used later. You only increase the risk of mistakes when maintaining this code.

File: tsl/src/bgw_policy/reorder_api.c [hunk 9]
```diff
@@ -245,31 +244,30 @@ policy_reorder_remove(PG_FUNCTION_ARGS)
...
 	PreventCommandIfReadOnly("remove_reorder_policy()");
 
-	int ht_id = ts_hypertable_relid_to_id(hypertable_oid);
+	ht = ts_hypertable_cache_get_cache_and_entry(hypertable_oid, CACHE_FLAG_NONE, &hcache);
 
 	List *jobs = ts_bgw_job_find_by_proc_and_hypertable_id(POLICY_REORDER_PROC_NAME,
 														   INTERNAL_SCHEMA_NAME,
-														   ht_id);
+														   ht->fd.id);
+	ts_cache_release(hcache);
```
Comment (mkindahl) [inline tsl/src/bgw_policy/reorder_api.c:257]: Same here. Seems like you only increase the risk of making a mistake when maintaining the code.

File: tsl/src/bgw_policy/retention_api.c [hunk 10]
```diff
@@ -285,29 +287,27 @@ policy_retention_remove(PG_FUNCTION_ARGS)
...
+		const char *view_name = get_rel_name(table_oid);
+
 		if (!view_name)
-		{
 			ereport(ERROR,
 					(errcode(ERRCODE_UNDEFINED_OBJECT),
-					 errmsg("OID %d does not refer to a hypertable or continuous aggregate",
-							table_oid)));
-		}
+					 errmsg("invalid hypertable or continuous aggregate")));
```
Comment (mkindahl) [inline tsl/src/bgw_policy/retention_api.c:302]: Well... this is not really an invalid hypertable or cagg because it's neither. It's the OID that is invalid because it doesn't refer to a hypertable or cagg.

Suggest something like:
```suggestion
					 errmsg("relation is not a hypertable or continuous aggregate")));
```

or

```suggestion
					 errmsg("not a hypertable or continuous aggregate")));
```

File: tsl/src/bgw_policy/retention_api.c (hunk 6 above)
Comment (mkindahl) [inline tsl/src/bgw_policy/retention_api.c:310]:
```suggestion
						 errmsg("relation \"%s\" is not a hypertable or continuous aggregate", view_name)));
```

File: tsl/src/compression/create.c (hunk 7 above)
Comment (mkindahl) [inline tsl/src/compression/create.c:175]:
```suggestion
						 errmsg("invalid order-by column type %s", format_type_be(attr->atttypid)),
```

File: tsl/src/data_node.c [hunk 11]
```diff
@@ -137,7 +137,7 @@ data_node_get_foreign_server(const char *node_name, AclMode mode, bool fail_on_a
 	if (node_name == NULL)
 		ereport(ERROR,
 				(errcode(ERRCODE_INVALID_PARAMETER_VALUE),
-				 errmsg("invalid node_name: cannot be NULL")));
+				 errmsg("invalid data node name: cannot be NULL")));
```
Comment (mkindahl) [inline tsl/src/data_node.c:140]:
```suggestion
				 errmsg("data node name cannot be NULL")));
```

File: tsl/src/hypertable.c [hunk 12]
```diff
@@ -162,9 +162,9 @@ hypertable_get_and_validate_data_nodes(ArrayType *nodearr)
 
 	if (num_data_nodes == 0)
 		ereport(ERROR,
-				(errcode(ERRCODE_TS_NO_DATA_NODES),
+				(errcode(ERRCODE_TS_INSUFFICIENT_NUM_DATA_NODES),
 				 errmsg("no data nodes can be assigned to the hypertable"),
-				 errhint("Add data nodes using the add_data_node() function.")));
+				 errhint("Add new data nodes to the database.")));
```
Comment (mkindahl) [inline tsl/src/hypertable.c:167]: Nit. Using "new" suggest that there are already old data nodes, which is not the case.
```suggestion
				 errhint("Add data nodes to the database.")));
```

File: tsl/src/bgw_policy/reorder_api.c (hunk 9 above)
Comment (erimatnor) [reply tsl/src/bgw_policy/reorder_api.c:258]: Explained above.

File: tsl/src/bgw_policy/compression_api.c (hunk 8 above)
Comment (mkindahl) [reply tsl/src/bgw_policy/compression_api.c:267]: It feels strange to have a function that returns `InvalidOid` so I would expect that `ts_hypertable_relid_to_id` to be fixed instead (and generate an error). However, that is a minor issue. I agree that we should not have several different locations to generate similar errors from since that leads to inconsistent error messages.

File: tsl/src/bgw_policy/compression_api.c [hunk 13]
```diff
@@ -106,25 +106,20 @@ policy_compression_add(PG_FUNCTION_ARGS)
...
-	PreventCommandIfReadOnly("add_compression_policy()");
-
 	Hypertable *hypertable;
 	Cache *hcache;
 	Dimension *dim;
-	ts_hypertable_permissions_check(ht_oid, GetUserId());
-	Oid owner_id = ts_hypertable_permissions_check(ht_oid, GetUserId());
+	Oid owner_id;
+
+	PreventCommandIfReadOnly("add_compression_policy()");
```
Comment (mkindahl) [inline tsl/src/bgw_policy/compression_api.c:114]: To avoid inconsistencies between the function name and this text:
```suggestion
	PreventCommandIfReadOnly(get_func_name(FC_FN_OID(fcinfo)));
```

File: tsl/src/bgw_policy/reorder_api.c [hunk 14]
```diff
@@ -125,35 +126,30 @@ policy_reorder_add(PG_FUNCTION_ARGS)
...
-	Hypertable *ht = ts_hypertable_get_by_id(hypertable_id);
+	Cache *hcache;
+	Hypertable *ht;
+	int32 hypertable_id;
 	Oid partitioning_type;
 	Oid owner_id;
 	List *jobs;
 
-	owner_id = ts_hypertable_permissions_check(ht_oid, GetUserId());
+	PreventCommandIfReadOnly("add_reorder_policy()");
```
Comment (mkindahl) [inline tsl/src/bgw_policy/reorder_api.c:140]:
```suggestion
	PreventCommandIfReadOnly(get_func_name(FC_FN_OID(fcinfo)));
```

File: tsl/src/bgw_policy/reorder_api.c [hunk 15]
```diff
@@ -183,9 +181,11 @@ policy_reorder_add(PG_FUNCTION_ARGS)
...
 		{
-			elog(WARNING,
-				 "could not add reorder policy due to existing policy on hypertable with different "
-				 "arguments");
+			ereport(WARNING,
+					(errmsg("reorder policy already exists for hypertable \"%s\"",
+							get_rel_name(ht_oid)),
+					 errdetail("A policy already exists with different arguments."),
+					 errhint("Remove the existing policy before adding a new one.")));
 			PG_RETURN_INT32(-1);
```
Comment (mkindahl) [inline tsl/src/bgw_policy/reorder_api.c:189]: AIUI, this is an error from the user perspective (we're not "proceeding with the operation") so maybe this should be an error? I would argue that the add policy function should not have an implicit "if not exists" last, which this is equivalent to.

File: tsl/src/bgw_policy/retention_api.c [hunk 16]
```diff
@@ -193,16 +193,18 @@ policy_retention_add(PG_FUNCTION_ARGS)
...
 			ts_cache_release(hcache);
-			elog(WARNING,
-				 "could not add retention policy due to existing policy on hypertable with "
-				 "different arguments");
+			ereport(WARNING,
+					(errmsg("retention policy already exists for hypertable \"%s\"",
+							get_rel_name(ht_oid)),
+					 errdetail("A policy already exists with different arguments."),
+					 errhint("Remove the existing policy before adding a new one.")));
 			PG_RETURN_INT32(-1);
```
Comment (mkindahl) [inline tsl/src/bgw_policy/retention_api.c:208]: IMHO, I think this should be an error similar to how you get an error if you try to create a function that already exists. The execution "aborts" after this anyway (which is what I assume that the "return -1" is about), so an error is appropriate.

**Review by mkindahl — COMMENTED** [review]
Looks good.

One minor thing, but then there are two warnings that I think should be errors. Please have a look at it.

File: tsl/src/bgw_policy/compression_api.c (hunk 8 above)
Comment (erimatnor) [reply tsl/src/bgw_policy/compression_api.c:267]: I agree, but that's a separate refactoring, IMO.

File: tsl/src/bgw_policy/reorder_api.c (hunk 14 above)
Comment (erimatnor) [reply tsl/src/bgw_policy/reorder_api.c:140]: This looks like a good idea, but let's do as a separate refactoring since the situation is similar in many places and doesn't change the current errors.

File: tsl/src/bgw_policy/reorder_api.c (hunk 15 above)
Comment (erimatnor) [reply tsl/src/bgw_policy/reorder_api.c:189]: I agree, but had this discussion previously with @gayyappan and there was some disagreement. I don't remember the arguments, but it might have something to do with always giving back a return value. Let's leave behavioral changes for another PR unless there's a bug.

Comment (mkindahl) [reply tsl/src/bgw_policy/reorder_api.c:189]: Ok. If it is a contention point we should not take it as part of this PR.

**Review by mkindahl — APPROVED** [review]
